BattleFrontier_Lounge8_MapScripts::
	.byte 0

BattleFrontier_Lounge8_EventScript_Man::
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman::
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy::
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds:
	.string "Một HLV cần gì à...\p"
	.string "Kiến thức... Chiến thuật... May mắn... Gan\n"
	.string "dạ... Tinh thần... Dũng khí... Và năng\l"
	.string "lực...\p"
	.string "Chà, tôi có đủ mọi thứ rồi! Tòa nhà nào\n"
	.string "tôi cũng sẽ bất khả chiến bại!\p"
	.string "Hả? POKéMON? Là gì thế?$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains:
	.string "Bạn có biết FRONTIER BRAINS không?\p"
	.string "Đó là cách SCOTT gọi bảy HLV đặc\n"
	.string "biệt điều hành bảy cơ sở tại BATTLE\l"
	.string "FRONTIER.$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling:
	.string "Ở BATTLE TOWER, một chị lớn tuổi hơn\n"
	.string "bảo tôi rất có năng khiếu chiến đấu!\p"
	.string "Tôi thích POKéMON CONTESTS hơn!\p"
	.string "Nhưng tôi lại chẳng giỏi các cuộc thi!\p"
	.string "Có vẻ có năng khiếu và yêu thích một\n"
	.string "việc không phải là một.$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global BattleFrontier_Lounge8_Text_WhatATrainerNeeds
	.global BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains
	.global BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling
@ END GENERATED LOCALIZATION EXPORTS
