VerdanturfTown_BattleTentCorridor_MapScripts::
	map_script MAP_SCRIPT_ON_FRAME_TABLE, VerdanturfTown_BattleTentCorridor_OnFrame
	.byte 0

VerdanturfTown_BattleTentCorridor_OnFrame:
	map_script_2 VAR_TEMP_0, 0, VerdanturfTown_BattleTentCorridor_EventScript_EnterCorridor
	.2byte 0

VerdanturfTown_BattleTentCorridor_EventScript_EnterCorridor::
	lockall
	setvar VAR_TEMP_0, 1
	applymovement LOCALID_VERDANTURF_TENT_CORRIDOR_ATTENDANT, VerdanturfTown_BattleTentCorridor_Movement_WalkToDoor
	applymovement LOCALID_PLAYER, VerdanturfTown_BattleTentCorridor_Movement_WalkToDoor
	waitmovement 0
	opendoor 2, 1
	waitdooranim
	applymovement LOCALID_VERDANTURF_TENT_CORRIDOR_ATTENDANT, VerdanturfTown_BattleTentCorridor_Movement_AttendantEnterDoor
	applymovement LOCALID_PLAYER, VerdanturfTown_BattleTentCorridor_Movement_PlayerEnterDoor
	waitmovement 0
	closedoor 2, 1
	waitdooranim
	setvar VAR_0x8006, 0
	warp MAP_VERDANTURF_TOWN_BATTLE_TENT_BATTLE_ROOM, 6, 5
	waitstate
	releaseall
	end

VerdanturfTown_BattleTentCorridor_Movement_WalkToDoor:
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

VerdanturfTown_BattleTentCorridor_Movement_PlayerEnterDoor:
	walk_up
VerdanturfTown_BattleTentCorridor_Movement_AttendantEnterDoor:
	walk_up
	set_invisible
	step_end


@ Leftover text from when this was a Contest Hall in R/S
@ Unused
VerdanturfTown_ContestHall_Text_WhichContestYouEntering:
	.string "Bạn sẽ tham gia cuộc thi nào? Muốn nghe\n"
	.string "một lời khuyên không?\p"
	.string "Trong bất kỳ cuộc thi nào, chẳng hạn\n"
	.string "CUTE CONTEST, tôi nghĩ vòng đầu không\l"
	.string "chỉ chấm mỗi độ đáng yêu.\p"
	.string "Bạn cần tìm cách nuôi dưỡng POKéMON\n"
	.string "tốt hơn nữa.$"

@ Unused
VerdanturfTown_ContestHall_Text_RaisedMonToBeCute:
	.string "Tôi đã nuôi POKéMON của mình thật đáng\n"
	.string "yêu.\p"
	.string "Rồi tôi phát hiện có thể cho POKéMON\n"
	.string "tham gia cuộc thi về độ đáng yêu!\p"
	.string "Tôi thật mừng vì đã hết lòng yêu\n"
	.string "thương và chăm sóc POKéMON...$"

@ Unused
VerdanturfTown_ContestHall_Text_MyMonRules:
	.string "POKéMON của tôi là số một!\p"
	.string "Nó ngầu, mạnh mẽ mà vẫn xinh đẹp, đáng\n"
	.string "yêu và thông minh. Hoàn hảo!\p"
	.string "Tôi sẽ giành chiến thắng trong mọi\n"
	.string "cuộc thi luôn.$"

@ Unused
VerdanturfTown_ContestHall_Text_NormalRankStage:
	.string "POKéMON CONTESTS NORMAL RANK STAGE!$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global VerdanturfTown_ContestHall_Text_WhichContestYouEntering
	.global VerdanturfTown_ContestHall_Text_RaisedMonToBeCute
	.global VerdanturfTown_ContestHall_Text_MyMonRules
	.global VerdanturfTown_ContestHall_Text_NormalRankStage
@ END GENERATED LOCALIZATION EXPORTS
