gText_ApprenticeChallenge0::
	.string "Ờm, tôi là đệ tử số {STR_VAR_2}\n"
	.string "của {STR_VAR_1}. Sụt sịt... Căng\l"
	.string "thẳng quá, tôi chịu không nổi...$"

gText_ApprenticeChallenge1::
	.string "Tôi là đệ tử số {STR_VAR_2} của\n"
	.string "{STR_VAR_1}! Xông lên nào!$"

gText_ApprenticeChallenge2::
	.string "Tôi là đệ tử số {STR_VAR_2} của\n"
	.string "{STR_VAR_1}! Hãy nhận lời thách\l"
	.string "đấu của tôi!$"

gText_ApprenticeChallenge3::
	.string "Ờm... Tôi là đệ tử số {STR_VAR_2}\n"
	.string "của {STR_VAR_1}... Bạn nghĩ\l"
	.string "người như tôi có thể thắng sao?$"

gText_ApprenticeChallenge4::
	.string "Tôi là đệ tử số {STR_VAR_2} của\n"
	.string "{STR_VAR_1}! Tôi cho phép bạn\l"
	.string "thách đấu với tôi!$"

gText_ApprenticeChallenge5::
	.string "Tôi bận tối mắt tối mũi, nhưng tình cờ\n"
	.string "cũng là đệ tử số {STR_VAR_2} của\l"
	.string "{STR_VAR_1}.$"

gText_ApprenticeChallenge6::
	.string "Tôi là đệ tử số {STR_VAR_2} của\n"
	.string "{STR_VAR_1}. Rất vui được gặp\l"
	.string "bạn!$"

gText_ApprenticeChallenge7::
	.string "Tôi phụng sự với tư cách đệ tử số\n"
	.string "{STR_VAR_2} của\l"
	.string "{STR_VAR_1}. Tôi xin phép bắt đầu\l"
	.string "chứ?$"

gText_ApprenticeChallenge8::
	.string "Á! Tôi là đệ tử số {STR_VAR_2}\n"
	.string "của {STR_VAR_1}! Tôi sẽ cố hết\l"
	.string "sức!$"

gText_ApprenticeChallenge9::
	.string "Yeehaw! Tôi là đệ tử số\n"
	.string "{STR_VAR_2} của\l"
	.string "{STR_VAR_1}! Vào thế đi!$"

gText_ApprenticeChallenge10::
	.string "Tôi là đệ tử thứ 1.000 của\n"
	.string "{STR_VAR_1}! Thật ra, tôi là số\l"
	.string "{STR_VAR_2}! Bắt đầu nhé!$"

gText_ApprenticeChallenge11::
	.string "Phải, tôi là đệ tử số {STR_VAR_2}\n"
	.string "của {STR_VAR_1}! Quẩy tưng bừng\l"
	.string "nào!$"

gText_ApprenticeChallenge12::
	.string "Yippee-yahoo! Tôi chính là đệ tử số\n"
	.string "{STR_VAR_2} của\l"
	.string "{STR_VAR_1} đấy!$"

gText_ApprenticeChallenge13::
	.string "Khụ! Tôi là đệ tử số {STR_VAR_2}\n"
	.string "của {STR_VAR_1}. Rất vui được\l"
	.string "gặp bạn! Khụ!$"

gText_ApprenticeChallenge14::
	.string "Căng thẳng quá... Tôi là đệ tử số\n"
	.string "{STR_VAR_2} của\l"
	.string "{STR_VAR_1}.$"

gText_ApprenticeChallenge15::
	.string "Tôi là đệ tử số {STR_VAR_2} của\n"
	.string "{STR_VAR_1}, và tôi nói thật đấy.$"

gText_ApprenticePleaseTeach0::
	.string "Bạn là... {PLAYER} sao? Ôi! Sụt sịt...\n"
	.string "hức...\p"
	.string "Ôi! X-xin lỗi... Tôi căng thẳng quá nên\n"
	.string "không cầm được nước mắt...\p"
	.string "Tôi là {STR_VAR_1}, và tôi thật\n"
	.string "sự rất ngưỡng mộ bạn, {PLAYER}.\p"
	.string "Tôi... Tôi luôn mơ một ngày được gặp bạn\n"
	.string "và hỏi bạn về POKéMON.\p"
	.string "Xin bạn, xin bạn đấy, {PLAYER}! Hãy\n"
	.string "dạy tôi về POKéMON!$"

gText_ApprenticeRejectTeaching0::
	.string "Ôi... N-nhưng... Sụt sịt... Oaaaaa!\p"
	.string "Xin bạn! Tôi van bạn đấy, làm ơn!$"

gText_ApprenticeWhichLevelMode0::
	.string "Thật sao? Bạn đồng ý ư? Tuyệt quá!\n"
	.string "Đỉnh quá! Auuuu!\p"
	.string "Ôi... Tôi xin lỗi... Tôi vui quá nên lại khóc\n"
	.string "mất rồi...\p"
	.string "Ờm... Vậy hãy cho tôi biết nhé! Chuyện\n"
	.string "này liên quan đến BATTLE TOWER.\p"
	.string "Level 50 hay Open Level sẽ phù hợp với\n"
	.string "tôi hơn?$"

gText_ApprenticeLevelModeThanks0::
	.string "{STR_VAR_1} sao? Oaaaaa!\p"
	.string "Ôi! Tôi xin lỗi! Bạn đã chọn cấp độ giúp\n"
	.string "tôi, khiến tôi vui đến phát khóc...\p"
	.string "Sụt sịt... Cảm ơn bạn rất nhiều! Lần sau\n"
	.string "hãy nói chuyện với tôi nữa nhé!$"

gText_ApprenticePleaseTeach1::
	.string "Chà! Bạn là {PLAYER}, đúng không? Bạn\n"
	.string "mạnh kinh khủng, đúng không?\p"
	.string "Tôi là {STR_VAR_1}! Tôi vừa trở\n"
	.string "thành HLV!\p"
	.string "Xin bạn đấy, {PLAYER}! Bạn có thể làm\n"
	.string "thầy và dạy tôi thật nhiều điều về việc\l"
	.string "trở thành HLV không?$"

gText_ApprenticeRejectTeaching1::
	.string "Ôi, tại sao chứ? Xin bạn mà? Đi mà? Làm\n"
	.string "thầy của tôi nhé, xin bạn đấy!$"

gText_ApprenticeWhichLevelMode1::
	.string "Hoan hô! Tuyệt quá!\p"
	.string "Điều đầu tiên tôi muốn hỏi là về BATTLE\n"
	.string "TOWER!\p"
	.string "Phòng Level 50 và Open Level... Phòng\n"
	.string "nào sẽ hoàn hảo với tôi?$"

gText_ApprenticeLevelModeThanks1::
	.string "{STR_VAR_1} sao? Đúng rồi! Tôi sẽ\n"
	.string "cố hết sức ở đó!\p"
	.string "Nếu chúng ta lại gặp nhau ở đây, hãy\n"
	.string "dạy tôi thêm điều khác nhé, thầy!$"

gText_ApprenticePleaseTeach2::
	.string "Ờm... Bạn là {PLAYER} phải không? Tôi\n"
	.string "tên là {STR_VAR_1}.\p"
	.string "Tôi muốn trở thành HLV POKéMON,\n"
	.string "nhưng không biết phải làm gì...\p"
	.string "Vì bạn rất nổi tiếng, tôi nghĩ có lẽ mình\n"
	.string "có thể xin bạn lời khuyên.\p"
	.string "{PLAYER}, bạn có thể cho tôi lời\n"
	.string "khuyên không?$"

gText_ApprenticeRejectTeaching2::
	.string "Ôi, nhưng...\p"
	.string "Tôi thật lòng muốn trở thành POKéMON\n"
	.string "HLV!\p"
	.string "Xin bạn hãy trả lời những câu hỏi của\n"
	.string "tôi được không?$"

gText_ApprenticeWhichLevelMode2::
	.string "Cảm ơn bạn! Tôi xin hỏi câu đầu tiên\n"
	.string "ngay nhé!\p"
	.string "BATTLE TOWER có hai cấp độ là Level 50\n"
	.string "và Open Level, đúng không?\p"
	.string "Bạn nghĩ cấp độ nào phù hợp với tôi\n"
	.string "hơn?$"

gText_ApprenticeLevelModeThanks2::
	.string "Ồ, thử thách {STR_VAR_1} sao?\n"
	.string "Tôi hiểu rồi!\p"
	.string "Nếu có câu hỏi khác, tôi sẽ quay lại đây\n"
	.string "xin lời khuyên của bạn!$"

gText_ApprenticePleaseTeach3::
	.string "Ồ? Hả? Bạn là... Không, không thể nào.\p"
	.string "Một người như tôi làm sao có cơ hội gặp\n"
	.string "{PLAYER} được.\p"
	.string "...Bạn thật sự là {PLAYER} sao? Tôi\n"
	.string "không thể tin mình đang nói chuyện với\l"
	.string "bạn!\p"
	.string "Khi chuyện tốt đẹp thế này xảy ra, từ\n"
	.string "giờ chắc chắn tôi chỉ gặp toàn chuyện\l"
	.string "khủng khiếp thôi...\p"
	.string "...Tôi xin lỗi... Tôi là...\n"
	.string "{STR_VAR_1}...\p"
	.string "Tôi chẳng có điểm gì đặc biệt để tự hào\n"
	.string "cả...\p"
	.string "Tôi cũng không nên kể gì về mình, vì rồi\n"
	.string "bạn sẽ quên thôi...\p"
	.string "Tôi từng mơ rằng nếu có ngày gặp bạn,\n"
	.string "{PLAYER}, có lẽ tôi sẽ được xin lời\l"
	.string "khuyên của bạn với tư cách HLV.\p"
	.string "Nhưng chắc bạn sẽ không đồng ý đâu.\p"
	.string "...Hay bạn sẽ rộng lòng cho tôi lời\n"
	.string "khuyên?$"

gText_ApprenticeRejectTeaching3::
	.string "Tôi biết mà...\p"
	.string "Chuyện này nhất định sẽ xảy ra, vì tôi\n"
	.string "chỉ là một kẻ vô danh tẻ nhạt...\p"
	.string "Nhưng tôi đã nghĩ biết đâu... Bạn sẽ\n"
	.string "không suy nghĩ lại sao?\p"
	.string "Nhưng tôi không thể bỏ cuộc dễ dàng\n"
	.string "như vậy. Tôi sẽ hỏi khi mình vẫn còn may\l"
	.string "mắn!\p"
	.string "Xin bạn hãy rộng lòng cho tôi lời khuyên\n"
	.string "được không?$"

gText_ApprenticeWhichLevelMode3::
	.string "Thật sao? Tôi không thể tin nổi! Không\n"
	.string "thể tin bạn sẽ khuyên tôi! Tôi... Tôi vui\l"
	.string "quá...\p"
	.string "Điều tôi muốn hỏi thật sự rất vụn vặt,\n"
	.string "nhưng tôi không sao quyết định được...\p"
	.string "Ở BATTLE TOWER, người ta cho chọn\n"
	.string "Level 50 hoặc Open Level.\p"
	.string "Bạn nghĩ ngay cả tôi cũng có cơ hội ở\n"
	.string "cấp độ nào?$"

gText_ApprenticeLevelModeThanks3::
	.string "{STR_VAR_1} sao? Được rồi!\n"
	.string "Nhưng bạn thật sự nghĩ người như tôi\l"
	.string "có cơ hội ư?\p"
	.string "Tôi sẽ cố hết sức, dù không nghĩ mình\n"
	.string "sẽ làm được.\p"
	.string "Cảm ơn bạn rất nhiều vì đã dành thời\n"
	.string "gian cho một người như tôi.$"

gText_ApprenticePleaseTeach4::
	.string "Ồ! Bạn là {PLAYER}{KUN}, đúng không?\p"
	.string "Tôi nghe nói bạn đấu POKéMON rất giỏi!\p"
	.string "Tôi là {STR_VAR_1}! Chúng ta làm\n"
	.string "bạn nhé!\p"
	.string "Bạn biết không?\p"
	.string "Bạn không thể thắng ở BATTLE FRONTIER\n"
	.string "nếu chỉ biết những gì họ dạy tại\l"
	.string "TRAINER'S SCHOOL.\p"
	.string "Tôi sẵn lòng nghe lời khuyên của bạn.\n"
	.string "Tất nhiên bạn sẽ đồng ý chứ?$"

gText_ApprenticeRejectTeaching4::
	.string "Hả? Sao bạn lại từ chối tôi? Chính tôi\n"
	.string "đang nhờ bạn cơ mà! Bạn phải nghĩ lại!$"

gText_ApprenticeWhichLevelMode4::
	.string "Được rồi, có một việc thế này. Tôi muốn\n"
	.string "bạn quyết định giúp.\p"
	.string "Bạn biết BATTLE TOWER có phòng Level\n"
	.string "50 và Open Level chứ?\p"
	.string "Bạn nghĩ cấp độ nào hợp với tôi,\n"
	.string "{PLAYER}{KUN}?$"

gText_ApprenticeLevelModeThanks4::
	.string "Được rồi, {STR_VAR_1} hợp với\n"
	.string "tôi sao? Cảm ơn bạn!\p"
	.string "Vì biết chính bạn đã quyết định,\n"
	.string "{PLAYER}{KUN}, tôi sẽ không quá buồn\l"
	.string "nếu thua.\p"
	.string "Được rồi, lần sau tôi sẽ lại nhờ bạn tư\n"
	.string "vấn. Tạm biệt!$"

gText_ApprenticePleaseTeach5::
	.string "Ồ, xin chào! {PLAYER}{KUN}! Tôi biết\n"
	.string "bạn vì bạn nổi tiếng lắm! Cứ gọi tôi là\l"
	.string "{STR_VAR_1}! Rất vui được gặp\l"
	.string "bạn!\p"
	.string "Tôi là TRIATHLETE, nên vẫn giữ cơ thể\n"
	.string "khỏe khoắn trong lúc nuôi POKéMON.\p"
	.string "Tôi còn bận nhiều việc khác như làm\n"
	.string "việc, ngủ trưa, khiêu vũ...\p"
	.string "Bận rộn thế này nên tôi không dễ trở\n"
	.string "thành một HLV tử tế.\p"
	.string "Vì vậy, tôi có một đề nghị!\p"
	.string "Hẳn phải có lý do chúng ta gặp nhau. Vậy\n"
	.string "thỉnh thoảng {PLAYER}{KUN} chia sẻ\l"
	.string "kinh nghiệm với tôi nhé?$"

gText_ApprenticeRejectTeaching5::
	.string "Ồ, nhưng xin bạn đấy? Một người như\n"
	.string "tôi cần một người như bạn,\l"
	.string "{PLAYER}{KUN}!\p"
	.string "Thật lòng đấy, tôi cần lời khuyên của\n"
	.string "bạn!$"

gText_ApprenticeWhichLevelMode5::
	.string "Cảm ơn bạn! Phải thế chứ! Vậy hãy bắt\n"
	.string "đầu bằng câu dễ nhé!\p"
	.string "Bạn biết hai cấp độ của BATTLE TOWER\n"
	.string "chứ? Level 50 và Open Level ấy.\p"
	.string "Một người bận rộn như tôi nên chuẩn bị\n"
	.string "cho cấp độ nào đây?$"

gText_ApprenticeLevelModeThanks5::
	.string "{STR_VAR_1} sao? Được rồi, hiểu\n"
	.string "rồi. Tôi sẽ cố thu xếp thời gian để thử\l"
	.string "sức!\p"
	.string "...Ối, tôi phải đi làm rồi! Cảm ơn! Hẹn gặp\n"
	.string "lại!$"

gText_ApprenticePleaseTeach6::
	.string "Không thể nào! Không đâu! Chẳng lẽ bạn\n"
	.string "là {PLAYER} thật sao?\p"
	.string "A-ha! Tuyệt quá! Tôi là\n"
	.string "{STR_VAR_1}, rất vui được gặp\l"
	.string "bạn!\p"
	.string "{PLAYER}, bạn mạnh lắm, đúng không?\p"
	.string "Ai cũng đang nhắc đến bạn!\p"
	.string "Ồ! Tôi vừa nảy ra một ý tuyệt vời! Tôi\n"
	.string "sẽ xin lời khuyên từ bạn, {PLAYER}!\l"
	.string "Chắc chắn chúng sẽ giúp tôi mạnh hơn!\p"
	.string "Ý hay quá, đúng không? Xin bạn hãy cho\n"
	.string "tôi lời khuyên!$"

gText_ApprenticeRejectTeaching6::
	.string "Ahahaha, bạn có thể giả vờ lạnh lùng,\n"
	.string "nhưng không lừa được tôi đâu! Thật ra\l"
	.string "bạn muốn đồng ý, đúng không?$"

gText_ApprenticeWhichLevelMode6::
	.string "Hoan hô! Tôi biết bạn có tấm lòng rộng\n"
	.string "lượng mà, {PLAYER}!\p"
	.string "Tôi nên hỏi gì trước đây? ...Ồ, nghĩ ra\n"
	.string "rồi!\p"
	.string "Xin hãy nổi trống lên! Câu hỏi của tôi\n"
	.string "là...\p"
	.string "Nếu thách đấu BATTLE TOWER, tôi nên\n"
	.string "chọn hướng nào?\p"
	.string "Level 50 hay Open Level? Cấp độ nào\n"
	.string "hợp với tôi hơn?$"

gText_ApprenticeLevelModeThanks6::
	.string "Ồ-ồ-ồ! Bạn chọn {STR_VAR_1} sao!\n"
	.string "Cảm ơn vì câu trả lời cực kỳ ngầu!\p"
	.string "Chắc hôm nay tôi chỉ muốn hỏi bấy nhiêu\n"
	.string "thôi.\p"
	.string "Chúng ta lại gặp nhau ở đây nhé? Cảm\n"
	.string "ơn!$"

gText_ApprenticePleaseTeach7::
	.string "Xin thứ lỗi, nhưng... Bạn có phải là\n"
	.string "{PLAYER} không?\p"
	.string "Tôi là {STR_VAR_1}, vô cùng hân\n"
	.string "hạnh được làm quen với bạn.\p"
	.string "Từ lâu tôi đã luôn ngưỡng mộ bạn...\p"
	.string "... ... ... ... ... ...\p"
	.string "Ờm... Tôi mong lời thỉnh cầu này không\n"
	.string "khiến bạn quá phiền lòng, nhưng...\p"
	.string "Tôi có thể trở thành đệ tử của bạn\n"
	.string "không, {PLAYER}?$"

gText_ApprenticeRejectTeaching7::
	.string "Ôi...!\p"
	.string "... ... ... ... ... ... ... ... ... ... ... ...\p"
	.string "...Chắc tôi đã ngất đi vì quá sốc. Xin lỗi,\n"
	.string "hẳn tôi đã nghe nhầm.\p"
	.string "Xin bạn! Xin hãy nói rằng bạn sẽ nhận tôi\n"
	.string "làm đệ tử!$"

gText_ApprenticeWhichLevelMode7::
	.string "Ôi... Tôi rất vui!\p"
	.string "Tôi không muốn làm phí thời gian của\n"
	.string "bạn, nên xin hãy cho tôi lời khuyên về\l"
	.string "việc này.\p"
	.string "Tôi dự định sớm thách đấu BATTLE\n"
	.string "TOWER.\p"
	.string "Tuy nhiên, ở đó có hai cấp độ...\p"
	.string "Cấp độ nào phù hợp với tôi nhất? Level\n"
	.string "50 hay Open Level?$"

gText_ApprenticeLevelModeThanks7::
	.string "Bạn chọn {STR_VAR_1} sao! Tôi\n"
	.string "hiểu rồi. Tôi sẽ cố hết sức!\p"
	.string "Cảm ơn bạn, {PLAYER}. Hy vọng lần sau\n"
	.string "tôi vẫn có thể nhờ cậy bạn. Xin bảo\l"
	.string "trọng!$"

gText_ApprenticePleaseTeach8::
	.string "Á! Á! {PLAYER}! Bạn đã nói chuyện với\n"
	.string "tôi! Tôi... Tôi vui sướng quá!\p"
	.string "Tôi! Tên tôi là {STR_VAR_1}! Tôi\n"
	.string "vừa trở thành HLV!\p"
	.string "Tôi rất vui vì được gặp bạn,\n"
	.string "{PLAYER}, người nổi danh trong giới\l"
	.string "POKéMON!\p"
	.string "Ồ-ồ-ồ, tôi biết rồi! Tôi có thể nhờ bạn\n"
	.string "một việc lớn không, {PLAYER}?\p"
	.string "Xin hãy nhận tôi làm đệ tử! Tôi muốn\n"
	.string "được học hỏi từ bạn!$"

gText_ApprenticeRejectTeaching8::
	.string "Oaaaa! {PLAYER} đã từ chối tôi...\n"
	.string "Đây... đây là một trải nghiệm vô giá!\p"
	.string "{PLAYER}, xin bạn đấy! Lần này tôi\n"
	.string "muốn nghe câu trả lời đồng ý!\p"
	.string "Tôi cầu xin bạn chỉ dạy!$"

gText_ApprenticeWhichLevelMode8::
	.string "Hííí! {PLAYER} đã đồng ý! {PLAYER}\n"
	.string "đã đồng ý!\p"
	.string "Đêm nay tôi sẽ không ngủ được mất...\n"
	.string "Cảm ơn bạn rất, rất nhiều!\p"
	.string "Vậy đây là câu hỏi của tôi!\p"
	.string "Ở BATTLE TOWER, Level 50 hay Open Level\n"
	.string "mới hợp với tôi?$"

gText_ApprenticeLevelModeThanks8::
	.string "{STR_VAR_1}! Tôi hiểu hoàn toàn\n"
	.string "rồi! Hoàn toàn hiểu rồi! Tôi vui đến phát\l"
	.string "cuồng!\p"
	.string "Hy vọng lần khác bạn vẫn sẵn lòng dạy\n"
	.string "tôi thêm.$"

gText_ApprenticePleaseTeach9::
	.string "Chà! Chẳng lẽ... Có khi nào... Bạn là\n"
	.string "{PLAYER}{KUN}?! HLV mạnh mẽ và\l"
	.string "nổi tiếng ấy sao? Xin chào, đúng là tôi\l"
	.string "may hết chỗ nói!\p"
	.string "Xin chào, tôi tên {STR_VAR_1}!\p"
	.string "Tôi vẫn luôn tìm một người thầy về\n"
	.string "POKéMON.\p"
	.string "Và đúng vào lúc hoàn hảo nhất, bạn xuất\n"
	.string "hiện, {PLAYER}{KUN}!\p"
	.string "Chuyện là thế đấy, {PLAYER}{KUN}! Hãy\n"
	.string "cho tôi theo bạn học việc!$"

gText_ApprenticeRejectTeaching9::
	.string "Gwaaaah! Bạn đúng là vừa ngầu vừa\n"
	.string "cứng rắn...\p"
	.string "Đừng như vậy mà. Tôi đang nhờ bạn đấy!$"

gText_ApprenticeWhichLevelMode9::
	.string "Ồ, tuyệt! Câu trả lời thật dứt khoát!\n"
	.string "Phải nói là xuất sắc!\p"
	.string "Vậy lời khuyên đầu tiên về BATTLE\n"
	.string "TOWER thì sao?\p"
	.string "Nếu đến đó, tôi nên chọn cấp độ nào?\n"
	.string "Level 50 hay Open Level?$"

gText_ApprenticeLevelModeThanks9::
	.string "Ừ-hứ, chọn {STR_VAR_1}! OK,\n"
	.string "A-OK! Tôi sẽ đi chứng tỏ bản lĩnh, chơi\l"
	.string "tới bến!\p"
	.string "Được rồi, từ giờ tôi sẽ xem bạn là\n"
	.string "người dẫn dắt! Adios!$"

gText_ApprenticePleaseTeach10::
	.string "Ồ, này, bạn là {PLAYER}{KUN}, đúng\n"
	.string "không? Cảnh sát đang tìm bạn đấy!\p"
	.string "... ... ... Tất nhiên là tôi nói dối!\p"
	.string "Tôi là {STR_VAR_1}. Trông vậy\n"
	.string "thôi chứ tôi là POKéMON CHAMPION đấy!\l"
	.string "...Câu đó cũng là nói dối!\p"
	.string "Nhưng chuyện này thì thật. Tôi chiến\n"
	.string "đấu không giỏi lắm.\p"
	.string "Vậy bạn làm sư phụ dạy tôi mọi điều về\n"
	.string "POKéMON nhé?$"

gText_ApprenticeRejectTeaching10::
	.string "Nếu bạn cứ lạnh lùng như vậy, tôi sẽ cho\n"
	.string "bạn thấy tôi làm gì!\p"
	.string "Oaaaa! Oaaaa! Oaaaa! Nấc!\p"
	.string "Hahaha, đó là FAKE TEARS của tôi!\p"
	.string "Nào, bạn làm sư phụ POKéMON của tôi\n"
	.string "nhé?$"

gText_ApprenticeWhichLevelMode10::
	.string "Yippee! Tôi sẽ mua tặng bạn một chiếc\n"
	.string "thuyền!\p"
	.string "Tất nhiên tôi lại nói dối! Nhưng... Cảm\n"
	.string "ơn sư phụ!\p"
	.string "Sư phụ biết BATTLE TOWER có Level 50 và\n"
	.string "Open Level chứ?\p"
	.string "Tôi không biết nên thách đấu cấp độ\n"
	.string "nào...\p"
	.string "Sư phụ quyết định giúp tôi nhé?$"

gText_ApprenticeLevelModeThanks10::
	.string "Được rồi, vậy {STR_VAR_1} tốt\n"
	.string "hơn! Thế thì tôi sẽ đến cấp độ kia!\p"
	.string "Đùa thôi! Tôi sẽ nghe lời dạy của sư\n"
	.string "phụ!\p"
	.string "Cảm ơn sư phụ! Mong sư phụ tiếp tục\n"
	.string "chỉ dạy tôi!$"

gText_ApprenticePleaseTeach11::
	.string "A-H-O-Y! Ghép lại thành ahoy, nghĩa là\n"
	.string "xin chào!\p"
	.string "Tôi là {STR_VAR_1}, một SAILOR\n"
	.string "rap vần, chính là tôi!\p"
	.string "Đến lượt bạn, hãy thử kể đôi lời về\n"
	.string "mình xem nào!\p"
	.string "Ừ-hứ, ừ-hứ! Tên bạn là {PLAYER}{KUN},\n"
	.string "còn POKéMON là cuộc chơi của bạn!\p"
	.string "Và bạn đang ở độ tuổi nhạy cảm, khi cả\n"
	.string "thế giới là sân khấu của mình!\p"
	.string "Dù sao tôi chỉ muốn nói, bạn là HLV\n"
	.string "thứ mười tôi trò chuyện hôm nay.\p"
	.string "Hãy kỷ niệm dịp này! Trở thành người\n"
	.string "dẫn dắt tôi ngay!$"

gText_ApprenticeRejectTeaching11::
	.string "Nhưng! Bạn phải hợp tác với tôi!\p"
	.string "Đừng trêu tôi thế! Hãy làm người dẫn\n"
	.string "dắt tôi nhé!$"

gText_ApprenticeWhichLevelMode11::
	.string "Đúng thế! {PLAYER}, bạn có khí thế\n"
	.string "lắm!\p"
	.string "Đây là câu hỏi đầu tiên, mong bạn đưa\n"
	.string "lời chỉ dẫn!\p"
	.string "Chuyện liên quan đến BATTLE TOWER, và\n"
	.string "phụ thuộc vào sức mạnh của tôi!\p"
	.string "Level 50 cùng Open Level, đâu là nơi phù\n"
	.string "hợp với tôi?$"

gText_ApprenticeLevelModeThanks11::
	.string "Được rồi, bạn nói chọn\n"
	.string "{STR_VAR_1}! Tôi sẽ lên đường và\l"
	.string "đương đầu với nó!\p"
	.string "Mỗi khi cần lời khuyên, {PLAYER}, tôi\n"
	.string "sẽ luôn nghe theo bạn!$"

gText_ApprenticePleaseTeach12::
	.string "Này, chẳng phải bạn là {PLAYER} sao?\n"
	.string "Tôi nên làm gì? Nói chuyện với bạn à?\l"
	.string "Sao lại không? Tôi đang nói rồi đây!\p"
	.string "{PLAYER}, bạn ngạc nhiên về tôi sao?\n"
	.string "Tôi nên cho bạn biết mình là ai!\p"
	.string "Bạn có thể gọi tôi là {STR_VAR_1}.\n"
	.string "Ngôi sao sáng nhất thế giới guitar\l"
	.string "chính là tôi!\p"
	.string "Bạn bắt được sóng của tôi chứ? Bạn\n"
	.string "đang bắt được đấy!\p"
	.string "Vận may đang lên cao, tôi sẽ đưa ra lời\n"
	.string "thỉnh cầu!\p"
	.string "{PLAYER}, cho tôi làm đệ tử của bạn!\n"
	.string "Tôi muốn bạn dạy tôi mọi thứ!$"

gText_ApprenticeRejectTeaching12::
	.string "Bạn từ chối tôi sao? Vậy tôi chỉ còn\n"
	.string "cách hỏi lại!\p"
	.string "{PLAYER}, tôi xin được làm đệ tử của\n"
	.string "bạn! Tôi cần bạn dạy tôi mọi thứ!$"

gText_ApprenticeWhichLevelMode12::
	.string "May quá, tuyệt quá, woohoo! Tôi hỏi bạn\n"
	.string "một câu nhé?\p"
	.string "Vì chúng ta đang ở gần BATTLE TOWER,\n"
	.string "hãy nói về sức mạnh nơi đó nhé?\p"
	.string "Trong những lựa chọn trước mắt, đâu là\n"
	.string "lựa chọn phù hợp với tôi?$"

gText_ApprenticeLevelModeThanks12::
	.string "Nếu bạn đề xuất {STR_VAR_1}, hẳn\n"
	.string "đó chính là lựa chọn tốt nhất!\p"
	.string "Nào, {PLAYER}, tôi phải tự do rong\n"
	.string "ruổi, nhưng đừng quên tôi nhé.\p"
	.string "Hẹn gặp lại, người bạn thông thái!$"

gText_ApprenticePleaseTeach13::
	.string "Ồ, chào bạn! Bạn kia! Bạn xoa bóp vai\n"
	.string "giúp tôi được không?\p"
	.string "...Đúng chỗ đó! Chính nó! Á, á! Ôi, dễ chịu\n"
	.string "quá!\p"
	.string "Tôi tên là {STR_VAR_1}. Tôi tập\n"
	.string "karate, nhưng thể trạng lại chẳng chịu\l"
	.string "nổi những bài tập khắc nghiệt...\p"
	.string "Tôi quyết định đấu POKéMON để rèn mình\n"
	.string "cứng cáp hơn.\p"
	.string "Bạn là {PLAYER}{KUN}, đúng không?\n"
	.string "POKéMON LEAGUE CHAMP ấy?\p"
	.string "Nghe này, bạn có thể cho tôi vài lời\n"
	.string "khuyên không?$"

gText_ApprenticeRejectTeaching13::
	.string "Ồ, tại sao chứ?\p"
	.string "Tôi hứa sẽ không làm phiền bạn nhiều\n"
	.string "đâu! Xin bạn đấy?$"

gText_ApprenticeWhichLevelMode13::
	.string "Cảm ơn bạn. Bạn tốt bụng quá! ...Khụ!\n"
	.string "Khụ!\p"
	.string "Ôi, tôi phải mau chóng khỏe hơn...\p"
	.string "Tôi sẽ đến BATTLE TOWER ngay, nhưng\n"
	.string "cấp độ nào hợp với tôi hơn? Level 50\l"
	.string "hay Open Level?$"

gText_ApprenticeLevelModeThanks13::
	.string "Hừm, được rồi. Vậy là\n"
	.string "{STR_VAR_1}. Tôi sẽ đến đó ngay.\p"
	.string "Mong sau này tôi vẫn có thể nhờ bạn\n"
	.string "giúp, dù sao bạn cũng là sư phụ của tôi!$"

gText_ApprenticePleaseTeach14::
	.string "Ờ... Ừm... {PLAYER}{KUN}...?\p"
	.string "Xin đừng nhìn tôi như vậy. Bạn làm tôi\n"
	.string "ngượng quá.\p"
	.string "Tôi... Tôi là {STR_VAR_1}.\p"
	.string "Tôi rất xấu hổ khi phải nói điều này,\n"
	.string "nhưng tôi thường khám phá những tàn\l"
	.string "tích cổ và các nơi tương tự.\p"
	.string "Tôi còn xấu hổ hơn khi thừa nhận mình\n"
	.string "quan tâm đến BATTLE FRONTIER.\p"
	.string "{PLAYER}{KUN}, bạn nổi tiếng là một\n"
	.string "HLV mạnh mẽ...\p"
	.string "Tôi rất khó mở lời, nhưng có chuyện\n"
	.string "muốn hỏi.\p"
	.string "Bạn có thể làm thầy và cho tôi lời\n"
	.string "khuyên không?$"

gText_ApprenticeRejectTeaching14::
	.string "Xin đừng gạt tôi đi như vậy! Tôi không\n"
	.string "thể chịu nổi nỗi nhục này.\p"
	.string "Xin hãy làm thầy của tôi! Tôi cần lời\n"
	.string "khuyên của bạn!$"

gText_ApprenticeWhichLevelMode14::
	.string "C-cảm ơn bạn...\p"
	.string "Nhưng xin đừng nhìn tôi như thế. Tôi\n"
	.string "bối rối lắm.\p"
	.string "Xin hãy trả lời mà đừng nhìn vào mắt\n"
	.string "tôi.\p"
	.string "Ở BATTLE TOWER... Tôi nên thử sức với\n"
	.string "cấp độ nào?$"

gText_ApprenticeLevelModeThanks14::
	.string "Ồ... Được rồi! Tôi sẽ thử sức ở đó.\p"
	.string "Hy vọng tôi có thể dũng cảm thách đấu\n"
	.string "mà không luống cuống...\p"
	.string "Cảm ơn bạn, {PLAYER}{KUN}. Nếu gặp lại,\n"
	.string "mong bạn vẫn nhiệt tình giúp đỡ tôi.$"

gText_ApprenticePleaseTeach15::
	.string "Hửm? Trông bạn có vẻ là\n"
	.string "{PLAYER}{KUN}... Nhưng bạn có thật sự\l"
	.string "là người thật không?\p"
	.string "Bạn có thể gọi tôi là {STR_VAR_1}.\p"
	.string "Tôi vẫn đang cân nhắc việc theo học một\n"
	.string "HLV mạnh mẽ.\p"
	.string "Vì vậy, phải nói rằng tôi thật may mắn\n"
	.string "khi bạn xuất hiện! ...Bạn thật sự là\l"
	.string "{PLAYER}{KUN}, đúng không?\p"
	.string "Không, không, nếu bạn là người thật thì\n"
	.string "được rồi. Tôi chỉ muốn bạn công nhận\l"
	.string "tôi là đệ tử.$"

gText_ApprenticeRejectTeaching15::
	.string "Ồ? Nhưng điều gì khiến bạn từ chối?\p"
	.string "Tôi xin lỗi vì đã nghi ngờ danh tính của\n"
	.string "bạn.\p"
	.string "Xin hãy chấp nhận lời xin lỗi và nhận tôi\n"
	.string "làm đệ tử.$"

gText_ApprenticeWhichLevelMode15::
	.string "Bạn thật sự nhận tôi sao? Tôi không\n"
	.string "muốn ăn mừng quá sớm.\p"
	.string "Nếu đó là sự thật thì tôi xin lỗi. Nhưng\n"
	.string "giờ tôi cần lời khuyên của bạn.\p"
	.string "Nếu tham gia BATTLE TOWER, cấp độ nào\n"
	.string "mới xứng với tôi? Level 50 hay Open\l"
	.string "Level?$"

gText_ApprenticeLevelModeThanks15::
	.string "{STR_VAR_1} sao? Bạn chắc chứ?\p"
	.string "Tôi hiểu rồi. Nếu vậy thì được. Cảm ơn\n"
	.string "bạn đã dành thời gian.\p"
	.string "Tôi biết mình có thể gây phiền, nhưng\n"
	.string "thật vui vì bạn đã nhận tôi.\p"
	.string "Hẹn gặp lại!$"

gText_ApprenticeWhatHeldItem0::
	.string "Haiz... Hức... Ôi, {PLAYER}!\p"
	.string "Tôi đang rối bời vì một lựa chọn mà mãi\n"
	.string "không quyết định được.\p"
	.string "Tôi không biết nên cho\n"
	.string "{STR_VAR_1} của mình cầm gì.\p"
	.string "Xin hãy cho tôi biết, {PLAYER}. Tôi nên\n"
	.string "cho nó cầm vật phẩm nào?$"

gText_ApprenticeHoldNothing0::
	.string "Ồ, thật sao? Tôi không nên cho\n"
	.string "{STR_VAR_1} của mình cầm gì cả\l"
	.string "sao?$"

gText_ApprenticeThanksNoHeldItem0::
	.string "Ồ, được rồi! Tôi vui quá vì đã quyết\n"
	.string "định xong! Tuyệt vời! Đỉnh quá! Auuuu!\p"
	.string "Cảm ơn bạn rất nhiều!$"

gText_ApprenticeThanksHeldItem0::
	.string "Ồ, tôi vui quá... Tôi nghĩ mình cũng có\n"
	.string "{STR_VAR_1} đó.\p"
	.string "Tôi vui quá vì đã quyết định xong!\n"
	.string "Tuyệt vời! Đỉnh quá! Auuuu!\p"
	.string "Cảm ơn bạn rất nhiều!$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "Oaaaa! Xin đừng trêu tôi!\p"
	.string "Vật phẩm {STR_VAR_1} đã được\n"
	.string "người khác gợi ý cho tôi rồi, hức...\p"
	.string "Hay ý bạn là tôi không nên cho\n"
	.string "{STR_VAR_2} cầm gì cả?$"

gText_ApprenticeWhatHeldItem1::
	.string "Hoan hô! Là {PLAYER}! Tuyệt quá! Tôi\n"
	.string "đang muốn hỏi bạn một chuyện!\p"
	.string "Bạn có cho POKéMON của mình cầm vật\n"
	.string "phẩm không? Tôi muốn cho POKéMON của\l"
	.string "mình cầm vật phẩm, nhưng...\p"
	.string "{STR_VAR_1} nên cầm vật phẩm nào\n"
	.string "thì tốt?\p"
	.string "Bạn nghĩ sao?$"

gText_ApprenticeHoldNothing1::
	.string "Hả? Ý bạn là {STR_VAR_1} của tôi\n"
	.string "không cần cầm gì cả sao?$"

gText_ApprenticeThanksNoHeldItem1::
	.string "Ồ, tôi hiểu rồi! Tôi sẽ làm vậy! Cảm ơn\n"
	.string "bạn đã dạy tôi!$"

gText_ApprenticeThanksHeldItem1::
	.string "Ồ, tuyệt quá! Một {STR_VAR_1}\n"
	.string "sao? Được rồi, tôi sẽ làm vậy!\p"
	.string "Cảm ơn bạn đã dạy tôi!$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "Ồ, ờm, không, ý tôi không phải vậy. Tôi\n"
	.string "muốn biết về một vật phẩm khác với\l"
	.string "những thứ mình đã biết.\p"
	.string "Hay ý bạn là lần này POKéMON của tôi\n"
	.string "không cần cầm gì cả?$"

gText_ApprenticeWhatHeldItem2::
	.string "{PLAYER}, xin chào! Chuyện này liên\n"
	.string "quan đến {STR_VAR_1} của tôi...\p"
	.string "Tôi muốn cho nó cầm một vật phẩm tốt.\n"
	.string "Vật phẩm nào sẽ phù hợp với nó?$"

gText_ApprenticeHoldNothing2::
	.string "Ồ, vậy {STR_VAR_1} của tôi không\n"
	.string "cần cầm gì cả sao?$"

gText_ApprenticeThanksNoHeldItem2::
	.string "Được rồi, tôi hiểu rồi! Hẹn gặp lại!$"

gText_ApprenticeThanksHeldItem2::
	.string "Ồ, vật phẩm {STR_VAR_1} sao? Tôi\n"
	.string "hiểu rồi!\p"
	.string "Tôi sẽ cố hết sức tìm một cái! Hẹn gặp\n"
	.string "lại!$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "Đã có người dạy tôi về\n"
	.string "{STR_VAR_1} rồi.\p"
	.string "Tôi muốn POKéMON của mình cầm một loại\n"
	.string "vật phẩm khác.\p"
	.string "Hay bạn nghĩ {STR_VAR_2} không\n"
	.string "cần cầm gì cả?$"

gText_ApprenticeWhatHeldItem3::
	.string "Xin chào, {PLAYER}... Xin lỗi vì đã làm\n"
	.string "phiền, nhưng tôi còn một chuyện muốn\l"
	.string "hỏi bạn.\p"
	.string "Tôi không nghĩ mình đủ giỏi để tự thắng\n"
	.string "các trận đấu, nên đang tính cho\l"
	.string "{STR_VAR_1} của mình cầm một vật\l"
	.string "phẩm.\p"
	.string "Nhưng tôi không biết vật phẩm nào sẽ\n"
	.string "tốt.\p"
	.string "{PLAYER}, xin bạn hãy quyết định giúp\n"
	.string "tôi được không?$"

gText_ApprenticeHoldNothing3::
	.string "POKéMON của một người như tôi thì\n"
	.string "không cầm vật phẩm lại tốt hơn sao?$"

gText_ApprenticeThanksNoHeldItem3::
	.string "Tôi hiểu rồi... Ý bạn là tôi không nên dựa\n"
	.string "dẫm vào vật phẩm. Tôi sẽ cố gắng không\l"
	.string "làm vậy!\p"
	.string "Cảm ơn bạn rất nhiều!$"

gText_ApprenticeThanksHeldItem3::
	.string "Vật phẩm {STR_VAR_1}, được rồi.\n"
	.string "Không biết tôi có kiếm được không...\l"
	.string "Không! Tôi sẽ cố hết sức để tìm cho\l"
	.string "bằng được.\p"
	.string "Cảm ơn bạn rất nhiều!$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "Ồ, nhưng... Hình như trước đây tôi\n"
	.string "từng nghe về nó rồi...\p"
	.string "Có phải vì tôi chưa biết cách dùng tốt\n"
	.string "vật phẩm {STR_VAR_1} không?\p"
	.string "Hay ý bạn là tôi không nên cho\n"
	.string "{STR_VAR_2} cầm gì cả?$"

gText_ApprenticeWhatHeldItem4::
	.string "Ồ, {PLAYER}{KUN}. Tôi có chuyện muốn\n"
	.string "hỏi bạn.\p"
	.string "Bạn nhớ đã quyết định giúp tôi nên có\n"
	.string "POKéMON nào chứ?\p"
	.string "Nhưng tôi chưa từng hỏi nên cho nó cầm\n"
	.string "vật phẩm gì.\p"
	.string "Bạn đã tư vấn rồi thì giúp tôi đến cùng\n"
	.string "nhé?\p"
	.string "Thứ gì sẽ phù hợp? Tôi muốn cho\n"
	.string "{STR_VAR_1} cầm một món.$"

gText_ApprenticeHoldNothing4::
	.string "Ồ! Vậy {STR_VAR_1} của tôi nên\n"
	.string "dốc hết sức mà không cầm gì sao?$"

gText_ApprenticeThanksNoHeldItem4::
	.string "Nếu bạn cho rằng như vậy là tốt nhất,\n"
	.string "tôi sẽ làm thế.\p"
	.string "Vì người quyết định là bạn,\n"
	.string "{PLAYER}{KUN}, nên nếu thua tôi cũng\l"
	.string "không buồn lắm đâu.\p"
	.string "Được rồi, lần sau tôi lại nhờ bạn tư vấn\n"
	.string "nhé. Tạm biệt!$"

gText_ApprenticeThanksHeldItem4::
	.string "Vật phẩm {STR_VAR_1} à? Không\n"
	.string "tệ. Tôi sẽ dùng nó!\p"
	.string "Vì người quyết định là bạn,\n"
	.string "{PLAYER}{KUN}, nên nếu thua tôi cũng\l"
	.string "không buồn lắm đâu.\p"
	.string "Được rồi, lần sau tôi lại nhờ bạn tư vấn\n"
	.string "nhé. Tạm biệt!$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "Hả? Bạn nói gì vậy? Trước đây bạn đã\n"
	.string "nói với tôi về {STR_VAR_1} rồi mà.\p"
	.string "Hay ý bạn là {STR_VAR_2} của tôi\n"
	.string "nên dốc hết sức mà không cầm gì?$"

gText_ApprenticeWhatHeldItem5::
	.string "Chào, {PLAYER}{KUN}!\p"
	.string "Cả hai ta đều bận, thế mà vẫn thường\n"
	.string "xuyên gặp nhau nhỉ!\p"
	.string "Hôm nay tôi còn phải đi bộ, dọn dẹp và\n"
	.string "chải chuốt.\p"
	.string "Tôi còn chẳng có thời gian mua gì cho\n"
	.string "{STR_VAR_1} quý giá của mình.\p"
	.string "Tôi không có thời gian, nên bạn tư vấn\n"
	.string "giúp xem nên cho {STR_VAR_1} cầm\l"
	.string "gì nhé?$"

gText_ApprenticeHoldNothing5::
	.string "Ồ, vì tôi là người bận rộn nên bạn bảo\n"
	.string "{STR_VAR_1} của tôi chẳng cần gì\l"
	.string "sao?$"

gText_ApprenticeThanksNoHeldItem5::
	.string "Được, hiểu rồi. Làm vậy chẳng tốn thời\n"
	.string "gian chút nào.\p"
	.string "Hôm nay cảm ơn nhé! Hẹn gặp lại!$"

gText_ApprenticeThanksHeldItem5::
	.string "Được, hiểu rồi. Tôi sẽ cố thu xếp thời\n"
	.string "gian để tìm món {STR_VAR_1} mà\l"
	.string "bạn đề xuất.\p"
	.string "Tôi thật may mắn khi gặp được một\n"
	.string "người thầy tốt như bạn. Cảm ơn! Hẹn\l"
	.string "gặp lại!$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "Hả? Tôi biết về {STR_VAR_1} đó\n"
	.string "rồi.\p"
	.string "À, phải rồi, tôi hiểu. Vì tôi là người bận\n"
	.string "rộn nên bạn bảo {STR_VAR_2} của\l"
	.string "tôi chẳng cần gì sao?$"

gText_ApprenticeWhatHeldItem6::
	.string "Chào, {PLAYER}! Là tôi đây! Hôm nay\n"
	.string "tôi lại cần mượn trí khôn của bạn. Làm\l"
	.string "ơn tư vấn giúp tôi!\p"
	.string "Xin một tràng trống! Câu hỏi của tôi là...\p"
	.string "Nếu muốn cho {STR_VAR_1} cầm một\n"
	.string "vật phẩm, tôi nên chọn thứ gì?$"

gText_ApprenticeHoldNothing6::
	.string "Vậy sao? Ý bạn là {STR_VAR_1} của\n"
	.string "tôi không cần cầm vật phẩm.$"

gText_ApprenticeThanksNoHeldItem6::
	.string "Được, tôi sẽ làm như vậy!\p"
	.string "Có lẽ hôm nay tôi chỉ muốn hỏi bạn bấy\n"
	.string "nhiêu thôi.\p"
	.string "Chúng ta lại gặp nhau ở đây nhé? Cảm\n"
	.string "ơn!$"

gText_ApprenticeThanksHeldItem6::
	.string "Ừ! Một món {STR_VAR_1}. Lựa chọn\n"
	.string "tuyệt quá! Tôi nhất định sẽ thử!\p"
	.string "Có lẽ hôm nay tôi chỉ muốn hỏi bạn bấy\n"
	.string "nhiêu thôi.\p"
	.string "Chúng ta lại gặp nhau ở đây nhé? Cảm\n"
	.string "ơn!$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "Ahaha! Ngớ ngẩn quá! Trước đây bạn đã\n"
	.string "nói với tôi về {STR_VAR_1} rồi mà!\p"
	.string "Bạn vẫn khỏe chứ, {PLAYER}?\p"
	.string "À, khoan! Ý bạn là {STR_VAR_2}\n"
	.string "của tôi không cần cầm vật phẩm.$"

gText_ApprenticeWhatHeldItem7::
	.string "Xin chào, {PLAYER}. Hy vọng bạn vẫn\n"
	.string "khỏe.\p"
	.string "Tôi có thể xin bạn một lời khuyên\n"
	.string "không?\p"
	.string "Trong trận đấu gần đây, đối thủ của tôi\n"
	.string "có vẻ đã cho POKéMON cầm một vật phẩm.\p"
	.string "Vì vậy, tôi đã thua...\p"
	.string "Tôi không muốn bị tụt lại phía sau. Tôi\n"
	.string "cũng muốn cho {STR_VAR_1} của\l"
	.string "mình cầm một vật phẩm.\p"
	.string "Tôi sẽ rất vui nếu bạn có thể quyết định\n"
	.string "thứ phù hợp với POKéMON của tôi...$"

gText_ApprenticeHoldNothing7::
	.string "Nói cách khác... POKéMON của tôi không\n"
	.string "cần cầm vật phẩm sao?$"

gText_ApprenticeThanksNoHeldItem7::
	.string "Giờ tôi đã hiểu rõ! Tôi sẽ tiếp tục cố\n"
	.string "gắng như vậy.\p"
	.string "Cảm ơn bạn, {PLAYER}. Hy vọng lần sau\n"
	.string "tôi vẫn có thể nhờ cậy bạn. Chúc bạn mọi\l"
	.string "điều tốt lành!$"

gText_ApprenticeThanksHeldItem7::
	.string "Vậy tôi sẽ chọn một món\n"
	.string "{STR_VAR_1}! Tôi sẽ đặt mua ngay.\p"
	.string "Cảm ơn bạn, {PLAYER}. Hy vọng lần sau\n"
	.string "tôi vẫn có thể nhờ cậy bạn. Chúc bạn mọi\l"
	.string "điều tốt lành!$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "Bạn đã nói với tôi về món đó rồi, và tôi\n"
	.string "cũng có nó rồi.\p"
	.string "Hay ý bạn là... POKéMON của tôi không\n"
	.string "cần cầm vật phẩm?$"

gText_ApprenticeWhatHeldItem8::
	.string "Á! {PLAYER}! Tôi... Tôi vui sướng quá\n"
	.string "khi lại được gặp bạn!\p"
	.string "Ôi, ôi, ôi! Có một chuyện tôi nhất định\n"
	.string "phải hỏi bạn, {PLAYER}!\p"
	.string "Xin hãy quyết định xem\n"
	.string "{STR_VAR_1} của tôi nên cầm gì!$"

gText_ApprenticeHoldNothing8::
	.string "Ôi, thật sao! Tôi không ngờ lại nhận\n"
	.string "được câu trả lời đó! Vậy không cần cầm\l"
	.string "vật phẩm à?$"

gText_ApprenticeThanksNoHeldItem8::
	.string "Tôi hiểu hoàn toàn rồi! Tôi sẽ tiếp tục\n"
	.string "mà không dùng vật phẩm!\p"
	.string "Hy vọng lần khác bạn vẫn sẵn lòng chỉ\n"
	.string "dạy thêm cho tôi.$"

gText_ApprenticeThanksHeldItem8::
	.string "{STR_VAR_1}! Tôi sẽ dùng món đó!\p"
	.string "Ừm... Có khi nào bạn cũng cho POKéMON\n"
	.string "của mình cầm vật phẩm đó không,\l"
	.string "{PLAYER}?\p"
	.string "Tôi nhất định sẽ kiếm được nó! Hy vọng\n"
	.string "lần khác bạn vẫn sẵn lòng chỉ dạy thêm\l"
	.string "cho tôi.$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "Ồ? Trước đây bạn cũng từng đề xuất\n"
	.string "{STR_VAR_1} rồi.\p"
	.string "Hay đó là vật phẩm tốt nhất để cầm? Hay\n"
	.string "ý bạn là {STR_VAR_2} của tôi\l"
	.string "không cần cầm gì?$"

gText_ApprenticeWhatHeldItem9::
	.string "Hola! Sư phụ của tôi, {PLAYER}{KUN}!\p"
	.string "Tôi muốn xin bạn lời khuyên về đồ dùng\n"
	.string "cho POKéMON.\p"
	.string "Bạn nghĩ {STR_VAR_1} của tôi nên\n"
	.string "cầm gì thì tốt?\p"
	.string "Đừng ngại nào. Cứ nói thẳng ra!$"

gText_ApprenticeHoldNothing9::
	.string "Ồ? Vậy ý bạn là {STR_VAR_1} của\n"
	.string "tôi có thể thắng mà không cần cầm vật\l"
	.string "phẩm?$"

gText_ApprenticeThanksNoHeldItem9::
	.string "Si, bueno! Tôi sẽ chơi hết mình, kiểu\n"
	.string "như, rầm!\p"
	.string "Được rồi, như mọi khi, cảm ơn nhé!\n"
	.string "Adios!$"

gText_ApprenticeThanksHeldItem9::
	.string "Ừ, một món {STR_VAR_1} phải\n"
	.string "không? Si, bueno! Tôi sẽ đi tìm một món,\l"
	.string "kiểu như, bùm!\p"
	.string "Được rồi, như mọi khi, cảm ơn nhé!\n"
	.string "Adios!$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "Không, không! Trước đây bạn đã nói với\n"
	.string "tôi về món {STR_VAR_1} đó rồi.\p"
	.string "Ồ, khoan đã nào... Vậy ý bạn là\n"
	.string "{STR_VAR_2} của tôi có thể thắng\l"
	.string "mà không cần cầm vật phẩm?$"

gText_ApprenticeWhatHeldItem10::
	.string "{PLAYER}{KUN}, một chuyện khó tin đã\n"
	.string "xảy ra!\p"
	.string "Sáng nay khi tôi thức dậy, POKéMON của\n"
	.string "tôi có tới 10 NUGGETS!\p"
	.string "Tất nhiên là tôi nói dối! Wahahaha!\p"
	.string "Nhưng chuyện này thì không phải nói\n"
	.string "dối. Tôi không giỏi nghĩ xem POKéMON nên\l"
	.string "cầm vật phẩm gì.\p"
	.string "Vậy sư phụ quyết định giúp xem\n"
	.string "{STR_VAR_1} của tôi nên cầm gì\l"
	.string "nhé?$"

gText_ApprenticeHoldNothing10::
	.string "Thế nghĩa là sao? Không cho nó cầm gì\n"
	.string "à?$"

gText_ApprenticeThanksNoHeldItem10::
	.string "Được, vậy nó không nên cầm gì cả. Thế\n"
	.string "thì tôi phải kiếm cho nó một món mới\l"
	.string "được!\p"
	.string "Đùa thôi! Tôi sẽ nghe theo lời dạy của\n"
	.string "sư phụ!\p"
	.string "Cảm ơn sư phụ! Mong sư phụ tiếp tục\n"
	.string "chỉ dạy tôi!$"

gText_ApprenticeThanksHeldItem10::
	.string "Được, vậy là một món\n"
	.string "{STR_VAR_1}! Tôi sẽ cho nó cầm\l"
	.string "bất cứ thứ gì trừ món đó!\p"
	.string "Đùa thôi! Tôi sẽ nghe theo lời dạy của\n"
	.string "sư phụ!\p"
	.string "Cảm ơn sư phụ! Mong sư phụ tiếp tục\n"
	.string "chỉ dạy tôi!$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "Ừm, trước đây bạn đã nói với tôi về món\n"
	.string "đó rồi, phải không?\p"
	.string "Không còn thứ gì khác sao?\p"
	.string "Hay ý bạn là không nên cho\n"
	.string "{STR_VAR_2} của tôi cầm gì?$"

gText_ApprenticeWhatHeldItem11::
	.string "A-H-O-Y! Ghép lại là ahoy!\p"
	.string "Ta là SAILOR biết rap! Xin dâng một câu\n"
	.string "hỏi cực chất!\p"
	.string "Câu hỏi về vật phẩm, mong bạn cho lời\n"
	.string "góp ý!\p"
	.string "{STR_VAR_1} của ta cần cầm một\n"
	.string "món, chọn gì đây, xin bạn cứ nói!$"

gText_ApprenticeHoldNothing11::
	.string "Thật vậy sao? {STR_VAR_1} của ta\n"
	.string "chẳng cần cầm món nào sao?$"

gText_ApprenticeThanksNoHeldItem11::
	.string "Được, ta nghe rõ, hiểu rồi! POKéMON của\n"
	.string "ta cũng sẽ tay không thôi!\p"
	.string "Mỗi khi cần lời khuyên, {PLAYER}, lời\n"
	.string "bạn nói ta luôn ghi nhớ!$"

gText_ApprenticeThanksHeldItem11::
	.string "Được, một món {STR_VAR_1}, ta sẽ\n"
	.string "dùng ngay. Nhờ bạn chọn quả thật rất\l"
	.string "hay!\p"
	.string "Mỗi khi cần lời khuyên, {PLAYER}, lời\n"
	.string "bạn nói ta luôn ghi nhớ!$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "Được, một món {STR_VAR_1}, bạn\n"
	.string "nói vậy sao? Hôm trước bạn đã bảo thế\l"
	.string "rồi nào. Ta cần ý tưởng mới, một cách\l"
	.string "thật khác.\p"
	.string "Hay khoan, đúng vậy sao? POKéMON của\n"
	.string "ta chẳng cần cầm món nào?$"

gText_ApprenticeWhatHeldItem12::
	.string "Này, chào {PLAYER}! Hôm nay lại gặp\n"
	.string "bạn rồi!\p"
	.string "Tôi nên làm gì? Xin lời khuyên của bạn\n"
	.string "à? Sao lại không? Tôi đang nói chuyện\l"
	.string "với bạn mà!\p"
	.string "{PLAYER}, bạn đã chán tôi chưa?\n"
	.string "Không đâu, chắc chắn không thể nào.\p"
	.string "Bạn nghe tôi nói nhé? Tôi đang cần lời\n"
	.string "khuyên, chuyện là vậy đó.\p"
	.string "Tôi cần một vật phẩm phù hợp để\n"
	.string "{STR_VAR_1} cầm. Cứ phân vân mãi\l"
	.string "làm tôi buồn rầu.$"

gText_ApprenticeHoldNothing12::
	.string "{STR_VAR_1} của tôi chẳng cần gì\n"
	.string "sao? Không cần cầm vật phẩm nào à?$"

gText_ApprenticeThanksNoHeldItem12::
	.string "Nếu không cầm gì là tốt nhất, tôi sẽ làm\n"
	.string "theo lời bạn!\p"
	.string "Thôi, {PLAYER}, tôi phải tự do rong\n"
	.string "ruổi, nhưng đừng quên tôi nhé.\p"
	.string "Hẹn gặp lại, người bạn thông thái!$"

gText_ApprenticeThanksHeldItem12::
	.string "Nếu cầm {STR_VAR_1} là tốt nhất,\n"
	.string "tôi sẽ làm theo lời bạn!\p"
	.string "Thôi, {PLAYER}, tôi phải tự do rong\n"
	.string "ruổi, nhưng đừng quên tôi nhé.\p"
	.string "Hẹn gặp lại, người bạn thông thái!$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "Chẳng phải trước đây tôi đã nghe về\n"
	.string "{STR_VAR_1} rồi sao? Chắc chắn là\l"
	.string "vậy, tôi biết rõ mà!\p"
	.string "Tôi cần một thứ mới! Hay\n"
	.string "{STR_VAR_2} của tôi chẳng cần gì\l"
	.string "sao? Không cần cầm vật phẩm nào à?$"

gText_ApprenticeWhatHeldItem13::
	.string "Ái! Đau quá! {PLAYER}{KUN}, tay tôi gãy\n"
	.string "rồi! Làm ơn đừng chạm vào!\p"
	.string "Chắc tôi đã làm gãy tay khi thử đủ loại\n"
	.string "vật phẩm cho đội POKéMON của mình cầm.\p"
	.string "Tình hình thế này, tôi cần bạn quyết\n"
	.string "định giúp.\p"
	.string "{PLAYER}{KUN}, bạn nghĩ\n"
	.string "{STR_VAR_1} của tôi nên cầm gì\l"
	.string "thì tốt?$"

gText_ApprenticeHoldNothing13::
	.string "Đau quá...\p"
	.string "Vậy bạn đề xuất rằng {STR_VAR_1}\n"
	.string "của tôi không cần cầm gì sao?$"

gText_ApprenticeThanksNoHeldItem13::
	.string "Ừm, được thôi. Với tình trạng hiện giờ\n"
	.string "của tôi, như vậy sẽ dễ hơn.\p"
	.string "Hy vọng sau này tôi vẫn có thể tiếp tục\n"
	.string "nhờ bạn giúp như thế này.$"

gText_ApprenticeThanksHeldItem13::
	.string "Ừm, được thôi. Vậy là một món\n"
	.string "{STR_VAR_1}. Tay POKéMON của tôi\l"
	.string "vẫn ổn, nên tôi sẽ cho nó cầm vật phẩm\l"
	.string "đó ngay.\p"
	.string "Hy vọng sau này tôi vẫn có thể tiếp tục\n"
	.string "nhờ bạn giúp như thế này.$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "Không, không, trước đây bạn đã nói với\n"
	.string "tôi về {STR_VAR_1} rồi, nhớ chứ?\p"
	.string "Hay bạn nói cho tôi thứ gì còn tốt hơn\n"
	.string "đi?\p"
	.string "À, khoan đã. Vậy bạn đề xuất rằng\n"
	.string "{STR_VAR_2} của tôi không cần\l"
	.string "cầm gì sao?$"

gText_ApprenticeWhatHeldItem14::
	.string "Ơ... Ừm... {PLAYER}{KUN}...\p"
	.string "Xin đừng nhìn tôi như vậy. POKéMON của\n"
	.string "tôi chẳng cầm gì cả.\p"
	.string "Tôi... Tôi thật sự rất xấu hổ, nhưng tôi\n"
	.string "rất cần lời khuyên của bạn.\p"
	.string "Tôi không quyết định được vật phẩm\n"
	.string "nào sẽ giúp {STR_VAR_1} của mình\l"
	.string "mạnh hơn.\p"
	.string "{PLAYER}{KUN}, bạn nghĩ thứ gì sẽ phù\n"
	.string "hợp?$"

gText_ApprenticeHoldNothing14::
	.string "Ồ... Vậy bạn nghĩ {STR_VAR_1} của\n"
	.string "tôi không cầm vật phẩm thì sẽ tốt hơn\l"
	.string "sao?$"

gText_ApprenticeThanksNoHeldItem14::
	.string "Ồ... Được rồi! Tôi sẽ không dùng vật\n"
	.string "phẩm.\p"
	.string "Nhưng thế này hồi hộp quá. Có ngầu quá\n"
	.string "không nhỉ?\p"
	.string "Cảm ơn bạn, {PLAYER}{KUN}. Nếu lại gặp\n"
	.string "nhau, hy vọng bạn vẫn sẽ nhiệt tình\l"
	.string "giúp đỡ.$"

gText_ApprenticeThanksHeldItem14::
	.string "Ồ... Được rồi! Tôi sẽ chọn\n"
	.string "{STR_VAR_1}.\p"
	.string "Nhưng thế này hồi hộp quá. Có ngầu quá\n"
	.string "không nhỉ?\p"
	.string "Cảm ơn bạn, {PLAYER}{KUN}. Nếu lại gặp\n"
	.string "nhau, hy vọng bạn vẫn sẽ nhiệt tình\l"
	.string "giúp đỡ.$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "N-nhưng tôi đã nghe về món đó rồi.\p"
	.string "Xin đừng gạt tôi đi như vậy! Tôi không\n"
	.string "chịu nổi nỗi nhục này đâu.\p"
	.string "Ồ... Tôi kết luận vội quá sao? Bạn nghĩ\n"
	.string "{STR_VAR_2} của tôi không cầm\l"
	.string "vật phẩm thì sẽ tốt hơn à?$"

gText_ApprenticeWhatHeldItem15::
	.string "Hửm? Trông bạn có vẻ là\n"
	.string "{PLAYER}{KUN}... Nhưng thật sự là bạn\l"
	.string "sao? Có lẽ bạn là anh em sinh đôi?\p"
	.string "Ồ, không, không, không, đừng lo! Nếu bạn\n"
	.string "thật sự là {PLAYER}, xin hãy bỏ qua\l"
	.string "sự thất lễ của tôi.\p"
	.string "Điều tôi muốn là được nghe thêm lời\n"
	.string "khuyên tuyệt vời của bạn.\p"
	.string "Tôi có {STR_VAR_1} ở đây và muốn\n"
	.string "cho nó cầm một vật phẩm hữu ích.\p"
	.string "Thứ gì mới xứng đáng với nó?$"

gText_ApprenticeHoldNothing15::
	.string "Không cầm gì sẽ tốt hơn sao? Bạn chắc\n"
	.string "chứ?$"

gText_ApprenticeThanksNoHeldItem15::
	.string "Tôi hiểu. Nếu là vậy thì cũng được. Cảm\n"
	.string "ơn bạn đã dành thời gian.\p"
	.string "Hẹn ngày gặp lại!$"

gText_ApprenticeThanksHeldItem15::
	.string "Một món {STR_VAR_1} sao? Bạn\n"
	.string "chắc chứ?\p"
	.string "Tôi hiểu. Nếu là vậy thì cũng được. Cảm\n"
	.string "ơn bạn đã dành thời gian.\p"
	.string "Tôi rất mong POKéMON của mình có thể\n"
	.string "tận dụng tốt món đó.\p"
	.string "Hẹn ngày gặp lại!$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "Không, không, xin chờ một chút. Tôi tin\n"
	.string "rằng trước đây bạn đã dạy tôi điều đó\l"
	.string "rồi.\p"
	.string "Lần này tôi muốn bạn đề xuất một thứ\n"
	.string "khác.\p"
	.string "Hay bạn đang gợi ý rằng\n"
	.string "{STR_VAR_2} của tôi không nên\l"
	.string "cầm gì? Bạn chắc chứ?$"

gText_ApprenticeWhichMonFirst0::
	.string "Hu hu, {PLAYER}! Tôi khó xử quá...\p"
	.string "Tôi muốn bắt đầu đấu với người khác,\n"
	.string "nhưng lại không biết phải làm gì.\p"
	.string "Tôi nên sắp xếp POKéMON thế nào để\n"
	.string "chúng phát huy sức mạnh tốt nhất?\p"
	.string "Làm ơn nói cho tôi biết đi, {PLAYER}.\n"
	.string "Nếu là tôi, bạn sẽ cho POKéMON nào trong\l"
	.string "số này ra trận trước?$"

gText_ApprenticeMonFirstThanks0::
	.string "{STR_VAR_1} của tôi nên ra trước\n"
	.string "sao? Hu hu hu!\p"
	.string "Ôi! Tôi xin lỗi! Bạn đã làm tôi vui đến\n"
	.string "mức bật khóc khi chọn POKéMON ra trận\l"
	.string "đầu tiên giúp tôi...\p"
	.string "Cảm ơn bạn rất nhiều!$"

gText_ApprenticeWhichMonFirst1::
	.string "Yay! Là {PLAYER}! Tuyệt quá! Tôi đang\n"
	.string "muốn hỏi bạn một chuyện!\p"
	.string "Ừm, trong số POKéMON của tôi, bạn nghĩ\n"
	.string "con nào nên ra trận trước?$"

gText_ApprenticeMonFirstThanks1::
	.string "{STR_VAR_1} của tôi sao? Đúng\n"
	.string "thật. Được, tôi sẽ làm vậy!\p"
	.string "Cảm ơn bạn đã chỉ dạy!$"

gText_ApprenticeWhichMonFirst2::
	.string "Xin chào, {PLAYER}!\p"
	.string "Tôi nghĩ trong một trận đấu, việc\n"
	.string "POKéMON nào ra đầu tiên rất quan trọng.\p"
	.string "Trong số POKéMON tôi có, con nào thích\n"
	.string "hợp để ra trận trước?$"

gText_ApprenticeMonFirstThanks2::
	.string "{STR_VAR_1} của tôi ra trước\n"
	.string "sao? Được, tôi hiểu rồi!\p"
	.string "Hẹn gặp lại!$"

gText_ApprenticeWhichMonFirst3::
	.string "Xin chào, {PLAYER}... Tôi xin lỗi vì lại\n"
	.string "làm phiền bạn bằng một câu hỏi khác.\p"
	.string "Tôi thiếu tự tin đến mức không biết\n"
	.string "mình sẽ làm gì nếu không có bạn,\l"
	.string "{PLAYER}.\p"
	.string "Có lẽ lo lắng về chuyện này cũng chỉ phí\n"
	.string "thời gian, nhưng tôi không sao quyết\l"
	.string "định được...\p"
	.string "Tôi nên cho POKéMON nào ra đầu tiên\n"
	.string "trong trận đấu?$"

gText_ApprenticeMonFirstThanks3::
	.string "{STR_VAR_1} của tôi sao? Tôi hiểu\n"
	.string "rồi!\p"
	.string "Không thể tin rằng bạn vẫn chịu khó trả\n"
	.string "lời câu hỏi của tôi nhiều lần như vậy!\p"
	.string "Chỉ riêng việc bạn chịu nói chuyện với\n"
	.string "tôi cũng khiến tôi vô cùng biết ơn... Cảm\l"
	.string "ơn bạn!$"

gText_ApprenticeWhichMonFirst4::
	.string "Ồ, {PLAYER}{KUN}! Là tôi đây! Tôi rất\n"
	.string "vui khi gặp bạn vì đang có một vấn đề\l"
	.string "nhỏ.\p"
	.string "Tôi không quyết định được nên sắp xếp\n"
	.string "POKéMON thế nào. Bạn quyết định giúp\l"
	.string "tôi nhé?\p"
	.string "À, bây giờ bạn không cần quyết định thứ\n"
	.string "tự cả đội đâu.\p"
	.string "Bạn chỉ cần chọn POKéMON đầu tiên giúp\n"
	.string "tôi thì sao?$"

gText_ApprenticeMonFirstThanks4::
	.string "{STR_VAR_1} của tôi sao? Tuyệt\n"
	.string "quá!\p"
	.string "Vì người quyết định là bạn,\n"
	.string "{PLAYER}{KUN}, nên nếu thua tôi cũng\l"
	.string "không buồn lắm đâu.\p"
	.string "Được rồi, lần sau tôi lại nhờ bạn tư vấn\n"
	.string "nhé. Tạm biệt!$"

gText_ApprenticeWhichMonFirst5::
	.string "Chào người thầy {PLAYER}{KUN} của\n"
	.string "tôi! Hôm nay tôi lại bận tối mắt!\p"
	.string "Tôi còn phải đạp xe, mua sắm và ngân\n"
	.string "nga.\p"
	.string "Tôi thậm chí chưa có thời gian quyết\n"
	.string "định thứ tự đội POKéMON của mình.\p"
	.string "Vậy bạn xem giúp đội của tôi nhé? Con\n"
	.string "nào nên ra trước?$"

gText_ApprenticeMonFirstThanks5::
	.string "Được, hiểu rồi. Ít nhất tôi vẫn đủ thời\n"
	.string "gian để đưa {STR_VAR_1} của\l"
	.string "mình lên đầu đội hình!\p"
	.string "Ôi, bạn gái tôi đang đợi! Cảm ơn nhé!\n"
	.string "Hẹn gặp lại!$"

gText_ApprenticeWhichMonFirst6::
	.string "Hú hú! Chào, {PLAYER}! Trông bạn lúc\n"
	.string "nào cũng thật mạnh mẽ!\p"
	.string "Nghe này, tôi lại cần bạn giúp! Vẫn là\n"
	.string "chuyện thường lệ thôi!\p"
	.string "Xin một tràng trống! Câu hỏi lần này là\n"
	.string "về đội của tôi.\p"
	.string "POKéMON nào của tôi nên ra đầu tiên\n"
	.string "trong trận đấu?$"

gText_ApprenticeMonFirstThanks6::
	.string "Hừm hừm! Bạn chọn {STR_VAR_1}\n"
	.string "của tôi sao! Cảm ơn vì câu trả lời cực\l"
	.string "ngầu!\p"
	.string "Có lẽ hôm nay tôi chỉ muốn hỏi bạn bấy\n"
	.string "nhiêu thôi.\p"
	.string "Chúng ta lại gặp nhau ở đây nhé? Cảm\n"
	.string "ơn!$"

gText_ApprenticeWhichMonFirst7::
	.string "Cảm ơn bạn rất nhiều vì đã dừng lại trò\n"
	.string "chuyện với tôi, {PLAYER}.\p"
	.string "Tôi biết mình đang lợi dụng lòng tốt\n"
	.string "của bạn, nhưng tôi có thể xin một lời\l"
	.string "khuyên không?\p"
	.string "Tôi muốn bạn quyết định thứ tự đội\n"
	.string "POKéMON của mình.\p"
	.string "Tôi sẽ rất vui nếu bạn có thể quyết định\n"
	.string "POKéMON nào nên đứng đầu.$"

gText_ApprenticeMonFirstThanks7::
	.string "Vậy sẽ là {STR_VAR_1} của tôi! Tôi\n"
	.string "sẽ lập tức đưa nó lên đầu!\p"
	.string "Cảm ơn bạn, {PLAYER}. Hy vọng lần sau\n"
	.string "tôi vẫn có thể nhờ cậy bạn. Chúc bạn mọi\l"
	.string "điều tốt lành!$"

gText_ApprenticeWhichMonFirst8::
	.string "Á! {PLAYER}! Tôi... Tôi vui sướng quá\n"
	.string "khi lại được gặp bạn!\p"
	.string "POKéMON của tôi đã mạnh hơn rất nhiều!\p"
	.string "Nhưng tôi không phải lúc nào cũng\n"
	.string "thắng. Có vẻ kết quả phụ thuộc vào\l"
	.string "POKéMON nào ra trước.\p"
	.string "{PLAYER}, làm ơn, tôi cần bạn giúp!\p"
	.string "Xin hãy quyết định POKéMON nào của tôi\n"
	.string "nên ra trận trước!$"

gText_ApprenticeMonFirstThanks8::
	.string "Phù... Tôi hạnh phúc đến choáng ngợp...\p"
	.string "Được bạn quyết định giúp cứ như một\n"
	.string "giấc mơ vậy, {PLAYER}.\p"
	.string "Nhưng tôi đã hiểu hoàn toàn! Tôi sẽ cho\n"
	.string "{STR_VAR_1} của mình ra trước!\p"
	.string "Hy vọng lần khác bạn vẫn sẵn lòng chỉ\n"
	.string "dạy thêm cho tôi.$"

gText_ApprenticeWhichMonFirst9::
	.string "Xin chào, xin chào! Sư phụ của tôi,\n"
	.string "{PLAYER}{KUN}! Hôm nay hãy ban cho tôi\l"
	.string "lời khuyên thông thái đi!\p"
	.string "Tôi đã tập hợp được một đội gồm ba\n"
	.string "POKéMON. Đến đây vẫn ổn.\p"
	.string "Nhưng thứ tự chiến đấu của cả đội vẫn\n"
	.string "chưa được quyết định.\p"
	.string "Đến lúc bạn ra tay rồi, {PLAYER}{KUN}!\n"
	.string "Hãy chọn POKéMON dẫn đầu!\p"
	.string "Đừng ngại nào. Cứ nói thẳng ra!$"

gText_ApprenticeMonFirstThanks9::
	.string "Ừ, {STR_VAR_1} của tôi dẫn đầu!\n"
	.string "OK, A-OK! Tôi sẽ đổi lại đội hình, kiểu\l"
	.string "như, rầm!\p"
	.string "Được rồi, như mọi khi, cảm ơn nhé!\n"
	.string "Adios!$"

gText_ApprenticeWhichMonFirst10::
	.string "{PLAYER}{KUN}, nghe này! Có chuyện\n"
	.string "nguy cấp!\p"
	.string "Cả ba POKéMON của tôi cùng lao vào trận\n"
	.string "một lúc!\p"
	.string "Tất nhiên là chuyện đó không thể xảy\n"
	.string "ra! Wahahaha!\p"
	.string "Nhưng chuyện này thì không phải nói\n"
	.string "dối. Tôi không giỏi nghĩ xem nên sắp xếp\l"
	.string "POKéMON của mình thế nào.\p"
	.string "Vậy sư phụ quyết định giúp xem POKéMON\n"
	.string "nào nên ra trước nhé?$"

gText_ApprenticeMonFirstThanks10::
	.string "Được, sư phụ chọn {STR_VAR_1}\n"
	.string "của tôi sao? Tôi sẽ cho bất cứ con nào\l"
	.string "trừ nó ra trước!\p"
	.string "Đùa thôi! Tôi sẽ nghe theo lời dạy của\n"
	.string "sư phụ!\p"
	.string "Cảm ơn sư phụ! Mong sư phụ tiếp tục\n"
	.string "chỉ dạy tôi!$"

gText_ApprenticeWhichMonFirst11::
	.string "A-H-O-Y! Ghép lại là ahoy!\p"
	.string "Ta là SAILOR biết rap! Xin dâng một câu\n"
	.string "hỏi cực chất!\p"
	.string "Câu hỏi về đội hình, mong bạn cho lời\n"
	.string "góp ý!\p"
	.string "Trong cả nhóm này, con nào nên đứng\n"
	.string "đầu để ra trước đây?$"

gText_ApprenticeMonFirstThanks11::
	.string "Được, ta nghe rõ, hiểu rồi! Ta sẽ đổi\n"
	.string "thứ tự ngay thôi!\p"
	.string "Mỗi khi cần lời khuyên, {PLAYER}, lời\n"
	.string "bạn nói ta luôn ghi nhớ!$"

gText_ApprenticeWhichMonFirst12::
	.string "Yahoo, {PLAYER}! Bạn khỏe chứ?\p"
	.string "Tôi nên làm gì? Cứ hỏi luôn à? Ừ, tôi có\n"
	.string "chuyện muốn hỏi! Bạn nghe rõ chứ? Bạn\l"
	.string "đang nghe rõ!\p"
	.string "Bạn phải quyết định POKéMON nào của tôi\n"
	.string "sẽ là con đầu tiên lên đường! Ý tôi là\l"
	.string "bước vào trận đấu.$"

gText_ApprenticeMonFirstThanks12::
	.string "{STR_VAR_1} của tôi sao? Tuyệt!\n"
	.string "Thế là ổn, chẳng cần lo lắng!\p"
	.string "Thôi, {PLAYER}, tôi phải tự do rong\n"
	.string "ruổi, nhưng đừng quên tôi nhé.\p"
	.string "Hẹn gặp lại, người bạn thông thái!$"

gText_ApprenticeWhichMonFirst13::
	.string "...Ối... đau... {PLAYER}{KUN}... Bụng tôi\n"
	.string "đột nhiên đau quá...\p"
	.string "...Giờ đỡ hơn rồi...\p"
	.string "Chắc tôi đã lo đến phát bệnh vì vắt óc\n"
	.string "nghĩ cách sắp xếp đội POKéMON của\l"
	.string "mình.\p"
	.string "Tình hình thế này, tôi cần bạn quyết\n"
	.string "định giúp.\p"
	.string "{PLAYER}{KUN}, POKéMON nào của tôi\n"
	.string "nên ra trước? Ý tôi là để tôi có thể\l"
	.string "thắng ấy.$"

gText_ApprenticeMonFirstThanks13::
	.string "Ừm, được thôi. {STR_VAR_1} của\n"
	.string "tôi sẽ ra trước.\p"
	.string "Sau khi ăn tối, tôi sẽ sắp xếp đội hình\n"
	.string "như vậy.\p"
	.string "Hy vọng sau này tôi vẫn có thể tiếp tục\n"
	.string "nhờ bạn giúp như thế này.$"

gText_ApprenticeWhichMonFirst14::
	.string "Ơ... Ừm... {PLAYER}{KUN}?\p"
	.string "Xin đừng nhìn tôi như vậy. Bạn làm tôi\n"
	.string "bối rối quá.\p"
	.string "Ừm... Tôi thật sự cần lời khuyên của\n"
	.string "bạn.\p"
	.string "Nói ra thật ngượng, nhưng tôi đã chọn\n"
	.string "được đội gồm 3 POKéMON. Chỉ là tôi\l"
	.string "chưa quyết định được thứ tự.\p"
	.string "Tôi nên cho POKéMON nào ra trước để ít\n"
	.string "nhất trông mình cũng có vẻ biết chiến\l"
	.string "đấu?$"

gText_ApprenticeMonFirstThanks14::
	.string "Ồ... Được rồi! Tôi sẽ cho\n"
	.string "{STR_VAR_1} của mình dẫn đầu.\p"
	.string "Hy vọng tôi có thể cố hết sức mà không\n"
	.string "quá bối rối.\p"
	.string "Cảm ơn bạn, {PLAYER}{KUN}. Nếu lại gặp\n"
	.string "nhau, hy vọng bạn vẫn sẽ nhiệt tình\l"
	.string "giúp đỡ.$"

gText_ApprenticeWhichMonFirst15::
	.string "Hửm? Trông bạn có vẻ là\n"
	.string "{PLAYER}{KUN}... Nhưng thật sự là bạn\l"
	.string "sao? Có lẽ bạn chỉ là một người giống\l"
	.string "hệt rất khéo giả dạng?\p"
	.string "Ồ, không, không, không, đừng lo! Nếu bạn\n"
	.string "thật sự là {PLAYER}, xin hãy bỏ qua\l"
	.string "sự thất lễ của tôi.\p"
	.string "Điều tôi muốn là lời khuyên tuyệt vời\n"
	.string "của bạn.\p"
	.string "Tôi có đội POKéMON của mình ở đây. Tôi\n"
	.string "muốn bạn cho biết con nào nên ra đầu\l"
	.string "tiên trong trận đấu.$"

gText_ApprenticeMonFirstThanks15::
	.string "{STR_VAR_1} của tôi sao... Bạn\n"
	.string "không trêu tôi đấy chứ?\p"
	.string "Tôi hiểu. Nếu là vậy thì cũng được. Cảm\n"
	.string "ơn bạn đã dành thời gian.\p"
	.string "Tôi vẫn là tôi như bạn thấy, nhưng tôi\n"
	.string "sẽ cố hết sức.\p"
	.string "Hẹn ngày gặp lại!$"

gText_ApprenticeWhichMon0::
	.string "Sụt sịt... Ôi, {PLAYER}!\p"
	.string "Bạn đến đúng lúc quá! Có chuyện tôi\n"
	.string "không sao quyết định được...\p"
	.string "Tôi không biết mình nên dùng POKéMON\n"
	.string "nào.\p"
	.string "Tôi không quyết định được giữa\n"
	.string "POKéMON {STR_VAR_1} và\l"
	.string "{STR_VAR_2}...\p"
	.string "{PLAYER}, bạn nghĩ con nào sẽ giúp\n"
	.string "ngay cả tôi cũng có cơ hội chiến thắng?$"

gText_ApprenticeMonThanks0::
	.string "Sụt sịt... Tôi... Tôi hiểu rồi! Ôi! Tôi xin\n"
	.string "lỗi! Bạn làm tôi vui đến phát khóc...\p"
	.string "Tôi sẽ cố hết sức để bắt một con\n"
	.string "{STR_VAR_1}!\p"
	.string "Cảm ơn bạn rất nhiều!$"

gText_ApprenticeWhichMon1::
	.string "Yay! Là {PLAYER}! Yay, bạn cũng đến\n"
	.string "đúng lúc quá! Tôi lại cần lời khuyên của\l"
	.string "bạn!\p"
	.string "Ừm, tôi rối hết cả lên, không biết nên\n"
	.string "dùng {STR_VAR_1} hay\l"
	.string "{STR_VAR_2}...\p"
	.string "Bạn nghĩ tôi nên nuôi con nào,\n"
	.string "{PLAYER}?$"

gText_ApprenticeMonThanks1::
	.string "Ồ, vậy {STR_VAR_1} của tôi tốt\n"
	.string "hơn! Được, tôi sẽ làm vậy!\p"
	.string "Cảm ơn bạn đã chỉ dạy!$"

gText_ApprenticeWhichMon2::
	.string "Xin chào, {PLAYER}! Tôi có một câu\n"
	.string "muốn hỏi bạn.\p"
	.string "Tôi đang khó xử không biết nên nuôi một\n"
	.string "con {STR_VAR_1} hay\l"
	.string "{STR_VAR_2}.\p"
	.string "Bạn nghĩ POKéMON nào sẽ mạnh hơn?$"

gText_ApprenticeMonThanks2::
	.string "Bạn chọn {STR_VAR_1} sao? Được,\n"
	.string "tôi hiểu rồi!\p"
	.string "Tôi sẽ đi bắt ngay một con\n"
	.string "{STR_VAR_1} thật mạnh!\p"
	.string "Hẹn gặp lại!$"

gText_ApprenticeWhichMon3::
	.string "Chào, {PLAYER}...\p"
	.string "Ừm, chắc cậu đã quên một người như tôi\n"
	.string "rồi...\p"
	.string "...Nhưng không sao, miễn là cậu chịu cho\n"
	.string "tôi lời khuyên...\p"
	.string "Tôi không thể quyết định nên nuôi loại\n"
	.string "POKéMON nào...\p"
	.string "Tôi đã thu hẹp lựa chọn còn POKéMON\n"
	.string "{STR_VAR_1} và\l"
	.string "{STR_VAR_2}, nhưng rồi lại bế\l"
	.string "tắc...\p"
	.string "{PLAYER}, chắc cậu chẳng muốn mất\n"
	.string "công đâu, nhưng xin hãy quyết định giúp\l"
	.string "tôi.$"

gText_ApprenticeMonThanks3::
	.string "Nhưng một {STR_VAR_1} hoang dã\n"
	.string "liệu có chịu để ý đến tôi không?\p"
	.string "Tôi sẽ thử!\p"
	.string "Nhưng liệu tôi có bắt nổi một con\n"
	.string "không... Không! Tôi sẽ cố hết sức!\p"
	.string "Cảm ơn cậu!$"

gText_ApprenticeWhichMon4::
	.string "Ôi, {PLAYER}{KUN}! Gặp cậu tôi mừng\n"
	.string "quá! Tôi đang định đi tìm cậu đây!\p"
	.string "Cậu quyết định giúp tôi nên dùng loại\n"
	.string "POKéMON nào được không?\p"
	.string "Ví dụ... POKéMON {STR_VAR_1} và\n"
	.string "{STR_VAR_2} thì sao?\p"
	.string "Cậu nghĩ con nào sẽ tốt hơn?$"

gText_ApprenticeMonThanks4::
	.string "{STR_VAR_1} à? Tuyệt quá!\p"
	.string "Vì chính {PLAYER}{KUN} đã quyết định\n"
	.string "nên dù thua tôi cũng sẽ không buồn lắm.\p"
	.string "Được rồi, lần sau tôi lại nhờ cậu tư vấn\n"
	.string "nhé. Tạm biệt!$"

gText_ApprenticeWhichMon5::
	.string "Chẳng phải {PLAYER}{KUN} đây sao! Dạo\n"
	.string "này thế nào? Tôi vẫn bận tối mắt như\l"
	.string "mọi khi!\p"
	.string "Tôi cũng muốn giỏi về POKéMON, nhưng\n"
	.string "mãi vẫn chưa quyết định được nên dùng\l"
	.string "POKéMON nào.\p"
	.string "{STR_VAR_1} trông mạnh lắm, đúng\n"
	.string "không? Nhưng {STR_VAR_2} cũng\l"
	.string "khó mà bỏ qua.\p"
	.string "{PLAYER}{KUN}, cho tôi lời khuyên hay\n"
	.string "ho đi! Con nào sẽ hợp với tôi?$"

gText_ApprenticeMonThanks5::
	.string "Được rồi, hiểu rồi. Tôi sẽ cố thu xếp\n"
	.string "thời gian để bắt một {STR_VAR_1}\l"
	.string "như cậu đề nghị.\p"
	.string "Tôi thật may mắn khi gặp được một\n"
	.string "người thầy tốt như cậu. Cảm ơn! Hẹn\l"
	.string "gặp lại!$"

gText_ApprenticeWhichMon6::
	.string "Ôi! Tuyệt, là {PLAYER}!\p"
	.string "Tôi đã khoe ngay với bạn bè chuyện\n"
	.string "mình gặp cậu rồi!\p"
	.string "Hôm nay tôi lại cần mượn trí tuệ của\n"
	.string "cậu. Với cậu thì câu này dễ thôi!\p"
	.string "Xin nổi trống lên! Câu hỏi của tôi là...\p"
	.string "Nếu tôi nuôi một POKéMON và phải chọn\n"
	.string "giữa {STR_VAR_1} với\l"
	.string "{STR_VAR_2}, tôi nên chọn con\l"
	.string "nào?$"

gText_ApprenticeMonThanks6::
	.string "A! Cậu chọn {STR_VAR_1} à! Cảm ơn\n"
	.string "vì câu trả lời cực ngầu!\p"
	.string "Chắc hôm nay tôi chỉ muốn hỏi cậu chừng\n"
	.string "đó thôi.\p"
	.string "Lần sau lại gặp nhau ở đây nhé? Cảm ơn!$"

gText_ApprenticeWhichMon7::
	.string "Ôi, là cậu sao, {PLAYER}? Tôi rất vui\n"
	.string "được gặp lại cậu!\p"
	.string "Từ khi trở thành học trò của cậu, tôi\n"
	.string "ngày càng tự tin hơn.\p"
	.string "Tôi nghĩ mình đã sẵn sàng tự nuôi một\n"
	.string "POKéMON rồi!\p"
	.string "{PLAYER}, tôi có thể phiền cậu chọn\n"
	.string "giúp POKéMON mình nên nuôi không?\p"
	.string "Hai lựa chọn là POKéMON\n"
	.string "{STR_VAR_1} và\l"
	.string "{STR_VAR_2}... POKéMON nào phù\l"
	.string "hợp với tôi?$"

gText_ApprenticeMonThanks7::
	.string "Vậy chọn {STR_VAR_1}! Tôi sẽ đi\n"
	.string "tìm ngay!\p"
	.string "Cảm ơn cậu, {PLAYER}. Mong rằng lần\n"
	.string "sau tôi vẫn có thể nhờ cậu. Bảo trọng\l"
	.string "nhé!$"

gText_ApprenticeWhichMon8::
	.string "Á! {PLAYER}! Tôi lại gặp cậu rồi! Tôi...\n"
	.string "tôi vui quá!\p"
	.string "Ôi-ôi-ôi, đúng rồi! Tôi không thể bỏ lỡ\n"
	.string "cơ hội này!\p"
	.string "Tôi có thể nhờ cậu một việc lớn không,\n"
	.string "{PLAYER}? Hãy chọn một POKéMON giúp\l"
	.string "tôi!\p"
	.string "Xin hãy quyết định xem\n"
	.string "{STR_VAR_1} hay\l"
	.string "{STR_VAR_2} sẽ tốt hơn!$"

gText_ApprenticeMonThanks8::
	.string "Oa! Cậu đã quyết định giúp tôi rồi! Tôi\n"
	.string "sẽ cố hết sức để nuôi một\l"
	.string "{STR_VAR_1} thật tốt.\p"
	.string "Hy vọng lần khác cậu vẫn sẵn lòng chỉ\n"
	.string "dạy tôi thêm.$"

gText_ApprenticeWhichMon9::
	.string "Này, này! Sư phụ {PLAYER}{KUN}!\p"
	.string "Xin chào, tôi đang tìm cậu để xin thêm\n"
	.string "vài lời vàng ngọc đây!\p"
	.string "Loại POKéMON nào hợp với tôi hơn,\n"
	.string "{STR_VAR_1} hay\l"
	.string "{STR_VAR_2}?\p"
	.string "Đừng ngại. Nói huỵch toẹt ra đi!$"

gText_ApprenticeMonThanks9::
	.string "Ừ-hử, vậy là {STR_VAR_1}! OK,\n"
	.string "A-OK! Tôi sẽ tóm một con vào BALL, cái\l"
	.string "rụp!\p"
	.string "Được rồi, như mọi khi, cảm ơn nhé!\n"
	.string "Adios!$"

gText_ApprenticeWhichMon10::
	.string "{PLAYER}{KUN}, nghe này! Tin động\n"
	.string "trời! Tôi đã bắt được một POKéMON ảo\l"
	.string "ảnh!\p"
	.string "Tất nhiên là tôi nói dối! Wahahaha!\p"
	.string "Nhưng chuyện này thì không nói dối\n"
	.string "đâu. Tôi bắt POKéMON không giỏi lắm.\p"
	.string "Vậy sư phụ quyết định giúp tôi nên bắt\n"
	.string "loại POKéMON nào nhé?\p"
	.string "Con nào sẽ tốt hơn? {STR_VAR_1}\n"
	.string "hay {STR_VAR_2}?$"

gText_ApprenticeMonThanks10::
	.string "Được rồi, sư phụ chọn\n"
	.string "{STR_VAR_1} à? Vậy tôi sẽ bắt\l"
	.string "loại còn lại!\p"
	.string "Đùa thôi! Tôi sẽ nghe lời dạy của sư\n"
	.string "phụ!\p"
	.string "Cảm ơn sư phụ! Mong sư phụ tiếp tục\n"
	.string "chỉ dạy tôi!$"

gText_ApprenticeWhichMon11::
	.string "A-H-O-Y! Đánh vần là ahoy!\p"
	.string "Ta là SAILOR rap vần! Chắc cậu vẫn nhớ\n"
	.string "ta chứ, đúng không nào?\p"
	.string "Hôm nay có chuyện POKéMON, mong cậu\n"
	.string "góp ý cho tròn!\p"
	.string "Giữa {STR_VAR_1} và\n"
	.string "{STR_VAR_2}, cậu thấy ta nên bắt\l"
	.string "con nào?$"

gText_ApprenticeMonThanks11::
	.string "{STR_VAR_1}, cậu bảo thế, hey,\n"
	.string "hey! Ta sẽ đi bắt ngay đây!\p"
	.string "Hễ cần lời khuyên, {PLAYER}, lời cậu\n"
	.string "ta luôn nghe!$"

gText_ApprenticeWhichMon12::
	.string "Ồ, chẳng phải {PLAYER} đây sao!\p"
	.string "Tôi nên làm gì nhỉ? Xin lời khuyên của\n"
	.string "bạn ư? Sao lại không? Tôi đã nói chuyện\l"
	.string "với bạn rồi mà!\p"
	.string "Lâu rồi không gặp. Để tôi phá tan sự\n"
	.string "ngượng ngùng nhé. Tôi cũng đang cần\l"
	.string "lời khuyên! Bạn có nghe rõ không? Nghe\l"
	.string "rõ rồi nhé!\p"
	.string "POKéMON của tôi nên dùng con nào?\n"
	.string "{STR_VAR_1} hay\l"
	.string "{STR_VAR_2}? Bạn chọn con nào?$"

gText_ApprenticeMonThanks12::
	.string "Nếu {STR_VAR_1} là lựa chọn tốt\n"
	.string "nhất, tôi sẽ làm như bạn nói!\p"
	.string "Nào, {PLAYER}, tôi phải tiếp tục phiêu\n"
	.string "du, nhưng đừng quên tôi nhé.\p"
	.string "Hẹn gặp lại, người bạn thông thái!$"

gText_ApprenticeWhichMon13::
	.string "Ồ, chào {PLAYER}{KUN}... Tôi đau đầu\n"
	.string "kinh khủng...\p"
	.string "Chắc tại tôi lo nghĩ quá nhiều về loại\n"
	.string "POKéMON mình nên nuôi.\p"
	.string "Thành ra thế này, tôi cần cậu quyết\n"
	.string "định giúp.\p"
	.string "{PLAYER}{KUN}, nếu phải chọn giữa\n"
	.string "POKéMON {STR_VAR_1} và\l"
	.string "{STR_VAR_2}, tôi nên chọn con\l"
	.string "nào?$"

gText_ApprenticeMonThanks13::
	.string "Ừm, vậy chọn {STR_VAR_1}. Khi\n"
	.string "khỏe lại tôi sẽ đi tìm một con.\p"
	.string "Hy vọng tôi vẫn có thể tiếp tục nhờ cậu\n"
	.string "giúp như thế này.$"

gText_ApprenticeWhichMon14::
	.string "Ơ... Ừm... {PLAYER}{KUN}...?\p"
	.string "Xin đừng nhìn tôi như thế. Tôi bối rối\n"
	.string "hết cả lên... Tôi... tôi cần lời khuyên của\l"
	.string "cậu.\p"
	.string "Tôi... tôi xấu hổ lắm, nhưng không thể\n"
	.string "quyết định nên dùng POKéMON nào.\p"
	.string "Nếu phải chọn giữa {STR_VAR_1}\n"
	.string "và {STR_VAR_2}, con nào sẽ tốt\l"
	.string "hơn?$"

gText_ApprenticeMonThanks14::
	.string "Ồ... Được rồi! Tôi sẽ cố hết sức với một\n"
	.string "{STR_VAR_1}.\p"
	.string "Hy vọng tôi có thể làm tốt mà không bối\n"
	.string "rối quá.\p"
	.string "Cảm ơn cậu, {PLAYER}{KUN}. Nếu gặp lại,\n"
	.string "mong cậu vẫn sẽ nhiệt tình giúp tôi.$"

gText_ApprenticeWhichMon15::
	.string "Hửm? Trông bạn có vẻ là\n"
	.string "{PLAYER}{KUN}... Nhưng bạn có thật sự\l"
	.string "tồn tại không?\p"
	.string "Không, không, nếu bạn là người thật thì\n"
	.string "được rồi. Nhân tiện, tôi muốn xin lời\l"
	.string "khuyên của bạn.\p"
	.string "Là về POKéMON mà tôi sẽ sử dụng.\p"
	.string "Nếu phải chọn giữa POKéMON\n"
	.string "{STR_VAR_1} và\l"
	.string "{STR_VAR_2}, con nào xứng tầm\l"
	.string "với tôi hơn?$"

gText_ApprenticeMonThanks15::
	.string "{STR_VAR_1} ư? Bạn chắc chứ?\p"
	.string "Tôi hiểu rồi. Nếu vậy thì được. Cảm ơn\n"
	.string "bạn đã dành thời gian.\p"
	.string "Tôi chỉ mong ngay cả mình cũng có thể\n"
	.string "sử dụng nó thật ung dung.\p"
	.string "Hẹn gặp lại!$"

gText_ApprenticeWhichMove0::
	.string "Hu hu! Ôi, {PLAYER}! Khụt khịt... Nấc...\p"
	.string "Tôi đang khó xử lắm! Tôi không thể chọn\n"
	.string "chiêu cho {STR_VAR_1} của mình...\p"
	.string "Xin cậu đấy, {PLAYER}. Cậu quyết định\n"
	.string "giúp tôi được không?\p"
	.string "Với {STR_VAR_1} của tôi, chiêu\n"
	.string "nào sẽ tốt hơn: {STR_VAR_2} hay\l"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks0::
	.string "{STR_VAR_1} ư? Hu hu hu!\p"
	.string "Ôi! Tôi xin lỗi, {PLAYER}! Cậu quyết\n"
	.string "định chiêu giúp tôi khiến tôi vui quá\l"
	.string "nên bật khóc...\p"
	.string "Khụt khịt... Cảm ơn cậu rất nhiều!$"

gText_ApprenticeWhichMove1::
	.string "Tuyệt! Chào {PLAYER}! Tôi lại cần lời\n"
	.string "khuyên của cậu!\p"
	.string "Tôi muốn dạy cho {STR_VAR_1} của\n"
	.string "mình một chiêu thật ngầu.\p"
	.string "Tôi thích cả {STR_VAR_2} lẫn\n"
	.string "{STR_VAR_3}. Cậu đề nghị chiêu\l"
	.string "nào?$"

gText_ApprenticeMoveThanks1::
	.string "{STR_VAR_1} tốt hơn à? Chắc vậy\n"
	.string "rồi! Được, tôi sẽ chọn chiêu đó!\p"
	.string "Nếu lại gặp nhau ở đây, xin hãy dạy tôi\n"
	.string "thêm điều khác nhé, thầy!$"

gText_ApprenticeWhichMove2::
	.string "{PLAYER}, xin chào! Tôi đang lo về các\n"
	.string "chiêu của {STR_VAR_1}.\p"
	.string "Cụ thể là hai chiêu {STR_VAR_2}\n"
	.string "và {STR_VAR_3}.\p"
	.string "Chiêu nào mạnh hơn và phù hợp với\n"
	.string "{STR_VAR_1} của tôi hơn?$"

gText_ApprenticeMoveThanks2::
	.string "Cậu chọn {STR_VAR_1} à? Được,\n"
	.string "tôi hiểu rồi!\p"
	.string "Tôi sẽ đi dạy {STR_VAR_1} cho\n"
	.string "POKéMON của mình ngay!\p"
	.string "Hẹn gặp lại!$"

gText_ApprenticeWhichMove3::
	.string "Ôi, {PLAYER}... Tôi thật vô dụng, thật\n"
	.string "đấy!\p"
	.string "Tôi đã quyết định nuôi một POKéMON, vậy\n"
	.string "mà đến chiêu nên cho nó học cũng không\l"
	.string "chọn nổi...\p"
	.string "Tôi biết chuyện này chẳng có ý nghĩa gì\n"
	.string "với cậu, {PLAYER}.\p"
	.string "Nhưng với tôi thì rất quan trọng...\p"
	.string "Xin cậu, {PLAYER}, hãy chọn một chiêu\n"
	.string "cho {STR_VAR_1} của tôi được\l"
	.string "không?\p"
	.string "Chỉ cần chọn giữa {STR_VAR_2} và\n"
	.string "{STR_VAR_3} thôi...$"

gText_ApprenticeMoveThanks3::
	.string "Tôi hiểu rồi!\p"
	.string "Nhưng liệu nó có chịu học\n"
	.string "{STR_VAR_1} vì tôi không...\l"
	.string "Không! Tôi sẽ cố hết sức!\p"
	.string "Cảm ơn cậu!$"

gText_ApprenticeWhichMove4::
	.string "Ôi, {PLAYER}{KUN}! Tôi cũng đang mong\n"
	.string "được gặp cậu đây!\p"
	.string "Tôi đang suy nghĩ xem chiêu nào sẽ phù\n"
	.string "hợp với {STR_VAR_1} của mình.\p"
	.string "Tôi không quyết định được, nên cậu\n"
	.string "quyết định thay tôi nhé?\p"
	.string "Ví dụ... Hai chiêu {STR_VAR_2} và\n"
	.string "{STR_VAR_3} thì sao? Chiêu nào\l"
	.string "sẽ tốt hơn?$"

gText_ApprenticeMoveThanks4::
	.string "{STR_VAR_1} à? Tuyệt quá!\p"
	.string "Vì chính {PLAYER}{KUN} đã quyết định\n"
	.string "nên dù thua tôi cũng sẽ không buồn lắm.\p"
	.string "Được rồi, lần sau tôi lại nhờ cậu tư vấn\n"
	.string "nhé. Tạm biệt!$"

gText_ApprenticeWhichMove5::
	.string "Sao mà bận đến thế này? Này, chẳng phải\n"
	.string "{PLAYER}{KUN} đây sao! Dạo này thế\l"
	.string "nào?\p"
	.string "Từ lúc thức dậy sáng nay, tôi đã chạy\n"
	.string "bộ, bơi lội rồi nấu ăn!\p"
	.string "Cậu không tưởng tượng nổi tôi bận thế\n"
	.string "nào đâu!\p"
	.string "Tôi còn chẳng quyết định nổi nên cho\n"
	.string "{STR_VAR_1} học chiêu gì!\p"
	.string "{STR_VAR_2} có vẻ tốt nhỉ?\n"
	.string "Nhưng {STR_VAR_3} cũng khá ổn.\p"
	.string "{PLAYER}{KUN}, cho tôi lời khuyên hay\n"
	.string "ho đi! Chiêu nào sẽ hợp với tôi?$"

gText_ApprenticeMoveThanks5::
	.string "Được rồi, hiểu rồi. Tôi sẽ thu xếp lịch\n"
	.string "để dạy chiêu đó.\p"
	.string "Tôi thật may mắn khi gặp được một\n"
	.string "người thầy tốt như cậu. Cảm ơn! Hẹn\l"
	.string "gặp lại!$"

gText_ApprenticeWhichMove6::
	.string "Ôi! May quá! Tôi lại gặp cậu rồi,\n"
	.string "{PLAYER}! Hôm nay tôi lại cần mượn\l"
	.string "trí tuệ của cậu.\p"
	.string "Xin nổi trống lên! Câu hỏi của tôi là...\p"
	.string "Với {STR_VAR_1} của tôi, chiêu\n"
	.string "nào phù hợp nhất, {STR_VAR_2}\l"
	.string "hay {STR_VAR_3}?$"

gText_ApprenticeMoveThanks6::
	.string "A! Cậu chọn {STR_VAR_1} à! Cảm ơn\n"
	.string "vì câu trả lời cực ngầu!\p"
	.string "Chắc hôm nay tôi chỉ muốn hỏi cậu chừng\n"
	.string "đó thôi.\p"
	.string "Lần sau lại gặp nhau ở đây nhé? Cảm ơn!$"

gText_ApprenticeWhichMove7::
	.string "Ồ, xin chào {PLAYER}. Dạo này cậu vẫn\n"
	.string "khỏe chứ?\p"
	.string "Tôi lại phải xin lời khuyên của cậu. Là\n"
	.string "về {STR_VAR_1} yêu quý của tôi.\p"
	.string "Chiêu lý tưởng cho {STR_VAR_1}\n"
	.string "đáng yêu của tôi là gì?\l"
	.string "{STR_VAR_2} hay\l"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks7::
	.string "Vậy chọn {STR_VAR_1}! Tôi sẽ dạy\n"
	.string "chiêu đó ngay!\p"
	.string "Cảm ơn cậu, {PLAYER}. Mong rằng lần\n"
	.string "sau tôi vẫn có thể nhờ cậu. Bảo trọng\l"
	.string "nhé!$"

gText_ApprenticeWhichMove8::
	.string "Á! {PLAYER}! Tôi lại gặp cậu rồi! Tôi...\n"
	.string "tôi vui quá!\p"
	.string "Mỗi khi tôi cần giúp đỡ, cậu luôn xuất\n"
	.string "hiện, {PLAYER}!\p"
	.string "Hôm nay tôi muốn cậu đề nghị cho tôi một\n"
	.string "chiêu!\p"
	.string "Xin hãy chọn một chiêu cho\n"
	.string "{STR_VAR_1} của tôi!\p"
	.string "Chiêu nào sẽ tốt hơn,\n"
	.string "{STR_VAR_2} hay\l"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks8::
	.string "Ôi-ôi-ôi! Cảm ơn cậu! Vậy là\n"
	.string "{STR_VAR_1}! Tôi hiểu hoàn toàn\l"
	.string "rồi!\p"
	.string "Hy vọng lần khác cậu vẫn sẵn lòng chỉ\n"
	.string "dạy tôi thêm.$"

gText_ApprenticeWhichMove9::
	.string "Hola, {PLAYER}{KUN}, bueno! Hôm nay\n"
	.string "tôi lại mong được nghe vài lời vàng\l"
	.string "ngọc của cậu!\p"
	.string "Chiêu nào sẽ tốt nhất cho\n"
	.string "{STR_VAR_1} của tôi?\p"
	.string "Phải là chiêu giúp tôi thắng cái rụp mới\n"
	.string "được!\p"
	.string "{STR_VAR_2} chăng? Hay là\n"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks9::
	.string "Ừ-hử, vậy là {STR_VAR_1}! Si,\n"
	.string "bueno! Tôi sẽ dạy nó ngay, cái rầm!\p"
	.string "Được rồi, như mọi khi, cảm ơn nhé!\n"
	.string "Adios!$"

gText_ApprenticeWhichMove10::
	.string "{PLAYER}{KUN}, chuyện này điên rồ lắm!\p"
	.string "POKéMON của tôi đã học được sáu chiêu!\p"
	.string "Tất nhiên là tôi nói dối! Wahahaha!\p"
	.string "Nhưng chuyện này thì không nói dối\n"
	.string "đâu. Tôi chọn chiêu cho POKéMON không\l"
	.string "giỏi lắm.\p"
	.string "Vậy cậu quyết định giúp tôi nên dạy loại\n"
	.string "chiêu nào nhé?\p"
	.string "{STR_VAR_2} hay\n"
	.string "{STR_VAR_3}, chiêu nào hợp với\l"
	.string "{STR_VAR_1} của tôi nhất?$"

gText_ApprenticeMoveThanks10::
	.string "Được rồi, sư phụ chọn\n"
	.string "{STR_VAR_1} à? Vậy tôi sẽ chọn\l"
	.string "chiêu khác!\p"
	.string "Đùa thôi! Tôi sẽ nghe lời dạy của sư\n"
	.string "phụ!\p"
	.string "Cảm ơn sư phụ! Mong sư phụ tiếp tục\n"
	.string "chỉ dạy tôi!$"

gText_ApprenticeWhichMove11::
	.string "A-H-O-Y! Đánh vần là ahoy!\p"
	.string "Ta là SAILOR rap vần! Luôn bắt kịp thời\n"
	.string "đại, chẳng cần hỏi nguyên nhân.\p"
	.string "Hôm nay có chuyện về chiêu, mong cậu\n"
	.string "góp ý một điều!\p"
	.string "{STR_VAR_2} và\n"
	.string "{STR_VAR_3} là hai chiêu đang cân\l"
	.string "nhắc. Chiêu nào giúp {STR_VAR_1}\l"
	.string "của ta bắt nhịp tuyệt nhất?$"

gText_ApprenticeMoveThanks11::
	.string "{STR_VAR_1}, cậu bảo thế, hey,\n"
	.string "hey! Ta sẽ dạy nó ngay đây!\p"
	.string "Hễ cần lời khuyên, {PLAYER}, lời cậu\n"
	.string "ta luôn nghe!$"

gText_ApprenticeWhichMove12::
	.string "Ồ, yeahah, chẳng phải {PLAYER} đây\n"
	.string "sao!\p"
	.string "Tôi nên làm gì nhỉ? Xin lời khuyên của\n"
	.string "bạn ư? Sao lại không? Tôi đã nói chuyện\l"
	.string "với bạn rồi mà!\p"
	.string "{PLAYER}, bạn có ngạc nhiên không?\n"
	.string "Tôi cần lời khuyên, thấy rõ rồi đúng\l"
	.string "không?\p"
	.string "Bạn có nghe rõ không? Nghe rõ rồi nhé!\p"
	.string "{STR_VAR_1} của tôi nên dùng\n"
	.string "chiêu nào? {STR_VAR_2} hay\l"
	.string "{STR_VAR_3}, bạn chọn sao?$"

gText_ApprenticeMoveThanks12::
	.string "Nếu {STR_VAR_1} là lựa chọn tốt\n"
	.string "nhất, tôi sẽ làm như bạn nói!\p"
	.string "Nào, {PLAYER}, tôi phải tiếp tục phiêu\n"
	.string "du, nhưng đừng quên tôi nhé.\p"
	.string "Hẹn gặp lại, người bạn thông thái!$"

gText_ApprenticeWhichMove13::
	.string "Khặc! Khụ! Ôi, {PLAYER}{KUN}... Tôi bị\n"
	.string "cảm nặng mất rồi...\p"
	.string "Tôi muốn chọn một chiêu cho POKéMON,\n"
	.string "nhưng giờ không đủ sức...\p"
	.string "Thành ra thế này, tôi cần cậu quyết\n"
	.string "định giúp.\p"
	.string "{PLAYER}{KUN}, nếu phải chọn giữa\n"
	.string "{STR_VAR_2} và\l"
	.string "{STR_VAR_3} cho\l"
	.string "{STR_VAR_1} của tôi, cậu sẽ chọn\l"
	.string "chiêu nào?$"

gText_ApprenticeMoveThanks13::
	.string "Ừm, vậy là {STR_VAR_1}. Khụ! Khi\n"
	.string "khỏe lại tôi sẽ đi dạy chiêu đó.\p"
	.string "Hy vọng tôi vẫn có thể tiếp tục nhờ cậu\n"
	.string "giúp như thế này.$"

gText_ApprenticeWhichMove14::
	.string "Ơ... Ừm... {PLAYER}{KUN}...?\p"
	.string "Xin đừng nhìn tôi như thế. Tôi bối rối\n"
	.string "hết cả lên... Tôi... tôi cần lời khuyên của\l"
	.string "cậu.\p"
	.string "Tôi... tôi xấu hổ lắm, nhưng không thể\n"
	.string "quyết định nên dạy POKéMON của mình\l"
	.string "chiêu nào.\p"
	.string "Là cho {STR_VAR_1} của tôi. Nếu\n"
	.string "phải chọn giữa {STR_VAR_2} và\l"
	.string "{STR_VAR_3}, chiêu nào sẽ tốt\l"
	.string "hơn?$"

gText_ApprenticeMoveThanks14::
	.string "Ồ... Được rồi! Tôi sẽ thử\n"
	.string "{STR_VAR_1}.\p"
	.string "Hy vọng tôi dạy được chiêu đó... Căng\n"
	.string "thẳng quá...\p"
	.string "Cảm ơn cậu, {PLAYER}{KUN}. Nếu gặp lại,\n"
	.string "mong cậu vẫn sẽ nhiệt tình giúp tôi.$"

gText_ApprenticeWhichMove15::
	.string "Hửm? Trông bạn có vẻ là\n"
	.string "{PLAYER}{KUN}... Nhưng bạn có thật sự\l"
	.string "tồn tại không?\p"
	.string "Hay bạn là một trong những kẻ bắt\n"
	.string "chước đang nổi tiếng đó?\p"
	.string "Không, không, nếu bạn là người thật thì\n"
	.string "được rồi. Tôi cam đoan bạn không cần\l"
	.string "nổi giận!\p"
	.string "Nhân tiện, tôi muốn xin lời khuyên của\n"
	.string "bạn.\p"
	.string "Là về {STR_VAR_1} của tôi.\p"
	.string "Nó dùng chiêu nào sẽ tốt hơn,\n"
	.string "{STR_VAR_2} hay\l"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks15::
	.string "{STR_VAR_1} ư? Hoàn toàn không\n"
	.string "cần bàn cãi sao?\p"
	.string "Tôi hiểu rồi. Nếu vậy thì được. Cảm ơn\n"
	.string "bạn đã dành thời gian.\p"
	.string "Tôi chỉ mong ngay cả POKéMON của mình\n"
	.string "cũng có thể học được chiêu đó.\p"
	.string "Hẹn gặp lại!$"

gText_ApprenticePickWinSpeech0::
	.string "Ôi... {PLAYER} ư? Đúng là {PLAYER}!\n"
	.string "Ôi! Khụt khịt... hu hu... Xin hãy nghe tôi!\p"
	.string "Tôi... Khi chiến đấu, tôi căng thẳng đến\n"
	.string "mức dù thắng vẫn không ngăn được\l"
	.string "nước mắt...\p"
	.string "Tôi ước mình có thể nói điều gì đó thật\n"
	.string "ngầu khi chiến thắng...\p"
	.string "Xin cậu đấy, {PLAYER}! Cậu có thể dạy\n"
	.string "tôi một câu thật ngầu để nói khi thắng,\l"
	.string "giúp tôi không khóc nữa không?$"

gText_ApprenticeWinSpeechThanks0::
	.string "{STR_VAR_1}\p"
	.string "Đỉnh quá! Tuyệt cú mèo! A hú! Ngầu\n"
	.string "thật!\p"
	.string "Ôi... Tôi xin lỗi... Tôi vui quá nên bật\n"
	.string "khóc...\p"
	.string "Khụt khịt... {PLAYER}! Cảm ơn cậu rất\n"
	.string "nhiều vì tất cả!\p"
	.string "Vì cậu, tôi sẽ cố gắng chiến đấu hết\n"
	.string "sức, {PLAYER}!\p"
	.string "{PLAYER}... Lần tới... Chúng ta hãy\n"
	.string "chiến đấu nhé!$"

gText_ApprenticePickWinSpeech1::
	.string "Tuyệt! Là {PLAYER}! Xin chào! Tôi muốn\n"
	.string "hỏi cậu một chuyện!\p"
	.string "Tôi muốn nói điều gì đó thật ngầu khi\n"
	.string "thắng trận.\p"
	.string "Cậu có câu nào hay ho để đề nghị không?$"

gText_ApprenticeWinSpeechThanks1::
	.string "{STR_VAR_1}\p"
	.string "Oa! Ngầu quá! Được, tôi sẽ nói câu đó!\p"
	.string "Cảm ơn vì suốt thời gian qua đã chỉ dạy\n"
	.string "tôi! Từ giờ, dù đi đâu tôi cũng sẽ cố\l"
	.string "hết sức!\p"
	.string "Lần sau gặp lại, chúng ta sẽ chiến đấu!$"

gText_ApprenticePickWinSpeech2::
	.string "{PLAYER}, xin chào!\p"
	.string "POKéMON của tôi và tôi đã sẵn sàng đối\n"
	.string "mặt với mọi thứ, ngoại trừ một việc.\p"
	.string "Tôi nghĩ sẽ rất hay nếu có một câu để hô\n"
	.string "lên khi chiến thắng.\p"
	.string "Cậu nghĩ giúp tôi một câu hay được\n"
	.string "không?$"

gText_ApprenticeWinSpeechThanks2::
	.string "{STR_VAR_1}\p"
	.string "...Ngầu đấy! Tôi sẽ dùng câu đó!\p"
	.string "Tôi sẽ lên đường chiến đấu khắp mọi\n"
	.string "nơi.\p"
	.string "Biết đâu một ngày nào đó tôi còn được\n"
	.string "chiến đấu với cậu, {PLAYER}.\p"
	.string "Lần tới, hãy gặp nhau tại đấu trường\n"
	.string "nhé!$"

gText_ApprenticePickWinSpeech3::
	.string "Chào {PLAYER}... Xin lỗi vì lại làm\n"
	.string "phiền, nhưng tôi thật vô dụng...\p"
	.string "Ngay cả khi... Ngay cả khi chiến thắng,\n"
	.string "tôi cũng chẳng có câu gì đặc biệt để\l"
	.string "nói...\p"
	.string "Tôi biết chuyện này chẳng có ý nghĩa gì\n"
	.string "với cậu, {PLAYER}.\p"
	.string "Nhưng với tôi thì rất quan trọng...\p"
	.string "Xin cậu, {PLAYER}, nếu thắng một trận\n"
	.string "thì tôi nên nói gì?$"

gText_ApprenticeWinSpeechThanks3::
	.string "{STR_VAR_1}\p"
	.string "Thật đầy cảm hứng...\p"
	.string "Ừm... Một người như tôi thật sự có thể\n"
	.string "nói câu đó sao?\p"
	.string "Không! Tôi sẽ cố hết sức!\p"
	.string "{PLAYER}, cảm ơn cậu rất nhiều vì đã\n"
	.string "chịu đựng tôi suốt thời gian qua...\p"
	.string "Tôi hứa từ giờ sẽ cố hết sức.\p"
	.string "Chắc cậu sẽ nhanh chóng quên một\n"
	.string "người như tôi, nhưng mong chúng ta lại\l"
	.string "gặp nhau ở đâu đó!$"

gText_ApprenticePickWinSpeech4::
	.string "Ồ, {PLAYER}{KUN}. Có chuyện này tôi\n"
	.string "muốn cậu nghe.\p"
	.string "Tôi biết mình không phải lúc nào cũng ăn\n"
	.string "nói dễ nghe hay lịch sự...\p"
	.string "Khi thắng một trận, tôi nghĩ mình tỏ ra\n"
	.string "khá kiêu ngạo.\p"
	.string "Tôi không muốn bị người khác ghét, nên\n"
	.string "muốn nói điều gì đó tử tế với người\l"
	.string "mình đánh bại.\p"
	.string "Nhưng tôi chẳng nghĩ ra được câu nào\n"
	.string "hay! Cậu nghĩ giúp tôi nhé?$"

gText_ApprenticeWinSpeechThanks4::
	.string "{STR_VAR_1}\p"
	.string "Không tệ! Phải, tôi sẽ chọn câu đó!\p"
	.string "Tôi sẽ lên đường, ghi lòng tạc dạ những\n"
	.string "điều cậu đã dạy và cố gắng hết sức.\p"
	.string "Xin lỗi vì suốt thời gian qua tôi đã ép\n"
	.string "cậu nhiều quá!\p"
	.string "Lần tới chúng ta chiến đấu nhé? Tạm\n"
	.string "biệt!$"

gText_ApprenticePickWinSpeech5::
	.string "Ôi, tôi bận đến phát ngán mất! À, tôi\n"
	.string "đang tìm cậu đấy, {PLAYER}{KUN}.\p"
	.string "Cậu vẫn khỏe như mọi khi chứ? Tôi thì\n"
	.string "chẳng có gì thay đổi.\p"
	.string "Tôi phải chạy, chiến đấu rồi vẽ bản đồ.\n"
	.string "Sao tôi lại bận đến thế nhỉ?\p"
	.string "Nhưng dù bận, thắng xong mà cứ quay\n"
	.string "gót bỏ đi chẳng nói lời nào thì thật bất\l"
	.string "lịch sự.\p"
	.string "Vậy khi xong việc và bước đi, tôi nên\n"
	.string "nói câu gì thật ngầu để càng làm nổi bật\l"
	.string "vẻ ngầu của mình? {PLAYER}{KUN}, giúp\l"
	.string "tôi!$"

gText_ApprenticeWinSpeechThanks5::
	.string "{STR_VAR_1}\p"
	.string "Được rồi, hiểu rồi. Tôi vẫn thu xếp\n"
	.string "được thời gian để nói câu đó!\p"
	.string "Thật lòng mà nói, tôi rất vui vì gặp\n"
	.string "được một người thầy tốt như cậu.\p"
	.string "Tôi sẽ cố thu xếp thời gian để tham gia\n"
	.string "chiến đấu.\p"
	.string "Cảm ơn vì tất cả, {PLAYER}{KUN}! Một\n"
	.string "ngày nào đó, cậu và tôi nhất định phải\l"
	.string "chiến đấu!$"

gText_ApprenticePickWinSpeech6::
	.string "Tôi lại gặp may rồi! {PLAYER}! Gặp cậu\n"
	.string "tôi mừng quá! Như mọi khi, tôi cần lời\l"
	.string "khuyên của cậu!\p"
	.string "Xin nổi trống lên! Câu hỏi cuối cùng của\n"
	.string "tôi là...\p"
	.string "Nếu thắng một trận và muốn kết thúc\n"
	.string "thật hoành tráng, tôi nên nói gì?$"

gText_ApprenticeWinSpeechThanks6::
	.string "{STR_VAR_1}\p"
	.string "Câu... câu đó tuyệt vời quá! Vừa đĩnh\n"
	.string "đạc vừa ngầu! Tôi xin nhận!\p"
	.string "...Nghe này, tôi nghĩ mình cũng khá lên\n"
	.string "rồi, đúng không?\p"
	.string "Vì vậy, từ giờ tôi định đi thách đấu\n"
	.string "các HLV khác.\p"
	.string "{PLAYER}, lời khuyên của cậu thật sự\n"
	.string "đã giúp tôi rất nhiều.\p"
	.string "Có lẽ một ngày nào đó chúng ta sẽ chiến\n"
	.string "đấu với nhau!\p"
	.string "Cảm ơn cậu vì tất cả!$"

gText_ApprenticePickWinSpeech7::
	.string "Ôi, {PLAYER}. Tôi thật may mắn khi gặp\n"
	.string "được cậu!\p"
	.string "Tôi không còn điều gì phải lo về\n"
	.string "POKéMON của mình nữa.\p"
	.string "Người khiến tôi lo lắng lại là chính\n"
	.string "mình...\p"
	.string "Cậu biết một HLV thường nói vài\n"
	.string "câu sau khi thắng trận chứ?\p"
	.string "Tôi nhất định cũng muốn làm như thế!\p"
	.string "Xin cậu cho biết, khi thắng trận tôi nên\n"
	.string "nói gì?$"

gText_ApprenticeWinSpeechThanks7::
	.string "{STR_VAR_1}\p"
	.string "A! Câu nói đó! Nó khiến tôi sảng khoái\n"
	.string "như được tái sinh!\p"
	.string "Tôi phải dùng nó ngay mới được!\p"
	.string "Và giờ tôi phải cáo từ, {PLAYER}...\p"
	.string "Tôi sẽ lên đường chiến đấu với nhiều\n"
	.string "người, nhưng không bao giờ quên những\l"
	.string "điều cậu đã dạy.\p"
	.string "Có lẽ một ngày nào đó... Tạm biệt!$"

gText_ApprenticePickWinSpeech8::
	.string "Á! Tôi thấy {PLAYER} rồi! Tôi... tôi vui\n"
	.string "mừng khôn xiết khi gặp cậu!\p"
	.string "Ôi-ôi-ôi! Có chuyện này tôi nhất định\n"
	.string "phải hỏi cậu!\p"
	.string "Cách đây không lâu, tôi đã thắng một\n"
	.string "trận. Lúc ấy phấn khích lắm!\p"
	.string "Nhưng tôi vui quá đến nghẹn lời, chẳng\n"
	.string "nói được gì cả!\p"
	.string "Vậy nên, {PLAYER}, xin cậu hãy nghĩ\n"
	.string "giúp tôi một câu kết để nói khi chiến\l"
	.string "thắng!$"

gText_ApprenticeWinSpeechThanks8::
	.string "{STR_VAR_1}\p"
	.string "Hu hu hu! Tôi sẽ được nói câu đó sao?!\n"
	.string "Tôi... tôi vui đến phát cuồng!\p"
	.string "C-c-cảm ơn cậu! Giờ tôi không còn gì\n"
	.string "phải tiếc nuối nữa!\p"
	.string "Tôi sẽ lên đường và chiến đấu với đủ\n"
	.string "mọi người.\p"
	.string "Tất cả đều nhờ cậu, {PLAYER}. Thật\n"
	.string "sự, thật sự cảm ơn cậu!\p"
	.string "Giờ tôi phải đi, nhưng một ngày nào đó\n"
	.string "hãy gặp nhau trong trận đấu nhé!$"

gText_ApprenticePickWinSpeech9::
	.string "Hola, bueno! {PLAYER}{KUN}!\p"
	.string "Cậu biết không, tôi đang ngứa ngáy\n"
	.string "muốn lên đường và chiến đấu khắp nơi\l"
	.string "rồi.\p"
	.string "Nhưng trước khi đi, xin hãy cho tôi lời\n"
	.string "khuyên thêm một lần nữa!\p"
	.string "Nếu thắng một trận, tôi nên khoe khoang\n"
	.string "câu gì với HLV đối thủ đã bại trận?$"

gText_ApprenticeWinSpeechThanks9::
	.string "{STR_VAR_1}\p"
	.string "Ừ-hử, tuyệt đấy! Si, bueno! Tôi sẽ thử\n"
	.string "nói câu đó, cái rầm!\p"
	.string "Và giờ đã đến lúc tạm biệt! Cảm ơn vì\n"
	.string "đủ mọi chuyện nhé!\p"
	.string "Một ngày nào đó hãy đấu với tôi, OK?\n"
	.string "Adios!$"

gText_ApprenticePickWinSpeech10::
	.string "{PLAYER}{KUN}, nguy to rồi!\p"
	.string "Mỗi khi thắng trận, tôi khoe khoang ít\n"
	.string "nhất một tiếng!\p"
	.string "Tất nhiên là tôi nói dối! Wahahaha!\p"
	.string "Nhưng chuyện này thì không nói dối\n"
	.string "đâu. Tôi ăn nói không giỏi lắm.\p"
	.string "Vậy sư phụ quyết định giúp tôi nên nói\n"
	.string "gì sau khi thắng trận nhé?$"

gText_ApprenticeWinSpeechThanks10::
	.string "{STR_VAR_1}\p"
	.string "Tôi nên nói câu đó à? Vậy tôi sẽ tránh\n"
	.string "xa nó!\p"
	.string "Đùa thôi! Tôi sẽ nghe lời dạy của sư\n"
	.string "phụ!\p"
	.string "Cảm ơn sư phụ đã chỉ dạy tôi suốt thời\n"
	.string "gian qua!\p"
	.string "Cuối cùng tôi cũng bắt đầu hiểu làm\n"
	.string "HLV là thế nào.\p"
	.string "Tôi sẽ lên đường và chiến thắng bất kỳ\n"
	.string "HLV nào.\p"
	.string "Có thể một ngày nào đó người đó sẽ là\n"
	.string "sư phụ!\p"
	.string "Chỉ vậy thôi! Vĩnh biệt, sư phụ của tôi!$"

gText_ApprenticePickWinSpeech11::
	.string "A-H-O-Y! Đánh vần là ahoy!\p"
	.string "Ta là SAILOR rap vần! Đây là câu cuối,\n"
	.string "xin đừng khóc rần!\p"
	.string "Một câu nói hay đang cần cậu góp ý\n"
	.string "ngay!\p"
	.string "Nếu thắng một trận, ta nên nói gì cho\n"
	.string "thật ngầu đây?$"

gText_ApprenticeWinSpeechThanks11::
	.string "{STR_VAR_1}\p"
	.string "Hoàn hảo! Ta sẽ dùng câu đó. Nhờ cậu\n"
	.string "chọn quả không sai!\p"
	.string "Và giờ điều tốt nhất là rời tổ bay xa!\p"
	.string "Cảm ơn mọi điều cậu dạy. Ta sẽ lên\n"
	.string "đường chiến đấu mê say!\p"
	.string "B-O-N-V-O-Y-A-G-E! Đánh vần là bon\n"
	.string "voyage, xin gửi lời tôn kính đến cậu\l"
	.string "đấy!$"

gText_ApprenticePickWinSpeech12::
	.string "Ồ, phải rồi, {PLAYER}! Hôm nay tôi lại\n"
	.string "tìm thấy bạn!\p"
	.string "Tôi nên làm gì nhỉ? Lại hỏi bạn ư? Sao\n"
	.string "lại không? Tôi đã hỏi rồi mà!\p"
	.string "Dù sao thì, {PLAYER}... Bạn có nghe rõ\n"
	.string "không? Nghe rõ rồi nhé! Tôi lại cần bạn\l"
	.string "khuyên bảo đây!\p"
	.string "Là về câu tôi nên hét lên. Một câu thật\n"
	.string "ngầu khi trận đấu kết thúc tốt đẹp.\p"
	.string "Nào, tôi muốn nghe bạn nói!$"

gText_ApprenticeWinSpeechThanks12::
	.string "{STR_VAR_1}\p"
	.string "Được rồi, được rồi! Tôi sẽ dùng vì câu\n"
	.string "ấy quá tuyệt vời!\p"
	.string "Tôi hết chuyện để hỏi bạn rồi. Giờ chỉ\n"
	.string "còn vẫy tay chào mà thôi.\p"
	.string "Nhưng có lẽ một ngày ta sẽ gặp, và một\n"
	.string "người phải nếm mùi thất bại.\p"
	.string "Dù sao cũng thật sự đến lúc nói lời chia\n"
	.string "tay.\p"
	.string "Nào, {PLAYER}, tôi phải tiếp tục phiêu\n"
	.string "du, nhưng đừng quên tôi nhé!\p"
	.string "Bảo trọng, {PLAYER}! Mến bạn lắm!$"

gText_ApprenticePickWinSpeech13::
	.string "{PLAYER}{KUN}, tôi tiêu rồi... Mũi cứ\n"
	.string "chảy mãi không ngừng...\p"
	.string "Tôi đã cố nghĩ một câu thật ngầu để nói\n"
	.string "khi thắng trận.\p"
	.string "Cảm hứng dâng trào khiến tôi bật khóc,\n"
	.string "giờ thì nước mũi cứ chảy mãi...\p"
	.string "Thành ra thế này, tôi cần cậu quyết\n"
	.string "định giúp, {PLAYER}{KUN}.\p"
	.string "Khi thắng một trận, tôi nên nói gì?$"

gText_ApprenticeWinSpeechThanks13::
	.string "{STR_VAR_1}\p"
	.string "... ... ... Hay đấy. Không, thật đầy cảm\n"
	.string "hứng! Nước mắt tôi lại tuôn trào rồi!\p"
	.string "Nhưng dù nước mắt và nước mũi ròng\n"
	.string "ròng, tôi vẫn sẽ dùng câu đó!\p"
	.string "Tôi hết sạch chuyện để hỏi cậu rồi,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "Từ giờ chúng ta là đối thủ! Cảm ơn vì\n"
	.string "tất cả!$"

gText_ApprenticePickWinSpeech14::
	.string "Ơ... Ừm... {PLAYER}{KUN}...\p"
	.string "Xin đừng nhìn tôi như thế. Cậu làm tôi\n"
	.string "căng thẳng quá.\p"
	.string "Tôi... tôi lại cần lời khuyên của cậu.\n"
	.string "Nhưng đây sẽ là lần cuối...\p"
	.string "Hỏi điều này thật xấu hổ, nhưng nếu\n"
	.string "thắng một trận thì tôi nên nói gì?$"

gText_ApprenticeWinSpeechThanks14::
	.string "{STR_VAR_1}\p"
	.string "Ồ... Được rồi! Tôi sẽ cố nói câu đó!\n"
	.string "Nhưng có khi tôi căng thẳng quá lại\l"
	.string "không nói nổi...\p"
	.string "Cảm ơn cậu, {PLAYER}{KUN}. Giờ tôi\n"
	.string "phải nói lời tạm biệt.\p"
	.string "Tôi sẽ nghe theo mọi điều\n"
	.string "{PLAYER}{KUN} đã dạy và cố gắng hết\l"
	.string "sức.$"

gText_ApprenticePickWinSpeech15::
	.string "Hửm? Trông bạn có vẻ là\n"
	.string "{PLAYER}{KUN}... Nhưng có thật là bạn\l"
	.string "không? Hay là một {PLAYER} DOLL tinh\l"
	.string "xảo?\p"
	.string "Ôi, không, không, không, đừng lo! Nếu\n"
	.string "bạn thật sự là người thật, xin hãy bỏ\l"
	.string "qua sự thất lễ của tôi.\p"
	.string "Không cần tức giận như vậy. Tôi chỉ\n"
	.string "mong nhận thêm lời khuyên tuyệt vời\l"
	.string "của bạn.\p"
	.string "Là về một câu nói.\p"
	.string "Chính xác hơn, nếu thắng một trận thì\n"
	.string "tôi nên nói gì?$"

gText_ApprenticeWinSpeechThanks15::
	.string "{STR_VAR_1}\p"
	.string "... ... ... ... ... ... Khi tôi thắng một trận...\p"
	.string "{STR_VAR_1}\p"
	.string "...Bạn nghiêm túc chứ?\p"
	.string "Tôi hiểu rồi. Nếu bạn nghiêm túc thì\n"
	.string "được. Cảm ơn bạn đã dành thời gian.\p"
	.string "Tôi chỉ mong ngay cả mình cũng có thể\n"
	.string "vận dụng tốt câu nói đó.\p"
	.string "Có vẻ tôi đã hết sạch chuyện cần xin lời\n"
	.string "khuyên rồi.\p"
	.string "Tôi tin đã đến lúc phải nói lời từ biệt\n"
	.string "và tự mình lên đường.\p"
	.string "Cảm ơn người thầy của tôi! Xin thứ lỗi\n"
	.string "vì tôi đã hoài nghi!$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global gText_ApprenticeChallenge0
	.global gText_ApprenticeChallenge1
	.global gText_ApprenticeChallenge2
	.global gText_ApprenticeChallenge3
	.global gText_ApprenticeChallenge4
	.global gText_ApprenticeChallenge5
	.global gText_ApprenticeChallenge6
	.global gText_ApprenticeChallenge7
	.global gText_ApprenticeChallenge8
	.global gText_ApprenticeChallenge9
	.global gText_ApprenticeChallenge10
	.global gText_ApprenticeChallenge11
	.global gText_ApprenticeChallenge12
	.global gText_ApprenticeChallenge13
	.global gText_ApprenticeChallenge14
	.global gText_ApprenticeChallenge15
	.global gText_ApprenticePleaseTeach0
	.global gText_ApprenticeRejectTeaching0
	.global gText_ApprenticeWhichLevelMode0
	.global gText_ApprenticeLevelModeThanks0
	.global gText_ApprenticePleaseTeach1
	.global gText_ApprenticeRejectTeaching1
	.global gText_ApprenticeWhichLevelMode1
	.global gText_ApprenticeLevelModeThanks1
	.global gText_ApprenticePleaseTeach2
	.global gText_ApprenticeRejectTeaching2
	.global gText_ApprenticeWhichLevelMode2
	.global gText_ApprenticeLevelModeThanks2
	.global gText_ApprenticePleaseTeach3
	.global gText_ApprenticeRejectTeaching3
	.global gText_ApprenticeWhichLevelMode3
	.global gText_ApprenticeLevelModeThanks3
	.global gText_ApprenticePleaseTeach4
	.global gText_ApprenticeRejectTeaching4
	.global gText_ApprenticeWhichLevelMode4
	.global gText_ApprenticeLevelModeThanks4
	.global gText_ApprenticePleaseTeach5
	.global gText_ApprenticeRejectTeaching5
	.global gText_ApprenticeWhichLevelMode5
	.global gText_ApprenticeLevelModeThanks5
	.global gText_ApprenticePleaseTeach6
	.global gText_ApprenticeRejectTeaching6
	.global gText_ApprenticeWhichLevelMode6
	.global gText_ApprenticeLevelModeThanks6
	.global gText_ApprenticePleaseTeach7
	.global gText_ApprenticeRejectTeaching7
	.global gText_ApprenticeWhichLevelMode7
	.global gText_ApprenticeLevelModeThanks7
	.global gText_ApprenticePleaseTeach8
	.global gText_ApprenticeRejectTeaching8
	.global gText_ApprenticeWhichLevelMode8
	.global gText_ApprenticeLevelModeThanks8
	.global gText_ApprenticePleaseTeach9
	.global gText_ApprenticeRejectTeaching9
	.global gText_ApprenticeWhichLevelMode9
	.global gText_ApprenticeLevelModeThanks9
	.global gText_ApprenticePleaseTeach10
	.global gText_ApprenticeRejectTeaching10
	.global gText_ApprenticeWhichLevelMode10
	.global gText_ApprenticeLevelModeThanks10
	.global gText_ApprenticePleaseTeach11
	.global gText_ApprenticeRejectTeaching11
	.global gText_ApprenticeWhichLevelMode11
	.global gText_ApprenticeLevelModeThanks11
	.global gText_ApprenticePleaseTeach12
	.global gText_ApprenticeRejectTeaching12
	.global gText_ApprenticeWhichLevelMode12
	.global gText_ApprenticeLevelModeThanks12
	.global gText_ApprenticePleaseTeach13
	.global gText_ApprenticeRejectTeaching13
	.global gText_ApprenticeWhichLevelMode13
	.global gText_ApprenticeLevelModeThanks13
	.global gText_ApprenticePleaseTeach14
	.global gText_ApprenticeRejectTeaching14
	.global gText_ApprenticeWhichLevelMode14
	.global gText_ApprenticeLevelModeThanks14
	.global gText_ApprenticePleaseTeach15
	.global gText_ApprenticeRejectTeaching15
	.global gText_ApprenticeWhichLevelMode15
	.global gText_ApprenticeLevelModeThanks15
	.global gText_ApprenticeWhatHeldItem0
	.global gText_ApprenticeHoldNothing0
	.global gText_ApprenticeThanksNoHeldItem0
	.global gText_ApprenticeThanksHeldItem0
	.global gText_ApprenticeItemAlreadyRecommended0
	.global gText_ApprenticeWhatHeldItem1
	.global gText_ApprenticeHoldNothing1
	.global gText_ApprenticeThanksNoHeldItem1
	.global gText_ApprenticeThanksHeldItem1
	.global gText_ApprenticeItemAlreadyRecommended1
	.global gText_ApprenticeWhatHeldItem2
	.global gText_ApprenticeHoldNothing2
	.global gText_ApprenticeThanksNoHeldItem2
	.global gText_ApprenticeThanksHeldItem2
	.global gText_ApprenticeItemAlreadyRecommended2
	.global gText_ApprenticeWhatHeldItem3
	.global gText_ApprenticeHoldNothing3
	.global gText_ApprenticeThanksNoHeldItem3
	.global gText_ApprenticeThanksHeldItem3
	.global gText_ApprenticeItemAlreadyRecommended3
	.global gText_ApprenticeWhatHeldItem4
	.global gText_ApprenticeHoldNothing4
	.global gText_ApprenticeThanksNoHeldItem4
	.global gText_ApprenticeThanksHeldItem4
	.global gText_ApprenticeItemAlreadyRecommended4
	.global gText_ApprenticeWhatHeldItem5
	.global gText_ApprenticeHoldNothing5
	.global gText_ApprenticeThanksNoHeldItem5
	.global gText_ApprenticeThanksHeldItem5
	.global gText_ApprenticeItemAlreadyRecommended5
	.global gText_ApprenticeWhatHeldItem6
	.global gText_ApprenticeHoldNothing6
	.global gText_ApprenticeThanksNoHeldItem6
	.global gText_ApprenticeThanksHeldItem6
	.global gText_ApprenticeItemAlreadyRecommended6
	.global gText_ApprenticeWhatHeldItem7
	.global gText_ApprenticeHoldNothing7
	.global gText_ApprenticeThanksNoHeldItem7
	.global gText_ApprenticeThanksHeldItem7
	.global gText_ApprenticeItemAlreadyRecommended7
	.global gText_ApprenticeWhatHeldItem8
	.global gText_ApprenticeHoldNothing8
	.global gText_ApprenticeThanksNoHeldItem8
	.global gText_ApprenticeThanksHeldItem8
	.global gText_ApprenticeItemAlreadyRecommended8
	.global gText_ApprenticeWhatHeldItem9
	.global gText_ApprenticeHoldNothing9
	.global gText_ApprenticeThanksNoHeldItem9
	.global gText_ApprenticeThanksHeldItem9
	.global gText_ApprenticeItemAlreadyRecommended9
	.global gText_ApprenticeWhatHeldItem10
	.global gText_ApprenticeHoldNothing10
	.global gText_ApprenticeThanksNoHeldItem10
	.global gText_ApprenticeThanksHeldItem10
	.global gText_ApprenticeItemAlreadyRecommended10
	.global gText_ApprenticeWhatHeldItem11
	.global gText_ApprenticeHoldNothing11
	.global gText_ApprenticeThanksNoHeldItem11
	.global gText_ApprenticeThanksHeldItem11
	.global gText_ApprenticeItemAlreadyRecommended11
	.global gText_ApprenticeWhatHeldItem12
	.global gText_ApprenticeHoldNothing12
	.global gText_ApprenticeThanksNoHeldItem12
	.global gText_ApprenticeThanksHeldItem12
	.global gText_ApprenticeItemAlreadyRecommended12
	.global gText_ApprenticeWhatHeldItem13
	.global gText_ApprenticeHoldNothing13
	.global gText_ApprenticeThanksNoHeldItem13
	.global gText_ApprenticeThanksHeldItem13
	.global gText_ApprenticeItemAlreadyRecommended13
	.global gText_ApprenticeWhatHeldItem14
	.global gText_ApprenticeHoldNothing14
	.global gText_ApprenticeThanksNoHeldItem14
	.global gText_ApprenticeThanksHeldItem14
	.global gText_ApprenticeItemAlreadyRecommended14
	.global gText_ApprenticeWhatHeldItem15
	.global gText_ApprenticeHoldNothing15
	.global gText_ApprenticeThanksNoHeldItem15
	.global gText_ApprenticeThanksHeldItem15
	.global gText_ApprenticeItemAlreadyRecommended15
	.global gText_ApprenticeWhichMonFirst0
	.global gText_ApprenticeMonFirstThanks0
	.global gText_ApprenticeWhichMonFirst1
	.global gText_ApprenticeMonFirstThanks1
	.global gText_ApprenticeWhichMonFirst2
	.global gText_ApprenticeMonFirstThanks2
	.global gText_ApprenticeWhichMonFirst3
	.global gText_ApprenticeMonFirstThanks3
	.global gText_ApprenticeWhichMonFirst4
	.global gText_ApprenticeMonFirstThanks4
	.global gText_ApprenticeWhichMonFirst5
	.global gText_ApprenticeMonFirstThanks5
	.global gText_ApprenticeWhichMonFirst6
	.global gText_ApprenticeMonFirstThanks6
	.global gText_ApprenticeWhichMonFirst7
	.global gText_ApprenticeMonFirstThanks7
	.global gText_ApprenticeWhichMonFirst8
	.global gText_ApprenticeMonFirstThanks8
	.global gText_ApprenticeWhichMonFirst9
	.global gText_ApprenticeMonFirstThanks9
	.global gText_ApprenticeWhichMonFirst10
	.global gText_ApprenticeMonFirstThanks10
	.global gText_ApprenticeWhichMonFirst11
	.global gText_ApprenticeMonFirstThanks11
	.global gText_ApprenticeWhichMonFirst12
	.global gText_ApprenticeMonFirstThanks12
	.global gText_ApprenticeWhichMonFirst13
	.global gText_ApprenticeMonFirstThanks13
	.global gText_ApprenticeWhichMonFirst14
	.global gText_ApprenticeMonFirstThanks14
	.global gText_ApprenticeWhichMonFirst15
	.global gText_ApprenticeMonFirstThanks15
	.global gText_ApprenticeWhichMon0
	.global gText_ApprenticeMonThanks0
	.global gText_ApprenticeWhichMon1
	.global gText_ApprenticeMonThanks1
	.global gText_ApprenticeWhichMon2
	.global gText_ApprenticeMonThanks2
	.global gText_ApprenticeWhichMon3
	.global gText_ApprenticeMonThanks3
	.global gText_ApprenticeWhichMon4
	.global gText_ApprenticeMonThanks4
	.global gText_ApprenticeWhichMon5
	.global gText_ApprenticeMonThanks5
	.global gText_ApprenticeWhichMon6
	.global gText_ApprenticeMonThanks6
	.global gText_ApprenticeWhichMon7
	.global gText_ApprenticeMonThanks7
	.global gText_ApprenticeWhichMon8
	.global gText_ApprenticeMonThanks8
	.global gText_ApprenticeWhichMon9
	.global gText_ApprenticeMonThanks9
	.global gText_ApprenticeWhichMon10
	.global gText_ApprenticeMonThanks10
	.global gText_ApprenticeWhichMon11
	.global gText_ApprenticeMonThanks11
	.global gText_ApprenticeWhichMon12
	.global gText_ApprenticeMonThanks12
	.global gText_ApprenticeWhichMon13
	.global gText_ApprenticeMonThanks13
	.global gText_ApprenticeWhichMon14
	.global gText_ApprenticeMonThanks14
	.global gText_ApprenticeWhichMon15
	.global gText_ApprenticeMonThanks15
	.global gText_ApprenticeWhichMove0
	.global gText_ApprenticeMoveThanks0
	.global gText_ApprenticeWhichMove1
	.global gText_ApprenticeMoveThanks1
	.global gText_ApprenticeWhichMove2
	.global gText_ApprenticeMoveThanks2
	.global gText_ApprenticeWhichMove3
	.global gText_ApprenticeMoveThanks3
	.global gText_ApprenticeWhichMove4
	.global gText_ApprenticeMoveThanks4
	.global gText_ApprenticeWhichMove5
	.global gText_ApprenticeMoveThanks5
	.global gText_ApprenticeWhichMove6
	.global gText_ApprenticeMoveThanks6
	.global gText_ApprenticeWhichMove7
	.global gText_ApprenticeMoveThanks7
	.global gText_ApprenticeWhichMove8
	.global gText_ApprenticeMoveThanks8
	.global gText_ApprenticeWhichMove9
	.global gText_ApprenticeMoveThanks9
	.global gText_ApprenticeWhichMove10
	.global gText_ApprenticeMoveThanks10
	.global gText_ApprenticeWhichMove11
	.global gText_ApprenticeMoveThanks11
	.global gText_ApprenticeWhichMove12
	.global gText_ApprenticeMoveThanks12
	.global gText_ApprenticeWhichMove13
	.global gText_ApprenticeMoveThanks13
	.global gText_ApprenticeWhichMove14
	.global gText_ApprenticeMoveThanks14
	.global gText_ApprenticeWhichMove15
	.global gText_ApprenticeMoveThanks15
	.global gText_ApprenticePickWinSpeech0
	.global gText_ApprenticeWinSpeechThanks0
	.global gText_ApprenticePickWinSpeech1
	.global gText_ApprenticeWinSpeechThanks1
	.global gText_ApprenticePickWinSpeech2
	.global gText_ApprenticeWinSpeechThanks2
	.global gText_ApprenticePickWinSpeech3
	.global gText_ApprenticeWinSpeechThanks3
	.global gText_ApprenticePickWinSpeech4
	.global gText_ApprenticeWinSpeechThanks4
	.global gText_ApprenticePickWinSpeech5
	.global gText_ApprenticeWinSpeechThanks5
	.global gText_ApprenticePickWinSpeech6
	.global gText_ApprenticeWinSpeechThanks6
	.global gText_ApprenticePickWinSpeech7
	.global gText_ApprenticeWinSpeechThanks7
	.global gText_ApprenticePickWinSpeech8
	.global gText_ApprenticeWinSpeechThanks8
	.global gText_ApprenticePickWinSpeech9
	.global gText_ApprenticeWinSpeechThanks9
	.global gText_ApprenticePickWinSpeech10
	.global gText_ApprenticeWinSpeechThanks10
	.global gText_ApprenticePickWinSpeech11
	.global gText_ApprenticeWinSpeechThanks11
	.global gText_ApprenticePickWinSpeech12
	.global gText_ApprenticeWinSpeechThanks12
	.global gText_ApprenticePickWinSpeech13
	.global gText_ApprenticeWinSpeechThanks13
	.global gText_ApprenticePickWinSpeech14
	.global gText_ApprenticeWinSpeechThanks14
	.global gText_ApprenticePickWinSpeech15
	.global gText_ApprenticeWinSpeechThanks15
@ END GENERATED LOCALIZATION EXPORTS
