FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Chào mừng bạn đến BATTLE TENT\n"
	.string "FALLARBOR SITE!\p"
	.string "Tôi là người hướng dẫn bạn tham gia\n"
	.string "Set KO Tourney!$"

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "Giờ bạn có muốn thử sức với Set KO\n"
	.string "Tourney không?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "Chúng tôi mong được đón nhận thử\n"
	.string "thách của bạn vào dịp khác!$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
	.string "Tại FALLARBOR BATTLE TENT, chúng tôi\n"
	.string "tổ chức Set KO Tourney.\p"
	.string "Mỗi người tham gia sẽ thi đấu với một\n"
	.string "đội gồm ba POKéMON.\p"
	.string "Ba POKéMON phải được xếp theo thứ tự\n"
	.string "ra sân.\p"
	.string "Trong trận đấu, từng POKéMON sẽ lần\n"
	.string "lượt ra sân theo thứ tự đã chọn.\p"
	.string "Một khi POKéMON đã ra sân, nó phải tiếp\n"
	.string "tục chiến đấu cho đến khi trận đấu có\l"
	.string "kết quả.\p"
	.string "Nếu sau ba lượt mà trận đấu vẫn chưa\n"
	.string "phân thắng bại, kết quả sẽ do giám khảo\l"
	.string "quyết định.\p"
	.string "Nếu muốn tạm dừng thử thách, vui lòng\n"
	.string "lưu trò chơi.\p"
	.string "Nếu không lưu, bạn sẽ không thể tiếp\n"
	.string "tục thử thách.\p"
	.string "Nếu đánh bại ba HLV liên tiếp, bạn\n"
	.string "sẽ nhận được một phần thưởng giá trị.$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Trước khi đưa bạn vào BATTLE TENT, tôi\n"
	.string "phải lưu trò chơi. Bạn đồng ý chứ?$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Chúng tôi có hai cấp độ thử thách:\n"
	.string "Level 50 và Open Level. Bạn chọn cấp\l"
	.string "nào?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Được rồi, giờ vui lòng chọn ba POKéMON.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Hỡi nhà thách đấu thân mến!\p"
	.string "Bạn chưa có đủ ba POKéMON cần thiết để\n"
	.string "tham gia.\p"
	.string "Chúng cũng không được giữ cùng loại\n"
	.string "vật phẩm.\p"
	.string "EGGS{STR_VAR_1} không đủ điều\n"
	.string "kiện.\p"
	.string "Khi đã chuẩn bị xong, xin hãy quay lại.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Hỡi nhà thách đấu thân mến!\p"
	.string "Bạn chưa có đủ ba POKéMON cần thiết để\n"
	.string "tham gia.\p"
	.string "Để đủ điều kiện, bạn phải mang theo ba\n"
	.string "loài POKéMON khác nhau.\p"
	.string "Chúng cũng không được giữ cùng loại\n"
	.string "vật phẩm.\p"
	.string "EGGS{STR_VAR_1} không đủ điều\n"
	.string "kiện.\p"
	.string "Khi đã chuẩn bị xong, xin hãy quay lại.$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "Bây giờ tôi sẽ đưa bạn đến BATTLE\n"
	.string "TENT.$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Hỡi nhà thách đấu thân mến!\p"
	.string "Bạn đã không lưu trò chơi trước khi\n"
	.string "tắt máy, đúng không?\p"
	.string "Thật đáng tiếc, vì vậy bạn đã bị loại\n"
	.string "khỏi lượt thử thách này.\p"
	.string "Dĩ nhiên, bạn có thể bắt đầu một lượt\n"
	.string "thử thách mới.$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "Tuyệt vời! Bạn đã đánh bại ba HLV\n"
	.string "liên tiếp!$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "Vui lòng chờ trong khi tôi lưu trò chơi.$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "Để kỷ niệm chuỗi 3 trận thắng của bạn,\n"
	.string "chúng tôi xin trao phần thưởng này.$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} nhận được phần thưởng\n"
	.string "{STR_VAR_1}.$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "Ồ? TÚI ĐỒ của bạn hình như đã đầy.\p"
	.string "Xin hãy dọn chỗ rồi quay lại nhận phần\n"
	.string "thưởng.$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "Cảm ơn bạn rất nhiều vì đã tham gia!\p"
	.string "Vui lòng chờ trong khi tôi lưu trò chơi.$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "Chúng tôi mong được đón nhận thử\n"
	.string "thách của bạn vào dịp khác!$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "Chúng tôi vẫn luôn mong đợi bạn đến.\p"
	.string "Trước khi đưa bạn vào BATTLE TENT, tôi\n"
	.string "phải lưu trò chơi. Vui lòng chờ.$"

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Chào mừng bạn đến BATTLE TENT\n"
	.string "VERDANTURF SITE!\p"
	.string "Tại đây, lòng tin của HLV dành cho\n"
	.string "POKéMON sẽ được thử thách.$"

VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
	.string "Bạn có muốn tham gia thử thách tại\n"
	.string "VERDANTURF BATTLE TENT không?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
	.string "Tại VERDANTURF BATTLE TENT, có một quy\n"
	.string "tắc quan trọng mà bạn phải tuân theo.\p"
	.string "HLV chỉ được phép đổi POKéMON ra\n"
	.string "vào trận.\p"
	.string "Ngoài việc đó, HLV không được ra\n"
	.string "lệnh cho POKéMON.\p"
	.string "POKéMON sẽ hành động theo tính cách và\n"
	.string "tự mình chiến đấu.\p"
	.string "Bạn phải đặt lòng tin vào POKéMON và\n"
	.string "dõi theo chúng.\p"
	.string "Nếu bạn đánh bại ba HLV liên tiếp,\n"
	.string "bạn sẽ nhận được\l"
	.string "một phần thưởng.\p"
	.string "Nếu muốn tạm dừng thử thách, vui lòng\n"
	.string "lưu trò chơi.\p"
	.string "Nếu không lưu trước khi tạm dừng, bạn\n"
	.string "sẽ bị loại.$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "Khi bạn và POKéMON đã vững vàng hơn,\n"
	.string "hãy quay lại.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Tại đây có hai độ khó: Level 50 và Open\n"
	.string "Level. Bạn muốn chọn thử thách nào?$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Haiz...\p"
	.string "Bạn chưa có đủ ba POKéMON cần thiết\n"
	.string "cho thử thách.\p"
	.string "Để tham gia, bạn phải mang theo ba loài\n"
	.string "POKéMON khác nhau.\p"
	.string "Chúng cũng không được giữ cùng loại\n"
	.string "vật phẩm.\p"
	.string "EGGS{STR_VAR_1} không đủ điều\n"
	.string "kiện.\p"
	.string "Hãy quay lại khi bạn đã chuẩn bị xong.$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Haiz...\p"
	.string "Bạn chưa có đủ ba POKéMON cần thiết\n"
	.string "cho thử thách.\p"
	.string "Để tham gia, bạn phải mang theo ba loài\n"
	.string "POKéMON khác nhau.\p"
	.string "Chúng cũng không được giữ cùng loại\n"
	.string "vật phẩm.\p"
	.string "EGGS{STR_VAR_1} không đủ điều\n"
	.string "kiện.\p"
	.string "Hãy quay lại khi bạn đã chuẩn bị xong.$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Tốt. Giờ bạn phải chọn ba POKéMON.$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Trước khi đưa bạn vào BATTLE TENT, tôi\n"
	.string "phải lưu trò chơi. Bạn đồng ý chứ?$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "Tốt. Giờ hãy theo tôi.$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "Thật vinh dự khi được chứng kiến màn\n"
	.string "thể hiện của POKéMON bên bạn.\p"
	.string "Kết quả sẽ được ghi lại. Xin bạn chờ\n"
	.string "một lát.$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "Đạt được chuỗi 3 trận thắng...\p"
	.string "Mối gắn kết giữa bạn và POKéMON dường\n"
	.string "như thật bền chặt và chân thành.$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "Thành tích của bạn sẽ được ghi lại. Xin\n"
	.string "bạn chờ một lát.$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "Để ghi nhận thành tích chuỗi 3 trận\n"
	.string "thắng, chúng tôi xin trao bạn phần\l"
	.string "thưởng này.$"

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Chào mừng bạn đến BATTLE TENT\n"
	.string "SLATEPORT SITE!\p"
	.string "Tôi là người hướng dẫn bạn tham gia\n"
	.string "Battle Swap Tournament.$"

SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "Bạn có muốn tham gia thử thách Battle\n"
	.string "Swap không?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
	.string "Tại SLATEPORT BATTLE TENT, chúng tôi\n"
	.string "tổ chức các sự kiện Battle Swap bằng\l"
	.string "POKéMON cho thuê.\p"
	.string "Trước tiên, bạn sẽ được cho mượn ba\n"
	.string "POKéMON dành riêng cho sự kiện này.\p"
	.string "Bạn phải dùng những POKéMON cho thuê\n"
	.string "đó để đấu một trận SINGLE BATTLE.\p"
	.string "Nếu thắng, bạn được phép đổi một\n"
	.string "POKéMON cho thuê của mình.\p"
	.string "Hãy lặp lại chu trình chiến đấu và đổi\n"
	.string "POKéMON này. Nếu thắng ba trận liên\l"
	.string "tiếp, bạn sẽ nhận được một phần\l"
	.string "thưởng giá trị.\p"
	.string "Nếu muốn tạm dừng thử thách, vui lòng\n"
	.string "lưu trò chơi.\p"
	.string "Nếu không lưu trước khi tạm dừng, bạn\n"
	.string "sẽ bị loại.$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "Chúng tôi mong được đón bạn trong lần\n"
	.string "tới.$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "Bạn muốn thử thách ở cấp nào? Level 50\n"
	.string "hay Level 100?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Trước khi bạn bắt đầu thử thách, tôi\n"
	.string "cần lưu dữ liệu. Bạn đồng ý chứ?$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "Được rồi, tôi sẽ giữ POKéMON của bạn an\n"
	.string "toàn trong lúc bạn thi đấu.$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "Xin mời đi lối này.$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "Cảm ơn bạn đã tham gia!\p"
	.string "Tôi sẽ trả lại POKéMON của bạn và nhận\n"
	.string "lại POKéMON cho thuê của chúng tôi.\p"
	.string "Tôi còn phải lưu kết quả sự kiện của\n"
	.string "bạn. Vui lòng chờ.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "Tôi sẽ trả lại POKéMON của bạn và nhận\n"
	.string "lại POKéMON cho thuê của chúng tôi.$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "Chúc mừng! Bạn đã thắng ba trận liên\n"
	.string "tiếp!\p"
	.string "Tôi sẽ trả lại POKéMON của bạn và nhận\n"
	.string "lại POKéMON cho thuê của chúng tôi.\p"
	.string "Tôi còn phải lưu kết quả sự kiện của\n"
	.string "bạn. Vui lòng chờ.$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "Để ghi nhận chuỗi 3 trận thắng của bạn,\n"
	.string "chúng tôi xin trao phần thưởng này.$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "Ồ? Có vẻ bạn không còn chỗ cho món này.\p"
	.string "Vui lòng dọn chỗ trong TÚI ĐỒ rồi\n"
	.string "báo cho tôi.$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "Chúng tôi đã chờ bạn!\p"
	.string "Trước khi tiếp tục thử thách, tôi phải\n"
	.string "lưu trò chơi.$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Tôi rất tiếc phải nói điều này, nhưng\n"
	.string "lần trước bạn đã không lưu trước khi\l"
	.string "ngừng chơi.\p"
	.string "Vì vậy, bạn đã bị loại khỏi lượt thử\n"
	.string "thách.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "Chúng tôi sẽ trả lại POKéMON của riêng\n"
	.string "bạn.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} nhận được phần thưởng\n"
	.string "{STR_VAR_1}.$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "Các luật của Battle Swap được liệt kê\n"
	.string "ở đây.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "Bạn muốn đọc mục nào?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "Trong sự kiện Battle Swap, bạn chỉ\n"
	.string "được sử dụng ba POKéMON.\p"
	.string "Dù đang thuê hay đổi POKéMON, đội của\n"
	.string "bạn cũng không được có từ hai POKéMON\l"
	.string "cùng loài trở lên.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "Bạn chỉ được đổi POKéMON với HLV\n"
	.string "vừa bị mình đánh bại.\p"
	.string "Bạn cũng chỉ được đổi lấy những\n"
	.string "POKéMON mà HLV đó đã sử dụng.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "Sau mỗi trận thắng, bạn có thể đổi lấy\n"
	.string "một POKéMON của đối thủ vừa bị đánh\l"
	.string "bại.\p"
	.string "Bạn không thể đổi POKéMON với HLV\n"
	.string "thứ ba trong sự kiện.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "Có hai điểm quan trọng cần lưu ý khi đổi\n"
	.string "POKéMON.\p"
	.string "Thứ nhất, khi đổi, bạn không thể kiểm\n"
	.string "tra chỉ số của POKéMON mình sắp nhận.\p"
	.string "Thứ hai, POKéMON trong đội được xếp\n"
	.string "theo thứ tự bạn đã thuê chúng.\p"
	.string "Thứ tự này không thay đổi ngay cả khi\n"
	.string "bạn đổi POKéMON.$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "Toàn bộ POKéMON tại SLATEPORT BATTLE\n"
	.string "TENT đều là POKéMON cho thuê.\p"
	.string "Tất cả POKéMON cho thuê đều được giữ\n"
	.string "ở Level 30.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "Các luật của VERDANTURF BATTLE TENT\n"
	.string "được liệt kê ở đây.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "Bạn muốn đọc mục nào?$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "Tại VERDANTURF BATTLE TENT, POKéMON\n"
	.string "phải tự suy nghĩ và chiến đấu.\p"
	.string "Khác với POKéMON hoang dã, POKéMON\n"
	.string "sống cùng con người sẽ hành động khác\l"
	.string "nhau tùy theo tính cách.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "Tùy theo tính cách, có POKéMON luôn\n"
	.string "thích tấn công bất kể tình huống.\p"
	.string "POKéMON khác lại thích bảo vệ bản thân\n"
	.string "khỏi mọi tổn hại.\p"
	.string "Một số khác lại thích quấy rối hoặc làm\n"
	.string "đối thủ rối trí.\p"
	.string "Tùy theo tính cách, POKéMON sẽ có\n"
	.string "những chiêu thức yêu thích mà nó sử\l"
	.string "dụng thành thạo.\p"
	.string "Nó cũng có thể không thích một số chiêu\n"
	.string "thức mà nó khó sử dụng.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "Có những chiêu thức tấn công gây sát\n"
	.string "thương trực tiếp cho đối thủ.\p"
	.string "Có những chiêu thức phòng thủ dùng để\n"
	.string "chuẩn bị đối phó đòn tấn công của đối\l"
	.string "phương, hồi HP và nhiều việc khác.\p"
	.string "Ngoài ra còn có các chiêu thức hơi khác\n"
	.string "thường, có thể làm đối thủ suy yếu bằng\l"
	.string "những trạng thái bất lợi như trúng độc\l"
	.string "và tê liệt.\p"
	.string "POKéMON sẽ cân nhắc sử dụng chiêu\n"
	.string "thức thuộc ba nhóm này.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "Khi không được HLV chỉ huy,\n"
	.string "POKéMON có thể không sử dụng hiệu quả\l"
	.string "một số chiêu thức.\p"
	.string "POKéMON không giỏi sử dụng những chiêu\n"
	.string "thức mà nó không thích.\p"
	.string "Nếu POKéMON chỉ biết các chiêu thức\n"
	.string "không phù hợp với tính cách, nó\l"
	.string "thường không thể phát huy hết tiềm\l"
	.string "năng.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "Tùy theo tính cách, khi gặp nguy hiểm,\n"
	.string "POKéMON có thể bắt đầu dùng những\l"
	.string "chiêu thức không phù hợp với tính\l"
	.string "cách của nó.\p"
	.string "Nếu POKéMON bỗng hành động kỳ lạ trong\n"
	.string "tình thế nguy cấp, hãy quan sát nó thật\l"
	.string "kỹ.$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "Tại BATTLE TENT này, cấp độ của đối thủ\n"
	.string "sẽ được điều chỉnh cho phù hợp với\l"
	.string "cấp độ POKéMON của bạn.\p"
	.string "Tuy nhiên, không HLV nào bạn đối\n"
	.string "đầu có POKéMON dưới Level 30.$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "Các luật của VERDANTURF BATTLE TENT\n"
	.string "được liệt kê ở đây.$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent
	.global FallarborTown_BattleTentLobby_Text_TakeChallenge
	.global FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge
	.global FallarborTown_BattleTentLobby_Text_ExplainFallarborTent
	.global FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge
	.global FallarborTown_BattleTentLobby_Text_WhichLevelMode
	.global FallarborTown_BattleTentLobby_Text_SelectThreeMons
	.global FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50
	.global FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen
	.global FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent
	.global FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting
	.global FallarborTown_BattleTentLobby_Text_BeatThreeTrainers
	.global FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame
	.global FallarborTown_BattleTentLobby_Text_PresentYouWithPrize
	.global FallarborTown_BattleTentLobby_Text_ReceivedPrize
	.global FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize
	.global FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving
	.global FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2
	.global FallarborTown_BattleTentLobby_Text_LookingForwardToArrival
	.global VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent
	.global VerdanturfTown_BattleTentLobby_Text_TakeChallenge
	.global VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent
	.global VerdanturfTown_BattleTentLobby_Text_ReturnFortified
	.global VerdanturfTown_BattleTentLobby_Text_WhichLevelMode
	.global VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50
	.global VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen
	.global VerdanturfTown_BattleTentLobby_Text_SelectThreeMons
	.global VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge
	.global VerdanturfTown_BattleTentLobby_Text_NowFollowMe
	.global VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded
	.global VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak
	.global VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded
	.global VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize
	.global SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent
	.global SlateportCity_BattleTentLobby_Text_TakeChallenge
	.global SlateportCity_BattleTentLobby_Text_ExplainSlateportTent
	.global SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit
	.global SlateportCity_BattleTentLobby_Text_WhichLevelMode
	.global SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge
	.global SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping
	.global SlateportCity_BattleTentLobby_Text_StepThisWay
	.global SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults
	.global SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals
	.global SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons
	.global SlateportCity_BattleTentLobby_Text_AwardYouThisPrize
	.global SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom
	.global SlateportCity_BattleTentLobby_Text_BeenWaitingForYou
	.global SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting
	.global SlateportCity_BattleTentLobby_Text_ReturnPersonalMons
	.global SlateportCity_BattleTentLobby_Text_ReceivedPrize
	.global SlateportCity_BattleTentLobby_Text_RulesAreListed
	.global SlateportCity_BattleTentLobby_Text_ReadWhichHeading
	.global SlateportCity_BattleTentLobby_Text_ExplainBasicRules
	.global SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules
	.global SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules
	.global SlateportCity_BattleTentLobby_Text_ExplainSwapNotes
	.global SlateportCity_BattleTentLobby_Text_ExplainMonRules
	.global VerdanturfTown_BattleTentLobby_Text_RulesAreListed2
	.global VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading
	.global VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules
	.global VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules
	.global VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules
	.global VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules
	.global VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules
	.global BattleTentLobby_Text_ExplainLevelRules
	.global VerdanturfTown_BattleTentLobby_Text_RulesAreListed
@ END GENERATED LOCALIZATION EXPORTS
