PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "BA: Chào, {PLAYER}!\p"
	.string "Ba vừa nhận được một BERRY rất hiếm.\n"
	.string "Ba muốn tặng nó cho con.$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "Nếu thấy BERRIES mọc trong đất mùn,\n"
	.string "bạn cứ tự nhiên hái.\p"
	.string "Nhưng nhớ trồng lại một BERRY đúng chỗ\n"
	.string "đó. Phép lịch sự thông thường mà.\p"
	.string "Đây, tôi sẽ chia cho bạn một quả.$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "Nhìn bạn thế kia, hẳn bạn là HLV,\n"
	.string "đúng không?\p"
	.string "HLV thường cho POKéMON giữ\n"
	.string "BERRIES.\p"
	.string "Trồng BERRIES hay sử dụng chúng là tùy\n"
	.string "bạn.$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "Ngày nào mình cũng tưới cây. Chúng đã\n"
	.string "nở rất nhiều hoa.\p"
	.string "Chúng còn cho mình rất nhiều BERRIES\n"
	.string "nữa.\p"
	.string "Đây! Bạn nhận lấy nhé!$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "Mình sẽ thật cố gắng để trồng ra\n"
	.string "BERRIES đủ màu.\p"
	.string "Mình mong bạn cũng cố gắng!$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "Hôm nay mình sẽ tìm BERRIES màu gì\n"
	.string "nhỉ?$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "Tôi rất thích dùng máy BERRY CRUSH nên\n"
	.string "đang thu thập BERRIES.\p"
	.string "Nếu bạn muốn, tôi sẽ chia cho bạn một\n"
	.string "quả.$"

Route114_Text_TryBerryCrushWithFriends:
	.string "Bạn nên thử dùng máy BERRY CRUSH cùng\n"
	.string "bạn bè.$"

Route114_Text_FunToThinkAboutBerries:
	.string "Nên trồng BERRY nào? Nên dùng hay để\n"
	.string "dành BERRIES?\p"
	.string "Nghĩ về những điều đó cũng thật thú vị.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "BERRIES lớn lên nhờ hấp thụ ánh nắng.\p"
	.string "Chúng ta giúp BERRIES phát triển bằng\n"
	.string "cách tưới nước thường xuyên.\p"
	.string "Đó là một cách thể hiện tình yêu, phải\n"
	.string "không?$"

Route120_Text_YesYouUnderstand:
	.string "Đúng, đúng. Bạn hiểu ý tôi rồi.\p"
	.string "Hãy nhận lấy món này.$"

Route120_Text_MakeYourOwnImpressions:
	.string "Ồ... Nhưng có lẽ tự mình cảm nhận vẫn\n"
	.string "rất quan trọng...\p"
	.string "Bạn cứ nhận lấy món này.$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "Tôi nghĩ BERRY đó rất hiếm. Mong bạn\n"
	.string "chăm nó thật chu đáo và đầy yêu\l"
	.string "thương.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "Tôi sẽ xin thêm BERRIES từ BERRY\n"
	.string "MASTER.$"

LilycoveCity_Text_BerrySuitsYou:
	.string "Nói cho cùng...\p"
	.string "Cũng như bộ suit vừa vặn hoàn hảo với\n"
	.string "tôi, làn gió mát rất hợp với biển.\p"
	.string "Còn bạn, một BERRY hợp với bạn đến chữ\n"
	.string "'T'...\p"
	.string "Tại sao lại như vậy nhỉ?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "Nói cho cùng...\p"
	.string "Vì bạn là HLV!$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "Nói cho cùng...\p"
	.string "Cũng như phong thái giản dị mà trang\n"
	.string "nhã rất hợp với tôi, {POKEBLOCK}S hoàn\l"
	.string "toàn hợp với POKéMON.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "Bạn có thể gọi tôi là BERRY MASTER.\p"
	.string "Tôi mơ ước phủ khắp thế giới bằng\n"
	.string "những bông hoa xinh đẹp, nên tôi trồng\l"
	.string "BERRIES rồi tặng chúng cho mọi người.\p"
	.string "Bạn xứng đáng nhận một BERRY!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "Sao phải keo kiệt chứ? Nhận thêm một\n"
	.string "quả nữa đi!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "Nhớ ghé cửa hàng hoa PRETTY PETAL gần\n"
	.string "RUSTBORO nhé.\p"
	.string "Hãy để hoa phủ khắp thế giới!$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "Hôm nay tôi làm xong rồi. Hôm khác hãy\n"
	.string "quay lại.\p"
	.string "Hãy để hoa phủ khắp thế giới!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "Chồng ta trồng BERRIES giỏi nhất thế\n"
	.string "giới đấy.\p"
	.string "Ông ấy khiến ta rất tự hào.\p"
	.string "Nhân tiện, cháu có nghe câu nói hay nào\n"
	.string "gần đây không?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "A! Câu nói thật tuyệt vời! Quả là truyền\n"
	.string "cảm hứng!\p"
	.string "Ta muốn cháu nhận lấy món này.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "Ồ! Một câu nói hay đấy. Cháu thật đáng\n"
	.string "nể.\p"
	.string "Ta muốn cháu nhận lấy món này.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "Bốn đứa cháu của chúng ta hẳn sẽ thành\n"
	.string "đạt hơn cả chồng ta.\p"
	.string "Cuộc đời ta lúc nào cũng ngập tràn niềm\n"
	.string "vui!$"

Route123_BerryMastersHouse_Text_Ah:
	.string "À...$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "Xin chào!\p"
	.string "Đây là cửa hàng hoa PRETTY PETAL. Đem\n"
	.string "hoa phủ khắp thế giới!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER}{KUN}, bạn có muốn tìm hiểu về\n"
	.string "BERRIES không?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "Tên bạn là gì?\p"
	.string "{PLAYER}{KUN}. Tên hay thật.\p"
	.string "{PLAYER}{KUN}, bạn có muốn tìm hiểu về\n"
	.string "BERRIES không?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "BERRIES mọc trên những cây chỉ sinh\n"
	.string "trưởng tốt trong đất mùn mềm.\p"
	.string "Nếu hái BERRIES, bạn nhớ trồng lại một\n"
	.string "BERRY trong đất mùn.\p"
	.string "BERRY được trồng sẽ sớm nảy mầm, lớn\n"
	.string "thành cây, nở hoa xinh đẹp rồi lại cho\l"
	.string "ra BERRIES.\p"
	.string "Tôi muốn thấy cả thế giới rộng lớn tràn\n"
	.string "ngập những bông hoa xinh đẹp. Đó là\l"
	.string "ước mơ của tôi.\p"
	.string "Xin hãy giúp tôi, {PLAYER}{KUN}. Hãy\n"
	.string "trồng BERRIES và mang thêm nhiều hoa\l"
	.string "đến với thế giới.$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "Hoa mang đến cho mọi người biết bao\n"
	.string "niềm vui, phải không?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "Xin chào!\p"
	.string "Càng chăm chút cho hoa, chúng sẽ càng\n"
	.string "nở đẹp.\p"
	.string "Em sẽ thích việc chăm hoa cho mà xem.\n"
	.string "Chị chắc chắn đấy. Tặng em thứ này.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "Khi cây BERRY đang lớn, hãy tưới chúng\n"
	.string "bằng WAILMER PAIL.\p"
	.string "À, còn một điều nữa.\p"
	.string "Nếu em không hái BERRIES một thời gian,\n"
	.string "chúng sẽ rụng xuống đất. Nhưng rồi\l"
	.string "chúng sẽ lại nảy mầm.\p"
	.string "Tuyệt lắm, phải không? Cứ như chúng có\n"
	.string "ý chí sinh tồn vậy.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "Em đang cố noi theo các chị của mình. Em\n"
	.string "cũng trồng hoa đấy!\p"
	.string "Đây ạ! Tặng anh chị này!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "Bạn có thể trồng một BERRY cho thật\n"
	.string "lớn, hoặc cho POKéMON giữ nó.\p"
	.string "Nhưng giờ người ta đã có một cỗ máy\n"
	.string "trộn nhiều loại BERRIES để làm kẹo cho\l"
	.string "POKéMON.\p"
	.string "Mình cũng muốn ăn kẹo nữa.$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "Chào bạn, bạn tên gì?\p"
	.string "À, được rồi. Tên hay lắm!\p"
	.string "Mình tên là KIRI.\p"
	.string "Ba mẹ đặt tên ấy với mong ước mình sẽ\n"
	.string "lớn lên khỏe mạnh và có tấm lòng ấm áp.\l"
	.string "Đó là điều ba mẹ mong muốn.\p"
	.string "Tặng bạn một trong những thứ này.$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "KIRI cũng sẽ tặng bạn BERRY này! KIRI\n"
	.string "thích nó lắm đấy!$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "Không biết trong tên của bạn gửi gắm\n"
	.string "điều ước gì nhỉ.$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "Xuân, hạ, thu và đông.\p"
	.string "Nếu sinh vào mùa xuân thì bạn sẽ thích\n"
	.string "mùa xuân, còn nếu sinh vào mùa hè thì\l"
	.string "bạn sẽ thích mùa hè sao?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "Vậy KIRI sinh vào mùa thu nên KIRI yêu\n"
	.string "mùa thu!\p"
	.string "Bạn thích mùa nào?$"

SootopolisCity_Text_OhDoesntMatter:
	.string "Ồ, không quan trọng đâu.\p"
	.string "Có rất nhiều điều mình muốn biết.$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global PetalburgCity_Gym_Text_GiveEnigmaBerry
	.global Route104_Text_PlantBerriesInSoilTakeThis
	.global Route104_Text_TrainersOftenMakeMonHoldBerries
	.global Route111_Text_WateredPlantsEveryDayTakeBerry
	.global Route111_Text_GoingToTryToMakeDifferentColorBerries
	.global Route111_Text_WhatColorBerriesToLookForToday
	.global Route114_Text_LoveUsingBerryCrushShareBerry
	.global Route114_Text_TryBerryCrushWithFriends
	.global Route114_Text_FunToThinkAboutBerries
	.global Route120_Text_BerriesExpressionOfLoveIsntIt
	.global Route120_Text_YesYouUnderstand
	.global Route120_Text_MakeYourOwnImpressions
	.global Route120_Text_BerryIsRareRaiseItWithCare
	.global Route120_Text_IllGetMoreBerriesFromBerryMaster
	.global LilycoveCity_Text_BerrySuitsYou
	.global LilycoveCity_Text_BecauseYoureTrainer
	.global LilycoveCity_Text_PokeblocksSuitPokemon
	.global Route123_BerryMastersHouse_Text_YoureDeservingOfBerry
	.global Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother
	.global Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop
	.global Route123_BerryMastersHouse_Text_DoneForToday
	.global Route123_BerryMastersHouse_Text_HeardAGoodSayingLately
	.global Route123_BerryMastersHouse_Text_InspirationalTakeThis
	.global Route123_BerryMastersHouse_Text_GoodSayingTakeThis
	.global Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife
	.global Route123_BerryMastersHouse_Text_Ah
	.global Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop
	.global Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries
	.global Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries
	.global Route104_PrettyPetalFlowerShop_Text_BerriesExplanation
	.global Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness
	.global Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis
	.global Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation
	.global Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers
	.global Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries
	.global SootopolisCity_Text_NameIsKiriHaveOneOfThese
	.global SootopolisCity_Text_GiveYouThisBerryToo
	.global SootopolisCity_Text_WhatKindOfWishInYourName
	.global SootopolisCity_Text_LikeSeasonBornIn
	.global SootopolisCity_Text_ThenILoveAutumn
	.global SootopolisCity_Text_OhDoesntMatter
@ END GENERATED LOCALIZATION EXPORTS
