gText_Birch_Welcome::
	.string "Xin chào! Xin lỗi đã để bạn phải chờ!\p"
	.string "Chào mừng đến với thế giới POKéMON!\p"
	.string "Tên tôi là BIRCH.\p"
	.string "Nhưng mọi người đều gọi tôi là POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Đây là sinh vật mà chúng ta gọi là\n"
	.string "POKéMON.\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "Khắp thế giới này là nơi sinh sống của\n"
	.string "những sinh vật được gọi là POKéMON.\p"
	.string "Con người chúng ta sống bên POKéMON,\n"
	.string "khi thì là bạn thân thiết, khi lại là\l"
	.string "cộng sự cùng làm việc.\p"
	.string "Đôi khi, chúng ta còn sát cánh chiến\n"
	.string "đấu với những người khác cũng giống\l"
	.string "mình.\p"
	.string "Nhưng dù gần gũi như vậy, chúng ta vẫn\n"
	.string "chưa biết mọi điều về POKéMON.\p"
	.string "Thật ra, POKéMON vẫn còn ẩn chứa vô vàn\n"
	.string "bí mật.\p"
	.string "Để khám phá những bí ẩn về POKéMON, tôi\n"
	.string "vẫn luôn tiến hành nghiên cứu. Đó là\l"
	.string "công việc của tôi.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Còn bạn là?$"

gText_Birch_BoyOrGirl::
	.string "Bạn là con trai? Hay là con gái?$"

gText_Birch_WhatsYourName::
	.string "Được rồi. Bạn tên gì?$"

gText_Birch_SoItsPlayer::
	.string "Vậy bạn là {PLAYER}{KUN} phải không?$"

gText_Birch_YourePlayer::
	.string "À, ra vậy!\p"
	.string "Bạn là {PLAYER}{KUN}, người sắp chuyển\n"
	.string "đến quê tôi, LITTLEROOT. Giờ thì tôi\l"
	.string "hiểu rồi!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Được rồi, bạn sẵn sàng chưa?\p"
	.string "Cuộc phiêu lưu của riêng bạn sắp bắt\n"
	.string "đầu.\p"
	.string "Hãy can đảm bước vào thế giới POKéMON,\n"
	.string "nơi những ước mơ, cuộc phiêu lưu và\l"
	.string "tình bạn đang chờ đón!\p"
	.string "Tôi sẽ đợi bạn. Lát nữa hãy đến gặp tôi\n"
	.string "tại POKéMON LAB.\p"
	.string "$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global gText_Birch_Welcome
	.global gText_Birch_Pokemon
	.global gText_Birch_MainSpeech
	.global gText_Birch_AndYouAre
	.global gText_Birch_BoyOrGirl
	.global gText_Birch_WhatsYourName
	.global gText_Birch_SoItsPlayer
	.global gText_Birch_YourePlayer
	.global gText_Birch_AreYouReady
@ END GENERATED LOCALIZATION EXPORTS
