BerryBlender_Text_BlendWithTheBlendMaster:
	.string "BẬC THẦY: Đúng vậy! Ta chính là\n"
	.string "BẬC THẦY PHA CHẾ!\p"
	.string "Hãy phối trộn cùng ta, rồi ngươi sẽ\n"
	.string "được chứng kiến kỹ nghệ bậc thầy của\l"
	.string "ta!$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "BẬC THẦY: Hừm! Vậy ngươi muốn tận\n"
	.string "mắt chứng kiến kỹ nghệ bậc thầy của ta\l"
	.string "sao?$"

BerryBlender_Text_TooBusyNowIsee:
	.string "Hừm!\p"
	.string "Ra là giờ ngươi đang bận!\p"
	.string "Nhưng đừng lo! Ta sẽ ở đây cả ngày!\n"
	.string "Làm xong việc thì mau quay lại!$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "Hừm!\p"
	.string "Ngươi không có lấy một BERRY!\p"
	.string "Ta sẽ ở đây cả ngày! Mau mang BERRIES\n"
	.string "quay lại!$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "Tất nhiên! Tất nhiên rồi!\p"
	.string "À, nhân tiện, ngươi biết cách phối\n"
	.string "BERRIES thành {POKEBLOCK}S chứ?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "Hừm!\p"
	.string "À, nhưng cách làm rất đơn giản!\p"
	.string "Khi mũi tên của BLENDER chạm đến dấu\n"
	.string "của ngươi, chỉ cần nhấn A Button.\p"
	.string "Chỉ vậy thôi.\p"
	.string "Khi thấy ta nhấn A Button chính xác\n"
	.string "đến mức nào, ngươi sẽ hiểu.$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "Tốt!\p"
	.string "Vậy bắt đầu thôi!\p"
	.string "Cùng BẬC THẦY, hãy bắt đầu\n"
	.string "BERRY BLENDER!$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "Hừm!\p"
	.string "Có vẻ ngươi chưa lấy được\n"
	.string "{POKEBLOCK} CASE!\p"
	.string "Ta sẽ ở đây cả ngày! Hãy lấy\n"
	.string "{POKEBLOCK} CASE rồi mau quay lại!$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "Hừm!\p"
	.string "Có vẻ {POKEBLOCK} CASE của ngươi đã\n"
	.string "đầy!\p"
	.string "Ta sẽ ở đây cả ngày! Hãy dùng bớt\n"
	.string "{POKEBLOCK}S rồi mau quay lại!$"

BerryBlender_Text_WhoaAwesome:
	.string "Chà! Tuyệt quá!$"

BerryBlender_Text_WickedlyFast:
	.string "Nhanh kinh khủng!$"

BerryBlender_Text_WhatAnExpert:
	.string "Đúng là cao thủ!$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "Khi phối trộn cùng BẬC THẦY, chúng tôi\n"
	.string "đã làm {POKEBLOCK}S tuyệt vời!$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "Đôi mắt bám theo mũi tên với sự tập\n"
	.string "trung như máy móc.\p"
	.string "Bàn tay nhấn A Button chính xác như\n"
	.string "đồng hồ.\p"
	.string "Chính những phẩm chất ấy làm nên một\n"
	.string "BẬC THẦY PHA CHẾ thực thụ.$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "Nghe nói BẬC THẦY PHA CHẾ rèn kỹ năng\n"
	.string "sâu trong núi.\p"
	.string "Thỉnh thoảng ông ấy đến LILYCOVE và\n"
	.string "phối BERRIES suốt cả ngày.$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global BerryBlender_Text_BlendWithTheBlendMaster
	.global BerryBlender_Text_SeeMyMasteryInAction
	.global BerryBlender_Text_TooBusyNowIsee
	.global BerryBlender_Text_BlendMasterNoBerries
	.global BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks
	.global BerryBlender_Text_BlendMasterExplainBerryBlending
	.global BerryBlender_Text_BlendMasterLetsBerryBlender
	.global BerryBlender_Text_BlendMasterNoPokeblockCase
	.global BerryBlender_Text_BlendMasterPokeblockCaseFull
	.global BerryBlender_Text_WhoaAwesome
	.global BerryBlender_Text_WickedlyFast
	.global BerryBlender_Text_WhatAnExpert
	.global BerryBlender_Text_MadeAmazingPokeblocksWithMaster
	.global BerryBlender_Text_QualitiesOfBlendMaster
	.global BerryBlender_Text_MasterWorksOnSkillsInMountains
@ END GENERATED LOCALIZATION EXPORTS
