CableClub_Text_WelcomeWhichCableClubService:
	.string "Chào mừng đến với POKéMON CABLE\n"
	.string "CLUB.\p"
	.string "Bạn muốn sử dụng dịch vụ nào?$"

CableClub_Text_WhichService:
	.string "Bạn muốn sử dụng dịch vụ nào?$"

CableClub_Text_TradeUsingLinkCable::
	.string "Trao đổi POKéMON với người chơi khác\n"
	.string "bằng GBA Game Link cable.$"

CableClub_Text_BattleUsingLinkCable::
	.string "Đấu với một HLV khác bằng\n"
	.string "GBA Game Link cable.$"

CableClub_Text_RecordCornerUsingLinkCable::
	.string "Dùng RECORD CORNER với người khác\n"
	.string "qua GBA Game Link cable.$"

@ Unused
CableClub_Text_CloseThisMenu:
	.string "Đóng menu này.$"

CableClub_Text_NeedTwoMonsForDoubleBattle:
	.string "DOUBLE BATTLE yêu cầu bạn có\n"
	.string "ít nhất hai POKéMON.$"

CableClub_Text_NeedTwoMonsToTrade:
	.string "Để trao đổi, bạn phải mang theo\n"
	.string "ít nhất hai POKéMON.$"

CableClub_Text_CantTradeEnigmaBerry:
	.string "Không thể trao đổi POKéMON đang giữ\n"
	.string "{STR_VAR_1} BERRY.$"

gText_PleaseWaitForLink::
	.string "Vui lòng chờ.\n"
	.string "… … B Button: Cancel$"

gText_ConfirmLinkWhenPlayersReady::
	.string "Khi tất cả người chơi đã sẵn sàng…\n"
	.string "A Button: Confirm\l"
	.string "B Button: Cancel$"

gText_ConfirmStartLinkWithXPlayers::
	.string "Kết nối {STR_VAR_1} người chơi.\n"
	.string "A Button: Confirm\l"
	.string "B Button: Cancel$"

gText_AwaitingLinkup::
	.string "Đang chờ kết nối…\n"
	.string "… … B Button: Cancel$"

@ Unused
CableClub_Text_OkayToSaveProgress::
	.string "Cần lưu tiến trình trước khi kết nối.\n"
	.string "Bạn có muốn lưu không?$"

CableClub_Text_PleaseEnter:
	.string "Xin mời vào.$"

CableClub_Text_DirectYouToYourRoom:
	.string "Tôi sẽ dẫn bạn đến phòng.$"

Text_SomeoneIsNotReadyToLink:
	.string "Có người chưa sẵn sàng kết nối.\p"
	.string "Hãy quay lại khi mọi người đã\n"
	.string "chuẩn bị xong.$"

Text_LinkErrorPleaseReset:
	.string "Xin lỗi, kết nối đã gặp lỗi…\n"
	.string "Hãy reset rồi thử lại.$"

Text_PlayersMadeDifferentSelections:
	.string "Có vẻ những người kết nối đã chọn\n"
	.string "các mục khác nhau.$"

CableClub_Text_PleaseVisitAgain:
	.string "Hẹn gặp lại bạn.$"

CableClub_Text_IncorrectNumberOfParticipants:
	.string "Số người tham gia không đúng.$"

CableClub_Text_CantSingleBattleWithXPlayers:
	.string "Không thể chơi SINGLE BATTLE với\n"
	.string "{STR_VAR_1} người chơi.$"

CableClub_Text_CantDoubleBattleWithXPlayers:
	.string "Không thể chơi DOUBLE BATTLE với\n"
	.string "{STR_VAR_1} người chơi.$"

CableClub_Text_NeedFourPlayers:
	.string "Battle Mode này yêu cầu đủ\n"
	.string "bốn người chơi.$"

CableClub_Text_PleaseConfirmNumberAndRestart:
	.string "Hãy kiểm tra số người chơi rồi\n"
	.string "bắt đầu lại.$"

Text_TerminateLinkConfirmation:
	.string "Kết nối sẽ bị ngắt nếu bạn rời phòng.\n"
	.string "Bạn vẫn muốn rời đi?$"

Text_TerminateLinkPleaseWait:
	.string "Đang ngắt kết nối…\n"
	.string "Bạn sẽ được đưa ra khỏi phòng.\l"
	.string "Vui lòng chờ.$"

CableClub_Text_TooBusyToNotice:
	.string "HLV này quá bận nên không\n"
	.string "để ý đến bạn…$"

CableClub_Text_GotToLookAtTrainerCard:
	.string "Tuyệt! Đã xem được TRAINER CARD\n"
	.string "của {STR_VAR_1}!$"

CableClub_Text_GotToLookAtColoredTrainerCard:
	.string "Tuyệt! Đã xem được TRAINER CARD\n"
	.string "của {STR_VAR_1}!\p"
	.string "Đó là thẻ {STR_VAR_2}!$"

BattleColosseum_2P_Text_TakePlaceStartBattle:
	.string "Hãy vào vị trí và bắt đầu\n"
	.string "trận đấu.$"

TradeCenter_Text_TakeSeatStartTrade:
	.string "Hãy vào chỗ và bắt đầu\n"
	.string "trao đổi.$"

RecordCorner_Text_ThanksForComing:
	.string "Cảm ơn bạn đã đến.$"

CableClub_Text_TrainerCardDataOverwritten:
	.string "Dữ liệu TRAINER CARD sẽ bị\n"
	.string "ghi đè.$"

CableClub_Text_HopeToSeeYouAgain:
	.string "Hẹn gặp lại bạn!$"

CableClub_Text_NotSetUpForFarAwayRegion:
	.string "Tôi thành thật xin lỗi.\p"
	.string "Hiện chúng tôi chưa thể trao đổi với\n"
	.string "HLV ở một vùng đất xa xôi khác…$"

CableClub_Text_OtherTrainerNotReady:
	.string "HLV kia chưa sẵn sàng.$"

CableClub_Text_YouHaveAMonThatCantBeTaken:
	.string "Bạn có ít nhất một POKéMON\n"
	.string "không thể mang theo.$"

RecordCorner_Text_TakeSeatAndWait:
	.string "Hãy vào chỗ và chờ một lát.$"

RecordCorner_Text_PlayerSentOverOneX:
	.string "{STR_VAR_1} đã gửi sang một\n"
	.string "{STR_VAR_2}.$"

CableClub_Text_CantMixWithJapaneseGame:
	.string "Xin lỗi, đã xảy ra lỗi truyền dữ liệu.\p"
	.string "Không thể trộn dữ liệu với bản Ruby\n"
	.string "hoặc Sapphire tiếng Nhật.\p"
	.string "Cũng không thể trộn dữ liệu đồng thời\n"
	.string "giữa Emerald tiếng Nhật và Ruby hoặc\l"
	.string "Sapphire quốc tế.$"

CableClub_Text_AdapterNotConnected:
	.string "Wireless Adapter chưa được\n"
	.string "kết nối đúng cách.$"

CableClub_Text_ParticipantsStepUpToCounter:
	.string "Mời những người tham gia đến\n"
	.string "quầy tiếp tân.$"

@ Unused
CableClub_Text_Hello:
	.string "Xin chào!$"

@ Unused
CableClub_Text_PleaseWait:
	.string "Vui lòng chờ.$"

CableClub_Text_YouMayTradeHere::
	.string "Tại đây, bạn có thể trao đổi POKéMON\n"
	.string "với một HLV khác.$"

CableClub_Text_YouMayBattleHere::
	.string "Tại đây, bạn có thể đấu với\n"
	.string "bạn bè.$"

CableClub_Text_CanMakeBerryPowder::
	.string "Từ hai đến năm HLV có thể cùng\n"
	.string "làm BERRY POWDER.$"

CableClub_Text_CanMixRecords::
	.string "Có thể trộn dữ liệu của từ hai đến\n"
	.string "bốn người chơi.$"

@ Unused
CableClub_Text_GuideToVariousServices:
	.string "Hướng dẫn về các dịch vụ khác nhau\n"
	.string "của WIRELESS CLUB.$"

CableClub_Text_CancelSelectedItem::
	.string "Hủy mục MENU đã chọn.$"

@ Unused
CableClub_Text_WhichBattleMode:
	.string "Bạn muốn chọn Battle Mode nào?$"

@ Unused
CableClub_Text_ReturnsToPreviousStep:
	.string "Quay lại bước trước.$"

CableClub_Text_NeedBerryForBerryCrush:
	.string "Để dùng BERRY CRUSH, bạn phải có\n"
	.string "ít nhất một BERRY.$"

CableClub_Text_NeedTwoMonsForUnionRoom:
	.string "Để vào UNION ROOM, bạn phải mang\n"
	.string "theo ít nhất hai POKéMON.$"

CableClub_Text_NoEnigmaBerryInUnionRoom:
	.string "POKéMON giữ {STR_VAR_1} BERRY\n"
	.string "không thể vào UNION ROOM.$"

CableClub_Text_UnionRoomAdapterNotConnected:
	.string "Đây là POKéMON WIRELESS CLUB\n"
	.string "UNION ROOM.\p"
	.string "Rất tiếc, Wireless Adapter của bạn\n"
	.string "chưa được kết nối đúng cách.\p"
	.string "Hẹn gặp lại bạn.$"

@ Unused
CableClub_Text_OhExcuseMe:
	.string "Ồ…\n"
	.string "Xin lỗi!$"

CableClub_Text_PlayerIsWaiting:
	.string "Có vẻ {STR_VAR_1} đang chơi.\n"
	.string "Hãy tham gia đi!$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame:
	.string "Nếu muốn, tôi có thể giải thích\n"
	.string "luật chơi cho bạn.\p"
	.string "Bạn muốn nghe về trò nào?$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo:
	.string "“POKéMON JUMP”\p"
	.string "Nhấn A Button để POKéMON nhảy qua\n"
	.string "dây VINE WHIP.\p"
	.string "Chỉ POKéMON nhỏ cao khoảng 28 inch\n"
	.string "trở xuống mới được tham gia.\p"
	.string "POKéMON chỉ biết bơi, đào đất\n"
	.string "hoặc bay đều không giỏi nhảy.\p"
	.string "Vì vậy, chúng không thể tham gia.\p"
	.string "Điều tốt đẹp sẽ xảy ra nếu mọi người\n"
	.string "nhảy đúng nhịp.$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo:
	.string "“DODRIO BERRY-PICKING”\p"
	.string "Điều khiển ba chiếc đầu của DODRIO\n"
	.string "để bắt BERRIES đang rơi.\p"
	.string "Nhấn phải, lên hoặc trái trên\n"
	.string "{PLUS} Control Pad để di chuyển đầu.\p"
	.string "Bạn phải có DODRIO mới chơi được.$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay:
	.string "Nếu muốn chơi, hãy nói chuyện với\n"
	.string "ông lão bên cạnh tôi.$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait:
	.string "Xin chào, chào mừng bạn!\n"
	.string "Bạn đến chơi bằng Wireless\l"
	.string "Communication phải không?\p"
	.string "Bạn chờ một lát nhé?$"

MossdeepCity_GameCorner_1F_Text_ComeAgain:
	.string "Được rồi, hẹn gặp lại!$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected:
	.string "Wireless Adapter chưa được kết nối.\n"
	.string "Hãy quay lại sau khi kết nối nhé!$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame:
	.string "Được rồi, bạn muốn chơi\n"
	.string "trò nào?$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon:
	.string "Bạn muốn cho POKéMON nào\n"
	.string "tham gia?$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo:
	.string "Được rồi, mọi thứ đã sẵn sàng.\n"
	.string "Đừng để người khác đánh bại nhé!$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain:
	.string "Bạn về bây giờ sao?\n"
	.string "Hẹn gặp lại!$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon:
	.string "Có vẻ bạn không có POKéMON nào\n"
	.string "đủ điều kiện tham gia…\p"
	.string "Bạn muốn tôi giải thích loại POKéMON\n"
	.string "nào có thể tham gia không?$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed:
	.string "“POKéMON JUMP” dành cho POKéMON\n"
	.string "cao khoảng 28 inch trở xuống.\p"
	.string "POKéMON không biết nhảy\n"
	.string "sẽ không được tham gia.\p"
	.string "Chẳng hạn như POKéMON chỉ biết\n"
	.string "bơi, đào đất hoặc bay.\p"
	.string "Bạn chỉ cần biết vậy thôi.$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed:
	.string "DODRIO BERRY-PICKING là trò chơi\n"
	.string "chỉ DODRIO được tham gia.$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease:
	.string "Bạn vui lòng thử lại\n"
	.string "từ đầu nhé?$"

CableClub_Text_WelcomeWhichDirectCornerRoom:
	.string "Chào mừng đến với POKéMON WIRELESS\n"
	.string "CLUB DIRECT CORNER.\p"
	.string "Tại đây, bạn có thể kết nối trực tiếp\n"
	.string "với bạn bè.\p"
	.string "Bạn muốn vào phòng nào?$"

CableClub_Text_TradePokemon:
	.string "Bạn muốn trao đổi POKéMON?$"

CableClub_Text_PlayWhichBattleMode:
	.string "Bạn muốn chơi Battle Mode nào?$"

CableClub_Text_AccessRecordCorner:
	.string "Bạn muốn vào RECORD CORNER?$"

CableClub_Text_UseBerryCrush:
	.string "Bạn muốn dùng BERRY CRUSH System?$"

CableClub_Text_ExplainBattleModes:
	.string "Có ba Battle Mode.\p"
	.string "SINGLE BATTLE dành cho hai HLV,\n"
	.string "mỗi người có ít nhất một POKéMON.\p"
	.string "Mỗi HLV đưa một POKéMON ra đấu\n"
	.string "trong cùng một thời điểm.\p"
	.string "DOUBLE BATTLE dành cho hai HLV,\n"
	.string "mỗi người có ít nhất hai POKéMON.\p"
	.string "Mỗi HLV đưa hai POKéMON ra đấu\n"
	.string "trong cùng một thời điểm.\p"
	.string "MULTI BATTLE dành cho bốn HLV,\n"
	.string "mỗi người có ít nhất một POKéMON.\p"
	.string "Mỗi HLV đưa một POKéMON ra đấu\n"
	.string "trong cùng một thời điểm.$"

CableClub_Text_ChooseGroupLeaderOfTwo:
	.string "Hai bạn hãy chọn một người làm\n"
	.string "LEADER.\p"
	.string "Người còn lại hãy chọn\n"
	.string "“JOIN GROUP.”$"

CableClub_Text_ChooseGroupLeaderOfFour:
	.string "Bốn bạn hãy chọn một người làm\n"
	.string "GROUP LEADER.\p"
	.string "Những người còn lại hãy chọn\n"
	.string "“JOIN GROUP.”$"

CableClub_Text_ChooseGroupLeader:
	.string "Hãy chọn một người làm\n"
	.string "GROUP LEADER.\p"
	.string "Những người còn lại hãy chọn\n"
	.string "“JOIN GROUP.”$"

CableClub_Text_WelcomeUnionRoomEnter:
	.string "Chào mừng đến với POKéMON WIRELESS\n"
	.string "CLUB UNION ROOM.\p"
	.string "Tại đây, bạn có thể kết nối trực tiếp\n"
	.string "với cả những HLV chưa quen biết.\p"
	.string "Bạn có muốn vào ROOM không?$"

CableClub_Text_UnionRoomInfo:
	.string "Các HLV trong UNION ROOM là\n"
	.string "người chơi ở gần cũng đã vào ROOM.\p"
	.string "Tại đây, bạn có thể chào hỏi và\n"
	.string "tham gia nhiều hoạt động khác.\p"
	.string "Bạn có thể mang hai POKéMON từ\n"
	.string "Lv. 30 trở xuống để đấu một chọi một.\p"
	.string "Bạn có thể trò chuyện trong nhóm\n"
	.string "từ hai đến năm người.\p"
	.string "Hoặc đăng ký một POKéMON để\n"
	.string "trao đổi.\p"
	.string "Bạn có muốn vào ROOM không?$"

CableClub_Text_EnjoyUnionRoom:
	.string "Chúc bạn có thời gian vui vẻ trong\n"
	.string "UNION ROOM.$"

CableClub_Text_FirstTimeRightThisWay:
	.string "Xin chào!\n"
	.string "Tên tôi là TEALA.\p"
	.string "Có lẽ đây là lần đầu bạn lên\n"
	.string "tầng này.\p"
	.string "Tôi sẽ hướng dẫn cách hoạt động của\n"
	.string "Wireless Communication System.\p"
	.string "Trước tiên, tôi sẽ giới thiệu tầng này\n"
	.string "của POKéMON CENTER.\p"
	.string "Xin mời đi theo tôi.$"

CableClub_Text_ExplainWirelessClubFirstTime:
	.string "Tầng trên cùng có hai phòng.\p"
	.string "Phòng bên trái là UNION ROOM.\p"
	.string "Bạn có thể kết nối với các HLV\n"
	.string "ở gần cũng đã vào UNION ROOM.\p"
	.string "Mọi người có thể trò chuyện, chiến đấu\n"
	.string "và trao đổi với nhau.\p"
	.string "Phòng bên phải là DIRECT CORNER.\p"
	.string "Tại đây, bạn có thể đấu hoặc trao đổi\n"
	.string "POKéMON với bạn bè.\p"
	.string "Nếu không kết nối Wireless Adapter,\n"
	.string "bạn có thể dùng GBA Game Link cable.\p"
	.string "Trong trường hợp đó, hãy đến\n"
	.string "DIRECT CORNER.\p"
	.string "Chúc bạn vui vẻ với Wireless\n"
	.string "Communication System.$"

CableClub_Text_AskAboutLinking:
	.string "Xin chào, {PLAYER}!\p"
	.string "Tôi là TEALA, nhân viên tầng 2 của\n"
	.string "POKéMON CENTER.\p"
	.string "Bạn muốn hỏi gì về việc kết nối?$"

CableClub_Text_ExplainWirelessClub:
	.string "Tôi sẽ giải thích cách hoạt động của\n"
	.string "POKéMON WIRELESS CLUB.\p"
	.string "Tầng trên cùng có hai phòng.\p"
	.string "Phòng bên trái là UNION ROOM.\p"
	.string "Bạn có thể kết nối với các HLV\n"
	.string "ở gần cũng đã vào UNION ROOM.\p"
	.string "Mọi người có thể trò chuyện, chiến đấu\n"
	.string "và trao đổi với nhau.\p"
	.string "Phòng bên phải là DIRECT CORNER.\p"
	.string "Tại đây, bạn có thể đấu hoặc trao đổi\n"
	.string "POKéMON với bạn bè.\p"
	.string "Đôi khi bạn không thể tìm thấy bạn bè\n"
	.string "trong hai phòng này.\p"
	.string "Khi đó, hãy đến gần họ hơn.\p"
	.string "Nếu không kết nối Wireless Adapter,\n"
	.string "bạn có thể dùng GBA Game Link cable.\p"
	.string "Trong trường hợp đó, hãy đến\n"
	.string "DIRECT CORNER.\p"
	.string "Chúc bạn vui vẻ với Wireless\n"
	.string "Communication System.$"

CableClub_Text_HopeYouEnjoyWirelessSystem:
	.string "Chúc bạn vui vẻ với Wireless\n"
	.string "Communication System.$"

CableClub_Text_TradeWithYourself:
	.string "Bạn muốn tự trao đổi POKéMON\n"
	.string "với chính mình?$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global CableClub_Text_WelcomeWhichCableClubService
	.global CableClub_Text_WhichService
	.global CableClub_Text_TradeUsingLinkCable
	.global CableClub_Text_BattleUsingLinkCable
	.global CableClub_Text_RecordCornerUsingLinkCable
	.global CableClub_Text_CloseThisMenu
	.global CableClub_Text_NeedTwoMonsForDoubleBattle
	.global CableClub_Text_NeedTwoMonsToTrade
	.global CableClub_Text_CantTradeEnigmaBerry
	.global gText_PleaseWaitForLink
	.global gText_ConfirmLinkWhenPlayersReady
	.global gText_ConfirmStartLinkWithXPlayers
	.global gText_AwaitingLinkup
	.global CableClub_Text_OkayToSaveProgress
	.global CableClub_Text_PleaseEnter
	.global CableClub_Text_DirectYouToYourRoom
	.global Text_SomeoneIsNotReadyToLink
	.global Text_LinkErrorPleaseReset
	.global Text_PlayersMadeDifferentSelections
	.global CableClub_Text_PleaseVisitAgain
	.global CableClub_Text_IncorrectNumberOfParticipants
	.global CableClub_Text_CantSingleBattleWithXPlayers
	.global CableClub_Text_CantDoubleBattleWithXPlayers
	.global CableClub_Text_NeedFourPlayers
	.global CableClub_Text_PleaseConfirmNumberAndRestart
	.global Text_TerminateLinkConfirmation
	.global Text_TerminateLinkPleaseWait
	.global CableClub_Text_TooBusyToNotice
	.global CableClub_Text_GotToLookAtTrainerCard
	.global CableClub_Text_GotToLookAtColoredTrainerCard
	.global BattleColosseum_2P_Text_TakePlaceStartBattle
	.global TradeCenter_Text_TakeSeatStartTrade
	.global RecordCorner_Text_ThanksForComing
	.global CableClub_Text_TrainerCardDataOverwritten
	.global CableClub_Text_HopeToSeeYouAgain
	.global CableClub_Text_NotSetUpForFarAwayRegion
	.global CableClub_Text_OtherTrainerNotReady
	.global CableClub_Text_YouHaveAMonThatCantBeTaken
	.global RecordCorner_Text_TakeSeatAndWait
	.global RecordCorner_Text_PlayerSentOverOneX
	.global CableClub_Text_CantMixWithJapaneseGame
	.global CableClub_Text_AdapterNotConnected
	.global CableClub_Text_ParticipantsStepUpToCounter
	.global CableClub_Text_Hello
	.global CableClub_Text_PleaseWait
	.global CableClub_Text_YouMayTradeHere
	.global CableClub_Text_YouMayBattleHere
	.global CableClub_Text_CanMakeBerryPowder
	.global CableClub_Text_CanMixRecords
	.global CableClub_Text_GuideToVariousServices
	.global CableClub_Text_CancelSelectedItem
	.global CableClub_Text_WhichBattleMode
	.global CableClub_Text_ReturnsToPreviousStep
	.global CableClub_Text_NeedBerryForBerryCrush
	.global CableClub_Text_NeedTwoMonsForUnionRoom
	.global CableClub_Text_NoEnigmaBerryInUnionRoom
	.global CableClub_Text_UnionRoomAdapterNotConnected
	.global CableClub_Text_OhExcuseMe
	.global CableClub_Text_PlayerIsWaiting
	.global MossdeepCity_GameCorner_1F_Text_DescribeWhichGame
	.global MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo
	.global MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo
	.global MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay
	.global MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait
	.global MossdeepCity_GameCorner_1F_Text_ComeAgain
	.global MossdeepCity_GameCorner_1F_Text_AdapterNotConnected
	.global MossdeepCity_GameCorner_1F_Text_PlayWhichGame
	.global MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon
	.global MossdeepCity_GameCorner_1F_Text_AllGoodToGo
	.global MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain
	.global MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon
	.global MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed
	.global MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed
	.global MossdeepCity_GameCorner_1F_Text_RetryPlease
	.global CableClub_Text_WelcomeWhichDirectCornerRoom
	.global CableClub_Text_TradePokemon
	.global CableClub_Text_PlayWhichBattleMode
	.global CableClub_Text_AccessRecordCorner
	.global CableClub_Text_UseBerryCrush
	.global CableClub_Text_ExplainBattleModes
	.global CableClub_Text_ChooseGroupLeaderOfTwo
	.global CableClub_Text_ChooseGroupLeaderOfFour
	.global CableClub_Text_ChooseGroupLeader
	.global CableClub_Text_WelcomeUnionRoomEnter
	.global CableClub_Text_UnionRoomInfo
	.global CableClub_Text_EnjoyUnionRoom
	.global CableClub_Text_FirstTimeRightThisWay
	.global CableClub_Text_ExplainWirelessClubFirstTime
	.global CableClub_Text_AskAboutLinking
	.global CableClub_Text_ExplainWirelessClub
	.global CableClub_Text_HopeYouEnjoyWirelessSystem
	.global CableClub_Text_TradeWithYourself
@ END GENERATED LOCALIZATION EXPORTS
