Text_PictureBookShelf:
	.string "Có một bộ sách tranh về POKéMON.$"

Text_BookShelf:
	.string "Kệ đầy đủ loại sách.$"

Text_PokemonCenterBookShelf:
	.string "POKéMON magazines!\n"
	.string "POKéMON PAL…\p"
	.string "POKéMON HANDBOOK…\n"
	.string "ADORABLE POKéMON…$"

Text_Vase:
	.string "Chiếc bình này trông đắt tiền…\n"
	.string "Nhìn vào bên trong…\p"
	.string "Nhưng nó trống rỗng.$"

Text_EmptyTrashCan:
	.string "Bên trong trống không.$"

Text_ShopShelf:
	.string "Các kệ chất đầy đủ loại\n"
	.string "hàng hóa POKéMON.$"

Text_Blueprint:
	.string "Một loại bản thiết kế nào đó?\n"
	.string "Phức tạp quá!$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global Text_PictureBookShelf
	.global Text_BookShelf
	.global Text_Vase
	.global Text_EmptyTrashCan
	.global Text_ShopShelf
	.global Text_Blueprint
@ END GENERATED LOCALIZATION EXPORTS
