@ Contest move effect descriptions

gText_HighlyAppealingMove::
	.string "Một chiêu thức cực kỳ cuốn hút.$"

gText_UserMoreEasilyStartled::
	.string "Sau chiêu thức này, người dùng dễ bị\n"
	.string "giật mình hơn.$"

gText_GreatAppealButNoMoreToEnd::
	.string "Rất cuốn hút, nhưng không thể\n"
	.string "trình diễn thêm.$"

gText_UsedRepeatedlyWithoutBoringJudge::
	.string "Có thể dùng liên tiếp mà không làm\n"
	.string "GIÁM KHẢO chán.$"

gText_AvoidStartledByOthersOnce::
	.string "Có thể tránh bị các POKéMON khác làm\n"
	.string "giật mình một lần.$"

gText_AvoidStartledByOthers::
	.string "Có thể tránh bị các POKéMON khác làm\n"
	.string "giật mình.$"

gText_AvoidStartledByOthersLittle::
	.string "Giúp phần nào tránh bị các POKéMON khác\n"
	.string "làm giật mình.$"

gText_UserLessLikelyStartled::
	.string "Sau chiêu thức này, người dùng ít bị\n"
	.string "giật mình hơn.$"

gText_SlightlyStartleFrontMon::
	.string "Làm POKéMON ngay phía trước hơi giật\n"
	.string "mình.$"

gText_SlightlyStartleAppealed::
	.string "Làm những POKéMON đã trình diễn hơi\n"
	.string "giật mình.$"

gText_StartleAppealedBeforeUser::
	.string "Làm POKéMON trình diễn ngay trước\n"
	.string "người dùng giật mình.$"

gText_StartleAllAppealed::
	.string "Làm tất cả POKéMON đã trình diễn giật\n"
	.string "mình.$"

gText_BadlyStartleFrontMon::
	.string "Làm POKéMON ngay phía trước giật mình\n"
	.string "dữ dội.$"

gText_BadlyStartleAppealed::
	.string "Làm những POKéMON đã trình diễn giật\n"
	.string "mình dữ dội.$"

gText_StartleAppealedBeforeUser2::
	.string "Làm POKéMON trình diễn ngay trước\n"
	.string "người dùng giật mình.$"

gText_StartleAllAppealed2::
	.string "Làm tất cả POKéMON đã trình diễn giật\n"
	.string "mình.$"

gText_ShiftJudgesAttentionFromOthers::
	.string "Chuyển sự chú ý của GIÁM KHẢO\n"
	.string "khỏi các POKéMON khác.$"

gText_StartleMonHasJudgesAttention::
	.string "Làm POKéMON đang được GIÁM KHẢO\n"
	.string "chú ý giật mình.$"

gText_JamOthersMissesTurn::
	.string "Cản trở đối thủ, nhưng mất một lượt\n"
	.string "trình diễn.$"

gText_StartleMonsMadeSameTypeAppeal::
	.string "Làm các POKéMON đã trình diễn cùng loại\n"
	.string "giật mình.$"

gText_BadlyStartleCoolAppeals::
	.string "Làm các POKéMON đã trình diễn COOL\n"
	.string "giật mình dữ dội.$"

gText_BadlyStartleBeautyAppeals::
	.string "Làm các POKéMON đã trình diễn BEAUTY\n"
	.string "giật mình dữ dội.$"

gText_BadlyStartleCuteAppeals::
	.string "Làm các POKéMON đã trình diễn CUTE\n"
	.string "giật mình dữ dội.$"

gText_BadlyStartleSmartAppeals::
	.string "Làm các POKéMON đã trình diễn SMART\n"
	.string "giật mình dữ dội.$"

gText_BadlyStartleToughAppeals::
	.string "Làm các POKéMON đã trình diễn TOUGH\n"
	.string "giật mình dữ dội.$"

gText_MakeMonAfterUserNervous::
	.string "Làm một POKéMON phía sau căng\n"
	.string "thẳng.$"

gText_MakeAllMonsAfterUserNervous::
	.string "Làm mọi POKéMON phía sau căng\n"
	.string "thẳng.$"

gText_WorsenConditionOfThoseMadeAppeals::
	.string "Làm giảm phong độ của những POKéMON\n"
	.string "đã trình diễn.$"

gText_BadlyStartleMonsGoodCondition::
	.string "Làm POKéMON có phong độ tốt\n"
	.string "giật mình dữ dội.$"

gText_AppealGreatIfPerformedFirst::
	.string "Hiệu quả cao nếu trình diễn\n"
	.string "đầu tiên.$"

gText_AppealGreatIfPerformedLast::
	.string "Hiệu quả cao nếu trình diễn\n"
	.string "cuối cùng.$"

gText_AppealAsGoodAsThoseBeforeIt::
	.string "Giúp màn trình diễn hay ngang những\n"
	.string "màn trước đó.$"

gText_AppealAsGoodAsOneBeforeIt::
	.string "Giúp màn trình diễn hay ngang màn ngay\n"
	.string "trước đó.$"

gText_AppealBetterLaterItsPerformed::
	.string "Càng thực hiện muộn, màn trình diễn\n"
	.string "càng hiệu quả.$"

gText_AppealVariesDependingOnTiming::
	.string "Hiệu quả thay đổi theo thời điểm\n"
	.string "trình diễn.$"

gText_WorksWellIfSameTypeAsBefore::
	.string "Đạt hiệu quả cao nếu cùng loại với màn\n"
	.string "ngay trước đó.$"

gText_WorksWellIfDifferentTypeAsBefore::
	.string "Đạt hiệu quả cao nếu khác loại với màn\n"
	.string "ngay trước đó.$"

gText_AffectedByAppealInFront::
	.string "Phụ thuộc màn trình diễn ngay\n"
	.string "trước đó.$"

gText_UpsConditionHelpsPreventNervousness::
	.string "Tăng phong độ và giúp tránh\n"
	.string "căng thẳng.$"

gText_AppealWorksWellIfConditionGood::
	.string "Hiệu quả cao khi phong độ\n"
	.string "tốt.$"

gText_NextAppealMadeEarlier::
	.string "Lượt sau có thể trình diễn\n"
	.string "sớm hơn.$"

gText_NextAppealMadeLater::
	.string "Lượt sau có thể trình diễn\n"
	.string "muộn hơn.$"

gText_TurnOrderMoreEasilyScrambled::
	.string "Khiến thứ tự biểu diễn ở lượt sau dễ bị\n"
	.string "xáo trộn hơn.$"

gText_ScrambleOrderOfNextAppeals::
	.string "Xáo trộn thứ tự biểu diễn ở lượt sau.$"

gText_AppealExcitesAudienceInAnyContest::
	.string "Làm khán giả phấn khích trong\n"
	.string "mọi cuộc thi.$"

gText_BadlyStartlesMonsGoodAppeals::
	.string "Làm POKéMON trình diễn tốt\n"
	.string "giật mình dữ dội.$"

gText_AppealBestMoreCrowdExcited::
	.string "Đám đông càng phấn khích,\n"
	.string "hiệu quả càng cao.$"

gText_TemporarilyStopCrowdExcited::
	.string "Tạm thời ngăn đám đông trở nên phấn\n"
	.string "khích.$"

@ Unused move names

gText_RainDance::
	.string "RAIN DANCE$"

gText_Rage::
	.string "RAGE$"

gText_FocusEnergy::
	.string "FOCUS ENERGY$"

gText_Hypnosis::
	.string "HYPNOSIS$"

gText_Softboiled::
	.string "SOFTBOILED$"

gText_HornAttack::
	.string "HORN ATTACK$"

gText_SwordsDance::
	.string "SWORDS DANCE$"

gText_Conversion::
	.string "CONVERSION$"

gText_SunnyDay::
	.string "SUNNY DAY$"

gText_Rest2::
	.string "REST$"

gText_Vicegrip::
	.string "VICEGRIP$"

gText_DefenseCurl::
	.string "DEFENSE CURL$"

gText_LockOn::
	.string "LOCK-ON$"

@ Contest type names

gContestMoveTypeCoolText::
	.string "COOL$"

gContestMoveTypeBeautyText::
	.string "BEAUTY$"

gContestMoveTypeCuteText::
	.string "CUTE$"

gContestMoveTypeSmartText::
	.string "SMART$"

gContestMoveTypeToughText::
	.string "TOUGH$"

gText_AppealNumWhichMoveWillBePlayed::
	.string "Lượt biểu diễn số {STR_VAR_1}!\n"
	.string "Sẽ dùng chiêu nào?$"

gText_AppealNumButItCantParticipate::
	.string "Lượt biểu diễn số {STR_VAR_1}!\n"
	.string "Nhưng không thể tham gia!$"

gText_MonAppealedWithMove::
	.string "{STR_VAR_1} biểu diễn bằng\n"
	.string "{STR_VAR_2}!$"

gText_MonWasWatchingOthers::
	.string "{STR_VAR_1} đứng quan sát\n"
	.string "những POKéMON khác.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AllOutOfAppealTime::
	.string "Thời gian biểu diễn đã hết!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

@ Unused appeal result texts

gText_ButAppealWasJammed::
	.string "Nhưng màn biểu diễn đã bị phá rối.$"

gText_FollowedAnotherMonsLead::
	.string "Nó làm theo màn biểu diễn của một\n"
	.string "POKéMON khác.$"

gText_ButItMessedUp::
	.string "Nhưng nó đã làm hỏng.$"

gText_WentBetterThanUsual::
	.string "Mọi chuyện diễn ra tốt hơn thường lệ.$"

gText_JudgeLookedAwayForSomeReason::
	.string "Không hiểu sao GIÁM KHẢO lại nhìn\n"
	.string "sang chỗ khác.$"

gText_WorkedHardToBuildOnPastMistakes::
	.string "Nó nỗ lực rút kinh nghiệm từ những sai\n"
	.string "lầm trước đó.$"

gText_CantMakeAnyMoreMoves::
	.string "Nó không thể thực hiện thêm chiêu nào\n"
	.string "nữa.$"

gText_WorkedFrighteninglyWell::
	.string "Nó phát huy hiệu quả tốt đến đáng sợ.$"

gText_WorkedHardAsStandoutMon::
	.string "Nó nỗ lực không kém POKéMON nổi bật\n"
	.string "nhất.$"

gText_JudgedLookedOnExpectantly::
	.string "GIÁM KHẢO chăm chú quan sát\n"
	.string "với vẻ mong đợi.$"

gText_WorkedRatherWell::
	.string "Nó phát huy hiệu quả khá tốt.$"

gText_WorkedLittleBetterThanUsual::
	.string "Nó phát huy hiệu quả tốt hơn thường lệ\n"
	.string "một chút.$"

@ Round result texts

gText_MonFailedToStandOutAtAll::
	.string "{STR_VAR_1} hoàn toàn không tạo\n"
	.string "được ấn tượng.{PAUSE_UNTIL_PRESS}$"

gText_MonDidntStandOutVeryMuch::
	.string "{STR_VAR_1} không tạo được mấy\n"
	.string "ấn tượng.{PAUSE_UNTIL_PRESS}$"

gText_MonCaughtALittleAttention::
	.string "{STR_VAR_1} thu hút được một\n"
	.string "chút chú ý.{PAUSE_UNTIL_PRESS}$"

gText_MonAttractedALotOfAttention::
	.string "{STR_VAR_1} thu hút rất nhiều sự\n"
	.string "chú ý.{PAUSE_UNTIL_PRESS}$"

gText_MonCommandedTotalAttention::
	.string "{STR_VAR_1} thu hút toàn bộ sự\n"
	.string "chú ý.{PAUSE_UNTIL_PRESS}$"

gText_MonHasntMadeItsAppeal::
	.string "{STR_VAR_1} vẫn chưa biểu diễn.{PAUSE_UNTIL_PRESS}$"

@ Unused
gText_AnticipationSwelledForMonsAppealNext2::
	.string "Mọi người càng háo hức chờ màn biểu\n"
	.string "diễn tiếp theo của {STR_VAR_1}.$"

gText_EmptyContestString::
	.string "$"

gText_JudgesViewsOnMonHeldFirm::
	.string "Nhận định của GIÁM KHẢO về\n"
	.string "{STR_VAR_1} vẫn không thay đổi.$"

gText_MonsXChangedPerceptions::
	.string "{STR_VAR_1} đã thay đổi cách\n"
	.string "nhìn của mọi người bằng\l"
	.string "{STR_VAR_3}.$"

gText_MonsAppealEffectWoreOff::
	.string "Hiệu ứng từ màn biểu diễn của\n"
	.string "{STR_VAR_1} đã hết.$"

gText_SpecialAppealsEffectWoreOff::
	.string "Hiệu ứng của màn biểu diễn đặc biệt đã\n"
	.string "hết.$"

gText_EveryonesAppealsMadeToLookSame::
	.string "Màn biểu diễn của tất cả đều trông\n"
	.string "giống nhau.$"

gText_CheapenedMonsAppeal::
	.string "Nó làm màn biểu diễn của\n"
	.string "{STR_VAR_2} kém nổi bật.$"

gText_CheapenedAppealOfThoseAhead::
	.string "Nó làm màn biểu diễn của các POKéMON\n"
	.string "phía trước kém nổi bật.$"

gText_StoleAttentionAwayFromMon::
	.string "Nó cướp mất sự chú ý vốn dành cho\n"
	.string "{STR_VAR_2}.$"

gText_CheapenedMonsAppeal2::
	.string "Nó làm màn biểu diễn của\n"
	.string "{STR_VAR_2} kém nổi bật.$"

gText_SeverelyCheapenedOtherAppeals::
	.string "Nó làm các màn biểu diễn khác kém nổi\n"
	.string "bật đi rất nhiều.$"

gText_AnticipationSwelledForMonsAppealNext::
	.string "Mọi người càng háo hức chờ màn biểu\n"
	.string "diễn tiếp theo của {STR_VAR_1}.$"

gText_CheapenedAppealOfThoseAhead2::
	.string "Nó làm màn biểu diễn của các POKéMON\n"
	.string "phía trước kém nổi bật.$"

gText_CheapenedJudgesFavoriteAppeal::
	.string "Nó làm màn biểu diễn yêu thích của\n"
	.string "GIÁM KHẢO kém nổi bật.$"

gText_AppealsOfOthersCheapenedByHalf::
	.string "Sức hút của các màn biểu diễn khác bị\n"
	.string "giảm một nửa.$"

gText_StoodOutToMakeUpForBeingJammed::
	.string "Nó trở nên nổi bật để bù lại việc bị phá\n"
	.string "rối.$"

gText_CantParticipateInAppealsAnyMore::
	.string "Nó không thể tiếp tục tham gia biểu\n"
	.string "diễn.$"

gText_TouchedJudgeForFantasticAppeal::
	.string "Màn biểu diễn tuyệt vời của nó đã chạm\n"
	.string "đến GIÁM KHẢO.$"

gText_AnticipationRoseForUpcomingAppeals::
	.string "Sự mong đợi dành cho các màn biểu diễn\n"
	.string "sắp tới tăng lên.$"

gText_StoodOutAsMuchAsSpecialAppeals::
	.string "Nó nổi bật ngang với những màn biểu\n"
	.string "diễn đặc biệt.$"

gText_StoodOutAsMuchAsMon::
	.string "Nó nổi bật ngang với {STR_VAR_1}.$"

gText_JammedAppealsMadeEvenLessNoticeable::
	.string "Những màn biểu diễn bị phá rối càng khó\n"
	.string "được chú ý hơn.$"

gText_EveryonesAppealsMadeSame::
	.string "Màn biểu diễn của tất cả trở nên giống\n"
	.string "nhau.$"

@ Appeal result texts

gText_BecameMoreConsciousOfOtherMons::
	.string "Nó để tâm hơn đến những POKéMON khác.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantMakeAnAppealAfterThis::
	.string "{STR_VAR_1} sẽ không thể biểu\n"
	.string "diễn sau lượt này.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SettledDownJustLittleBit::
	.string "Nó chỉ bình tĩnh lại đôi chút.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameObliviousToOtherMons::
	.string "Nó hoàn toàn không còn để tâm đến\n"
	.string "những POKéMON khác.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameLessAwareOfOtherMons::
	.string "Nó ít để tâm đến những POKéMON khác\n"
	.string "hơn.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoppedCaringAboutOtherMons::
	.string "Nó hầu như không còn quan tâm đến\n"
	.string "những POKéMON khác.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherMons::
	.string "Nó cố làm những POKéMON khác giật mình.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToDazzleOthers::
	.string "Nó cố làm những đối thủ khác choáng\n"
	.string "ngợp.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAwayFromMon::
	.string "GIÁM KHẢO tránh nhìn {STR_VAR_1}.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToUnnerveNextMon::
	.string "Nó cố làm POKéMON tiếp theo căng thẳng.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameNervous::
	.string "{STR_VAR_1} trở nên căng thẳng.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealTriedToUnnerveWaitingMons::
	.string "Màn biểu diễn đã cố làm những POKéMON\n"
	.string "đang chờ căng thẳng.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TauntedMonsDoingWell::
	.string "Nó khiêu khích những POKéMON đang thể\n"
	.string "hiện tốt.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonRegainedItsForm::
	.string "{STR_VAR_1} đã lấy lại phong độ.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToJamMonDoingWell::
	.string "Nó cố phá rối những POKéMON đang thể\n"
	.string "hiện tốt.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StandoutMonHustledEvenMore::
	.string "Vốn đã nổi bật, {STR_VAR_1} càng\n"
	.string "nỗ lực hơn nữa.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_LargelyUnnoticedMonWorkedHard::
	.string "Dù hầu như không được chú ý,\n"
	.string "{STR_VAR_1} vẫn nỗ lực hết mình.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsMonBefore::
	.string "Nó nỗ lực ngang với POKéMON biểu diễn\n"
	.string "trước mình.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell::
	.string "Màn biểu diễn của {STR_VAR_1}\n"
	.string "không suôn sẻ.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsPrecedingMon::
	.string "Nó nỗ lực ngang với POKéMON ngay\n"
	.string "trước đó.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell2::
	.string "Màn biểu diễn của {STR_VAR_1}\n"
	.string "không suôn sẻ.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell3::
	.string "Màn biểu diễn của {STR_VAR_1}\n"
	.string "không suôn sẻ.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell::
	.string "Màn biểu diễn của {STR_VAR_1} có\n"
	.string "phần suôn sẻ.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell::
	.string "Màn biểu diễn của {STR_VAR_1}\n"
	.string "diễn ra khá tốt.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently::
	.string "Màn biểu diễn của {STR_VAR_1}\n"
	.string "diễn ra xuất sắc.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWasDud::
	.string "Màn trình diễn của {STR_VAR_1}\n"
	.string "thất bại thảm hại.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotWorkVeryWell::
	.string "Màn trình diễn của {STR_VAR_1}\n"
	.string "không được suôn sẻ lắm.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell2::
	.string "Màn trình diễn của {STR_VAR_1}\n"
	.string "cũng khá ổn.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell2::
	.string "Màn trình diễn của {STR_VAR_1}\n"
	.string "khá tốt.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentVeryWell::
	.string "Màn trình diễn của {STR_VAR_1}\n"
	.string "rất tốt.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently2::
	.string "Màn trình diễn của {STR_VAR_1}\n"
	.string "thật xuất sắc.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SameTypeAsOneBeforeGood::
	.string "Nó cùng loại với POKéMON trước, tốt\n"
	.string "lắm!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_NotSameTypeAsOneBeforeGood::
	.string "Nó không cùng loại với phần trước, tốt\n"
	.string "lắm!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoodOutMuchMoreThanMonBefore::
	.string "Nó nổi bật hơn hẳn POKéMON trước.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_DidntDoAsWellAsMonBefore::
	.string "Nó thể hiện không tốt bằng POKéMON\n"
	.string "trước.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsConditionRoseAboveUsual::
	.string "Phong độ của {STR_VAR_1} đã\n"
	.string "vượt mức bình thường.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsHotStatusMadeGreatAppeal::
	.string "Trạng thái sung sức của\n"
	.string "{STR_VAR_1} đã tạo nên màn trình\l"
	.string "diễn tuyệt vời!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedUpInLineForNextAppeal::
	.string "Nó được xếp lên trước cho lượt trình\n"
	.string "diễn tiếp theo.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedBackInLineForNextAppeal::
	.string "Nó bị lùi lại một vị trí cho lượt trình\n"
	.string "diễn tiếp theo.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ScrambledUpOrderForNextTurn::
	.string "Nó làm đảo lộn thứ tự của lượt tiếp\n"
	.string "theo.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAtMonExpectantly::
	.string "GIÁM KHẢO nhìn {STR_VAR_1} đầy kỳ\n"
	.string "vọng.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverWell::
	.string "Chuỗi trình diễn đã thành công.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverVeryWell::
	.string "Chuỗi trình diễn đã rất thành công.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverExcellently::
	.string "Chuỗi trình diễn đã thành công xuất\n"
	.string "sắc.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonManagedToAvertGaze::
	.string "{STR_VAR_1} đã kịp ngoảnh mặt đi.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonManagedToAvoidSeeingIt::
	.string "{STR_VAR_1} đã tránh nhìn vào\n"
	.string "đó.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonIsntFazedByThatSortOfThing::
	.string "{STR_VAR_1} không hề nao núng\n"
	.string "trước chuyện đó.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameALittleDistracted::
	.string "{STR_VAR_1} hơi mất tập trung.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherPokemon::
	.string "Nó cố làm các POKéMON khác giật mình.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonLookedDownOutOfDistraction::
	.string "{STR_VAR_1} mất tập trung nên\n"
	.string "cúi xuống.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonTurnedBackOutOfDistraction::
	.string "{STR_VAR_1} mất tập trung nên\n"
	.string "quay lưng lại.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCouldntHelpUtteringCry::
	.string "{STR_VAR_1} không kìm được\n"
	.string "tiếng kêu.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCouldntHelpLeapingUp::
	.string "{STR_VAR_1} không kìm được mà\n"
	.string "nhảy dựng lên.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonTrippedOutOfDistraction::
	.string "{STR_VAR_1} mất tập trung nên\n"
	.string "vấp ngã.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonWasTooNervousToMove::
	.string "{STR_VAR_1} căng thẳng đến mức\n"
	.string "không thể cử động.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItMessedUp2::
	.string "Nhưng nó đã làm hỏng.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItFailedToMakeTargetNervous::
	.string "Nhưng nó không làm mục tiêu căng thẳng\n"
	.string "được.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItFailedToMakeAnyoneNervous::
	.string "Nhưng nó chẳng làm ai căng thẳng được.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItWasIgnored::
	.string "Nhưng nó bị phớt lờ...{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_CouldntImproveItsCondition::
	.string "Nhưng nó không thể cải thiện phong\n"
	.string "độ...{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BadConditionResultedInWeakAppeal::
	.string "Phong độ kém khiến màn trình diễn trở\n"
	.string "nên yếu ớt.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonWasUnaffected::
	.string "{STR_VAR_1} không bị ảnh hưởng.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_RepeatedAppeal::
	.string "{STR_VAR_1} khiến khán giả thất\n"
	.string "vọng vì lặp lại màn trình diễn.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXWentOverGreat::
	.string "{STR_VAR_3} của\n"
	.string "{STR_VAR_1} được hưởng ứng\l"
	.string "nhiệt liệt.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXDidntGoOverWell::
	.string "{STR_VAR_3} của\n"
	.string "{STR_VAR_1} không được đón\l"
	.string "nhận tại đây...{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXGotTheCrowdGoing::
	.string "{STR_VAR_3} của\n"
	.string "{STR_VAR_1} khiến đám đông phấn\l"
	.string "khích.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantAppealNextTurn::
	.string "{STR_VAR_1} không thể trình diễn\n"
	.string "ở lượt tiếp theo...{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AttractedCrowdsAttention::
	.string "Nó thu hút sự chú ý của đám đông.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_CrowdContinuesToWatchMon::
	.string "Đám đông vẫn tiếp tục dõi theo\n"
	.string "{STR_VAR_3}.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsMoveIsIgnored::
	.string "{STR_VAR_2} của\n"
	.string "{STR_VAR_1} bị phớt lờ.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_Contest_Shyness::
	.string "sự rụt rè$"

gText_Contest_Anxiety::
	.string "sự lo âu$"

gText_Contest_Laziness::
	.string "sự lười biếng$"

gText_Contest_Hesitancy::
	.string "sự do dự$"

gText_Contest_Fear::
	.string "nỗi sợ hãi$"

gText_Contest_Coolness::
	.string "vẻ ngầu$"

gText_Contest_Beauty::
	.string "vẻ đẹp$"

gText_Contest_Cuteness::
	.string "vẻ đáng yêu$"

gText_Contest_Smartness::
	.string "sự thông minh$"

gText_Contest_Toughness::
	.string "sự cứng cỏi$"

@ Unused
gText_Tension::
	.string "TENSION$"

gText_CoolMove::
	.string "Chiêu COOL$"

gText_BeautyMove::
	.string "Chiêu BEAUTY$"

gText_CuteMove::
	.string "Chiêu CUTE$"

gText_SmartMove::
	.string "Chiêu SMART$"

gText_ToughMove::
	.string "Chiêu TOUGH$"

gText_3QuestionMarks::
	.string "???$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global gText_HighlyAppealingMove
	.global gText_UserMoreEasilyStartled
	.global gText_GreatAppealButNoMoreToEnd
	.global gText_UsedRepeatedlyWithoutBoringJudge
	.global gText_AvoidStartledByOthersOnce
	.global gText_AvoidStartledByOthers
	.global gText_AvoidStartledByOthersLittle
	.global gText_UserLessLikelyStartled
	.global gText_SlightlyStartleFrontMon
	.global gText_SlightlyStartleAppealed
	.global gText_StartleAppealedBeforeUser
	.global gText_StartleAllAppealed
	.global gText_BadlyStartleFrontMon
	.global gText_BadlyStartleAppealed
	.global gText_StartleAppealedBeforeUser2
	.global gText_StartleAllAppealed2
	.global gText_ShiftJudgesAttentionFromOthers
	.global gText_StartleMonHasJudgesAttention
	.global gText_JamOthersMissesTurn
	.global gText_StartleMonsMadeSameTypeAppeal
	.global gText_BadlyStartleCoolAppeals
	.global gText_BadlyStartleBeautyAppeals
	.global gText_BadlyStartleCuteAppeals
	.global gText_BadlyStartleSmartAppeals
	.global gText_BadlyStartleToughAppeals
	.global gText_MakeMonAfterUserNervous
	.global gText_MakeAllMonsAfterUserNervous
	.global gText_WorsenConditionOfThoseMadeAppeals
	.global gText_BadlyStartleMonsGoodCondition
	.global gText_AppealGreatIfPerformedFirst
	.global gText_AppealGreatIfPerformedLast
	.global gText_AppealAsGoodAsThoseBeforeIt
	.global gText_AppealAsGoodAsOneBeforeIt
	.global gText_AppealBetterLaterItsPerformed
	.global gText_AppealVariesDependingOnTiming
	.global gText_WorksWellIfSameTypeAsBefore
	.global gText_WorksWellIfDifferentTypeAsBefore
	.global gText_AffectedByAppealInFront
	.global gText_UpsConditionHelpsPreventNervousness
	.global gText_AppealWorksWellIfConditionGood
	.global gText_NextAppealMadeEarlier
	.global gText_NextAppealMadeLater
	.global gText_TurnOrderMoreEasilyScrambled
	.global gText_ScrambleOrderOfNextAppeals
	.global gText_AppealExcitesAudienceInAnyContest
	.global gText_BadlyStartlesMonsGoodAppeals
	.global gText_AppealBestMoreCrowdExcited
	.global gText_TemporarilyStopCrowdExcited
	.global gText_AppealNumWhichMoveWillBePlayed
	.global gText_AppealNumButItCantParticipate
	.global gText_MonAppealedWithMove
	.global gText_MonWasWatchingOthers
	.global gText_AllOutOfAppealTime
	.global gText_ButAppealWasJammed
	.global gText_FollowedAnotherMonsLead
	.global gText_ButItMessedUp
	.global gText_WentBetterThanUsual
	.global gText_JudgeLookedAwayForSomeReason
	.global gText_WorkedHardToBuildOnPastMistakes
	.global gText_CantMakeAnyMoreMoves
	.global gText_WorkedFrighteninglyWell
	.global gText_WorkedHardAsStandoutMon
	.global gText_JudgedLookedOnExpectantly
	.global gText_WorkedRatherWell
	.global gText_WorkedLittleBetterThanUsual
	.global gText_MonFailedToStandOutAtAll
	.global gText_MonDidntStandOutVeryMuch
	.global gText_MonCaughtALittleAttention
	.global gText_MonAttractedALotOfAttention
	.global gText_MonCommandedTotalAttention
	.global gText_MonHasntMadeItsAppeal
	.global gText_AnticipationSwelledForMonsAppealNext2
	.global gText_JudgesViewsOnMonHeldFirm
	.global gText_MonsXChangedPerceptions
	.global gText_MonsAppealEffectWoreOff
	.global gText_SpecialAppealsEffectWoreOff
	.global gText_EveryonesAppealsMadeToLookSame
	.global gText_CheapenedMonsAppeal
	.global gText_CheapenedAppealOfThoseAhead
	.global gText_StoleAttentionAwayFromMon
	.global gText_CheapenedMonsAppeal2
	.global gText_SeverelyCheapenedOtherAppeals
	.global gText_AnticipationSwelledForMonsAppealNext
	.global gText_CheapenedAppealOfThoseAhead2
	.global gText_CheapenedJudgesFavoriteAppeal
	.global gText_AppealsOfOthersCheapenedByHalf
	.global gText_StoodOutToMakeUpForBeingJammed
	.global gText_CantParticipateInAppealsAnyMore
	.global gText_TouchedJudgeForFantasticAppeal
	.global gText_AnticipationRoseForUpcomingAppeals
	.global gText_StoodOutAsMuchAsSpecialAppeals
	.global gText_StoodOutAsMuchAsMon
	.global gText_JammedAppealsMadeEvenLessNoticeable
	.global gText_EveryonesAppealsMadeSame
	.global gText_BecameMoreConsciousOfOtherMons
	.global gText_MonCantMakeAnAppealAfterThis
	.global gText_SettledDownJustLittleBit
	.global gText_BecameObliviousToOtherMons
	.global gText_BecameLessAwareOfOtherMons
	.global gText_StoppedCaringAboutOtherMons
	.global gText_TriedToStartleOtherMons
	.global gText_TriedToDazzleOthers
	.global gText_JudgeLookedAwayFromMon
	.global gText_TriedToUnnerveNextMon
	.global gText_MonBecameNervous
	.global gText_AppealTriedToUnnerveWaitingMons
	.global gText_TauntedMonsDoingWell
	.global gText_MonRegainedItsForm
	.global gText_TriedToJamMonDoingWell
	.global gText_StandoutMonHustledEvenMore
	.global gText_LargelyUnnoticedMonWorkedHard
	.global gText_WorkedAsMuchAsMonBefore
	.global gText_MonsAppealDidNotGoWell
	.global gText_WorkedAsMuchAsPrecedingMon
	.global gText_MonsAppealDidNotGoWell2
	.global gText_MonsAppealDidNotGoWell3
	.global gText_MonsAppealWentSlightlyWell
	.global gText_MonsAppealWentPrettyWell
	.global gText_MonsAppealWentExcellently
	.global gText_MonsAppealWasDud
	.global gText_MonsAppealDidNotWorkVeryWell
	.global gText_MonsAppealWentSlightlyWell2
	.global gText_MonsAppealWentPrettyWell2
	.global gText_MonsAppealWentVeryWell
	.global gText_MonsAppealWentExcellently2
	.global gText_SameTypeAsOneBeforeGood
	.global gText_NotSameTypeAsOneBeforeGood
	.global gText_StoodOutMuchMoreThanMonBefore
	.global gText_DidntDoAsWellAsMonBefore
	.global gText_MonsConditionRoseAboveUsual
	.global gText_MonsHotStatusMadeGreatAppeal
	.global gText_MovedUpInLineForNextAppeal
	.global gText_MovedBackInLineForNextAppeal
	.global gText_ScrambledUpOrderForNextTurn
	.global gText_JudgeLookedAtMonExpectantly
	.global gText_AppealComboWentOverWell
	.global gText_AppealComboWentOverVeryWell
	.global gText_AppealComboWentOverExcellently
	.global gText_MonManagedToAvertGaze
	.global gText_MonManagedToAvoidSeeingIt
	.global gText_MonIsntFazedByThatSortOfThing
	.global gText_MonBecameALittleDistracted
	.global gText_TriedToStartleOtherPokemon
	.global gText_MonLookedDownOutOfDistraction
	.global gText_MonTurnedBackOutOfDistraction
	.global gText_MonCouldntHelpUtteringCry
	.global gText_MonCouldntHelpLeapingUp
	.global gText_MonTrippedOutOfDistraction
	.global gText_MonWasTooNervousToMove
	.global gText_ButItMessedUp2
	.global gText_ButItFailedToMakeTargetNervous
	.global gText_ButItFailedToMakeAnyoneNervous
	.global gText_ButItWasIgnored
	.global gText_CouldntImproveItsCondition
	.global gText_BadConditionResultedInWeakAppeal
	.global gText_MonWasUnaffected
	.global gText_RepeatedAppeal
	.global gText_MonsXWentOverGreat
	.global gText_MonsXDidntGoOverWell
	.global gText_MonsXGotTheCrowdGoing
	.global gText_MonCantAppealNextTurn
	.global gText_AttractedCrowdsAttention
	.global gText_CrowdContinuesToWatchMon
	.global gText_MonsMoveIsIgnored
	.global gText_Contest_Shyness
	.global gText_Contest_Anxiety
	.global gText_Contest_Laziness
	.global gText_Contest_Hesitancy
	.global gText_Contest_Fear
	.global gText_Contest_Coolness
	.global gText_Contest_Beauty
	.global gText_Contest_Cuteness
	.global gText_Contest_Smartness
	.global gText_Contest_Toughness
	.global gText_CoolMove
	.global gText_BeautyMove
	.global gText_CuteMove
	.global gText_SmartMove
	.global gText_ToughMove
@ END GENERATED LOCALIZATION EXPORTS
