@ With the exception of Link standby, none of the below texts are used

gTest_MissedTurn::
	.string "Missed turn$"

gText_LinkStandby4::
	.string "Link standby!$"

gText_WinnerIsPlayersMonCongrats::
	.string "Người chiến thắng là {STR_VAR_2}\n"
	.string "của {STR_VAR_1}! Xin chúc mừng!$"

gText_WinnerIsPlayersMon::
	.string "Người chiến thắng là {STR_VAR_2}\n"
	.string "của {STR_VAR_1}!{PAUSE_UNTIL_PRESS}$"

gText_PrimaryJudgingNumX::
	.string "Primary judging: No. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SecondaryJudgingNumX::
	.string "Secondary judging: No. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX::
	.string "Set event: No. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MoveUsedMostOften::
	.string "Chiêu được dùng nhiều nhất:\n"
	.string "{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MostImpressiveMon::
	.string "POKéMON gây ấn tượng nhất:\n"
	.string "{STR_VAR_1}'s {STR_VAR_2}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX2::
	.string "Set event: No. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_LinkTVProgramWillNotBeMadeTrainerLost::
	.string "Không có chương trình link TV\n"
	.string "vì HLV đã thua.{PAUSE_UNTIL_PRESS}$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global gText_WinnerIsPlayersMonCongrats
	.global gText_WinnerIsPlayersMon
	.global gText_MoveUsedMostOften
	.global gText_MostImpressiveMon
	.global gText_LinkTVProgramWillNotBeMadeTrainerLost
@ END GENERATED LOCALIZATION EXPORTS
