gContestHallPaintingCaption::
	.string "{STR_VAR_1} {STR_VAR_2}:\n"
	.string "{STR_VAR_3}$"

@ Unused
gContestPaintingContest::
	.string "CONTEST$"

gContestRankNormal::
	.string "NORMAL RANK$"

gContestRankSuper::
	.string "SUPER RANK$"

gContestRankHyper::
	.string "HYPER RANK$"

gContestRankMaster::
	.string "MASTER RANK$"

gContestLink::
	.string "LINK$"

gContestCoolness::
	.string "COOLNESS$"

gContestBeauty::
	.string "BEAUTY$"

gContestCuteness::
	.string "CUTENESS$"

gContestSmartness::
	.string "SMARTNESS$"

gContestToughness::
	.string "TOUGHNESS$"

gContestPaintingCool1::
	.string "Cực ngầu không ngừng nghỉ:\n"
	.string "{STR_VAR_1} vô giá$"

gContestPaintingCool2::
	.string "Nhìn đây! POKéMON điển trai\n"
	.string "{STR_VAR_1}$"

gContestPaintingCool3::
	.string "Kỳ diệu, tuyệt vời và vô cùng xuất sắc:\n"
	.string "{STR_VAR_1}$"

gContestPaintingBeauty1::
	.string "Nữ thần Venus cuối cùng của thế kỷ này:\n"
	.string "{STR_VAR_1} xinh đẹp$"

gContestPaintingBeauty2::
	.string "Nụ cười rạng rỡ, lấp lánh của\n"
	.string "{STR_VAR_1}$"

gContestPaintingBeauty3::
	.string "Siêu thần tượng của POKéMON CENTER:\n"
	.string "{STR_VAR_1} không ai sánh bằng$"

gContestPaintingCute1::
	.string "{STR_VAR_1} đáng yêu và ngọt\n"
	.string "ngào$"

gContestPaintingCute2::
	.string "Bức chân dung chiến thắng của\n"
	.string "{STR_VAR_1} xinh xắn$"

gContestPaintingCute3::
	.string "Nháy mắt nào! POKéMON dễ thương\n"
	.string "{STR_VAR_1}$"

gContestPaintingSmart1::
	.string "Bậc thầy trí tuệ: POKéMON thông thái\n"
	.string "{STR_VAR_1}$"

gContestPaintingSmart2::
	.string "{STR_VAR_1}: kẻ được chọn giữa\n"
	.string "tất cả POKéMON$"

gContestPaintingSmart3::
	.string "Khoảnh khắc thanh lịch của\n"
	.string "{STR_VAR_1} xuất chúng$"

gContestPaintingTough1::
	.string "Tay đua cơ bắp cuồn cuộn\n"
	.string "{STR_VAR_1}$"

gContestPaintingTough2::
	.string "{STR_VAR_1} mạnh, mạnh hơn và\n"
	.string "mạnh nhất$"

gContestPaintingTough3::
	.string "POKéMON siêu cứng cỏi đầy uy lực\n"
	.string "{STR_VAR_1}$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global gContestHallPaintingCaption
	.global gContestPaintingCool1
	.global gContestPaintingCool2
	.global gContestPaintingCool3
	.global gContestPaintingBeauty1
	.global gContestPaintingBeauty2
	.global gContestPaintingBeauty3
	.global gContestPaintingCute1
	.global gContestPaintingCute2
	.global gContestPaintingCute3
	.global gContestPaintingSmart1
	.global gContestPaintingSmart2
	.global gContestPaintingSmart3
	.global gContestPaintingTough1
	.global gContestPaintingTough2
	.global gContestPaintingTough3
@ END GENERATED LOCALIZATION EXPORTS
