EventTicket_Text_OldSeaMapTooFar:
	.string "Có chuyện gì vậy, nhóc?\p"
	.string "Gì cơ, chính cậu là người có tấm bản đồ\n"
	.string "cũ rách nát đó sao?\p"
	.string "Đưa ta xem nào. ... ... ... ... ... ...\p"
	.string "Ôi, nơi này xa lắm. E rằng ta không giúp\n"
	.string "được cậu...$"

EventTicket_Text_BrineyHoldOnASecond:
	.string "BRINEY: Khoan đã!\p"
	.string "Sao anh lại từ chối người mà tôi mang\n"
	.string "ơn rất nhiều chứ?$"

EventTicket_Text_BrineyLetsSail:
	.string "{PLAYER}{KUN}, tôi thật sự xin lỗi.\p"
	.string "Cháu đã tìm đến nhờ tôi giúp, vậy mà\n"
	.string "chúng tôi suýt từ chối cháu.\p"
	.string "Để tôi sửa sai nhé.\p"
	.string "Tất nhiên, chúng ta sẽ khởi hành ngay!\p"
	.string "Hãy cùng tìm hòn đảo trên OLD SEA MAP\n"
	.string "này!$"

EventTicket_Text_OddTicketGetOnBoard:
	.string "Có phải cậu mang tấm vé kỳ lạ đó tới\n"
	.string "không?\p"
	.string "Nơi cậu muốn đến là một hòn đảo xa thật\n"
	.string "xa.\p"
	.string "Không ai biết điều gì đang chờ ở đó...\p"
	.string "Chỉ nghĩ đến thôi, máu của một thủy thủ\n"
	.string "như ta đã sôi lên rồi!\p"
	.string "Lên tàu đi, nhóc!$"

FarawayIsland_Entrance_Text_SailorReturn:
	.string "CAPT. BRINEY đúng là hay thay đổi đến\n"
	.string "phát bực...\p"
	.string "Cậu có muốn quay lại LILYCOVE không?$"

BirthIsland_Harbor_Text_SailorReturn:
	.string "Hòn đảo này có hình thù kỳ lạ thật nhỉ?\n"
	.string "Cậu có muốn quay lại LILYCOVE không?$"

EventTicket_Text_OddTicketsWhereTo:
	.string "Có phải cậu mang những tấm vé kỳ lạ đó\n"
	.string "tới không?\p"
	.string "... ... ... Hừm.\p"
	.string "Những tấm vé này sẽ đưa cậu đến các\n"
	.string "hòn đảo xa thật xa.\p"
	.string "Không ai biết điều gì đang chờ ở đó,\n"
	.string "hay chuyện gì có thể xảy ra.\p"
	.string "Chỉ nghĩ đến thôi, máu của một thủy thủ\n"
	.string "như ta đã sôi lên rồi!\p"
	.string "Lên tàu đi, nhóc! Ta sẽ đến đâu trước?$"

NavelRock_Harbor_Text_SailorReturn:
	.string "Cậu... Cậu có nghe thấy không? Tiếng gầm\n"
	.string "trầm thấp từ sâu bên trong ấy.\p"
	.string "Cậu chắc nơi này an toàn chứ? Hay\n"
	.string "chúng ta nên rời đi?$"

FarawayIsland_Entrance_Text_Sign:
	.string "Chữ viết đang phai dần, như thể đã\n"
	.string "được viết từ rất lâu...\p"
	.string "“...ber, ngày 6 Nếu có con người\n"
	.string "nào...đặt chân đến đây... lần nữa...ãy để\l"
	.string "đó là một người nhân hậu... ...ới hy vọng\l"
	.string "ấy, ta rời...”$"

FarawayIsland_Interior_Text_Mew:
	.string "Myuu...$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global EventTicket_Text_OldSeaMapTooFar
	.global EventTicket_Text_BrineyHoldOnASecond
	.global EventTicket_Text_BrineyLetsSail
	.global EventTicket_Text_OddTicketGetOnBoard
	.global FarawayIsland_Entrance_Text_SailorReturn
	.global BirthIsland_Harbor_Text_SailorReturn
	.global EventTicket_Text_OddTicketsWhereTo
	.global NavelRock_Harbor_Text_SailorReturn
	.global FarawayIsland_Entrance_Text_Sign
	.global FarawayIsland_Interior_Text_Mew
@ END GENERATED LOCALIZATION EXPORTS
