EventTicket_Text_ShowOldSeaMap:
	.string "Chuyến phà đến SLATEPORT thì...\p"
	.string "Xin lỗi, gì cơ? Chúng ta có thể đi\n"
	.string "thuyền đến nơi này trên bản đồ sao?\p"
	.string "Tôi biết một người có thể giúp bạn tốt\n"
	.string "hơn. Xin hãy chờ.$"

EventTicket_Text_ThatPass:
	.string "Chuyến phà đến SLATEPORT thì...\p"
	.string "Ồ? Tấm PASS đó...$"

EventTicket_Text_ShowEonTicket:
	.string "Này, cậu bạn, có phải cậu mang tấm PASS\n"
	.string "kỳ quặc đó đến không?\p"
	.string "Nói cho cậu biết, cậu đang định tới một\n"
	.string "hòn đảo bé tí tận phương nam xa xôi.\p"
	.string "Chẳng ai biết khi đến đó ta sẽ gặp gì\n"
	.string "đâu. Nghĩ thôi đã khiến lão thủy thủ\l"
	.string "này rùng mình rồi!\p"
	.string "Tất cả lên tàu!$"

EventTicket_Text_SouthernIslandSailBack:
	.string "Này, cậu bạn, hòn đảo đáng quên này\n"
	.string "chẳng có gì để xem hay làm cả.\p"
	.string "Ta căng buồm quay lại LILYCOVE nhé?$"

EventTicket_Text_SailHome:
	.string "Ừ, được thôi! Vậy ta sẽ căng buồm về\n"
	.string "nhà!$"

EventTicket_Text_AsYouLike:
	.string "Ừ, được thôi, tùy cậu vậy.$"

SouthernIsland_Interior_Text_Sign:
	.string "“Mọi giấc mơ chỉ là một hiện thực khác.\n"
	.string "Đừng bao giờ quên...”$"

SouthernIsland_Exterior_Text_Sign:
	.string "“Những ai có ký ức phai mờ luôn tìm\n"
	.string "cách khắc chúng vào tim...”$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global EventTicket_Text_ShowOldSeaMap
	.global EventTicket_Text_ThatPass
	.global EventTicket_Text_ShowEonTicket
	.global EventTicket_Text_SouthernIslandSailBack
	.global EventTicket_Text_SailHome
	.global EventTicket_Text_AsYouLike
	.global SouthernIsland_Interior_Text_Sign
	.global SouthernIsland_Exterior_Text_Sign
@ END GENERATED LOCALIZATION EXPORTS
