@ Battle Tower
gText_AnabelWonSilver::
	.string "Thật đáng thất vọng...$"

gText_AnabelDefeatSilver::
	.string "Được rồi, tôi hiểu...$"

gText_AnabelWonGold::
	.string "Tôi vô cùng xin lỗi...$"

gText_AnabelDefeatGold::
	.string "Cảm ơn bạn...$"

@ Battle Dome
gText_TuckerWonSilver::
	.string "Ahahaha! Cậu không thấy xấu hổ sao?\n"
	.string "Mọi người đang nhìn đấy!$"

gText_TuckerDefeatSilver::
	.string "Grr... Cái quái...$"

gText_TuckerWonGold::
	.string "Danh hiệu DOME ACE của ta không chỉ để\n"
	.string "trưng đâu!$"

gText_TuckerDefeatGold::
	.string "Ahahaha! Cậu thật truyền cảm hứng!$"

@ Battle Factory
gText_NolandWonSilver::
	.string "Khá lắm! Vừa học được một bài hay, phải\n"
	.string "không?$"

gText_NolandDefeatSilver::
	.string "Tốt lắm! Cậu biết mình đang làm gì đấy!$"

gText_NolandWonGold::
	.string "Này, này, này! Cậu xong đời nhanh vậy\n"
	.string "sao?$"

gText_NolandDefeatGold::
	.string "Chuyện gì vừa xảy ra thế này?$"

@ Battle Pike
gText_LucyWonSilver::
	.string "Hừm...$"

gText_LucyDefeatSilver::
	.string "Ực...$"

gText_LucyWonGold::
	.string "Ha!$"

gText_LucyDefeatGold::
	.string "Chết tiệt!$"

@ Battle Arena
gText_GretaWonSilver::
	.string "Ôi, thôi nào! Cậu phải cố hơn thế chứ!$"

gText_GretaDefeatSilver::
	.string "Không thể nào! Giỏi lắm!$"

gText_GretaWonGold::
	.string "Heheh! Cậu mong đợi gì chứ?$"

gText_GretaDefeatGold::
	.string "Hả? Cậu nghiêm túc đấy sao?!$"

@ Battle Palace
gText_SpenserWonSilver::
	.string "POKéMON của ngươi yếu đuối vì HLV\n"
	.string "như ngươi cũng yếu đuối!$"

gText_SpenserDefeatSilver::
	.string "À... Chuyện này lại khác hẳn...$"

gText_SpenserWonGold::
	.string "Gwahahaha! Hỡi các chiến hữu, chúng ta\n"
	.string "chẳng có gì phải sợ!$"

gText_SpenserDefeatGold::
	.string "Gwah! Hahahaha!$"

@ Battle Pyramid
gText_BrandonWonSilver::
	.string "Này! Có chuyện gì với bạn vậy! Cố gắng\n"
	.string "lên xem nào! Đứng dậy!$"

gText_BrandonDefeatSilver::
	.string "Đúng thế! Bạn làm tốt lắm! Bao công sức\n"
	.string "của bạn đã được đền đáp!$"

gText_BrandonWonGold::
	.string "Này! Đừng bỏ cuộc lúc này! Đứng dậy!\n"
	.string "Đừng đánh mất niềm tin vào bản thân!$"

gText_BrandonDefeatGold::
	.string "Đúng thế! Bạn làm được rồi! Bao nỗ lực\n"
	.string "bền bỉ của bạn đã được đền đáp!$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global gText_AnabelWonSilver
	.global gText_AnabelDefeatSilver
	.global gText_AnabelWonGold
	.global gText_AnabelDefeatGold
	.global gText_TuckerWonSilver
	.global gText_TuckerDefeatSilver
	.global gText_TuckerWonGold
	.global gText_TuckerDefeatGold
	.global gText_NolandWonSilver
	.global gText_NolandDefeatSilver
	.global gText_NolandWonGold
	.global gText_NolandDefeatGold
	.global gText_LucyWonSilver
	.global gText_LucyDefeatSilver
	.global gText_LucyWonGold
	.global gText_LucyDefeatGold
	.global gText_GretaWonSilver
	.global gText_GretaDefeatSilver
	.global gText_GretaWonGold
	.global gText_GretaDefeatGold
	.global gText_SpenserWonSilver
	.global gText_SpenserDefeatSilver
	.global gText_SpenserWonGold
	.global gText_SpenserDefeatGold
	.global gText_BrandonWonSilver
	.global gText_BrandonDefeatSilver
	.global gText_BrandonWonGold
	.global gText_BrandonDefeatGold
@ END GENERATED LOCALIZATION EXPORTS
