LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "Đây là POKéMON LOTTERY CORNER.\p"
	.string "Mọi khách hàng của DEPARTMENT STORE\n"
	.string "đều được rút POKéMON LOTO TICKET.\p"
	.string "Nếu số trên LOTO TICKET trùng với\n"
	.string "ID của bất kỳ POKéMON nào, bạn sẽ\l"
	.string "nhận được một món quà tuyệt vời.\p"
	.string "Bạn muốn rút một POKéMON\n"
	.string "LOTO TICKET không?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "Vui lòng quay lại vào ngày mai.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "Hẹn gặp lại bạn.$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "Hãy chọn một LOTO TICKET.\n"
	.string "…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "Số LOTO TICKET là {STR_VAR_1}.\p"
	.string "Tôi cần kiểm tra xem số này có trùng\n"
	.string "với ID của POKéMON nào không.\l"
	.string "Vui lòng chờ.$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "Xin chúc mừng!\p"
	.string "ID của {STR_VAR_1} trong đội\n"
	.string "trùng với số LOTO TICKET!$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "Xin chúc mừng!\p"
	.string "ID của {STR_VAR_1} trong PC BOX\n"
	.string "trùng với số LOTO TICKET!$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "Rất tiếc.\n"
	.string "Không có số nào trùng khớp.$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "Hai chữ số trùng khớp, bạn giành\n"
	.string "giải ba!\l"
	.string "Bạn đã nhận được {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "Ba chữ số trùng khớp, bạn giành\n"
	.string "giải nhì!\l"
	.string "Bạn đã nhận được {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "Bốn chữ số trùng khớp, bạn giành\n"
	.string "giải nhất!\l"
	.string "Bạn đã nhận được {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "Ôi trời, cả năm chữ số\n"
	.string "đều trùng khớp!\p"
	.string "Bạn đã trúng giải độc đắc!\n"
	.string "Bạn đã nhận được {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "Ồ?\n"
	.string "Có vẻ bạn không còn chỗ cho món này.\p"
	.string "Hãy dọn chỗ trong TÚI ĐỒ rồi báo lại\n"
	.string "cho tôi.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "{PLAYER}?\n"
	.string "Đúng rồi, tôi đang chờ bạn.\p"
	.string "Đây là phần thưởng chúng tôi\n"
	.string "đã giữ cho bạn.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "Hẹn gặp lại bạn.$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket
	.global LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow
	.global LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain
	.global LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket
	.global LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait
	.global LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon
	.global LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon
	.global LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched
	.global LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched
	.global LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched
	.global LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched
	.global LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched
	.global LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis
	.global LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding
	.global LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2
@ END GENERATED LOCALIZATION EXPORTS
