gText_HowMayIServeYou::
	.string "Chào mừng!\p"
	.string "Tôi có thể giúp gì cho bạn?$"

gText_PleaseComeAgain::
	.string "Hẹn gặp lại!$"

gText_PlayerWhatCanIDoForYou::
	.string "{PLAYER}{KUN}, chào mừng!\p"
	.string "Tôi có thể giúp gì cho bạn?$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global gText_HowMayIServeYou
	.global gText_PleaseComeAgain
	.global gText_PlayerWhatCanIDoForYou
@ END GENERATED LOCALIZATION EXPORTS
