MatchCall_WildBattleText1::
	.string "Chào! Xin chào, {PLAYER}{KUN}! Đây là\n"
	.string "{STR_VAR_1}.\p"
	.string "Lúc nãy tôi thấy một con\n"
	.string "{STR_VAR_2}, nhưng không bắt\l"
	.string "được.\p"
	.string "Chỉ thiếu chút nữa thôi! Vậy nhé, hẹn\n"
	.string "gặp lại!$"

MatchCall_WildBattleText2::
	.string "Chào {PLAYER}{KUN}. Tôi là\n"
	.string "{STR_VAR_1}.\p"
	.string "Lúc nãy tôi đã thử bắt một con\n"
	.string "{STR_VAR_2} rất tuyệt.\p"
	.string "Nhưng nó chạy mất. Tôi thất vọng lắm!\p"
	.string "Thôi nhé, tạm biệt!$"

MatchCall_WildBattleText3::
	.string "Chào {PLAYER}! Tôi đây,\n"
	.string "{STR_VAR_1}.\p"
	.string "Tôi vừa thử bắt con {STR_VAR_2}\n"
	.string "này, nhưng nó chạy mất.\p"
	.string "Chỉ thiếu một chút nữa thôi!\p"
	.string "Thế là cả ngày mất vui... Thôi, hẹn gặp\n"
	.string "lại!$"

MatchCall_WildBattleText4::
	.string "Này, {PLAYER}{KUN}. {STR_VAR_1}\n"
	.string "đây.\p"
	.string "Bạn biết POKéMON {STR_VAR_2}\n"
	.string "chứ? Tôi suýt bắt được một con đấy.\p"
	.string "Mới lúc nãy thôi. Tôi cứ tưởng đã tóm\n"
	.string "được nó, nhưng nó lại thoát mất.\p"
	.string "Dù sao, lần sau gặp lại tôi nhất định sẽ\n"
	.string "bắt được.\p"
	.string "Được rồi, hẹn gặp lại nhé.$"

MatchCall_WildBattleText5::
	.string "Chào {PLAYER}{KUN}! Tôi là\n"
	.string "{STR_VAR_1}. Gần đây bạn có bắt\l"
	.string "được POKéMON nào không?\p"
	.string "Lúc nãy tôi suýt tóm được một con,\n"
	.string "nhưng nó lại thoát mất.\p"
	.string "Thôi nhé, giữ gìn sức khỏe!$"

MatchCall_WildBattleText6::
	.string "Này, {PLAYER}{KUN}. {STR_VAR_1}\n"
	.string "đây. Gần đây bạn có bắt được POKéMON\l"
	.string "nào không?\p"
	.string "Hôm nọ tôi suýt tóm được một con.\n"
	.string "Nhưng chẳng hiểu sao nó vẫn thoát\l"
	.string "được.\p"
	.string "Nhớ giữ gìn sức khỏe.$"

MatchCall_WildBattleText7::
	.string "...Ờ, {PLAYER}{KUN} phải không? Tôi\n"
	.string "đây, {STR_VAR_1}.\p"
	.string "Khoan! Khoan đã! Tôi bắt được con\n"
	.string "{STR_VAR_2} này rồi...\p"
	.string "Aaarrrgh! Nó vùng chạy mất rồi! Chỉ\n"
	.string "thiếu đúng một chút nữa thôi!$"

MatchCall_WildBattleText8::
	.string "Ồ, {PLAYER}{KUN}, bạn khỏe chứ? Tôi là\n"
	.string "{STR_VAR_1}.\p"
	.string "Gần đây bạn có bắt POKéMON thuận lợi\n"
	.string "không?\p"
	.string "Lúc nãy tôi đã đến rất gần thành công,\n"
	.string "nhưng mục tiêu lại thoát mất.\p"
	.string "Tôi phải cố gắng hơn nữa! Hẹn gặp lại!$"

MatchCall_WildBattleText9::
	.string "Ồ, chào {PLAYER}{KUN}! Tôi là\n"
	.string "{STR_VAR_1}!\p"
	.string "Sao rồi? Bạn có thu phục thêm POKéMON\n"
	.string "không?\p"
	.string "Còn tôi thì xui xẻo kinh khủng! Con nào\n"
	.string "cũng chạy thoát!\p"
	.string "Hẹn gặp lại!$"

MatchCall_WildBattleText10::
	.string "Ồ, chào {PLAYER}{KUN}... Tôi là\n"
	.string "{STR_VAR_1}.\p"
	.string "Nghe này, tôi chỉ còn cách việc bắt\n"
	.string "được con {STR_VAR_2} này một\l"
	.string "chút xíu...\p"
	.string "Nhưng nó lại lẻn thoát mất...\p"
	.string "Tôi phải cố gắng hơn. Hẹn gặp lại nhé.$"

MatchCall_WildBattleText11::
	.string "À, {PLAYER}{KUN}. Tôi là\n"
	.string "{STR_VAR_1}. Bạn vẫn ổn chứ?\p"
	.string "Lúc nãy tôi thử bắt một con\n"
	.string "{STR_VAR_2} hoang dã, nhưng nó\l"
	.string "đã chạy thoát.\p"
	.string "Tôi cảm thấy mình thất bại quá...$"

MatchCall_WildBattleText12::
	.string "Chào {PLAYER}{KUN}. Tôi đây,\n"
	.string "{STR_VAR_1}. Bạn vẫn đang bắt\l"
	.string "POKéMON chứ?\p"
	.string "Tôi cũng đang cố bắt chúng, nhưng\n"
	.string "chẳng dễ chút nào.\p"
	.string "Con đường của POKéMON thật thâm sâu!$"

MatchCall_WildBattleText13::
	.string "À, chào {PLAYER}{KUN}! Tôi là\n"
	.string "{STR_VAR_1}! Bạn có đang bắt\l"
	.string "POKéMON không?\p"
	.string "Tôi cũng đang cố bắt chúng, nhưng\n"
	.string "chẳng thành công được bao nhiêu.\p"
	.string "Con đường của POKéMON thật thâm sâu!$"

MatchCall_WildBattleText14::
	.string "Ồ, chào {PLAYER}{KUN}, bạn khỏe chứ?\n"
	.string "Tôi là {STR_VAR_1}.\p"
	.string "Vừa rồi tôi đã thử bắt một con\n"
	.string "{STR_VAR_2} dễ thương.\p"
	.string "Nhưng nó chạy mất rồi! Ôi, tôi thất vọng\n"
	.string "lắm đấy!\p"
	.string "Tạm biệt nhé!$"

MatchCall_WildBattleText15::
	.string "Này, {PLAYER}! Tôi là\n"
	.string "{STR_VAR_1}!\p"
	.string "Tôi đang tính thử bắt vài con POKéMON.\p"
	.string "Nhưng tìm mãi chẳng thấy con nào. Thật\n"
	.string "chẳng hiểu nổi!\p"
	.string "Tôi hết cách rồi! Hẹn gặp lại!$"

MatchCall_NegativeBattleText1::
	.string "Chào! Xin chào, {PLAYER}{KUN}! Đây là\n"
	.string "{STR_VAR_1}.\p"
	.string "Tôi đã thử đấu với một HLV khác,\n"
	.string "nhưng lại thua.\p"
	.string "Thất vọng thật đấy. Vậy nhé, hẹn gặp\n"
	.string "lại!$"

MatchCall_NegativeBattleText2::
	.string "Chào {PLAYER}{KUN}. Tôi là\n"
	.string "{STR_VAR_1}.\p"
	.string "Sau trận đấu với bạn, tôi đã thách đấu\n"
	.string "một người khác.\p"
	.string "Tôi suýt thắng, nhưng cuối cùng vẫn\n"
	.string "thua. Đành chịu vậy!$"

MatchCall_NegativeBattleText3::
	.string "Chào {PLAYER}! Tôi đây,\n"
	.string "{STR_VAR_1}.\p"
	.string "Tôi vừa bị đánh bại tan tác trong một\n"
	.string "trận đấu.\p"
	.string "Chắc tôi phải rèn luyện đội hình thêm\n"
	.string "nữa!$"

MatchCall_NegativeBattleText4::
	.string "Này, {PLAYER}. {STR_VAR_1} đây.\p"
	.string "Hôm qua tôi đã đấu thêm một trận, nhưng\n"
	.string "không thể giành chiến thắng.\p"
	.string "Đội hình của tôi cần được rèn luyện\n"
	.string "thêm. Thôi, hẹn gặp lại.$"

MatchCall_NegativeBattleText5::
	.string "Chào {PLAYER}! Tôi là\n"
	.string "{STR_VAR_1}.\p"
	.string "Bạn vẫn ổn chứ?\p"
	.string "Tôi vẫn chiến đấu liên tục, nhưng chẳng\n"
	.string "thắng được bao nhiêu.\p"
	.string "Tôi không sao bắt nhịp được. Thôi nhé,\n"
	.string "giữ gìn sức khỏe!$"

MatchCall_NegativeBattleText6::
	.string "Này, {PLAYER}. {STR_VAR_1} đây.\p"
	.string "Mọi chuyện bên bạn thế nào?\p"
	.string "Gần đây tôi chiến đấu rất chăm chỉ,\n"
	.string "nhưng chẳng thành công được bao\l"
	.string "nhiêu.\p"
	.string "Tôi không sao bắt nhịp được. Nhớ giữ\n"
	.string "gìn sức khỏe.$"

MatchCall_NegativeBattleText7::
	.string "{STR_VAR_1} đây. Gần đây bạn thế\n"
	.string "nào?\p"
	.string "Hôm qua tôi thua một trận, cứ nghĩ mãi\n"
	.string "về chuyện đó.\p"
	.string "Tôi phải nghĩ ra một kế hoạch... Hẹn gặp\n"
	.string "lại.$"

MatchCall_NegativeBattleText8::
	.string "Ồ, {PLAYER}{KUN}, bạn khỏe chứ? Tôi là\n"
	.string "{STR_VAR_1}.\p"
	.string "POKéMON của bạn thế nào rồi? Hôm nọ tôi\n"
	.string "đã thua một trận.\p"
	.string "Tôi phải cố gắng hơn nữa! Hẹn gặp lại!$"

MatchCall_NegativeBattleText9::
	.string "Ồ, chào {PLAYER}{KUN}! Tôi là\n"
	.string "{STR_VAR_1}!\p"
	.string "Nghe này, nghe này, bạn nhất định phải\n"
	.string "nghe chuyện này!\p"
	.string "Lúc nãy tôi đấu POKéMON, nhưng lại thua\n"
	.string "vào giây cuối cùng.\p"
	.string "Ôi, tức chết đi được!$"

MatchCall_NegativeBattleText10::
	.string "Ồ, chào {PLAYER}{KUN}... Tôi là\n"
	.string "{STR_VAR_1}.\p"
	.string "Lúc nãy tôi đã tham gia một trận đấu.\n"
	.string "Nhưng tôi thua rồi.\p"
	.string "Tôi cần rèn luyện POKéMON thêm nữa. Hẹn\n"
	.string "gặp lại nhé.$"

MatchCall_NegativeBattleText11::
	.string "À, {PLAYER}{KUN}. Tôi là\n"
	.string "{STR_VAR_1}. POKéMON của bạn thế\l"
	.string "nào rồi?\p"
	.string "Tôi lại vừa thua thêm một trận nữa.\p"
	.string "Thôi, hẹn gặp lại!$"

MatchCall_NegativeBattleText12::
	.string "Chào {PLAYER}{KUN}. Tôi đây,\n"
	.string "{STR_VAR_1}. Bạn vẫn đang chiến\l"
	.string "đấu hết mình chứ?\p"
	.string "Còn tôi, gần đây vừa thua nên đang rèn\n"
	.string "luyện lại toàn bộ đội hình.\p"
	.string "Hẹn ngày gặp lại.$"

MatchCall_NegativeBattleText13::
	.string "À, chào {PLAYER}{KUN}! Tôi là\n"
	.string "{STR_VAR_1}!\p"
	.string "Mong rằng bạn vẫn khỏe.\p"
	.string "Tôi vừa tham gia một trận đấu cách đây\n"
	.string "không lâu.\p"
	.string "{PLAYER}{KUN}, hãy năng động như tôi\n"
	.string "nhé. Hẹn gặp lại!$"

MatchCall_NegativeBattleText14::
	.string "Ồ, chào {PLAYER}{KUN}. Tôi là\n"
	.string "{STR_VAR_1}.\p"
	.string "Bạn vẫn khỏe chứ?\p"
	.string "Nhưng thỉnh thoảng bạn cũng nên về\n"
	.string "nhà nhé.\p"
	.string "Tạm biệt!$"

MatchCall_PositiveBattleText1::
	.string "Chào! Xin chào, {PLAYER}{KUN}! Đây là\n"
	.string "{STR_VAR_1}!\p"
	.string "Lúc nãy tôi đã đấu với một HLV\n"
	.string "khác. Tôi thắng rồi! Thắng rồi!\p"
	.string "{STR_VAR_2} của tôi đã cố gắng\n"
	.string "hết sức. Tuyệt quá đi!$"

MatchCall_PositiveBattleText2::
	.string "Chào {PLAYER}{KUN}! Tôi là\n"
	.string "{STR_VAR_1}!\p"
	.string "Hôm qua tôi đã đấu một trận và giành\n"
	.string "chiến thắng! Tuyệt vời quá!$"

MatchCall_PositiveBattleText3::
	.string "Chào {PLAYER}! Tôi đây,\n"
	.string "{STR_VAR_1}! Việc chiến đấu của\l"
	.string "bạn thế nào?\p"
	.string "Còn tôi, hôm nọ tôi đã đấu một trận và\n"
	.string "{STR_VAR_2} của tôi tỏa sáng rực\l"
	.string "rỡ!\p"
	.string "Lần tới đấu với bạn, {PLAYER}, người\n"
	.string "thua sẽ không phải là tôi!$"

MatchCall_PositiveBattleText4::
	.string "Này, {PLAYER}. {STR_VAR_1} đây.\p"
	.string "Lúc nãy tôi đã đấu một trận. Tôi thắng,\n"
	.string "nhưng sát nút lắm.\p"
	.string "{STR_VAR_2} của tôi đã thể hiện\n"
	.string "xuất sắc.$"

MatchCall_PositiveBattleText5::
	.string "Chào {PLAYER}{KUN}! Tôi là\n"
	.string "{STR_VAR_1}.\p"
	.string "Bạn vẫn ổn chứ? Có chiến đấu nhiều\n"
	.string "không?\p"
	.string "Tôi vừa thắng một trận đấy!\n"
	.string "{STR_VAR_2} của tôi tuyệt lắm!\p"
	.string "Cứ chờ xem. Lần tới tôi sẽ đánh bại\n"
	.string "bạn! Thôi nhé, giữ gìn sức khỏe!$"

MatchCall_PositiveBattleText6::
	.string "Này, {PLAYER}{KUN}. {STR_VAR_1}\n"
	.string "đây.\p"
	.string "Mọi chuyện bên bạn thế nào?\p"
	.string "Tôi đang thắng liên tiếp. Tôi vừa thắng\n"
	.string "thêm một trận đấy.\p"
	.string "Lần tới chúng ta đấu, tôi nhất định sẽ\n"
	.string "không thua!$"

MatchCall_PositiveBattleText7::
	.string "{PLAYER}{KUN} phải không?\n"
	.string "{STR_VAR_1} đây.\p"
	.string "{STR_VAR_2} của tôi mạnh lắm! Nó\n"
	.string "vừa giúp tôi thắng thêm một trận nữa!\p"
	.string "Tôi nóng lòng muốn tái đấu với bạn.$"

MatchCall_PositiveBattleText8::
	.string "Ồ, {PLAYER}{KUN}, bạn khỏe chứ? Tôi là\n"
	.string "{STR_VAR_1}.\p"
	.string "Mong rằng bạn vẫn khỏe. Tôi muốn báo\n"
	.string "rằng mình vừa thắng một trận.\p"
	.string "{STR_VAR_2} của tôi đã đặc biệt\n"
	.string "nỗ lực để giành chiến thắng.\p"
	.string "Hẹn gặp lại!$"

MatchCall_PositiveBattleText9::
	.string "Ồ, chào {PLAYER}{KUN}! Tôi là\n"
	.string "{STR_VAR_1}!\p"
	.string "POKéMON của bạn vẫn ổn chứ? POKéMON\n"
	.string "của tôi vừa thắng một trận!\p"
	.string "Phải nói là {STR_VAR_2} của tôi\n"
	.string "đã thể hiện ngoạn mục!\p"
	.string "Giá mà tôi có thể cho bạn xem! Hẹn gặp\n"
	.string "lại!$"

MatchCall_PositiveBattleText10::
	.string "Ồ, chào {PLAYER}{KUN}... Tôi là\n"
	.string "{STR_VAR_1}.\p"
	.string "Cuộc sống của bạn dạo này thế nào?\p"
	.string "POKéMON của tôi dường như đang tràn\n"
	.string "đầy năng lượng.\p"
	.string "Tôi vừa cùng chúng thắng một trận. Hẹn\n"
	.string "gặp lại nhé.$"

MatchCall_PositiveBattleText11::
	.string "À, {PLAYER}{KUN}. Tôi là\n"
	.string "{STR_VAR_1}.\p"
	.string "Gần đây bạn có đấu trận nào không? Hôm\n"
	.string "nay tôi lại vừa thắng thêm một trận!\p"
	.string "Tôi đang thắng như chẻ tre! Gahahaha!\n"
	.string "Thôi, hẹn gặp lại!$"

MatchCall_PositiveBattleText12::
	.string "Chào {PLAYER}{KUN}. Tôi đây,\n"
	.string "{STR_VAR_1}.\p"
	.string "Chắc bạn vẫn khỏe chứ? Tôi vẫn tràn\n"
	.string "đầy sức sống!\p"
	.string "Vừa rồi tôi lại thắng thêm một trận. Tôi\n"
	.string "chưa chịu nhường bước cho lớp trẻ các\l"
	.string "bạn đâu!$"

MatchCall_PositiveBattleText13::
	.string "À, chào {PLAYER}{KUN}! Tôi là\n"
	.string "{STR_VAR_1}!\p"
	.string "Mong rằng bạn vẫn khỏe. Bước chân tôi\n"
	.string "vẫn còn nhanh nhẹn lắm!\p"
	.string "Tôi vừa lại thắng thêm một trận. Tôi\n"
	.string "chưa chịu thua lớp trẻ đâu!\p"
	.string "Hẹn gặp lại!$"

MatchCall_PositiveBattleText14::
	.string "Ồ, chào {PLAYER}{KUN}. Tôi là\n"
	.string "{STR_VAR_1}.\p"
	.string "Gần đây tôi đã đấu một trận và\n"
	.string "{STR_VAR_2} của tôi thể hiện\l"
	.string "xuất sắc lắm!\p"
	.string "Giá mà bạn được tận mắt chứng kiến,\n"
	.string "{PLAYER}{KUN}. Tạm biệt!$"

MatchCall_SameRouteBattleRequestText1::
	.string "Chào! Xin chào, {PLAYER}! Đây là\n"
	.string "{STR_VAR_1}.\p"
	.string "Hả? Khoan, bạn đang ở gần\n"
	.string "{STR_VAR_2} sao?\p"
	.string "Ôi, vậy chúng ta phải đấu một trận rồi!\n"
	.string "Tôi sẽ chờ! Hẹn gặp lại!$"

MatchCall_SameRouteBattleRequestText2::
	.string "Chào {PLAYER}! Tôi là\n"
	.string "{STR_VAR_1}.\p"
	.string "Ồ? Hiện giờ bạn tình cờ đang ở gần\n"
	.string "{STR_VAR_2} sao?\p"
	.string "Bạn muốn đấu ngay không? Tôi sẽ chờ!\n"
	.string "Hẹn gặp lại!$"

MatchCall_SameRouteBattleRequestText3::
	.string "Chào {PLAYER}! Tôi đây,\n"
	.string "{STR_VAR_1}.\p"
	.string "Ồ, bạn đang ở gần {STR_VAR_2}\n"
	.string "phải không?\p"
	.string "Bạn muốn đấu với tôi ngay bây giờ chứ?\p"
	.string "Tôi sẽ không thua lần nữa đâu! Tôi sẽ\n"
	.string "chờ! Mau đến nhé!$"

MatchCall_SameRouteBattleRequestText4::
	.string "Này, {PLAYER}{KUN}. {STR_VAR_1}\n"
	.string "đây.\p"
	.string "Hiện giờ bạn đang ở đâu? Hả?\n"
	.string "{STR_VAR_2} sao?\p"
	.string "Muốn đấu ngay không? Tôi sẽ chờ. Hẹn\n"
	.string "gặp lại!$"

MatchCall_SameRouteBattleRequestText5::
	.string "Chào {PLAYER}{KUN}! Tôi là\n"
	.string "{STR_VAR_1}. Bạn vẫn ổn chứ?\p"
	.string "Giờ bạn đang ở đâu cơ?\n"
	.string "{STR_VAR_2} sao?\p"
	.string "Vậy chúng ta tái đấu nhanh một trận\n"
	.string "ngay nhé?\p"
	.string "Tôi sẽ để mắt tìm bạn. Mau đến nhé!$"

MatchCall_SameRouteBattleRequestText6::
	.string "Này, {PLAYER}{KUN}. {STR_VAR_1}\n"
	.string "đây. POKéMON của bạn vẫn khỏe chứ?\p"
	.string "Ồ, vậy sao? Bạn đang ở gần\n"
	.string "{STR_VAR_2} à?\p"
	.string "Vậy thì chúng ta nên tái đấu một trận.\p"
	.string "Tôi chờ được mà. Hẹn gặp lại!$"

MatchCall_SameRouteBattleRequestText7::
	.string "...Ờ, {PLAYER}{KUN} phải không?\n"
	.string "{STR_VAR_1} đây...\p"
	.string "Ồ, bạn tình cờ đang ở gần\n"
	.string "{STR_VAR_2} sao?\p"
	.string "Vậy hãy đấu đi. Ý tôi là ngay bây giờ.\p"
	.string "Tôi sẽ cho bạn thấy POKéMON của mình.\n"
	.string "Tôi sẽ chờ.$"

MatchCall_SameRouteBattleRequestText8::
	.string "Ồ, {PLAYER}{KUN}, bạn khỏe chứ? Tôi là\n"
	.string "{STR_VAR_1}.\p"
	.string "Mong rằng bạn vẫn khỏe. Ồ, bạn đang ở\n"
	.string "gần {STR_VAR_2}.\p"
	.string "Vậy bạn có muốn đấu với tôi một trận\n"
	.string "không?\p"
	.string "Tôi sẽ chờ. Mau đến nhé!$"

MatchCall_SameRouteBattleRequestText9::
	.string "Ồ, chào {PLAYER}{KUN}! Tôi là\n"
	.string "{STR_VAR_1}!\p"
	.string "Bạn vẫn theo kịp chứ? Ồ, bạn đang ở gần\n"
	.string "{STR_VAR_2} sao?\p"
	.string "Vậy thì bạn không nghĩ chúng ta nên\n"
	.string "đấu một trận à?\p"
	.string "Đừng để tôi chờ lâu quá nhé!$"

MatchCall_SameRouteBattleRequestText10::
	.string "Ồ, chào {PLAYER}{KUN}... Tôi là\n"
	.string "{STR_VAR_1}.\p"
	.string "Mọi chuyện bên bạn thế nào? Ồ, bạn đang\n"
	.string "ở gần {STR_VAR_2}.\p"
	.string "Vậy chúng ta nên đấu ngay một trận.\p"
	.string "Tôi đã sẵn sàng chờ rồi. Mau lên!$"

MatchCall_SameRouteBattleRequestText11::
	.string "À, {PLAYER}{KUN}. Tôi là\n"
	.string "{STR_VAR_1}.\p"
	.string "À, vậy hiện giờ bạn đang ở\n"
	.string "{STR_VAR_2} sao?\p"
	.string "Thế thì chúng ta nhất định phải đấu một\n"
	.string "trận, đúng không?\p"
	.string "Tôi sẽ chờ bạn ở đây! Mau đến nhé!$"

MatchCall_SameRouteBattleRequestText12::
	.string "Chào {PLAYER}{KUN}. Tôi đây,\n"
	.string "{STR_VAR_1}. Hiện giờ bạn đang ở\l"
	.string "đâu vậy?\p"
	.string "{STR_VAR_2} sao? Khá gần đây\n"
	.string "đấy!\p"
	.string "Chúng ta đấu ngay một trận nhé?\p"
	.string "Tôi chờ được mà. Hẹn gặp lại!$"

MatchCall_SameRouteBattleRequestText13::
	.string "À, chào {PLAYER}{KUN}! Tôi là\n"
	.string "{STR_VAR_1}!\p"
	.string "Mong rằng bạn vẫn khỏe. Ồ, bạn đang ở\n"
	.string "gần {STR_VAR_2} sao?\p"
	.string "Vì nơi đó không xa lắm, hãy đến gặp tôi\n"
	.string "để đấu một trận.\p"
	.string "Tôi sẽ chờ. Tạm biệt nhé.$"

MatchCall_SameRouteBattleRequestText14::
	.string "Ồ, chào {PLAYER}{KUN}. Tôi là\n"
	.string "{STR_VAR_1}.\p"
	.string "Bạn đang ở đâu cơ?\n"
	.string "...{STR_VAR_2} sao? Gần lắm đấy.\p"
	.string "Bạn không nghĩ chúng ta nên đấu một\n"
	.string "trận à?\p"
	.string "Tôi sẽ tìm bạn! Tạm biệt!$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "Chào! Xin chào, {PLAYER}! Đây là\n"
	.string "{STR_VAR_1}.\p"
	.string "Muốn đấu với tôi một trận không?\p"
	.string "Tôi sẽ chờ bạn ở quanh\n"
	.string "{STR_VAR_2}!$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "Chào {PLAYER}! Tôi là\n"
	.string "{STR_VAR_1}.\p"
	.string "Bạn có muốn đấu lại với tôi không?\p"
	.string "Bạn có thể tìm thấy tôi ở quanh\n"
	.string "{STR_VAR_2}. Tôi sẽ chờ!$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "Chào {PLAYER}! Tôi đây,\n"
	.string "{STR_VAR_1}.\p"
	.string "POKéMON của tôi đã mạnh hơn lần trước\n"
	.string "rất nhiều.\p"
	.string "Tôi muốn dùng POKéMON của bạn để xem\n"
	.string "chúng đã mạnh đến đâu, {PLAYER}.\p"
	.string "Vì vậy, hãy đấu một trận nào!\p"
	.string "Tôi sẽ chờ bạn ở quanh\n"
	.string "{STR_VAR_2}.$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "Này, {PLAYER}{KUN}. {STR_VAR_1}\n"
	.string "đây. Bạn vẫn ổn chứ?\p"
	.string "Gần đây POKéMON của tôi đã trở nên khá\n"
	.string "mạnh.\p"
	.string "Này, bạn có muốn đấu lại với tôi một\n"
	.string "trận không?\p"
	.string "Chúng ta gặp nhau ở quanh\n"
	.string "{STR_VAR_2} nhé?$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "Chào {PLAYER}{KUN}! Tôi là\n"
	.string "{STR_VAR_1}.\p"
	.string "POKéMON của tôi đang trưởng thành khá\n"
	.string "tốt.\p"
	.string "Tôi rất muốn đấu lại với bạn.\p"
	.string "Tôi sẽ để mắt tìm bạn ở quanh\n"
	.string "{STR_VAR_2}. Mau đến nhé!$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "Này, {PLAYER}{KUN}. {STR_VAR_1}\n"
	.string "đây. Mong rằng mọi chuyện bên bạn vẫn\l"
	.string "ổn.\p"
	.string "Tôi đang nghĩ mình muốn đấu lại với\n"
	.string "bạn. Bạn thấy sao?\p"
	.string "Nếu muốn đấu, hãy đến\n"
	.string "{STR_VAR_2}.\p"
	.string "Hẹn gặp lại!$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "...Ờ, {PLAYER}{KUN} phải không?\n"
	.string "{STR_VAR_1} đây... Sao rồi?\l"
	.string "POKéMON của bạn có đang trưởng thành\l"
	.string "không?\p"
	.string "POKéMON của tôi chắc chắn đã mạnh hơn.\n"
	.string "Tôi muốn cho bạn thấy.\p"
	.string "Tôi sẽ ở quanh {STR_VAR_2}. Hãy\n"
	.string "đến gặp tôi để đấu một trận.\p"
	.string "Hẹn gặp lại.$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "Ồ, {PLAYER}{KUN}, bạn khỏe chứ? Tôi là\n"
	.string "{STR_VAR_1}.\p"
	.string "Mong rằng bạn vẫn khỏe. POKéMON của tôi\n"
	.string "đang rất sung sức.\p"
	.string "Nếu có dịp đến khu vực này, xin hãy tái\n"
	.string "đấu với tôi.\p"
	.string "Tôi sẽ ở quanh {STR_VAR_2}. Từ\n"
	.string "giờ đến lúc đó, tạm biệt!$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "Ồ, chào {PLAYER}{KUN}! Tôi là\n"
	.string "{STR_VAR_1}! POKéMON của bạn thế\l"
	.string "nào rồi?\p"
	.string "POKéMON của tôi đang ngày càng tiến bộ.\n"
	.string "Tôi muốn cho bạn thấy, {PLAYER}{KUN}.\p"
	.string "Hiện giờ tôi đang ở quanh\n"
	.string "{STR_VAR_2}, nên nếu bạn ở gần\l"
	.string "thì hãy đấu nhé.\p"
	.string "Mong sớm được gặp bạn!$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "Ồ, chào {PLAYER}{KUN}... Tôi là\n"
	.string "{STR_VAR_1}. Mọi chuyện bên bạn\l"
	.string "thế nào?\p"
	.string "POKéMON của tôi đã mạnh hơn trước rất\n"
	.string "nhiều.\p"
	.string "Tôi rất muốn đấu lại với bạn,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "Tôi sẽ ở quanh {STR_VAR_2}. Nếu\n"
	.string "ở gần thì hãy đến gặp tôi.$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "À, {PLAYER}{KUN}. Tôi là\n"
	.string "{STR_VAR_1}. Hiện giờ bạn đang ở\l"
	.string "đâu vậy?\p"
	.string "POKéMON của tôi tràn đầy sức sống. Có\n"
	.string "vẻ chúng đang mong được gặp POKéMON\l"
	.string "của bạn, {PLAYER}{KUN}.\p"
	.string "Hiện giờ tôi đang ở quanh\n"
	.string "{STR_VAR_2}. Mong rằng bạn sẽ\l"
	.string "đến tìm chúng tôi.$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "Chào {PLAYER}{KUN}. Tôi đây,\n"
	.string "{STR_VAR_1}.\p"
	.string "Tôi phải nói rằng gần đây POKéMON của\n"
	.string "tôi đã trở nên rất cứng cáp.\p"
	.string "Tôi muốn xem chúng chiến đấu với bạn,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "Chúng tôi sẽ ở quanh\n"
	.string "{STR_VAR_2}. Hãy đến gặp bất cứ\l"
	.string "lúc nào!$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "À, chào {PLAYER}{KUN}! Tôi là\n"
	.string "{STR_VAR_1}! POKéMON của bạn vẫn\l"
	.string "khỏe chứ?\p"
	.string "POKéMON của tôi khỏe đến mức trông\n"
	.string "chẳng thể nào thua được!\p"
	.string "Tôi thật sự rất muốn đấu lại với bạn.\p"
	.string "Nếu ở gần {STR_VAR_2}, hãy đến\n"
	.string "gặp chúng tôi.$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "Ồ, chào {PLAYER}{KUN}. Tôi là\n"
	.string "{STR_VAR_1}. Mong rằng bạn vẫn\l"
	.string "khỏe.\p"
	.string "À, phải rồi! POKéMON của tôi đã mạnh hơn\n"
	.string "trước rất nhiều.\p"
	.string "Bạn không nghĩ chúng ta nên đấu một\n"
	.string "trận sao, {PLAYER}{KUN}?\p"
	.string "Chúng tôi sẽ chờ bạn ở quanh\n"
	.string "{STR_VAR_2}.\p"
	.string "Hãy đến gặp bất cứ lúc nào nhé?$"

MatchCall_PersonalizedText1::
	.string "Tôi đây, {STR_VAR_1}, người yêu\n"
	.string "núi non!\p"
	.string "Kể từ lần chúng ta gặp nhau, bạn đã yêu\n"
	.string "quý núi non hơn chưa?\p"
	.string "Tôi hiếm khi thấy bạn trên núi...\p"
	.string "Lần tới chúng ta sẽ gặp nhau ở đâu đó\n"
	.string "quanh {STR_VAR_2}.$"

MatchCall_PersonalizedText2::
	.string "Tôi là {STR_VAR_1}. Xin chào.\p"
	.string "Tôi vừa kể về bạn cho một cô gái mới làm\n"
	.string "HLV.\p"
	.string "Tôi kể với cô ấy về một HLV mạnh mẽ\n"
	.string "luôn chăm chút khi nuôi dưỡng POKéMON.\p"
	.string "Mong rằng bạn sẽ trở thành một HLV\n"
	.string "được mọi người ngưỡng mộ.\p"
	.string "Hy vọng chúng ta sẽ gặp lại!$"

MatchCall_PersonalizedText3::
	.string "Xin chào! Tôi là {STR_VAR_1}.\p"
	.string "Tôi rất thích nơi mình đang ở. Không\n"
	.string "khí dễ chịu với hương thơm ngọt ngào!\p"
	.string "Có lẽ ai đó đã trồng BERRIES và chúng\n"
	.string "đang nở rộ.\p"
	.string "Khi nào đó hẹn gặp lại!$"

MatchCall_PersonalizedText4::
	.string "Xin chào! {STR_VAR_1}, nhà thám\n"
	.string "hiểm với ba mươi năm kinh nghiệm, xin\l"
	.string "được phục vụ!\p"
	.string "Có vẻ bạn đang tràn đầy năng lượng đi\n"
	.string "khắp nơi.\p"
	.string "Bạn có phát hiện di tích mới nào không?\n"
	.string "Nếu có thì hãy kể cho tôi nhé!\p"
	.string "Giờ xin phép, tôi còn phải khám phá di\n"
	.string "tích.$"

MatchCall_PersonalizedText5::
	.string "Tôi là {STR_VAR_1}!\p"
	.string "Biết hôm nay tôi đang làm gì không?\n"
	.string "Ngắm sóng từ bãi biển đấy!\p"
	.string "Chà... Những con sóng lấp lánh quá. Ngắm\n"
	.string "từ đây là biển đẹp nhất. Tôi bắt đầu đói\l"
	.string "rồi, tạm biệt nhé!$"

MatchCall_PersonalizedText6::
	.string "Nhai nhồm nhoàm... Ồ, chào, tôi là\n"
	.string "{STR_VAR_1}. Tôi rất thích ăn\l"
	.string "uống trên bãi biển.\p"
	.string "POKéMON của tôi và tôi đều rất khỏe.\n"
	.string "Chúng tôi đã nạp đầy năng lượng! Tôi đi\l"
	.string "bơi đây. Tạm biệt!$"

MatchCall_PersonalizedText7::
	.string "Xin chào, tôi là {STR_VAR_1}...\p"
	.string "Tôi bắt đầu hơi chán ngán chuyện làm\n"
	.string "COOLTRAINER rồi...\p"
	.string "Ai cũng nghĩ tôi là một HLV hoàn\n"
	.string "hảo, khiến tôi phải cố sống đúng với kỳ\l"
	.string "vọng đó.\p"
	.string "Nhưng có lẽ làm COOLTRAINER thì phải\n"
	.string "chấp nhận chuyện ấy.\p"
	.string "Tôi chỉ còn cách nghiêm túc cố gắng...\n"
	.string "rồi mỉm cười chịu đựng.\p"
	.string "Bạn là người duy nhất tôi có thể tâm sự\n"
	.string "những chuyện thế này.\p"
	.string "Nhưng lần tới gặp nhau, đừng lo, tôi sẽ\n"
	.string "không than vãn đâu!$"

MatchCall_PersonalizedText8::
	.string "Yahoo, tôi là {STR_VAR_1}! Bạn\n"
	.string "khỏe chứ?\p"
	.string "Tôi đang rèn luyện POKéMON với mục tiêu\n"
	.string "vượt qua bạn.\p"
	.string "Lần tới chúng ta đấu, tôi không định\n"
	.string "thua đâu.\p"
	.string "Có bạn bè cùng làm HLV thật tuyệt,\n"
	.string "phải không? Hẹn gặp lại!$"

MatchCall_PersonalizedText9::
	.string "Tôi là {STR_VAR_1}... Ngay lúc này,\n"
	.string "phía sau bạn... Chẳng phải có thứ gì đó\l"
	.string "sao...?\p"
	.string "Sức mạnh của những POKéMON đang ngủ\n"
	.string "tại MT. PYRE...\p"
	.string "Nó đang kể cho tôi về bạn...\p"
	.string "Bạn nên nhanh chóng rời đi và tuyệt đối\n"
	.string "đừng ngoảnh lại...\p"
	.string "Hí hí... Vĩnh biệt...$"

MatchCall_PersonalizedText10::
	.string "Tôi là {STR_VAR_1}. Bạn khỏe chứ?\p"
	.string "Thật tiện khi chúng ta có thể trò\n"
	.string "chuyện từ xa thế này, phải không?\p"
	.string "Trước đây, nếu muốn nói chuyện với ai,\n"
	.string "tôi phải nhờ ba lái xe chở đi...\p"
	.string "Tôi phải đi rồi. Rất vui vì chúng ta đã\n"
	.string "trò chuyện.$"

MatchCall_PersonalizedText11::
	.string "Tôi là {STR_VAR_1}! Nghe tôi kể\n"
	.string "chuyện này nhé?\p"
	.string "Tôi rất thích SAFARI ZONE, nhưng lần\n"
	.string "nào đến đó cũng bị lạc!\p"
	.string "Cỏ cao ở khắp nơi! Mà khu vực lại rộng\n"
	.string "mênh mông!\p"
	.string "Nói hết ra thấy nhẹ nhõm hơn rồi!\p"
	.string "Tôi lại lên đường đến SAFARI ZONE đây!\n"
	.string "Hẹn gặp lại!$"

MatchCall_PersonalizedText12::
	.string "Xin chào, {STR_VAR_1} đây. Đúng\n"
	.string "vậy, tôi giàu có, chính xác là thế.\p"
	.string "Tôi nên cho bạn biết rằng kể từ lần cuối\n"
	.string "gặp nhau, tài sản của tôi còn tăng thêm.\p"
	.string "Hơn nữa, POKéMON của tôi cũng đã mạnh\n"
	.string "hơn.\p"
	.string "Tôi không thể xua đi cảm giác rằng thế\n"
	.string "giới này tồn tại vì mình!\p"
	.string "Ồ, không cần nói gì đâu! Ai cũng biết đó\n"
	.string "là sự thật!\p"
	.string "Xin thứ lỗi, tôi phải tham dự một bữa\n"
	.string "tối trang trọng.$"

MatchCall_PersonalizedText13::
	.string "Ufufufufu... Tôi đây,\n"
	.string "{STR_VAR_1}...\p"
	.string "Bạn đoán được tôi đang nhìn thấy gì\n"
	.string "không? Một cặp {STR_VAR_2} đang\l"
	.string "chiến đấu.\p"
	.string "Có lẽ tôi sẽ thử bắt con thắng cuộc...\n"
	.string "Ufufufufufu...\p"
	.string "Tôi... lúc này tôi hơi bận. Tôi phải đi rồi.$"

MatchCall_PersonalizedText14::
	.string "Ồ, tôi là {STR_VAR_1}!\p"
	.string "Tôi vừa nghĩ rằng mình đang bắt đầu\n"
	.string "chán ABANDONED SHIP.\p"
	.string "Nhưng vì đã ở đây rồi và vẫn muốn\n"
	.string "thắng bạn một lần, tôi sẽ nán lại thêm\l"
	.string "một thời gian.\p"
	.string "Nếu thấy muốn đến, sao bạn không ghé\n"
	.string "gặp tôi?\p"
	.string "Tôi nghĩ hôm nay sẽ là ngày mình cuối\n"
	.string "cùng cũng thách đấu người đàn ông\l"
	.string "phòng bên.\p"
	.string "Hẹn gặp lại!$"

MatchCall_PersonalizedText15::
	.string "Tôi là {STR_VAR_1}! Người đàn\n"
	.string "ông của biển cả!\p"
	.string "Bạn biết tôi nghĩ gì không?\p"
	.string "Các HLV ngoài biển là những người\n"
	.string "cứng cỏi nhất trong số những người\l"
	.string "cứng cỏi!\p"
	.string "Bạn nên học theo tôi và rèn luyện giữa\n"
	.string "biển khơi...\p"
	.string "Ôi, một con sóng khổng lồ đang dâng lên!\p"
	.string "Đây là cơ hội rèn luyện tuyệt vời! Xin\n"
	.string "lỗi, tôi phải đi rồi!$"

MatchCall_PersonalizedText16::
	.string "Tôi là {STR_VAR_1}! Nghe này, tôi\n"
	.string "đang dạy karate cho POKéMON của mình.\p"
	.string "Nhưng giờ chúng còn giỏi hơn cả tôi!\n"
	.string "Tôi đấu trận nào cũng thua chúng!\p"
	.string "Nhưng dù có thể thua POKéMON, tôi nhất\n"
	.string "định không thua một HLV khác đâu!\p"
	.string "Chúng ta phải đấu lại! Ugwaah!$"

MatchCall_PersonalizedText17::
	.string "Tôi đây, {STR_VAR_1}. Chuyến\n"
	.string "phiêu lưu của bạn thế nào rồi?\p"
	.string "...Ồ, thật sao? Nghe hào hứng quá!\p"
	.string "Tôi nghĩ mình có thể viết một bài hát về\n"
	.string "một trong những câu chuyện của bạn.\p"
	.string "...Ồ, cảm hứng đến rồi. Tôi nghe thấy\n"
	.string "những đoạn riff trong đầu.\p"
	.string "Tôi phải viết lại giai điệu này cho đàng\n"
	.string "hoàng, nên phải đi đây! Hẹn gặp lại!$"

MatchCall_PersonalizedText18::
	.string "Tôi là {STR_VAR_1}... Hãy nghe bài\n"
	.string "hát mới của tôi.\p"
	.string "Lalala, {STR_VAR_2},\n"
	.string "{STR_VAR_2}! Sao bạn lại là\l"
	.string "{STR_VAR_2}? Sao tôi không thể\l"
	.string "là bạn, {STR_VAR_2}? Lala,\l"
	.string "{STR_VAR_2} và\l"
	.string "{STR_VAR_1}, {STR_VAR_1}\l"
	.string "và {STR_VAR_2}...\p"
	.string "Lặp lại điệp khúc, âm thanh nhỏ dần...$"

MatchCall_PersonalizedText19::
	.string "Tôi là {STR_VAR_1}, chuyên gia\n"
	.string "cắm trại đây!\p"
	.string "Khi chúng ta đấu, tôi đành phải thua\n"
	.string "bạn.\p"
	.string "Dù sao chuyên môn của tôi cũng là cắm\n"
	.string "trại.\p"
	.string "Nhưng thắng hay thua, tôi vẫn thích\n"
	.string "chiến đấu khi đang cắm trại.\p"
	.string "Hãy đấu lại với chúng tôi nhé? À, chúng\n"
	.string "ta cũng đi cắm trại nữa!$"

MatchCall_PersonalizedText20::
	.string "Tôi đây, tôi đây, {STR_VAR_1}!\p"
	.string "Thành thật mà nói, tôi muốn leo những\n"
	.string "ngọn núi khác ngoài nơi này.\p"
	.string "Nhưng tôi không biết ở đó có quý cô nào\n"
	.string "như trên MT. CHIMNEY không.\p"
	.string "Nếu biết ngọn núi nào khác có các quý\n"
	.string "cô, hãy báo cho tôi nhé!\p"
	.string "Ehehehe, hẹn gặp lại!$"

MatchCall_PersonalizedText21::
	.string "... ... ... ... ... ... ... ... ... ... ... ... Tôi là\n"
	.string "{STR_VAR_1}...\p"
	.string "... ... ... ... ... ... ... ... ... ... ... ... Hôm nay chỉ\n"
	.string "có vậy...$"

MatchCall_PersonalizedText22::
	.string "Đây là {STR_VAR_1}. Hôm nay, tôi\n"
	.string "có linh cảm rằng mình sẽ trò chuyện với\l"
	.string "bạn.\p"
	.string "Khát khao đánh bại bạn trong tôi cứ lớn\n"
	.string "dần cả ngày lẫn đêm.\p"
	.string "Bạn cũng có một đối thủ như thế, đúng\n"
	.string "không? Tôi ước người đó là mình...\p"
	.string "Cảm ơn bạn đã lắng nghe. Hẹn gặp lại!$"

MatchCall_PersonalizedText23::
	.string "Là {STR_VAR_1} đây.\p"
	.string "Khi có một HLV mạnh ở gần, đôi lúc\n"
	.string "tôi có thể cảm nhận được bằng cách nào\l"
	.string "đó.\p"
	.string "Vừa rồi {PLAYER}{KUN} có đi ngang qua\n"
	.string "đây không? Có lẽ người tôi cảm nhận\l"
	.string "được là bạn.\p"
	.string "Tôi sẽ chờ bạn ghé thăm. Tạm biệt!$"

MatchCall_PersonalizedText24::
	.string "Xin chào, đây là {STR_VAR_1}.\n"
	.string "Nghe giọng bạn có vẻ khỏe đấy,\l"
	.string "{PLAYER}{KUN}.\p"
	.string "Tôi đã chu du khắp thế giới, nhưng phải\n"
	.string "nói rằng mình thực sự yêu thích vùng\l"
	.string "đất này.\p"
	.string "Tôi định ở lại đây một thời gian. Có lẽ\n"
	.string "chúng ta sẽ lại gặp nhau chứ?\p"
	.string "Tôi vẫn chưa quên những kỹ thuật\n"
	.string "tuyệt vời của bạn.\p"
	.string "Tôi rất mong được tái đấu.$"

MatchCall_PersonalizedText25::
	.string "Sụt sịt... Là... {STR_VAR_1} đây...\n"
	.string "Hức...\p"
	.string "Hôm nay ROXANNE đã mắng tôi trong lớp.\p"
	.string "Nhưng không phải vì thế mà tôi ghét cô\n"
	.string "ấy đâu.\p"
	.string "ROXANNE chỉ rõ tôi đã sai ở đâu để tôi\n"
	.string "có thể rút kinh nghiệm.\p"
	.string "Nhất định ngày mai tôi vẫn sẽ đến\n"
	.string "TRAINER'S SCHOOL!\p"
	.string "Hẹn gặp lại!$"

MatchCall_PersonalizedText26::
	.string "Là {STR_VAR_1} đây!\p"
	.string "Hôm qua ROXANNE đã cho tôi đấu với cô\n"
	.string "ấy.\p"
	.string "Kết quả... Tệ hại, khỏi hỏi cũng biết.\p"
	.string "Nhưng chỉ riêng việc ROXANNE cho phép\n"
	.string "tôi thách đấu cũng đủ khiến tôi vui lắm\l"
	.string "rồi!\p"
	.string "Bạn không tưởng tượng nổi tôi càng\n"
	.string "ngưỡng mộ cô ấy đến mức nào đâu!\p"
	.string "Tôi sẽ thật tập trung và cố gắng hết\n"
	.string "sức! Tôi phải đi đây!$"

MatchCall_PersonalizedText27::
	.string "Chào, ANNA đây! Hôm nay tôi lại ở cùng\n"
	.string "cộng sự đàn em MEG.\p"
	.string "Tôi rất thích chăm sóc MEG và POKéMON.\n"
	.string "Họ đáng yêu lắm!\p"
	.string "Tôi ước mình có thể chăm nom họ như em\n"
	.string "ruột vậy!\p"
	.string "Ô, chào MEG! Em mua bánh về chưa?\p"
	.string "Hả? Không, không, chị đâu có coi em là nô\n"
	.string "lệ riêng của mình!\p"
	.string "Em thua trận nên phải đi mua bánh mì để\n"
	.string "chịu phạt thôi!\p"
	.string "Chị không bao giờ coi em là nô lệ đâu,\n"
	.string "MEG! Em đặc biệt với chị lắm!\p"
	.string "Tôi phải đi rồi. Đến giờ ăn nhẹ của\n"
	.string "chúng tôi rồi!$"

MatchCall_PersonalizedText28::
	.string "Tôi yêu POKéMON! Là {STR_VAR_1}\n"
	.string "của FAN CLUB đây!\p"
	.string "Bạn nhất định phải nghe chuyện này!\n"
	.string "POKéMON yêu quý của tôi...\p"
	.string "Phì! Wahaha! Tôi không thể kể thêm đâu!\n"
	.string "Đây là bí mật! Nó đáng yêu đến mức\l"
	.string "không lời nào tả nổi!\p"
	.string "Ôi, {STR_VAR_2} yêu quý của tôi\n"
	.string "đang nài xin một {POKEBLOCK}!\p"
	.string "Đúng là hiện thân của sự đáng yêu!\p"
	.string "Xin lỗi, giờ tôi không nói chuyện được!\n"
	.string "Lần sau bạn phải nghe tiếp nhé!$"

MatchCall_PersonalizedText29::
	.string "Ohoho!\p"
	.string "Đây là {STR_VAR_1}! Tôi nóng lòng\n"
	.string "muốn kể cho bạn nghe về POKéMON cưng\l"
	.string "của mình!\p"
	.string "Xin bạn nhất định phải nghe nhé. Chuyện\n"
	.string "là về {STR_VAR_2} yêu quý của\l"
	.string "tôi.\p"
	.string "Hễ có ai bế nó lên, nó liền nhảy thẳng\n"
	.string "vào vòng tay tôi!\p"
	.string "Ôi... Ôi... Còn gì hạnh phúc hơn thế nữa\n"
	.string "chứ?\p"
	.string "Ôi, cảm giác như đang ở thiên đường\n"
	.string "vậy!\p"
	.string "Tôi rất vui vì có thể chia sẻ chút hạnh\n"
	.string "phúc của mình với bạn.\p"
	.string "Giờ tôi phải đi rồi. Tạm biệt nhé!$"

MatchCall_PersonalizedText30::
	.string "Ta là... {STR_VAR_1}. Mọi người\n"
	.string "gọi ta là một EXPERT.\p"
	.string "Nhưng có một điều ta hiểu rõ. Chỉ bằng\n"
	.string "sức mình, ta không thể trở thành\l"
	.string "EXPERT.\p"
	.string "Chỉ nhờ sự trợ giúp của POKéMON, một\n"
	.string "HLV mới có thể trở thành EXPERT.\p"
	.string "Hừm! Có vẻ ta vừa nói ra điều gì đó\n"
	.string "thật sâu sắc!\p"
	.string "Ta xin phép rời đi trong tâm trạng đầy\n"
	.string "phấn chấn!$"

MatchCall_PersonalizedText31::
	.string "Là {STR_VAR_1} đây. Thật vui khi\n"
	.string "được trò chuyện với bạn!\p"
	.string "Ngâm mình trong bồn nước nóng này\n"
	.string "khiến tôi thấy khỏe khoắn và tràn đầy\l"
	.string "sức sống.\p"
	.string "Từ lần gặp bạn, tôi đã đấu với nhiều\n"
	.string "HLV trẻ tuổi, nhưng bạn vẫn là\l"
	.string "người xuất sắc nhất.\p"
	.string "Tôi nghĩ khi về già, bạn sẽ trở thành\n"
	.string "một EXPERT! Ohohoho...$"

MatchCall_PersonalizedText32::
	.string "Yay! {STR_VAR_1} đây! Bạn đang\n"
	.string "làm gì thế?\p"
	.string "Có thể chỉ là tôi tưởng tượng thôi,\n"
	.string "nhưng mỗi khi thắng trận, chiếc quần\l"
	.string "đùi của tôi có vẻ dễ chịu hơn. Ý tôi là\l"
	.string "chất vải ấy.\p"
	.string "Tôi nói vậy nghĩa là sao à? Khó giải\n"
	.string "thích lắm, nhưng... Nói thế nào nhỉ...\l"
	.string "Chiếc quần đùi trở nên mềm mượt hơn!\p"
	.string "Còn khi đấu với {PLAYER}{KUN}, quần\n"
	.string "đùi của tôi lại vừa khó chịu vừa thô\l"
	.string "ráp.\p"
	.string "... ... ... ... ... ... Bạn không thật sự tin đấy\n"
	.string "chứ? Ehehehe, chỉ có vậy thôi! Tạm biệt\l"
	.string "nhé!$"

MatchCall_PersonalizedText33::
	.string "Ahoy! {STR_VAR_1} đây!\p"
	.string "Như mọi khi, tôi đang say sưa câu cá\n"
	.string "hết mình!\p"
	.string "Ngoài biển và sông ra, còn nơi nào khác\n"
	.string "có thể câu cá không nhỉ?\p"
	.string "Tôi thường nổi hứng muốn thả câu ở bất\n"
	.string "cứ đâu!\p"
	.string "Ôi trời, chết tiệt! Dây câu của tôi bị rối\n"
	.string "rồi!\p"
	.string "Tôi phải đi đây! Hãy tìm giúp tôi vài\n"
	.string "điểm câu cá mới nhé!$"

MatchCall_PersonalizedText34::
	.string "Chào nhé! Là {STR_VAR_1} đây.\n"
	.string "Bạn vẫn sống thong thả chứ?\p"
	.string "Từ nhỏ đến giờ, tôi vốn luôn điềm nhiên\n"
	.string "như thế, hiểu chứ?\p"
	.string "Tôi chẳng bao giờ thích căng thẳng hay\n"
	.string "vội vàng.\p"
	.string "Vậy mà giờ đây tôi lại trở thành một\n"
	.string "TRIATHLETE.\p"
	.string "Cuộc đời sẽ đưa ta đến đâu thật khó mà\n"
	.string "đoán được, nếu bạn hiểu ý tôi.\p"
	.string "Hiện giờ bạn là một HLV, nhưng ai\n"
	.string "biết tương lai sẽ thế nào, đúng không?\p"
	.string "Hãy tưởng tượng mình trở thành giáo\n"
	.string "viên, hoặc có thể là họa sĩ. Tuyệt chứ?\p"
	.string "Nhưng cứ bình tĩnh nhé. Sống thong thả\n"
	.string "thôi. Hẹn gặp lại.$"

MatchCall_PersonalizedText35::
	.string "Đây là {STR_VAR_1}! Tôi đang đạp\n"
	.string "xe.\p"
	.string "Tôi thích bơi và chạy, nhưng đạp xe mới\n"
	.string "là niềm đam mê lớn nhất!\p"
	.string "Nó khiến cả cơ thể tôi có cảm giác hòa\n"
	.string "làm một với gió.\p"
	.string "Tôi phấn khích như thể mình đang bay\n"
	.string "vậy!\p"
	.string "Được rồi! Hôm nay tôi sẽ lập kỷ lục mới\n"
	.string "tại CYCLING ROAD!\p"
	.string "Bạn cũng nên thử sức nhé! Hẹn gặp lại!$"

MatchCall_PersonalizedText36::
	.string "Yo, {STR_VAR_1} đây! Tôi đang ở\n"
	.string "ngay giữa cuộc thi ba môn phối hợp!\p"
	.string "Nhưng tôi lúc nào cũng có thời gian tán\n"
	.string "gẫu!\p"
	.string "Tập luyện cùng POKéMON thật sự rất\n"
	.string "tuyệt!\p"
	.string "Không cần nói với nhau lời nào, chúng\n"
	.string "tôi vẫn đồng điệu như cùng chung một\l"
	.string "trái tim.\p"
	.string "Thật truyền cảm hứng!\p"
	.string "Hộc... Vừa chạy vừa nói chuyện... Tôi\n"
	.string "đuối sức rồi... Hộc... Phải... đi... thôi...$"

MatchCall_PersonalizedText37::
	.string "Chào, là {STR_VAR_1} đây. Nếu\n"
	.string "muốn tăng sức bền, luyện tập trên cao\l"
	.string "là hiệu quả nhất!\p"
	.string "Thử chạy trên đỉnh núi đi. Chẳng mấy\n"
	.string "chốc bạn sẽ thở không ra hơi!\p"
	.string "Tôi cũng đang thiếu dưỡng khí đây! Hẹn\n"
	.string "gặp lại!$"

MatchCall_PersonalizedText38::
	.string "Ồ, xin chào, là {STR_VAR_1} đây.\p"
	.string "Tôi đã bơi rất nhiều, vậy mà vẫn chưa\n"
	.string "thể đến EVERGRANDE.\p"
	.string "Có lẽ tôi chỉ đang bơi vòng tròn.\p"
	.string "Không, không, chuyện đó không thể xảy\n"
	.string "ra được. Wahahaha. Bảo trọng nhé!$"

MatchCall_PersonalizedText39::
	.string "Này, {STR_VAR_1} đây... Úi!\p"
	.string "Tõm!\p"
	.string "Ùng ục ùng ục...\p"
	.string "Ào!\p"
	.string "Phì phò! Phì phò!\p"
	.string "Này! Xin lỗi nhé! Tôi vừa thoa dầu chống\n"
	.string "nắng.\p"
	.string "Thế là chiếc POKéNAV tuột khỏi tay tôi\n"
	.string "và rơi tõm xuống nước!\p"
	.string "Nhưng phải nói POKéNAV của DEVON được\n"
	.string "chế tạo bền thật. Ngâm nước như thế mà\l"
	.string "vẫn sống sót!\p"
	.string "Dù sao tôi cũng đang bận tắm nắng, để\n"
	.string "lần khác nói chuyện nhé.$"

MatchCall_PersonalizedText40::
	.string "Xin chào, đây là {STR_VAR_1}.\p"
	.string "Trong ba môn của cuộc thi ba môn phối\n"
	.string "hợp, tôi thích bơi nhất.\p"
	.string "Nhưng nếu ở dưới biển quá lâu, da tôi\n"
	.string "sẽ nhăn nheo hết phải không?\p"
	.string "Ôi, ba môn phối hợp đúng là thử thách\n"
	.string "khắc nghiệt đối với sức bền con người!\l"
	.string "Tạm biệt!$"

MatchCall_PersonalizedText41::
	.string "Xin chào, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} đây.\p"
	.string "Các POKéMON của bạn thế nào rồi?\p"
	.string "DRAGON POKéMON của tôi có vẻ đang ở\n"
	.string "trạng thái tốt nhất. Tạm biệt nhé.$"

MatchCall_PersonalizedText42::
	.string "{STR_VAR_1} đây.\p"
	.string "{STR_VAR_2} của tôi còn mạnh hơn\n"
	.string "cả lần trước.\p"
	.string "Lần tới tôi sẽ không thua bạn nữa đâu.\n"
	.string "Cứ chờ đấy!\p"
	.string "Hẹn gặp lại!$"

MatchCall_PersonalizedText43::
	.string "Ta là {STR_VAR_1}.\p"
	.string "Ta vẫn tiếp tục nghiên cứu nghệ thuật\n"
	.string "ẩn thân.\p"
	.string "Nhưng ta đã thành công quá mức. Không\n"
	.string "ai có thể tìm thấy ta. Thành công này\l"
	.string "khiến ta cô đơn...\p"
	.string "Ta tan biến tựa làn khói! Vĩnh biệt!$"

MatchCall_PersonalizedText44::
	.string "Đây là {STR_VAR_1}. Từ lần gặp\n"
	.string "nhau, tôi vẫn luôn duy trì luyện tập.\p"
	.string "{STR_VAR_2} của tôi đang trở nên\n"
	.string "khá mạnh.\p"
	.string "Quả nhiên luyện tập trên bãi biển rất\n"
	.string "hiệu quả. Tạm biệt nhé!$"

MatchCall_PersonalizedText45::
	.string "Xin chào. Đây là {STR_VAR_1}.\p"
	.string "Không biết đến bao giờ thứ tro núi lửa\n"
	.string "đáng ghét này mới ngừng rơi?\p"
	.string "Nếu tro tích quá dày, hoa văn trên\n"
	.string "chiếc ô của tôi sẽ bị che mất...\p"
	.string "Hãy hứa rằng chúng ta sẽ lại gặp nhau\n"
	.string "nhé!$"

MatchCall_PersonalizedText46::
	.string "Chào, {STR_VAR_1} đây.\p"
	.string "Bạn có biết nổi trên biển dễ hơn nổi\n"
	.string "trong hồ bơi không?\p"
	.string "Chỉ cần nằm yên, cơ thể sẽ tự nổi lên.\p"
	.string "Nhưng nếu nổi quá lâu, hãy cẩn thận kẻo\n"
	.string "bị cuốn ra quá xa.\p"
	.string "...Mà đây là đâu vậy? Tôi phải đi thôi!$"

MatchCall_PersonalizedText47::
	.string "Ồ, xin chào {PLAYER}{KUN}! Đây là\n"
	.string "{STR_VAR_1}. Giờ tôi đang ở trên\l"
	.string "núi.\p"
	.string "Nhưng mặt đất gồ ghề quá. Tôi không thể\n"
	.string "dựng lều ở đây...\p"
	.string "Ô, tôi vừa nghĩ ra một ý tuyệt hay!\p"
	.string "Có lẽ tôi có thể nhờ POKéMON nện phẳng\n"
	.string "mặt đất nơi này!\p"
	.string "Tôi sẽ thử xem! Tạm biệt!$"

MatchCall_PersonalizedText48::
	.string "Ô, chào, chào nhé, {STR_VAR_1}\n"
	.string "đây!\p"
	.string "Tôi đang cùng LIV nuôi dưỡng POKéMON!\n"
	.string "Chúng tôi cố gắng lắm đấy!\p"
	.string "Nếu cố gắng hơn nữa, liệu chúng tôi có\n"
	.string "thể trở thành số một không? Tạm biệt!$"

MatchCall_PersonalizedText49::
	.string "{STR_VAR_1} đây!\p"
	.string "Tôi là một SAILOR, nhưng giờ tôi không\n"
	.string "ở trên thuyền.\p"
	.string "Điều đó khiến tôi tự hỏi một SAILOR\n"
	.string "trên đất liền thì nên được gọi là gì?\p"
	.string "Tôi cứ suy nghĩ chuyện ấy trong khi\n"
	.string "nhìn ra những con sóng.\p"
	.string "Được rồi, hẹn lần sau!$"

MatchCall_PersonalizedText50::
	.string "Là {STR_VAR_1} đây. Sao rồi? Bạn\n"
	.string "có thêm POKéMON nào chưa?\p"
	.string "Nếu bắt được POKéMON mới, bạn phải đến\n"
	.string "cho tôi xem nhé.\p"
	.string "Tôi hứa sẽ không mè nheo đòi nó đâu. Tôi\n"
	.string "sẽ chờ. Hẹn gặp lại.$"

MatchCall_PersonalizedText51::
	.string "Đây là {STR_VAR_1}.\p"
	.string "Bạn có đang nuôi dưỡng POKéMON theo\n"
	.string "cách tốt nhất không?\p"
	.string "Không khí chỗ tôi rất trong lành. Đây là\n"
	.string "môi trường hoàn hảo để nuôi dưỡng\l"
	.string "POKéMON.\p"
	.string "Nếu muốn chuyên tâm nuôi dưỡng\n"
	.string "POKéMON, bạn nên đến\l"
	.string "{STR_VAR_2}. Bảo trọng nhé.$"

MatchCall_PersonalizedText52::
	.string "Xin chào, đây là {STR_VAR_1}.\p"
	.string "Tôi đã cho {STR_VAR_2} của mình\n"
	.string "ăn một {POKEBLOCK}. Nó có vẻ rất thích.\p"
	.string "Có vẻ POKéMON cũng có món {POKEBLOCK}\n"
	.string "thích và không thích.\p"
	.string "Tôi thấy điều đó thật thú vị. Xin hãy\n"
	.string "bảo trọng.$"

MatchCall_PersonalizedText53::
	.string "{STR_VAR_1} đây.\p"
	.string "Nếu hợp tác với POKéMON, con người có\n"
	.string "thể sống thoải mái giữa thiên nhiên\l"
	.string "hoang dã.\p"
	.string "Mọi người nên nhận ra điều đó và hợp\n"
	.string "tác với POKéMON nhiều hơn.\p"
	.string "Đó sẽ là điều lý tưởng. Tôi thật lòng\n"
	.string "nghĩ vậy.\p"
	.string "Tôi nghĩ bạn đang đi đúng hướng! Hẹn\n"
	.string "gặp lại!$"

MatchCall_PersonalizedText54::
	.string "Chào, là {STR_VAR_1}, HLV\n"
	.string "luôn chuẩn bị chu đáo đây!\p"
	.string "{PLAYER}{KUN}, bạn có đủ vật phẩm\n"
	.string "không? POKéMON của bạn đã sẵn sàng\l"
	.string "chiến đấu chưa?\p"
	.string "Bí quyết để tiếp tục hành trình là luôn\n"
	.string "giữ mọi thứ quanh mình trong trạng\l"
	.string "thái hoàn hảo.\p"
	.string "Tôi cũng phải đi kiểm tra vật dụng của\n"
	.string "mình! Luôn cảnh giác nhé!$"

MatchCall_PersonalizedText55::
	.string "Là {STR_VAR_1} đây! Là\n"
	.string "{STR_VAR_1} đây!\p"
	.string "{STR_VAR_2} là tuyến đường rất\n"
	.string "đông đúc nên ngày nào tôi cũng được\l"
	.string "đủ loại HLV thách đấu.\p"
	.string "Hôm nay tôi thắng năm trận và chỉ thua\n"
	.string "ba trận!\p"
	.string "Hôm nay bạn thi đấu thế nào? Lần sau kể\n"
	.string "tôi nghe nhé?$"

MatchCall_PersonalizedText56::
	.string "Là tôi, {STR_VAR_1} đây.\p"
	.string "Tôi nổi tiếng vì có rất nhiều BUG\n"
	.string "POKéMON, đúng không?\p"
	.string "Hôm nay tôi mang một nhóm POKéMON bọ\n"
	.string "yêu thích đến trường.\p"
	.string "Cô bạn tôi thích đã bật khóc! Muốn\n"
	.string "cười thì cứ cười đi.\p"
	.string "Tôi phải cố giúp cô ấy hiểu BUG POKéMON\n"
	.string "hấp dẫn đến mức nào.\p"
	.string "Sụt sịt... Hẹn gặp lại!$"

MatchCall_PersonalizedText57::
	.string "Hộc! Hộc! Hộc! Hộc!\p"
	.string "Chào! {STR_VAR_1} đây! Hộc! Hộc!\p"
	.string "Cố nói chuyện... Trong lúc leo núi... Đúng\n"
	.string "là bài tập khắc nghiệt... Hộc! Hộc!\p"
	.string "Ư! Hự... Dốc hơn rồi... Lần khác... nói\n"
	.string "tiếp nhé... Hộc! Hộc! Hộc!$"

MatchCall_PersonalizedText58::
	.string "Ồ, chào bạn!\p"
	.string "Tôi vẫn đang tìm kho báu cùng KIRA!\p"
	.string "Có lẽ ở đây chẳng có kho báu nào cả...\p"
	.string "Nhưng điều quan trọng là tôi được tìm\n"
	.string "kiếm bên cạnh KIRA.\p"
	.string "Ơ, KIRA! T-tại sao em lại giận?\p"
	.string "Anh đâu có phớt lờ em, em yêu! Em là\n"
	.string "người duy nhất của anh!\p"
	.string "...{PLAYER}, tôi phải đi rồi, tạm biệt!$"

MatchCall_PersonalizedText59::
	.string "Đây là {STR_VAR_1}!\p"
	.string "Tôi lại đến GYM ở DEWFORD để luyện tập.\p"
	.string "BRAWLY, GYM LEADER, có vẻ đã mạnh hơn\n"
	.string "trước.\p"
	.string "Hình như anh ấy được những con sóng\n"
	.string "dữ dội tôi luyện...\p"
	.string "Nhưng anh ấy vẫn ngầu như mọi khi. Các\n"
	.string "cô gái mê anh ấy lắm! Thành thật mà nói,\l"
	.string "tôi thấy ganh tị.\p"
	.string "Không biết... Người bạn BRUNO của anh\n"
	.string "ấy có giống BRAWLY không nhỉ?\p"
	.string "Kiểu như lúc nào cũng đẫm mồ hôi hoặc\n"
	.string "nặng mùi, rồi hay gọi người khác là con\l"
	.string "sóng lớn ấy.\p"
	.string "Nhưng mà, ghen tị thế này trông chẳng\n"
	.string "hay ho gì, đúng không?\p"
	.string "Hãy coi như cuộc trò chuyện này chưa\n"
	.string "từng xảy ra nhé? Tạm biệt!$"

MatchCall_PersonalizedText60::
	.string "Thật vui khi được trò chuyện với một\n"
	.string "HLV trẻ tuổi như bạn.\p"
	.string "Tôi tin rằng dù ở độ tuổi nào, bạn vẫn\n"
	.string "sẽ tiếp tục yêu thích POKéMON.\p"
	.string "Sẽ thật tuyệt nếu bạn có một mối gắn bó\n"
	.string "giống như chúng tôi, phải không?\p"
	.string "Dĩ nhiên, {PLAYER}{KUN}, ngay lúc này\n"
	.string "bạn đã có được niềm tin và tình bạn\l"
	.string "của các POKéMON rồi.\p"
	.string "Bạn đã có nền tảng để xây dựng những\n"
	.string "mối quan hệ lâu dài và bền chặt!\p"
	.string "Hahaha! Đừng bao giờ nản lòng!$"

MatchCall_PersonalizedText61::
	.string "Chào, {STR_VAR_1} đây! Chúng tôi\n"
	.string "vừa thắng một trận!\p"
	.string "Chúng tôi không thường thắng đâu,\n"
	.string "nhưng đối thủ lần này là một anh chàng\l"
	.string "SWIMMER rất ngầu.\p"
	.string "Chị tôi tức điên lên!\p"
	.string "Chị ấy định giả vờ yếu đuối để gây ấn\n"
	.string "tượng với anh ta!\p"
	.string "Dù thắng hay thua, chị ấy lúc nào cũng\n"
	.string "mắng tôi!\p"
	.string "{PLAYER}{KUN}, lần sau bạn nói giúp tôi\n"
	.string "vài lời với chị ấy nhé?\p"
	.string "Được rồi, hẹn gặp lại!$"

MatchCall_PersonalizedText62::
	.string "Đúng vậy, {STR_VAR_1} đây. Hôm\n"
	.string "qua tôi đã ra biển.\p"
	.string "Tôi hy vọng sẽ tìm thấy một phế tích\n"
	.string "mới để khám phá.\p"
	.string "Nhưng chẳng hiểu sao thủy triều cứ\n"
	.string "đưa tôi trở lại nơi xuất phát.\p"
	.string "Khả năng chiến đấu của tôi vẫn còn kém\n"
	.string "nữa... Bạn muốn cười nhạo thì cứ việc...\l"
	.string "Nhưng tôi sẽ không bỏ cuộc.\p"
	.string "Rồi sẽ đến ngày tôi khám phá ra một phế\n"
	.string "tích mới!\p"
	.string "Tôi chỉ muốn nói vậy thôi! Tạm biệt nhé!$"

MatchCall_PersonalizedText63::
	.string "Ahoy! Là tôi, {STR_VAR_1} đây!\n"
	.string "Tôi đang ở ROUTE 108! Nói cách khác,\l"
	.string "vẫn là nơi tôi luôn ở!\p"
	.string "Hôm nay có một cô SWIMMER xinh đẹp bơi\n"
	.string "ngang qua tôi!\p"
	.string "Thế là tôi hét lên làm cô ấy giật mình!\p"
	.string "Và cô ấy lườm tôi một cái đáng sợ!\p"
	.string "Bản tin từ ROUTE 108 đến đây là hết!\n"
	.string "Được gửi tới bạn bởi\l"
	.string "{STR_VAR_1}!$"

MatchCall_PersonalizedText64::
	.string "Là {STR_VAR_1} đây!\p"
	.string "Tôi khá bận, nhưng nghĩ rằng mình nên\n"
	.string "báo cho bạn biết hôm nay tôi lại đánh\l"
	.string "bại năm HLV.\p"
	.string "Nếu duy trì tốc độ này, lần tới có lẽ tôi\n"
	.string "sẽ đánh bại được bạn.\p"
	.string "Tôi nghĩ bạn và tôi sẽ trở thành những\n"
	.string "đối thủ tốt của nhau. Tạm biệt nhé!$"

MatchCall_BattleFrontierStreakText1::
	.string "Chào! Đây là {STR_VAR_1}. Tôi\n"
	.string "nghe tin rồi!\p"
	.string "Mọi người nói bạn đã thể hiện xuất sắc\n"
	.string "tại {STR_VAR_2}.\p"
	.string "Thật tuyệt, bạn thắng liền\n"
	.string "{STR_VAR_3} trận sao? Hẹn gặp\l"
	.string "lại!$"

MatchCall_BattleFrontierStreakText2::
	.string "Xin chào, {STR_VAR_1} đây! Tôi\n"
	.string "nghe chuyện về bạn rồi!\p"
	.string "Họ nói bạn đã thắng liên tiếp\n"
	.string "{STR_VAR_3} trận tại\l"
	.string "{STR_VAR_2}.\p"
	.string "Thật phi thường! Tôi cũng phải cố gắng\n"
	.string "hơn! Hẹn gặp lại!$"

MatchCall_BattleFrontierStreakText3::
	.string "Chào nhé, {PLAYER}! Là tôi,\n"
	.string "{STR_VAR_1} đây.\p"
	.string "Tôi nghe nói bạn đã tung hoành tại\n"
	.string "{STR_VAR_2}!\p"
	.string "Chuỗi {STR_VAR_3} trận thắng...\n"
	.string "Đó là một kỷ lục lớn, đúng không?\p"
	.string "Tôi cũng phải nghiêm túc hơn mới được!\n"
	.string "Hẹn sớm gặp lại!$"

MatchCall_BattleFrontierStreakText4::
	.string "Này, {PLAYER}{KUN}. {STR_VAR_1}\n"
	.string "đây. Có chuyện gì không?\p"
	.string "Tôi nghe tin đồn rằng bạn đã thắng liên\n"
	.string "tiếp {STR_VAR_3} trận tại\l"
	.string "{STR_VAR_2}.\p"
	.string "Tôi cũng phải tăng tốc thôi. Hẹn gặp lại!$"

MatchCall_BattleFrontierStreakText5::
	.string "Chào {PLAYER}{KUN}! Là\n"
	.string "{STR_VAR_1} đây.\p"
	.string "Bạn đã đến {STR_VAR_2} và thắng\n"
	.string "liên tiếp {STR_VAR_3} trận sao?\l"
	.string "Thật đáng nể!\p"
	.string "Tôi phải chăm lo cho POKéMON của mình\n"
	.string "hơn nữa. Hẹn sớm gặp lại!$"

MatchCall_BattleFrontierStreakText6::
	.string "Này, {PLAYER}{KUN}. {STR_VAR_1}\n"
	.string "đây. Bạn khỏe không?\p"
	.string "Nhân tiện, tôi nghe nói bạn đã lập thành\n"
	.string "tích thắng liên tiếp {STR_VAR_3}\l"
	.string "trận tại {STR_VAR_2}.\p"
	.string "Điều đó truyền cảm hứng để tôi tập\n"
	.string "trung nuôi dưỡng đội của mình.$"

MatchCall_BattleFrontierStreakText7::
	.string "...Ờ, {PLAYER}{KUN} phải không?\n"
	.string "{STR_VAR_1} đây...\p"
	.string "À phải rồi, bạn đã đến\n"
	.string "{STR_VAR_2}, đúng không?\p"
	.string "Và bạn đã thắng liên tiếp\n"
	.string "{STR_VAR_3} trận.\p"
	.string "Ô, một POKéMON hiếm vừa chạy qua! Tôi\n"
	.string "phải đi đây!$"

MatchCall_BattleFrontierStreakText8::
	.string "Ồ, xin chào {PLAYER}{KUN}. Đây là\n"
	.string "{STR_VAR_1}. Tôi mong bạn vẫn\l"
	.string "khỏe.\p"
	.string "À, nhưng rõ ràng là bạn rất khỏe. Tôi\n"
	.string "nghe nói bạn đã thắng liên tiếp\l"
	.string "{STR_VAR_3} trận tại\l"
	.string "{STR_VAR_2}.\p"
	.string "Thật vô cùng ấn tượng! Chúc bạn tiếp\n"
	.string "tục thành công.$"

MatchCall_BattleFrontierStreakText9::
	.string "Ồ, chào {PLAYER}{KUN}! Đây là\n"
	.string "{STR_VAR_1}!\p"
	.string "Tôi nghe rồi! Chuỗi {STR_VAR_3}\n"
	.string "trận thắng của bạn tại\l"
	.string "{STR_VAR_2}!\p"
	.string "Thật quá ngầu! Tôi cũng phải cố gắng\n"
	.string "hơn!$"

MatchCall_BattleFrontierStreakText10::
	.string "Ồ, xin chào {PLAYER}{KUN}... Đây là\n"
	.string "{STR_VAR_1}.\p"
	.string "Bạn đã thắng liên tiếp\n"
	.string "{STR_VAR_3} trận tại\l"
	.string "{STR_VAR_2} sao?\p"
	.string "Đó là một thành tích đáng nể. Tôi cần cố\n"
	.string "gắng hơn.$"

MatchCall_BattleFrontierStreakText11::
	.string "À, {PLAYER}{KUN}. Đây là\n"
	.string "{STR_VAR_1}.\p"
	.string "Tôi nghe nói bạn là nỗi kinh hoàng của\n"
	.string "{STR_VAR_2}?\p"
	.string "Bạn đã thắng liên tiếp bao nhiêu nhỉ,\n"
	.string "{STR_VAR_3} trận sao?\p"
	.string "Bạn giỏi thật đấy. Không biết tôi có thể\n"
	.string "thắng được bao nhiêu trận?$"

MatchCall_BattleFrontierStreakText12::
	.string "Xin chào, {PLAYER}{KUN}. Là tôi,\n"
	.string "{STR_VAR_1} đây. Bạn vẫn khỏe\l"
	.string "chứ?\p"
	.string "Có người kể tôi nghe chuyện bạn đã\n"
	.string "thắng liên tiếp {STR_VAR_3} trận\l"
	.string "tại một nơi tên là {STR_VAR_2}.\p"
	.string "Quả là một câu chuyện đáng nể. Hẹn gặp\n"
	.string "lại!$"

MatchCall_BattleFrontierStreakText13::
	.string "À, xin chào {PLAYER}{KUN}! Đây là\n"
	.string "{STR_VAR_1}! Mong rằng bạn vẫn\l"
	.string "khỏe.\p"
	.string "Họ nói bạn đã thắng liên tiếp\n"
	.string "{STR_VAR_3} trận tại\l"
	.string "{STR_VAR_2}.\p"
	.string "Tôi thật khâm phục nghị lực của bạn!\n"
	.string "Tạm biệt nhé.$"

MatchCall_BattleFrontierStreakText14::
	.string "Ồ, chào {PLAYER}{KUN}. Đây là\n"
	.string "{STR_VAR_1}.\p"
	.string "Tôi nghe chuyện về bạn rồi! Chẳng phải\n"
	.string "bạn vừa thắng liên tiếp\l"
	.string "{STR_VAR_3} trận tại\l"
	.string "{STR_VAR_2} sao?\p"
	.string "Bạn thật truyền cảm hứng! Tạm biệt!$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "Chào! Đây là {STR_VAR_1}. Tôi\n"
	.string "nghe tin rồi!\p"
	.string "Mọi người nói bạn đã thể hiện xuất sắc\n"
	.string "tại {STR_VAR_2}.\p"
	.string "Thật tuyệt, bạn thắng liền\n"
	.string "{STR_VAR_3} trận sao? Hẹn gặp\l"
	.string "lại!$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "Xin chào, {STR_VAR_1} đây! Tôi\n"
	.string "nghe chuyện về bạn rồi!\p"
	.string "Họ nói bạn đã thắng liên tiếp\n"
	.string "{STR_VAR_3} trận tại\l"
	.string "{STR_VAR_2}.\p"
	.string "Thật phi thường! Tôi cũng phải cố gắng\n"
	.string "hơn! Hẹn gặp lại!$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "Chào nhé, {PLAYER}! Là tôi,\n"
	.string "{STR_VAR_1} đây.\p"
	.string "Tôi nghe nói bạn đã tung hoành tại\n"
	.string "{STR_VAR_2}!\p"
	.string "Chuỗi {STR_VAR_3} trận thắng...\n"
	.string "Đó là một kỷ lục lớn, đúng không?\p"
	.string "Tôi cũng phải nghiêm túc hơn mới được!\n"
	.string "Hẹn sớm gặp lại!$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "Này, {PLAYER}{KUN}. {STR_VAR_1}\n"
	.string "đây. Có chuyện gì không?\p"
	.string "Tôi nghe tin đồn rằng bạn đã thắng liên\n"
	.string "tiếp {STR_VAR_3} trận tại\l"
	.string "{STR_VAR_2}.\p"
	.string "Tôi cũng phải tăng tốc thôi. Hẹn gặp lại!$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "Chào {PLAYER}{KUN}! Là\n"
	.string "{STR_VAR_1} đây.\p"
	.string "Bạn đã đến {STR_VAR_2} và thắng\n"
	.string "liên tiếp {STR_VAR_3} trận sao?\l"
	.string "Thật đáng nể!\p"
	.string "Còn tôi à? Tôi nghĩ mình cũng đang tiến\n"
	.string "bộ. Hẹn sớm gặp lại!$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "Này, {PLAYER}{KUN}. {STR_VAR_1}\n"
	.string "đây. Bạn khỏe không?\p"
	.string "Nhân tiện, tôi nghe nói bạn đã lập thành\n"
	.string "tích thắng liên tiếp {STR_VAR_3}\l"
	.string "trận tại {STR_VAR_2}.\p"
	.string "Bản thân tôi cũng phải cố gắng hơn! Hẹn\n"
	.string "sớm gặp lại!$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "...Ờ, {PLAYER}{KUN} phải không?\n"
	.string "{STR_VAR_1} đây...\p"
	.string "À phải rồi, bạn đã đến\n"
	.string "{STR_VAR_2}, đúng không?\p"
	.string "Và bạn đã thắng liên tiếp\n"
	.string "{STR_VAR_3} trận.\p"
	.string "Ô, một POKéMON hiếm vừa chạy qua! Tôi\n"
	.string "phải đi đây!$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "Ồ, xin chào {PLAYER}{KUN}. Đây là\n"
	.string "{STR_VAR_1}. Tôi mong bạn vẫn\l"
	.string "khỏe.\p"
	.string "À, nhưng rõ ràng là bạn rất khỏe. Tôi\n"
	.string "nghe nói bạn đã thắng liên tiếp\l"
	.string "{STR_VAR_3} trận tại\l"
	.string "{STR_VAR_2}.\p"
	.string "Thật vô cùng ấn tượng! Tôi cũng phải\n"
	.string "chăm lo cho POKéMON của mình hơn!$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "Ồ, chào {PLAYER}{KUN}! Đây là\n"
	.string "{STR_VAR_1}!\p"
	.string "Tôi nghe rồi! Chuỗi {STR_VAR_3}\n"
	.string "trận thắng của bạn tại\l"
	.string "{STR_VAR_2}!\p"
	.string "Thật quá ngầu! Tôi cũng phải cố gắng\n"
	.string "hơn!$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "Ồ, xin chào {PLAYER}{KUN}... Đây là\n"
	.string "{STR_VAR_1}.\p"
	.string "Bạn đã thắng liên tiếp\n"
	.string "{STR_VAR_3} trận tại\l"
	.string "{STR_VAR_2} sao?\p"
	.string "Đó là một thành tích đáng nể. Tôi cần cố\n"
	.string "gắng hơn.$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "À, {PLAYER}{KUN}. Đây là\n"
	.string "{STR_VAR_1}.\p"
	.string "Tôi nghe nói bạn là nỗi kinh hoàng của\n"
	.string "{STR_VAR_2}?\p"
	.string "Bạn đã thắng liên tiếp bao nhiêu nhỉ,\n"
	.string "{STR_VAR_3} trận sao?\p"
	.string "Bạn giỏi thật đấy. Không biết tôi có thể\n"
	.string "thắng được bao nhiêu trận?$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "Xin chào, {PLAYER}{KUN}. Là tôi,\n"
	.string "{STR_VAR_1} đây. Bạn vẫn khỏe\l"
	.string "chứ?\p"
	.string "Có người kể tôi nghe chuyện bạn đã\n"
	.string "thắng liên tiếp {STR_VAR_3} trận\l"
	.string "tại một nơi tên là {STR_VAR_2}.\p"
	.string "Quả là một câu chuyện đáng nể. Hẹn gặp\n"
	.string "lại!$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "À, xin chào {PLAYER}{KUN}! Đây là\n"
	.string "{STR_VAR_1}! Mong rằng bạn vẫn\l"
	.string "khỏe.\p"
	.string "Họ nói bạn đã thắng liên tiếp\n"
	.string "{STR_VAR_3} trận tại\l"
	.string "{STR_VAR_2}.\p"
	.string "Tôi thật khâm phục nghị lực của bạn!\n"
	.string "Tạm biệt nhé.$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "Ồ, chào {PLAYER}{KUN}. Đây là\n"
	.string "{STR_VAR_1}. Tôi nghe chuyện về\l"
	.string "bạn rồi!\p"
	.string "Chẳng phải bạn vừa thắng liên tiếp\n"
	.string "{STR_VAR_3} trận tại\l"
	.string "{STR_VAR_2} sao?\p"
	.string "Bạn thật truyền cảm hứng! Tạm biệt!$"

MatchCall_BattleDomeText1::
	.string "Chào! {PLAYER} phải không? Xin chào,\n"
	.string "đây là {STR_VAR_1}! Tôi nghe tin\l"
	.string "rồi!\p"
	.string "Bạn đã trở thành nhà vô địch tại\n"
	.string "{STR_VAR_2} đến\l"
	.string "{STR_VAR_3} lần sao?\p"
	.string "Thật tuyệt! Tôi phải làm tốt hơn nữa!\n"
	.string "Hẹn gặp lại!$"

MatchCall_BattleDomeText2::
	.string "Xin chào, {STR_VAR_1} đây! Tôi\n"
	.string "nghe chuyện về bạn rồi!\p"
	.string "Họ nói bạn đã giành {STR_VAR_3}\n"
	.string "danh hiệu tại {STR_VAR_2}.\p"
	.string "Thật tuyệt vời! Không biết tôi có thể\n"
	.string "trở thành nhà vô địch không nhỉ?$"

MatchCall_BattleDomeText3::
	.string "Chào nhé, {PLAYER}! Là tôi,\n"
	.string "{STR_VAR_1} đây. Bạn thế nào rồi?\p"
	.string "Tôi nghe nói bạn đã chiến thắng\n"
	.string "{STR_VAR_3} lần tại\l"
	.string "{STR_VAR_2}!\p"
	.string "Lần sau hãy thắng thêm một lần nữa nhé!\n"
	.string "Hẹn sớm gặp lại!$"

MatchCall_BattleDomeText4::
	.string "Này, {PLAYER}{KUN}. {STR_VAR_1}\n"
	.string "đây.\p"
	.string "Tôi nghe nói bạn đã trở thành nhà vô\n"
	.string "địch tại {STR_VAR_2} đến\l"
	.string "{STR_VAR_3} lần.\p"
	.string "Có vẻ bạn đang rất nỗ lực. Tôi cũng sẽ\n"
	.string "cố theo kịp!$"

MatchCall_BattleDomeText5::
	.string "Chào {PLAYER}{KUN}! Là\n"
	.string "{STR_VAR_1} đây.\p"
	.string "Tôi nghe nói bạn đã giành chiến thắng\n"
	.string "tuyệt đối {STR_VAR_3} lần tại\l"
	.string "{STR_VAR_2}.\p"
	.string "Tôi cũng phải bắt tay vào cố gắng thôi!\n"
	.string "Hẹn sớm gặp lại!$"

MatchCall_BattleDomeText6::
	.string "Này, {PLAYER}{KUN} phải không?\n"
	.string "{STR_VAR_1} đây. Bạn khỏe không?\p"
	.string "Nhân tiện, tôi nghe nói bạn đã trở\n"
	.string "thành nhà vô địch {STR_VAR_3}\l"
	.string "lần tại {STR_VAR_2}.\p"
	.string "Tôi phải nuôi dưỡng POKéMON của mình\n"
	.string "tốt hơn trước khi bạn bỏ xa tôi thêm\l"
	.string "nữa.$"

MatchCall_BattleDomeText7::
	.string "{PLAYER}{KUN} phải không?\n"
	.string "{STR_VAR_1} đây.\p"
	.string "Bạn đã đến {STR_VAR_2} và trở\n"
	.string "thành nhà vô địch {STR_VAR_3}\l"
	.string "lần sao?\p"
	.string "Hay thật. Nhân tiện, gần đây bạn có bắt\n"
	.string "được POKéMON hiếm nào không?\p"
	.string "Ồ, vậy sao. Được rồi, tạm biệt.$"

MatchCall_BattleDomeText8::
	.string "Ồ, xin chào {PLAYER}{KUN}. Đây là\n"
	.string "{STR_VAR_1}. Tôi mong bạn vẫn\l"
	.string "khỏe. À, nhưng rõ ràng là bạn rất khỏe.\p"
	.string "Tôi nghe nói bạn đã giành\n"
	.string "{STR_VAR_3} danh hiệu tại\l"
	.string "{STR_VAR_2}.\p"
	.string "Tôi phải nuôi dưỡng POKéMON giỏi như\n"
	.string "bạn mới được. Hẹn gặp lại.$"

MatchCall_BattleDomeText9::
	.string "Ồ, chào {PLAYER}{KUN}! Đây là\n"
	.string "{STR_VAR_1}!\p"
	.string "Tôi nghe rồi! Bạn đã giành danh hiệu\n"
	.string "{STR_VAR_3} lần tại\l"
	.string "{STR_VAR_2}!\p"
	.string "Thật quá ngầu! Tôi cũng phải cố gắng\n"
	.string "hơn!$"

MatchCall_BattleDomeText10::
	.string "Ồ, xin chào {PLAYER}{KUN}. Đây là\n"
	.string "{STR_VAR_1}.\p"
	.string "Bạn đã chiến thắng liên tiếp\n"
	.string "{STR_VAR_3} lần tại\l"
	.string "{STR_VAR_2} sao?\p"
	.string "Đó là một thành tích đáng nể. Tôi cần cố\n"
	.string "gắng hơn.$"

MatchCall_BattleDomeText11::
	.string "À, {PLAYER}{KUN}. Đây là\n"
	.string "{STR_VAR_1}.\p"
	.string "Tôi nghe nói bạn là nỗi kinh hoàng của\n"
	.string "{STR_VAR_2}?\p"
	.string "Bạn đã chiến thắng liên tiếp bao nhiêu\n"
	.string "nhỉ, {STR_VAR_3} lần sao?\p"
	.string "Không biết tôi có bao giờ trở thành nhà\n"
	.string "vô địch được không?\p"
	.string "...Gần như không thể sao? Được rồi, hẹn\n"
	.string "gặp lại!$"

MatchCall_BattleDomeText12::
	.string "Xin chào, {PLAYER}{KUN}. Là tôi,\n"
	.string "{STR_VAR_1} đây. Bạn vẫn khỏe\l"
	.string "chứ?\p"
	.string "Bạn đã chiến thắng {STR_VAR_3}\n"
	.string "lần tại một nơi tên là\l"
	.string "{STR_VAR_2} sao?\p"
	.string "Quả là một câu chuyện đáng nể. Hẹn gặp\n"
	.string "lại!$"

MatchCall_BattleDomeText13::
	.string "À, xin chào {PLAYER}{KUN}! Đây là\n"
	.string "{STR_VAR_1}! Mong rằng bạn vẫn\l"
	.string "khỏe.\p"
	.string "Họ nói bạn đã chiến thắng\n"
	.string "{STR_VAR_3} lần tại\l"
	.string "{STR_VAR_2} sao?\p"
	.string "Tôi thật khâm phục nghị lực của bạn!\n"
	.string "Tạm biệt nhé.$"

MatchCall_BattleDomeText14::
	.string "Ồ, chào {PLAYER}{KUN}. Đây là\n"
	.string "{STR_VAR_1}. Tôi nghe chuyện về\l"
	.string "bạn rồi!\p"
	.string "Chẳng phải bạn đã giành\n"
	.string "{STR_VAR_3} danh hiệu tại\l"
	.string "{STR_VAR_2} sao?\p"
	.string "Bạn thật truyền cảm hứng! Hẹn gặp lại!$"

MatchCall_BattlePikeText1::
	.string "Chào! {PLAYER} phải không? Xin chào,\n"
	.string "đây là {STR_VAR_1}! Tôi nghe tin\l"
	.string "rồi!\p"
	.string "Bạn đã vượt qua {STR_VAR_3}\n"
	.string "phòng tại {STR_VAR_2}!\p"
	.string "Thật tuyệt vời! Hẹn gặp lại!$"

MatchCall_BattlePikeText2::
	.string "Xin chào, {STR_VAR_1} đây! Tôi\n"
	.string "nghe chuyện về bạn rồi!\p"
	.string "Họ nói bạn đã chiến thắng và vượt qua\n"
	.string "{STR_VAR_3} phòng tại\l"
	.string "{STR_VAR_2}.\p"
	.string "Tôi phải cố gắng hơn nhiều nữa! Tạm\n"
	.string "biệt!$"

MatchCall_BattlePikeText3::
	.string "Chào nhé, {PLAYER}! Là tôi,\n"
	.string "{STR_VAR_1} đây. Bạn thế nào rồi?\p"
	.string "Tôi nghe nói bạn đã chiến thắng và\n"
	.string "vượt qua {STR_VAR_3} phòng tại\l"
	.string "{STR_VAR_2}!\p"
	.string "Lần sau hãy đạt thành tích cao hơn\n"
	.string "nữa nhé! Hẹn sớm gặp lại!$"

MatchCall_BattlePikeText4::
	.string "Này, {PLAYER}{KUN}. {STR_VAR_1}\n"
	.string "đây.\p"
	.string "Tôi nghe nói bạn đã dễ dàng vượt qua\n"
	.string "{STR_VAR_3} phòng tại\l"
	.string "{STR_VAR_2}.\p"
	.string "Tôi phải huấn luyện POKéMON và cố theo\n"
	.string "kịp bạn!$"

MatchCall_BattlePikeText5::
	.string "Chào {PLAYER}{KUN}! Là\n"
	.string "{STR_VAR_1} đây.\p"
	.string "Tôi nghe nói bạn đã vượt qua\n"
	.string "{STR_VAR_3} phòng tại\l"
	.string "{STR_VAR_2}.\p"
	.string "Tôi cũng phải bắt tay vào cố gắng thôi!\n"
	.string "Hẹn sớm gặp lại!$"

MatchCall_BattlePikeText6::
	.string "Này, {PLAYER}{KUN} phải không?\n"
	.string "{STR_VAR_1} đây. Bạn khỏe không?\p"
	.string "Nhân tiện, tôi nghe nói bạn đã vượt qua\n"
	.string "{STR_VAR_3} phòng tại\l"
	.string "{STR_VAR_2}.\p"
	.string "Tôi phải nuôi dưỡng POKéMON của mình\n"
	.string "tốt hơn trước khi bạn bỏ xa tôi thêm\l"
	.string "nữa.$"

MatchCall_BattlePikeText7::
	.string "{PLAYER}{KUN} phải không?\n"
	.string "{STR_VAR_1} đây.\p"
	.string "Bạn đã đến {STR_VAR_2} và chiến\n"
	.string "thắng để vượt qua {STR_VAR_3}\l"
	.string "phòng sao?\p"
	.string "Ghê thật.\p"
	.string "Ô, một POKéMON hiếm vừa chạy qua! Được\n"
	.string "rồi, tạm biệt.$"

MatchCall_BattlePikeText8::
	.string "Ồ, xin chào {PLAYER}{KUN}. Đây là\n"
	.string "{STR_VAR_1}. Tôi mong bạn vẫn\l"
	.string "khỏe. À, nhưng rõ ràng là bạn rất khỏe.\p"
	.string "Tôi nghe nói bạn đã vượt qua\n"
	.string "{STR_VAR_3} phòng tại\l"
	.string "{STR_VAR_2}.\p"
	.string "Thật vô cùng ấn tượng! Tôi phải nuôi\n"
	.string "dưỡng POKéMON giỏi như bạn mới được.\l"
	.string "Hẹn gặp lại.$"

MatchCall_BattlePikeText9::
	.string "Ồ, chào {PLAYER}{KUN}! Đây là\n"
	.string "{STR_VAR_1}!\p"
	.string "Tôi nghe rồi! Bạn đã chiến thắng và\n"
	.string "vượt qua {STR_VAR_3} phòng tại\l"
	.string "{STR_VAR_2}!\p"
	.string "Thật quá ngầu! Tôi cũng phải cố gắng\n"
	.string "hơn!$"

MatchCall_BattlePikeText10::
	.string "Ồ, xin chào {PLAYER}{KUN}. Đây là\n"
	.string "{STR_VAR_1}.\p"
	.string "Bạn đã chiến thắng để vượt qua\n"
	.string "{STR_VAR_3} phòng tại\l"
	.string "{STR_VAR_2} sao?\p"
	.string "Đó là một thành tích đáng nể. Tôi cần cố\n"
	.string "gắng hơn.$"

MatchCall_BattlePikeText11::
	.string "À, {PLAYER}{KUN}. Đây là\n"
	.string "{STR_VAR_1}.\p"
	.string "Tôi nghe nói bạn là nỗi kinh hoàng của\n"
	.string "{STR_VAR_2}?\p"
	.string "Bạn đã vượt qua bao nhiêu nhỉ,\n"
	.string "{STR_VAR_3} phòng sao? Thành\l"
	.string "tích đó phải có ý nghĩa gì chứ.\p"
	.string "Không biết tôi có bao giờ trở thành nhà\n"
	.string "vô địch được không?\p"
	.string "...Gần như không thể sao? Được rồi, hẹn\n"
	.string "gặp lại!$"

MatchCall_BattlePikeText12::
	.string "Xin chào, {PLAYER}{KUN}. Là tôi,\n"
	.string "{STR_VAR_1} đây. Bạn vẫn khỏe\l"
	.string "chứ?\p"
	.string "Bạn đã chiến thắng và vượt qua\n"
	.string "{STR_VAR_3} phòng tại một nơi\l"
	.string "tên là {STR_VAR_2} sao?\p"
	.string "Quả là một câu chuyện đáng nể. Hẹn gặp\n"
	.string "lại!$"

MatchCall_BattlePikeText13::
	.string "À, xin chào {PLAYER}{KUN}! Đây là\n"
	.string "{STR_VAR_1}! Mong rằng bạn vẫn\l"
	.string "khỏe.\p"
	.string "Họ nói bạn đã chiến thắng trong\n"
	.string "{STR_VAR_3} phòng tại\l"
	.string "{STR_VAR_2} sao?\p"
	.string "Tôi thật khâm phục nghị lực của bạn!\n"
	.string "Tạm biệt nhé.$"

MatchCall_BattlePikeText14::
	.string "Ồ, chào {PLAYER}{KUN}. Đây là\n"
	.string "{STR_VAR_1}. Tôi nghe chuyện về\l"
	.string "bạn rồi!\p"
	.string "Chẳng phải bạn đã vượt qua\n"
	.string "{STR_VAR_3} phòng tại\l"
	.string "{STR_VAR_2} sao?\p"
	.string "Bạn thật truyền cảm hứng! Hẹn gặp lại!$"

MatchCall_BattlePyramidText1::
	.string "Chào! {PLAYER} phải không? Xin chào,\n"
	.string "đây là {STR_VAR_1}! Tôi nghe tin\l"
	.string "rồi!\p"
	.string "Bạn đã leo qua {STR_VAR_3} tầng\n"
	.string "bên trong {STR_VAR_2}, đúng\l"
	.string "không?\p"
	.string "Thật tuyệt vời! Tôi cũng nên thử sức\n"
	.string "với thử thách đó.$"

MatchCall_BattlePyramidText2::
	.string "Chào, {STR_VAR_1} đây! Tôi nghe\n"
	.string "chuyện về bạn rồi!\p"
	.string "Nghe nói bạn đã vượt qua\n"
	.string "{STR_VAR_3} tầng trong\l"
	.string "{STR_VAR_2}.\p"
	.string "Chà, tuyệt thật đấy! Tôi cũng phải chăm\n"
	.string "bồi dưỡng POKéMON mới được!$"

MatchCall_BattlePyramidText3::
	.string "Chào, {PLAYER}! {STR_VAR_1}\n"
	.string "đây. Dạo này thế nào?\p"
	.string "Tôi nghe nói bạn đã leo qua\n"
	.string "{STR_VAR_3} tầng trong\l"
	.string "{STR_VAR_2}!\p"
	.string "Lần tới hãy cố đạt thành tích cao hơn\n"
	.string "nữa nhé! Hẹn sớm gặp lại!$"

MatchCall_BattlePyramidText4::
	.string "Này, {PLAYER}{KUN}. {STR_VAR_1}\n"
	.string "đây.\p"
	.string "Tôi nghe nói bạn đã vượt qua\n"
	.string "{STR_VAR_3} tầng trong\l"
	.string "{STR_VAR_2}.\p"
	.string "Tôi phải cố gắng chăm chỉ để theo kịp\n"
	.string "bạn mới được!$"

MatchCall_BattlePyramidText5::
	.string "Chào, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} đây.\p"
	.string "Tôi nghe nói bạn đã leo qua\n"
	.string "{STR_VAR_3} tầng trong\l"
	.string "{STR_VAR_2}.\p"
	.string "Tôi cũng phải bắt tay vào cố gắng thôi!\n"
	.string "Hẹn sớm gặp lại!$"

MatchCall_BattlePyramidText6::
	.string "Này, {PLAYER}{KUN} phải không?\n"
	.string "{STR_VAR_1} đây. Bạn khỏe chứ?\p"
	.string "Nhân tiện, tôi nghe nói bạn đã vượt qua\n"
	.string "{STR_VAR_3} tầng trong\l"
	.string "{STR_VAR_2}.\p"
	.string "Tôi phải mau bồi dưỡng POKéMON trước\n"
	.string "khi bị bạn bỏ xa hơn nữa.$"

MatchCall_BattlePyramidText7::
	.string "{PLAYER}{KUN} phải không?\n"
	.string "{STR_VAR_1} đây.\p"
	.string "Bạn đã đến {STR_VAR_2} và thắng\n"
	.string "một mạch qua {STR_VAR_3} tầng à?\p"
	.string "Hay đấy. Ở đó có POKéMON quý hiếm nào\n"
	.string "không?\p"
	.string "Không à? Được rồi, tạm biệt.$"

MatchCall_BattlePyramidText8::
	.string "Ồ, {PLAYER}{KUN}, xin chào. Tôi là\n"
	.string "{STR_VAR_1}. Mong là bạn vẫn\l"
	.string "khỏe. À, nhưng chắc chắn là vậy rồi.\p"
	.string "Tôi nghe nói bạn đã vượt qua\n"
	.string "{STR_VAR_3} tầng trong\l"
	.string "{STR_VAR_2}.\p"
	.string "Thật đáng nể! Tôi cũng phải bồi dưỡng\n"
	.string "POKéMON như bạn mới được. Hẹn gặp lại.$"

MatchCall_BattlePyramidText9::
	.string "Ồ, chào {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} đây!\p"
	.string "Tôi nghe tin rồi! Bạn đã thắng một mạch\n"
	.string "qua {STR_VAR_3} tầng trong\l"
	.string "{STR_VAR_2}!\p"
	.string "Ngầu thật đấy! Tôi cũng phải cố gắng\n"
	.string "hơn nữa!$"

MatchCall_BattlePyramidText10::
	.string "Ồ, xin chào {PLAYER}{KUN}. Tôi là\n"
	.string "{STR_VAR_1}.\p"
	.string "Bạn đã leo qua {STR_VAR_3} tầng\n"
	.string "bên trong {STR_VAR_2} à?\p"
	.string "Quả là một thành tích đáng nể. Tôi cần\n"
	.string "cố gắng hơn nữa.$"

MatchCall_BattlePyramidText11::
	.string "À, {PLAYER}{KUN}. {STR_VAR_1}\n"
	.string "đây.\p"
	.string "Nghe nói bạn đang gieo kinh hoàng trong\n"
	.string "{STR_VAR_2} à?\p"
	.string "Bạn đã vượt qua bao nhiêu nhỉ,\n"
	.string "{STR_VAR_3} tầng sao? Thành\l"
	.string "tích ấy hẳn phải có ý nghĩa gì đó.\p"
	.string "Không biết tôi có thể trở thành nhà vô\n"
	.string "địch không nhỉ?\p"
	.string "...Gần như không thể à? Thôi, hẹn gặp\n"
	.string "lại!$"

MatchCall_BattlePyramidText12::
	.string "Xin chào, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} đây. Bạn vẫn khỏe\l"
	.string "chứ?\p"
	.string "Bạn đã thắng một mạch qua\n"
	.string "{STR_VAR_3} tầng ở một nơi tên\l"
	.string "là {STR_VAR_2} à?\p"
	.string "Quả là một câu chuyện đáng nể. Hẹn gặp\n"
	.string "lại!$"

MatchCall_BattlePyramidText13::
	.string "À, xin chào {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} đây! Mong là bạn vẫn\l"
	.string "khỏe.\p"
	.string "Nghe nói bạn đã leo qua\n"
	.string "{STR_VAR_3} tầng trong\l"
	.string "{STR_VAR_2} à?\p"
	.string "Tôi thật khâm phục sức lực của bạn! Tạm\n"
	.string "biệt nhé.$"

MatchCall_BattlePyramidText14::
	.string "Ồ, chào {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} đây. Tôi nghe chuyện\l"
	.string "về bạn rồi!\p"
	.string "Chẳng phải bạn đã vượt qua\n"
	.string "{STR_VAR_3} tầng trong\l"
	.string "{STR_VAR_2} sao?\p"
	.string "Bạn thật sự truyền cảm hứng cho tôi!\n"
	.string "Hẹn gặp lại!$"

MatchCall_Text_Mom1::
	.string "MẸ: Ba con và con... Ai cũng say mê\n"
	.string "POKéMON.\p"
	.string "POKéMON có sức hấp dẫn gì nhỉ?\p"
	.string "Còn mẹ à? Mẹ rất yêu những POKéMON\n"
	.string "giúp mẹ làm việc nhà hằng ngày.$"

MatchCall_Text_Mom2::
	.string "MẸ: Chào con, {PLAYER}! Ba con cứ\n"
	.string "nhốt mình trong PETALBURG GYM suốt.\p"
	.string "Thỉnh thoảng ông ấy cũng về nhà. Nhưng\n"
	.string "ăn sạch mọi thứ có thể ăn xong là lại\l"
	.string "quay về GYM.\p"
	.string "Mẹ đoán việc thua con đã giáng một đòn\n"
	.string "mạnh vào lòng tự trọng của ba!$"

MatchCall_Text_Mom3::
	.string "MẸ: {PLAYER}... Đừng lo cho mẹ hay\n"
	.string "căn nhà.\p"
	.string "Cứ mang đôi RUNNING SHOES ấy chạy đến\n"
	.string "khi rách thì thôi nhé, con yêu!$"

MatchCall_Text_Roxanne_Preparing::
	.string "ROXANNE: Ồ, xin chào {PLAYER}!\p"
	.string "Từ lần gặp cậu, tôi đã miệt mài rèn luyện\n"
	.string "lại.\p"
	.string "Tôi vẫn cần thêm một thời gian nữa mới\n"
	.string "có thể mở cửa lại GYM.\p"
	.string "Nhưng khi ấy, hãy đến GYM của tôi để tái\n"
	.string "đấu nhé!$"

MatchCall_Text_Roxanne_PreparingPostGame::
	.string "ROXANNE: Có phải {PLAYER} không?\n"
	.string "Chúc mừng cậu! Tôi đã nghe rất nhiều\l"
	.string "chuyện về cậu!\p"
	.string "Còn tôi vẫn cần thêm một thời gian nữa\n"
	.string "mới có thể mở cửa lại GYM.\p"
	.string "Nhưng khi ấy, hãy đến GYM của tôi để tái\n"
	.string "đấu nhé!$"

MatchCall_Text_Roxanne_RematchReady::
	.string "ROXANNE: {PLAYER}! GYM của tôi đã sẵn\n"
	.string "sàng!\p"
	.string "Khi nào có thể, hãy đến RUSTBORO nhé!$"

MatchCall_Text_Roxanne_PostRematch::
	.string "ROXANNE: Việc từng được chiến đấu với\n"
	.string "cậu tại RUSTBORO GYM là niềm tự hào của\l"
	.string "tôi, {PLAYER}.$"

MatchCall_Text_Brawly_Preparing::
	.string "BRAWLY: Chào, {PLAYER}{KUN}!\p"
	.string "Tớ đã học được rất nhiều từ trận đấu\n"
	.string "giữa chúng ta.\p"
	.string "Tớ định rèn luyện lại từ đầu rồi mở cửa\n"
	.string "GYM.\p"
	.string "Sẽ phải mất một thời gian nữa tớ mới\n"
	.string "sẵn sàng điều hành GYM trở lại.\p"
	.string "Nhưng khi GYM mở cửa, tớ muốn cậu đến\n"
	.string "thách đấu bọn tớ lần nữa.$"

MatchCall_Text_Brawly_PreparingPostGame::
	.string "BRAWLY: Này, {PLAYER}{KUN}! Chúc mừng\n"
	.string "nhé!\p"
	.string "Tin về những chiến công của cậu đã\n"
	.string "theo gió biển truyền tới đây!\p"
	.string "Có vẻ tớ vẫn cần rèn luyện thêm.\p"
	.string "Sẽ phải mất một thời gian nữa tớ mới\n"
	.string "sẵn sàng điều hành GYM trở lại.\p"
	.string "Nhưng khi GYM mở cửa, tớ muốn cậu đến\n"
	.string "thách đấu bọn tớ lần nữa.$"

MatchCall_Text_Brawly_RematchReady::
	.string "BRAWLY: Này, {PLAYER}{KUN}! GYM của\n"
	.string "tớ đã sẵn sàng chiến đấu!\p"
	.string "Cứ trở lại DEWFORD bất cứ lúc nào để\n"
	.string "nhận thử thách mới nhé!$"

MatchCall_Text_Brawly_PostRematch::
	.string "BRAWLY: {PLAYER}{KUN}, tớ nghĩ mình\n"
	.string "sẽ chẳng bao giờ chán chiến đấu với\l"
	.string "cậu!$"

MatchCall_Text_Wattson_Preparing::
	.string "WATTSON: Ồ, là cậu đấy à!\p"
	.string "Sau khi cậu rời đi, ta đã rèn luyện lại\n"
	.string "từ đầu.\p"
	.string "Ta nghĩ mình cần thêm chút thời gian\n"
	.string "nữa mới có thể mở cửa lại GYM.\p"
	.string "Cậu phải chờ đến lúc đó thôi!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson_PreparingPostGame::
	.string "WATTSON: Wahahahaha!\p"
	.string "Cậu thật sự làm được rồi nhỉ? Ta đã\n"
	.string "nghe tin về cậu!\p"
	.string "Có vẻ ta vẫn cần rèn luyện thêm nữa.\p"
	.string "Ta nghĩ mình cần thêm chút thời gian\n"
	.string "nữa mới có thể mở cửa lại GYM.\p"
	.string "Cậu phải chờ đến lúc đó thôi!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson_RematchReady::
	.string "WATTSON: Ồ, là cậu đấy à! GYM của ta đã\n"
	.string "sẵn sàng!\p"
	.string "Cứ đến MAUVILLE bất cứ lúc nào!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson_PostRematch::
	.string "WATTSON: Wahahaha!\p"
	.string "Trận đấu với cậu lúc nào cũng tràn đầy\n"
	.string "sức mạnh điện giật!$"

MatchCall_Text_Flannery_Preparing::
	.string "FLANNERY: {PLAYER}...\p"
	.string "Qua trận đấu giữa chúng ta, tôi đã hiểu\n"
	.string "rõ mình còn non nớt đến mức nào.\p"
	.string "Nhưng tôi chưa chịu thua đâu!\p"
	.string "Tôi sẽ rèn luyện lại rồi mở cửa GYM.\p"
	.string "Khi thời điểm đến, {PLAYER}, hãy\n"
	.string "thách đấu chúng tôi lần nữa nhé.$"

MatchCall_Text_Flannery_PreparingPostGame::
	.string "FLANNERY: A lô, {PLAYER} phải không?\n"
	.string "Chúc mừng cậu!\p"
	.string "Tin về thành công của cậu đã truyền\n"
	.string "đến đây nóng như hơi núi lửa!\p"
	.string "Việc rèn luyện của chúng tôi đang tiến\n"
	.string "triển rất tốt.\p"
	.string "Khi GYM sẵn sàng, một dấu hiệu sẽ xuất\n"
	.string "hiện cạnh tên tôi trong danh sách MATCH\l"
	.string "CALL.$"

MatchCall_Text_Flannery_RematchReady::
	.string "FLANNERY: Ồ, {PLAYER} phải không? GYM\n"
	.string "của chúng tôi đã sẵn sàng!\p"
	.string "Hãy đến LAVARIDGE ngâm suối nước nóng\n"
	.string "rồi nhận lời thách đấu nhé!$"

MatchCall_Text_Flannery_PostRematch::
	.string "FLANNERY: {PLAYER}... Tôi tin chắc\n"
	.string "rằng qua mỗi lần rèn luyện, cậu lại tiến\l"
	.string "bộ hơn.$"

MatchCall_Text_Winona_Preparing::
	.string "WINONA: Xin chào, {PLAYER}!\p"
	.string "Nhờ trận đấu với cậu, tôi đã hiểu được\n"
	.string "những điểm yếu của mình!\p"
	.string "Khi mở cửa lại GYM, tôi sẽ không để mình\n"
	.string "thất bại lần nữa!$"

MatchCall_Text_Winona_PreparingPostGame::
	.string "WINONA: Cậu làm được rồi, {PLAYER}!\p"
	.string "Tin tức về CHAMPION mới đã truyền đến\n"
	.string "tận FORTREE!\p"
	.string "Nhưng... Trận đấu tiếp theo giữa chúng\n"
	.string "ta sẽ không kết thúc như lần trước\l"
	.string "đâu.$"

MatchCall_Text_Winona_RematchReady::
	.string "WINONA: Có phải {PLAYER} không? GYM\n"
	.string "của chúng tôi đã hoạt động trở lại!\p"
	.string "Chúng tôi đang chờ cậu tại FORTREE!$"

MatchCall_Text_Winona_PostRematch::
	.string "WINONA: {PLAYER}... Dù đã thua, đôi\n"
	.string "cánh của tôi sẽ không bao giờ gãy.\p"
	.string "Phải, cũng như cậu chưa bao giờ rời mắt\n"
	.string "khỏi ước mơ của mình.$"

MatchCall_Text_TateLiza_Preparing::
	.string "TATE: Ồ! Cậu là... LIZA: {PLAYER}!\p"
	.string "TATE: Bọn mình đang rèn luyện lại...\n"
	.string "LIZA: Để có thể mở cửa GYM!\p"
	.string "TATE: Khi GYM sẵn sàng... LIZA: Khi GYM\n"
	.string "sẵn sàng...\p"
	.string "TATE: Một dấu hiệu sẽ xuất hiện cạnh\n"
	.string "tên bọn mình... LIZA: Trong danh sách\l"
	.string "MATCH CALL.$"

MatchCall_Text_TateLiza_PreparingPostGame::
	.string "TATE: {PLAYER}, chúc mừng nhé! LIZA:\n"
	.string "{PLAYER}, chúc mừng nhé!\p"
	.string "TATE: Hai bọn mình vẫn đang... LIZA: Tiếp\n"
	.string "tục rèn luyện!\p"
	.string "TATE: Bọn mình cần thêm thời gian,\n"
	.string "nhưng... LIZA: Khi GYM sẵn sàng...\p"
	.string "TATE: Một dấu hiệu sẽ xuất hiện cạnh\n"
	.string "tên bọn mình... LIZA: Trong danh sách\l"
	.string "MATCH CALL.$"

MatchCall_Text_TateLiza_RematchReady::
	.string "TATE: {PLAYER}! LIZA: {PLAYER}!\p"
	.string "TATE: GYM đã sẵn sàng! LIZA: GYM đã sẵn\n"
	.string "sàng!\p"
	.string "TATE: Hãy đến thăm... LIZA: MOSSDEEP bất\n"
	.string "cứ lúc nào nhé!$"

MatchCall_Text_TateLiza_PostRematch::
	.string "TATE: {PLAYER}, trận đấu giữa chúng\n"
	.string "ta... LIZA: Là một trải nghiệm vô giá.\p"
	.string "TATE: Sẽ thật tuyệt nếu... LIZA: Tất cả\n"
	.string "chúng ta lại được chiến đấu!$"

MatchCall_Text_Juan_Preparing::
	.string "JUAN: Hừm... {PLAYER}{KUN}... Đúng\n"
	.string "không nhỉ?\p"
	.string "Trận đấu giữa chúng ta đã gợi ta nhớ\n"
	.string "đến lần đầu gặp WALLACE.\p"
	.string "Có lẽ cậu là một thiên tài rồi sẽ vượt\n"
	.string "qua cả WALLACE!$"

MatchCall_Text_Juan_PreparingPostGame::
	.string "JUAN: Fufu... {PLAYER}{KUN}... Cuối cùng\n"
	.string "cậu đã đạt được mục tiêu.\p"
	.string "Con mắt nhìn người của ta quả không\n"
	.string "nhầm...\p"
	.string "Ta mong được gặp lại cậu, người đã\n"
	.string "chinh phục đỉnh cao của sức mạnh và\l"
	.string "danh vọng.$"

MatchCall_Text_Juan_RematchReady::
	.string "JUAN: Hoho... {PLAYER}{KUN}...\p"
	.string "SOOTOPOLIS GYM của chúng ta cuối cùng\n"
	.string "đã mở cửa trở lại.\p"
	.string "Nếu muốn gặp ta, cậu luôn được chào\n"
	.string "đón bất cứ lúc nào.$"

MatchCall_Text_Juan_PostRematch::
	.string "JUAN: {PLAYER}{KUN}...\p"
	.string "Như khúc nhạc tuyệt mỹ, những trận đấu\n"
	.string "giữa chúng ta ngân lên trong tim ta\l"
	.string "những hợp âm đầy cảm hứng...\p"
	.string "Khi nhắm mắt lại, ta thấy hình bóng cậu\n"
	.string "bay cao theo giai điệu...$"

MatchCall_Text_Sidney::
	.string "SIDNEY: Này, {PLAYER}!\p"
	.string "Nếu muốn đấu với ta lần nữa, cứ trở lại\n"
	.string "POKéMON LEAGUE bất cứ lúc nào cậu\l"
	.string "thích.\p"
	.string "Ta sẽ luôn ở đây! Ta sẽ chờ cậu!$"

MatchCall_Text_Phoebe::
	.string "PHOEBE: Chào, {PLAYER}!\p"
	.string "Khi nào đó cậu quay lại đây nhé?\p"
	.string "Tôi muốn xem mối gắn kết giữa cậu và\n"
	.string "POKéMON đã bền chặt thêm đến mức nào.$"

MatchCall_Text_Glacia::
	.string "GLACIA: Xin chào, {PLAYER}.\p"
	.string "Tôi tin rằng cậu chưa tự mãn với sức\n"
	.string "mạnh của mình chứ?\p"
	.string "Nếu cảm thấy cần làm nguội bớt cảm xúc\n"
	.string "nóng bỏng, hãy đến POKéMON LEAGUE...$"

MatchCall_Text_Drake::
	.string "DRAKE: Giọng nói đó... {PLAYER} phải\n"
	.string "không? Nghe có vẻ cậu vẫn khỏe...\p"
	.string "Ta được biết hiện có một cơ sở tên là\n"
	.string "BATTLE FRONTIER dùng để thử thách kỹ\l"
	.string "năng của các HLV.\p"
	.string "Tuy nhiên, nếu muốn trải nghiệm những\n"
	.string "trận đấu thực sự, không nơi nào thay\l"
	.string "thế được POKéMON LEAGUE!\p"
	.string "Cậu cũng đồng ý chứ, {PLAYER}?$"

MatchCall_Text_Wallace::
	.string "WALLACE: Xin chào, {PLAYER}{KUN}. Cậu\n"
	.string "đã gặp STEVEN chưa?\p"
	.string "Anh ấy... Thật ra vô cùng tài giỏi.\p"
	.string "Tuy nhiên, anh ấy là một người kỳ lạ và\n"
	.string "hiếm khi chiến đấu.\p"
	.string "Thay vào đó, anh ấy thích tìm kiếm\n"
	.string "những viên đá quý hiếm hơn.\p"
	.string "Chắc giờ anh ấy đang đào bới trong\n"
	.string "hang động hay trên ngọn núi lởm chởm\l"
	.string "nào đó.\p"
	.string "Nhưng chính xác thì đá quý hiếm là gì\n"
	.string "nhỉ? Tôi chỉ nghĩ ra được METEORITE...$"

MatchCall_Text_MayRayquazaCall:
	.string "... Bíp!\p"
	.string "MAY: Chào, {PLAYER}{KUN}!\p"
	.string "Vừa nãy tớ mới ở PACIFIDLOG.\p"
	.string "Tớ đã thấy một POKéMON xanh lục khổng\n"
	.string "lồ bay tít trên trời.\p"
	.string "Tớ... Tớ chưa từng thấy thứ gì như\n"
	.string "vậy.\p"
	.string "Không biết đó là gì nhỉ. Chẳng lẽ đây là\n"
	.string "một phát hiện lớn?\p"
	.string "... Tách!$"

MatchCall_Text_BrendanRayquazaCall:
	.string "... Bíp!\p"
	.string "BRENDAN: Này, {PLAYER}! Tớ vừa ở\n"
	.string "PACIFIDLOG.\p"
	.string "Tớ đã thấy một POKéMON xanh lục khổng\n"
	.string "lồ bay ngang qua bầu trời.\p"
	.string "Trước giờ tớ chưa từng thấy cảnh\n"
	.string "tượng nào kỳ diệu đến thế.\p"
	.string "Giá mà cậu cũng được nhìn thấy nó,\n"
	.string "{PLAYER}.\p"
	.string "... Tách!$"

MatchCall_Text_May1::
	.string "MAY: Chào, {PLAYER}{KUN}!\p"
	.string "MR. BRINEY đã nghỉ làm SAILOR, nhưng\n"
	.string "đôi khi tớ vẫn thấy ông ấy ra khơi cùng\l"
	.string "PEEKO cưng.\p"
	.string "Chắc ông ấy vẫn yêu biển lắm.$"

MatchCall_Text_May2::
	.string "MAY: Chào, {PLAYER}{KUN}!\p"
	.string "Cậu biết những thị trấn nhỏ như\n"
	.string "PETALBURG và DEWFORD đều có GYMS chứ?\p"
	.string "Vậy mà chẳng hiểu sao cảng lớn\n"
	.string "SLATEPORT lại không có GYM.\p"
	.string "Khi họ xây được GYM ở đó, tớ nên đăng\n"
	.string "ký làm LEADER.$"

MatchCall_Text_May3::
	.string "MAY: Chào, {PLAYER}{KUN}!\p"
	.string "Cậu nhớ người đàn ông tên CUTTER ở\n"
	.string "RUSTBORO không? Ông ấy có một căn nhà\l"
	.string "ở đó, nhớ chứ?\p"
	.string "Tớ phát hiện em trai ông ấy sống tại\n"
	.string "MAUVILLE.\p"
	.string "Cậu đoán được tên anh ta không?\p"
	.string "...\p"
	.string "ROCK SMASH GUY!$"

MatchCall_Text_May4::
	.string "MAY: {PLAYER}{KUN} phải không?\p"
	.string "RUSTURF TUNNEL... Nó được đặt tên như\n"
	.string "vậy vì nối liền RUSTBORO và VERDANTURF.$"

MatchCall_Text_May5::
	.string "MAY: {PLAYER}{KUN}, cậu khỏe không?\p"
	.string "Giờ tớ đang ở ROUTE 111.\p"
	.string "Tớ định nghỉ chân tại nhà một bà lão.\p"
	.string "Bà ấy sống ngay phía bắc sa mạc.$"

MatchCall_Text_May6::
	.string "MAY: Chào, {PLAYER}{KUN}!\p"
	.string "Cậu biết MIRAGE TOWER trong sa mạc\n"
	.string "không?\p"
	.string "Nghe nói nó bí ẩn lúc ẩn lúc hiện như ảo\n"
	.string "ảnh.\p"
	.string "Tớ ước gì được nhìn thấy nó.$"

MatchCall_Text_May7::
	.string "MAY: {PLAYER}{KUN}, hú hú! Giờ tớ đang\n"
	.string "ở ROUTE 119.\p"
	.string "Ở đây có một con sông lớn và trời\n"
	.string "thường xuyên mưa.\p"
	.string "Tớ ướt sũng rồi!$"

MatchCall_Text_May8::
	.string "MAY: Chào, {PLAYER}{KUN}.\p"
	.string "MT. PYRE là nơi tưởng niệm những\n"
	.string "POKéMON đã qua đời.\p"
	.string "Có lẽ vì vậy mà nơi đó đầy rẫy POKéMON\n"
	.string "GHOST-type!$"

MatchCall_Text_May9::
	.string "MAY: Chào, {PLAYER}{KUN}!\p"
	.string "Tớ đang định đến suối nước nóng ở\n"
	.string "LAVARIDGE.\p"
	.string "Nhưng trên đường đi, gần JAGGED PASS,\n"
	.string "tớ gặp một đám người trông rất khả\l"
	.string "nghi. Không khí lúc đó đáng sợ lắm!$"

MatchCall_Text_May10::
	.string "MAY: Chào, {PLAYER}{KUN}! Cậu xem tin\n"
	.string "tức chưa?\p"
	.string "Nghe nói CAPT. STERN đã phát hiện\n"
	.string "SEAFLOOR CAVERN trong chuyến thám\l"
	.string "hiểm bằng tàu ngầm.$"

MatchCall_Text_May11::
	.string "MAY: Chào, {PLAYER}{KUN}! Cậu không\n"
	.string "thấy tuyệt sao?\p"
	.string "Dù không có thuyền, cậu vẫn có thể dùng\n"
	.string "chiêu thức của POKéMON để vượt biển.\p"
	.string "Cậu biết còn điều này nữa không?\p"
	.string "Có một chiêu thức của POKéMON cho phép\n"
	.string "cậu xuống tận đáy biển đấy.$"

MatchCall_Text_May12::
	.string "MAY: Chào, {PLAYER}{KUN}! Mong mọi\n"
	.string "chuyện vẫn ổn!\p"
	.string "Cậu từng đi trên biển rồi bị chặn, không\n"
	.string "thể sang phía bên kia chưa?\p"
	.string "Hãy lặn sâu xuống nước và men theo các\n"
	.string "rãnh biển.\p"
	.string "Khi sang đến phía bên kia thì nổi lên\n"
	.string "mặt nước. Dễ lắm!$"

MatchCall_Text_May13::
	.string "MAY: Chào, {PLAYER}{KUN}!\p"
	.string "Mọi chuyện thế nào? Cậu đang hoàn\n"
	.string "thiện POKéDEX chứ?\p"
	.string "Tớ nghe đồn ngoài kia có những POKéMON\n"
	.string "siêu cổ đại. Tận ba con cơ!\p"
	.string "Tớ rất muốn được thấy dù chỉ một con...$"

MatchCall_Text_May14::
	.string "MAY: {PLAYER}{KUN}! Tớ nghe lời đồn\n"
	.string "rồi!\p"
	.string "Cậu đã đánh bại SOOTOPOLIS GYM LEADER\n"
	.string "à?\p"
	.string "Vậy nghĩa là cậu chẳng còn cách mục\n"
	.string "tiêu bao xa nữa nhỉ?$"

MatchCall_Text_May15::
	.string "MAY: Ở HOENN chẳng còn một HLV nào\n"
	.string "không biết cậu là ai đâu,\l"
	.string "{PLAYER}{KUN}!\p"
	.string "Khi tớ kể mình là bạn của cậu,\n"
	.string "{PLAYER}{KUN}, ai cũng ngạc nhiên!$"

MatchCall_Text_Brendan1::
	.string "BRENDAN: Này, {PLAYER}!\p"
	.string "MR. BRINEY đã nghỉ làm SAILOR, nhưng\n"
	.string "đôi khi tớ vẫn thấy ông ấy ra khơi cùng\l"
	.string "PEEKO cưng.\p"
	.string "Chắc ông ấy vẫn yêu biển lắm.$"

MatchCall_Text_Brendan2::
	.string "BRENDAN: Này, {PLAYER}!\p"
	.string "Tớ không hiểu tại sao những thị trấn\n"
	.string "nhỏ như PETALBURG và DEWFORD lại có\l"
	.string "GYMS.\p"
	.string "Nhất là khi cảng lớn SLATEPORT lại\n"
	.string "chẳng có GYM.\p"
	.string "Khi họ xây được GYM ở đó, tớ nên đăng\n"
	.string "ký làm LEADER.$"

MatchCall_Text_Brendan3::
	.string "BRENDAN: Này, {PLAYER}!\p"
	.string "Cậu nhớ người tên CUTTER ở RUSTBORO\n"
	.string "không? Ông ấy có một căn nhà ở đó, đúng\l"
	.string "chứ?\p"
	.string "Hóa ra em trai ông ấy sống tại MAUVILLE.\p"
	.string "Cậu đoán được tên anh ta không?\p"
	.string "...\p"
	.string "ROCK SMASH GUY!$"

MatchCall_Text_Brendan4::
	.string "BRENDAN: Giọng này... {PLAYER} phải\n"
	.string "không?\p"
	.string "Họ đặt tên RUSTURF TUNNEL như vậy vì\n"
	.string "nó nối liền RUSTBORO và VERDANTURF.\p"
	.string "Cậu biết chưa?$"

MatchCall_Text_Brendan5::
	.string "BRENDAN: {PLAYER}, thế nào rồi?\p"
	.string "Này, giờ tớ đang ở ROUTE 111.\p"
	.string "Tớ định nghỉ chân tại nhà một bà lão ở\n"
	.string "phía bắc sa mạc.\p"
	.string "Nếu đang ở gần đây, cậu cũng nên ghé\n"
	.string "thăm bà ấy.$"

MatchCall_Text_Brendan6::
	.string "BRENDAN: Này, {PLAYER}!\p"
	.string "Cậu biết MIRAGE TOWER trong sa mạc\n"
	.string "không?\p"
	.string "Nghe nói nó giống như ảo ảnh, chỉ thỉnh\n"
	.string "thoảng mới xuất hiện.\p"
	.string "Tớ muốn được nhìn thấy nó!$"

MatchCall_Text_Brendan7::
	.string "BRENDAN: Ai đấy? Ồ, {PLAYER} à? Biết\n"
	.string "gì không? Giờ tớ đang ở ROUTE 119.\p"
	.string "Ở đây có một con sông lớn và trời mưa\n"
	.string "suốt.\p"
	.string "Tớ ướt đến tận xương rồi!$"

MatchCall_Text_Brendan8::
	.string "BRENDAN: {PLAYER}!\p"
	.string "MT. PYRE là nơi tưởng niệm những\n"
	.string "POKéMON đã qua đời.\p"
	.string "Chắc vì vậy mà nơi đó đầy rẫy POKéMON\n"
	.string "GHOST-type!$"

MatchCall_Text_Brendan9::
	.string "BRENDAN: Chào, {PLAYER}.\p"
	.string "Tớ đang trên đường quay lại suối nước\n"
	.string "nóng ở LAVARIDGE.\p"
	.string "Nhưng gần JAGGED PASS, tớ gặp một đám\n"
	.string "người trông rất đáng ngờ.\p"
	.string "Bọn đáng ghét đó... Tớ nghĩ chúng thuộc\n"
	.string "TEAM MAGMA.$"

MatchCall_Text_Brendan10::
	.string "BRENDAN: Chào, {PLAYER}! Cậu nghe tin\n"
	.string "chưa?\p"
	.string "Nghe nói CAPT. STERN đã phát hiện\n"
	.string "SEAFLOOR CAVERN trong chuyến thám\l"
	.string "hiểm bằng tàu ngầm.$"

MatchCall_Text_Brendan11::
	.string "BRENDAN: Này, {PLAYER}! Cậu không\n"
	.string "thấy quá tuyệt sao?\p"
	.string "Dù không có thuyền, cậu vẫn có thể dùng\n"
	.string "chiêu thức của POKéMON để vượt biển.\p"
	.string "Hơn nữa, còn có một chiêu thức cho\n"
	.string "phép cậu xuống tận đáy biển.\p"
	.string "Đúng là POKéMON có thể làm mọi thứ!$"

MatchCall_Text_Brendan12::
	.string "BRENDAN: Chào, {PLAYER}! Cậu vẫn ổn\n"
	.string "chứ?\p"
	.string "Cậu từng đi trên biển rồi bị chặn, không\n"
	.string "thể sang phía bên kia chưa?\p"
	.string "Hãy lặn sâu xuống nước và men theo các\n"
	.string "rãnh dưới đáy biển.\p"
	.string "Khi sang đến phía bên kia thì nổi lên\n"
	.string "mặt nước. Đơn giản!$"

MatchCall_Text_Brendan13::
	.string "BRENDAN: Này, {PLAYER}!\p"
	.string "Mọi chuyện thế nào? Việc hoàn thiện\n"
	.string "POKéDEX thuận lợi chứ?\p"
	.string "Tớ nghe đồn ngoài kia có những POKéMON\n"
	.string "siêu cổ đại. Không chỉ một mà tận ba\l"
	.string "con!\p"
	.string "Tớ rất muốn bắt được dù chỉ một con...$"

MatchCall_Text_Brendan14::
	.string "BRENDAN: {PLAYER}! Tớ nghe lời đồn\n"
	.string "rồi!\p"
	.string "Cậu đã đánh bại SOOTOPOLIS GYM LEADER\n"
	.string "à? Tuyệt quá!\p"
	.string "Cậu sắp đến đích rồi!$"

MatchCall_Text_Brendan15::
	.string "BRENDAN: Khắp HOENN chẳng có một\n"
	.string "HLV nào không biết cậu là ai đâu,\l"
	.string "{PLAYER}!\p"
	.string "Khi tớ kể mình là bạn của cậu,\n"
	.string "{PLAYER}, ai cũng ghen tị lắm!$"

MatchCall_Text_Wally1::
	.string "WALLY: Ồ, {PLAYER}!\p"
	.string "Sức khỏe và thể lực của tớ đang tốt\n"
	.string "dần lên.\p"
	.string "Mong rằng tớ sớm có thể trở thành một\n"
	.string "HLV như cậu, {PLAYER}!$"

MatchCall_Text_Wally2::
	.string "WALLY: Chào, {PLAYER}!\p"
	.string "Từ khi RUSTURF TUNNEL được thông\n"
	.string "hoàn toàn, WANDA vui lắm!$"

MatchCall_Text_Wally3::
	.string "WALLY: Ồ, {PLAYER}!\p"
	.string "Tớ... Tớ đã rời nhà chú ở VERDANTURF mà\n"
	.string "không nói với ai.\p"
	.string "Không biết chú có nổi giận với tớ\n"
	.string "không...\p"
	.string "{PLAYER}, cậu hiểu cảm giác của tớ\n"
	.string "chứ?$"

MatchCall_Text_Wally4::
	.string "WALLY: {PLAYER} phải không? Tớ là\n"
	.string "WALLY đây!\p"
	.string "Thế giới của các HLV thật tuyệt\n"
	.string "vời!\p"
	.string "Khi có POKéMON bên cạnh, đủ mọi người\n"
	.string "đều đến chào hỏi tớ!\p"
	.string "Cứ như tất cả mọi người đều được\n"
	.string "POKéMON kết nối vậy!$"

MatchCall_Text_Wally5::
	.string "WALLY: {PLAYER} phải không? Tuyệt\n"
	.string "lắm! Con RALTS chúng ta cùng bắt ấy? Nó\l"
	.string "đã tiến hóa rồi, {PLAYER}!\p"
	.string "Có lẽ tớ có tài năng...\p"
	.string "Ồ, nhưng tớ không nên tự mãn như thế!\p"
	.string "Suy cho cùng, POKéMON mới là người\n"
	.string "đáng được khen!$"

MatchCall_Text_Wally6::
	.string "...\p"
	.string "Có vẻ WALLY đang ở ngoài vùng phủ sóng\n"
	.string "của POKéNAV...$"

MatchCall_Text_Wally7::
	.string "WALLY: Ồ, {PLAYER}!\p"
	.string "Trước khi gặp cậu, tớ gần như chẳng\n"
	.string "bao giờ rời khỏi nhà...\p"
	.string "Nhưng giờ tớ đang phiêu lưu cùng\n"
	.string "POKéMON của riêng mình...\p"
	.string "{PLAYER}... Cảm ơn cậu...$"

MatchCall_Text_Scott1::
	.string "SCOTT: Xin chào, {PLAYER}{KUN}!\p"
	.string "Cậu biết POKéMON có thể được tìm thấy\n"
	.string "ở khắp mọi nơi chứ?\p"
	.string "Trên núi, dưới biển hay trong bất kỳ bụi\n"
	.string "cỏ cao nào chẳng hạn?\p"
	.string "Cũng như POKéMON, cậu có thể tìm thấy\n"
	.string "HLV ở khắp mọi nơi.\p"
	.string "Vì vậy, tôi cũng phải tất bật chạy khắp\n"
	.string "nơi. Bận rộn, bận rộn!$"

MatchCall_Text_Scott2::
	.string "SCOTT: Hiện giờ tôi đang ở ROUTE 119.\n"
	.string "Nơi này đầy ắp HLV!\p"
	.string "Có vẻ cỏ cao cũng mọc um tùm khắp nơi.\p"
	.string "Mặc quần đùi đi quanh đây khiến chân\n"
	.string "tôi nhột quá!$"

MatchCall_Text_Scott3::
	.string "SCOTT: Chào, chào, {PLAYER}{KUN}!\p"
	.string "Cậu đã có dịp leo MT. PYRE chưa?\p"
	.string "Nơi đó tưởng niệm những POKéMON đã\n"
	.string "qua đời.\p"
	.string "Đó là nơi mà mọi HLV đều nên một\n"
	.string "lần leo lên tận đỉnh.$"

MatchCall_Text_Scott4::
	.string "SCOTT: Chào, {PLAYER}{KUN}!\p"
	.string "Tôi nghe nói có vài băng nhóm kỳ quặc\n"
	.string "đang gây rắc rối.\p"
	.string "Hình như là TEAM MAGMA và TEAM AQUA.\p"
	.string "Tôi đoán trong số chúng cũng có vài\n"
	.string "HLV tài giỏi.\p"
	.string "...Nhưng nếu chúng chỉ là lũ côn đồ...$"

MatchCall_Text_Scott5::
	.string "SCOTT: Ồ, chào {PLAYER}{KUN}.\p"
	.string "Liệu dưới đáy biển có HLV mạnh\n"
	.string "nào không nhỉ?\p"
	.string "Tôi không thể tự đi kiểm tra. Trước hết\n"
	.string "là vì tôi không biết bơi. Mà tôi cũng\l"
	.string "chẳng nuôi POKéMON...$"

MatchCall_Text_Scott6::
	.string "SCOTT: Chào, chào, {PLAYER}{KUN}!\p"
	.string "Cậu biết mình có thể thách đấu POKéMON\n"
	.string "LEAGUE sau khi thu thập đủ GYM BADGES\l"
	.string "chứ?\p"
	.string "Với tài năng của cậu, trở thành\n"
	.string "CHAMPION không phải giấc mơ viển vông.\p"
	.string "Nhưng cậu có biết không? Còn một nơi\n"
	.string "tuyệt vời hơn nữa.\p"
	.string "Tuy nhiên, hiện giờ tôi chỉ sẵn lòng\n"
	.string "tiết lộ đến thế thôi.\p"
	.string "Cứ mong chờ nó nhé.\p"
	.string "Sau khi cậu chiến thắng POKéMON LEAGUE\n"
	.string "và bước vào HALL OF FAME!$"

MatchCall_Text_Scott7::
	.string "...\p"
	.string "Có vẻ SCOTT đang ở ngoài vùng phủ sóng\n"
	.string "của POKéNAV...$"

MatchCall_Text_Norman1::
	.string "BA: Ở RUSTBORO có một người đàn ông\n"
	.string "mang cái tên kỳ lạ là CUTTER.\p"
	.string "Nếu đang ở gần đó, con nên ghé thăm ông\n"
	.string "ấy.$"

MatchCall_Text_Norman2::
	.string "BA: Hừm... Từng chút một, nhưng rất\n"
	.string "vững chắc, con đang ngày càng mạnh\l"
	.string "hơn, {PLAYER}.\p"
	.string "Con càng mạnh, con càng bay xa và cao\n"
	.string "khỏi mẹ và ba...\p"
	.string "Cảm giác này thật khó diễn tả.$"

MatchCall_Text_Norman3::
	.string "BA: Ra vậy... Con đã thu thập được bốn\n"
	.string "GYM BADGES...\p"
	.string "Giờ không thể tránh né nữa rồi. Chúng\n"
	.string "ta sẽ chiến đấu như ba đã hứa.\p"
	.string "Cứ đến bất cứ lúc nào. Mọi người sẽ\n"
	.string "chờ con!$"

MatchCall_Text_Norman4::
	.string "BA: {PLAYER}! Thỉnh thoảng con nhớ\n"
	.string "về thăm mẹ nhé.\p"
	.string "Ba sẽ ở lại đây và tăng cường rèn\n"
	.string "luyện.\p"
	.string "Con đường chiến đấu vừa sâu thẳm vừa\n"
	.string "khắc nghiệt!$"

MatchCall_Text_Norman5::
	.string "BA: Ồ, chào con, {PLAYER}!\p"
	.string "Gì cơ? MAGMA EMBLEM à? Ba không biết\n"
	.string "nó có ý nghĩa gì.\p"
	.string "Nhưng với cái tên như vậy, có lẽ nó liên\n"
	.string "quan đến núi lửa!$"

MatchCall_Text_Norman_Preparing::
	.string "BA: Hây da! Ha! Hự!\p"
	.string "...Ồ? {PLAYER}!\p"
	.string "Con gọi đúng lúc ba đang huấn luyện\n"
	.string "POKéMON!$"

MatchCall_Text_Norman_PreparingPostGame::
	.string "BA: {PLAYER}!\p"
	.string "Ai mà ngờ con lại trở thành POKéMON\n"
	.string "LEAGUE CHAMPION...\p"
	.string "Được! Ba sẽ không chịu tụt lại đâu!$"

MatchCall_Text_Norman_RematchReady::
	.string "BA: Hửm? {PLAYER} à? Con gọi đúng\n"
	.string "lúc lắm!\p"
	.string "Lần này ba sẽ thách đấu với con.\p"
	.string "Ba đang chờ ở PETALBURG GYM. Cứ đến\n"
	.string "nhận lời thách đấu bất cứ lúc nào!$"

MatchCall_Text_Norman_PostRematch::
	.string "BA: ...Con khiến ba phải kinh ngạc,\n"
	.string "{PLAYER}. Con còn vươn cao đến đâu\l"
	.string "nữa đây?$"

MatchCall_Text_Steven1::
	.string "STEVEN: Chào, {PLAYER}{KUN}!\p"
	.string "Cậu đã đến MAUVILLE chưa?\p"
	.string "Cậu nên ghé BIKE SHOP và lấy một chiếc\n"
	.string "MACH BIKE.\p"
	.string "Sau đó hãy thử khám phá thật kỹ\n"
	.string "GRANITE CAVE.\p"
	.string "Có thể cậu sẽ phát hiện ra điều gì đó\n"
	.string "mới mẻ.$"

MatchCall_Text_Steven2::
	.string "STEVEN: Chào, {PLAYER}{KUN}!\p"
	.string "Cho đến giờ tôi đã gặp rất nhiều\n"
	.string "HLV khác nhau.\p"
	.string "Nhưng cậu là độc nhất. Cậu không giống\n"
	.string "bất kỳ ai.$"

MatchCall_Text_Steven3::
	.string "STEVEN: Chào, {PLAYER}{KUN}!\p"
	.string "Khi phiêu lưu cùng các POKéMON, cậu\n"
	.string "nghĩ gì về chúng?\p"
	.string "Cậu xem chúng là những cộng sự mạnh\n"
	.string "mẽ?\p"
	.string "Hay xem chúng là những người bạn đồng\n"
	.string "hành vui vẻ?\p"
	.string "Ý nghĩa chuyến phiêu lưu sẽ thay đổi\n"
	.string "tùy theo cách cậu nhìn nhận chúng.$"

MatchCall_Text_Steven4::
	.string "STEVEN: Alô? {PLAYER}{KUN} à?\p"
	.string "Tôi đang vướng vào chút rắc rối ở\n"
	.string "SPACE CENTER.\p"
	.string "Xin lỗi, giờ tôi không nói chuyện được.\n"
	.string "Chào nhé!$"

MatchCall_Text_Steven5::
	.string "STEVEN: Ồ! {PLAYER}{KUN}!\p"
	.string "Không cần nói gì nữa. Giờ không còn là\n"
	.string "lúc để nói chuyện.\p"
	.string "Cậu phải tin vào bản thân và làm điều\n"
	.string "đúng đắn.$"

MatchCall_Text_Steven6::
	.string "... ... ... ... ... ...\p"
	.string "Có vẻ cuộc gọi không kết nối được với\n"
	.string "STEVEN...$"

MatchCall_Text_Steven7::
	.string "STEVEN: {PLAYER}{KUN}... Chúc mừng cậu\n"
	.string "đã ghi danh vào HALL OF FAME.\p"
	.string "... ... ... ... ... ... ... ... ... ... ... ...\p"
	.string "Hy vọng chúng ta sẽ lại gặp nhau ở nơi\n"
	.string "nào đó!$"

MatchCall_Text_BirchRegisterCall:
	.string "PROF. BIRCH: Ồ, {PLAYER}{KUN}! Ta đã\n"
	.string "nghe về cháu rồi!\p"
	.string "Có vẻ POKéNAV của cháu đã được nâng\n"
	.string "cấp thêm MATCH CALL.\p"
	.string "Thế thì ta cũng nên đăng ký!\p"
	.string "Nhờ vậy, ngay cả khi cháu đang đi thực\n"
	.string "địa, ta vẫn có thể xem POKéDEX của\l"
	.string "cháu.\p"
	.string "... ... ... ... ... ...$"

MatchCall_Text_RegisteredBirch:
	.string "Đã đăng ký PROF. BIRCH vào POKéNAV.$"

MatchCall_Text_UnusedProfBirch:
	.string "PROF. BIRCH: Khi có cả POKéDEX lẫn\n"
	.string "POKéNAV, việc nghiên cứu POKéMON sẽ\l"
	.string "vui hơn, phải không?$"

MatchCall_Text_MrStone1::
	.string "MR. STONE: Ồ? {PLAYER}{KUN}!\p"
	.string "Cháu gọi được cho ta, vậy là POKéNAV\n"
	.string "đang hoạt động bình thường!\p"
	.string "Sau này sẽ có thêm những người khác\n"
	.string "được đăng ký, nên cháu cũng thử gọi\l"
	.string "cho họ nhé!\p"
	.string "Tốt! Tốt lắm! Trông cháu có vẻ rất vui!\p"
	.string "Hửm... Sao ta biết được ư?\p"
	.string "Vì ta đang nhìn xuống chỗ cháu từ cửa\n"
	.string "sổ văn phòng!\p"
	.string "Wahahaha! Hẹn gặp lại!$"

MatchCall_Text_MrStone2::
	.string "MR. STONE: Ồ? {PLAYER}{KUN}!\p"
	.string "Có chuyện gì vậy? Cháu quên việc vặt\n"
	.string "nho nhỏ ta nhờ rồi sao?\p"
	.string "Ta cần cháu giao lá thư của ta cho\n"
	.string "STEVEN ở DEWFORD.\p"
	.string "Sau đó hãy giao kiện hàng của chúng ta\n"
	.string "cho CAPT. STERN ở SLATEPORT.\p"
	.string "Cháu vẫn nhớ chứ?\p"
	.string "Giờ ta phải đi vì ta là một PRESIDENT\n"
	.string "bận rộn! Tạm biệt!$"

MatchCall_Text_MrStone3::
	.string "MR. STONE: Ồ! {PLAYER}{KUN}!\p"
	.string "À, vậy là cháu đã gặp STEVEN! Thế thì ta\n"
	.string "phải thưởng cho cháu mới được!\p"
	.string "Khi quay lại RUSTBORO, hãy đến gặp ta\n"
	.string "tại văn phòng.\p"
	.string "Ta sẽ chờ cháu!$"

MatchCall_Text_MrStone4::
	.string "MR. STONE: Ồ! {PLAYER}{KUN}!\p"
	.string "Cháu có biết DEVON từng đào RUSTURF\n"
	.string "TUNNEL không?\p"
	.string "Nhưng chúng ta đã dừng công việc để\n"
	.string "bảo vệ các POKéMON trong khu vực.\p"
	.string "Chuyện đó vốn chẳng cần đắn đo.\p"
	.string "Để POKéMON được sống yên bình quan\n"
	.string "trọng hơn sự tiện lợi của chúng ta.$"

MatchCall_Text_MrStone5::
	.string "MR. STONE: Alô, alô, {PLAYER}{KUN}!\p"
	.string "Ta nghe một người ở PETALBURG nói\n"
	.string "cháu là con của NORMAN!\p"
	.string "Thảo nào cháu lại giỏi giang đến vậy!$"

MatchCall_Text_MrStone6::
	.string "MR. STONE: Gì cơ?\p"
	.string "Cháu đã đấu với chính ba mình và đánh\n"
	.string "bại ông ấy sao?\p"
	.string "Thật đáng kinh ngạc!\p"
	.string "Ta không ngờ mình lại kết bạn với một\n"
	.string "người đặc biệt đến thế! Wahaha!$"

MatchCall_Text_MrStone7::
	.string "Xin chào! Đây là DEVON CORPORATI... Ồ,\n"
	.string "chào {PLAYER}!\p"
	.string "Ngài PRESIDENT vừa ở đây cách đây\n"
	.string "không lâu, nhưng giờ đã ra ngoài rồi.\p"
	.string "PRESIDENT của chúng tôi rất bận, nhưng\n"
	.string "có vẻ bạn cũng bận chẳng kém,\l"
	.string "{PLAYER}.$"

MatchCall_Text_MrStone8::
	.string "...Hả? ...Gì cơ?\p"
	.string "GROU... Vâng? ...DON?\p"
	.string "Sóng chập chờn... ...không nghe rõ...\p"
	.string "BZZZZ...$"

MatchCall_Text_MrStone9::
	.string "...Hả? ...Gì cơ?\p"
	.string "Seaflo... Vâng? ...Caver...?\p"
	.string "Sóng chập chờn... ...không nghe rõ...\p"
	.string "BZZZZ...$"

MatchCall_Text_MrStone10::
	.string "MR. STONE: {PLAYER}{KUN}! Ta đây!\p"
	.string "Nghe nói cháu đã dính vào đủ thứ\n"
	.string "chuyện, nhưng vì bận quá nên ta chẳng\l"
	.string "biết cụ thể là gì!\p"
	.string "Dù vậy, ta mong cháu hãy chọn con\n"
	.string "đường mình tin tưởng và bước tiếp.\p"
	.string "Ta sẽ luôn ủng hộ cháu! Bảo trọng nhé!$"

MatchCall_Text_MrStone11::
	.string "MR. STONE: ... ... ... ... ... ... Có phải\n"
	.string "{PLAYER}{KUN} không?\p"
	.string "Giọng cháu tràn đầy tự tin đến mức ta\n"
	.string "không nhận ra ngay!\p"
	.string "Hừm! Lúc nào đó cháu nhất định phải\n"
	.string "đến thăm DEVON nhé!$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global MatchCall_WildBattleText1
	.global MatchCall_WildBattleText2
	.global MatchCall_WildBattleText3
	.global MatchCall_WildBattleText4
	.global MatchCall_WildBattleText5
	.global MatchCall_WildBattleText6
	.global MatchCall_WildBattleText7
	.global MatchCall_WildBattleText8
	.global MatchCall_WildBattleText9
	.global MatchCall_WildBattleText10
	.global MatchCall_WildBattleText11
	.global MatchCall_WildBattleText12
	.global MatchCall_WildBattleText13
	.global MatchCall_WildBattleText14
	.global MatchCall_WildBattleText15
	.global MatchCall_NegativeBattleText1
	.global MatchCall_NegativeBattleText2
	.global MatchCall_NegativeBattleText3
	.global MatchCall_NegativeBattleText4
	.global MatchCall_NegativeBattleText5
	.global MatchCall_NegativeBattleText6
	.global MatchCall_NegativeBattleText7
	.global MatchCall_NegativeBattleText8
	.global MatchCall_NegativeBattleText9
	.global MatchCall_NegativeBattleText10
	.global MatchCall_NegativeBattleText11
	.global MatchCall_NegativeBattleText12
	.global MatchCall_NegativeBattleText13
	.global MatchCall_NegativeBattleText14
	.global MatchCall_PositiveBattleText1
	.global MatchCall_PositiveBattleText2
	.global MatchCall_PositiveBattleText3
	.global MatchCall_PositiveBattleText4
	.global MatchCall_PositiveBattleText5
	.global MatchCall_PositiveBattleText6
	.global MatchCall_PositiveBattleText7
	.global MatchCall_PositiveBattleText8
	.global MatchCall_PositiveBattleText9
	.global MatchCall_PositiveBattleText10
	.global MatchCall_PositiveBattleText11
	.global MatchCall_PositiveBattleText12
	.global MatchCall_PositiveBattleText13
	.global MatchCall_PositiveBattleText14
	.global MatchCall_SameRouteBattleRequestText1
	.global MatchCall_SameRouteBattleRequestText2
	.global MatchCall_SameRouteBattleRequestText3
	.global MatchCall_SameRouteBattleRequestText4
	.global MatchCall_SameRouteBattleRequestText5
	.global MatchCall_SameRouteBattleRequestText6
	.global MatchCall_SameRouteBattleRequestText7
	.global MatchCall_SameRouteBattleRequestText8
	.global MatchCall_SameRouteBattleRequestText9
	.global MatchCall_SameRouteBattleRequestText10
	.global MatchCall_SameRouteBattleRequestText11
	.global MatchCall_SameRouteBattleRequestText12
	.global MatchCall_SameRouteBattleRequestText13
	.global MatchCall_SameRouteBattleRequestText14
	.global MatchCall_DifferentRouteBattleRequestText1
	.global MatchCall_DifferentRouteBattleRequestText2
	.global MatchCall_DifferentRouteBattleRequestText3
	.global MatchCall_DifferentRouteBattleRequestText4
	.global MatchCall_DifferentRouteBattleRequestText5
	.global MatchCall_DifferentRouteBattleRequestText6
	.global MatchCall_DifferentRouteBattleRequestText7
	.global MatchCall_DifferentRouteBattleRequestText8
	.global MatchCall_DifferentRouteBattleRequestText9
	.global MatchCall_DifferentRouteBattleRequestText10
	.global MatchCall_DifferentRouteBattleRequestText11
	.global MatchCall_DifferentRouteBattleRequestText12
	.global MatchCall_DifferentRouteBattleRequestText13
	.global MatchCall_DifferentRouteBattleRequestText14
	.global MatchCall_PersonalizedText1
	.global MatchCall_PersonalizedText2
	.global MatchCall_PersonalizedText3
	.global MatchCall_PersonalizedText4
	.global MatchCall_PersonalizedText5
	.global MatchCall_PersonalizedText6
	.global MatchCall_PersonalizedText7
	.global MatchCall_PersonalizedText8
	.global MatchCall_PersonalizedText9
	.global MatchCall_PersonalizedText10
	.global MatchCall_PersonalizedText11
	.global MatchCall_PersonalizedText12
	.global MatchCall_PersonalizedText13
	.global MatchCall_PersonalizedText14
	.global MatchCall_PersonalizedText15
	.global MatchCall_PersonalizedText16
	.global MatchCall_PersonalizedText17
	.global MatchCall_PersonalizedText18
	.global MatchCall_PersonalizedText19
	.global MatchCall_PersonalizedText20
	.global MatchCall_PersonalizedText21
	.global MatchCall_PersonalizedText22
	.global MatchCall_PersonalizedText23
	.global MatchCall_PersonalizedText24
	.global MatchCall_PersonalizedText25
	.global MatchCall_PersonalizedText26
	.global MatchCall_PersonalizedText27
	.global MatchCall_PersonalizedText28
	.global MatchCall_PersonalizedText29
	.global MatchCall_PersonalizedText30
	.global MatchCall_PersonalizedText31
	.global MatchCall_PersonalizedText32
	.global MatchCall_PersonalizedText33
	.global MatchCall_PersonalizedText34
	.global MatchCall_PersonalizedText35
	.global MatchCall_PersonalizedText36
	.global MatchCall_PersonalizedText37
	.global MatchCall_PersonalizedText38
	.global MatchCall_PersonalizedText39
	.global MatchCall_PersonalizedText40
	.global MatchCall_PersonalizedText41
	.global MatchCall_PersonalizedText42
	.global MatchCall_PersonalizedText43
	.global MatchCall_PersonalizedText44
	.global MatchCall_PersonalizedText45
	.global MatchCall_PersonalizedText46
	.global MatchCall_PersonalizedText47
	.global MatchCall_PersonalizedText48
	.global MatchCall_PersonalizedText49
	.global MatchCall_PersonalizedText50
	.global MatchCall_PersonalizedText51
	.global MatchCall_PersonalizedText52
	.global MatchCall_PersonalizedText53
	.global MatchCall_PersonalizedText54
	.global MatchCall_PersonalizedText55
	.global MatchCall_PersonalizedText56
	.global MatchCall_PersonalizedText57
	.global MatchCall_PersonalizedText58
	.global MatchCall_PersonalizedText59
	.global MatchCall_PersonalizedText60
	.global MatchCall_PersonalizedText61
	.global MatchCall_PersonalizedText62
	.global MatchCall_PersonalizedText63
	.global MatchCall_PersonalizedText64
	.global MatchCall_BattleFrontierStreakText1
	.global MatchCall_BattleFrontierStreakText2
	.global MatchCall_BattleFrontierStreakText3
	.global MatchCall_BattleFrontierStreakText4
	.global MatchCall_BattleFrontierStreakText5
	.global MatchCall_BattleFrontierStreakText6
	.global MatchCall_BattleFrontierStreakText7
	.global MatchCall_BattleFrontierStreakText8
	.global MatchCall_BattleFrontierStreakText9
	.global MatchCall_BattleFrontierStreakText10
	.global MatchCall_BattleFrontierStreakText11
	.global MatchCall_BattleFrontierStreakText12
	.global MatchCall_BattleFrontierStreakText13
	.global MatchCall_BattleFrontierStreakText14
	.global MatchCall_BattleFrontierRecordStreakText1
	.global MatchCall_BattleFrontierRecordStreakText2
	.global MatchCall_BattleFrontierRecordStreakText3
	.global MatchCall_BattleFrontierRecordStreakText4
	.global MatchCall_BattleFrontierRecordStreakText5
	.global MatchCall_BattleFrontierRecordStreakText6
	.global MatchCall_BattleFrontierRecordStreakText7
	.global MatchCall_BattleFrontierRecordStreakText8
	.global MatchCall_BattleFrontierRecordStreakText9
	.global MatchCall_BattleFrontierRecordStreakText10
	.global MatchCall_BattleFrontierRecordStreakText11
	.global MatchCall_BattleFrontierRecordStreakText12
	.global MatchCall_BattleFrontierRecordStreakText13
	.global MatchCall_BattleFrontierRecordStreakText14
	.global MatchCall_BattleDomeText1
	.global MatchCall_BattleDomeText2
	.global MatchCall_BattleDomeText3
	.global MatchCall_BattleDomeText4
	.global MatchCall_BattleDomeText5
	.global MatchCall_BattleDomeText6
	.global MatchCall_BattleDomeText7
	.global MatchCall_BattleDomeText8
	.global MatchCall_BattleDomeText9
	.global MatchCall_BattleDomeText10
	.global MatchCall_BattleDomeText11
	.global MatchCall_BattleDomeText12
	.global MatchCall_BattleDomeText13
	.global MatchCall_BattleDomeText14
	.global MatchCall_BattlePikeText1
	.global MatchCall_BattlePikeText2
	.global MatchCall_BattlePikeText3
	.global MatchCall_BattlePikeText4
	.global MatchCall_BattlePikeText5
	.global MatchCall_BattlePikeText6
	.global MatchCall_BattlePikeText7
	.global MatchCall_BattlePikeText8
	.global MatchCall_BattlePikeText9
	.global MatchCall_BattlePikeText10
	.global MatchCall_BattlePikeText11
	.global MatchCall_BattlePikeText12
	.global MatchCall_BattlePikeText13
	.global MatchCall_BattlePikeText14
	.global MatchCall_BattlePyramidText1
	.global MatchCall_BattlePyramidText2
	.global MatchCall_BattlePyramidText3
	.global MatchCall_BattlePyramidText4
	.global MatchCall_BattlePyramidText5
	.global MatchCall_BattlePyramidText6
	.global MatchCall_BattlePyramidText7
	.global MatchCall_BattlePyramidText8
	.global MatchCall_BattlePyramidText9
	.global MatchCall_BattlePyramidText10
	.global MatchCall_BattlePyramidText11
	.global MatchCall_BattlePyramidText12
	.global MatchCall_BattlePyramidText13
	.global MatchCall_BattlePyramidText14
	.global MatchCall_Text_Mom1
	.global MatchCall_Text_Mom2
	.global MatchCall_Text_Mom3
	.global MatchCall_Text_Roxanne_Preparing
	.global MatchCall_Text_Roxanne_PreparingPostGame
	.global MatchCall_Text_Roxanne_RematchReady
	.global MatchCall_Text_Roxanne_PostRematch
	.global MatchCall_Text_Brawly_Preparing
	.global MatchCall_Text_Brawly_PreparingPostGame
	.global MatchCall_Text_Brawly_RematchReady
	.global MatchCall_Text_Brawly_PostRematch
	.global MatchCall_Text_Wattson_Preparing
	.global MatchCall_Text_Wattson_PreparingPostGame
	.global MatchCall_Text_Wattson_RematchReady
	.global MatchCall_Text_Wattson_PostRematch
	.global MatchCall_Text_Flannery_Preparing
	.global MatchCall_Text_Flannery_PreparingPostGame
	.global MatchCall_Text_Flannery_RematchReady
	.global MatchCall_Text_Flannery_PostRematch
	.global MatchCall_Text_Winona_Preparing
	.global MatchCall_Text_Winona_PreparingPostGame
	.global MatchCall_Text_Winona_RematchReady
	.global MatchCall_Text_Winona_PostRematch
	.global MatchCall_Text_TateLiza_Preparing
	.global MatchCall_Text_TateLiza_PreparingPostGame
	.global MatchCall_Text_TateLiza_RematchReady
	.global MatchCall_Text_TateLiza_PostRematch
	.global MatchCall_Text_Juan_Preparing
	.global MatchCall_Text_Juan_PreparingPostGame
	.global MatchCall_Text_Juan_RematchReady
	.global MatchCall_Text_Juan_PostRematch
	.global MatchCall_Text_Sidney
	.global MatchCall_Text_Phoebe
	.global MatchCall_Text_Glacia
	.global MatchCall_Text_Drake
	.global MatchCall_Text_Wallace
	.global MatchCall_Text_MayRayquazaCall
	.global MatchCall_Text_BrendanRayquazaCall
	.global MatchCall_Text_May1
	.global MatchCall_Text_May2
	.global MatchCall_Text_May3
	.global MatchCall_Text_May4
	.global MatchCall_Text_May5
	.global MatchCall_Text_May6
	.global MatchCall_Text_May7
	.global MatchCall_Text_May8
	.global MatchCall_Text_May9
	.global MatchCall_Text_May10
	.global MatchCall_Text_May11
	.global MatchCall_Text_May12
	.global MatchCall_Text_May13
	.global MatchCall_Text_May14
	.global MatchCall_Text_May15
	.global MatchCall_Text_Brendan1
	.global MatchCall_Text_Brendan2
	.global MatchCall_Text_Brendan3
	.global MatchCall_Text_Brendan4
	.global MatchCall_Text_Brendan5
	.global MatchCall_Text_Brendan6
	.global MatchCall_Text_Brendan7
	.global MatchCall_Text_Brendan8
	.global MatchCall_Text_Brendan9
	.global MatchCall_Text_Brendan10
	.global MatchCall_Text_Brendan11
	.global MatchCall_Text_Brendan12
	.global MatchCall_Text_Brendan13
	.global MatchCall_Text_Brendan14
	.global MatchCall_Text_Brendan15
	.global MatchCall_Text_Wally1
	.global MatchCall_Text_Wally2
	.global MatchCall_Text_Wally3
	.global MatchCall_Text_Wally4
	.global MatchCall_Text_Wally5
	.global MatchCall_Text_Wally6
	.global MatchCall_Text_Wally7
	.global MatchCall_Text_Scott1
	.global MatchCall_Text_Scott2
	.global MatchCall_Text_Scott3
	.global MatchCall_Text_Scott4
	.global MatchCall_Text_Scott5
	.global MatchCall_Text_Scott6
	.global MatchCall_Text_Scott7
	.global MatchCall_Text_Norman1
	.global MatchCall_Text_Norman2
	.global MatchCall_Text_Norman3
	.global MatchCall_Text_Norman4
	.global MatchCall_Text_Norman5
	.global MatchCall_Text_Norman_Preparing
	.global MatchCall_Text_Norman_PreparingPostGame
	.global MatchCall_Text_Norman_RematchReady
	.global MatchCall_Text_Norman_PostRematch
	.global MatchCall_Text_Steven1
	.global MatchCall_Text_Steven2
	.global MatchCall_Text_Steven3
	.global MatchCall_Text_Steven4
	.global MatchCall_Text_Steven5
	.global MatchCall_Text_Steven6
	.global MatchCall_Text_Steven7
	.global MatchCall_Text_BirchRegisterCall
	.global MatchCall_Text_RegisteredBirch
	.global MatchCall_Text_UnusedProfBirch
	.global MatchCall_Text_MrStone1
	.global MatchCall_Text_MrStone2
	.global MatchCall_Text_MrStone3
	.global MatchCall_Text_MrStone4
	.global MatchCall_Text_MrStone5
	.global MatchCall_Text_MrStone6
	.global MatchCall_Text_MrStone7
	.global MatchCall_Text_MrStone8
	.global MatchCall_Text_MrStone9
	.global MatchCall_Text_MrStone10
	.global MatchCall_Text_MrStone11
@ END GENERATED LOCALIZATION EXPORTS
