@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
	.string "đẹp quá!$"

GiddyText_SoDarling::
	.string "đáng yêu quá!$"

GiddyText_SoRelaxed::
	.string "thư thái quá!$"

GiddyText_SoSunny::
	.string "rạng rỡ quá!$"

GiddyText_SoDesirable::
	.string "hấp dẫn quá!$"

GiddyText_SoExciting::
	.string "thú vị quá!$"

GiddyText_SoAmusing::
	.string "vui nhộn quá!$"

GiddyText_SoMagical::
	.string "kỳ diệu quá!$"

GiddyText_Is::
	.string "thật là$"

GiddyText_DontYouAgree::
	.string "Bạn không thấy vậy sao?$"

GiddyText_ISoWantToGoOnAVacation::
	.string "Tôi muốn đi nghỉ mát quá. Bạn có biết\n"
	.string "nơi nào đẹp không?$"

GiddyText_IBoughtCrayonsWith120Colors::
	.string "Tôi đã mua một hộp bút sáp có 120 màu!\n"
	.string "Bạn không thấy tuyệt sao?$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.string "Giá mà chúng ta có thể bồng bềnh bay đi\n"
	.string "trên một đám mây bong bóng thì tuyệt\l"
	.string "biết bao?$"

GiddyText_WhenYouWriteOnASandyBeach::
	.string "Những chữ viết trên bãi cát sẽ bị sóng\n"
	.string "cuốn trôi. Điều đó khiến tôi buồn.$"

GiddyText_WhatsTheBottomOfTheSeaLike::
	.string "Đáy biển trông như thế nào nhỉ? Tôi rất\n"
	.string "muốn được đến đó dù chỉ một lần!$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.string "Khi nhìn thấy hoàng hôn, bạn có muốn\n"
	.string "trở về nhà không?$"

GiddyText_LyingBackInTheGreenGrass::
	.string "Nằm ngửa trên thảm cỏ xanh... Ôi, dễ chịu\n"
	.string "ơi là dễ chịu!$"

GiddyText_SecretBasesAreSoWonderful::
	.string "SECRET BASES tuyệt vời quá! Bạn không\n"
	.string "thấy háo hức sao?$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global GiddyText_SoPretty
	.global GiddyText_SoDarling
	.global GiddyText_SoRelaxed
	.global GiddyText_SoSunny
	.global GiddyText_SoDesirable
	.global GiddyText_SoExciting
	.global GiddyText_SoAmusing
	.global GiddyText_SoMagical
	.global GiddyText_Is
	.global GiddyText_DontYouAgree
	.global GiddyText_ISoWantToGoOnAVacation
	.global GiddyText_IBoughtCrayonsWith120Colors
	.global GiddyText_WouldntItBeNiceIfWeCouldFloat
	.global GiddyText_WhenYouWriteOnASandyBeach
	.global GiddyText_WhatsTheBottomOfTheSeaLike
	.global GiddyText_WhenYouSeeTheSettingSunDoesIt
	.global GiddyText_LyingBackInTheGreenGrass
	.global GiddyText_SecretBasesAreSoWonderful
@ END GENERATED LOCALIZATION EXPORTS
