MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "Chiêu thức này chỉ có thể được học\n"
	.string "một lần. Bạn đồng ý chứ?$"

MoveTutor_Text_SwaggerTeach:
	.string "Hê! POKéMON của tôi đúng là số một! Nó\n"
	.string "ngầu hơn mọi POKéMON khác!\p"
	.string "Tôi cứ vênh váo huênh hoang như thế\n"
	.string "thì bị CHỦ TỊCH mắng cho một trận.\p"
	.string "Thế là tôi hết dám vênh váo.\p"
	.string "Nếu thích, tôi sẽ dạy chiêu SWAGGER cho\n"
	.string "một POKéMON của bạn.$"

MoveTutor_Text_SwaggerDeclined:
	.string "Gì, không à? Bạn không hòa mình vào\n"
	.string "không khí được sao?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "Được rồi, POKéMON nào muốn học cách\n"
	.string "dùng SWAGGER?$"

MoveTutor_Text_SwaggerTaught:
	.string "Từ giờ tôi sẽ chỉ khen POKéMON của\n"
	.string "mình thôi, không vênh váo nữa.$"

MoveTutor_Text_RolloutTeach:
	.string "Bạn có biết từ đây cứ đi thẳng theo\n"
	.string "hướng đó thì có thể đi rất xa không?\p"
	.string "Có khi tôi còn lăn được tới tận đó.\p"
	.string "Bạn nghĩ POKéMON của mình cũng muốn\n"
	.string "lăn theo không?\p"
	.string "Nếu thích, tôi có thể dạy một con chiêu\n"
	.string "ROLLOUT.$"

MoveTutor_Text_RolloutDeclined:
	.string "Không cần phải ngại đâu. Cùng lăn nào!$"

MoveTutor_Text_RolloutWhichMon:
	.string "Ehehe, được thôi! Giá mà POKéMON đó\n"
	.string "trông giống tôi thì tuyệt.$"

MoveTutor_Text_RolloutTaught:
	.string "Lăn lộn trên cỏ khiến tôi vui lắm. Nào,\n"
	.string "cùng lăn thôi!$"

MoveTutor_Text_FuryCutterTeach:
	.string "Có một chiêu thức sẽ mạnh dần lên khi\n"
	.string "được sử dụng liên tiếp.\p"
	.string "Đó là chiêu hệ BUG, và nó ngầu kinh\n"
	.string "khủng.\p"
	.string "Nó tên là FURY CUTTER. Bạn muốn tôi dạy\n"
	.string "nó cho một POKéMON không?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "Chúng ta không cùng tần số rồi.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Tuyệt! Cho tôi xem POKéMON mà tôi nên\n"
	.string "dạy nào.$"

MoveTutor_Text_FuryCutterTaught:
	.string "Tôi thấy hồi hộp lắm khi chờ xem chiêu\n"
	.string "thức có tiếp tục đánh trúng liên tiếp\l"
	.string "hay không!$"

MoveTutor_MimicTeach:
	.string "Ôi, người trẻ tuổi!\p"
	.string "Ta cũng là người trẻ, nhưng ta bắt\n"
	.string "chước cách ăn mặc và nói năng của các\l"
	.string "bậc cao niên trong thị trấn này.\p"
	.string "Thế nào, người trẻ tuổi? Nếu ta đề nghị\n"
	.string "dạy chiêu MIMIC, cậu có đồng ý chăng?$"

MoveTutor_MimicDeclined:
	.string "Ôi, chán quá! Ta muốn dạy MIMIC cho\n"
	.string "POKéMON của cậu mà!$"

MoveTutor_Text_MimicWhichMon:
	.string "Khà khà! Vậy ta sẽ dạy! Hãy cho ta xem\n"
	.string "POKéMON mà cậu muốn ta truyền dạy.$"

MoveTutor_Text_MimicTaught:
	.string "MIMIC là một chiêu thức vô cùng thâm\n"
	.string "sâu.\p"
	.string "Liệu cậu có thể thi triển nó hoàn hảo\n"
	.string "như ta không...?$"

MoveTutor_Text_MetronomeTeach:
	.string "Tôi muốn đủ thứ! Nhưng đã tiêu hết tiền\n"
	.string "tiêu vặt rồi...\p"
	.string "Giá mà có phép thuật khiến tiền xuất\n"
	.string "hiện khi ta ngọ nguậy một ngón tay thì\l"
	.string "tuyệt nhỉ?\p"
	.string "Nếu muốn, tôi có thể dạy POKéMON của\n"
	.string "bạn chiêu METRONOME.\p"
	.string "Tiền sẽ không xuất hiện, nhưng POKéMON\n"
	.string "của bạn sẽ ngọ nguậy ngón tay. Đồng ý\l"
	.string "chứ?$"

MoveTutor_Text_MetronomeDeclined:
	.string "Được thôi. Nếu đổi ý thì cứ quay lại\n"
	.string "gặp tôi.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "Được! Tôi sẽ dạy! Tôi nên dạy POKéMON\n"
	.string "nào?$"

MoveTutor_Text_MetronomeTaught:
	.string "Khi một POKéMON lắc ngón tay như chiếc\n"
	.string "METRONOME, đủ chuyện hay ho sẽ xảy ra.\p"
	.string "Giá mà chúng ta cũng dùng được thì\n"
	.string "tuyệt nhỉ?$"

MoveTutor_Text_SleepTalkTeach:
	.string "Hừ! Vợ tôi phải nhờ HIDDEN POWER để\n"
	.string "giữ mình tỉnh táo.\p"
	.string "Bà ấy cứ ngủ một giấc như tôi rồi SLEEP\n"
	.string "TALK là được.\p"
	.string "Thay vào đó, tôi có thể dạy POKéMON của\n"
	.string "bạn cách SLEEP TALK. Có hứng thú\l"
	.string "không?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Ồ, được thôi, được thôi. Bạn cũng muốn\n"
	.string "dùng HIDDEN POWER để thức chứ gì...$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "À, một đứa trẻ biết trân trọng đấy! Tôi\n"
	.string "nên dạy POKéMON nào?$"

MoveTutor_Text_SleepTalkTaught:
	.string "Tôi chưa bao giờ làm đúng trò đồng xu\n"
	.string "của vợ mình.\p"
	.string "Giá mà tôi làm đúng được, ngay cả trong\n"
	.string "lúc SLEEP TALK, thì vui biết mấy...$"

MoveTutor_Text_SubstituteTeach:
	.string "Khi nhìn thế giới rộng lớn từ trên mái\n"
	.string "nhà này...\p"
	.string "Tôi nghĩ sẽ thật tuyệt nếu có nhiều hơn\n"
	.string "một tôi, để tôi có thể tận hưởng đủ\l"
	.string "kiểu cuộc đời.\p"
	.string "Tất nhiên là không thể rồi. Hì hì...\p"
	.string "Tôi biết rồi! Bạn có muốn cho một\n"
	.string "POKéMON học SUBSTITUTE không?$"

MoveTutor_Text_SubstituteDeclined:
	.string "Ồ, không à?\p"
	.string "POKéMON có thể dùng chiêu đó để tạo ra\n"
	.string "một bản sao của chính mình đấy.$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Hì hì... Bạn muốn tôi dạy SUBSTITUTE cho\n"
	.string "POKéMON nào?$"

MoveTutor_Text_SubstituteTaught:
	.string "Con người chúng ta nên tận hưởng cuộc\n"
	.string "đời mình hết mức!\p"
	.string "Tôi mong bạn cũng sẽ sống như vậy!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "Tôi hết chịu nổi rồi!\p"
	.string "Hoàn toàn vô vọng!\p"
	.string "Tôi là HLV hệ FIGHTING, nên dù cố\n"
	.string "đến đâu cũng không thể thắng tại\l"
	.string "MOSSDEEP GYM!\p"
	.string "Aaargh! Đấm! Đấm! Đấm! Đấm! Đấm! Đấm!\p"
	.string "Gì chứ, đừng nhìn tôi như vậy! Tôi chỉ\n"
	.string "đang đấm xuống đất thôi!\p"
	.string "Hay là bạn muốn tôi dạy POKéMON của bạn\n"
	.string "DYNAMICPUNCH?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Chết tiệt! Đến bạn cũng chế giễu tôi\n"
	.string "sao? Đấm! Đấm! Đấm!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "Gì cơ? Bạn muốn thật à? Bạn tốt quá!\n"
	.string "Tôi nên dạy POKéMON nào?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "Tôi muốn bạn dùng DYNAMICPUNCH đó để\n"
	.string "chiến thắng tại MOSSDEEP GYM!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Thở dài...\p"
	.string "GYM LEADER của SOOTOPOLIS thật sự vừa\n"
	.string "đáng yêu vừa đáng ngưỡng mộ.\p"
	.string "Nhưng như vậy cũng có nghĩa là tôi có\n"
	.string "rất nhiều tình địch.\p"
	.string "Sức hút của anh ấy sắc bén như\n"
	.string "DOUBLE-EDGE. Tôi còn chẳng khiến anh\l"
	.string "ấy để mắt tới.\p"
	.string "Xin hãy để tôi dạy POKéMON của bạn\n"
	.string "chiêu DOUBLE-EDGE!$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Ồ... Đến bạn cũng từ chối tôi...$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "Được rồi, tôi nên dạy DOUBLE-EDGE cho\n"
	.string "POKéMON nào?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "Tôi sẽ không sống vì tình yêu nữa! Tôi\n"
	.string "sẽ trở nên mạnh mẽ!$"

MoveTutor_Text_ExplosionTeach:
	.string "Tôi không định chôn chân mãi ở chốn quê\n"
	.string "mùa chẳng có tương lai này.\p"
	.string "Cứ chờ xem, tôi sẽ lên thành phố và nổi\n"
	.string "đình nổi đám.\p"
	.string "Nghiêm túc đấy, tôi sẽ tạo nên một cơn\n"
	.string "EXPLOSION danh tiếng!\p"
	.string "Nếu đã nghe lỏm rồi, tôi sẵn lòng dạy\n"
	.string "EXPLOSION cho POKéMON của bạn!$"

MoveTutor_Text_ExplosionDeclined:
	.string "Gaah! Bạn từ chối tôi vì tôi sống ở\n"
	.string "vùng quê sao?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Được! Vậy EXPLOSION nhé! POKéMON nào\n"
	.string "muốn nổ tung đây?$"

MoveTutor_Text_ExplosionTaught:
	.string "Bao năm qua, tôi đã dạy POKéMON cách\n"
	.string "dùng EXPLOSION, nhưng ngọn EXPLOSION\l"
	.string "của chính tôi vẫn chưa bùng lên...\p"
	.string "Có lẽ vì sâu thẳm trong lòng, tôi vẫn\n"
	.string "muốn ở lại đây hơn...$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce
	.global MoveTutor_Text_SwaggerTeach
	.global MoveTutor_Text_SwaggerDeclined
	.global MoveTutor_Text_SwaggerWhichMon
	.global MoveTutor_Text_SwaggerTaught
	.global MoveTutor_Text_RolloutTeach
	.global MoveTutor_Text_RolloutDeclined
	.global MoveTutor_Text_RolloutWhichMon
	.global MoveTutor_Text_RolloutTaught
	.global MoveTutor_Text_FuryCutterTeach
	.global MoveTutor_Text_FuryCutterDeclined
	.global MoveTutor_Text_FuryCutterWhichMon
	.global MoveTutor_Text_FuryCutterTaught
	.global MoveTutor_MimicTeach
	.global MoveTutor_MimicDeclined
	.global MoveTutor_Text_MimicWhichMon
	.global MoveTutor_Text_MimicTaught
	.global MoveTutor_Text_MetronomeTeach
	.global MoveTutor_Text_MetronomeDeclined
	.global MoveTutor_Text_MetronomeWhichMon
	.global MoveTutor_Text_MetronomeTaught
	.global MoveTutor_Text_SleepTalkTeach
	.global MoveTutor_Text_SleepTalkDeclined
	.global MoveTutor_Text_SleepTalkWhichMon
	.global MoveTutor_Text_SleepTalkTaught
	.global MoveTutor_Text_SubstituteTeach
	.global MoveTutor_Text_SubstituteDeclined
	.global MoveTutor_Text_SubstituteWhichMon
	.global MoveTutor_Text_SubstituteTaught
	.global MoveTutor_Text_DynamicPunchTeach
	.global MoveTutor_Text_DynamicPunchDeclined
	.global MoveTutor_Text_DynamicPunchWhichMon
	.global MoveTutor_Text_DynamicPunchTaught
	.global MoveTutor_Text_DoubleEdgeTeach
	.global MoveTutor_Text_DoubleEdgeDeclined
	.global MoveTutor_Text_DoubleEdgeWhichMon
	.global MoveTutor_Text_DoubleEdgeTaught
	.global MoveTutor_Text_ExplosionTeach
	.global MoveTutor_Text_ExplosionDeclined
	.global MoveTutor_Text_ExplosionWhichMon
	.global MoveTutor_Text_ExplosionTaught
@ END GENERATED LOCALIZATION EXPORTS
