gText_ObtainedTheItem::
	.string "Nhận được {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "TÚI ĐỒ đã đầy…$"

gText_PutItemInPocket::
	.string "{PLAYER} đã cất {STR_VAR_2}\n"
	.string "vào {STR_VAR_3} POCKET.$"

gText_PutItemInPC::
	.string "TÚI ĐỒ đã đầy, nên {PLAYER}\n"
	.string "gửi {STR_VAR_2} vào PC.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} tìm thấy {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "Tiếc quá!\n"
	.string "TÚI ĐỒ đã đầy…$"

gText_TooBadBagAndPCAreFull::
	.string "Tiếc quá!\n"
	.string "TÚI ĐỒ và PC đều đã đầy…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} đã cất {STR_VAR_2}\n"
	.string "vào TÚI ĐỒ.$"

gText_ObtainedTheDecor::
	.string "Nhận được {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "Tiếc quá! Không còn chỗ để cất\n"
	.string "thêm {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "Đã chuyển {STR_VAR_2}\n"
	.string "vào PC.$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global gText_ObtainedTheItem
	.global gText_TheBagIsFull
	.global gText_PutItemInPocket
	.global gText_PutItemInPC
	.global gText_PlayerFoundOneItem
	.global gText_TooBadBagIsFull
	.global gText_TooBadBagAndPCAreFull
	.global gText_PlayerPutItemInBag
	.global gText_ObtainedTheDecor
	.global gText_NoRoomLeftForAnother
	.global gText_TheDecorWasTransferredToThePC
@ END GENERATED LOCALIZATION EXPORTS
