Text_BootUpPC:
	.string "{PLAYER} đã khởi động PC.$"

gText_WhichPCShouldBeAccessed::
	.string "Bạn muốn truy cập PC nào?$"

gText_AccessedSomeonesPC::
	.string "Đã truy cập SOMEONE'S PC.$"

gText_StorageSystemOpened::
	.string "POKéMON Storage System đã mở.$"

gText_AccessedPlayersPC::
	.string "Đã truy cập PC của {PLAYER}.$"

gText_AccessedLanettesPC::
	.string "Đã truy cập PC của LANETTE.$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global Text_BootUpPC
	.global gText_WhichPCShouldBeAccessed
	.global gText_AccessedSomeonesPC
	.global gText_StorageSystemOpened
	.global gText_AccessedPlayersPC
	.global gText_AccessedLanettesPC
@ END GENERATED LOCALIZATION EXPORTS
