gText_PkmnTransferredSomeonesPC::
	.string "{STR_VAR_2} đã được chuyển đến\n"
	.string "SOMEONE'S PC.\p"
	.string "Nó được đặt vào\n"
	.string "BOX “{STR_VAR_1}.”$"

gText_PkmnTransferredLanettesPC::
	.string "{STR_VAR_2} đã được chuyển đến\n"
	.string "LANETTE'S PC.\p"
	.string "Nó được đặt vào\n"
	.string "BOX “{STR_VAR_1}.”$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "BOX “{STR_VAR_3}” trong\n"
	.string "SOMEONE'S PC đã đầy.\p"
	.string "{STR_VAR_2} được chuyển đến\n"
	.string "BOX “{STR_VAR_1}.”$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "BOX “{STR_VAR_3}” trong\n"
	.string "LANETTE'S PC đã đầy.\p"
	.string "{STR_VAR_2} được chuyển đến\n"
	.string "BOX “{STR_VAR_1}.”$"

gText_PkmnSentToPCAfterCatch::
	.string "{STR_VAR_2} đã được gửi đến\n"
	.string "PC của {B_PC_CREATOR_NAME}.\p"
	.string "Nó được đặt vào\n"
	.string "BOX “{STR_VAR_1}.”$"

gText_NoMoreRoomForPokemon::
	.string "Không còn chỗ cho POKéMON!\p"
	.string "Tất cả POKéMON BOXES đều đã đầy!$"

gText_NicknameThisPokemon::
	.string "Bạn có muốn đặt tên cho\n"
	.string "{STR_VAR_1} này không?$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global gText_PkmnTransferredSomeonesPC
	.global gText_PkmnTransferredLanettesPC
	.global gText_PkmnTransferredSomeonesPCBoxFull
	.global gText_PkmnTransferredLanettesPCBoxFull
	.global gText_PkmnSentToPCAfterCatch
	.global gText_NoMoreRoomForPokemon
	.global gText_NicknameThisPokemon
@ END GENERATED LOCALIZATION EXPORTS
