gText_WouldYouLikeToRestYourPkmn::
	.string "Xin chào! Chào mừng bạn đến với\n"
	.string "POKéMON CENTER.\p"
	.string "Chúng tôi sẽ hồi phục POKéMON của bạn\n"
	.string "về trạng thái khỏe mạnh.\p"
	.string "Bạn có muốn để POKéMON nghỉ ngơi\n"
	.string "một lát không?$"

gText_IllTakeYourPkmn::
	.string "Được rồi, xin gửi POKéMON cho tôi\n"
	.string "trong giây lát.$"

gText_RestoredPkmnToFullHealth::
	.string "Cảm ơn bạn đã chờ.\p"
	.string "POKéMON của bạn đã hồi phục\n"
	.string "hoàn toàn.$"

gText_WeHopeToSeeYouAgain::
	.string "Hẹn gặp lại bạn!$"

gText_WelcomeCutShort::
	.string "Xin chào! Chào mừng bạn đến với\n"
	.string "POKéMON CENTER.\p"
	.string "Chúng tôi sẽ hồi phục POKéMON của bạn\n"
	.string "về trạng thái khỏe mạnh.\p"
	.string "Bạn có muốn…$"

gText_NoticesGoldCard::
	.string "Th-thẻ đó…\n"
	.string "Chẳng lẽ là… GOLD CARD?!\p"
	.string "Ôi, sắc vàng thật rực rỡ!\n"
	.string "Bốn ngôi sao như đang lấp lánh!\p"
	.string "Tôi từng thấy vài HLV sở hữu\n"
	.string "SILVER CARD, nhưng {PLAYER},\p"
	.string "bạn là HLV đầu tiên tôi gặp\n"
	.string "có GOLD CARD!\p"
	.string "Được rồi, {PLAYER}, xin hãy cho tôi\n"
	.string "vinh dự chăm sóc POKéMON của bạn!$"

gText_YouWantTheUsual::
	.string "Rất vui được gặp lại bạn, {PLAYER}!\n"
	.string "Vẫn như thường lệ, đúng không?$"

gText_IllTakeYourPkmn2::
	.string "Được rồi, xin gửi POKéMON cho tôi\n"
	.string "trong giây lát.$"

gText_ThankYouForWaiting::
	.string "Cảm ơn bạn đã chờ.$"

gText_WeHopeToSeeYouAgain2::
	.string "Hẹn gặp lại bạn!$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global gText_WouldYouLikeToRestYourPkmn
	.global gText_IllTakeYourPkmn
	.global gText_RestoredPkmnToFullHealth
	.global gText_WeHopeToSeeYouAgain
	.global gText_WelcomeCutShort
	.global gText_NoticesGoldCard
	.global gText_YouWantTheUsual
	.global gText_IllTakeYourPkmn2
	.global gText_ThankYouForWaiting
	.global gText_WeHopeToSeeYouAgain2
@ END GENERATED LOCALIZATION EXPORTS
