
gPokeNewsTextSlateport_Upcoming::
	.string "Xin chào! Đã đến giờ POKéMON NEWS.\p"
	.string "Nhân vật được yêu thích nhất\n"
	.string "SLATEPORT, ENERGY GURU, lại lên bản tin!\p"
	.string "Ông hứa rằng chỉ sau {STR_VAR_1}\n"
	.string "ngày nữa, ông sẽ chơi lớn chưa từng\l"
	.string "thấy!\p"
	.string "Tuy không chịu tiết lộ mình định chơi\n"
	.string "lớn chuyện gì, ENERGY GURU vẫn khuyên\l"
	.string "mọi người hãy để dành tiền vì chắc\l"
	.string "chắn sẽ có ích.\p"
	.string "Có vẻ hôm đó rất đáng để đến SLATEPORT\n"
	.string "một chuyến.\p"
	.string "POKéMON NEWS xin kết thúc tại đây.$"

gPokeNewsTextSlateport_Ongoing::
	.string "Xin chào! Đã đến giờ POKéMON NEWS.\p"
	.string "Đây chính là tin tức mà mọi người hằng\n"
	.string "mong đợi!\p"
	.string "SLATEPORT'S ENERGY GURU đang chơi lớn\n"
	.string "chưa từng thấy tại MARKET!\p"
	.string "Ông hứa sẽ bán CALCIUM và PROTEIN với\n"
	.string "mức giá ưu đãi không đâu sánh bằng!\p"
	.string "Có vẻ rất đáng để đến SLATEPORT CITY.\n"
	.string "Sao bạn không ghé qua và thỏa sức mua\l"
	.string "sắm?\p"
	.string "POKéMON NEWS xin kết thúc tại đây.$"

gPokeNewsTextSlateport_Ending::
	.string "Xin chào! Đã đến giờ POKéMON NEWS.\p"
	.string "Đây chính là tin tức mà mọi người hằng\n"
	.string "mong đợi!\p"
	.string "SLATEPORT'S ENERGY GURU đang chơi lớn\n"
	.string "chưa từng thấy tại MARKET!\p"
	.string "Ông hứa sẽ bán CALCIUM và PROTEIN với\n"
	.string "mức giá ưu đãi không đâu sánh bằng!\p"
	.string "Theo ENERGY GURU, ông vẫn còn rất nhiều\n"
	.string "hàng.\p"
	.string "Sao bạn không đến SLATEPORT CITY để\n"
	.string "tận hưởng một chuyến mua sắm thật\l"
	.string "vui?\p"
	.string "POKéMON NEWS xin kết thúc tại đây.$"

gPokeNewsTextGameCorner_Upcoming::
	.string "Xin chào! Đã đến giờ POKéMON NEWS.\p"
	.string "Sắp đến rồi! Cuối cùng cũng sắp đến!\p"
	.string "Chỉ còn {STR_VAR_1} ngày nữa là\n"
	.string "tới ngày phục vụ đặc biệt của GAME\l"
	.string "CORNER!\p"
	.string "Ngay cả những người thường kém may\n"
	.string "mắn cũng có thể gặp vận đỏ vào ngày\l"
	.string "đặc biệt này!\p"
	.string "POKéMON NEWS xin kết thúc tại đây.$"

gPokeNewsTextGameCorner_Ongoing::
	.string "Xin chào! Đã đến giờ POKéMON NEWS.\p"
	.string "Đến rồi! Cuối cùng cũng đến rồi!\p"
	.string "Ngày phục vụ đặc biệt của GAME CORNER\n"
	.string "cuối cùng đã tới!\p"
	.string "Liệu bạn có gặp may với SLOTS và\n"
	.string "ROULETTE không?\p"
	.string "Địa điểm là MAUVILLE CITY. Chính là nơi\n"
	.string "này!\p"
	.string "POKéMON NEWS xin kết thúc tại đây.$"

gPokeNewsTextGameCorner_Ending::
	.string "Xin chào! Đã đến giờ POKéMON NEWS.\p"
	.string "Đến rồi! Cuối cùng cũng đến rồi!\p"
	.string "Ngày phục vụ đặc biệt của GAME CORNER\n"
	.string "cuối cùng đã tới!\p"
	.string "Liệu bạn có gặp may với SLOTS và\n"
	.string "ROULETTE không?\p"
	.string "Thời gian có hạn và sắp hết rồi. Địa\n"
	.string "điểm là MAUVILLE CITY.\p"
	.string "POKéMON NEWS xin kết thúc tại đây.$"

gPokeNewsTextLilycove_Upcoming::
	.string "Xin chào! Đã đến giờ POKéMON NEWS.\p"
	.string "Chúng tôi vừa nhận được tin tuyệt vời\n"
	.string "từ LILYCOVE DEPARTMENT STORE.\p"
	.string "Chỉ còn {STR_VAR_1} ngày nữa là\n"
	.string "đến đợt xả kho của DEPARTMENT STORE!\p"
	.string "Món đồ nọ hay thứ đồ kia mà bạn luôn ao\n"
	.string "ước có thể sẽ thuộc về bạn!\p"
	.string "POKéMON NEWS xin kết thúc tại đây.$"

gPokeNewsTextLilycove_Ongoing::
	.string "Xin chào! Đã đến giờ POKéMON NEWS.\p"
	.string "Đây chính là tin tức mà mọi người hằng\n"
	.string "mong đợi!\p"
	.string "Đợt xả kho của LILYCOVE DEPARTMENT\n"
	.string "STORE cuối cùng đã bắt đầu!\p"
	.string "Bao nhiêu món đồ nọ, thứ đồ kia mà bạn\n"
	.string "luôn mơ ước.\p"
	.string "Có thể bạn sẽ gặp được tất cả những\n"
	.string "món đồ định mệnh ấy!\p"
	.string "POKéMON NEWS xin kết thúc tại đây.$"

gPokeNewsTextLilycove_Ending::
	.string "Xin chào! Đã đến giờ POKéMON NEWS.\p"
	.string "Đây chính là tin tức mà mọi người hằng\n"
	.string "mong đợi!\p"
	.string "Đợt xả kho của LILYCOVE DEPARTMENT\n"
	.string "STORE cuối cùng đã bắt đầu!\p"
	.string "Bao nhiêu món đồ nọ, thứ đồ kia mà bạn\n"
	.string "luôn mơ ước.\p"
	.string "Có thể bạn sẽ gặp được tất cả những\n"
	.string "món đồ định mệnh ấy!\p"
	.string "POKéMON NEWS xin kết thúc tại đây.$"

gPokeNewsTextBlendMaster_Upcoming::
	.string "Xin chào! Đã đến giờ POKéMON NEWS.\p"
	.string "Chúng tôi có tin lớn dành cho tất cả\n"
	.string "những ai làm {POKEBLOCK}S.\p"
	.string "Chỉ còn {STR_VAR_1} ngày nữa,\n"
	.string "BẬC THẦY PHA CHẾ huyền thoại sẽ xuất\l"
	.string "hiện tại LILYCOVE CITY!\p"
	.string "Ông được cho là người quay\n"
	.string "BERRY BLENDER giỏi nhất toàn HOENN.\p"
	.string "Những ai muốn làm ra {POKEBLOCK}S\n"
	.string "tuyệt hảo hoặc xem BẬC THẦY trổ\l"
	.string "tài được khuyên nên để dành BERRIES.\p"
	.string "POKéMON NEWS xin kết thúc tại đây.$"

gPokeNewsTextBlendMaster_Ongoing::
	.string "Xin chào! Đã đến giờ POKéMON NEWS.\p"
	.string "Chúng tôi có tin lớn dành cho tất cả\n"
	.string "những ai làm {POKEBLOCK}S.\p"
	.string "BẬC THẦY PHA CHẾ huyền thoại cuối cùng\n"
	.string "đã xuất hiện!\p"
	.string "BẬC THẦY đang quay BERRY BLENDER\n"
	.string "tại LILYCOVE CONTEST HALL.\p"
	.string "Những ai muốn làm ra {POKEBLOCK}S\n"
	.string "tuyệt hảo hoặc xem BẬC THẦY trổ\l"
	.string "tài hãy mau đến LILYCOVE.\p"
	.string "POKéMON NEWS xin kết thúc tại đây.$"

gPokeNewsTextBlendMaster_Ending::
	.string "Xin chào! Đã đến giờ POKéMON NEWS.\p"
	.string "Thật khó tin! Quá sức khó tin!\p"
	.string "BERRY BLENDER đang quay với tốc độ\n"
	.string "chóng mặt!\p"
	.string "BẬC THẦY quả nhiên danh bất hư\n"
	.string "truyền!\p"
	.string "BẬC THẦY sắp rời LILYCOVE.\p"
	.string "Nếu chưa được xem BẬC THẦY trổ tài,\n"
	.string "đừng bỏ phí cơ hội này! Hãy đến\l"
	.string "LILYCOVE ngay!\p"
	.string "POKéMON NEWS xin kết thúc tại đây.$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global gPokeNewsTextSlateport_Upcoming
	.global gPokeNewsTextSlateport_Ongoing
	.global gPokeNewsTextSlateport_Ending
	.global gPokeNewsTextGameCorner_Upcoming
	.global gPokeNewsTextGameCorner_Ongoing
	.global gPokeNewsTextGameCorner_Ending
	.global gPokeNewsTextLilycove_Upcoming
	.global gPokeNewsTextLilycove_Ongoing
	.global gPokeNewsTextLilycove_Ending
	.global gPokeNewsTextBlendMaster_Upcoming
	.global gPokeNewsTextBlendMaster_Ongoing
	.global gPokeNewsTextBlendMaster_Ending
@ END GENERATED LOCALIZATION EXPORTS
