gBirchDexRatingText_AreYouCurious::
	.string "PROF. BIRCH: À, {PLAYER}{KUN}!\p"
	.string "Cháu muốn biết POKéDEX của mình đang\n"
	.string "tiến triển đến đâu phải không?$"

gBirchDexRatingText_Cancel::
	.string "Hửm? À, cháu chưa bắt đủ POKéMON để ta\n"
	.string "đánh giá đâu.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hừm hừm...\p"
	.string "Vậy là cháu đã thấy {STR_VAR_1}\n"
	.string "POKéMON và bắt được\l"
	.string "{STR_VAR_2} POKéMON...$"

gBirchDexRatingText_LessThan10::
	.string "Hãy vào các vùng cỏ nhiều hơn và tìm\n"
	.string "POKéMON thật kỹ.$"

gBirchDexRatingText_LessThan20::
	.string "Có vẻ cháu đang dần quen rồi. Nhưng từ\n"
	.string "đây sẽ khó hơn đấy.$"

gBirchDexRatingText_LessThan30::
	.string "Một số POKéMON chỉ xuất hiện ở những\n"
	.string "khu vực nhất định. Cháu phải thật kiên\l"
	.string "trì.$"

gBirchDexRatingText_LessThan40::
	.string "Số lượng vẫn còn hơi ít, nhưng giờ\n"
	.string "trông nó đã giống một POKéDEX hơn rồi.$"

gBirchDexRatingText_LessThan50::
	.string "Tiến triển khá tốt đấy. Hãy tiếp tục cố\n"
	.string "gắng.$"

gBirchDexRatingText_LessThan60::
	.string "Cháu có dùng RODS không? Có rất nhiều\n"
	.string "POKéMON ở biển đấy.$"

gBirchDexRatingText_LessThan70::
	.string "Thay vì chỉ bắt POKéMON, cháu thử giúp\n"
	.string "chúng tiến hóa nữa xem?$"

gBirchDexRatingText_LessThan80::
	.string "Ta có cảm giác đây sẽ trở thành một\n"
	.string "POKéDEX tuyệt vời.$"

gBirchDexRatingText_LessThan90::
	.string "Cháu đã sưu tầm được nhiều thế này...\n"
	.string "Tài năng của cháu thật đáng nể!$"

gBirchDexRatingText_LessThan100::
	.string "Cháu đã đến SAFARI ZONE chưa?\p"
	.string "Ta nghe nói có những POKéMON chỉ có\n"
	.string "thể bắt được ở đó.$"

gBirchDexRatingText_LessThan110::
	.string "Cuối cùng cháu đã đạt mốc 100 loài.\p"
	.string "Đây là một POKéDEX đầy ấn tượng!$"

gBirchDexRatingText_LessThan120::
	.string "Có thể có những POKéMON chỉ tìm thấy\n"
	.string "được bằng ROCK SMASH.$"

gBirchDexRatingText_LessThan130::
	.string "Cháu nên trao đổi với người khác để có\n"
	.string "thêm POKéMON.$"

gBirchDexRatingText_LessThan140::
	.string "Tôi từng nghe nói có những POKéMON\n"
	.string "tiến hóa khi chúng hết lòng yêu quý\l"
	.string "HLV của mình.$"

gBirchDexRatingText_LessThan150::
	.string "Tôi không ngờ vùng HOENN lại có nhiều\n"
	.string "loài POKéMON đến thế.$"

gBirchDexRatingText_LessThan160::
	.string "Đôi khi, một số POKéMON sẽ xuất hiện\n"
	.string "hàng loạt như một đợt bùng phát.\p"
	.string "Đừng bỏ lỡ những cơ hội như thế.$"

gBirchDexRatingText_LessThan170::
	.string "Chỉ cần xem POKéDEX của cháu, người ta\n"
	.string "có thể hiểu rất rõ về các POKéMON ở\l"
	.string "vùng HOENN.$"

gBirchDexRatingText_LessThan180::
	.string "Theo tôi, cháu đã đủ tư cách làm một\n"
	.string "POKéMON PROFESSOR rồi, mà còn là một\l"
	.string "người rất giỏi nữa!$"

gBirchDexRatingText_LessThan190::
	.string "Với một POKéDEX đầy đủ đến mức này,\n"
	.string "cháu đúng là chuyên gia thực thụ!$"

gBirchDexRatingText_LessThan200::
	.string "Cháu sắp hoàn thành POKéDEX này rồi.\n"
	.string "Tôi cảm nhận được tận trong xương\l"
	.string "cốt!$"

gBirchDexRatingText_DexCompleted::
	.string "Chúc mừng! POKéDEX của cháu đã hoàn\n"
	.string "thành!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hừm hừm. Xét trên phạm vi toàn quốc.\p"
	.string "Cháu đã thấy {STR_VAR_1}\n"
	.string "POKéMON và bắt được\l"
	.string "{STR_VAR_2} POKéMON.$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global gBirchDexRatingText_AreYouCurious
	.global gBirchDexRatingText_Cancel
	.global gBirchDexRatingText_SoYouveSeenAndCaught
	.global gBirchDexRatingText_LessThan10
	.global gBirchDexRatingText_LessThan20
	.global gBirchDexRatingText_LessThan30
	.global gBirchDexRatingText_LessThan40
	.global gBirchDexRatingText_LessThan50
	.global gBirchDexRatingText_LessThan60
	.global gBirchDexRatingText_LessThan70
	.global gBirchDexRatingText_LessThan80
	.global gBirchDexRatingText_LessThan90
	.global gBirchDexRatingText_LessThan100
	.global gBirchDexRatingText_LessThan110
	.global gBirchDexRatingText_LessThan120
	.global gBirchDexRatingText_LessThan130
	.global gBirchDexRatingText_LessThan140
	.global gBirchDexRatingText_LessThan150
	.global gBirchDexRatingText_LessThan160
	.global gBirchDexRatingText_LessThan170
	.global gBirchDexRatingText_LessThan180
	.global gBirchDexRatingText_LessThan190
	.global gBirchDexRatingText_LessThan200
	.global gBirchDexRatingText_DexCompleted
	.global gBirchDexRatingText_OnANationwideBasis
@ END GENERATED LOCALIZATION EXPORTS
