Questionnaire_Text_FillOut::
	.string "Có một bảng câu hỏi.\n"
	.string "Bạn có muốn điền không?$"

Questionnaire_Text_ThankYou::
	.string "Cảm ơn bạn đã dành thời gian\n"
	.string "điền bảng câu hỏi.\p"
	.string "Phản hồi của bạn sẽ được dùng\n"
	.string "để tham khảo trong tương lai.$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "Ồ, xin chào!\n"
	.string "Bạn biết những từ đó sao?\p"
	.string "Vậy là bạn biết về MYSTERY GIFT.\p"
	.string "Từ giờ, bạn có thể nhận\n"
	.string "MYSTERY GIFTS!$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "Sau khi lưu game, bạn có thể\n"
	.string "truy cập MYSTERY GIFT.$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "Ồ, xin chào!\n"
	.string "Bạn biết những từ đó sao?\p"
	.string "Vậy là bạn biết về MYSTERY EVENT.$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "Sau khi lưu game, bạn có thể\n"
	.string "truy cập MYSTERY EVENT.$"

MysteryGift_Text_TheresATicketForYou::
	.string "Cảm ơn bạn đã dùng hệ thống\n"
	.string "MYSTERY EVENT.\p"
	.string "Bạn hẳn là {PLAYER}.\n"
	.string "Có một ticket dành cho bạn.$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "Có vẻ ticket này dùng tại cảng\n"
	.string "LILYCOVE CITY.\p"
	.string "Sao bạn không thử dùng xem?$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global Questionnaire_Text_FillOut
	.global Questionnaire_Text_ThankYou
	.global Questionnaire_Text_YouKnowThoseWordsGift
	.global Questionnaire_Text_YouCanAccessMysteryGift
	.global Questionnaire_Text_YouKnowThoseWordsEvent
	.global Questionnaire_Text_YouCanAccessMysteryEvent
	.global MysteryGift_Text_TheresATicketForYou
	.global MysteryGift_Text_TryUsingItAtLilycovePort
@ END GENERATED LOCALIZATION EXPORTS
