	.align 2
gText_ConfirmSave::
	.string "Bạn có muốn lưu trò chơi không?$"

gText_AlreadySavedFile::
	.string "Đã có dữ liệu lưu.\n"
	.string "Bạn có muốn ghi đè không?$"

gText_SavingDontTurnOff::
	.string "ĐANG LƯU…\n"
	.string "KHÔNG ĐƯỢC TẮT NGUỒN.$"

gText_PlayerSavedGame::
	.string "{PLAYER} đã lưu trò chơi.$"

gText_DifferentSaveFile::
	.string "CẢNH BÁO!\p"
	.string "Đã có dữ liệu của trò chơi khác.\p"
	.string "Nếu lưu lúc này, toàn bộ hành trình,\n"
	.string "vật phẩm và POKéMON trong dữ liệu đó\l"
	.string "sẽ bị mất.\p"
	.string "Bạn có chắc muốn ghi đè dữ liệu\n"
	.string "đó không?$"

gText_SaveError::
	.string "Lỗi khi lưu.\p"
	.string "Vui lòng thay bộ nhớ\n"
	.string "dự phòng.$"

gText_SavingDontTurnOffPower::
	.string "ĐANG LƯU…\n"
	.string "KHÔNG ĐƯỢC TẮT NGUỒN.$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global gText_ConfirmSave
	.global gText_AlreadySavedFile
	.global gText_SavingDontTurnOff
	.global gText_PlayerSavedGame
	.global gText_DifferentSaveFile
	.global gText_SaveError
	.global gText_SavingDontTurnOffPower
@ END GENERATED LOCALIZATION EXPORTS
