SecretBase_Text_Trainer0Intro:
	.string "Cậu đã làm SECRET BASE chưa?\p"
	.string "Tớ đã đi hết chỗ này đến chỗ khác rồi\n"
	.string "mới chọn nơi đây.\p"
	.string "Cậu đã đến tận đây rồi, đấu với tớ một\n"
	.string "trận nhé?$"

SecretBase_Text_Trainer0AcceptBattle:
	.string "Được! Bọn tớ lên đây!$"

SecretBase_Text_Trainer0DeclineBattle:
	.string "Hả? À, giờ cậu không đấu được sao.$"

SecretBase_Text_Trainer0Defeated::
	.string "Oa! Cậu mạnh quá! Chuyện tớ thua, làm\n"
	.string "ơn giữ bí mật nhé!$"

SecretBase_Text_Trainer0PostBattle:
	.string "Cậu thấy SECRET BASE của tớ thế nào?\n"
	.string "Ngày mai lại đến chơi nhé.$"

SecretBase_Text_Trainer0PreChampion:
	.string "Cậu đã làm SECRET BASE chưa?\p"
	.string "Tớ đã đi hết chỗ này đến chỗ khác rồi\n"
	.string "mới chọn nơi đây.\p"
	.string "Cứ tự nhiên ở lại chơi nhé!$"

SecretBase_Text_Trainer5Intro:
	.string "Có rất nhiều nơi để làm SECRET BASE.\p"
	.string "Nhưng tớ thích chỗ này nhất. Cậu không\n"
	.string "thấy nó đẹp sao?\p"
	.string "À, cậu có muốn đấu một trận không?$"

SecretBase_Text_Trainer5AcceptBattle:
	.string "Được, bắt đầu thôi!$"

SecretBase_Text_Trainer5DeclineBattle:
	.string "À, giờ cậu không đấu được sao. Được\n"
	.string "thôi.$"

SecretBase_Text_Trainer5Defeated::
	.string "Hừm. Bọn tớ thua rồi. Nhưng đừng kể\n"
	.string "với ai nhé! Đây là bí mật tuyệt mật!$"

SecretBase_Text_Trainer5PostBattle:
	.string "Nếu lại đến khu vực này, tớ mong cậu sẽ\n"
	.string "ghé thăm.$"

SecretBase_Text_Trainer5PreChampion:
	.string "Có rất nhiều nơi để làm SECRET BASE.\p"
	.string "Nhưng tớ thích chỗ này nhất. Cậu không\n"
	.string "thấy nó đẹp sao?$"

SecretBase_Text_Trainer1Intro:
	.string "Chỗ này được ưa chuộng lắm, lúc nào\n"
	.string "cũng có người chiếm.\p"
	.string "Ơ! Cậu cũng định lấy chỗ này sao?\p"
	.string "Thế này nhé, nếu đánh bại được tớ thì\n"
	.string "chỗ này sẽ thuộc về cậu.$"

SecretBase_Text_Trainer1AcceptBattle:
	.string "Được! Tớ sẽ bảo vệ SECRET BASE của\n"
	.string "mình!$"

SecretBase_Text_Trainer1DeclineBattle:
	.string "Hả? Vậy sao? Cậu không hứng thú với\n"
	.string "chỗ này à?$"

SecretBase_Text_Trainer1Defeated::
	.string "Tớ không trụ nổi nữa! Tớ đầu hàng!$"

SecretBase_Text_Trainer1PostBattle:
	.string "Được rồi, ngày nào đó khi tớ chuyển đi,\n"
	.string "nơi này sẽ thuộc về cậu!$"

SecretBase_Text_Trainer1PreChampion:
	.string "Chỗ này được ưa chuộng lắm, lúc nào\n"
	.string "cũng có người chiếm.\p"
	.string "Tớ đã chờ rất lâu mới thấy nó trống.\n"
	.string "Cuối cùng tớ cũng được dùng rồi!$"

SecretBase_Text_Trainer6Intro:
	.string "Chào mừng đến với POKéMON LAB của tôi.\p"
	.string "Tôi bí mật nghiên cứu về chiến đấu.\p"
	.string "Bạn có muốn xem tôi mạnh đến đâu\n"
	.string "không?$"

SecretBase_Text_Trainer6AcceptBattle:
	.string "Tôi sẽ dốc toàn lực!$"

SecretBase_Text_Trainer6DeclineBattle:
	.string "Ồ. Vậy để lần khác nhé!$"

SecretBase_Text_Trainer6Defeated::
	.string "Hừm. Tôi vẫn còn nhiều điều phải học.\n"
	.string "Tôi cần nghiên cứu thêm.$"

SecretBase_Text_Trainer6PostBattle:
	.string "Cảm ơn bạn đã đấu với tôi. Ngày mai hãy\n"
	.string "quay lại nhé.$"

SecretBase_Text_Trainer6PreChampion:
	.string "Chào mừng đến với POKéMON LAB của tôi.\p"
	.string "Tôi bí mật nghiên cứu về chiến đấu.$"

SecretBase_Text_Trainer2Intro:
	.string "Biệt thự lớn cũng hay, nhưng tớ thích\n"
	.string "kiểu nơi này hơn.\p"
	.string "Tớ thích vì đủ kiểu người sẽ đến thăm.\p"
	.string "Vậy cậu có muốn đấu một trận không?$"

SecretBase_Text_Trainer2AcceptBattle:
	.string "Phải thế chứ!$"

SecretBase_Text_Trainer2DeclineBattle:
	.string "Khi nào sẵn sàng thì gọi tớ nhé!$"

SecretBase_Text_Trainer2Defeated::
	.string "Ôi! Bị hạ mất rồi! Nhưng chiến đấu vẫn\n"
	.string "vui thật!$"

SecretBase_Text_Trainer2PostBattle:
	.string "Dù sao thì tớ cũng nên đi mua thêm đồ\n"
	.string "trang trí và nội thất.\p"
	.string "Tớ muốn SECRET BASE của mình trở\n"
	.string "thành nơi mà mọi người đều có thể vui\l"
	.string "chơi.$"

SecretBase_Text_Trainer2PreChampion:
	.string "Biệt thự lớn cũng hay, nhưng tớ thích\n"
	.string "kiểu nơi này hơn.\p"
	.string "Tớ thích vì đủ kiểu người sẽ đến thăm.$"

SecretBase_Text_Trainer7Intro:
	.string "Tôi vô cùng thích mua đồ trang trí và\n"
	.string "nội thất.\p"
	.string "Tôi cũng yêu thích việc nuôi dưỡng\n"
	.string "POKéMON không kém.\p"
	.string "Nếu bạn không phiền, hãy đấu với\n"
	.string "POKéMON của tôi nhé?$"

SecretBase_Text_Trainer7AcceptBattle:
	.string "Cảm ơn bạn. Chúng ta bắt đầu nhé?$"

SecretBase_Text_Trainer7DeclineBattle:
	.string "Ồ. Thật đáng tiếc.$"

SecretBase_Text_Trainer7Defeated::
	.string "Tôi xin nhận thua.$"

SecretBase_Text_Trainer7PostBattle:
	.string "Trận đấu thật vui! Giờ tôi nên đi tận\n"
	.string "hưởng việc mua sắm thôi.$"

SecretBase_Text_Trainer7PreChampion:
	.string "Tôi vô cùng thích mua đồ trang trí và\n"
	.string "nội thất.\p"
	.string "Tôi cũng yêu thích việc nuôi dưỡng\n"
	.string "POKéMON không kém.$"

SecretBase_Text_Trainer3Intro:
	.string "Có người xây SECRET BASE ở những nơi\n"
	.string "rất khó tìm. Họ chỉ muốn ẩn mình thôi\l"
	.string "sao?\p"
	.string "Nhưng cậu đã tìm thấy tớ rồi, chúng ta\n"
	.string "đấu một trận nhé?$"

SecretBase_Text_Trainer3AcceptBattle:
	.string "Tớ sẽ không dễ dàng gục ngã đâu!$"

SecretBase_Text_Trainer3DeclineBattle:
	.string "À. Có phải cậu mệt vì phải tìm nơi này\n"
	.string "không?$"

SecretBase_Text_Trainer3Defeated::
	.string "Tớ gục mất rồi.$"

SecretBase_Text_Trainer3PostBattle:
	.string "SECRET BASE của cậu ở đâu? Tớ nên đến\n"
	.string "thăm mới được.$"

SecretBase_Text_Trainer3PreChampion:
	.string "Có người xây SECRET BASE ở những nơi\n"
	.string "rất khó tìm. Họ chỉ muốn ẩn mình thôi\l"
	.string "sao?$"

SecretBase_Text_Trainer8Intro:
	.string "Mọi người bảo tớ rằng có nhiều cách để\n"
	.string "kiếm đồ trang trí.\p"
	.string "Chúng ta nên thi xem ai kiếm được đồ\n"
	.string "trang trí và nội thất đẹp hơn!\p"
	.string "Trong lúc đó, cậu muốn đấu một trận\n"
	.string "không?$"

SecretBase_Text_Trainer8AcceptBattle:
	.string "Đây là SECRET BASE của tớ. Tớ không\n"
	.string "thể thua!$"

SecretBase_Text_Trainer8DeclineBattle:
	.string "Lúc nào tớ cũng sẵn sàng đấu với cậu.$"

SecretBase_Text_Trainer8Defeated::
	.string "Hả? Tớ vừa thua sao?$"

SecretBase_Text_Trainer8PostBattle:
	.string "Tớ sẽ không thua trong cuộc đua sưu\n"
	.string "tầm đồ trang trí đâu. Lại đến chơi nhé!$"

SecretBase_Text_Trainer8PreChampion:
	.string "Mọi người bảo tớ rằng có nhiều cách để\n"
	.string "kiếm đồ trang trí.\p"
	.string "Chúng ta nên thi xem ai kiếm được đồ\n"
	.string "trang trí và nội thất đẹp hơn!$"

SecretBase_Text_Trainer4Intro:
	.string "Tớ tìm được một chỗ ưng ý rồi bày biện\n"
	.string "bằng những món đồ trang trí mình thích\l"
	.string "nhất.\p"
	.string "Tớ nuôi POKéMON yêu thích và cùng nó\n"
	.string "trở nên mạnh hơn.\p"
	.string "Đó là việc tớ vẫn làm. Cậu muốn đấu với\n"
	.string "tớ không?$"

SecretBase_Text_Trainer4AcceptBattle:
	.string "Cho tớ xem bản lĩnh của cậu nào!$"

SecretBase_Text_Trainer4DeclineBattle:
	.string "Chắc cũng có lúc cậu không có hứng.$"

SecretBase_Text_Trainer4Defeated::
	.string "Giờ thì tớ biết chính xác cậu có bản\n"
	.string "lĩnh thế nào rồi.$"

SecretBase_Text_Trainer4PostBattle:
	.string "Cả hai ta đều có thể mạnh hơn. Cùng\n"
	.string "tiếp tục cố gắng nhé!$"

SecretBase_Text_Trainer4PreChampion:
	.string "Tớ tìm được một chỗ ưng ý rồi bày biện\n"
	.string "bằng những món đồ trang trí mình thích\l"
	.string "nhất.\p"
	.string "Tớ nuôi POKéMON yêu thích và cùng nó\n"
	.string "trở nên mạnh hơn.\p"
	.string "Ngày nào cũng thật tuyệt.$"

SecretBase_Text_Trainer9Intro:
	.string "Nhìn vào loại đồ trang trí một người\n"
	.string "sở hữu và cách họ trưng bày, ta có thể\l"
	.string "biết nhiều về gu thẩm mỹ và óc tinh tế\l"
	.string "của họ.\p"
	.string "Cậu thấy gu của tớ thế nào? Đẹp đến\n"
	.string "mức không nói nên lời sao?\p"
	.string "Muốn xem phong cách chiến đấu của tớ\n"
	.string "không?$"

SecretBase_Text_Trainer9AcceptBattle:
	.string "Không cần nương tay!$"

SecretBase_Text_Trainer9DeclineBattle:
	.string "Lúc nào tớ cũng sẵn lòng phô diễn phong\n"
	.string "cách của mình.$"

SecretBase_Text_Trainer9Defeated::
	.string "Cậu tài giỏi tuyệt đỉnh! Sức mạnh của\n"
	.string "cậu dường như không có giới hạn.$"

SecretBase_Text_Trainer9PostBattle:
	.string "Cậu thấy phong cách của tớ thế nào? Tớ\n"
	.string "sẽ tiếp tục trau chuốt nó!$"

SecretBase_Text_Trainer9PreChampion:
	.string "Nhìn vào loại đồ trang trí một người\n"
	.string "sở hữu và cách họ trưng bày, ta có thể\l"
	.string "biết nhiều về gu thẩm mỹ và óc tinh tế\l"
	.string "của họ.\p"
	.string "Cậu thấy gu của tớ thế nào? Đẹp đến\n"
	.string "mức không nói nên lời sao?$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global SecretBase_Text_Trainer0Intro
	.global SecretBase_Text_Trainer0AcceptBattle
	.global SecretBase_Text_Trainer0DeclineBattle
	.global SecretBase_Text_Trainer0Defeated
	.global SecretBase_Text_Trainer0PostBattle
	.global SecretBase_Text_Trainer0PreChampion
	.global SecretBase_Text_Trainer5Intro
	.global SecretBase_Text_Trainer5AcceptBattle
	.global SecretBase_Text_Trainer5DeclineBattle
	.global SecretBase_Text_Trainer5Defeated
	.global SecretBase_Text_Trainer5PostBattle
	.global SecretBase_Text_Trainer5PreChampion
	.global SecretBase_Text_Trainer1Intro
	.global SecretBase_Text_Trainer1AcceptBattle
	.global SecretBase_Text_Trainer1DeclineBattle
	.global SecretBase_Text_Trainer1Defeated
	.global SecretBase_Text_Trainer1PostBattle
	.global SecretBase_Text_Trainer1PreChampion
	.global SecretBase_Text_Trainer6Intro
	.global SecretBase_Text_Trainer6AcceptBattle
	.global SecretBase_Text_Trainer6DeclineBattle
	.global SecretBase_Text_Trainer6Defeated
	.global SecretBase_Text_Trainer6PostBattle
	.global SecretBase_Text_Trainer6PreChampion
	.global SecretBase_Text_Trainer2Intro
	.global SecretBase_Text_Trainer2AcceptBattle
	.global SecretBase_Text_Trainer2DeclineBattle
	.global SecretBase_Text_Trainer2Defeated
	.global SecretBase_Text_Trainer2PostBattle
	.global SecretBase_Text_Trainer2PreChampion
	.global SecretBase_Text_Trainer7Intro
	.global SecretBase_Text_Trainer7AcceptBattle
	.global SecretBase_Text_Trainer7DeclineBattle
	.global SecretBase_Text_Trainer7Defeated
	.global SecretBase_Text_Trainer7PostBattle
	.global SecretBase_Text_Trainer7PreChampion
	.global SecretBase_Text_Trainer3Intro
	.global SecretBase_Text_Trainer3AcceptBattle
	.global SecretBase_Text_Trainer3DeclineBattle
	.global SecretBase_Text_Trainer3Defeated
	.global SecretBase_Text_Trainer3PostBattle
	.global SecretBase_Text_Trainer3PreChampion
	.global SecretBase_Text_Trainer8Intro
	.global SecretBase_Text_Trainer8AcceptBattle
	.global SecretBase_Text_Trainer8DeclineBattle
	.global SecretBase_Text_Trainer8Defeated
	.global SecretBase_Text_Trainer8PostBattle
	.global SecretBase_Text_Trainer8PreChampion
	.global SecretBase_Text_Trainer4Intro
	.global SecretBase_Text_Trainer4AcceptBattle
	.global SecretBase_Text_Trainer4DeclineBattle
	.global SecretBase_Text_Trainer4Defeated
	.global SecretBase_Text_Trainer4PostBattle
	.global SecretBase_Text_Trainer4PreChampion
	.global SecretBase_Text_Trainer9Intro
	.global SecretBase_Text_Trainer9AcceptBattle
	.global SecretBase_Text_Trainer9DeclineBattle
	.global SecretBase_Text_Trainer9Defeated
	.global SecretBase_Text_Trainer9PostBattle
	.global SecretBase_Text_Trainer9PreChampion
@ END GENERATED LOCALIZATION EXPORTS
