ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "Cháu định đi sâu vào trong đó sao?\p"
	.string "Cháu mang về cho ta một ít SHOAL SALT\n"
	.string "và SHOAL SHELLS nhé?\p"
	.string "Nếu cháu mang đủ nguyên liệu, ta có thể\n"
	.string "làm cho cháu một món đồ tốt.$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "Nếu cháu mang cho ta bốn phần SHOAL\n"
	.string "SALT và bốn chiếc SHOAL SHELLS, ta có\l"
	.string "thể làm một chiếc SHELL BELL cho cháu.\p"
	.string "Ngày nào cháu cũng có thể kiếm những\n"
	.string "nguyên liệu ấy.$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "Ồ, xem này! SHOAL SALT và SHOAL SHELLS!\n"
	.string "Số lượng cũng đủ rồi!\p"
	.string "Cháu có muốn ta dùng chúng làm một\n"
	.string "chiếc SHELL BELL không?$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "Được rồi! Ta sẽ làm ngay một chiếc\n"
	.string "SHELL BELL cho cháu.\p"
	.string "Chờ ta một chút.\p"
	.string "Xong rồi!$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "Hãy cho một POKéMON cầm nó. Chắc chắn\n"
	.string "nó sẽ rất thích.\p"
	.string "Âm thanh của SHELL BELL mới tuyệt diệu\n"
	.string "làm sao!\p"
	.string "Ngày nào cháu cũng có thể kiếm nguyên\n"
	.string "liệu, nên ta có thể làm thêm cho cháu.$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "Ồ. Vậy sao. Ta đã muốn làm một chiếc\n"
	.string "SHELL BELL lắm.$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "TÚI ĐỒ của cháu không đủ chỗ nếu\n"
	.string "ta làm nó.\p"
	.string "Hãy dọn chỗ rồi quay lại nhận SHELL\n"
	.string "BELL nhé.$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "Ở đây từng có SHOAL SALT, nhưng giờ\n"
	.string "chẳng còn gì nữa.$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "Ở đây từng có một chiếc SHOAL SHELL,\n"
	.string "nhưng giờ chẳng còn gì nữa.$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere
	.global ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells
	.global ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell
	.global ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway
	.global ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell
	.global ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell
	.global ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag
	.global ShoalCave_Text_WasShoalSaltNowNothing
	.global ShoalCave_Text_WasShoallShellNowNothing
@ END GENERATED LOCALIZATION EXPORTS
