Route102_Text_CalvinIntro:
	.string "Nếu có POKéMON đi cùng thì cậu đã là\n"
	.string "một HLV POKéMON chính thức! Cậu\l"
	.string "không được từ chối lời thách đấu của\l"
	.string "tớ!$"

Route102_Text_CalvinDefeated:
	.string "A, tớ thua rồi. Lẽ ra tớ phải huấn luyện\n"
	.string "POKéMON của mình nhiều hơn.$"

Route102_Text_CalvinPostBattle:
	.string "Này nhé, nếu mạnh như vậy thì cậu phải\n"
	.string "nói trước với tớ chứ!$"

Route102_Text_CalvinRegister:
	.string "Từ lần gặp cậu trước, tớ vẫn luôn chăm\n"
	.string "chỉ luyện tập.\p"
	.string "Tớ muốn đấu với cậu lần nữa, nên cậu\n"
	.string "đăng ký tớ vào POKéNAV được không?$"

Route102_Text_CalvinRegisterShort:
	.string "Tớ muốn đấu với cậu lần nữa, nên cậu\n"
	.string "đăng ký tớ vào POKéNAV được không?$"

Route102_Text_CalvinRematchIntro:
	.string "Kể từ khi thua cậu, tớ đã liều mạng\n"
	.string "huấn luyện POKéMON. Cậu không được từ\l"
	.string "chối lời thách đấu của tớ!$"

Route102_Text_CalvinRematchDefeated:
	.string "A, tớ lại thua rồi. Phương pháp luyện\n"
	.string "tập của tớ không đúng sao?$"

Route102_Text_CalvinRematchPostBattle:
	.string "Nếu cậu mạnh hơn, tớ cũng sẽ mạnh\n"
	.string "hơn.$"

Route102_Text_AllenIntro:
	.string "Cậu vừa trở thành HLV phải không?\n"
	.string "Cả hai chúng ta đều là người mới!$"

Route102_Text_AllenDefeated:
	.string "Tớ gọi cậu lại vì cứ nghĩ mình có thể\n"
	.string "thắng.$"

Route102_Text_AllenPostBattle:
	.string "Mình vẫn chưa thắng nổi lần nào... Ước\n"
	.string "gì mình sớm thắng được một trận...$"

Route102_Text_RickIntro:
	.string "Ha ha! Ánh mắt chúng ta chạm nhau rồi!\n"
	.string "Tôi sẽ đấu với cậu bằng BUG POKéMON!$"

Route102_Text_RickDefeated:
	.string "Á! Thua sạch rồi!$"

Route102_Text_RickPostBattle:
	.string "Nếu chạm mắt một HLV, cậu phải\n"
	.string "thách đấu! Luật là thế!$"

Route102_Text_TianaIntro:
	.string "Tôi sẽ tiếp tục chiến thắng và nhắm đến\n"
	.string "vị trí HLV giỏi nhất.\p"
	.string "Hãy giúp sự nghiệp của tôi tiến xa hơn!$"

Route102_Text_TianaDefeated:
	.string "Rốt cuộc tôi lại giúp sự nghiệp của cậu\n"
	.string "tiến xa hơn...$"

Route102_Text_TianaPostBattle:
	.string "Muốn tiếp tục thắng để tiến lên, xem ra\n"
	.string "tôi phải bắt thêm POKéMON.$"

Route103_Text_DaisyIntro:
	.string "Cậu có cảm nhận được sức hút từ\n"
	.string "hương thơm xoa dịu tâm hồn của chúng\l"
	.string "tôi không?$"

Route103_Text_DaisyDefeated:
	.string "Cậu không bị hương thơm của chúng tôi\n"
	.string "làm lạc lối...$"

Route103_Text_DaisyPostBattle:
	.string "Aromatherapy là một phương pháp chữa\n"
	.string "lành tinh thần bằng hương thơm.$"

Route103_Text_AmyIntro:
	.string "AMY: Mình là AMY. Còn đây là em gái mình,\n"
	.string "LIV. Hai chị em mình cùng chiến đấu!$"

Route103_Text_AmyDefeated:
	.string "AMY: Ôi không, chúng mình thua rồi.$"

Route103_Text_AmyPostBattle:
	.string "AMY: Khi đấu cùng lúc với hai HLV,\n"
	.string "cậu phải tính đến đủ thứ.$"

Route103_Text_AmyNotEnoughPokemon:
	.string "AMY: Ôi không, cậu chỉ mang theo một\n"
	.string "POKéMON. Như vậy thì không thể đấu với\l"
	.string "chúng mình.$"

Route103_Text_LivIntro:
	.string "LIV: Hai chị em mình chiến đấu như một\n"
	.string "đội.$"

Route103_Text_LivDefeated:
	.string "LIV: Ôi, chúng ta thua rồi, chị ơi...$"

Route103_Text_LivPostBattle:
	.string "LIV: Em và chị phối hợp hoàn hảo với\n"
	.string "nhau...\p"
	.string "Vậy mà vẫn thua...$"

Route103_Text_AmyLivRegister:
	.string "LIV: Thật ra chúng mình giỏi hơn nhiều...\n"
	.string "Thật đấy! Lần sau chúng mình sẽ cho\l"
	.string "cậu thấy!$"

Route103_Text_LivNotEnoughPokemon:
	.string "LIV: Muốn đấu với chúng mình thì cậu\n"
	.string "phải có hai POKéMON! Nếu không thì đâu\l"
	.string "có công bằng!$"

Route103_Text_AmyRematchIntro:
	.string "AMY: Mình là AMY. Còn đây là em gái mình,\n"
	.string "LIV. Hai chị em mình cùng chiến đấu!$"

Route103_Text_AmyRematchDefeated:
	.string "AMY: Ôi, chán quá! Lại không thắng được\n"
	.string "rồi...$"

Route103_Text_AmyRematchPostBattle:
	.string "AMY: Khi đấu cùng lúc với hai HLV,\n"
	.string "cậu phải tính đến đủ thứ.$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "AMY: Ôi không, cậu chỉ mang theo một\n"
	.string "POKéMON. Như vậy thì không thể đấu với\l"
	.string "chúng mình.$"

Route103_Text_LivRematchIntro:
	.string "LIV: Hai chị em mình chiến đấu như một\n"
	.string "đội.$"

Route103_Text_LivRematchDefeated:
	.string "LIV: Ôi, chúng ta lại thua rồi... Chị ơi...$"

Route103_Text_LivRematchPostBattle:
	.string "LIV: Em và chị phối hợp hoàn hảo với\n"
	.string "nhau...\p"
	.string "Nhưng sao chúng ta lại thua nữa chứ?$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "LIV: Muốn đấu với chúng mình thì cậu\n"
	.string "phải có hai POKéMON! Nếu không thì đâu\l"
	.string "có công bằng!$"

Route103_Text_AndrewIntro:
	.string "Á! Dây câu của tôi rối tung cả rồi! Tôi\n"
	.string "bực đến phát cáu đây! Đủ rồi! Đấu với\l"
	.string "tôi!$"

Route103_Text_AndrewDefeated:
	.string "Á! Thua mất rồi! Giờ tôi còn bực hơn\n"
	.string "nữa!$"

Route103_Text_AndrewPostBattle:
	.string "Á, tôi vẫn đang tức sôi máu... Gừừừ...$"

Route103_Text_MiguelIntro:
	.string "POKéMON của tôi đáng yêu hết chỗ nói!\n"
	.string "Đừng ngại, tôi cho cậu xem!$"

Route103_Text_MiguelDefeated:
	.string "Trời ơi! POKéMON cưng của tôi!$"

Route103_Text_MiguelPostBattle:
	.string "POKéMON đáng yêu của tôi dù ngất xỉu\n"
	.string "vẫn dễ thương!$"

Route103_Text_MiguelRegister:
	.string "Tôi sẽ gọi cậu đến ngắm POKéMON đáng\n"
	.string "yêu của tôi lần nữa!$"

Route103_Text_MiguelRematchIntro:
	.string "Này, cậu! POKéMON vốn đã đáng yêu của\n"
	.string "tôi giờ còn dễ thương hơn nữa!$"

Route103_Text_MiguelRematchDefeated:
	.string "Ôi! POKéMON cưng của tôi!$"

Route103_Text_MiguelRematchPostBattle:
	.string "Càng ở bên nhau lâu, POKéMON của tôi\n"
	.string "càng trở nên đáng yêu.$"

Route103_Text_PeteIntro:
	.string "Quãng đường thế này... Cứ bơi qua là\n"
	.string "được mà!$"

Route103_Text_PeteDefeated:
	.string "Ồ, khá lắm!$"

Route103_Text_PetePostBattle:
	.string "Ồ, giờ tôi hiểu ý cậu rồi.\p"
	.string "Nếu tôi có một POKéMON đáng tin như\n"
	.string "thế, tôi cũng muốn dùng SURF trên lưng\l"
	.string "nó!$"

Route103_Text_IsabelleIntro:
	.string "Nhìn đường đi chứ! Chúng ta sắp đâm\n"
	.string "nhau rồi!$"

Route103_Text_IsabelleDefeated:
	.string "Ư...$"

Route103_Text_IsabellePostBattle:
	.string "Tôi bơi kém nên đang luyện tập... Xin lỗi\n"
	.string "vì suýt đâm vào cậu.$"

Route103_Text_RhettIntro:
	.string "Ồ! Sao cậu chui được vào chỗ chật thế\n"
	.string "này?$"

Route103_Text_RhettDefeated:
	.string "Ồ! Nhóc này chất thật!$"

Route103_Text_RhettPostBattle:
	.string "Cậu thích những chỗ chật chội thế này\n"
	.string "à?$"

Route103_Text_MarcosIntro:
	.string "Tiếng guitar gào rú của tôi đã kéo cậu\n"
	.string "đến đây à?$"

Route103_Text_MarcosDefeated:
	.string "Buổi diễn một người của tôi hỏng mất\n"
	.string "rồi...$"

Route103_Text_MarcosPostBattle:
	.string "Tôi chọn chỗ vắng người để chơi guitar,\n"
	.string "vậy mà giờ có đông người hâm mộ tụ tập\l"
	.string "quá.\p"
	.string "Hê, có khi tôi nên theo nghề chuyên\n"
	.string "nghiệp.$"

Route104_Text_GinaIntro:
	.string "GINA: Được rồi, cùng cho POKéMON của\n"
	.string "chúng ta chiến đấu nào!$"

Route104_Text_GinaDefeat:
	.string "GINA: Thua làm mình buồn lắm!$"

Route104_Text_GinaPostBattle:
	.string "GINA: Cậu mạnh thật! Chúng mình phải\n"
	.string "luyện tập nhiều hơn nữa!$"

Route104_Text_GinaNotEnoughMons:
	.string "GINA: Ồ? Chỉ có một POKéMON thôi à? Vậy\n"
	.string "chúng mình không đấu với cậu đâu.\p"
	.string "Nếu chỉ có một POKéMON, nó sẽ cô đơn\n"
	.string "lắm. Như thế không hay.$"

Route104_Text_MiaIntro:
	.string "MIA: Chúng mình là sinh đôi, nên luôn\n"
	.string "cùng nhau cho POKéMON chiến đấu.$"

Route104_Text_MiaDefeat:
	.string "MIA: Chúng mình cùng chiến đấu, nhưng\n"
	.string "cả hai đều thua...$"

Route104_Text_MiaPostBattle:
	.string "MIA: Chúng mình sẽ luyện POKéMON nhiều\n"
	.string "hơn để mạnh như cậu.$"

Route104_Text_MiaNotEnoughMons:
	.string "MIA: Cậu muốn đấu với chúng mình à?\p"
	.string "Không mang theo hai POKéMON là không\n"
	.string "được đâu. Chúng mình mạnh quá với cậu\l"
	.string "đấy!$"

Route104_Text_IvanIntro:
	.string "Có gì mà phải giấu? Tôi là chuyên gia\n"
	.string "WATER POKéMON!\p"
	.string "Hả? Cậu không biết tôi sao?$"

Route104_Text_IvanDefeat:
	.string "Tôi cứ tưởng mình cũng khá lắm, tự tôi\n"
	.string "nói vậy có hơi kỳ, nhưng xem ra không\l"
	.string "phải... Chậc...$"

Route104_Text_IvanPostBattle:
	.string "Tôi mải câu cá quá. Quên mất phải nuôi\n"
	.string "dạy POKéMON...$"

Route104_Text_BillyIntro:
	.string "Để lại dấu chân trên cát vui thật đấy!$"

Route104_Text_BillyDefeat:
	.string "Oa! Cát lọt vào giày thể thao của mình\n"
	.string "rồi! Sạn lạo xạo khắp nơi!$"

Route104_Text_BillyPostBattle:
	.string "Mình muốn để lại dấu chân trên cát ở\n"
	.string "khắp mọi nơi, nhưng chúng biến mất\l"
	.string "nhanh quá...$"

Route104_Text_HaleyIntro:
	.string "Mình có nên... Hay không nên nhỉ?\p"
	.string "Được rồi, mình sẽ đấu!$"

Route104_Text_HaleyDefeat:
	.string "Lẽ ra mình không nên đấu...$"

Route104_Text_HaleyPostBattle:
	.string "Khi phải đưa ra quyết định mà để người\n"
	.string "khác chọn thay, dù kết quả thế nào cậu\l"
	.string "cũng sẽ hối hận.$"

Route104_Text_HaleyRegister1:
	.string "Cậu mạnh thật, nhưng mình có nên đăng\n"
	.string "ký cậu vào POKéNAV không? Có lẽ không\l"
	.string "nên...\p"
	.string "Được rồi, mình sẽ đăng ký cậu!$"

Route104_Text_HaleyRegister2:
	.string "Cậu mạnh thật, nhưng mình có nên đăng\n"
	.string "ký cậu vào POKéNAV không? Có lẽ không\l"
	.string "nên...\p"
	.string "Được rồi, mình sẽ đăng ký cậu!$"

Route104_Text_HaleyRematchIntro:
	.string "Nào, đấu với mình đi!$"

Route104_Text_HaleyRematchDefeat:
	.string "Ôi... Mình cứ tưởng sẽ thắng...$"

Route104_Text_HaleyPostRematch:
	.string "Mình đã tự quyết định chiến đấu, nên có\n"
	.string "thể bình thản chấp nhận thất bại này.\p"
	.string "Nhưng mình vẫn buồn vì thua!$"

Route104_Text_WinstonIntro:
	.string "Ồ, được thôi, tôi chấp nhận lời thách\n"
	.string "đấu của cậu. Tôi có rất nhiều tiền.$"

Route104_Text_WinstonDefeat:
	.string "Tại sao tôi lại không thắng được?$"

Route104_Text_WinstonPostBattle:
	.string "Có những thứ tiền không thể mua được.\n"
	.string "Đó là POKéMON...$"

Route104_Text_WinstonRegister1:
	.string "Hửm? À, cậu đã có POKéNAV rồi.\p"
	.string "Tôi rất sẵn lòng đăng ký cậu. Dù sao tôi\n"
	.string "cũng có rất nhiều tiền.$"

Route104_Text_WinstonRegister2:
	.string "Hửm? À, cậu đã có POKéNAV rồi.\p"
	.string "Tôi rất sẵn lòng đăng ký cậu. Dù sao tôi\n"
	.string "cũng có rất nhiều tiền.$"

Route104_Text_WinstonRematchIntro:
	.string "Sau khi thua cậu, tôi đã học được rất\n"
	.string "nhiều điều về POKéMON.$"

Route104_Text_WinstonRematchDefeat:
	.string "Tôi lại thua sao? Tại sao tôi không thể\n"
	.string "thắng?$"

Route104_Text_WinstonPostRematch:
	.string "Tôi giàu nứt đố đổ vách, vậy mà chẳng\n"
	.string "thể thắng khi đấu POKéMON...\p"
	.string "Thế giới POKéMON thật sâu sắc...$"

Route104_Text_CindyIntro:
	.string "Hẳn là định mệnh đã cho chúng ta gặp\n"
	.string "nhau. Tôi có thể xin cậu một trận đấu\l"
	.string "không?$"

Route104_Text_CindyDefeat:
	.string "Ôi trời!$"

Route104_Text_CindyPostBattle:
	.string "“Xin chào” là khởi đầu của “Tạm biệt”.\n"
	.string "Tôi mong chúng ta sẽ gặp lại.$"

Route104_Text_CindyRegister1:
	.string "Xin chào, chúng ta lại gặp nhau rồi.\p"
	.string "Dường như chúng ta luôn bị cuốn về\n"
	.string "phía nhau. Hãy đăng ký nhau vào\l"
	.string "POKéNAVS nhé.$"

Route104_Text_CindyRegister2:
	.string "Hãy kỷ niệm mối duyên cứ đưa chúng ta\n"
	.string "đến với nhau.\p"
	.string "Chúng ta cùng đăng ký nhau vào\n"
	.string "POKéNAVS nhé.$"

Route104_Text_CindyRematchIntro:
	.string "Xin chào, chúng ta lại gặp nhau rồi. Tôi\n"
	.string "có thể xin cậu một trận đấu không?$"

Route104_Text_CindyRematchDefeat:
	.string "Ôi trời... Tôi đã cố hết sức rồi...$"

Route104_Text_CindyPostRematch:
	.string "“Xin chào” là khởi đầu của “Tạm biệt”.\n"
	.string "Tôi mong chúng ta sẽ gặp lại.$"

Route104_Text_DarianIntro:
	.string "Tôi câu được một POKéMON trông rất\n"
	.string "mạnh!\p"
	.string "Nó toát ra vẻ kỳ diệu! Chắc chắn trông\n"
	.string "rất mạnh, đúng thế!$"

Route104_Text_DarianDefeat:
	.string "Cái gì...$"

Route104_Text_DarianPostBattle:
	.string "Này, MAGIKARP, ngươi chẳng xứng với\n"
	.string "cái tên chút nào, đúng không?$"

Route105_Text_FosterIntro:
	.string "Nghe nói quanh đây có một tảng đá\n"
	.string "huyền bí. Cậu biết gì về nó không?$"

Route105_Text_FosterDefeated:
	.string "Tôi mải nghĩ về tảng đá đó quá, còn\n"
	.string "POKéMON của mình thì vẫn yếu...$"

Route105_Text_FosterPostBattle:
	.string "Tôi có thể ngắm một tảng đá đẹp hàng\n"
	.string "giờ liền mà không chán.$"

Route105_Text_LuisIntro:
	.string "Phù! Thấy cậu, tôi cứ lo có đứa trẻ\n"
	.string "đang bị đuối nước.\p"
	.string "Xem ra cậu vẫn ổn, vậy đấu một trận\n"
	.string "nhé?$"

Route105_Text_LuisDefeated:
	.string "Ục... Ục...$"

Route105_Text_LuisPostBattle:
	.string "Nếu bị đuối nước, hãy ra hiệu bằng cách\n"
	.string "vẫy một tay về phía bờ.$"

Route105_Text_DominikIntro:
	.string "Bơi giữa biển xanh thẳm... Cảm giác\n"
	.string "tuyệt nhất!$"

Route105_Text_DominikDefeated:
	.string "Tôi thua rồi... Giờ buồn như biển xanh...$"

Route105_Text_DominikPostBattle:
	.string "Tại sao biển lại có màu xanh?\p"
	.string "Tôi từng học điều đó ở MUSEUM tại\n"
	.string "SLATEPORT, nhưng quên mất rồi.$"

Route105_Text_BeverlyIntro:
	.string "Ở dưới nước, cơ thể tôi nhẹ hơn hẳn.\n"
	.string "Cứ như thể tôi đã gầy đi vậy!$"

Route105_Text_BeverlyDefeated:
	.string "Tôi đang trôi bồng bềnh...$"

Route105_Text_PostBattle:
	.string "Ở dưới nước, trọng lượng cơ thể chỉ\n"
	.string "còn một phần mười.\p"
	.string "Thế thì cân nặng của tôi sẽ... Ối! Tôi\n"
	.string "không nói cho bạn biết đâu!$"

Route105_Text_ImaniIntro:
	.string "Bầu trời xanh, thật xanh... Biển cả mênh\n"
	.string "mông... Thật yên bình...$"

Route105_Text_ImaniDefeated:
	.string "Tôi thua ngay lúc đang thư giãn!$"

Route105_Text_ImaniPostBattle:
	.string "Tôi muốn người ta nói rằng ở bên tôi\n"
	.string "thật thư thái. Hihi.$"

Route105_Text_AndresIntro:
	.string "Tôi tin rằng biển cả đang giấu chúng ta\n"
	.string "những bí mật.$"

Route105_Text_AndresDefeated:
	.string "Đúng vậy... Tôi chẳng giỏi chiến đấu...$"

Route105_Text_AndresPostBattle:
	.string "Tôi chắc chắn biển cả trên thế giới còn\n"
	.string "rất nhiều bí mật chưa được khám phá.\p"
	.string "Tôi sẽ tìm ra tất cả!$"

Route105_Text_AndresRegister:
	.string "Hả? Tôi yếu thế này mà bạn vẫn muốn\n"
	.string "đăng ký tôi vào POKéNAV sao?$"

Route105_Text_AndresRematchIntro:
	.string "Tôi đã nói là mình yếu rồi mà... Bạn chắc\n"
	.string "vẫn muốn đấu chứ?$"

Route105_Text_AndresRematchDefeated:
	.string "Đúng vậy... Tôi cũng chẳng nghĩ mình có\n"
	.string "thể thắng.$"

Route105_Text_AndresRematchPostBattle:
	.string "Tôi có thể yếu trong chiến đấu, nhưng\n"
	.string "không ai đánh bại được quyết tâm khám\l"
	.string "phá của tôi.\p"
	.string "Tôi sẽ chu du khắp các đại dương trên\n"
	.string "thế giới!$"

Route105_Text_JosueIntro:
	.string "Bơi lội khiến tôi kiệt sức. Tôi vẫn chưa\n"
	.string "quen.\p"
	.string "Tôi cần một trận đấu để đổi không khí!$"

Route105_Text_JosueDefeated:
	.string "Tôi thua vì chiến đấu trên biển.$"

Route105_Text_JosuePostBattle:
	.string "Ừ, với tôi thì bầu trời hợp hơn biển cả\n"
	.string "nhiều.$"

Route106_Text_ElliotIntro:
	.string "Bạn thích câu cá ngoài biển hay ở suối\n"
	.string "hơn?$"

Route106_Text_ElliotDefeated:
	.string "Giống như khi câu cá biển sâu, tôi đã\n"
	.string "thua một cách ngoạn mục!$"

Route106_Text_ElliotPostBattle:
	.string "Dù câu ngoài biển hay ở suối thì câu cá\n"
	.string "vẫn là tuyệt nhất. Bạn cũng đồng ý,\l"
	.string "đúng không?$"

Route106_Text_ElliotRegister:
	.string "Câu cá rất tuyệt, nhưng chiến đấu cũng\n"
	.string "vậy. Nếu bạn không phiền, chúng ta có\l"
	.string "thể gặp lại nhau không?$"

Route106_Text_ElliotRematchIntro:
	.string "Tôi đã câu được cả đống POKéMON. Tôi\n"
	.string "sẽ cho bạn xem một trận đấu thật ấn\l"
	.string "tượng!$"

Route106_Text_ElliotRematchDefeated:
	.string "Tôi lại thua một cách ngoạn mục!$"

Route106_Text_ElliotRematchPostBattle:
	.string "Dù thắng hay thua, POKéMON vẫn là tuyệt\n"
	.string "nhất! Bạn cũng đồng ý, đúng không?$"

Route106_Text_NedIntro:
	.string "Khi cần đi vệ sinh thì mọi người làm thế\n"
	.string "nào nhỉ?\p"
	.string "Nhỡ ROD câu trúng một con cá lớn đúng\n"
	.string "lúc tôi đang đi vệ sinh thì sao? Tôi\l"
	.string "không thể đi được...$"

Route106_Text_NedDefeated:
	.string "Tôi thua vì đang cố nhịn đi vệ sinh...$"

Route106_Text_NedPostBattle:
	.string "Ôi không! Tôi có cảm giác mình sắp câu\n"
	.string "được một con cá lớn!$"

Route106_Text_DouglasIntro:
	.string "Ha ha ha! Tôi chạy rất tệ, nhưng dưới\n"
	.string "nước thì bạn không bắt kịp tôi đâu!$"

Route106_Text_DouglasDefeated:
	.string "Tôi chịu thua!$"

Route106_Text_DouglasPostBattle:
	.string "Nếu thi bơi thì tôi đã không thua...$"

Route106_Text_KylaIntro:
	.string "Biển cả là sân sau của tôi. Tôi sẽ không\n"
	.string "nương tay chỉ vì bạn là trẻ con đâu!$"

Route106_Text_KylaDefeated:
	.string "Không lẽ bạn đã nương tay với tôi sao?$"

Route106_Text_KylaPostBattle:
	.string "Thả mình trôi theo những con sóng... Tôi\n"
	.string "thích lắm! Sao bạn không thử xem?$"

Route107_Text_DarrinIntro:
	.string "Ngáp...\p"
	.string "Chắc tôi đã ngủ quên trong lúc thả mình\n"
	.string "trôi theo những con sóng.$"

Route107_Text_DarrinDefeated:
	.string "Ha ha, tôi thua rồi... Chắc tôi sẽ chợp\n"
	.string "mắt một lát...$"

Route107_Text_DarrinPostBattle:
	.string "Nổi bồng bềnh và được sóng đưa qua\n"
	.string "đưa lại giống như đang ngủ trên một\l"
	.string "chiếc giường êm ái, dễ chịu vậy.$"

Route107_Text_TonyIntro:
	.string "Biển cả chẳng khác nào sân sau của tôi.\n"
	.string "Đấu thôi!$"

Route107_Text_TonyDefeated:
	.string "Tôi lại thua ngay trên sân nhà... Sốc\n"
	.string "thật!$"

Route107_Text_TonyPostBattle:
	.string "Tôi bơi giữa biển khơi với trái tim đầy\n"
	.string "ắp ước mơ...\p"
	.string "Đó là một bài hát đấy! Dù sao thì tôi sẽ\n"
	.string "bơi tiếp.$"

Route107_Text_TonyRegister:
	.string "Bạn khiến tôi sốc đến tận xương tủy!\n"
	.string "Nào, để bạn không quên tôi...$"

Route107_Text_TonyRematchIntro:
	.string "Nhờ bơi giữa biển cả bao la, POKéMON\n"
	.string "của tôi đã mạnh hơn!$"

Route107_Text_TonyRematchDefeated:
	.string "Sốc thật!\p"
	.string "POKéMON của tôi đã mạnh hơn, nhưng tôi\n"
	.string "vẫn là một HLV yếu đuối!$"

Route107_Text_TonyRematchPostBattle:
	.string "Những điều học được trong chiến đấu\n"
	.string "sẽ giúp bạn trở thành một HLV mạnh\l"
	.string "hơn. Chính những con sóng đã dạy tôi\l"
	.string "điều đó.$"

Route107_Text_DeniseIntro:
	.string "Bạn có biết thị trấn nhỏ mang tên\n"
	.string "DEWFORD không?$"

Route107_Text_DeniseDefeated:
	.string "Tôi ghét thế này!$"

Route107_Text_DenisePostBattle:
	.string "Một câu nói kỳ lạ đang trở nên cực kỳ\n"
	.string "thịnh hành ở DEWFORD HALL.$"

Route107_Text_BethIntro:
	.string "Bạn muốn đấu với tôi à? Được thôi, tôi\n"
	.string "nhận lời!$"

Route107_Text_BethDefeated:
	.string "Tôi không đủ sức đấu với bạn.$"

Route107_Text_BethPostBattle:
	.string "Tôi nghĩ bạn sẽ còn tiến bộ hơn nữa. Tôi\n"
	.string "cũng sẽ cố gắng!$"

Route107_Text_LisaIntro:
	.string "LISA: Hai chị em tôi thách đấu bạn!$"

Route107_Text_LisaDefeated:
	.string "LISA: Tuyệt thật. Sức mạnh của bạn ở\n"
	.string "một đẳng cấp hoàn toàn khác.$"

Route107_Text_LisaPostBattle:
	.string "LISA: Bạn có người bạn nào chịu đi biển\n"
	.string "cùng mình không?$"

Route107_Text_LisaNotEnoughPokemon:
	.string "LISA: Nếu muốn đấu với chúng tôi, hãy\n"
	.string "mang thêm POKéMON đến.$"

Route107_Text_RayIntro:
	.string "RAY: Chị em tôi lúc nào cũng đấu POKéMON\n"
	.string "với nhau.\p"
	.string "Tôi luôn thua, nhưng nếu đấu hai chọi\n"
	.string "hai thì chúng tôi có thể thắng bạn!$"

Route107_Text_RayDefeated:
	.string "RAY: Chà, trình độ của bạn cao hơn\n"
	.string "chúng tôi hẳn!$"

Route107_Text_RayPostBattle:
	.string "RAY: Chị tôi đã tặng tôi POKéMON này.\n"
	.string "Tôi nuôi nấng nó, và giờ nó là cộng sự\l"
	.string "quan trọng của tôi!$"

Route107_Text_RayNotEnoughPokemon:
	.string "RAY: Nếu muốn đấu với chúng tôi, hãy đi\n"
	.string "mang thêm POKéMON đến!$"

Route107_Text_CamronIntro:
	.string "Tôi đang thi ba môn phối hợp, nhưng vẫn\n"
	.string "chưa thấy mệt chút nào!$"

Route107_Text_CamronDefeated:
	.string "Trận đó làm tôi kiệt sức...$"

Route107_Text_CamronPostBattle:
	.string "Sau chuyện này, tôi vẫn còn phải bơi và\n"
	.string "chạy nữa.\p"
	.string "Liệu tôi có ổn không đây?$"

Route108_Text_JeromeIntro:
	.string "Ước mơ của tôi là bơi qua bảy biển trên\n"
	.string "thế giới!$"

Route108_Text_JeromeDefeated:
	.string "Cứ thế này thì tôi chẳng thể bơi qua\n"
	.string "bảy biển được...$"

Route108_Text_JeromePostBattle:
	.string "Vui đùa cùng POKéMON biển là một trong\n"
	.string "những thú vui của việc bơi lội!$"

Route108_Text_MatthewIntro:
	.string "A-hoy! Bạn cũng đang đi tới ABANDONED\n"
	.string "SHIP à?$"

Route108_Text_MatthewDefeated:
	.string "Tôi đang chìm! Ùng ục... Ùng ục...$"

Route108_Text_MatthewPostBattle:
	.string "Thậm chí có người còn đi vào bên trong\n"
	.string "ABANDONED SHIP.$"

Route108_Text_TaraIntro:
	.string "Gã bạn trai dối trá của tôi bảo rằng tôi\n"
	.string "mặc bikini trông rất đẹp...$"

Route108_Text_TaraDefeated:
	.string "Ôi, chán quá!$"

Route108_Text_TaraPostBattle:
	.string "Dù đó là lời nói dối, tôi vẫn thích được\n"
	.string "khen là mình trông rất đẹp... Con gái\l"
	.string "chúng tôi thật phức tạp...$"

Route108_Text_MissyIntro:
	.string "Tôi yêu biển cả! Mỗi khi bơi, tôi quên\n"
	.string "hết mọi phiền muộn!$"

Route108_Text_MissyDefeated:
	.string "Cứ thua trận là tôi lại căng thẳng vô\n"
	.string "cùng!$"

Route108_Text_MissyPostBattle:
	.string "Hãy bơi để xua tan căng thẳng! Tốt cho\n"
	.string "sức khỏe lắm!$"

Route108_Text_CoryIntro:
	.string "Tôi yêu POKéMON hệ WATER. Những\n"
	.string "POKéMON khác tôi cũng yêu!$"

Route108_Text_CoryDefeated:
	.string "Oa! Tôi thua rồi! Oa! Oa!$"

Route108_Text_CoryPostBattle:
	.string "La hét rất tốt cho tôi! Nó khiến tôi\n"
	.string "phấn chấn!$"

Route108_Text_CoryRegister:
	.string "Tôi cũng thích những HLV mạnh mẽ!\n"
	.string "Hãy đăng ký tôi vào POKéNAV của bạn!$"

Route108_Text_CoryRematchIntro:
	.string "Dù thắng hay thua, tôi vẫn thích chiến\n"
	.string "đấu trên biển!$"

Route108_Text_CoryRematchDefeated:
	.string "Oa! Tôi lại thua rồi! Oa! Oa!$"

Route108_Text_CoryRematchPostBattle:
	.string "Khi gặp thử thách, hãy thử hét thật\n"
	.string "lớn về phía biển!$"

Route108_Text_CarolinaIntro:
	.string "Tôi vô cùng tự hào về POKéMON của mình.\n"
	.string "Chúng tôi sẽ cho bạn xem một trận đấu\l"
	.string "chớp nhoáng!$"

Route108_Text_CarolinaDefeated:
	.string "Chẳng đáng yêu chút nào.$"

Route108_Text_CarolinaPostBattle:
	.string "Đã ra biển thế này, tôi cũng muốn mặc\n"
	.string "một bộ đồ bơi màu hồng có bèo nhún...$"

Route109_Text_DavidIntro:
	.string "Hây da! Nhìn cơ bụng săn chắc của tôi\n"
	.string "đi! Thế này mới gọi là nét căng!$"

Route109_Text_DavidDefeated:
	.string "Ái da! Xì hơi mất rồi!$"

Route109_Text_DavidPostBattle:
	.string "Hây da!\p"
	.string "Cơ bụng như tạc của tôi chẳng liên quan\n"
	.string "gì đến chiến đấu POKéMON cả!$"

Route109_Text_AliceIntro:
	.string "Bạn đã chống nắng cẩn thận chưa?$"

Route109_Text_AliceDefeated:
	.string "Đau, đau, đau!$"

Route109_Text_AlicePostBattle:
	.string "Đôi má là chỗ dễ bị cháy nắng nhất!$"

Route109_Text_HueyIntro:
	.string "Tôi từng thả neo tại các cảng khắp thế\n"
	.string "giới, nhưng SLATEPORT vẫn là tuyệt\l"
	.string "nhất.$"

Route109_Text_HueyDefeated:
	.string "Bạn là tuyệt nhất!$"

Route109_Text_HueyPostBattle:
	.string "Tại cảng tuyệt nhất lại có HLV\n"
	.string "tuyệt nhất...$"

Route109_Text_EdmondIntro:
	.string "Ợ... Đấu à? Với tôi sao?$"

Route109_Text_EdmondDefeated:
	.string "Ợ... Ớớớớớ... Ợợợợ...$"

Route109_Text_EdmondPostBattle:
	.string "Bình thường tôi mạnh hơn thế này! Chỉ\n"
	.string "là tôi đang say sóng kinh khủng!\p"
	.string "Tôi là SAILOR, vậy mà...$"

Route109_Text_RickyIntro:
	.string "Tôi khát quá... Giá mà có một chai SODA\n"
	.string "POP ở SEASHORE HOUSE...$"

Route109_Text_RickyDefeated:
	.string "Ư...$"

Route109_Text_RickyPostBattle:
	.string "Tôi đói cồn cào rồi... Chiếc phao bơi của\n"
	.string "tôi trông như một cái bánh vòng khổng\l"
	.string "lồ...$"

Route109_Text_RickyRegister:
	.string "Khi tôi không còn khát thế này, bạn sẽ\n"
	.string "đấu lại với tôi chứ?$"

Route109_Text_RickyRematchIntro:
	.string "Tôi đang đói, nhưng vẫn còn đủ sức để\n"
	.string "chiến đấu!$"

Route109_Text_RickyRematchDefeated:
	.string "Tôi thua rồi... Là vì tôi đang đói...$"

Route109_Text_RickyRematchPostBattle:
	.string "Khi ăn trên bãi biển, món gì dường như\n"
	.string "cũng ngon hơn một chút.$"

Route109_Text_LolaIntro:
	.string "Bạn không thấy chiếc ô trên bãi biển\n"
	.string "trông giống một bông hoa khổng lồ sao?$"

Route109_Text_LolaDefeated:
	.string "Mẹ ơi!$"

Route109_Text_LolaPostBattle:
	.string "Nếu nhìn bãi biển từ trên trời, nó trông\n"
	.string "như một vườn hoa khổng lồ!$"

Route109_Text_LolaRegister:
	.string "Tớ á? Ngày nào tớ cũng ở đây!$"

Route109_Text_LolaRematchIntro:
	.string "Lần này tớ sẽ không thua bạn nữa! Vì\n"
	.string "thế tớ mới mang theo phao bơi!$"

Route109_Text_LolaRematchDefeated:
	.string "Mẹ ơi!$"

Route109_Text_LolaRematchPostBattle:
	.string "Có phao bơi thì tớ và POKéMON của tớ\n"
	.string "càng đáng yêu hơn nhiều!$"

Route109_Text_AustinaIntro:
	.string "Không có phao bơi thì tớ không biết\n"
	.string "bơi, nhưng đấu POKéMON thì tớ sẽ\l"
	.string "không thua đâu!$"

Route109_Text_AustinaDefeated:
	.string "Tớ thua vì mang phao bơi sao?$"

Route109_Text_AustinaPostBattle:
	.string "Phao bơi là món đồ thời trang của tớ.\n"
	.string "Tớ không thể để ai thấy mình thiếu nó.$"

Route109_Text_GwenIntro:
	.string "Chào HLV lớn! Đấu với em nhé?$"

Route109_Text_GwenDefeated:
	.string "Ồ, bạn mạnh thật.$"

Route109_Text_GwenPostBattle:
	.string "Làm sao bạn trở nên mạnh như vậy?$"

Route109_Text_CarterIntro:
	.string "Oa ha ha! Tay này sắp câu được một con\n"
	.string "thật bự đây!$"

Route109_Text_CarterDefeated:
	.string "Tay này vừa để vuột mất một con...$"

Route109_Text_CarterPostBattle:
	.string "Tay này thấy cậu là một con cá lớn.\n"
	.string "Không, là một con cá lớn trong tương\l"
	.string "lai!$"

Route109_Text_PaulIntro:
	.string "PAUL: Chậc, mất cả hứng.\p"
	.string "Tôi mong bạn đừng quấy rầy khoảng thời\n"
	.string "gian quý giá của hai chúng tôi.$"

Route109_Text_PaulDefeated:
	.string "PAUL: Được rồi, tôi chịu thua.$"

Route109_Text_PaulPostBattle:
	.string "PAUL: Đừng kể với ai rằng chúng tôi ở\n"
	.string "đây nhé. Đây là thế giới riêng chỉ có\l"
	.string "hai chúng tôi!$"

Route109_Text_PaulNotEnoughPokemon:
	.string "PAUL: Chúng tôi yêu nhau vô cùng say\n"
	.string "đắm. Vì thế chúng tôi mới cho POKéMON\l"
	.string "của mình cùng chiến đấu.$"

Route109_Text_MelIntro:
	.string "MEL: Bọn mình kiểu như yêu nhau hết\n"
	.string "mình ấy. Tình yêu của bọn mình đang hâm\l"
	.string "nóng cả HOENN!$"

Route109_Text_MelDefeated:
	.string "MEL: Bọn mình thua rồi, tất cả là lỗi của\n"
	.string "mình! PAUL sẽ ghét mình mất!$"

Route109_Text_MelPostBattle:
	.string "MEL: Ừm, PAUL, anh giận em sao? Xin anh\n"
	.string "đừng giận.$"

Route109_Text_MelNotEnoughPokemon:
	.string "MEL: Bọn mình kiểu như yêu nhau sâu sắc\n"
	.string "và chân thành lắm ấy. Vì thế bọn mình\l"
	.string "mới cho POKéMON cùng chiến đấu.$"

Route109_Text_ChandlerIntro:
	.string "Ta-da! Thấy chưa? Phao bơi của tớ tròn\n"
	.string "vo!$"

Route109_Text_ChandlerDefeated:
	.string "Ôi, ôi! Tiếc quá!$"

Route109_Text_ChandlerPostBattle:
	.string "Tớ đã cho bạn xem cả chiếc phao bơi\n"
	.string "tròn vo của mình rồi mà...$"

Route109_Text_HaileyIntro:
	.string "Tớ không biết bơi nên đang giả vờ bơi\n"
	.string "thôi.$"

Route109_Text_HaileyDefeated:
	.string "Tớ biết ngay mà! Tớ đã nghĩ bọn tớ\n"
	.string "không thể thắng.$"

Route109_Text_HaileyPostBattle:
	.string "Khi tớ học được cách bơi, chắc\n"
	.string "POKéMON của tớ cũng sẽ mạnh mẽ hơn.$"

Route109_Text_ElijahIntro:
	.string "Với một anh chàng nam tính như tôi,\n"
	.string "loại POKéMON này đúng là hợp nhất!$"

Route109_Text_ElijahDefeated:
	.string "Dù thua tôi vẫn ngầu, nhỉ?$"

Route109_Text_ElijahPostBattle:
	.string "Với một anh chàng nam tính như tôi, bến\n"
	.string "cảng là khung cảnh hoàn hảo!\p"
	.string "Chắc tôi sẽ tới SLATEPORT.$"

Route110_Text_JacobIntro:
	.string "Whoa! Cẩn thận chứ! Chắc bạn chưa quen\n"
	.string "đua BIKE.$"

Route110_Text_JacobDefeated:
	.string "Whoa! Phanh của tôi hỏng rồi!$"

Route110_Text_JacobPostBattle:
	.string "Lốp xẹp và phanh hỏng có thể gây\n"
	.string "thương tích nghiêm trọng! Hãy kiểm tra\l"
	.string "xem BIKE của bạn có vấn đề gì không!$"

Route110_Text_AnthonyIntro:
	.string "Này, bạn kia! Bạn có theo kịp tốc độ của\n"
	.string "tôi không?$"

Route110_Text_AnthonyDefeated:
	.string "Ngã chỏng vó rồi!$"

Route110_Text_AnthonyPostBattle:
	.string "Chỉ có tốc độ thì không thể giúp tôi\n"
	.string "thắng khi đấu POKéMON. Tôi phải xem xét\l"
	.string "lại chuyện này...$"

Route110_Text_BenjaminIntro:
	.string "Đừng hoảng nếu BIKE của bạn chạy quá\n"
	.string "nhanh!$"

Route110_Text_BenjaminDefeated:
	.string "Lẽ ra tôi không nên hoảng khi đấu\n"
	.string "POKéMON...$"

Route110_Text_BenjaminPostBattle:
	.string "Không cần hoảng hốt hay căng thẳng. Cứ\n"
	.string "thong thả. Vẫn còn nhiều thời gian mà.$"

Route110_Text_BenjaminRegister:
	.string "Tôi sẽ cứ thong thả tiến bước mà không\n"
	.string "căng thẳng. Nếu muốn thì cứ gọi tôi nhé.$"

Route110_Text_BenjaminRematchIntro:
	.string "Bạn đi hơi nhanh quá rồi đấy nhỉ? Cứ\n"
	.string "thong thả và đấu với tôi nào.$"

Route110_Text_BenjaminRematchDefeated:
	.string "Tôi không hề hoảng, vậy mà vẫn thua...$"

Route110_Text_BenjaminRematchPostBattle:
	.string "Không cần hoảng hốt hay căng thẳng. Cứ\n"
	.string "thong thả. Vẫn còn nhiều thời gian mà.$"

Route110_Text_AbigailIntro:
	.string "Ba môn phối hợp cực kỳ khắc nghiệt.\p"
	.string "Bạn phải hoàn thành cả ba môn là bơi,\n"
	.string "đạp xe và chạy bộ.$"

Route110_Text_AbigailDefeated:
	.string "Đấu POKéMON cũng khó thật!$"

Route110_Text_AbigailPostBattle:
	.string "Tôi kiệt sức rồi nên cần nghỉ một chút.\n"
	.string "Nghỉ ngơi đầy đủ rất quan trọng.$"

Route110_Text_AbigailRegister:
	.string "Bạn biết không, tôi quý bạn đấy! Hãy tái\n"
	.string "đấu trên CYCLING ROAD nhé.$"

Route110_Text_AbigailRematchIntro:
	.string "Vừa đạp xe vừa đấu thật tuyệt, phải\n"
	.string "không?$"

Route110_Text_AbigailRematchDefeated:
	.string "Whoa... Sao bạn có thể mạnh đến vậy?$"

Route110_Text_AbigailRematchPostBattle:
	.string "Bạn đang định lập kỷ lục sao?\p"
	.string "Xin lỗi nếu tôi đã làm bạn chậm lại!$"

Route110_Text_JasmineIntro:
	.string "Tôi đã đạp xe không ngừng nghỉ. Bắp đùi\n"
	.string "tôi cứng như đá!$"

Route110_Text_JasmineDefeated:
	.string "Tôi lo mình sẽ bị chuột rút...$"

Route110_Text_JasminePostBattle:
	.string "Ồ, bạn có vài GYM BADGES sao? Thảo nào\n"
	.string "bạn mạnh đến thế!$"

Route110_Text_EdwardIntro:
	.string "Ta đã nhìn thấu ý định của ngươi! Ta\n"
	.string "không thể nào thua!$"

Route110_Text_EdwardDefeated:
	.string "Ta đã không tiên đoán được kết cục\n"
	.string "của chính mình!$"

Route110_Text_EdwardPostBattle:
	.string "Ta thấy tương lai của ngươi...\p"
	.string "Hừm... Ta thấy một luồng sáng rực rỡ...$"

Route110_Text_JaclynIntro:
	.string "A ha ha ha! Ta sẽ khiến ngươi choáng\n"
	.string "ngợp trước những điều kỳ diệu của ta!$"

Route110_Text_JaclynDefeated:
	.string "Ta đã thua một cách kỳ diệu!$"

Route110_Text_JaclynPostBattle:
	.string "Ngươi thắng được chỉ vì đó là một kỳ\n"
	.string "tích! Đúng, một kỳ tích! Đừng tưởng\l"
	.string "lần nào ngươi cũng có thể thắng!$"

Route110_Text_EdwinIntro:
	.string "Cho tôi xem POKéMON của bạn được\n"
	.string "không? Chỉ nhìn một chút thôi, làm ơn\l"
	.string "nhé?$"

Route110_Text_EdwinDefeated:
	.string "Tôi đã muốn hoàn thành bộ sưu tập của\n"
	.string "mình...$"

Route110_Text_EdwinPostBattle:
	.string "Mỗi khi thấy một POKéMON mà mình chưa\n"
	.string "biết, niềm đam mê sưu tầm trong tôi lại\l"
	.string "bùng cháy!$"

Route110_Text_EdwinRegister:
	.string "Tôi cũng thích sưu tầm đăng ký MATCH\n"
	.string "CALL...$"

Route110_Text_EdwinRematchIntro:
	.string "Chào bạn, bạn có bắt được POKéMON mới\n"
	.string "nào không?\p"
	.string "Cho tôi xem POKéMON của bạn được\n"
	.string "không? Chỉ nhìn một chút thôi, làm ơn\l"
	.string "nhé?$"

Route110_Text_EdwinRematchDefeated:
	.string "POKéMON của bạn... Tôi thật ghen tị.$"

Route110_Text_EdwinRematchPostBattle:
	.string "Ôi, tôi khao khát được sở hữu tất cả\n"
	.string "POKéMON quý hiếm!$"

Route110_Text_DaleIntro:
	.string "Này! Đừng lén tới sau lưng tôi như thế!$"

Route110_Text_DaleDefeated:
	.string "Tôi thua rồi! Đáng ghét!$"

Route110_Text_DalePostBattle:
	.string "Câu cá quan trọng nhất là sự tập trung.\n"
	.string "Bạn phải chăm chú nhìn phao câu.$"

Route110_Text_IsabelIntro:
	.string "A ha ha ha! Ta có thể đi bất cứ đâu để\n"
	.string "khoe những POKéMON tuyệt vời của\l"
	.string "mình.$"

Route110_Text_IsabelDefeated:
	.string "Ôi trời, thế này không được rồi.$"

Route110_Text_IsabelPostBattle:
	.string "Thay vì chiến đấu, có lẽ ta nên tới FAN\n"
	.string "CLUB để khoe POKéMON của mình.$"

Route110_Text_IsabelRegister:
	.string "Vừa rồi còn chưa đủ để ta phô diễn\n"
	.string "POKéMON của mình.\p"
	.string "Ta sẽ bắt bạn làm khán giả bất đắc dĩ\n"
	.string "bất cứ khi nào có thể!$"

Route110_Text_IsabelRematchIntro:
	.string "A ha ha ha! Ta rất vui lòng khoe POKéMON\n"
	.string "của mình bao nhiêu lần tùy thích!$"

Route110_Text_IsabelRematchDefeated:
	.string "Ôi trời, thế này không được rồi.$"

Route110_Text_IsabelRematchPostBattle:
	.string "Ta không nghĩ mình có thể ngừng khoe\n"
	.string "POKéMON được.\p"
	.string "Nhưng ta cũng thích chiến đấu!$"

Route110_Text_TimmyIntro:
	.string "Tớ tìm thấy vài POKéMON cực ngầu trong\n"
	.string "bãi cỏ quanh đây!$"

Route110_Text_TimmyDefeated:
	.string "Chỉ ngầu thôi thì chưa đủ để thắng...$"

Route110_Text_TimmyPostBattle:
	.string "Thật khó chiến đấu bằng những POKéMON\n"
	.string "vừa mới bắt.$"

Route110_Text_AlyssaIntro:
	.string "Tôi bị ngã khỏi CYCLING ROAD...\p"
	.string "Tôi sẽ đấu với bạn để quên đi nỗi xấu hổ\n"
	.string "này!$"

Route110_Text_AlyssaDefeated:
	.string "Ôi! Cuối cùng tôi lại thua mất rồi!$"

Route110_Text_AlyssaPostBattle:
	.string "Bị ngã... Rồi lại thua... Thật quá nhục\n"
	.string "nhã!$"

Route110_Text_JosephIntro:
	.string "Được rồi! Tăng hết tốc lực nào! Không\n"
	.string "biết bắt nhịp là bị bỏ lại đấy!$"

Route110_Text_JosephDefeated:
	.string "Bạn bắt nhịp ngon lành thật...$"

Route110_Text_JosephPostBattle:
	.string "Chuyện này không làm tôi nản đâu! Thất\n"
	.string "bại đã giúp tôi trưởng thành hơn!$"

Route110_Text_KalebIntro:
	.string "Khi những POKéMON dễ thương giúp đỡ\n"
	.string "lẫn nhau... Không gì đáng yêu hơn thế!$"

Route110_Text_KalebDefeated:
	.string "Bạn không có chút lòng trắc ẩn hay\n"
	.string "thương xót nào sao?$"

Route110_Text_KalebPostBattle:
	.string "Được rồi, được rồi, các bé cưng của ta\n"
	.string "đã cố hết sức rồi.$"

Route111_Text_DrewIntro:
	.string "Ồ, chào! GO-GOGGLES đó hợp với bạn\n"
	.string "đấy. Nhưng tôi nghĩ đeo trên tôi trông\l"
	.string "đẹp hơn.\p"
	.string "Hãy đấu một trận để xem ai đeo đẹp hơn!$"

Route111_Text_DrewDefeat:
	.string "Vì GO-GOGGLES mà tôi không thấy hai\n"
	.string "bên đang xảy ra chuyện gì.$"

Route111_Text_DrewPostBattle:
	.string "GO-GOGGLES giúp ta đi xuyên qua bão\n"
	.string "cát. Điều đó khiến tôi rất vui!$"

Route111_Text_HeidiIntro:
	.string "Tôi đang dã ngoại trong sa mạc.\p"
	.string "Ở đây lúc nào cũng tìm được một\n"
	.string "HLV, nên tôi vẫn có thể vui vẻ chiến\l"
	.string "đấu!$"

Route111_Text_HeidiDefeat:
	.string "Ôi! Bạn xấu tính quá!$"

Route111_Text_HeidiPostBattle:
	.string "Khi chiến đấu trong bão cát, hãy để ý HP\n"
	.string "của POKéMON.\p"
	.string "Nếu không chú ý, nó có thể ngất đấy!$"

Route111_Text_BeauIntro:
	.string "Đeo GO-GOGGLES khiến tớ cảm thấy mình\n"
	.string "như một siêu anh hùng. Bây giờ không ai\l"
	.string "thắng nổi tớ!$"

Route111_Text_BeauDefeat:
	.string "Chỉ có tinh thần thôi thì tớ không thể\n"
	.string "thắng...$"

Route111_Text_BeauPostBattle:
	.string "Một ngày nào đó tớ sẽ trở thành anh\n"
	.string "hùng thật sự. Tớ sẽ cố gắng hơn để cả\l"
	.string "tớ và POKéMON của mình mạnh hơn.$"

Route111_Text_BeckyIntro:
	.string "Tôi nghe nói có thể tìm thấy hóa thạch\n"
	.string "trong sa mạc. Chúng có thể ở đâu nhỉ?$"

Route111_Text_BeckyDefeat:
	.string "Tôi vẫn còn kém một chút...$"

Route111_Text_BeckyPostBattle:
	.string "Nếu người ta tìm thấy hóa thạch trong\n"
	.string "sa mạc, hẳn nơi này từng là biển.$"

Route111_Text_DustyIntro:
	.string "Suốt ba mươi năm, tôi đã tìm kiếm những\n"
	.string "tàn tích cổ! Cậu muốn thách đấu tôi\l"
	.string "sao?$"

Route111_Text_DustyDefeat:
	.string "Mải tìm tàn tích, tôi lại chẳng tìm\n"
	.string "POKéMON mạnh.$"

Route111_Text_DustyPostBattle:
	.string "Suốt ba mươi năm, tôi đã tìm kiếm những\n"
	.string "tàn tích cổ!\p"
	.string "Không, khoan, là bốn mươi năm thì phải?\n"
	.string "Rốt cuộc là bao nhiêu nhỉ?$"

Route111_Text_DustyRegister:
	.string "Tôi chẳng hề đi tìm POKéMON mạnh nào\n"
	.string "cả.\p"
	.string "Nhưng chẳng hiểu sao tôi lại rất thích\n"
	.string "POKéNAVS.$"

Route111_Text_DustyRematchIntro:
	.string "Suốt ba mươi năm, tôi đã tìm kiếm những\n"
	.string "tàn tích cổ!\p"
	.string "Không, khoan, là bốn mươi năm thì phải?\n"
	.string "Dù sao thì cậu muốn thách đấu tôi sao?$"

Route111_Text_DustyRematchDefeat:
	.string "Tôi chẳng tìm thấy tàn tích, cũng chẳng\n"
	.string "tìm thấy POKéMON mạnh nào...$"

Route111_Text_DustyPostRematch:
	.string "Suốt ba mươi năm, tôi đã tìm kiếm những\n"
	.string "tàn tích cổ!\p"
	.string "Không, khoan, tôi đã tìm suốt bốn mươi\n"
	.string "năm thì phải?\p"
	.string "Hừm... Có khi là năm mươi năm cũng nên...\n"
	.string "Tôi làm việc này bao lâu rồi nhỉ?$"

Route111_Text_TravisIntro:
	.string "Tôi tràn đầy năng lượng! POKéMON của\n"
	.string "tôi cũng sung sức!$"

Route111_Text_TravisDefeat:
	.string "POKéMON của tôi hết sung sức rồi...$"

Route111_Text_TravisPostBattle:
	.string "Thấy một HLV tràn đầy năng lượng\n"
	.string "là tôi không thể không ngoái nhìn.$"

Route111_Text_IreneIntro:
	.string "Tôi không biết bạn đang đi đâu, nhưng\n"
	.string "đấu một trận nhé?$"

Route111_Text_IreneDefeat:
	.string "Ôi, bạn giỏi đến phát ghét!$"

Route111_Text_IrenePostBattle:
	.string "Tôi đang tính đến MT. CHIMNEY, nhưng\n"
	.string "cảnh quanh đây cũng đẹp lắm.$"

Route111_Text_DaisukeIntro:
	.string "Để rèn luyện bản thân, tôi thách đấu\n"
	.string "với bất cứ ai gặp mặt!$"

Route111_Text_DaisukeDefeat:
	.string "Xin thua! Tôi đầu hàng!$"

Route111_Text_DaisukePostBattle:
	.string "Tôi chỉ có thể tiếp tục luyện tập cho\n"
	.string "đến khi đánh bại được những HLV\l"
	.string "mạnh như bạn.$"

Route111_Text_WiltonIntro:
	.string "Cho tôi xem bạn đã rèn POKéMON cứng\n"
	.string "cáp đến mức nào.$"

Route111_Text_WiltonDefeat:
	.string "Ra vậy, bạn đã rèn chúng cứng cáp hơn\n"
	.string "rất nhiều.$"

Route111_Text_WiltonPostBattle:
	.string "POKéMON và HLV học được rất\n"
	.string "nhiều qua chiến đấu.\p"
	.string "Điều quan trọng là dù thua cũng không\n"
	.string "bao giờ bỏ cuộc.$"

Route111_Text_WiltonRegister:
	.string "Tôi học được nhiều điều từ cách luyện\n"
	.string "tập của bạn.\p"
	.string "Nếu tiện, mong bạn cho tôi cơ hội tái\n"
	.string "đấu.$"

Route111_Text_WiltonRematchIntro:
	.string "Chúng tôi đang luyện tập ở đây để\n"
	.string "vươn lên một tầm cao mới. Hãy ở lại\l"
	.string "luyện cùng chúng tôi!$"

Route111_Text_WiltonRematchDefeat:
	.string "Ồ, bạn khá đấy!$"

Route111_Text_WiltonPostRematch:
	.string "Mạnh đến vậy thì bạn nên nhắm tới\n"
	.string "POKéMON LEAGUE.$"

Route111_Text_BrookeIntro:
	.string "Ồ, POKéMON của bạn trông đúng là những\n"
	.string "đấu thủ đáng gờm. Tôi phải xin bạn một\l"
	.string "trận mới được.$"

Route111_Text_BrookeDefeat:
	.string "Chúng không chỉ trông mạnh, mà thật sự\n"
	.string "rất mạnh!$"

Route111_Text_BrookePostBattle:
	.string "Tôi cứ nghĩ mình đã chăm chỉ nuôi dạy\n"
	.string "POKéMON, nhưng ôi không, vẫn còn rất\l"
	.string "nhiều việc phải làm.$"

Route111_Text_BrookeRegister:
	.string "Ước gì tôi có thể kết bạn với nhiều\n"
	.string "người mạnh như bạn hơn nữa!$"

Route111_Text_BrookeRematchIntro:
	.string "Các chiêu bạn dạy có thể khiến POKéMON\n"
	.string "mạnh lên hoặc yếu đi.\p"
	.string "POKéMON của bạn biết những chiêu gì?$"

Route111_Text_BrookeRematchDefeat:
	.string "Bạn đã dạy chúng những chiêu rất hay!$"

Route111_Text_BrookePostRematch:
	.string "Có lẽ tôi nên ngăn POKéMON tiến hóa cho\n"
	.string "đến khi chúng học được những chiêu\l"
	.string "tốt hơn...$"

Route111_Text_CeliaIntro:
	.string "Đáng lẽ tôi không nên đến một nơi thế\n"
	.string "này để dã ngoại!$"

Route111_Text_CeliaDefeat:
	.string "Hu hu! Mình thật sự không nên đến đây!$"

Route111_Text_CeliaPostBattle:
	.string "Giữa bão cát thế này, dù đeo\n"
	.string "GO-GOGGLES tôi cũng không thể bày biện\l"
	.string "chỗ dã ngoại...$"

Route111_Text_BryanIntro:
	.string "Bạn mạnh đến đâu? Ta sẽ khám phá bí\n"
	.string "mật đó!$"

Route111_Text_BryanDefeat:
	.string "Ô! Sức mạnh của bạn! Thật bí ẩn khôn\n"
	.string "lường!$"

Route111_Text_BryanPostBattle:
	.string "Sa mạc này cất giấu bao bí ẩn dưới\n"
	.string "những lớp cát luôn dịch chuyển!$"

Route111_Text_BrandenIntro:
	.string "Nếu bạn chịu thua, tôi sẽ chia cho bạn\n"
	.string "một ít bánh kẹp.$"

Route111_Text_BrandenDefeat:
	.string "Chậc! Tôi cứ tưởng một chiếc bánh kẹp\n"
	.string "là đủ để mua chuộc bạn...$"

Route111_Text_BrandenPostBattle:
	.string "SANDSHREW của tôi mê ăn bánh kẹp của\n"
	.string "tôi lắm.$"

Route111_Text_TyronIntro:
	.string "Đây là loại POKéMON tôi thích nhất!$"

Route111_Text_TyronDefeat:
	.string "Khoan! Bạn đã nhìn kỹ POKéMON của tôi\n"
	.string "chưa?$"

Route111_Text_TyronPostBattle:
	.string "Mỗi khi chiến đấu, tôi thích thú nhất là\n"
	.string "được khoe POKéMON của mình.\p"
	.string "Tôi cá ai bước vào trận đấu cũng cảm\n"
	.string "thấy vậy!$"

Route111_Text_CelinaIntro:
	.string "Hãy chỉ tôi cách làm cuộc đời thú vị\n"
	.string "hơn một chút.$"

Route111_Text_CelinaDefeat:
	.string "Ôi... Trời ơi... Thế này phấn khích quá\n"
	.string "mức rồi.$"

Route111_Text_CelinaPostBattle:
	.string "Tim tôi vẫn đập thình thịch. Bạn đúng là\n"
	.string "một HLV tuyệt vời.$"

Route111_Text_HaydenIntro:
	.string "Đói lả như tôi thì chẳng còn chỗ cho\n"
	.string "lòng thương hại đâu!$"

Route111_Text_HaydenDefeat:
	.string "Ư...$"

Route111_Text_HaydenPostBattle:
	.string "Bụng tôi đang réo ầm lên! Hay là nướng\n"
	.string "ít BERRIES nhỉ...$"

Route111_Text_BiancaIntro:
	.string "Bạn đến từ MAUVILLE à? Vậy hẳn phải\n"
	.string "tràn đầy năng lượng!$"

Route111_Text_BiancaDefeat:
	.string "Úi chà! Thế này quá sức chịu đựng rồi!$"

Route111_Text_BiancaPostBattle:
	.string "Con đường này... Bạn còn phải đi xa lắm.$"

Route112_Text_BriceIntro:
	.string "Ha ha ha! Ta đấu một trận nhé? Bạn với\n"
	.string "tôi! Ha ha ha!$"

Route112_Text_BriceDefeat:
	.string "Tôi thua rồi! Ha ha ha!$"

Route112_Text_BricePostBattle:
	.string "Ha ha ha ha ha! Có gì bay vào mũi tôi rồi!\n"
	.string "Ha ha ha... hắt xì!$"

Route112_Text_TrentIntro:
	.string "Đôi chân tôi rắn chắc nhờ miệt mài leo\n"
	.string "lên xuống núi.\p"
	.string "Chúng không dễ khuỵu đâu, bạn hiền!$"

Route112_Text_TrentDefeat:
	.string "Ái! Chân tôi bị chuột rút!$"

Route112_Text_TrentPostBattle:
	.string "Thử đeo ba lô nặng hàng chục pound rồi\n"
	.string "đi bộ thật lực trên những đường núi\l"
	.string "này xem.\p"
	.string "Bạn hiền à, làm vậy thì cơ thể sẽ săn\n"
	.string "chắc vô cùng.$"

Route112_Text_TrentRegister:
	.string "Ối, chân tôi chuột rút rồi. Lấy giúp tôi\n"
	.string "ít băng gạc trong ba lô nhé?\p"
	.string "Không, đó là POKéNAV của tôi! Thôi\n"
	.string "được, tôi sẽ đăng ký bạn.$"

Route112_Text_TrentRematchIntro:
	.string "Tôi vẫn giữ dáng bằng cách đi bộ đường\n"
	.string "dài. Sức mạnh thì tôi có thừa!$"

Route112_Text_TrentRematchDefeat:
	.string "Tôi lại thua về sức mạnh sao?$"

Route112_Text_TrentRematchPostBattle:
	.string "Nghe nói trên đỉnh MT. CHIMNEY có vài\n"
	.string "HLV cực kỳ mạnh.\p"
	.string "Tôi nhất định sẽ lên đó thách đấu họ!$"

Route112_Text_LarryIntro:
	.string "Tôi mạnh lắm. Thua tôi cũng không khóc\n"
	.string "đâu.$"

Route112_Text_LarryDefeat:
	.string "Oa oa!$"

Route112_Text_LarryPostBattle:
	.string "Tôi không khóc vì nhớ mẹ đâu! Sụt sịt...$"

Route112_Text_CarolIntro:
	.string "Đi dã ngoại thì tất nhiên phải hát rồi!\n"
	.string "Nào, hát cùng tôi đi!$"

Route112_Text_CarolDefeat:
	.string "Ôi, bạn mạnh quá!$"

Route112_Text_CarolPostBattle:
	.string "Hát hay hay dở, dùng POKéMON giỏi hay\n"
	.string "kém đều không quan trọng.\p"
	.string "Ai vui nhất, người đó thắng!$"

Route112_Text_BryantIntro:
	.string "Tôi bắt được POKéMON nóng bỏng trong\n"
	.string "FIERY PATH! Xem này!$"

Route112_Text_BryantDefeat:
	.string "Đúng là một trận xóc nảy!$"

Route112_Text_BryantPostBattle:
	.string "Tôi thích cách bạn chiến đấu. Có nét\n"
	.string "rất riêng.$"

Route112_Text_ShaylaIntro:
	.string "Ôi, bạn đúng là một HLV đáng yêu!\n"
	.string "Làm ơn, tôi cần một trận đấu lãng mạn!\l"
	.string "Tôi cũng khá lắm đấy!$"

Route112_Text_ShaylaDefeat:
	.string "Ôi, bạn mạnh quá! Làm tôi choáng thật\n"
	.string "đấy!$"

Route112_Text_ShaylaPostBattle:
	.string "Giờ bạn có bận không? Tôi đang nghĩ\n"
	.string "hay là ta tái đấu ngay bây giờ... Nhưng\l"
	.string "nếu bạn bận thì cũng không sao.$"

Route113_Text_JaylenIntro:
	.string "Bạn đoán được vì sao quanh đây mát mẻ\n"
	.string "thế không?$"

Route113_Text_JaylenDefeat:
	.string "Eo ôi! Hôi quá!$"

Route113_Text_JaylenPostBattle:
	.string "Tro núi lửa che khuất mặt trời nên trời\n"
	.string "không ấm lên mấy.\p"
	.string "Với tôi thế lại hay, tôi không chịu nổi\n"
	.string "nóng!$"

Route113_Text_DillonIntro:
	.string "Núi lửa phun trào là bằng chứng Trái\n"
	.string "Đất đang sống.$"

Route113_Text_DillonDefeat:
	.string "Bạn mạnh dữ dội thật!$"

Route113_Text_DillonPostBattle:
	.string "Ái! Ái da! Tôi không thấy gì cả! Tro dính\n"
	.string "vào lông mi rồi!\p"
	.string "Hiểu không? Tro với lông mi ấy?\p"
	.string "Được rồi, câu đó dở thật, xin lỗi...$"

Route113_Text_MadelineIntro:
	.string "Tôi dùng chiếc ô này để bảo vệ NUMEL\n"
	.string "yêu quý khỏi thứ tro núi lửa bẩn thỉu,\l"
	.string "ghê tởm kia.$"

Route113_Text_MadelineDefeat:
	.string "Hộc, hộc... Tôi kiệt sức rồi...$"

Route113_Text_MadelinePostBattle:
	.string "Bạn giỏi thật đấy. Phải nói là tôi rất ấn\n"
	.string "tượng!$"

Route113_Text_MadelineRegister:
	.string "Nào, vào nép dưới ô của tôi đi. Để tôi\n"
	.string "đăng ký bạn vào POKéNAV.$"

Route113_Text_MadelineRematchIntro:
	.string "Ồ, xin chào, lâu rồi không gặp nhỉ? Tôi\n"
	.string "có thể mời bạn đấu một trận không?$"

Route113_Text_MadelineRematchDefeat:
	.string "Ôi, tuyệt quá!$"

Route113_Text_MadelinePostRematch:
	.string "Bạn vẫn giỏi như trước. Phải nói là tôi\n"
	.string "rất ấn tượng!$"

Route113_Text_LaoIntro:
	.string "Ta bật ra từ trong tro bụi! Hây da! Ta\n"
	.string "thách đấu ngươi!$"

Route113_Text_LaoDefeat:
	.string "Ta xin nhận thua trong danh dự!$"

Route113_Text_LaoPostBattle:
	.string "Ta phải trau dồi thuật ẩn thân. Xin cáo\n"
	.string "từ.$"

Route113_Text_LaoRegister:
	.string "Hây da! Hãy chứng kiến tuyệt kỹ ninja\n"
	.string "cổ truyền: đăng ký POKéNAV!$"

Route113_Text_LaoRematchIntro:
	.string "Ta bật ra từ trong tro bụi! Hây da! Ta\n"
	.string "thách đấu ngươi!$"

Route113_Text_LaoRematchDefeat:
	.string "Ta xin nhận thua trong danh dự!$"

Route113_Text_LaoPostRematch:
	.string "Thuật ẩn thân hoàn hảo của ta đã bị kỹ\n"
	.string "năng chiến đấu non nớt làm hỏng...\p"
	.string "Xin cáo từ.$"

Route113_Text_LungIntro:
	.string "Cảm ơn vì đã tìm ra tôi! Nhưng ta vẫn\n"
	.string "phải đấu!$"

Route113_Text_LungDefeat:
	.string "Tôi sẽ dùng nhẫn thuật với bạn...\n"
	.string "VOLCANIC ASH SWIRL CLOAK!\p"
	.string "...Gì cơ? Xong rồi à?$"

Route113_Text_LungPostBattle:
	.string "Bạn biết điều tệ nhất khi trốn là gì\n"
	.string "không? Nếu chẳng ai đến thì cô đơn lắm.$"

Route113_Text_ToriIntro:
	.string "TORI: Cả hai chúng tôi đều nhặt tro.\n"
	.string "Chúng tôi cũng đấu POKéMON.$"

Route113_Text_ToriDefeat:
	.string "TORI: Chúng tôi thua rồi... Chán quá, nên\n"
	.string "tôi sẽ đi nhặt thêm tro.$"

Route113_Text_ToriPostBattle:
	.string "TORI: Chúng ta có bao nhiêu tro rồi? Hy\n"
	.string "vọng là đủ làm một chiếc WHITE FLUTE.$"

Route113_Text_ToriNotEnoughMons:
	.string "TORI: Bọn mình muốn đấu 2 chọi 2. Không\n"
	.string "đấu vậy thì bọn mình sẽ thua mất!$"

Route113_Text_TiaIntro:
	.string "TIA: Cả hai bọn mình đều nhặt tro. Bọn\n"
	.string "mình cũng đấu POKéMON nữa.$"

Route113_Text_TiaDefeat:
	.string "TIA: Bọn mình không thắng được... Chán\n"
	.string "quá, mình đi nhặt thêm tro đây.$"

Route113_Text_TiaPostBattle:
	.string "TIA: Bọn mình có nhiều tro lắm! Chắc đủ\n"
	.string "làm một chiếc WHITE FLUTE rồi!$"

Route113_Text_TiaNotEnoughMons:
	.string "TIA: Bọn mình muốn đấu 2 chọi 2. Không\n"
	.string "đấu vậy thì bọn mình không thắng nổi!$"

Route113_Text_CobyIntro:
	.string "Hừ, với đôi cánh này, tôi có thể hất bay\n"
	.string "cậu!$"

Route113_Text_CobyDefeat:
	.string "Ơ... Gì cơ?$"

Route113_Text_CobyPostBattle:
	.string "Tôi chẳng biết phải nói gì khi bị hạ dễ\n"
	.string "dàng đến thế...$"

Route113_Text_SophieIntro:
	.string "Ở đây ấm quá làm tôi buồn ngủ. Đấu với\n"
	.string "tôi để tôi tỉnh táo nào.$"

Route113_Text_SophieDefeat:
	.string "Đây là một giấc mơ. Chắc chắn là vậy...$"

Route113_Text_SophiePostBattle:
	.string "Thua trận làm tôi nóng cả người... Tôi sẽ\n"
	.string "ngủ ngay tại đây! Khò khò!$"

Route113_Text_LawrenceIntro:
	.string "Có phải cậu đang bận thu gom tro núi\n"
	.string "lửa không?$"

Route113_Text_LawrenceDefeat:
	.string "Ehehe. Bọn tôi bị đánh bại hoàn toàn rồi.$"

Route113_Text_LawrencePostBattle:
	.string "Tôi cũng nên chui xuống tro mà trốn.$"

Route113_Text_WyattIntro:
	.string "C-cậu muốn đấu với tôi sao? Dù tôi vừa\n"
	.string "mới bắt được POKéMON à?$"

Route113_Text_WyattDefeat:
	.string "C-cậu vui lắm vì thắng được tôi sao?\n"
	.string "Dù đối thủ chỉ là tôi thôi à?$"

Route113_Text_WyattPostBattle:
	.string "Ồ, giờ cậu lại muốn nói vài lời với kẻ\n"
	.string "thua cuộc sao?\p"
	.string "Cậu ngầu quá cơ nhỉ? Hừ!$"

Route114_Text_LennyIntro:
	.string "Yodelayhihoo!\p"
	.string "... ...\p"
	.string "Đáng lẽ cậu phải hét Yodelayhihoo chứ,\n"
	.string "vì ở đây đâu có tiếng vọng!$"

Route114_Text_LennyDefeat:
	.string "Yodelayhihoo!$"

Route114_Text_LennyPostBattle:
	.string "Hồi còn bé xíu, tôi từng tin rằng có ai\n"
	.string "đó bắt chước mình rồi hét vọng lại:\l"
	.string "Yodelayhihoo.$"

Route114_Text_LucasIntro:
	.string "Nếu chưa chuẩn bị kỹ thì đừng lên núi!$"

Route114_Text_LucasDefeat:
	.string "Núi non không hề khoan nhượng...$"

Route114_Text_LucasPostBattle:
	.string "Vào mùa đông, núi non trở nên chết chóc\n"
	.string "vì bão tuyết và tuyết lở.$"

Route114_Text_ShaneIntro:
	.string "Cắm trại vui lắm! Có thể câu cá, nướng\n"
	.string "kẹo marshmallow và kể chuyện ma!\p"
	.string "Nhưng tuyệt nhất vẫn là những trận\n"
	.string "đấu POKéMON!$"

Route114_Text_ShaneDefeat:
	.string "Mạnh quá sức!$"

Route114_Text_ShanePostBattle:
	.string "Được đi cắm trại cùng POKéMON của mình\n"
	.string "thật tuyệt.$"

Route114_Text_NancyIntro:
	.string "Sau bữa ăn, tôi cần vận động một chút.\n"
	.string "Đấu một trận nhé!$"

Route114_Text_NancyDefeat:
	.string "Ôi không!$"

Route114_Text_NancyPostBattle:
	.string "Tôi vừa ăn một bữa ngon lành. Giờ buồn\n"
	.string "ngủ quá...$"

Route114_Text_SteveIntro:
	.string "Ufufufufufu... Muốn đấu với POKéMON\n"
	.string "của tôi không?$"

Route114_Text_SteveDefeat:
	.string "P-POKéMON của tôi...$"

Route114_Text_StevePostBattle:
	.string "Một thân hình to lớn, gồ ghề và cứng\n"
	.string "cáp, cặp sừng khổng lồ cùng những\l"
	.string "chiếc nanh hung tợn...\p"
	.string "Ufufufufu... Ước gì tôi có một POKéMON\n"
	.string "như thế...$"

Route114_Text_SteveRegister:
	.string "Đừng quên những gì cậu đã làm với tôi!\n"
	.string "Tôi sẽ khiến cậu không thể nào quên!$"

Route114_Text_SteveRematchIntro:
	.string "Ufufufufufu... Nào, hãy đấu với POKéMON\n"
	.string "của tôi đi...$"

Route114_Text_SteveRematchDefeat:
	.string "Được nhìn thấy POKéMON của cậu, tôi\n"
	.string "thật may mắn...$"

Route114_Text_StevePostRematch:
	.string "Ufufufufufu...\p"
	.string "Mỗi khi thấy POKéMON chiến đấu, tôi lại\n"
	.string "run lên bần bật...$"

Route114_Text_BernieIntro:
	.string "Nếu nhóm lửa trại, hãy nhớ để sẵn nước\n"
	.string "bên cạnh.$"

Route114_Text_BernieDefeat:
	.string "Cảm ơn đã dập tắt ngọn lửa của tôi!$"

Route114_Text_BerniePostBattle:
	.string "Trong rừng, thật sự phải cẩn thận với\n"
	.string "bất kỳ ngọn lửa nào.\p"
	.string "Đừng bao giờ xem thường sức mạnh của\n"
	.string "lửa.$"

Route114_Text_BernieRegister:
	.string "Cậu đã thắp bùng ngọn lửa trong tôi.\n"
	.string "Hãy đăng ký liên lạc với nhau!$"

Route114_Text_BernieRematchIntro:
	.string "Cậu đã học được cách để sẵn nước bên\n"
	.string "cạnh khi nhóm lửa trại chưa?$"

Route114_Text_BernieRematchDefeat:
	.string "Chắc là tôi đã bị xịt ướt trước khi kịp\n"
	.string "bùng cháy rồi.$"

Route114_Text_BerniePostRematch:
	.string "Trong rừng, thật sự phải cẩn thận với\n"
	.string "bất kỳ ngọn lửa nào.\p"
	.string "Đừng bao giờ xem thường sức mạnh của\n"
	.string "lửa.$"

Route114_Text_ClaudeIntro:
	.string "Nếu thi câu cá, cậu chẳng có cửa thắng\n"
	.string "tôi đâu. Vậy nên, hãy cho POKéMON của\l"
	.string "cậu ra đi!$"

Route114_Text_ClaudeDefeat:
	.string "Nếu là thi câu cá thì tôi đã thắng rồi...$"

Route114_Text_ClaudePostBattle:
	.string "Tôi sẽ thử vận may, câu một con thật\n"
	.string "lớn ở METEOR FALLS.\p"
	.string "Trong đó chắc chắn phải có thứ gì đó.\n"
	.string "Tôi biết mà.$"

Route114_Text_NolanIntro:
	.string "Tôi thích câu cá. Nhưng tôi cũng thích\n"
	.string "chiến đấu!\p"
	.string "Hễ ai thách đấu, tôi sẽ nhận lời, kể cả\n"
	.string "khi đang câu cá.$"

Route114_Text_NolanDefeat:
	.string "Tôi thích chiến đấu, nhưng đâu có\n"
	.string "nghĩa là tôi giỏi...$"

Route114_Text_NolanPostBattle:
	.string "Lần này nhất định sẽ được!\p"
	.string "Lúc nào tôi cũng nghĩ vậy, nên chẳng\n"
	.string "thể dứt khỏi câu cá hay POKéMON.$"

Route114_Text_TyraIntro:
	.string "TYRA: Ừ, được thôi. Tôi đang có hứng.\n"
	.string "Để tôi dạy cậu đôi điều về POKéMON.$"

Route114_Text_TyraDefeat:
	.string "TYRA: Phong cách chiến đấu thật đáng\n"
	.string "kinh ngạc!$"

Route114_Text_TyraPostBattle:
	.string "TYRA: Tôi đang dạy đàn em IVY về\n"
	.string "POKéMON.$"

Route114_Text_TyraNotEnoughMons:
	.string "TYRA: Khúc khích... Nếu muốn đấu với bọn\n"
	.string "tôi, chỉ một POKéMON là không đủ đâu!$"

Route114_Text_IvyIntro:
	.string "IVY: Ai đã dạy cậu về POKéMON vậy?$"

Route114_Text_IvyDefeat:
	.string "IVY: Phong cách chiến đấu thật đáng\n"
	.string "kinh ngạc!$"

Route114_Text_IvyPostBattle:
	.string "IVY: Tôi bắt đầu huấn luyện POKéMON\n"
	.string "nhờ được đàn chị TYRA chỉ dạy!$"

Route114_Text_IvyNotEnoughMons:
	.string "IVY: Cậu chỉ có một POKéMON thôi sao?\n"
	.string "Tôi nghĩ nó hẳn sẽ cô đơn lắm.$"

Route114_Text_KaiIntro:
	.string "Tôi câu được một con lớn lắm! Khổng lồ\n"
	.string "luôn, tôi nói thật đấy!$"

Route114_Text_KaiDefeat:
	.string "Chuyện đó là sao? Con của tôi thua về\n"
	.string "kích cỡ à?$"

Route114_Text_KaiPostBattle:
	.string "Được! Tôi chỉ cần câu một con lớn hơn\n"
	.string "nữa!$"

Route114_Text_CharlotteIntro:
	.string "Tôi ấy à! Tôi đâu chỉ có gương mặt xinh\n"
	.string "đẹp!$"

Route114_Text_CharlotteDefeat:
	.string "Chẳng đáng yêu chút nào!$"

Route114_Text_CharlottePostBattle:
	.string "Tôi không muốn một POKéMON chỉ được\n"
	.string "mỗi vẻ dễ thương.\p"
	.string "Tôi mê những bé dễ thương mà còn có\n"
	.string "một hai nét khác lạ cơ!$"

Route114_Text_AngelinaIntro:
	.string "Cậu đã cho POKéMON của mình tiến hóa\n"
	.string "nhiều chưa?$"

Route114_Text_AngelinaDefeat:
	.string "Ồ, ra vậy. Biết được điều đó thật tốt.$"

Route114_Text_AngelinaPostBattle:
	.string "Một số POKéMON thay đổi nhiều đến mức\n"
	.string "khiến người ta giật mình khi tiến hóa!$"

Route115_Text_TimothyIntro:
	.string "Hừm... Cậu có vẻ khá tài giỏi... Để tôi\n"
	.string "tiếp cậu một trận!$"

Route115_Text_TimothyDefeat:
	.string "Cậu mạnh hơn tôi tưởng rất nhiều!$"

Route115_Text_TimothyPostBattle:
	.string "Không ai sinh ra đã là thiên tài. Tất cả\n"
	.string "đều phụ thuộc vào nỗ lực! Đó là điều tôi\l"
	.string "tin...$"

Route115_Text_TimothyRegister:
	.string "Hừm... Đã lâu lắm rồi tôi mới thua triệt\n"
	.string "để đến thế.\p"
	.string "Nếu cậu cho phép, tôi mong có thêm một\n"
	.string "cơ hội để giao đấu.$"

Route115_Text_TimothyRematchIntro:
	.string "Hừm... Như mọi khi, sự nhanh nhẹn của\n"
	.string "cậu đã nói lên tất cả. Nào, hãy đấu với\l"
	.string "tôi!$"

Route115_Text_TimothyRematchDefeat:
	.string "Vẫn mạnh mẽ như xưa!$"

Route115_Text_TimothyPostRematch:
	.string "Chỉ cần nỗ lực là được!\p"
	.string "Tôi thua vì mình chưa nỗ lực đủ!$"

Route115_Text_KoichiIntro:
	.string "Ngươi kia!\p"
	.string "Các MACHOP của ta!\p"
	.string "Đang đòi giao đấu!$"

Route115_Text_KoichiDefeat:
	.string "Đau, đau, đau quá!$"

Route115_Text_KoichiPostBattle:
	.string "Các MACHOP của ta!\p"
	.string "Chừng nào chúng còn khao khát sức\n"
	.string "mạnh, ta sẽ mạnh lên cùng chúng!$"

Route115_Text_NobIntro:
	.string "Sở trường lợi hại nhất của tôi là dùng\n"
	.string "trán đập vỡ gạch!$"

Route115_Text_NobDefeat:
	.string "Ugwaaaah! Đầu tôi vỡ mất rồi!$"

Route115_Text_NobPostBattle:
	.string "Tôi đã dạy POKéMON của mình karate.\p"
	.string "Có vẻ chúng sẽ giỏi hơn tôi rất nhiều.\n"
	.string "Nghĩ thôi đã thấy hào hứng rồi.$"

Route115_Text_NobRegister:
	.string "Cậu khiến tôi khâm phục đấy! Hãy tái\n"
	.string "đấu sau khi tôi luyện tập lại!$"

Route115_Text_NobRematchIntro:
	.string "Sau khi bị cậu đánh bại, chúng tôi đã\n"
	.string "khổ luyện để nâng cao kỹ năng. Nào, hãy\l"
	.string "tái đấu với chúng tôi!$"

Route115_Text_NobRematchDefeat:
	.string "Ugwaaah! Chúng tôi lại thua rồi!$"

Route115_Text_NobPostRematch:
	.string "POKéMON của tôi sẽ mạnh hơn nữa! Tôi sẽ\n"
	.string "tăng gấp đôi cường độ luyện tập!$"

Route115_Text_CyndyIntro:
	.string "Bãi biển này là nơi luyện tập bí mật của\n"
	.string "tôi! Đừng có xông vào!$"

Route115_Text_CyndyDefeat:
	.string "Tôi vẫn chưa luyện tập đủ!$"

Route115_Text_CyndyPostBattle:
	.string "Cát đóng vai trò như lớp đệm, giúp giảm\n"
	.string "chấn động và ngăn chấn thương. Đây là\l"
	.string "nơi hoàn hảo để luyện tập.$"

Route115_Text_CyndyRegister:
	.string "Thôi được rồi, cậu cứ tự nhiên đến đây.\n"
	.string "Đổi lại, tôi muốn đấu với cậu lần nữa.$"

Route115_Text_CyndyRematchIntro:
	.string "Được rồi, bắt đầu trận đấu thôi!$"

Route115_Text_CyndyRematchDefeat:
	.string "Tôi vẫn có thể chiến đấu, nhưng\n"
	.string "POKéMON của tôi thì...$"

Route115_Text_CyndyPostRematch:
	.string "Dù thua, tôi vẫn thấy vui. Chắc là vì tôi\n"
	.string "yêu POKéMON.$"

Route115_Text_HectorIntro:
	.string "Tôi có một POKéMON hiếm đấy! Cậu có\n"
	.string "muốn tôi cho xem không?$"

Route115_Text_HectorDefeat:
	.string "Cậu... Cậu muốn lấy POKéMON của tôi,\n"
	.string "đúng không?$"

Route115_Text_HectorPostBattle:
	.string "Tôi có POKéMON hiếm này. Chỉ vậy thôi\n"
	.string "cũng đủ làm tôi mãn nguyện.$"

Route115_Text_KyraIntro:
	.string "Tôi sẽ vừa chạy vừa chiến đấu! Cố theo\n"
	.string "kịp tôi nhé!$"

Route115_Text_KyraDefeat:
	.string "Hộc, hộc...$"

Route115_Text_KyraPostBattle:
	.string "Tôi đã sai khi cố vừa chạy vừa chiến\n"
	.string "đấu!\p"
	.string "Tôi nên chạy một vòng để bình tĩnh lại...$"

Route115_Text_JaidenIntro:
	.string "Đỡ này! Tuyệt kỹ ninja POKéMON siêu\n"
	.string "cấp!$"

Route115_Text_JaidenDefeat:
	.string "Waaah! Chiến thuật của chúng ta thất\n"
	.string "bại rồi!$"

Route115_Text_JaidenPostBattle:
	.string "Nhưng mấy POKéMON của tôi siêu cấp lắm,\n"
	.string "đúng không?$"

Route115_Text_HeleneIntro:
	.string "POKéMON của tôi có sức mạnh tầm đai\n"
	.string "đen!$"

Route115_Text_HeleneDefeat:
	.string "Nhục nhã quá!$"

Route115_Text_HelenePostBattle:
	.string "Hiếm khi tôi gặp được ai giỏi hơn mình...\p"
	.string "Tôi hiểu rồi! Bạn là GYM LEADER, phải\n"
	.string "không?$"

Route115_Text_AlixIntro:
	.string "Ánh mắt chúng ta chạm nhau rồi! Giờ thì\n"
	.string "không thoát được đâu!$"

Route115_Text_AlixDefeat:
	.string "Á! Không tệ!$"

Route115_Text_AlixPostBattle:
	.string "Thôi được. Tôi sẽ dùng TELEPORT để về\n"
	.string "nhà.$"

Route115_Text_MarleneIntro:
	.string "Bạn đã quấy rầy lúc tôi thiền... Bạn sẽ bị\n"
	.string "trừng phạt.$"

Route115_Text_MarleneDefeat:
	.string "Bạn đã phá tan sự tập trung của tôi!$"

Route115_Text_MarlenePostBattle:
	.string "Tôi đang thiền cùng POKéMON. Nhưng nơi\n"
	.string "này chẳng yên tĩnh chút nào...$"

Route116_Text_ClarkIntro:
	.string "Nếu đường hầm không thông, tôi sẽ leo\n"
	.string "qua núi.$"

Route116_Text_ClarkDefeat:
	.string "Hộc... Hộc... Thua trận làm tôi mệt quá...$"

Route116_Text_ClarkPostBattle:
	.string "Không có đường hầm cũng chẳng sao.\n"
	.string "Với một HIKER, núi non chính là đường\l"
	.string "đi!$"

Route116_Text_JoeyIntro:
	.string "POKéMON của tôi vô địch! Xem đây!$"

Route116_Text_JoeyDefeat:
	.string "Ái! Trầy xước rồi! Phải dán băng thôi!$"

Route116_Text_JoeyPostBattle:
	.string "Băng dán là dấu hiệu của sự cứng cỏi!\n"
	.string "Tôi lại có thêm một miếng nữa rồi!$"

Route116_Text_JoseIntro:
	.string "BUG POKéMON của tôi mạnh lắm! Đấu nào!$"

Route116_Text_JoseDefeat:
	.string "Tôi thua rồi! Cứ tưởng đã thắng được\n"
	.string "bạn chứ!$"

Route116_Text_JosePostBattle:
	.string "BUG POKéMON tiến hóa rất nhanh. Vì thế\n"
	.string "chúng cũng mạnh lên rất nhanh.$"

Route116_Text_JaniceIntro:
	.string "Để tôi cho bạn thấy POKéMON đáng yêu\n"
	.string "của tôi mạnh đến mức nào!$"

Route116_Text_JaniceDefeat:
	.string "Bạn trên cơ tôi một bậc...$"

Route116_Text_JanicePostBattle:
	.string "POKéMON vừa đáng yêu vừa mạnh mẽ,\n"
	.string "theo tôi đó mới là lý tưởng.$"

Route116_Text_JerryIntro:
	.string "Chúng tôi học đủ thứ ở TRAINER'S\n"
	.string "SCHOOL.\p"
	.string "Tôi muốn thử áp dụng vào thực chiến!$"

Route116_Text_JerryDefeat:
	.string "Tôi đã lười học... Vì thế nên mới thua.$"

Route116_Text_JerryPostBattle:
	.string "Tôi sẽ phải học lại vài khóa ở TRAINER'S\n"
	.string "SCHOOL. Nếu không, ROXANNE sẽ nổi giận\l"
	.string "mất.$"

Route116_Text_JerryRegister1:
	.string "Tôi học ở TRAINER'S SCHOOL rằng\n"
	.string "POKéNAV có thể đăng ký HLV.\p"
	.string "Tôi không hiểu rõ lắm, nên cứ để tôi thử\n"
	.string "được không?$"

Route116_Text_JerryRegister2:
	.string "Tôi học ở TRAINER'S SCHOOL rằng\n"
	.string "POKéNAV có thể đăng ký HLV.\p"
	.string "Tôi không hiểu rõ lắm, nên cứ để tôi thử\n"
	.string "được không?$"

Route116_Text_JerryRematchIntro:
	.string "Tôi đã học hành nghiêm túc ở TRAINER'S\n"
	.string "SCHOOL. Lần này tôi sẽ không thua như\l"
	.string "trước đâu.$"

Route116_Text_JerryRematchDefeat:
	.string "Hả? Tôi đã học rất chăm chỉ mà.$"

Route116_Text_JerryPostRematch:
	.string "Tôi sẽ phải học lại vài khóa ở TRAINER'S\n"
	.string "SCHOOL. Nếu không, ROXANNE sẽ nổi giận\l"
	.string "mất.$"

Route116_Text_KarenIntro:
	.string "Tôi học ở trường, rồi trên đường về\n"
	.string "nhà cũng học nữa!$"

Route116_Text_KarenDefeat:
	.string "Tôi sốc quá, tôi thua ư?$"

Route116_Text_KarenPostBattle:
	.string "Hu hu, thế này thì tôi sẽ chẳng bao giờ\n"
	.string "trở thành một HLV thanh lịch như\l"
	.string "ROXANNE mất!$"

Route116_Text_KarenRegister1:
	.string "Ôi, tuyệt quá! Đó là POKéNAV phải\n"
	.string "không? Tôi cũng có một cái! Hãy đăng ký\l"
	.string "tôi nhé!$"

Route116_Text_KarenRegister2:
	.string "Ôi, tuyệt quá! Đó là POKéNAV phải\n"
	.string "không? Tôi cũng có một cái! Hãy đăng ký\l"
	.string "tôi nhé!$"

Route116_Text_KarenRematchIntro:
	.string "Từ lần gặp bạn, tôi đã học rất nhiều.\n"
	.string "Bạn nhất định phải xem thành quả của\l"
	.string "tôi!$"

Route116_Text_KarenRematchDefeat:
	.string "Tôi sốc quá. Tôi lại thua ư?$"

Route116_Text_KarenPostRematch:
	.string "Bạn đã đánh bại ROXANNE sao? Vậy thì\n"
	.string "tôi chưa thể thắng bạn. Chưa đâu.$"

Route116_Text_SarahIntro:
	.string "Nói trước nhé, từ trước tới giờ tôi\n"
	.string "chưa từng bị ai đánh bại trong bất cứ\l"
	.string "việc gì.$"

Route116_Text_SarahDefeat:
	.string "Ôi trời. Đây quả là một trải nghiệm mới\n"
	.string "đối với tôi.$"

Route116_Text_SarahPostBattle:
	.string "Cuộc sống xa hoa cho tôi mọi thứ mình\n"
	.string "có thể ao ước.\p"
	.string "Nhưng khi nói đến POKéMON, tiền bạc của\n"
	.string "tôi chẳng có ý nghĩa gì.$"

Route116_Text_DawsonIntro:
	.string "Chỉ cần ngắm bộ lông lộng lẫy của\n"
	.string "POKéMON tôi, vẻ đẹp ấy sẽ khiến bạn\l"
	.string "không thể chống cự!$"

Route116_Text_DawsonDefeat:
	.string "Ôi trời, đừng nói là thật chứ!$"

Route116_Text_DawsonPostBattle:
	.string "Không, không, không! Bạn làm rối tung bộ\n"
	.string "lông của POKéMON tôi rồi! Kiểu tóc của\l"
	.string "tôi cũng hỏng luôn! Tôi phải gọi nhà tạo\l"
	.string "mẫu ngay!$"

Route116_Text_DevanIntro:
	.string "Bọn tôi sẽ cho bạn rung chuyển tới bến!$"

Route116_Text_DevanDefeat:
	.string "Ái da da! Chẳng cân sức chút nào!$"

Route116_Text_DevanPostBattle:
	.string "Tôi nên thử dùng những hệ POKéMON\n"
	.string "khác nhau. Đúng, tôi phải làm thế.$"

Route116_Text_JohnsonIntro:
	.string "Trên này là đường cụt. Tôi đang chán,\n"
	.string "đấu với tôi nhé?$"

Route116_Text_JohnsonDefeat:
	.string "Dù thua nhưng trận đấu vui thật.$"

Route116_Text_JohnsonPostBattle:
	.string "Bạn muốn ở lại đây làm bạn với tôi\n"
	.string "không?$"

Route117_Text_IsaacIntro:
	.string "Này, bạn có thể đấu với những POKéMON\n"
	.string "tôi đang nuôi không?$"

Route117_Text_IsaacDefeat:
	.string "Bạn đã nuôi POKéMON của mình xuất sắc\n"
	.string "thật...$"

Route117_Text_IsaacPostBattle:
	.string "POKéMON không chỉ là sức mạnh.\p"
	.string "Mài giũa nét tính cách riêng của mỗi con\n"
	.string "cũng là một cách tận hưởng POKéMON.$"

Route117_Text_IsaacRegister:
	.string "Tôi sẽ tăng gấp đôi cường độ huấn\n"
	.string "luyện. Thỉnh thoảng bạn đến xem chúng\l"
	.string "tôi nhé?$"

Route117_Text_IsaacRematchIntro:
	.string "Những POKéMON tôi nuôi vẫn phát triển\n"
	.string "rất tốt như trước.$"

Route117_Text_IsaacRematchDefeat:
	.string "Bạn biết cách nuôi dạy chúng đúng cách.\n"
	.string "Có lẽ bạn có tố chất làm việc ở DAY\l"
	.string "CARE...$"

Route117_Text_IsaacPostRematch:
	.string "POKéMON của bạn lớn nhanh thật! Bạn\n"
	.string "nên cho chúng tham gia các cuộc thi.$"

Route117_Text_LydiaIntro:
	.string "Xin cho phép tôi đánh giá xem bạn đã\n"
	.string "nuôi dạy POKéMON đúng cách chưa.$"

Route117_Text_LydiaDefeat:
	.string "Vâng, chúng đang trưởng thành đúng\n"
	.string "hướng.$"

Route117_Text_LydiaPostBattle:
	.string "Hãy thử nuôi POKéMON và chú ý hơn tới\n"
	.string "đặc điểm tính cách của chúng.$"

Route117_Text_LydiaRegister:
	.string "Tôi rất vui vì đã gặp một HLV xuất\n"
	.string "sắc như bạn. Mong được gặp lại.$"

Route117_Text_LydiaRematchIntro:
	.string "Xin cho phép tôi đánh giá lại xem bạn đã\n"
	.string "nuôi dạy POKéMON đúng cách chưa.$"

Route117_Text_LydiaRematchDefeat:
	.string "Chúng đang trưởng thành thật đáng\n"
	.string "khâm phục.$"

Route117_Text_LydiaPostRematch:
	.string "Tùy tính cách, POKéMON dường như\n"
	.string "thích những loại {POKEBLOCK}S khác\l"
	.string "nhau.$"

Route117_Text_DylanIntro:
	.string "Tôi đang thi ba môn phối hợp, nhưng\n"
	.string "thôi kệ, đấu nào!$"

Route117_Text_DylanDefeat:
	.string "Tôi cạn năng lượng rồi!$"

Route117_Text_DylanPostBattle:
	.string "Có lẽ hỏng rồi...\p"
	.string "Trong lúc đấu, chắc tôi đã tụt xuống\n"
	.string "cuối mất...$"

Route117_Text_DylanRegister:
	.string "POKéMON cũng phải mạnh sao? Tôi muốn\n"
	.string "bạn huấn luyện tôi!$"

Route117_Text_DylanRematchIntro:
	.string "Tôi đang giữa cuộc thi ba môn phối hợp,\n"
	.string "nhưng hiện dẫn trước khá xa. Đấu nhanh\l"
	.string "một trận nào!$"

Route117_Text_DylanRematchDefeat:
	.string "Tôi lại cạn năng lượng rồi!$"

Route117_Text_DylanPostRematch:
	.string "Tôi đứng đầu môn bơi và đạp xe, nhưng\n"
	.string "với POKéMON thì vẫn chưa tự tin đến\l"
	.string "thế.$"

Route117_Text_MariaIntro:
	.string "Tôi luyện ba môn phối hợp cùng POKéMON,\n"
	.string "nên khá tự tin về tốc độ.$"

Route117_Text_MariaDefeat:
	.string "Có lẽ tôi cần tập luyện nhiều hơn.$"

Route117_Text_MariaPostBattle:
	.string "Việc tập luyện chỉ có ý nghĩa nếu bạn\n"
	.string "duy trì thường xuyên.\p"
	.string "Được rồi! Tôi sẽ tiếp tục tập luyện!\n"
	.string "Ngày mai!$"

Route117_Text_MariaRegister:
	.string "Có vẻ bạn đang luyện tập rất nghiêm\n"
	.string "túc... Nếu muốn, lần sau tôi sẽ đấu với\l"
	.string "bạn!$"

Route117_Text_MariaRematchIntro:
	.string "Bạn vẫn chăm chỉ luyện tập chứ? Tôi thì\n"
	.string "chắc chắn rồi! Để tôi cho bạn thấy bằng\l"
	.string "chứng!$"

Route117_Text_MariaRematchDefeat:
	.string "Có lẽ tôi cần tập luyện nhiều hơn.$"

Route117_Text_MariaPostRematch:
	.string "Ngày mai tôi sẽ tập lại. Khi nào đấu nữa\n"
	.string "nhé!$"

Route117_Text_DerekIntro:
	.string "Từng là BUG CATCHER! Giờ là BUG MANIAC!\p"
	.string "Nhưng tình yêu của tôi dành cho\n"
	.string "POKéMON vẫn không hề thay đổi!$"

Route117_Text_DerekDefeat:
	.string "Sự vụng về của tôi cũng chẳng thay\n"
	.string "đổi...$"

Route117_Text_DerekPostBattle:
	.string "Tôi chỉ làm theo con tim, vậy mà giờ họ\n"
	.string "gọi tôi là BUG MANIAC...\p"
	.string "Nhưng tôi là chuyên gia về BUG POKéMON,\n"
	.string "nên họ gọi tôi là BUG MANIAC cũng là\l"
	.string "chuyện đương nhiên.$"

Route117_Text_AnnaIntro:
	.string "ANNA: Tôi đang đi cùng cô bạn học khóa\n"
	.string "dưới xinh xắn. Tôi phải thể hiện thật\l"
	.string "tốt!$"

Route117_Text_AnnaDefeat:
	.string "ANNA: Tôi đang đi cùng cô bạn học khóa\n"
	.string "dưới xinh xắn! Hãy để tôi thắng đi!$"

Route117_Text_AnnaPostBattle:
	.string "ANNA: POKéMON của bạn phối hợp khá hay.\p"
	.string "Tôi cho rằng bạn chỉ đứng sau bọn tôi\n"
	.string "thôi!$"

Route117_Text_AnnaAndMegRegister:
	.string "ANNA: Bọn tôi không thể để yên chuyện\n"
	.string "này! Bạn sẽ quay lại chứ?$"

Route117_Text_AnnaNotEnoughMons:
	.string "ANNA: Nếu muốn đấu với bọn tôi, hãy\n"
	.string "mang theo hai POKéMON.$"

Route117_Text_MegIntro:
	.string "MEG: Tôi sẽ bắt cặp với đàn chị siêu giỏi\n"
	.string "của mình và đánh bại bạn!$"

Route117_Text_MegDefeat:
	.string "MEG: Ôi không! Em xin lỗi, ANNA! Em đã làm\n"
	.string "chị thất vọng...$"

Route117_Text_MegPostBattle:
	.string "MEG: Em đã cản chân chị ANNA... Nếu\n"
	.string "không vì em, chị ấy đã thắng rồi!$"

Route117_Text_MegNotEnoughMons:
	.string "MEG: Bạn chỉ có một POKéMON thôi à? Vậy\n"
	.string "bọn tôi không thể đấu với bạn.\p"
	.string "Bọn tôi muốn đấu 2 chọi 2.$"

Route117_Text_AnnaRematchIntro:
	.string "ANNA: Tôi không thể cứ thua trước mặt\n"
	.string "đàn em mãi được, phải không?$"

Route117_Text_AnnaRematchDefeat:
	.string "ANNA: Tôi không bắt được nhịp.$"

Route117_Text_AnnaPostRematch:
	.string "ANNA: POKéMON của bạn phối hợp khá hay.\p"
	.string "Tôi cho rằng bạn chỉ đứng sau bọn tôi\n"
	.string "thôi!$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "ANNA: Nếu muốn đấu với bọn tôi, hãy\n"
	.string "mang theo hai POKéMON.$"

Route117_Text_MegRematchIntro:
	.string "MEG: Tôi sẽ bắt cặp với đàn chị của mình\n"
	.string "và lần này nhất định thắng!$"

Route117_Text_MegRematchDefeat:
	.string "MEG: Mạnh quá!$"

Route117_Text_MegPostRematch:
	.string "MEG: Tôi đã chiến đấu cùng đàn chị, vậy\n"
	.string "mà bọn tôi vẫn thua...\p"
	.string "Nản quá...$"

Route117_Text_MegRematchNotEnoughMons:
	.string "MEG: Bạn chỉ có một POKéMON thôi à? Vậy\n"
	.string "bọn tôi không thể đấu với bạn.\p"
	.string "Bọn tôi muốn đấu 2 chọi 2.$"

Route117_Text_MelinaIntro:
	.string "Thật tuyệt phải không? Vừa ngắm hoa\n"
	.string "đẹp vừa chiến đấu?$"

Route117_Text_MelinaDefeat:
	.string "Ồ, ấn tượng thật đấy!$"

Route117_Text_MelinaPostBattle:
	.string "Vừa ngắm hoa vừa chạy bộ thật dễ chịu.$"

Route117_Text_BrandiIntro:
	.string "Để tôi cho bạn thấy sức mạnh ẩn giấu\n"
	.string "bên trong một PSYCHIC POKéMON!$"

Route117_Text_BrandiDefeat:
	.string "Kinh ngạc thật!$"

Route117_Text_BrandiPostBattle:
	.string "PSYCHIC POKéMON rất phức tạp. Bạn nên\n"
	.string "thử bắt vài con.$"

Route117_Text_AishaIntro:
	.string "Chỉ tập trung giành chiến thắng. Tôi\n"
	.string "chiến đấu như thế đấy!$"

Route117_Text_AishaDefeat:
	.string "Tôi không phí thời gian tức giận vì\n"
	.string "thua cuộc đâu. Tôi thà đi luyện tập còn\l"
	.string "hơn.$"

Route117_Text_AishaPostBattle:
	.string "Tôi nghĩ càng lo thua thì càng dễ thua.$"

Route118_Text_RoseIntro:
	.string "Hương hoa có một sức mạnh kỳ diệu. Nó\n"
	.string "thanh lọc cả thể xác lẫn tâm hồn chúng\l"
	.string "ta.$"

Route118_Text_RoseDefeat:
	.string "Ôi trời. Hình như tôi thua mất rồi.$"

Route118_Text_RosePostBattle:
	.string "Hoa, POKéMON... Tôi yêu mọi thứ có mùi\n"
	.string "thơm.\p"
	.string "Còn những thứ nặng mùi... Xin kiếu.$"

Route118_Text_RoseRegister:
	.string "Khịt khịt... Mùi đó... là POKéNAV! Chúng\n"
	.string "ta phải đăng ký nhau thôi!$"

Route118_Text_RoseRematchIntro:
	.string "Bạn bị hương thơm ngọt ngào dẫn lối\n"
	.string "đến đây sao?$"

Route118_Text_RoseRematchDefeat:
	.string "Sức mạnh của hương thơm... Có vẻ chẳng\n"
	.string "giúp được gì mấy.$"

Route118_Text_RosePostRematch:
	.string "Nếu dùng hương thơm ngọt ngào đúng\n"
	.string "cách, POKéMON sẽ bị thu hút.$"

Route118_Text_PerryIntro:
	.string "BIRD POKéMON FLY uyển chuyển trên bầu\n"
	.string "trời... Chúng là tuyệt nhất!$"

Route118_Text_PerryDefeat:
	.string "Ự... Tôi rơi mất rồi...$"

Route118_Text_PerryPostBattle:
	.string "POKéMON của bạn tuyệt thật. Tôi phải\n"
	.string "rèn luyện POKéMON của mình tốt hơn.$"

Route118_Text_ChesterIntro:
	.string "Cất cánh đi! BIRD POKéMON của ta!$"

Route118_Text_ChesterDefeat:
	.string "Chúng cất cánh thật rồi...$"

Route118_Text_ChesterPostBattle:
	.string "Nếu mạnh hơn, chúng sẽ có thể bay lượn\n"
	.string "tự do hơn...$"

Route118_Text_BarnyIntro:
	.string "Tôi là FISHERMAN, nhưng cũng là\n"
	.string "HLV. Tôi đang nuôi những POKéMON\l"
	.string "mình câu được.$"

Route118_Text_BarnyDefeat:
	.string "Tôi cứ tưởng việc luyện tập đang tiến\n"
	.string "triển tốt...$"

Route118_Text_BarnyPostBattle:
	.string "Tôi không thể thắng khi vừa câu cá vừa\n"
	.string "luyện POKéMON...\p"
	.string "Chẳng lẽ tôi đã làm mọi thứ nửa vời\n"
	.string "sao?$"

Route118_Text_WadeIntro:
	.string "Với FISHERMEN, trang bị là yếu tố then\n"
	.string "chốt.\p"
	.string "Nhưng với HLV, tất nhiên điều\n"
	.string "quan trọng là POKéMON và trái tim!$"

Route118_Text_WadeDefeat:
	.string "Ý chí của tôi cũng thua sao?$"

Route118_Text_WadePostBattle:
	.string "Nghĩ kỹ thì, câu cá là một trận chiến\n"
	.string "giữa FISHERMAN và POKéMON.$"

Route118_Text_DaltonIntro:
	.string "Hãy để giai điệu của tôi khuấy động tâm\n"
	.string "hồn bạn!$"

Route118_Text_DaltonDefeat:
	.string "La-lalala...$"

Route118_Text_DaltonPostBattle:
	.string "Guitar điện đâu phải lúc nào cũng ồn\n"
	.string "ào...\p"
	.string "Chỉ cần khảy dây, nó cũng có thể cất lên\n"
	.string "giai điệu lay động lòng người này...$"

Route118_Text_DaltonRegister:
	.string "Khi tôi sáng tác được những giai điệu\n"
	.string "hay hơn, bạn phải đến nghe nhé?$"

Route118_Text_DaltonRematchIntro:
	.string "Một giai điệu từ tôi và POKéMON của\n"
	.string "mình... Hãy để chúng tôi gửi nó đến tâm\l"
	.string "hồn bạn.$"

Route118_Text_DaltonRematchDefeat:
	.string "La-lalala...$"

Route118_Text_DaltonPostRematch:
	.string "Khi tôi chơi đàn, cảm xúc của tôi phải\n"
	.string "truyền đến bạn qua cây guitar điện...$"

Route118_Text_DeandreIntro:
	.string "Tiến lên, tiến lên, tiến lên! POKéMON 1, 2\n"
	.string "và 3!$"

Route118_Text_DeandreDefeat:
	.string "A lô, POKéMON! Các bạn ổn chứ? POKéMON\n"
	.string "1, 2 và 3?!$"

Route118_Text_DeandrePostBattle:
	.string "Tôi có cả một đội POKéMON chiến đấu,\n"
	.string "ngầu phải không?\p"
	.string "Bạn cứ bắt chước tôi, tôi không phiền\n"
	.string "đâu!$"

Route119_Text_BrentIntro:
	.string "Chúng tôi là MIMIC CIRCLE! Chúng tôi\n"
	.string "MIMIC mọi hành động của bạn!$"

Route119_Text_BrentDefeat:
	.string "Ối! Tôi thua rồi!$"

Route119_Text_BrentPostBattle:
	.string "Bắt chước thì có gì hay ư?\p"
	.string "Fufufu... Bạn sẽ không bao giờ hiểu\n"
	.string "đâu...$"

Route119_Text_DonaldIntro:
	.string "Cuối cùng ta cũng gặp nhau! BUG\n"
	.string "POKéMON của tôi sẽ tiếp bạn!$"

Route119_Text_DonaldDefeat:
	.string "Ước gì chúng ta chưa từng gặp nhau...$"

Route119_Text_DonaldPostBattle:
	.string "Tôi muốn MIMIC bạn thêm nữa. Bạn mau di\n"
	.string "chuyển đi được không?$"

Route119_Text_TaylorIntro:
	.string "Bạn bước lên, chúng tôi cũng bước lên.\p"
	.string "Bạn rẽ phải, chúng tôi cũng rẽ...$"

Route119_Text_TaylorDefeat:
	.string "Nhưng bạn thắng thì tôi lại thua...$"

Route119_Text_TaylorPostBattle:
	.string "Tôi không thể MIMIC cảnh bạn thắng\n"
	.string "trận. Chuyện đó hoàn toàn không thể...\l"
	.string "Tôi tức điên lên mất...$"

Route119_Text_DougIntro:
	.string "Phải, cuối cùng bạn cũng bắt được tôi\n"
	.string "rồi! Hay là bạn đang cố tránh tôi đấy?$"

Route119_Text_DougDefeat:
	.string "Chà, trận đấu hay thật!$"

Route119_Text_DougPostBattle:
	.string "Chúng tôi là MIMIC CIRCLE! Hy vọng bạn\n"
	.string "thích màn trình diễn của chúng tôi.$"

Route119_Text_GregIntro:
	.string "Bạn không biết tôi là ai, đúng không?\p"
	.string "Nhưng tôi cũng chẳng biết bạn. Vậy nên\n"
	.string "đấu thôi!$"

Route119_Text_GregDefeat:
	.string "Bạn khá mạnh đấy!$"

Route119_Text_GregPostBattle:
	.string "Cho đến khi bạn đi khỏi đây, chúng tôi\n"
	.string "sẽ tiếp tục bắt chước từng cử động\l"
	.string "của bạn.$"

Route119_Text_KentIntro:
	.string "MIMIC CIRCLE được lập nên bởi những\n"
	.string "người thích MIMIC.\p"
	.string "Vừa gặp nhau là trận đấu bắt đầu ngay!$"

Route119_Text_KentDefeat:
	.string "Tôi chịu thua!$"

Route119_Text_KentPostBattle:
	.string "Bạn gia nhập MIMIC CIRCLE nhé?$"

Route119_Text_JacksonIntro:
	.string "Ai là người có kiến thức và kỹ năng\n"
	.string "sinh tồn?\p"
	.string "Chính là POKéMON RANGERS!$"

Route119_Text_JacksonDefeat:
	.string "Kiến thức về POKéMON của tôi vẫn chưa\n"
	.string "đủ...$"

Route119_Text_JacksonPostBattle:
	.string "Rời xa nền văn minh và đánh thức bản\n"
	.string "năng hoang dã bên trong!\p"
	.string "Đó là lý tưởng của chúng tôi.$"

Route119_Text_JacksonRegister:
	.string "Hy vọng bạn sẽ tái đấu với tôi mà không\n"
	.string "chế giễu sự thiếu hiểu biết của tôi.$"

Route119_Text_JacksonRematchIntro:
	.string "Tôi sẽ tìm lại tinh thần hoang dã bằng\n"
	.string "cách sống bên POKéMON.$"

Route119_Text_JacksonRematchDefeat:
	.string "Bạn vẫn mạnh như trước!$"

Route119_Text_JacksonPostRematch:
	.string "Hãy tin vào POKéMON của bạn. Hãy tin\n"
	.string "vào chính mình.\p"
	.string "Con đường sẽ tự mở ra trước mắt bạn.$"

Route119_Text_CatherineIntro:
	.string "Ồ? Nhìn bạn kìa.\p"
	.string "Đang phiêu lưu mà hành trang của bạn\n"
	.string "nhẹ đến lạ.$"

Route119_Text_CatherineDefeat:
	.string "Tai nạn xảy ra khi ta không chuẩn bị kỹ!$"

Route119_Text_CatherinePostBattle:
	.string "Hành trang nhẹ nhàng nhưng bạn có đủ\n"
	.string "mọi thứ cần thiết.\p"
	.string "Bạn cũng chuẩn bị chu đáo cả tinh thần\n"
	.string "lẫn thể chất.$"

Route119_Text_CatherineRegister:
	.string "Bạn có POKéNAV không? Đó là công cụ\n"
	.string "không thể thiếu với mọi HLV.\p"
	.string "Ồ, bạn có rồi! Vậy hãy đăng ký nhau nhé!$"

Route119_Text_CatherineRematchIntro:
	.string "Chuyến hành trình cùng POKéMON của\n"
	.string "bạn thế nào rồi?$"

Route119_Text_CatherineRematchDefeat:
	.string "Tôi vẫn còn thiếu điều gì đó...$"

Route119_Text_CatherinePostRematch:
	.string "Cũng như bạn, một HLV, dựa vào\n"
	.string "POKéMON của mình, POKéMON cũng dựa\l"
	.string "vào bạn.$"

Route119_Text_HughIntro:
	.string "Bầu trời bao la ẩn chứa vô vàn hứa hẹn!\p"
	.string "Không gì sánh được với cảm giác phấn\n"
	.string "khích tột độ khi bay!$"

Route119_Text_HughDefeat:
	.string "Đo ván rồi!$"

Route119_Text_HughPostBattle:
	.string "BIRD POKéMON đã biến giấc mơ bay lượn\n"
	.string "của tôi thành hiện thực!$"

Route119_Text_PhilIntro:
	.string "Tôi sẽ cho bạn thấy tiềm năng thật sự\n"
	.string "của tôi và BIRD POKéMON!$"

Route119_Text_PhilDefeat:
	.string "Tiềm năng của chúng tôi chưa đủ...$"

Route119_Text_PhilPostBattle:
	.string "Từ nhỏ, tôi đã luôn ngưỡng mộ BIRD\n"
	.string "POKéMON...$"

Route119_Text_YasuIntro:
	.string "Ẩn mình trong bóng tối, sống giữa màn\n"
	.string "đêm... Đó là số phận của ta.\p"
	.string "Ta xuất hiện để thách đấu ngươi!$"

Route119_Text_YasuDefeat:
	.string "Ta thừa nhận thất bại!$"

Route119_Text_YasuPostBattle:
	.string "Kẻ bại trận lặng lẽ lui về bóng tối. Đó\n"
	.string "cũng là số phận...$"

Route119_Text_TakashiIntro:
	.string "Nếu lơ là cảnh giác, bạn sẽ phải nếm mùi\n"
	.string "đau đớn!$"

Route119_Text_TakashiDefeat:
	.string "Bạn giỏi hơn tôi tưởng đấy!$"

Route119_Text_TakashiPostBattle:
	.string "Đòn tập kích bất ngờ của tôi đã thất\n"
	.string "bại...$"

Route119_Text_HideoIntro:
	.string "Muốn giấu một cái cây, hãy dùng cả khu\n"
	.string "rừng!$"

Route119_Text_HideoDefeat:
	.string "Tôi xin cúi đầu trước tài nghệ vượt\n"
	.string "trội của bạn.$"

Route119_Text_HideoPostBattle:
	.string "Muốn giấu một cái cây, hãy dùng cả khu\n"
	.string "rừng! Muốn giấu một POKéMON, hãy dùng\l"
	.string "một POKéMON!\p"
	.string "Câu đó chẳng có ý nghĩa sâu xa ẩn giấu\n"
	.string "gì đâu.$"

Route119_Text_ChrisIntro:
	.string "Bạn bắt chuyện với tôi... Vậy là muốn\n"
	.string "thách đấu!\p"
	.string "Được thôi! Tôi sẽ thử sức những\n"
	.string "POKéMON mình bắt được khi SURFING!$"

Route119_Text_ChrisDefeat:
	.string "Tôi chẳng hiểu cần gì để giành chiến\n"
	.string "thắng.$"

Route119_Text_ChrisPostBattle:
	.string "SURF trên POKéMON của tôi...\p"
	.string "Rồi ngồi trên lưng nó mà câu cá...\p"
	.string "Đó là một trải nghiệm xa xỉ không sao\n"
	.string "diễn tả nổi!$"

Route119_Text_FabianIntro:
	.string "Nện một hợp âm thật cháy đi! Chiến\n"
	.string "thắng thuộc về ta! Đến lúc ta tỏa sáng\l"
	.string "rồi, whoa, yeah!$"

Route119_Text_FabianDefeat:
	.string "Bạn đã cho tôi biết ai mới là trùm!\n"
	.string "Chúng tôi đành nhận thua thôi, ôi\l"
	.string "không!$"

Route119_Text_FabianPostBattle:
	.string "Nện thêm một hợp âm thật cháy đi! Để\n"
	.string "tôi yên! Bạn phải chuộc lỗi vì chiến\l"
	.string "thắng này!$"

Route119_Text_DaytonIntro:
	.string "Hohoho! Tôi thích những HLV nhí!\n"
	.string "Hãy đấu một trận ra trò nào!$"

Route119_Text_DaytonDefeat:
	.string "Bạn đáng kinh ngạc thật! Hohoho!$"

Route119_Text_DaytonPostBattle:
	.string "Hohoho! Tôi sẽ thử học theo sức sống\n"
	.string "của những HLV nhí như bạn!$"

Route119_Text_RachelIntro:
	.string "Dù ở đâu hay lúc nào, tôi cũng luôn cầm\n"
	.string "ô trong tay.$"

Route119_Text_RachelDefeat:
	.string "Ồ, nhưng... Như thế không công bằng.$"

Route119_Text_RachelPostBattle:
	.string "Bạn hỏi ô của tôi có nặng không à?\p"
	.string "TÚI ĐỒ của bạn còn chứa nhiều thứ linh\l"
	.string "tinh hơn tất cả những gì tôi mang đấy.$"

Route120_Text_ColinIntro:
	.string "Bạn có chiêu thức nào đánh trúng được\n"
	.string "POKéMON đang bay không?$"

Route120_Text_ColinDefeat:
	.string "Bạn đã bay cao hơn tôi!$"

Route120_Text_ColinPostBattle:
	.string "Chiêu FLY tiện lợi lắm, bạn không thấy\n"
	.string "vậy sao?\p"
	.string "Khi POKéMON đang bay, gần như không\n"
	.string "chiêu thức nào đánh trúng nó.$"

Route120_Text_RobertIntro:
	.string "POKéMON của tôi rất mạnh! Còn của bạn\n"
	.string "thì sao?$"

Route120_Text_RobertDefeat:
	.string "POKéMON của bạn mạnh hơn...$"

Route120_Text_RobertPostBattle:
	.string "Một POKéMON lớn mạnh vững vàng là\n"
	.string "POKéMON bạn có thể trông cậy.$"

Route120_Text_RobertRegister:
	.string "Có thể tin rằng bạn sẽ còn tiến bộ. Tôi\n"
	.string "muốn đăng ký bạn vào POKéNAV của tôi!$"

Route120_Text_RobertRematchIntro:
	.string "Một POKéMON trưởng thành đều đặn là\n"
	.string "bạn đồng hành đáng tin cậy.$"

Route120_Text_RobertRematchDefeat:
	.string "POKéMON của bạn mạnh thật sự.$"

Route120_Text_RobertPostRematch:
	.string "POKéMON của tôi đang ngày càng mạnh\n"
	.string "hơn. Tôi cũng phải mạnh hơn nữa.$"

Route120_Text_LorenzoIntro:
	.string "Tôi sẽ kiểm tra POKéMON của bạn xem\n"
	.string "chúng có thích hợp với hoạt động ngoài\l"
	.string "trời không.$"

Route120_Text_LorenzoDefeat:
	.string "Với POKéMON mạnh như thế, bạn chẳng lo\n"
	.string "phải cần người giải cứu!$"

Route120_Text_LorenzoPostBattle:
	.string "Được cùng POKéMON đi đến bất cứ nơi\n"
	.string "đâu trái tim mình mong muốn... Đó chính\l"
	.string "là niềm vui khi làm HLV.$"

Route120_Text_JennaIntro:
	.string "Thể lực của bạn thế nào? Nếu không đủ\n"
	.string "khỏe, bạn có thể gặp khó khăn trong\l"
	.string "tình huống nguy cấp.$"

Route120_Text_JennaDefeat:
	.string "Tôi hoàn toàn sung sức, nhưng...$"

Route120_Text_JennaPostBattle:
	.string "Luyện thể lực là thói quen của tôi. Tôi\n"
	.string "luôn chạy cùng POKéMON.$"

Route120_Text_JeffreyIntro:
	.string "... ... ... ... ... ... ... ... ... ... ... ... Muốn đấu\n"
	.string "không?$"

Route120_Text_JeffreyDefeat:
	.string "Thua rồi...$"

Route120_Text_JeffreyPostBattle:
	.string "... ... ... ... ... ... ... ... ... ... ... ... Tôi sẽ cố\n"
	.string "gắng hơn...$"

Route120_Text_JeffreyRegister:
	.string "... ... ... ... ... ... ... ... ... ... ... ... Bạn có\n"
	.string "POKéNAV không...?$"

Route120_Text_JeffreyRematchIntro:
	.string "... ... ... ... ... ... ... ... ... ... ... ... Muốn đấu lại\n"
	.string "không?$"

Route120_Text_JeffreyRematchDefeat:
	.string "... ... ... ... ... ... Tôi lại thua rồi...$"

Route120_Text_JeffreyPostRematch:
	.string "... ... ... ... ... ... ... ... ... ... ... ... Tôi sẽ cố\n"
	.string "gắng hơn... Vì BUG POKéMON quý giá của\l"
	.string "tôi...$"

Route120_Text_JenniferIntro:
	.string "POKéMON có rất nhiều khả năng đặc biệt.\n"
	.string "Nếu muốn trở thành HLV hạng nhất,\l"
	.string "hãy tìm hiểu về chúng.$"

Route120_Text_JenniferDefeat:
	.string "Rõ ràng là bạn đã suy tính kỹ.$"

Route120_Text_JenniferPostBattle:
	.string "Các khả năng đặc biệt của POKéMON sẽ\n"
	.string "làm thay đổi phong cách chiến đấu.$"

Route120_Text_ChipIntro:
	.string "Bạn là ai vậy?\p"
	.string "Chẳng lẽ bạn đang tìm những tàn tích\n"
	.string "cổ xưa mà theo truyền thuyết, người ta\l"
	.string "đồn rằng có thể tồn tại sao?$"

Route120_Text_ChipDefeat:
	.string "Thật là một thất bại đáng hổ thẹn...$"

Route120_Text_ChipPostBattle:
	.string "Tảng đá khổng lồ kia... Tôi muốn tin rằng\n"
	.string "bên trong nó quả thực có thể chứa tàn\l"
	.string "tích cổ xưa. Nhưng tôi không thấy lối\l"
	.string "vào.$"

Route120_Text_ClarissaIntro:
	.string "Tại sao tôi mang chiếc ô này ư?\p"
	.string "Nếu bạn thắng được tôi, tôi sẽ cho bạn\n"
	.string "biết.$"

Route120_Text_ClarissaDefeat:
	.string "Một chiếc ô không thể đỡ được đòn tấn\n"
	.string "công của POKéMON...$"

Route120_Text_ClarissaPostBattle:
	.string "Tôi không nghĩ ánh nắng gay gắt tốt cho\n"
	.string "POKéMON của mình. Vì vậy tôi che nắng\l"
	.string "cho chúng bằng chiếc ô.$"

Route120_Text_AngelicaIntro:
	.string "Tôi, POKéMON và chiếc ô của tôi...\p"
	.string "Chỉ cần thiếu một thứ thôi là bức tranh\n"
	.string "tuyệt mỹ này sẽ bị phá hỏng.$"

Route120_Text_AngelicaDefeat:
	.string "Bạn đã phá hỏng hoàn toàn vẻ đẹp của\n"
	.string "tôi...$"

Route120_Text_AngelicaPostBattle:
	.string "Chiếc ô chẳng hợp với bạn chút nào.\p"
	.string "Thứ như thế này chỉ tổ vướng víu bạn\n"
	.string "thôi.$"

Route120_Text_KeigoIntro:
	.string "Tôi sẽ học theo chuyển động của\n"
	.string "POKéMON và sáng tạo ra những nhẫn\l"
	.string "thuật mới.$"

Route120_Text_KeigoDefeat:
	.string "Việc sáng tạo nhẫn thuật mới vẫn chỉ là\n"
	.string "một giấc mơ xa vời...$"

Route120_Text_KeigoPostBattle:
	.string "Có lẽ tôi nên xin làm đệ tử của một bậc\n"
	.string "thầy ninja.$"

Route120_Text_RileyIntro:
	.string "Ninja chúng tôi ẩn mình dưới áo choàng\n"
	.string "ngụy trang. Tôi cá là bạn không biết tôi\l"
	.string "ở đâu!$"

Route120_Text_RileyDefeat:
	.string "Tôi thua rồi! Phải ngụy trang cả nỗi\n"
	.string "nhục này thôi!$"

Route120_Text_RileyPostBattle:
	.string "Áo choàng ngụy trang của chúng tôi đều\n"
	.string "được làm thủ công.$"

Route120_Text_CallieIntro:
	.string "Nếu không chú ý, bạn có thể bị thương\n"
	.string "đấy!$"

Route120_Text_CallieDefeat:
	.string "Ui da! Hóa ra người bị thương lại là tôi.$"

Route120_Text_CalliePostBattle:
	.string "Không biết có nên tiến hóa POKéMON của\n"
	.string "mình không nhỉ? Nhưng chúng hiện giờ\l"
	.string "đáng yêu lắm.$"

Route120_Text_LeonelIntro:
	.string "Các POKéMON trong đội của bạn... Chúng\n"
	.string "có thuộc nhiều hệ khác nhau không?$"

Route120_Text_LeonelDefeat:
	.string "Tôi đã thấy chiến thuật của bạn phát\n"
	.string "huy ra sao rồi!$"

Route120_Text_LeonelPostBattle:
	.string "Tôi thấy thật tuyệt khi bạn mạnh đến\n"
	.string "vậy dù chiến đấu bằng những POKéMON\l"
	.string "mình yêu thích.$"

Route121_Text_VanessaIntro:
	.string "Bạn có muốn chơi với những POKéMON\n"
	.string "xinh đẹp tuyệt trần của tôi không?$"

Route121_Text_VanessaDefeat:
	.string "Ý tôi đâu phải thế này!$"

Route121_Text_VanessaPostBattle:
	.string "Tôi đang đến một cuộc thi ở LILYCOVE.\p"
	.string "POKéMON của tôi chắc chắn sẽ dễ dàng áp\n"
	.string "đảo MASTER CLASS.$"

Route121_Text_WalterIntro:
	.string "Tôi đã cùng POKéMON đi khắp bốn\n"
	.string "phương trời.\p"
	.string "Có thể nói tôi khá tự tin vào năng lực\n"
	.string "của mình.$"

Route121_Text_WalterDefeat:
	.string "À, đánh hay lắm.$"

Route121_Text_WalterPostBattle:
	.string "Tôi muốn một lần nữa cùng POKéMON đi\n"
	.string "vòng quanh thế giới.$"

Route121_Text_WalterRegister:
	.string "Tài huấn luyện POKéMON của bạn thật\n"
	.string "đáng nể. Cho phép tôi đăng ký bạn để\l"
	.string "làm kỷ niệm.$"

Route121_Text_WalterRematchIntro:
	.string "Tôi đã cùng POKéMON đi khắp bốn\n"
	.string "phương trời.\p"
	.string "Có thể nói tôi khá tự tin vào năng lực\n"
	.string "của mình.$"

Route121_Text_WalterRematchDefeat:
	.string "À, đánh hay lắm.$"

Route121_Text_WalterPostRematch:
	.string "Bạn và POKéMON của bạn...\p"
	.string "Sức mạnh khi hai bên phối hợp sẽ được\n"
	.string "xem là đáng gờm, ngay cả ở hải ngoại.$"

Route121_Text_TammyIntro:
	.string "Trên thế gian có những sức mạnh vượt\n"
	.string "ngoài hiểu biết của chúng ta...$"

Route121_Text_TammyDefeat:
	.string "Tôi đã thua...$"

Route121_Text_TammyPostBattle:
	.string "MT. PYRE... Nơi đó có một sức mạnh bí ẩn\n"
	.string "đang vận hành...$"

Route121_Text_KateIntro:
	.string "KATE: Khi ở bên nhau, chúng tôi chẳng\n"
	.string "sợ gì cả! Chúng tôi sẽ cho bạn thấy\l"
	.string "mình mạnh đến mức nào!$"

Route121_Text_KateDefeat:
	.string "KATE: Tôi lại làm hỏng chuyện ngay\n"
	.string "trước mặt người bạn đồng môn khóa\l"
	.string "dưới của mình...$"

Route121_Text_KatePostBattle:
	.string "KATE: Khi có người trông cậy vào mình,\n"
	.string "tôi lại muốn tỏ ra thật ngầu trước mặt\l"
	.string "họ...$"

Route121_Text_KateNotEnoughMons:
	.string "KATE: Nếu bạn chỉ có một POKéMON thì\n"
	.string "chúng tôi không thể đấu với bạn.\p"
	.string "Làm vậy chẳng khác nào bắt nạt.$"

Route121_Text_JoyIntro:
	.string "JOY: Khi ở bên nhau, chúng tôi chẳng sợ\n"
	.string "gì cả! Chúng tôi sẽ cho bạn thấy mình\l"
	.string "mạnh đến mức nào!$"

Route121_Text_JoyDefeat:
	.string "JOY: KATE, xin hãy tha lỗi cho em!$"

Route121_Text_JoyPostBattle:
	.string "JOY: Ehehe, tôi sẽ phải tập luyện lại\n"
	.string "cùng KATE, người bạn đồng môn khóa\l"
	.string "trên của tôi.$"

Route121_Text_JoyNotEnoughMons:
	.string "JOY: Muốn thách đấu chúng tôi thì bạn\n"
	.string "phải có ít nhất hai POKéMON!$"

Route121_Text_JessicaIntro:
	.string "Dừng lại! Hãy nhìn kỹ những POKéMON\n"
	.string "quý giá của tôi đi!$"

Route121_Text_JessicaDefeat:
	.string "Ôi, sao bạn dám! Đừng nghiêm túc đến\n"
	.string "thế chứ!$"

Route121_Text_JessicaPostBattle:
	.string "Có lẽ tôi sẽ đến SAFARI bắt thêm\n"
	.string "POKéMON.$"

Route121_Text_JessicaRegister:
	.string "Lần này tôi đã nương tay với bạn! Lần\n"
	.string "sau sẽ không như vậy đâu!$"

Route121_Text_JessicaRematchIntro:
	.string "POKéMON quý giá của tôi đã trưởng\n"
	.string "thành rồi! Hãy nhìn cho kỹ!$"

Route121_Text_JessicaRematchDefeat:
	.string "Ôi, sao bạn dám! Bạn vẫn chẳng chịu\n"
	.string "nương tay gì cả!$"

Route121_Text_JessicaPostRematch:
	.string "Có lẽ tôi sẽ đến SAFARI bắt thêm\n"
	.string "POKéMON.$"

Route121_Text_CristinIntro:
	.string "Tôi có một thói quen: mỗi ngày đánh bại\n"
	.string "năm HLV. Đoán xem? Bạn là người\l"
	.string "thứ năm!$"

Route121_Text_CristinDefeat:
	.string "Không! Bạn thật xấu xa!$"

Route121_Text_CristinPostBattle:
	.string "Tôi không ngờ mình lại thua dễ dàng thế\n"
	.string "này... Lần sau tôi sẽ thắng!$"

Route121_Text_CristinRegister:
	.string "Thật là một nỗi nhục ê chề! Tôi sẽ không\n"
	.string "quên bạn đâu... Đưa POKéNAV của bạn\l"
	.string "đây!$"

Route121_Text_CristinRematchIntro:
	.string "Tôi có thói quen mới: mỗi ngày đánh bại\n"
	.string "mười HLV. Đoán xem? Bạn là người\l"
	.string "thứ mười!$"

Route121_Text_CristinRematchDefeat:
	.string "Khoan đã! Thật quá đáng! Tôi yêu cầu\n"
	.string "đấu lại!$"

Route121_Text_CristinPostRematch:
	.string "Một đối thủ mà tôi không tài nào thắng\n"
	.string "nổi... Sụt sịt... Tôi không thể tin chuyện\l"
	.string "này lại xảy ra...$"

Route121_Text_CaleIntro:
	.string "Bạn không thấy tôi đang mang ngần này\n"
	.string "đồ sao?\p"
	.string "Vậy mà bạn vẫn nhất quyết đòi đấu với\n"
	.string "tôi à?$"

Route121_Text_CaleDefeat:
	.string "Tất nhiên tôi thua rồi! Cả hai tay tôi\n"
	.string "đều đang xách đồ mà!$"

Route121_Text_CalePostBattle:
	.string "Tôi đã mua quá nhiều đồ ở LILYCOVE\n"
	.string "DEPT. STORE.\p"
	.string "Cửa hàng ở ngay phía trước con đường\n"
	.string "này. Ước gì tôi có một chiếc TÚI ĐỒ như\l"
	.string "của bạn.$"

Route121_Text_MylesIntro:
	.string "Không gì khiến tôi thích hơn việc ngắm\n"
	.string "nghía POKéMON của người khác!$"

Route121_Text_MylesDefeat:
	.string "Tuyệt đỉnh!$"

Route121_Text_MylesPostBattle:
	.string "POKéMON của bạn tuyệt thật! Bạn nuôi\n"
	.string "chúng thế nào vậy?$"

Route121_Text_PatIntro:
	.string "Tôi muốn mọi người đều được thấy\n"
	.string "những POKéMON mà tôi đã nuôi dưỡng!$"

Route121_Text_PatDefeat:
	.string "Chà! Ngoạn mục!$"

Route121_Text_PatPostBattle:
	.string "Tôi nuôi mọi POKéMON bằng tình yêu và\n"
	.string "sự chăm sóc như nhau. Tôi không thiên\l"
	.string "vị con nào cả.$"

Route121_Text_MarcelIntro:
	.string "POKéMON của tôi chưa từng nếm mùi thất\n"
	.string "bại! Sau chiến thắng tiếp theo, tôi sẽ\l"
	.string "cho chúng tham gia các cuộc thi.$"

Route121_Text_MarcelDefeat:
	.string "Ồ, chuyện gì vừa xảy ra thế này?$"

Route121_Text_MarcelPostBattle:
	.string "Có lẽ tôi phải huấn luyện cả nhóm thêm\n"
	.string "nữa trước khi tham gia bất kỳ cuộc thi\l"
	.string "nào.$"

Route123_Text_WendyIntro:
	.string "Muốn biết mình mạnh đến đâu không? Tôi\n"
	.string "sẽ là bài kiểm tra!$"

Route123_Text_WendyDefeat:
	.string "Bạn đã vượt qua xuất sắc!$"

Route123_Text_WendyPostBattle:
	.string "Đánh bại được cả tôi... Sức mạnh của\n"
	.string "bạn thật phi thường!$"

Route123_Text_BraxtonIntro:
	.string "Có vẻ bạn sở hữu cả một bộ sưu tập GYM\n"
	.string "BADGES.\p"
	.string "Để tôi xem bạn có thực sự xứng đáng\n"
	.string "với những BADGES đó không!$"

Route123_Text_BraxtonDefeat:
	.string "Ồ, bạn hoàn toàn xứng đáng!$"

Route123_Text_BraxtonPostBattle:
	.string "Trong trận vừa rồi, bạn đã không phụ\n"
	.string "lòng những BADGES của mình!$"

Route123_Text_VioletIntro:
	.string "Người ta nói những khoảng thời gian\n"
	.string "vui vẻ luôn ngập tràn hương thơm dễ\l"
	.string "chịu.$"

Route123_Text_VioletDefeat:
	.string "Ôi... Tôi ngửi thấy mùi cay đắng của khổ\n"
	.string "đau...$"

Route123_Text_VioletPostBattle:
	.string "Khu vườn của BERRY MASTER tràn ngập\n"
	.string "những hương thơm làm tinh thần phấn\l"
	.string "chấn.$"

Route123_Text_CameronIntro:
	.string "Làm nhà ngoại cảm là phải có ý chí.\p"
	.string "Tôi dùng ý chí buộc mình không được\n"
	.string "thua bất kỳ ai. Chính điều đó làm tôi\l"
	.string "mạnh!$"

Route123_Text_CameronDefeat:
	.string "Tôi thấy buồn...$"

Route123_Text_CameronPostBattle:
	.string "Làm nhà ngoại cảm là phải có ý chí. Tôi\n"
	.string "cứ nghĩ mình sẽ không thua bạn...$"

Route123_Text_CameronRegister:
	.string "Tôi cảm nhận được! Cậu và tôi nhất định\n"
	.string "sẽ lại giao đấu! Nhưng tôi không biết\l"
	.string "mình có thắng nổi không...\p"
	.string "Cho tôi xem POKéNAV của cậu nào.$"

Route123_Text_CameronRematchIntro:
	.string "Tôi đã tự thuyết phục rằng từ giờ mình\n"
	.string "sẽ không thua nữa. Chính điều đó khiến\l"
	.string "tôi mạnh hơn!$"

Route123_Text_CameronRematchDefeat:
	.string "Tôi buồn quá...$"

Route123_Text_CameronPostRematch:
	.string "Tôi nên luyện tập ở MT. PYRE... Cứ thế\n"
	.string "này thì tôi sẽ chẳng bao giờ thắng\l"
	.string "được cậu...$"

Route123_Text_JackiIntro:
	.string "Đừng vội mừng nếu POKéMON của cậu\n"
	.string "phát triển năng lực tâm linh.\p"
	.string "Cậu phải mài giũa những năng lực đó thì\n"
	.string "chúng mới thật sự hữu ích.$"

Route123_Text_JackiDefeat:
	.string "Bị áp đảo rồi!$"

Route123_Text_JackiPostBattle:
	.string "Tất cả chúng ta đều có năng lực tâm\n"
	.string "linh. Chỉ là ta đã quên cách sử dụng\l"
	.string "chúng.$"

Route123_Text_JackiRegister:
	.string "Tôi muốn đấu với cậu lần nữa. Cậu đồng\n"
	.string "ý chứ?$"

Route123_Text_JackiRematchIntro:
	.string "Cậu đã đánh thức năng lực tâm linh bên\n"
	.string "trong mình chưa?$"

Route123_Text_JackiRematchDefeat:
	.string "Thật phi thường!$"

Route123_Text_JackiPostRematch:
	.string "Sức mạnh của cậu khi đồng hành cùng\n"
	.string "POKéMON... Có lẽ đó cũng là một dạng\l"
	.string "năng lực tâm linh.$"

Route123_Text_MiuIntro:
	.string "MIU: Xin chào, HLV. Mong là POKéMON\n"
	.string "của bạn sẽ không khóc khi thua.$"

Route123_Text_MiuDefeat:
	.string "MIU: Ôi không, bọn mình thua rồi.$"

Route123_Text_MiuPostBattle:
	.string "MIU: HLV, POKéMON của bạn mạnh vì\n"
	.string "các bạn là bạn bè.$"

Route123_Text_MiuNotEnoughMons:
	.string "MIU: Đấu sẽ chẳng vui nếu bạn không có\n"
	.string "hai POKéMON.$"

Route123_Text_YukiIntro:
	.string "YUKI: Được rồi! Bọn mình sẽ đánh bại\n"
	.string "POKéMON của HLV này!$"

Route123_Text_YukiDefeat:
	.string "YUKI: Ôi không, bọn mình thua rồi.$"

Route123_Text_YukiPostBattle:
	.string "YUKI: Sao bạn lại mạnh thế? Trước giờ\n"
	.string "bọn mình chưa từng thua.$"

Route123_Text_YukiNotEnoughMons:
	.string "YUKI: Đấu sẽ chẳng vui nếu bạn không có\n"
	.string "hai POKéMON.$"

Route123_Text_KindraIntro:
	.string "MT. PYRE... Nơi linh hồn của POKéMON yên\n"
	.string "nghỉ... POKéMON của cậu cũng sẽ yên\l"
	.string "nghỉ chứ?$"

Route123_Text_KindraDefeat:
	.string "Tràn đầy sinh lực...$"

Route123_Text_KindraPostBattle:
	.string "MT. PYRE... Nơi linh hồn của POKéMON yên\n"
	.string "nghỉ...\p"
	.string "Nơi ấy hẳn tràn ngập một sức mạnh có\n"
	.string "thể xoa dịu các linh hồn...$"

Route123_Text_FernandoIntro:
	.string "Tôi sẽ cho cậu tắt điện trong lúc quẩy\n"
	.string "tung bản nhạc này!$"

Route123_Text_FernandoDefeat:
	.string "Này, khoan đã! Tôi vẫn còn đang chơi\n"
	.string "đoạn dạo đầu mà!$"

Route123_Text_FernandoPostBattle:
	.string "Cậu vững như bàn thạch. Tôi muốn viết\n"
	.string "một ca khúc về cậu.$"

Route123_Text_FernandoRegister:
	.string "Lần tới, hãy nghe trọn cả bài của tôi\n"
	.string "nhé?$"

Route123_Text_FernandoRematchIntro:
	.string "Hôm nay nhất định tôi sẽ làm được! Tôi\n"
	.string "sẽ cho cậu tắt điện trước khi hát xong\l"
	.string "bài!$"

Route123_Text_FernandoRematchDefeat:
	.string "Này, khoan đã! Tôi còn chưa hát đến\n"
	.string "điệp khúc mà!$"

Route123_Text_FernandoPostRematch:
	.string "Tôi cứ tưởng cậu sẽ mải mê nghe nhạc\n"
	.string "của tôi đến mức thua trận chứ.$"

Route123_Text_DavisIntro:
	.string "Đây là BUG POKéMON siêu ngầu của tớ!\n"
	.string "Anh trai tớ kiếm nó cho tớ đấy.$"

Route123_Text_DavisDefeat:
	.string "Hu hu hu! Đồ xấu tính!$"

Route123_Text_DavisPostBattle:
	.string "Đừng kể với anh tớ là tớ thua nhé. Cậu\n"
	.string "phải giữ bí mật đấy!$"

Route123_Text_JazmynIntro:
	.string "Đánh bại một người rõ ràng rất mạnh sẽ\n"
	.string "giúp tôi tự tin hơn!$"

Route123_Text_JazmynDefeat:
	.string "Thế là sự tự tin của tôi đi tong...$"

Route123_Text_JazmynPostBattle:
	.string "Người ta nói không thể trông mặt mà\n"
	.string "bắt hình dong.\p"
	.string "Nhưng nhiều khi, vẻ ngoài lại chẳng hề\n"
	.string "nói dối...$"

Route123_Text_FrederickIntro:
	.string "Chào cháu! Cháu có thể dành chút thời\n"
	.string "gian không?$"

Route123_Text_FrederickDefeat:
	.string "À, một đứa trẻ thật tài giỏi! Để ta góp\n"
	.string "thêm vào tiền tiêu vặt của cháu nhé.$"

Route123_Text_FrederickPostBattle:
	.string "Góp vào tiền tiêu vặt của cháu ư? Tiền\n"
	.string "thưởng chưa đủ sao?$"

Route123_Text_AlbertoIntro:
	.string "Tôi phải nói cho cậu biết, BIRD POKéMON\n"
	.string "là niềm đam mê bất tận của tôi!\p"
	.string "Chim thật ngầu! Chúng là tuyệt nhất!$"

Route123_Text_AlbertoDefeat:
	.string "Dù thua, BIRD POKéMON vẫn ngầu!$"

Route123_Text_AlbertoPostBattle:
	.string "Tôi nhặt những chiếc lông BIRD POKéMON\n"
	.string "rơi ra trong các trận đấu.\p"
	.string "Tôi sẽ làm một chiếc mũ bằng lông BIRD\n"
	.string "POKéMON.$"

Route123_Text_EdIntro:
	.string "Khi không có HLV nào quanh đây,\n"
	.string "tôi cho POKéMON của mình đấu với nhau\l"
	.string "rồi đứng xem.$"

Route123_Text_EdDefeat:
	.string "Tôi cũng khá thích POKéMON của cậu.$"

Route123_Text_EdPostBattle:
	.string "Hê hê, tôi đang chôm các chiến thuật thi\n"
	.string "đấu của cậu đây! Tôi nghĩ chúng sẽ giúp\l"
	.string "mình giỏi hơn.$"

Route123_Text_JonasIntro:
	.string "Ta mai phục sẵn, và một HLV đã sa\n"
	.string "vào bẫy của ta!$"

Route123_Text_JonasDefeat:
	.string "Cậu không chịu thua thì tôi chơi trò\n"
	.string "ninja sao mà vui được?$"

Route123_Text_JonasPostBattle:
	.string "Lần sau tôi sẽ phục kích một HLV\n"
	.string "trông yếu hơn.$"

Route123_Text_KayleyIntro:
	.string "Tôi vừa mua chiếc ô này. Độ đáng yêu\n"
	.string "của tôi chắc phải tăng thêm một phần\l"
	.string "ba!$"

Route123_Text_KayleyDefeat:
	.string "Cậu giỏi gấp tôi khoảng năm lần!$"

Route123_Text_KayleyPostBattle:
	.string "Bí quyết tạo nên sức hút thời trang là\n"
	.string "biết dùng phụ kiện thật hiệu quả.$"

Route124_Text_SpencerIntro:
	.string "Này, cậu bị lạc giữa biển à?\p"
	.string "Nếu cậu đánh bại được POKéMON của tôi,\n"
	.string "tôi sẽ làm hoa tiêu cho cậu.$"

Route124_Text_SpencerDefeat:
	.string "Tôi mất phương hướng ngay trong trận\n"
	.string "đấu rồi!$"

Route124_Text_SpencerPostBattle:
	.string "Nhiều người bị mất phương hướng trên\n"
	.string "biển.\p"
	.string "Nếu cậu cũng thế, hãy xem MAP trên\n"
	.string "POKéNAV.$"

Route124_Text_RolandIntro:
	.string "Hừm! Cậu cưỡi POKéMON thay vì tự bơi...\p"
	.string "Tôi ghen tị quá!$"

Route124_Text_RolandDefeat:
	.string "Ôi! Tôi không thể...$"

Route124_Text_RolandPostBattle:
	.string "Tôi lạnh cóng rồi... Tôi ngâm mình dưới\n"
	.string "nước quá lâu...\p"
	.string "Giá mà tôi cũng có thể cưỡi POKéMON\n"
	.string "như cậu...$"

Route124_Text_JennyIntro:
	.string "Cứ thả mình nổi trên biển thế này,\n"
	.string "POKéMON sẽ kéo đến chơi cùng.$"

Route124_Text_JennyDefeat:
	.string "Ôi, chán thật. Tôi lại thua mất rồi.$"

Route124_Text_JennyPostBattle:
	.string "Khi đang bơi, tôi nhận ra có POKéMON lao\n"
	.string "vào tấn công, còn có con chỉ đứng nhìn.\p"
	.string "Có lẽ mỗi POKéMON đều có tính cách\n"
	.string "riêng.$"

Route124_Text_JennyRegister:
	.string "Chỉ là hứng lên thôi, nhưng có lẽ tôi sẽ\n"
	.string "nhờ cậu đăng ký tôi vào POKéNAV.$"

Route124_Text_JennyRematchIntro:
	.string "Cứ thả mình nổi trên biển thế này,\n"
	.string "HLV sẽ đến thách đấu!$"

Route124_Text_JennyRematchDefeat:
	.string "Lạ thật... Tôi lại thua nữa rồi...$"

Route124_Text_JennyPostRematch:
	.string "Chuyện này chẳng liên quan gì cả, nhưng\n"
	.string "có lẽ tôi sẽ ghé TRICK HOUSE.$"

Route124_Text_GraceIntro:
	.string "Tôi bắt đầu chán bơi rồi... Đấu một trận\n"
	.string "nhé?$"

Route124_Text_GraceDefeat:
	.string "Tôi không ngờ cậu lại mạnh đến thế!$"

Route124_Text_GracePostBattle:
	.string "Hẳn là bao nỗ lực cậu bỏ ra đã giúp cậu\n"
	.string "mạnh đến vậy.$"

Route124_Text_ChadIntro:
	.string "Hư hư hư... Tôi lặn sâu dưới nước để\n"
	.string "hoạt động ngầm thật sâu. Khám phá tận\l"
	.string "đáy là sở trường của tôi!$"

Route124_Text_ChadDefeat:
	.string "Ọc, ọc, ọc... Tôi đang chìm...$"

Route124_Text_ChadPostBattle:
	.string "Tôi nghe từ nguồn đáng tin rằng quanh\n"
	.string "đây có một điểm DIVE.\p"
	.string "Nó lại khiến tôi muốn lặn sâu...$"

Route124_Text_LilaIntro:
	.string "LILA: Haiz...\p"
	.string "Tôi đang ở giữa biển, nhưng người bên\n"
	.string "cạnh tôi là ai? Em trai tôi!\p"
	.string "Đấu một trận để tôi khỏi phải nghĩ đến\n"
	.string "chuyện đó nào!$"

Route124_Text_LilaDefeat:
	.string "LILA: ROY! Tại em mà chúng ta thua đấy!\n"
	.string "Lát nữa em biết tay chị!$"

Route124_Text_LilaPostBattle:
	.string "LILA: Haiz...\p"
	.string "Giá mà người bên cạnh tôi không phải em\n"
	.string "trai, mà là một anh bạn trai tử tế...$"

Route124_Text_LilaNotEnoughMons:
	.string "LILA: Bạn định đấu với chúng tôi à?\n"
	.string "Không có hai POKéMON thì miễn nhé.$"

Route124_Text_RoyIntro:
	.string "ROY: Chị gái tớ đấu POKéMON giỏi lắm!\p"
	.string "Thua rồi thì đừng khóc nhé!$"

Route124_Text_RoyDefeat:
	.string "ROY: Ôi không... Chị tớ sẽ mắng cho một\n"
	.string "trận mất...$"

Route124_Text_RoyPostBattle:
	.string "ROY: Chị tớ lúc nổi giận đáng sợ lắm.\p"
	.string "Vì thế nên chị ấy mới không có bạn trai.$"

Route124_Text_LilaRoyRegister:
	.string "ROY: Bạn sẽ lại đấu với bọn tớ chứ?\n"
	.string "Nhưng lần sau nhẹ tay thôi nhé?$"

Route124_Text_RoyNotEnoughMons:
	.string "ROY: Bạn muốn đấu với bọn tớ à? Vậy hãy\n"
	.string "mang theo hai POKéMON.$"

Route124_Text_LilaRematchIntro:
	.string "LILA: Haiz...\p"
	.string "Tôi đang ở giữa biển, nhưng người bên\n"
	.string "cạnh tôi là ai? Em trai tôi!\p"
	.string "À, chào bạn, lâu rồi không gặp. Đấu một\n"
	.string "trận để tôi khỏi nghĩ ngợi lung tung\l"
	.string "nào!$"

Route124_Text_LilaRematchDefeat:
	.string "LILA: ROY! Lại tại em mà chúng ta thua\n"
	.string "đấy!\p"
	.string "Lát nữa phải tập luyện đặc biệt!$"

Route124_Text_LilaPostRematch:
	.string "LILA: Haiz...\p"
	.string "Nếu có một anh bạn trai tử tế, chúng tôi\n"
	.string "sẽ dùng những màn phối hợp tuyệt đẹp\l"
	.string "để đánh bại bất kỳ ai...$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "LILA: Bạn định đấu với chúng tôi à?\n"
	.string "Không có hai POKéMON thì miễn nhé.$"

Route124_Text_RoyRematchIntro:
	.string "ROY: Nếu thua, tớ sẽ bị mắng té tát. Tớ\n"
	.string "sẽ dốc hết sức luôn!$"

Route124_Text_RoyRematchDefeat:
	.string "ROY: Ôi không... Chị tớ lại mắng cho một\n"
	.string "trận mất.$"

Route124_Text_RoyPostRematch:
	.string "ROY: Chị tớ lúc nổi giận đáng sợ lắm.\p"
	.string "Lát nữa chị ấy sẽ bắt tớ luyện POKéMON\n"
	.string "thật khắc nghiệt...$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "ROY: Bạn muốn đấu với bọn tớ à? Vậy hãy\n"
	.string "mang theo hai POKéMON.$"

Route124_Text_DeclanIntro:
	.string "Tôi đang bơi một mình lẻ loi giữa vùng\n"
	.string "biển rộng lớn, tuyệt đẹp này.\p"
	.string "Không còn từ nào khác để nói. Thật thảm\n"
	.string "hại!$"

Route124_Text_DeclanDefeat:
	.string "Tôi buồn quá. Nỗi buồn xanh như bầu\n"
	.string "trời...$"

Route124_Text_DeclanPostBattle:
	.string "Tôi nên bắt chuyện với mấy cô SWIMMERS\n"
	.string "rồi rủ họ bơi đường dài.$"

Route124_Text_IsabellaIntro:
	.string "Tôi sẽ không thua một HLV chỉ biết\n"
	.string "lướt sóng đâu.$"

Route124_Text_IsabellaDefeat:
	.string "Chỉ là mồ hôi chảy vào mắt thôi! Tôi\n"
	.string "không khóc!$"

Route124_Text_IsabellaPostBattle:
	.string "Quanh đây có thể tìm thấy những mảnh\n"
	.string "vỡ đủ màu rất đẹp.$"

Route125_Text_NolenIntro:
	.string "Tôi nghe thấy cậu đang đến nên đã nán\n"
	.string "lại chờ!$"

Route125_Text_NolenDefeat:
	.string "Tôi đầu hàng!$"

Route125_Text_NolenPostBattle:
	.string "Âm thanh truyền trong nước nhanh hơn\n"
	.string "trong không khí.$"

Route125_Text_StanIntro:
	.string "Này! Xem POKéMON cực chất của tôi đi!$"

Route125_Text_StanDefeat:
	.string "Tôi quẫy mãi rồi vẫn thua...$"

Route125_Text_StanPostBattle:
	.string "Tôi bị sức hút của HORSEA mê hoặc nên\n"
	.string "cũng bắt đầu tập bơi.$"

Route125_Text_TanyaIntro:
	.string "Tôi bơi mệt rồi. Cậu có muốn đấu với tôi\n"
	.string "không?$"

Route125_Text_TanyaDefeat:
	.string "Cậu giỏi quá mức rồi!$"

Route125_Text_TanyaPostBattle:
	.string "Phù... Đi đường nào mới tới MOSSDEEP\n"
	.string "CITY vậy?$"

Route125_Text_SharonIntro:
	.string "Bạn có muốn đối đầu với những POKéMON\n"
	.string "hệ WATER do tôi nuôi dưỡng không?$"

Route125_Text_SharonDefeat:
	.string "Thua mất rồi...$"

Route125_Text_SharonPostBattle:
	.string "Sức mạnh của bạn... Quả là hàng thật. Tôi\n"
	.string "kinh ngạc đấy!$"

Route125_Text_ErnestIntro:
	.string "Hô dô! Tôi là một SAILOR lực lưỡng, gan\n"
	.string "lì! Tôi đã vượt qua biển cả khắp thế\l"
	.string "gian!$"

Route125_Text_ErnestDefeat:
	.string "Gừừừ! Tôi không thắng nổi!$"

Route125_Text_ErnestPostBattle:
	.string "Thủy triều trong SHOAL CAVE cứ lên rồi\n"
	.string "xuống.\p"
	.string "Nhân tiện, từ lúc triều lên cao đến lúc\n"
	.string "triều xuống thấp mất khoảng sáu giờ.\l"
	.string "Bạn biết chứ?$"

Route125_Text_ErnestRegister:
	.string "Hãy đăng ký tôi vào POKéNAV của bạn,\n"
	.string "tôi sẽ mách bạn một điều hay.$"

Route125_Text_ErnestRematchIntro:
	.string "Đã đến lúc tôi trả món nợ này rồi! Nào,\n"
	.string "đấu thôi!$"

Route125_Text_ErnestRematchDefeat:
	.string "Tôi không thắng nổi! Hoàn toàn không\n"
	.string "thắng nổi!$"

Route125_Text_ErnestRematchPostBattle:
	.string "SHOAL CAVE...\p"
	.string "Có những nơi bạn chỉ có thể hoặc không\n"
	.string "thể đến tùy theo thủy triều lên xuống.\p"
	.string "Nhân tiện, từ lúc triều lên cao đến lúc\n"
	.string "triều xuống thấp mất khoảng sáu giờ.\l"
	.string "Đừng quên đấy!$"

Route125_Text_KimIntro:
	.string "KIM: Một ông lão vui tính sống trong\n"
	.string "SHOAL CAVE. Tôi nghe người ta kể vậy.\l"
	.string "Bạn cũng định đến gặp ông ấy à?$"

Route125_Text_KimDefeat:
	.string "KIM: Tôi cứ tưởng chúng tôi sẽ thắng.$"

Route125_Text_KimPostBattle:
	.string "KIM: Có một ông lão vui tính sống trong\n"
	.string "SHOAL CAVE, đúng không?\p"
	.string "Đi gặp ông ấy thôi, IRIS!$"

Route125_Text_KimNotEnoughMons:
	.string "KIM: Không, không, không! Bạn phải có\n"
	.string "hai POKéMON, nếu không thì không được!$"

Route125_Text_IrisIntro:
	.string "IRIS: KIM, cậu nói cho tôi biết chúng ta\n"
	.string "đang tìm gì ngoài này được không?$"

Route125_Text_IrisDefeat:
	.string "IRIS: Ôi, chúng ta cũng suýt thắng rồi.$"

Route125_Text_IrisPostBattle:
	.string "IRIS: KIM, chúng ta thật sự sẽ vào\n"
	.string "SHOAL CAVE sao? Sẽ ướt hết mất.$"

Route125_Text_IrisNotEnoughMons:
	.string "IRIS: Ôi, chúng tôi tuyệt đối không thể\n"
	.string "đấu kiểu hai chọi một đâu.$"

Route125_Text_PresleyIntro:
	.string "Tại sao một BIRDKEEPER như tôi lại ra\n"
	.string "tận biển nhỉ?$"

Route125_Text_PresleyDefeat:
	.string "Được rồi. Tôi sẽ cho bạn biết lý do tôi\n"
	.string "ở đây.$"

Route125_Text_PresleyPostBattle:
	.string "Tôi bỏ một lời nhắn vào chai rồi thả ra\n"
	.string "biển.\p"
	.string "Chắc chắn một cô gái SWIMMER sẽ tìm\n"
	.string "thấy nó!$"

Route125_Text_AuronIntro:
	.string "Này! Có phải bạn đã ném rác xuống biển\n"
	.string "không?$"

Route125_Text_AuronDefeat:
	.string "Ồ, hóa ra bạn không ném rác xuống biển.$"

Route125_Text_AuronPostBattle:
	.string "Lúc nãy tôi thấy một cái chai xấu xí dập\n"
	.string "dềnh trên sóng.\p"
	.string "Nghĩ đến chuyện có kẻ làm ô nhiễm biển\n"
	.string "là tôi nổi giận!$"

Route126_Text_BarryIntro:
	.string "Bơi lội rèn luyện toàn thân! Bạn sẽ khỏe\n"
	.string "lên!$"

Route126_Text_BarryDefeat:
	.string "Tôi công nhận! Bạn thắng!$"

Route126_Text_BarryPostBattle:
	.string "Nhờ ngày nào cũng bơi... Nhìn đi! Hãy\n"
	.string "chiêm ngưỡng vóc dáng này của tôi!$"

Route126_Text_DeanIntro:
	.string "Ngọn núi đá trắng sừng sững này chính\n"
	.string "là SOOTOPOLIS CITY.$"

Route126_Text_DeanDefeat:
	.string "Tôi bị hạ rồi sao?$"

Route126_Text_DeanPostBattle:
	.string "Tôi không tìm thấy lối vào SOOTOPOLIS.\n"
	.string "Nó có thể ở đâu nhỉ?$"

Route126_Text_NikkiIntro:
	.string "Ufufufufu! Tôi là nàng tiên cá!$"

Route126_Text_NikkiDefeat:
	.string "Giấc mơ của tôi vỡ tan như bong bóng!\n"
	.string "Ùng ục, ùng ục, ùng ục...$"

Route126_Text_NikkiPostBattle:
	.string "Bạn đánh tôi tan tác... Tôi muốn biến mất\n"
	.string "trong làn sóng tuyệt vọng...$"

Route126_Text_BrendaIntro:
	.string "Chào nhóc! Muốn đấu với tôi không?$"

Route126_Text_BrendaDefeat:
	.string "Ôi, khôngggg!$"

Route126_Text_BrendaPostBattle:
	.string "Tôi thích nô đùa cùng POKéMON giữa\n"
	.string "biển thế này!$"

Route126_Text_PabloIntro:
	.string "Nhìn thân hình được tạc nên này đi!\n"
	.string "Tôi còn rắn chắc hơn cả BLACK BELT!$"

Route126_Text_PabloDefeat:
	.string "Ối! Mạnh quá! Không tệ! Không tệ chút\n"
	.string "nào!$"

Route126_Text_PabloPostBattle:
	.string "Thua bạn làm mọi giác quan của tôi bừng\n"
	.string "tỉnh! Tôi sẽ rèn luyện bản thân và\l"
	.string "POKéMON chăm chỉ hơn!$"

Route126_Text_PabloRegister:
	.string "Ừ, bạn không tệ chút nào! Tôi muốn hiểu\n"
	.string "thêm về bạn!$"

Route126_Text_PabloRematchIntro:
	.string "Nhìn thân hình tuyệt đẹp này đi! Tôi\n"
	.string "còn cân đối hơn cả SWIMMER!$"

Route126_Text_PabloRematchDefeat:
	.string "Ối! Thật sự mạnh quá! Không tệ! Không\n"
	.string "tệ chút nào!$"

Route126_Text_PabloPostRematch:
	.string "Tôi sẽ luyện tập chăm chỉ hơn nữa! Bạn\n"
	.string "là nguồn động lực tuyệt vời! Nhất định\l"
	.string "phải quay lại nhé!$"

Route126_Text_LeonardoIntro:
	.string "Năm ngoái tôi còn không biết bơi, nhưng\n"
	.string "giờ đã là một SWIMMER khá cừ.\p"
	.string "Giờ tôi nghĩ mình có thể làm được bất\n"
	.string "cứ điều gì.$"

Route126_Text_LeonardoDefeat:
	.string "Chậc, tham quá cũng chẳng giúp ích gì.$"

Route126_Text_LeonardoPostBattle:
	.string "Cứ luyện tập thì bạn sẽ tiến bộ.\p"
	.string "Bạn còn trẻ, đừng ngại thử đủ mọi thứ!$"

Route126_Text_IsobelIntro:
	.string "Nước biển mà lọt vào mũi thì khó chịu\n"
	.string "kinh khủng, đúng không?$"

Route126_Text_IsobelDefeat:
	.string "Á! Bạn... Ục!$"

Route126_Text_IsobelPostBattle:
	.string "Ối, tôi bị sặc nước rồi! Đắng quá! Mặn\n"
	.string "quá!!$"

Route126_Text_SiennaIntro:
	.string "Tôi sẽ dốc hết lòng vào trận này!$"

Route126_Text_SiennaDefeat:
	.string "Bạn có quyết tâm lớn hơn!$"

Route126_Text_SiennaPostBattle:
	.string "Giờ tôi cần hạ nhiệt... Chắc tôi sẽ lặn\n"
	.string "một chuyến.$"

Route127_Text_CamdenIntro:
	.string "Nhìn mặt bạn là tôi biết. Bạn muốn thách\n"
	.string "đấu tôi.$"

Route127_Text_CamdenDefeat:
	.string "Oaoaoaoaoa...$"

Route127_Text_CamdenPostBattle:
	.string "Một trận đấu đẹp khiến tôi cảm thấy\n"
	.string "sảng khoái và thanh thản.$"

Route127_Text_DonnyIntro:
	.string "Bạn có một đối thủ mà mình cực ghét\n"
	.string "phải thua trước người đó không?$"

Route127_Text_DonnyDefeat:
	.string "Aaa! Tôi ghét thua cuộc!$"

Route127_Text_DonnyPostBattle:
	.string "Có đối thủ rồi, bạn có thấy mình phải\n"
	.string "không ngừng tiến bộ không?$"

Route127_Text_JonahIntro:
	.string "Nhờ câu cá, tôi đã đạt đến cảnh giới\n"
	.string "tĩnh tại, không chút gợn sóng...\p"
	.string "Xin cho phép tôi chứng minh...$"

Route127_Text_JonahDefeat:
	.string "Dù đã thua, lòng tôi vẫn bình thản...$"

Route127_Text_JonahPostBattle:
	.string "Không câu được gì cũng chẳng sao. Dây\n"
	.string "câu vẫn ở trong nước...$"

Route127_Text_HenryIntro:
	.string "Ối! Đừng nói là tôi câu trúng một\n"
	.string "SURFING POKéMON nhé?$"

Route127_Text_HenryDefeat:
	.string "Tôi không theo kịp!$"

Route127_Text_HenryPostBattle:
	.string "Nếu câu trúng POKéMON mạnh mẽ của bạn\n"
	.string "thì chắc tôi khốn đốn lắm!$"

Route127_Text_RogerIntro:
	.string "Ồ, chào nhé! Đây là cuộc so tài giữa một\n"
	.string "người hâm mộ POKéMON và một tay mê câu\l"
	.string "cá!$"

Route127_Text_RogerDefeat:
	.string "Không! Dây câu rối tung rồi! Cuộc vui\n"
	.string "kết thúc!$"

Route127_Text_RogerPostBattle:
	.string "Dây câu của tôi đang nhảy múa! Điệu\n"
	.string "tango rối dây! Ha ha ha, rối quá!$"

Route127_Text_AidanIntro:
	.string "BIRD POKéMON có thị lực tuyệt vời.\n"
	.string "Chúng phát hiện con mồi từ trên cao.$"

Route127_Text_AidanDefeat:
	.string "Phù... Tôi chịu thua.$"

Route127_Text_AidanPostBattle:
	.string "Vùng biển quanh đây có rất nhiều điểm\n"
	.string "lặn.\p"
	.string "Từ trên trời, bạn dễ dàng nhận ra chúng\n"
	.string "vì màu nước ở đó sẫm hơn.$"

Route127_Text_KojiIntro:
	.string "Hãy chạy bằng chân trần. Như thế lòng\n"
	.string "bàn chân sẽ trở nên chai cứng!$"

Route127_Text_KojiDefeat:
	.string "Ái! Có viên sỏi mắc dưới móng chân tôi!$"

Route127_Text_KojiPostBattle:
	.string "Đi chân trần thích lắm. Nhưng RUNNING\n"
	.string "SHOES của bạn cũng ngầu đấy.$"

Route127_Text_KojiRegister:
	.string "Với ai đánh bại mình, tôi đều làm thế\n"
	.string "này! Hy vọng chúng ta sẽ lại đấu với\l"
	.string "nhau.$"

Route127_Text_KojiRematchIntro:
	.string "Ngày nào tôi vẫn chạy chân trần. Lòng\n"
	.string "bàn chân tôi cứng lắm!$"

Route127_Text_KojiRematchDefeat:
	.string "Ái! Sỏi cắm vào hõm bàn chân tôi rồi!$"

Route127_Text_KojiPostRematch:
	.string "Bạn có muốn đi chân trần một lúc không?\n"
	.string "Để tôi thử RUNNING SHOES của bạn nhé?$"

Route127_Text_AthenaIntro:
	.string "Chúng ta nên đấu một trận chậm rãi và\n"
	.string "có tính toán.$"

Route127_Text_AthenaDefeat:
	.string "Bạn chẳng cho tôi cơ hội bày ra chiến\n"
	.string "thuật nào cả.$"

Route127_Text_AthenaPostBattle:
	.string "Khi được biển xanh và trời xanh bao\n"
	.string "quanh, tôi cảm thấy như thời gian chậm\l"
	.string "lại.$"

Route128_Text_IsaiahIntro:
	.string "EVER GRANDE CITY vẫn còn xa lắm...$"

Route128_Text_IsaiahDefeat:
	.string "Có vẻ chiến thắng đầu tiên của tôi cũng\n"
	.string "còn xa lắm...$"

Route128_Text_IsaiahPostBattle:
	.string "Cả đời tôi chỉ toàn thua, nhưng tôi sẽ\n"
	.string "không bao giờ bỏ cuộc!$"

Route128_Text_IsaiahRegister:
	.string "Tôi biết giờ mình chưa giỏi, nhưng tôi\n"
	.string "tin rồi sẽ có ngày chiến thắng.\p"
	.string "Xin hãy đăng ký tôi vào POKéNAV của\n"
	.string "bạn.$"

Route128_Text_IsaiahRematchIntro:
	.string "Tôi vẫn thấy sung sức. Tôi sẽ tiếp tục\n"
	.string "bơi đến EVER GRANDE CITY.$"

Route128_Text_IsaiahRematchDefeat:
	.string "Tôi vẫn chưa được nếm mùi chiến thắng\n"
	.string "đầu tiên...$"

Route128_Text_IsaiahPostRematch:
	.string "Rồi tôi sẽ tới EVER GRANDE CITY, nơi rồi\n"
	.string "tôi cũng sẽ chiến thắng...$"

Route128_Text_KatelynIntro:
	.string "Trong ba môn phối hợp, bạn phải bơi, đạp\n"
	.string "xe, rồi chạy marathon.\p"
	.string "Đó là một cuộc đua khắc nghiệt gồm ba\n"
	.string "môn.$"

Route128_Text_KatelynDefeat:
	.string "Một trận đấu POKéMON cũng khắc\n"
	.string "nghiệt...$"

Route128_Text_KatelynPostBattle:
	.string "Tiếp theo tôi phải đi BIKE, nhưng... Tôi\n"
	.string "sắp bỏ cuộc rồi...$"

Route128_Text_KatelynRegister:
	.string "Thôi thì tôi cũng nên cố tận dụng tình\n"
	.string "thế này. Khi nào đó tôi muốn tái đấu.$"

Route128_Text_KatelynRematchIntro:
	.string "Ba môn phối hợp là một chặng đường dài.\n"
	.string "Nhưng có lẽ con đường trở thành\l"
	.string "POKéMON CHAMPION cũng dài đằng đẵng\l"
	.string "và khắc nghiệt.$"

Route128_Text_KatelynRematchDefeat:
	.string "Một trận đấu POKéMON quả thật khắc\n"
	.string "nghiệt và không chút khoan nhượng...$"

Route128_Text_KatelynPostRematch:
	.string "Bạn nên nghiêm túc suy nghĩ về những\n"
	.string "thử thách trên VICTORY ROAD.$"

Route128_Text_AlexaIntro:
	.string "Chúng tôi đã nỗ lực rất nhiều để thách\n"
	.string "đấu POKéMON LEAGUE...\p"
	.string "Giờ chúng tôi không thể để thua!$"

Route128_Text_AlexaDefeat:
	.string "Ôi! Sao chuyện này có thể xảy ra chứ?!$"

Route128_Text_AlexaPostBattle:
	.string "Tôi đã làm biết bao điều để đến được\n"
	.string "đây, nên sẽ không bỏ cuộc chỉ vì một\l"
	.string "lần vấp ngã.$"

Route128_Text_RubenIntro:
	.string "Không có HLV nào mạnh hơn tôi!$"

Route128_Text_RubenDefeat:
	.string "Không thể nào!$"

Route128_Text_RubenPostBattle:
	.string "Có lẽ chẳng còn HLV nào mạnh hơn\n"
	.string "bạn!$"

Route128_Text_WayneIntro:
	.string "Tôi muốn đến EVER GRANDE, nên đã bắt\n"
	.string "một POKéMON biết chiêu WATERFALL để\l"
	.string "vượt qua thác nước.$"

Route128_Text_WayneDefeat:
	.string "Tôi thất vọng quá!$"

Route128_Text_WaynePostBattle:
	.string "Ôi, chán thật!\p"
	.string "POKéMON của tôi biết WATERFALL, nhưng\n"
	.string "tôi lại không có SOOTOPOLIS GYM BADGE!$"

Route128_Text_HarrisonIntro:
	.string "Trông bạn mạnh khiếp đấy. Không biết\n"
	.string "tôi có thắng nổi không?$"

Route128_Text_HarrisonDefeat:
	.string "Ối! Xem ra thắng bạn là chuyện bất khả\n"
	.string "thi rồi.$"

Route128_Text_HarrisonPostBattle:
	.string "Quanh EVER GRANDE có vô số HLV\n"
	.string "rất mạnh.\p"
	.string "Có phải tôi không đủ tầm không nhỉ?$"

Route128_Text_CarleeIntro:
	.string "Nắng ở khu vực này có vẻ gay gắt hơn\n"
	.string "hẳn.$"

Route128_Text_CarleeDefeat:
	.string "Ánh nắng chói quá nên tôi chẳng nhìn rõ\n"
	.string "được.$"

Route128_Text_CarleePostBattle:
	.string "Tôi nên sớm quay về thôi. Phải thoa lại\n"
	.string "kem chống nắng mới được.$"

Route129_Text_ChaseIntro:
	.string "Đây là lần đầu tôi thi ba môn phối hợp.\n"
	.string "Tôi căng thẳng và hồi hộp quá!$"

Route129_Text_ChaseDefeat:
	.string "Gừừừào! Tôi không thắng nổi rồi!$"

Route129_Text_ChasePostBattle:
	.string "Cứ căng thẳng thế này thì tôi không\n"
	.string "thể dốc hết sức được.$"

Route129_Text_AllisonIntro:
	.string "Tôi đang thi ba môn phối hợp, nhưng\n"
	.string "thôi được, đấu một trận nhé?$"

Route129_Text_AllisonDefeat:
	.string "Tôi cứ chắc mẩm mình sẽ thắng cơ!$"

Route129_Text_AllisonPostBattle:
	.string "Bạn biết điều tuyệt nhất của ba môn\n"
	.string "phối hợp là gì không?\p"
	.string "Đó là thử xem sức mạnh và sức bền của\n"
	.string "bản thân có thể chống chọi với Mẹ thiên\l"
	.string "nhiên đến đâu!$"

Route129_Text_ReedIntro:
	.string "Này, này! Bắt đầu luôn đi!$"

Route129_Text_ReedDefeat:
	.string "Thua, tôi thua rồi. Vậy là hết!$"

Route129_Text_ReedPostBattle:
	.string "Kẻ thua cuộc chẳng được gì cả. Đến lúc\n"
	.string "tôi cuốn gói về nhà rồi.$"

Route129_Text_TishaIntro:
	.string "Vội gì chứ? Cứ chậm rãi, thong thả thôi.$"

Route129_Text_TishaDefeat:
	.string "Ôi chao. Tôi còn muốn thư giãn thêm\n"
	.string "chút nữa...$"

Route129_Text_TishaPostBattle:
	.string "Bạn cũng ghét mắc sai lầm khi đang vội,\n"
	.string "đúng không?\p"
	.string "Vì thế tôi luôn cố làm mọi việc thật\n"
	.string "chậm rãi.$"

Route129_Text_ClarenceIntro:
	.string "Lướt sóng không dễ như nhìn đâu, đúng\n"
	.string "không?$"

Route129_Text_ClarenceDefeat:
	.string "Chiến thắng đúng là chẳng dễ dàng.$"

Route129_Text_ClarencePostBattle:
	.string "Bạn đang nhắm đến POKéMON LEAGUE à?\n"
	.string "Cứ cố gắng nhé!$"

Route130_Text_RodneyIntro:
	.string "Thật bất ngờ! Tôi không nghĩ sẽ gặp một\n"
	.string "HLV giữa biển.\p"
	.string "Chúng ta nên đấu một trận!$"

Route130_Text_RodneyDefeat:
	.string "Nhóc này mạnh kinh khủng...$"

Route130_Text_RodneyPostBattle:
	.string "Ánh mắt bạn cho thấy bạn đã trải qua\n"
	.string "những thử thách khắc nghiệt và giành\l"
	.string "chiến thắng. Rất hợp với bạn đấy!$"

Route130_Text_KatieIntro:
	.string "Giữa biển xanh thẳm, trái tim xanh tan\n"
	.string "vỡ của tôi tìm được niềm an ủi trong\l"
	.string "những con sóng.$"

Route130_Text_KatieDefeat:
	.string "Tựa biển xanh mênh mông, thế giới\n"
	.string "POKéMON sâu rộng đến mức không thể\l"
	.string "tưởng tượng.$"

Route130_Text_KatiePostBattle:
	.string "Trẻ em trên khắp thế giới đều mơ một\n"
	.string "ngày trở thành POKéMON CHAMPION.$"

Route130_Text_SantiagoIntro:
	.string "Thả mình trôi giữa biển khơi thế này...\n"
	.string "Thật yên bình.$"

Route130_Text_SantiagoDefeat:
	.string "Lẽ ra tôi phải bớt thảnh thơi một chút!$"

Route130_Text_SantiagoPostBattle:
	.string "Vừa bơi vừa chiến đấu thế này... Tôi\n"
	.string "đúng là một anh chàng hạnh phúc...$"

Route131_Text_RichardIntro:
	.string "Biển đầy ắp POKéMON. Bơi ở đây chẳng\n"
	.string "dễ chút nào, tôi nói thật đấy.$"

Route131_Text_RichardDefeat:
	.string "POKéMON được HLV nuôi dưỡng\n"
	.string "đúng là mạnh khủng khiếp...$"

Route131_Text_RichardPostBattle:
	.string "Hộc... Hộc... Tôi kiệt sức rồi...\p"
	.string "Lúc đi thì dễ, lúc về mới khó.\p"
	.string "Không biết tôi còn đủ sức cho chuyến\n"
	.string "về không nữa?$"

Route131_Text_HermanIntro:
	.string "Biển... Biển... Biển... Nhìn đến đâu cũng\n"
	.string "chỉ thấy biển! Tôi chán biển đến phát\l"
	.string "ngấy rồi!$"

Route131_Text_HermanDefeat:
	.string "Ọe!$"

Route131_Text_HermanPostBattle:
	.string "Biển thì ta chán, nhưng bơi thì ta phải\n"
	.string "bơi.\p"
	.string "Ta là một tay bơi bẩm sinh! Chính là ta.$"

Route131_Text_SusieIntro:
	.string "Chào cưng, đợi đã! Tôi với bạn đấu một\n"
	.string "trận nhé!$"

Route131_Text_SusieDefeat:
	.string "Trông vậy mà bạn mạnh ghê!$"

Route131_Text_SusiePostBattle:
	.string "Bạn có thấy anh chàng đằng kia cứ than\n"
	.string "chán biển không?\p"
	.string "Chỉ nói miệng thế thôi. Anh ta yêu biển\n"
	.string "đến hết thuốc chữa rồi!$"

Route131_Text_KaraIntro:
	.string "Sao đàn ông lại mê đồ bơi đến thế nhỉ?\p"
	.string "Ai cũng nhìn tôi chằm chằm!$"

Route131_Text_KaraDefeat:
	.string "Tôi không đủ tầm rồi!$"

Route131_Text_KaraPostBattle:
	.string "Có lẽ không phải bộ đồ bơi khiến đàn\n"
	.string "ông ngoái nhìn. Chắc chắn là vì sắc đẹp\l"
	.string "của tôi!$"

Route131_Text_ReliIntro:
	.string "RELI: Chị em tôi sẽ phối hợp để đấu với\n"
	.string "bạn!$"

Route131_Text_ReliDefeat:
	.string "RELI: Dù đã phối hợp với nhau, chị em\n"
	.string "tôi vẫn không thắng nổi...$"

Route131_Text_ReliPostBattle:
	.string "RELI: Người dân PACIFIDLOG gắn bó với\n"
	.string "biển và POKéMON ngay từ khi chào đời.$"

Route131_Text_ReliNotEnoughMons:
	.string "RELI: Bạn không có hai POKéMON à? Vậy\n"
	.string "thì chúng tôi không thể tận hưởng trận\l"
	.string "đấu được rồi.$"

Route131_Text_IanIntro:
	.string "IAN: Em sẽ cùng chị cố gắng hết sức!$"

Route131_Text_IanDefeat:
	.string "IAN: Em và chị đã cố hết sức, nhưng vẫn\n"
	.string "không thắng nổi...$"

Route131_Text_IanPostBattle:
	.string "IAN: Bạn biết PACIFIDLOG là một thị\n"
	.string "trấn nổi trên biển mà, phải không?\p"
	.string "Vì vậy, hễ nơi nào có biển thì nơi đó là\n"
	.string "một phần của PACIFIDLOG!$"

Route131_Text_IanNotEnoughMons:
	.string "IAN: Nếu bạn có hai POKéMON, chúng tôi\n"
	.string "sẽ đấu với bạn!$"

Route131_Text_TaliaIntro:
	.string "Nếu thắng tôi, tôi sẽ cho bạn một tin\n"
	.string "cực kỳ hữu ích!$"

Route131_Text_TaliaDefeat:
	.string "Ơ? Tôi thua rồi sao?$"

Route131_Text_TaliaPostBattle:
	.string "Gần đây có một nơi rất kỳ lạ. Ở đó có\n"
	.string "một tòa tháp khổng lồ. Sao bạn không đi\l"
	.string "xem thử?$"

Route131_Text_KevinIntro:
	.string "Người dân PACIFIDLOG rất hiền hòa.\p"
	.string "Họ chẳng bao giờ nổi giận. Tôi cũng thế.$"

Route131_Text_KevinDefeat:
	.string "Ối!$"

Route131_Text_KevinPostBattle:
	.string "Chậc! ...Khoan, không phải. Tôi đâu có\n"
	.string "giận. Thật đấy!\p"
	.string "Nhưng mà bạn mạnh thật! Ha ha ha!$"

Route132_Text_GilbertIntro:
	.string "Hồi nhỏ tôi suốt ngày bị cảm, nhưng từ\n"
	.string "khi bắt đầu bơi, tôi đã trở nên cực kỳ\l"
	.string "khỏe mạnh.$"

Route132_Text_GilbertDefeat:
	.string "Tôi khao khát thêm sức mạnh...$"

Route132_Text_GilbertPostBattle:
	.string "HLV băng qua đồng bằng và núi\n"
	.string "non, nên chắc họ cũng rất khỏe.$"

Route132_Text_DanaIntro:
	.string "Tôi cố tránh bơi ở những nơi dòng chảy\n"
	.string "quá mạnh.$"

Route132_Text_DanaDefeat:
	.string "Ôi, xin đừng!$"

Route132_Text_DanaPostBattle:
	.string "Nếu bị cuốn đi, tôi sẽ chẳng còn biết\n"
	.string "mình đang ở đâu nữa...$"

Route132_Text_RonaldIntro:
	.string "Thắng hay thua, không thử thì sao biết\n"
	.string "được!$"

Route132_Text_RonaldDefeat:
	.string "Oa! Tôi chìm trong thất bại rồi!$"

Route132_Text_RonaldPostBattle:
	.string "Tôi không bao giờ đấu khi biết chắc\n"
	.string "mình sẽ thắng. Tôi thích những trận\l"
	.string "đấu mong manh giữa thắng và thua!$"

Route132_Text_KiyoIntro:
	.string "Tôi suy ngẫm về POKéMON 24 giờ mỗi\n"
	.string "ngày. Làm sao bạn có thể thắng tôi chứ?$"

Route132_Text_KiyoDefeat:
	.string "Tôi thua. Tôi xin nhận thất bại.$"

Route132_Text_KiyoPostBattle:
	.string "Ư... Bạn là một kẻ cuồng POKéMON, phải\n"
	.string "không?\p"
	.string "Hẳn bạn cũng suy ngẫm về POKéMON 24\n"
	.string "giờ mỗi ngày nhỉ?$"

Route132_Text_MakaylaIntro:
	.string "Tôi luôn ở bên chồng, nhưng không có\n"
	.string "anh ấy tôi vẫn thắng được.$"

Route132_Text_MakaylaDefeat:
	.string "Ôi, xem ra tôi vẫn chưa đủ giỏi.$"

Route132_Text_MakaylaPostBattle:
	.string "Chàng trai đằng kia trông hệt như\n"
	.string "chồng tôi hồi trẻ.\p"
	.string "Cậu ấy làm tôi đỏ cả mặt!$"

Route132_Text_JonathanIntro:
	.string "Có ai đó cứ nhìn tôi chằm chằm. Là bạn\n"
	.string "sao?$"

Route132_Text_JonathanDefeat:
	.string "Chà! Đúng là mạnh thật đấy!$"

Route132_Text_JonathanPostBattle:
	.string "Tôi cứ có cảm giác ai đó đang nhìn mình.\p"
	.string "Tôi không thể tập trung được!$"

Route132_Text_PaxtonIntro:
	.string "Vợ tôi đi đâu mất rồi nhỉ? Tôi lúc nào\n"
	.string "cũng ở bên cô ấy. Không biết một mình\l"
	.string "tôi có thắng nổi không.$"

Route132_Text_PaxtonDefeat:
	.string "À, hóa ra cuối cùng một mình tôi vẫn\n"
	.string "không thể thắng.$"

Route132_Text_PaxtonPostBattle:
	.string "Chắc vợ tôi đang tìm tôi. Tôi nên đi tìm\n"
	.string "cô ấy ngay.$"

Route132_Text_DarcyIntro:
	.string "Tôi thích luyện tập một mình ở đây. Mọi\n"
	.string "người kéo đến đông thế này thật phiền\l"
	.string "quá!$"

Route132_Text_DarcyDefeat:
	.string "Được rồi! Tôi sẽ không phàn nàn chuyện\n"
	.string "có người khác ở đây nữa.$"

Route132_Text_DarcyPostBattle:
	.string "Có lẽ tôi có thể bắt cặp với ông lão kia\n"
	.string "để thách đấu đội bên đó.$"

Route133_Text_FranklinIntro:
	.string "Bạn cũng bị dòng nước cuốn đến đây à?\n"
	.string "Chắc đây là định mệnh. Đấu thôi!$"

Route133_Text_FranklinDefeat:
	.string "Mạnh! Mạnh quá mức rồi!$"

Route133_Text_FranklinPostBattle:
	.string "Đúng là số tôi đen đủi mới có một\n"
	.string "HLV mạnh như bạn trôi dạt đến\l"
	.string "đây... Chắc tôi bị nguyền rủa rồi...$"

Route133_Text_DebraIntro:
	.string "Đời tôi chỉ toàn đau buồn và khổ sở...\n"
	.string "Tôi bị bỏ rơi, rồi trôi dạt đến tận đây...$"

Route133_Text_DebraDefeat:
	.string "Lại thua nữa...$"

Route133_Text_DebraPostBattle:
	.string "Một cuộc đời trôi dạt... Tôi không muốn\n"
	.string "thế nữa!$"

Route133_Text_LindaIntro:
	.string "Chào mừng! Tôi đã chờ bạn!$"

Route133_Text_LindaDefeat:
	.string "Không! Xin đừng!$"

Route133_Text_LindaPostBattle:
	.string "Một HLV nhỏ tuổi mà mạnh đến thế...\n"
	.string "Thật bực mình!$"

Route133_Text_WarrenIntro:
	.string "Tôi cũng muốn thắng như mọi người,\n"
	.string "nhưng tôi sẽ không nuôi POKéMON theo\l"
	.string "cách của mọi người.$"

Route133_Text_WarrenDefeat:
	.string "Khỉ thật! Cách của tôi vẫn còn quá dễ\n"
	.string "dãi!$"

Route133_Text_WarrenPostBattle:
	.string "Làm mọi thứ theo cách mình muốn vui\n"
	.string "hơn nhiều so với việc giống hệt mọi\l"
	.string "người. Rõ ràng là thế mà!$"

Route133_Text_BeckIntro:
	.string "Tôi đã cùng BIRD POKéMON của mình đi\n"
	.string "một mạch tới tận đây.$"

Route133_Text_BeckDefeat:
	.string "Bạn... Bạn ngầu đến choáng ngợp!$"

Route133_Text_BeckPostBattle:
	.string "Tôi muốn quay lại FORTREE, nhưng tôi\n"
	.string "cũng dần thích nơi này rồi.$"

Route133_Text_MollieIntro:
	.string "Chắc tôi đã chiến đấu hàng nghìn lần.\n"
	.string "Tôi chẳng đếm nổi nữa.$"

Route133_Text_MollieDefeat:
	.string "Dù đã thua hàng nghìn lần, mỗi thất bại\n"
	.string "vẫn khiến tôi đau lòng.$"

Route133_Text_MolliePostBattle:
	.string "Cứ tiếp tục cố gắng nhé, người trẻ\n"
	.string "tuổi. Rồi cháu sẽ được như vợ chồng\l"
	.string "ta.$"

Route133_Text_ConorIntro:
	.string "Người trẻ quá dễ dãi, cứ thuận theo\n"
	.string "dòng mà đi. Chẳng có phương hướng gì\l"
	.string "cả.$"

Route133_Text_ConorDefeat:
	.string "Cháu có mục tiêu rất rõ ràng.$"

Route133_Text_ConorPostBattle:
	.string "Đừng để người khác dẫn cháu đi lạc. Khi\n"
	.string "lớn lên cũng đừng đánh mất phương\l"
	.string "hướng.$"

Route134_Text_JackIntro:
	.string "Ngay cả những POKéMON biết bơi cũng bị\n"
	.string "dòng chảy xiết cuốn đi.$"

Route134_Text_JackDefeat:
	.string "Áaaaa!$"

Route134_Text_JackPostBattle:
	.string "Tôi nghĩ POKéMON rất thích những dòng\n"
	.string "chảy xiết quanh vùng này.$"

Route134_Text_LaurelIntro:
	.string "Các LUVDISC của tôi đang muốn đấu một\n"
	.string "trận thật vui. Bạn tham gia cùng chúng\l"
	.string "tôi nhé?$"

Route134_Text_LaurelDefeat:
	.string "Ối!$"

Route134_Text_LaurelPostBattle:
	.string "Có một nhà sưu tầm đang tìm kiếm\n"
	.string "SCALES của LUVDISC.$"

Route134_Text_AlexIntro:
	.string "Được rồi! Nghỉ thế đủ rồi, cả đội! Đến\n"
	.string "lúc thi đấu thôi!$"

Route134_Text_AlexDefeat:
	.string "Lại kiệt sức rồi...$"

Route134_Text_AlexPostBattle:
	.string "BIRD POKéMON của tôi nhanh mệt sau một\n"
	.string "chuyến bay dài...$"

Route134_Text_HitoshiIntro:
	.string "Ngươi là một HLV POKéMON. Không\n"
	.string "cần nhiều lời. Giờ thì chiến đấu.$"

Route134_Text_HitoshiDefeat:
	.string "... ... ... ... ... ... ... ... ... ... ... ...$"

Route134_Text_HitoshiPostBattle:
	.string "Chính ta là người thách đấu, vậy mà lại\n"
	.string "thua. Thật quá hổ thẹn...$"

Route134_Text_AaronIntro:
	.string "Thủy triều dữ dội ở vùng này giúp chúng\n"
	.string "tôi ngày càng mạnh hơn.$"

Route134_Text_AaronDefeat:
	.string "Tôi xin tâm phục khẩu phục.$"

Route134_Text_AaronPostBattle:
	.string "Chúng tôi sẽ quay lại METEOR FALLS để\n"
	.string "luyện tập thêm.\p"
	.string "Nếu muốn, cậu cũng nên tới đó. Chắc\n"
	.string "chắn nó sẽ giúp cậu cứng cáp hơn!$"

Route134_Text_KelvinIntro:
	.string "T-thuyền của chúng tôi! Thủy triều\n"
	.string "cuốn nó đi mất rồi!$"

Route134_Text_KelvinDefeat:
	.string "Á á á á! Xin hãy dừng lại! Làm ơn!$"

Route134_Text_KelvinPostBattle:
	.string "Nếu không thể SURF thì chúng tôi về nhà\n"
	.string "bằng cách nào đây?\p"
	.string "Thật ra, tôi biết POKéMON đã ngất vẫn\n"
	.string "có thể SURF, nhưng làm vậy cứ sai sai.$"

Route134_Text_MarleyIntro:
	.string "POKéMON của bạn có né được những đòn\n"
	.string "nhanh như chớp của chúng tôi không?$"

Route134_Text_MarleyDefeat:
	.string "Tôi chưa từng biết có kỹ thuật như\n"
	.string "thế! Bạn đã đánh bại chúng tôi hoàn\l"
	.string "toàn.$"

Route134_Text_MarleyPostBattle:
	.string "Niềm đam mê tốc độ của tôi vẫn chưa hề\n"
	.string "nguội. Tôi sẽ cố gắng hơn nữa.$"

Route134_Text_ReynaIntro:
	.string "POKéMON của tôi không dễ bị hạ đâu!$"

Route134_Text_ReynaDefeat:
	.string "Đùa à! Giải thích xem sao tôi lại thua\n"
	.string "đi!$"

Route134_Text_ReynaPostBattle:
	.string "Ha ha! Đúng là cậu thắng rồi!\p"
	.string "Tôi sẽ từng bước vươn lên bằng cách\n"
	.string "thách đấu mọi HLV mình gặp!$"

Route134_Text_HudsonIntro:
	.string "Này, cậu có thấy một SAILOR khác quanh\n"
	.string "đây không?$"

Route134_Text_HudsonDefeat:
	.string "Khá lắm!$"

Route134_Text_HudsonPostBattle:
	.string "Thuyền của chúng tôi đã trôi ra biển.\p"
	.string "Anh bạn của tôi nhút nhát lắm nên tôi\n"
	.string "đang lo cho cậu ấy.$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global Route102_Text_CalvinIntro
	.global Route102_Text_CalvinDefeated
	.global Route102_Text_CalvinPostBattle
	.global Route102_Text_CalvinRegister
	.global Route102_Text_CalvinRegisterShort
	.global Route102_Text_CalvinRematchIntro
	.global Route102_Text_CalvinRematchDefeated
	.global Route102_Text_CalvinRematchPostBattle
	.global Route102_Text_AllenIntro
	.global Route102_Text_AllenDefeated
	.global Route102_Text_AllenPostBattle
	.global Route102_Text_RickIntro
	.global Route102_Text_RickDefeated
	.global Route102_Text_RickPostBattle
	.global Route102_Text_TianaIntro
	.global Route102_Text_TianaDefeated
	.global Route102_Text_TianaPostBattle
	.global Route103_Text_DaisyIntro
	.global Route103_Text_DaisyDefeated
	.global Route103_Text_DaisyPostBattle
	.global Route103_Text_AmyIntro
	.global Route103_Text_AmyDefeated
	.global Route103_Text_AmyPostBattle
	.global Route103_Text_AmyNotEnoughPokemon
	.global Route103_Text_LivIntro
	.global Route103_Text_LivDefeated
	.global Route103_Text_LivPostBattle
	.global Route103_Text_AmyLivRegister
	.global Route103_Text_LivNotEnoughPokemon
	.global Route103_Text_AmyRematchIntro
	.global Route103_Text_AmyRematchDefeated
	.global Route103_Text_AmyRematchPostBattle
	.global Route103_Text_AmyRematchNotEnoughPokemon
	.global Route103_Text_LivRematchIntro
	.global Route103_Text_LivRematchDefeated
	.global Route103_Text_LivRematchPostBattle
	.global Route103_Text_LivRematchNotEnoughPokemon
	.global Route103_Text_AndrewIntro
	.global Route103_Text_AndrewDefeated
	.global Route103_Text_AndrewPostBattle
	.global Route103_Text_MiguelIntro
	.global Route103_Text_MiguelDefeated
	.global Route103_Text_MiguelPostBattle
	.global Route103_Text_MiguelRegister
	.global Route103_Text_MiguelRematchIntro
	.global Route103_Text_MiguelRematchDefeated
	.global Route103_Text_MiguelRematchPostBattle
	.global Route103_Text_PeteIntro
	.global Route103_Text_PeteDefeated
	.global Route103_Text_PetePostBattle
	.global Route103_Text_IsabelleIntro
	.global Route103_Text_IsabelleDefeated
	.global Route103_Text_IsabellePostBattle
	.global Route103_Text_RhettIntro
	.global Route103_Text_RhettDefeated
	.global Route103_Text_RhettPostBattle
	.global Route103_Text_MarcosIntro
	.global Route103_Text_MarcosDefeated
	.global Route103_Text_MarcosPostBattle
	.global Route104_Text_GinaIntro
	.global Route104_Text_GinaDefeat
	.global Route104_Text_GinaPostBattle
	.global Route104_Text_GinaNotEnoughMons
	.global Route104_Text_MiaIntro
	.global Route104_Text_MiaDefeat
	.global Route104_Text_MiaPostBattle
	.global Route104_Text_MiaNotEnoughMons
	.global Route104_Text_IvanIntro
	.global Route104_Text_IvanDefeat
	.global Route104_Text_IvanPostBattle
	.global Route104_Text_BillyIntro
	.global Route104_Text_BillyDefeat
	.global Route104_Text_BillyPostBattle
	.global Route104_Text_HaleyIntro
	.global Route104_Text_HaleyDefeat
	.global Route104_Text_HaleyPostBattle
	.global Route104_Text_HaleyRegister1
	.global Route104_Text_HaleyRegister2
	.global Route104_Text_HaleyRematchIntro
	.global Route104_Text_HaleyRematchDefeat
	.global Route104_Text_HaleyPostRematch
	.global Route104_Text_WinstonIntro
	.global Route104_Text_WinstonDefeat
	.global Route104_Text_WinstonPostBattle
	.global Route104_Text_WinstonRegister1
	.global Route104_Text_WinstonRegister2
	.global Route104_Text_WinstonRematchIntro
	.global Route104_Text_WinstonRematchDefeat
	.global Route104_Text_WinstonPostRematch
	.global Route104_Text_CindyIntro
	.global Route104_Text_CindyDefeat
	.global Route104_Text_CindyPostBattle
	.global Route104_Text_CindyRegister1
	.global Route104_Text_CindyRegister2
	.global Route104_Text_CindyRematchIntro
	.global Route104_Text_CindyRematchDefeat
	.global Route104_Text_CindyPostRematch
	.global Route104_Text_DarianIntro
	.global Route104_Text_DarianDefeat
	.global Route104_Text_DarianPostBattle
	.global Route105_Text_FosterIntro
	.global Route105_Text_FosterDefeated
	.global Route105_Text_FosterPostBattle
	.global Route105_Text_LuisIntro
	.global Route105_Text_LuisDefeated
	.global Route105_Text_LuisPostBattle
	.global Route105_Text_DominikIntro
	.global Route105_Text_DominikDefeated
	.global Route105_Text_DominikPostBattle
	.global Route105_Text_BeverlyIntro
	.global Route105_Text_BeverlyDefeated
	.global Route105_Text_PostBattle
	.global Route105_Text_ImaniIntro
	.global Route105_Text_ImaniDefeated
	.global Route105_Text_ImaniPostBattle
	.global Route105_Text_AndresIntro
	.global Route105_Text_AndresDefeated
	.global Route105_Text_AndresPostBattle
	.global Route105_Text_AndresRegister
	.global Route105_Text_AndresRematchIntro
	.global Route105_Text_AndresRematchDefeated
	.global Route105_Text_AndresRematchPostBattle
	.global Route105_Text_JosueIntro
	.global Route105_Text_JosueDefeated
	.global Route105_Text_JosuePostBattle
	.global Route106_Text_ElliotIntro
	.global Route106_Text_ElliotDefeated
	.global Route106_Text_ElliotPostBattle
	.global Route106_Text_ElliotRegister
	.global Route106_Text_ElliotRematchIntro
	.global Route106_Text_ElliotRematchDefeated
	.global Route106_Text_ElliotRematchPostBattle
	.global Route106_Text_NedIntro
	.global Route106_Text_NedDefeated
	.global Route106_Text_NedPostBattle
	.global Route106_Text_DouglasIntro
	.global Route106_Text_DouglasDefeated
	.global Route106_Text_DouglasPostBattle
	.global Route106_Text_KylaIntro
	.global Route106_Text_KylaDefeated
	.global Route106_Text_KylaPostBattle
	.global Route107_Text_DarrinIntro
	.global Route107_Text_DarrinDefeated
	.global Route107_Text_DarrinPostBattle
	.global Route107_Text_TonyIntro
	.global Route107_Text_TonyDefeated
	.global Route107_Text_TonyPostBattle
	.global Route107_Text_TonyRegister
	.global Route107_Text_TonyRematchIntro
	.global Route107_Text_TonyRematchDefeated
	.global Route107_Text_TonyRematchPostBattle
	.global Route107_Text_DeniseIntro
	.global Route107_Text_DeniseDefeated
	.global Route107_Text_DenisePostBattle
	.global Route107_Text_BethIntro
	.global Route107_Text_BethDefeated
	.global Route107_Text_BethPostBattle
	.global Route107_Text_LisaIntro
	.global Route107_Text_LisaDefeated
	.global Route107_Text_LisaPostBattle
	.global Route107_Text_LisaNotEnoughPokemon
	.global Route107_Text_RayIntro
	.global Route107_Text_RayDefeated
	.global Route107_Text_RayPostBattle
	.global Route107_Text_RayNotEnoughPokemon
	.global Route107_Text_CamronIntro
	.global Route107_Text_CamronDefeated
	.global Route107_Text_CamronPostBattle
	.global Route108_Text_JeromeIntro
	.global Route108_Text_JeromeDefeated
	.global Route108_Text_JeromePostBattle
	.global Route108_Text_MatthewIntro
	.global Route108_Text_MatthewDefeated
	.global Route108_Text_MatthewPostBattle
	.global Route108_Text_TaraIntro
	.global Route108_Text_TaraDefeated
	.global Route108_Text_TaraPostBattle
	.global Route108_Text_MissyIntro
	.global Route108_Text_MissyDefeated
	.global Route108_Text_MissyPostBattle
	.global Route108_Text_CoryIntro
	.global Route108_Text_CoryDefeated
	.global Route108_Text_CoryPostBattle
	.global Route108_Text_CoryRegister
	.global Route108_Text_CoryRematchIntro
	.global Route108_Text_CoryRematchDefeated
	.global Route108_Text_CoryRematchPostBattle
	.global Route108_Text_CarolinaIntro
	.global Route108_Text_CarolinaDefeated
	.global Route108_Text_CarolinaPostBattle
	.global Route109_Text_DavidIntro
	.global Route109_Text_DavidDefeated
	.global Route109_Text_DavidPostBattle
	.global Route109_Text_AliceIntro
	.global Route109_Text_AliceDefeated
	.global Route109_Text_AlicePostBattle
	.global Route109_Text_HueyIntro
	.global Route109_Text_HueyDefeated
	.global Route109_Text_HueyPostBattle
	.global Route109_Text_EdmondIntro
	.global Route109_Text_EdmondDefeated
	.global Route109_Text_EdmondPostBattle
	.global Route109_Text_RickyIntro
	.global Route109_Text_RickyDefeated
	.global Route109_Text_RickyPostBattle
	.global Route109_Text_RickyRegister
	.global Route109_Text_RickyRematchIntro
	.global Route109_Text_RickyRematchDefeated
	.global Route109_Text_RickyRematchPostBattle
	.global Route109_Text_LolaIntro
	.global Route109_Text_LolaDefeated
	.global Route109_Text_LolaPostBattle
	.global Route109_Text_LolaRegister
	.global Route109_Text_LolaRematchIntro
	.global Route109_Text_LolaRematchDefeated
	.global Route109_Text_LolaRematchPostBattle
	.global Route109_Text_AustinaIntro
	.global Route109_Text_AustinaDefeated
	.global Route109_Text_AustinaPostBattle
	.global Route109_Text_GwenIntro
	.global Route109_Text_GwenDefeated
	.global Route109_Text_GwenPostBattle
	.global Route109_Text_CarterIntro
	.global Route109_Text_CarterDefeated
	.global Route109_Text_CarterPostBattle
	.global Route109_Text_PaulIntro
	.global Route109_Text_PaulDefeated
	.global Route109_Text_PaulPostBattle
	.global Route109_Text_PaulNotEnoughPokemon
	.global Route109_Text_MelIntro
	.global Route109_Text_MelDefeated
	.global Route109_Text_MelPostBattle
	.global Route109_Text_MelNotEnoughPokemon
	.global Route109_Text_ChandlerIntro
	.global Route109_Text_ChandlerDefeated
	.global Route109_Text_ChandlerPostBattle
	.global Route109_Text_HaileyIntro
	.global Route109_Text_HaileyDefeated
	.global Route109_Text_HaileyPostBattle
	.global Route109_Text_ElijahIntro
	.global Route109_Text_ElijahDefeated
	.global Route109_Text_ElijahPostBattle
	.global Route110_Text_JacobIntro
	.global Route110_Text_JacobDefeated
	.global Route110_Text_JacobPostBattle
	.global Route110_Text_AnthonyIntro
	.global Route110_Text_AnthonyDefeated
	.global Route110_Text_AnthonyPostBattle
	.global Route110_Text_BenjaminIntro
	.global Route110_Text_BenjaminDefeated
	.global Route110_Text_BenjaminPostBattle
	.global Route110_Text_BenjaminRegister
	.global Route110_Text_BenjaminRematchIntro
	.global Route110_Text_BenjaminRematchDefeated
	.global Route110_Text_BenjaminRematchPostBattle
	.global Route110_Text_AbigailIntro
	.global Route110_Text_AbigailDefeated
	.global Route110_Text_AbigailPostBattle
	.global Route110_Text_AbigailRegister
	.global Route110_Text_AbigailRematchIntro
	.global Route110_Text_AbigailRematchDefeated
	.global Route110_Text_AbigailRematchPostBattle
	.global Route110_Text_JasmineIntro
	.global Route110_Text_JasmineDefeated
	.global Route110_Text_JasminePostBattle
	.global Route110_Text_EdwardIntro
	.global Route110_Text_EdwardDefeated
	.global Route110_Text_EdwardPostBattle
	.global Route110_Text_JaclynIntro
	.global Route110_Text_JaclynDefeated
	.global Route110_Text_JaclynPostBattle
	.global Route110_Text_EdwinIntro
	.global Route110_Text_EdwinDefeated
	.global Route110_Text_EdwinPostBattle
	.global Route110_Text_EdwinRegister
	.global Route110_Text_EdwinRematchIntro
	.global Route110_Text_EdwinRematchDefeated
	.global Route110_Text_EdwinRematchPostBattle
	.global Route110_Text_DaleIntro
	.global Route110_Text_DaleDefeated
	.global Route110_Text_DalePostBattle
	.global Route110_Text_IsabelIntro
	.global Route110_Text_IsabelDefeated
	.global Route110_Text_IsabelPostBattle
	.global Route110_Text_IsabelRegister
	.global Route110_Text_IsabelRematchIntro
	.global Route110_Text_IsabelRematchDefeated
	.global Route110_Text_IsabelRematchPostBattle
	.global Route110_Text_TimmyIntro
	.global Route110_Text_TimmyDefeated
	.global Route110_Text_TimmyPostBattle
	.global Route110_Text_AlyssaIntro
	.global Route110_Text_AlyssaDefeated
	.global Route110_Text_AlyssaPostBattle
	.global Route110_Text_JosephIntro
	.global Route110_Text_JosephDefeated
	.global Route110_Text_JosephPostBattle
	.global Route110_Text_KalebIntro
	.global Route110_Text_KalebDefeated
	.global Route110_Text_KalebPostBattle
	.global Route111_Text_DrewIntro
	.global Route111_Text_DrewDefeat
	.global Route111_Text_DrewPostBattle
	.global Route111_Text_HeidiIntro
	.global Route111_Text_HeidiDefeat
	.global Route111_Text_HeidiPostBattle
	.global Route111_Text_BeauIntro
	.global Route111_Text_BeauDefeat
	.global Route111_Text_BeauPostBattle
	.global Route111_Text_BeckyIntro
	.global Route111_Text_BeckyDefeat
	.global Route111_Text_BeckyPostBattle
	.global Route111_Text_DustyIntro
	.global Route111_Text_DustyDefeat
	.global Route111_Text_DustyPostBattle
	.global Route111_Text_DustyRegister
	.global Route111_Text_DustyRematchIntro
	.global Route111_Text_DustyRematchDefeat
	.global Route111_Text_DustyPostRematch
	.global Route111_Text_TravisIntro
	.global Route111_Text_TravisDefeat
	.global Route111_Text_TravisPostBattle
	.global Route111_Text_IreneIntro
	.global Route111_Text_IreneDefeat
	.global Route111_Text_IrenePostBattle
	.global Route111_Text_DaisukeIntro
	.global Route111_Text_DaisukeDefeat
	.global Route111_Text_DaisukePostBattle
	.global Route111_Text_WiltonIntro
	.global Route111_Text_WiltonDefeat
	.global Route111_Text_WiltonPostBattle
	.global Route111_Text_WiltonRegister
	.global Route111_Text_WiltonRematchIntro
	.global Route111_Text_WiltonRematchDefeat
	.global Route111_Text_WiltonPostRematch
	.global Route111_Text_BrookeIntro
	.global Route111_Text_BrookeDefeat
	.global Route111_Text_BrookePostBattle
	.global Route111_Text_BrookeRegister
	.global Route111_Text_BrookeRematchIntro
	.global Route111_Text_BrookeRematchDefeat
	.global Route111_Text_BrookePostRematch
	.global Route111_Text_CeliaIntro
	.global Route111_Text_CeliaDefeat
	.global Route111_Text_CeliaPostBattle
	.global Route111_Text_BryanIntro
	.global Route111_Text_BryanDefeat
	.global Route111_Text_BryanPostBattle
	.global Route111_Text_BrandenIntro
	.global Route111_Text_BrandenDefeat
	.global Route111_Text_BrandenPostBattle
	.global Route111_Text_TyronIntro
	.global Route111_Text_TyronDefeat
	.global Route111_Text_TyronPostBattle
	.global Route111_Text_CelinaIntro
	.global Route111_Text_CelinaDefeat
	.global Route111_Text_CelinaPostBattle
	.global Route111_Text_HaydenIntro
	.global Route111_Text_HaydenDefeat
	.global Route111_Text_HaydenPostBattle
	.global Route111_Text_BiancaIntro
	.global Route111_Text_BiancaDefeat
	.global Route111_Text_BiancaPostBattle
	.global Route112_Text_BriceIntro
	.global Route112_Text_BriceDefeat
	.global Route112_Text_BricePostBattle
	.global Route112_Text_TrentIntro
	.global Route112_Text_TrentDefeat
	.global Route112_Text_TrentPostBattle
	.global Route112_Text_TrentRegister
	.global Route112_Text_TrentRematchIntro
	.global Route112_Text_TrentRematchDefeat
	.global Route112_Text_TrentRematchPostBattle
	.global Route112_Text_LarryIntro
	.global Route112_Text_LarryDefeat
	.global Route112_Text_LarryPostBattle
	.global Route112_Text_CarolIntro
	.global Route112_Text_CarolDefeat
	.global Route112_Text_CarolPostBattle
	.global Route112_Text_BryantIntro
	.global Route112_Text_BryantDefeat
	.global Route112_Text_BryantPostBattle
	.global Route112_Text_ShaylaIntro
	.global Route112_Text_ShaylaDefeat
	.global Route112_Text_ShaylaPostBattle
	.global Route113_Text_JaylenIntro
	.global Route113_Text_JaylenDefeat
	.global Route113_Text_JaylenPostBattle
	.global Route113_Text_DillonIntro
	.global Route113_Text_DillonDefeat
	.global Route113_Text_DillonPostBattle
	.global Route113_Text_MadelineIntro
	.global Route113_Text_MadelineDefeat
	.global Route113_Text_MadelinePostBattle
	.global Route113_Text_MadelineRegister
	.global Route113_Text_MadelineRematchIntro
	.global Route113_Text_MadelineRematchDefeat
	.global Route113_Text_MadelinePostRematch
	.global Route113_Text_LaoIntro
	.global Route113_Text_LaoDefeat
	.global Route113_Text_LaoPostBattle
	.global Route113_Text_LaoRegister
	.global Route113_Text_LaoRematchIntro
	.global Route113_Text_LaoRematchDefeat
	.global Route113_Text_LaoPostRematch
	.global Route113_Text_LungIntro
	.global Route113_Text_LungDefeat
	.global Route113_Text_LungPostBattle
	.global Route113_Text_ToriIntro
	.global Route113_Text_ToriDefeat
	.global Route113_Text_ToriPostBattle
	.global Route113_Text_ToriNotEnoughMons
	.global Route113_Text_TiaIntro
	.global Route113_Text_TiaDefeat
	.global Route113_Text_TiaPostBattle
	.global Route113_Text_TiaNotEnoughMons
	.global Route113_Text_CobyIntro
	.global Route113_Text_CobyDefeat
	.global Route113_Text_CobyPostBattle
	.global Route113_Text_SophieIntro
	.global Route113_Text_SophieDefeat
	.global Route113_Text_SophiePostBattle
	.global Route113_Text_LawrenceIntro
	.global Route113_Text_LawrenceDefeat
	.global Route113_Text_LawrencePostBattle
	.global Route113_Text_WyattIntro
	.global Route113_Text_WyattDefeat
	.global Route113_Text_WyattPostBattle
	.global Route114_Text_LennyIntro
	.global Route114_Text_LennyPostBattle
	.global Route114_Text_LucasIntro
	.global Route114_Text_LucasDefeat
	.global Route114_Text_LucasPostBattle
	.global Route114_Text_ShaneIntro
	.global Route114_Text_ShaneDefeat
	.global Route114_Text_ShanePostBattle
	.global Route114_Text_NancyIntro
	.global Route114_Text_NancyDefeat
	.global Route114_Text_NancyPostBattle
	.global Route114_Text_SteveIntro
	.global Route114_Text_SteveDefeat
	.global Route114_Text_StevePostBattle
	.global Route114_Text_SteveRegister
	.global Route114_Text_SteveRematchIntro
	.global Route114_Text_SteveRematchDefeat
	.global Route114_Text_StevePostRematch
	.global Route114_Text_BernieIntro
	.global Route114_Text_BernieDefeat
	.global Route114_Text_BerniePostBattle
	.global Route114_Text_BernieRegister
	.global Route114_Text_BernieRematchIntro
	.global Route114_Text_BernieRematchDefeat
	.global Route114_Text_BerniePostRematch
	.global Route114_Text_ClaudeIntro
	.global Route114_Text_ClaudeDefeat
	.global Route114_Text_ClaudePostBattle
	.global Route114_Text_NolanIntro
	.global Route114_Text_NolanDefeat
	.global Route114_Text_NolanPostBattle
	.global Route114_Text_TyraIntro
	.global Route114_Text_TyraDefeat
	.global Route114_Text_TyraPostBattle
	.global Route114_Text_TyraNotEnoughMons
	.global Route114_Text_IvyIntro
	.global Route114_Text_IvyDefeat
	.global Route114_Text_IvyPostBattle
	.global Route114_Text_IvyNotEnoughMons
	.global Route114_Text_KaiIntro
	.global Route114_Text_KaiDefeat
	.global Route114_Text_KaiPostBattle
	.global Route114_Text_CharlotteIntro
	.global Route114_Text_CharlotteDefeat
	.global Route114_Text_CharlottePostBattle
	.global Route114_Text_AngelinaIntro
	.global Route114_Text_AngelinaDefeat
	.global Route114_Text_AngelinaPostBattle
	.global Route115_Text_TimothyIntro
	.global Route115_Text_TimothyDefeat
	.global Route115_Text_TimothyPostBattle
	.global Route115_Text_TimothyRegister
	.global Route115_Text_TimothyRematchIntro
	.global Route115_Text_TimothyRematchDefeat
	.global Route115_Text_TimothyPostRematch
	.global Route115_Text_KoichiIntro
	.global Route115_Text_KoichiDefeat
	.global Route115_Text_KoichiPostBattle
	.global Route115_Text_NobIntro
	.global Route115_Text_NobDefeat
	.global Route115_Text_NobPostBattle
	.global Route115_Text_NobRegister
	.global Route115_Text_NobRematchIntro
	.global Route115_Text_NobRematchDefeat
	.global Route115_Text_NobPostRematch
	.global Route115_Text_CyndyIntro
	.global Route115_Text_CyndyDefeat
	.global Route115_Text_CyndyPostBattle
	.global Route115_Text_CyndyRegister
	.global Route115_Text_CyndyRematchIntro
	.global Route115_Text_CyndyRematchDefeat
	.global Route115_Text_CyndyPostRematch
	.global Route115_Text_HectorIntro
	.global Route115_Text_HectorDefeat
	.global Route115_Text_HectorPostBattle
	.global Route115_Text_KyraIntro
	.global Route115_Text_KyraDefeat
	.global Route115_Text_KyraPostBattle
	.global Route115_Text_JaidenIntro
	.global Route115_Text_JaidenDefeat
	.global Route115_Text_JaidenPostBattle
	.global Route115_Text_HeleneIntro
	.global Route115_Text_HeleneDefeat
	.global Route115_Text_HelenePostBattle
	.global Route115_Text_AlixIntro
	.global Route115_Text_AlixDefeat
	.global Route115_Text_AlixPostBattle
	.global Route115_Text_MarleneIntro
	.global Route115_Text_MarleneDefeat
	.global Route115_Text_MarlenePostBattle
	.global Route116_Text_ClarkIntro
	.global Route116_Text_ClarkDefeat
	.global Route116_Text_ClarkPostBattle
	.global Route116_Text_JoeyIntro
	.global Route116_Text_JoeyDefeat
	.global Route116_Text_JoeyPostBattle
	.global Route116_Text_JoseIntro
	.global Route116_Text_JoseDefeat
	.global Route116_Text_JosePostBattle
	.global Route116_Text_JaniceIntro
	.global Route116_Text_JaniceDefeat
	.global Route116_Text_JanicePostBattle
	.global Route116_Text_JerryIntro
	.global Route116_Text_JerryDefeat
	.global Route116_Text_JerryPostBattle
	.global Route116_Text_JerryRegister1
	.global Route116_Text_JerryRegister2
	.global Route116_Text_JerryRematchIntro
	.global Route116_Text_JerryRematchDefeat
	.global Route116_Text_JerryPostRematch
	.global Route116_Text_KarenIntro
	.global Route116_Text_KarenDefeat
	.global Route116_Text_KarenPostBattle
	.global Route116_Text_KarenRegister1
	.global Route116_Text_KarenRegister2
	.global Route116_Text_KarenRematchIntro
	.global Route116_Text_KarenRematchDefeat
	.global Route116_Text_KarenPostRematch
	.global Route116_Text_SarahIntro
	.global Route116_Text_SarahDefeat
	.global Route116_Text_SarahPostBattle
	.global Route116_Text_DawsonIntro
	.global Route116_Text_DawsonDefeat
	.global Route116_Text_DawsonPostBattle
	.global Route116_Text_DevanIntro
	.global Route116_Text_DevanDefeat
	.global Route116_Text_DevanPostBattle
	.global Route116_Text_JohnsonIntro
	.global Route116_Text_JohnsonDefeat
	.global Route116_Text_JohnsonPostBattle
	.global Route117_Text_IsaacIntro
	.global Route117_Text_IsaacDefeat
	.global Route117_Text_IsaacPostBattle
	.global Route117_Text_IsaacRegister
	.global Route117_Text_IsaacRematchIntro
	.global Route117_Text_IsaacRematchDefeat
	.global Route117_Text_IsaacPostRematch
	.global Route117_Text_LydiaIntro
	.global Route117_Text_LydiaDefeat
	.global Route117_Text_LydiaPostBattle
	.global Route117_Text_LydiaRegister
	.global Route117_Text_LydiaRematchIntro
	.global Route117_Text_LydiaRematchDefeat
	.global Route117_Text_LydiaPostRematch
	.global Route117_Text_DylanIntro
	.global Route117_Text_DylanDefeat
	.global Route117_Text_DylanPostBattle
	.global Route117_Text_DylanRegister
	.global Route117_Text_DylanRematchIntro
	.global Route117_Text_DylanRematchDefeat
	.global Route117_Text_DylanPostRematch
	.global Route117_Text_MariaIntro
	.global Route117_Text_MariaDefeat
	.global Route117_Text_MariaPostBattle
	.global Route117_Text_MariaRegister
	.global Route117_Text_MariaRematchIntro
	.global Route117_Text_MariaRematchDefeat
	.global Route117_Text_MariaPostRematch
	.global Route117_Text_DerekIntro
	.global Route117_Text_DerekDefeat
	.global Route117_Text_DerekPostBattle
	.global Route117_Text_AnnaIntro
	.global Route117_Text_AnnaDefeat
	.global Route117_Text_AnnaPostBattle
	.global Route117_Text_AnnaAndMegRegister
	.global Route117_Text_AnnaNotEnoughMons
	.global Route117_Text_MegIntro
	.global Route117_Text_MegDefeat
	.global Route117_Text_MegPostBattle
	.global Route117_Text_MegNotEnoughMons
	.global Route117_Text_AnnaRematchIntro
	.global Route117_Text_AnnaRematchDefeat
	.global Route117_Text_AnnaPostRematch
	.global Route117_Text_AnnaRematchNotEnoughMons
	.global Route117_Text_MegRematchIntro
	.global Route117_Text_MegRematchDefeat
	.global Route117_Text_MegPostRematch
	.global Route117_Text_MegRematchNotEnoughMons
	.global Route117_Text_MelinaIntro
	.global Route117_Text_MelinaDefeat
	.global Route117_Text_MelinaPostBattle
	.global Route117_Text_BrandiIntro
	.global Route117_Text_BrandiDefeat
	.global Route117_Text_BrandiPostBattle
	.global Route117_Text_AishaIntro
	.global Route117_Text_AishaDefeat
	.global Route117_Text_AishaPostBattle
	.global Route118_Text_RoseIntro
	.global Route118_Text_RoseDefeat
	.global Route118_Text_RosePostBattle
	.global Route118_Text_RoseRegister
	.global Route118_Text_RoseRematchIntro
	.global Route118_Text_RoseRematchDefeat
	.global Route118_Text_RosePostRematch
	.global Route118_Text_PerryIntro
	.global Route118_Text_PerryDefeat
	.global Route118_Text_PerryPostBattle
	.global Route118_Text_ChesterIntro
	.global Route118_Text_ChesterDefeat
	.global Route118_Text_ChesterPostBattle
	.global Route118_Text_BarnyIntro
	.global Route118_Text_BarnyDefeat
	.global Route118_Text_BarnyPostBattle
	.global Route118_Text_WadeIntro
	.global Route118_Text_WadeDefeat
	.global Route118_Text_WadePostBattle
	.global Route118_Text_DaltonIntro
	.global Route118_Text_DaltonDefeat
	.global Route118_Text_DaltonPostBattle
	.global Route118_Text_DaltonRegister
	.global Route118_Text_DaltonRematchIntro
	.global Route118_Text_DaltonRematchDefeat
	.global Route118_Text_DaltonPostRematch
	.global Route118_Text_DeandreIntro
	.global Route118_Text_DeandreDefeat
	.global Route118_Text_DeandrePostBattle
	.global Route119_Text_BrentIntro
	.global Route119_Text_BrentDefeat
	.global Route119_Text_BrentPostBattle
	.global Route119_Text_DonaldIntro
	.global Route119_Text_DonaldDefeat
	.global Route119_Text_DonaldPostBattle
	.global Route119_Text_TaylorIntro
	.global Route119_Text_TaylorDefeat
	.global Route119_Text_TaylorPostBattle
	.global Route119_Text_DougIntro
	.global Route119_Text_DougDefeat
	.global Route119_Text_DougPostBattle
	.global Route119_Text_GregIntro
	.global Route119_Text_GregDefeat
	.global Route119_Text_GregPostBattle
	.global Route119_Text_KentIntro
	.global Route119_Text_KentDefeat
	.global Route119_Text_KentPostBattle
	.global Route119_Text_JacksonIntro
	.global Route119_Text_JacksonDefeat
	.global Route119_Text_JacksonPostBattle
	.global Route119_Text_JacksonRegister
	.global Route119_Text_JacksonRematchIntro
	.global Route119_Text_JacksonRematchDefeat
	.global Route119_Text_JacksonPostRematch
	.global Route119_Text_CatherineIntro
	.global Route119_Text_CatherineDefeat
	.global Route119_Text_CatherinePostBattle
	.global Route119_Text_CatherineRegister
	.global Route119_Text_CatherineRematchIntro
	.global Route119_Text_CatherineRematchDefeat
	.global Route119_Text_CatherinePostRematch
	.global Route119_Text_HughIntro
	.global Route119_Text_HughDefeat
	.global Route119_Text_HughPostBattle
	.global Route119_Text_PhilIntro
	.global Route119_Text_PhilDefeat
	.global Route119_Text_PhilPostBattle
	.global Route119_Text_YasuIntro
	.global Route119_Text_YasuDefeat
	.global Route119_Text_YasuPostBattle
	.global Route119_Text_TakashiIntro
	.global Route119_Text_TakashiDefeat
	.global Route119_Text_TakashiPostBattle
	.global Route119_Text_HideoIntro
	.global Route119_Text_HideoDefeat
	.global Route119_Text_HideoPostBattle
	.global Route119_Text_ChrisIntro
	.global Route119_Text_ChrisDefeat
	.global Route119_Text_ChrisPostBattle
	.global Route119_Text_FabianIntro
	.global Route119_Text_FabianDefeat
	.global Route119_Text_FabianPostBattle
	.global Route119_Text_DaytonIntro
	.global Route119_Text_DaytonDefeat
	.global Route119_Text_DaytonPostBattle
	.global Route119_Text_RachelIntro
	.global Route119_Text_RachelDefeat
	.global Route119_Text_RachelPostBattle
	.global Route120_Text_ColinIntro
	.global Route120_Text_ColinDefeat
	.global Route120_Text_ColinPostBattle
	.global Route120_Text_RobertIntro
	.global Route120_Text_RobertDefeat
	.global Route120_Text_RobertPostBattle
	.global Route120_Text_RobertRegister
	.global Route120_Text_RobertRematchIntro
	.global Route120_Text_RobertRematchDefeat
	.global Route120_Text_RobertPostRematch
	.global Route120_Text_LorenzoIntro
	.global Route120_Text_LorenzoDefeat
	.global Route120_Text_LorenzoPostBattle
	.global Route120_Text_JennaIntro
	.global Route120_Text_JennaDefeat
	.global Route120_Text_JennaPostBattle
	.global Route120_Text_JeffreyIntro
	.global Route120_Text_JeffreyDefeat
	.global Route120_Text_JeffreyPostBattle
	.global Route120_Text_JeffreyRegister
	.global Route120_Text_JeffreyRematchIntro
	.global Route120_Text_JeffreyRematchDefeat
	.global Route120_Text_JeffreyPostRematch
	.global Route120_Text_JenniferIntro
	.global Route120_Text_JenniferDefeat
	.global Route120_Text_JenniferPostBattle
	.global Route120_Text_ChipIntro
	.global Route120_Text_ChipDefeat
	.global Route120_Text_ChipPostBattle
	.global Route120_Text_ClarissaIntro
	.global Route120_Text_ClarissaDefeat
	.global Route120_Text_ClarissaPostBattle
	.global Route120_Text_AngelicaIntro
	.global Route120_Text_AngelicaDefeat
	.global Route120_Text_AngelicaPostBattle
	.global Route120_Text_KeigoIntro
	.global Route120_Text_KeigoDefeat
	.global Route120_Text_KeigoPostBattle
	.global Route120_Text_RileyIntro
	.global Route120_Text_RileyDefeat
	.global Route120_Text_RileyPostBattle
	.global Route120_Text_CallieIntro
	.global Route120_Text_CallieDefeat
	.global Route120_Text_CalliePostBattle
	.global Route120_Text_LeonelIntro
	.global Route120_Text_LeonelDefeat
	.global Route120_Text_LeonelPostBattle
	.global Route121_Text_VanessaIntro
	.global Route121_Text_VanessaDefeat
	.global Route121_Text_VanessaPostBattle
	.global Route121_Text_WalterIntro
	.global Route121_Text_WalterDefeat
	.global Route121_Text_WalterPostBattle
	.global Route121_Text_WalterRegister
	.global Route121_Text_WalterRematchIntro
	.global Route121_Text_WalterRematchDefeat
	.global Route121_Text_WalterPostRematch
	.global Route121_Text_TammyIntro
	.global Route121_Text_TammyDefeat
	.global Route121_Text_TammyPostBattle
	.global Route121_Text_KateIntro
	.global Route121_Text_KateDefeat
	.global Route121_Text_KatePostBattle
	.global Route121_Text_KateNotEnoughMons
	.global Route121_Text_JoyIntro
	.global Route121_Text_JoyDefeat
	.global Route121_Text_JoyPostBattle
	.global Route121_Text_JoyNotEnoughMons
	.global Route121_Text_JessicaIntro
	.global Route121_Text_JessicaDefeat
	.global Route121_Text_JessicaPostBattle
	.global Route121_Text_JessicaRegister
	.global Route121_Text_JessicaRematchIntro
	.global Route121_Text_JessicaRematchDefeat
	.global Route121_Text_JessicaPostRematch
	.global Route121_Text_CristinIntro
	.global Route121_Text_CristinDefeat
	.global Route121_Text_CristinPostBattle
	.global Route121_Text_CristinRegister
	.global Route121_Text_CristinRematchIntro
	.global Route121_Text_CristinRematchDefeat
	.global Route121_Text_CristinPostRematch
	.global Route121_Text_CaleIntro
	.global Route121_Text_CaleDefeat
	.global Route121_Text_CalePostBattle
	.global Route121_Text_MylesIntro
	.global Route121_Text_MylesDefeat
	.global Route121_Text_MylesPostBattle
	.global Route121_Text_PatIntro
	.global Route121_Text_PatDefeat
	.global Route121_Text_PatPostBattle
	.global Route121_Text_MarcelIntro
	.global Route121_Text_MarcelDefeat
	.global Route121_Text_MarcelPostBattle
	.global Route123_Text_WendyIntro
	.global Route123_Text_WendyDefeat
	.global Route123_Text_WendyPostBattle
	.global Route123_Text_BraxtonIntro
	.global Route123_Text_BraxtonDefeat
	.global Route123_Text_BraxtonPostBattle
	.global Route123_Text_VioletIntro
	.global Route123_Text_VioletDefeat
	.global Route123_Text_VioletPostBattle
	.global Route123_Text_CameronIntro
	.global Route123_Text_CameronDefeat
	.global Route123_Text_CameronPostBattle
	.global Route123_Text_CameronRegister
	.global Route123_Text_CameronRematchIntro
	.global Route123_Text_CameronRematchDefeat
	.global Route123_Text_CameronPostRematch
	.global Route123_Text_JackiIntro
	.global Route123_Text_JackiDefeat
	.global Route123_Text_JackiPostBattle
	.global Route123_Text_JackiRegister
	.global Route123_Text_JackiRematchIntro
	.global Route123_Text_JackiRematchDefeat
	.global Route123_Text_JackiPostRematch
	.global Route123_Text_MiuIntro
	.global Route123_Text_MiuDefeat
	.global Route123_Text_MiuPostBattle
	.global Route123_Text_MiuNotEnoughMons
	.global Route123_Text_YukiIntro
	.global Route123_Text_YukiDefeat
	.global Route123_Text_YukiPostBattle
	.global Route123_Text_YukiNotEnoughMons
	.global Route123_Text_KindraIntro
	.global Route123_Text_KindraDefeat
	.global Route123_Text_KindraPostBattle
	.global Route123_Text_FernandoIntro
	.global Route123_Text_FernandoDefeat
	.global Route123_Text_FernandoPostBattle
	.global Route123_Text_FernandoRegister
	.global Route123_Text_FernandoRematchIntro
	.global Route123_Text_FernandoRematchDefeat
	.global Route123_Text_FernandoPostRematch
	.global Route123_Text_DavisIntro
	.global Route123_Text_DavisDefeat
	.global Route123_Text_DavisPostBattle
	.global Route123_Text_JazmynIntro
	.global Route123_Text_JazmynDefeat
	.global Route123_Text_JazmynPostBattle
	.global Route123_Text_FrederickIntro
	.global Route123_Text_FrederickDefeat
	.global Route123_Text_FrederickPostBattle
	.global Route123_Text_AlbertoIntro
	.global Route123_Text_AlbertoDefeat
	.global Route123_Text_AlbertoPostBattle
	.global Route123_Text_EdIntro
	.global Route123_Text_EdDefeat
	.global Route123_Text_EdPostBattle
	.global Route123_Text_JonasIntro
	.global Route123_Text_JonasDefeat
	.global Route123_Text_JonasPostBattle
	.global Route123_Text_KayleyIntro
	.global Route123_Text_KayleyDefeat
	.global Route123_Text_KayleyPostBattle
	.global Route124_Text_SpencerIntro
	.global Route124_Text_SpencerDefeat
	.global Route124_Text_SpencerPostBattle
	.global Route124_Text_RolandIntro
	.global Route124_Text_RolandDefeat
	.global Route124_Text_RolandPostBattle
	.global Route124_Text_JennyIntro
	.global Route124_Text_JennyDefeat
	.global Route124_Text_JennyPostBattle
	.global Route124_Text_JennyRegister
	.global Route124_Text_JennyRematchIntro
	.global Route124_Text_JennyRematchDefeat
	.global Route124_Text_JennyPostRematch
	.global Route124_Text_GraceIntro
	.global Route124_Text_GraceDefeat
	.global Route124_Text_GracePostBattle
	.global Route124_Text_ChadIntro
	.global Route124_Text_ChadDefeat
	.global Route124_Text_ChadPostBattle
	.global Route124_Text_LilaIntro
	.global Route124_Text_LilaDefeat
	.global Route124_Text_LilaPostBattle
	.global Route124_Text_LilaNotEnoughMons
	.global Route124_Text_RoyIntro
	.global Route124_Text_RoyDefeat
	.global Route124_Text_RoyPostBattle
	.global Route124_Text_LilaRoyRegister
	.global Route124_Text_RoyNotEnoughMons
	.global Route124_Text_LilaRematchIntro
	.global Route124_Text_LilaRematchDefeat
	.global Route124_Text_LilaPostRematch
	.global Route124_Text_LilaRematchNotEnoughMons
	.global Route124_Text_RoyRematchIntro
	.global Route124_Text_RoyRematchDefeat
	.global Route124_Text_RoyPostRematch
	.global Route124_Text_RoyRematchNotEnoughMons
	.global Route124_Text_DeclanIntro
	.global Route124_Text_DeclanDefeat
	.global Route124_Text_DeclanPostBattle
	.global Route124_Text_IsabellaIntro
	.global Route124_Text_IsabellaDefeat
	.global Route124_Text_IsabellaPostBattle
	.global Route125_Text_NolenIntro
	.global Route125_Text_NolenDefeat
	.global Route125_Text_NolenPostBattle
	.global Route125_Text_StanIntro
	.global Route125_Text_StanDefeat
	.global Route125_Text_StanPostBattle
	.global Route125_Text_TanyaIntro
	.global Route125_Text_TanyaDefeat
	.global Route125_Text_TanyaPostBattle
	.global Route125_Text_SharonIntro
	.global Route125_Text_SharonDefeat
	.global Route125_Text_SharonPostBattle
	.global Route125_Text_ErnestIntro
	.global Route125_Text_ErnestDefeat
	.global Route125_Text_ErnestPostBattle
	.global Route125_Text_ErnestRegister
	.global Route125_Text_ErnestRematchIntro
	.global Route125_Text_ErnestRematchDefeat
	.global Route125_Text_ErnestRematchPostBattle
	.global Route125_Text_KimIntro
	.global Route125_Text_KimDefeat
	.global Route125_Text_KimPostBattle
	.global Route125_Text_KimNotEnoughMons
	.global Route125_Text_IrisIntro
	.global Route125_Text_IrisDefeat
	.global Route125_Text_IrisPostBattle
	.global Route125_Text_IrisNotEnoughMons
	.global Route125_Text_PresleyIntro
	.global Route125_Text_PresleyDefeat
	.global Route125_Text_PresleyPostBattle
	.global Route125_Text_AuronIntro
	.global Route125_Text_AuronDefeat
	.global Route125_Text_AuronPostBattle
	.global Route126_Text_BarryIntro
	.global Route126_Text_BarryDefeat
	.global Route126_Text_BarryPostBattle
	.global Route126_Text_DeanIntro
	.global Route126_Text_DeanDefeat
	.global Route126_Text_DeanPostBattle
	.global Route126_Text_NikkiIntro
	.global Route126_Text_NikkiDefeat
	.global Route126_Text_NikkiPostBattle
	.global Route126_Text_BrendaIntro
	.global Route126_Text_BrendaDefeat
	.global Route126_Text_BrendaPostBattle
	.global Route126_Text_PabloIntro
	.global Route126_Text_PabloDefeat
	.global Route126_Text_PabloPostBattle
	.global Route126_Text_PabloRegister
	.global Route126_Text_PabloRematchIntro
	.global Route126_Text_PabloRematchDefeat
	.global Route126_Text_PabloPostRematch
	.global Route126_Text_LeonardoIntro
	.global Route126_Text_LeonardoDefeat
	.global Route126_Text_LeonardoPostBattle
	.global Route126_Text_IsobelIntro
	.global Route126_Text_IsobelDefeat
	.global Route126_Text_IsobelPostBattle
	.global Route126_Text_SiennaIntro
	.global Route126_Text_SiennaDefeat
	.global Route126_Text_SiennaPostBattle
	.global Route127_Text_CamdenIntro
	.global Route127_Text_CamdenDefeat
	.global Route127_Text_CamdenPostBattle
	.global Route127_Text_DonnyIntro
	.global Route127_Text_DonnyDefeat
	.global Route127_Text_DonnyPostBattle
	.global Route127_Text_JonahIntro
	.global Route127_Text_JonahDefeat
	.global Route127_Text_JonahPostBattle
	.global Route127_Text_HenryIntro
	.global Route127_Text_HenryDefeat
	.global Route127_Text_HenryPostBattle
	.global Route127_Text_RogerIntro
	.global Route127_Text_RogerDefeat
	.global Route127_Text_RogerPostBattle
	.global Route127_Text_AidanIntro
	.global Route127_Text_AidanDefeat
	.global Route127_Text_AidanPostBattle
	.global Route127_Text_KojiIntro
	.global Route127_Text_KojiDefeat
	.global Route127_Text_KojiPostBattle
	.global Route127_Text_KojiRegister
	.global Route127_Text_KojiRematchIntro
	.global Route127_Text_KojiRematchDefeat
	.global Route127_Text_KojiPostRematch
	.global Route127_Text_AthenaIntro
	.global Route127_Text_AthenaDefeat
	.global Route127_Text_AthenaPostBattle
	.global Route128_Text_IsaiahIntro
	.global Route128_Text_IsaiahDefeat
	.global Route128_Text_IsaiahPostBattle
	.global Route128_Text_IsaiahRegister
	.global Route128_Text_IsaiahRematchIntro
	.global Route128_Text_IsaiahRematchDefeat
	.global Route128_Text_IsaiahPostRematch
	.global Route128_Text_KatelynIntro
	.global Route128_Text_KatelynDefeat
	.global Route128_Text_KatelynPostBattle
	.global Route128_Text_KatelynRegister
	.global Route128_Text_KatelynRematchIntro
	.global Route128_Text_KatelynRematchDefeat
	.global Route128_Text_KatelynPostRematch
	.global Route128_Text_AlexaIntro
	.global Route128_Text_AlexaDefeat
	.global Route128_Text_AlexaPostBattle
	.global Route128_Text_RubenIntro
	.global Route128_Text_RubenDefeat
	.global Route128_Text_RubenPostBattle
	.global Route128_Text_WayneIntro
	.global Route128_Text_WayneDefeat
	.global Route128_Text_WaynePostBattle
	.global Route128_Text_HarrisonIntro
	.global Route128_Text_HarrisonDefeat
	.global Route128_Text_HarrisonPostBattle
	.global Route128_Text_CarleeIntro
	.global Route128_Text_CarleeDefeat
	.global Route128_Text_CarleePostBattle
	.global Route129_Text_ChaseIntro
	.global Route129_Text_ChaseDefeat
	.global Route129_Text_ChasePostBattle
	.global Route129_Text_AllisonIntro
	.global Route129_Text_AllisonDefeat
	.global Route129_Text_AllisonPostBattle
	.global Route129_Text_ReedIntro
	.global Route129_Text_ReedDefeat
	.global Route129_Text_ReedPostBattle
	.global Route129_Text_TishaIntro
	.global Route129_Text_TishaDefeat
	.global Route129_Text_TishaPostBattle
	.global Route129_Text_ClarenceIntro
	.global Route129_Text_ClarenceDefeat
	.global Route129_Text_ClarencePostBattle
	.global Route130_Text_RodneyIntro
	.global Route130_Text_RodneyDefeat
	.global Route130_Text_RodneyPostBattle
	.global Route130_Text_KatieIntro
	.global Route130_Text_KatieDefeat
	.global Route130_Text_KatiePostBattle
	.global Route130_Text_SantiagoIntro
	.global Route130_Text_SantiagoDefeat
	.global Route130_Text_SantiagoPostBattle
	.global Route131_Text_RichardIntro
	.global Route131_Text_RichardDefeat
	.global Route131_Text_RichardPostBattle
	.global Route131_Text_HermanIntro
	.global Route131_Text_HermanDefeat
	.global Route131_Text_HermanPostBattle
	.global Route131_Text_SusieIntro
	.global Route131_Text_SusieDefeat
	.global Route131_Text_SusiePostBattle
	.global Route131_Text_KaraIntro
	.global Route131_Text_KaraDefeat
	.global Route131_Text_KaraPostBattle
	.global Route131_Text_ReliIntro
	.global Route131_Text_ReliDefeat
	.global Route131_Text_ReliPostBattle
	.global Route131_Text_ReliNotEnoughMons
	.global Route131_Text_IanIntro
	.global Route131_Text_IanDefeat
	.global Route131_Text_IanPostBattle
	.global Route131_Text_IanNotEnoughMons
	.global Route131_Text_TaliaIntro
	.global Route131_Text_TaliaDefeat
	.global Route131_Text_TaliaPostBattle
	.global Route131_Text_KevinIntro
	.global Route131_Text_KevinDefeat
	.global Route131_Text_KevinPostBattle
	.global Route132_Text_GilbertIntro
	.global Route132_Text_GilbertDefeat
	.global Route132_Text_GilbertPostBattle
	.global Route132_Text_DanaIntro
	.global Route132_Text_DanaDefeat
	.global Route132_Text_DanaPostBattle
	.global Route132_Text_RonaldIntro
	.global Route132_Text_RonaldDefeat
	.global Route132_Text_RonaldPostBattle
	.global Route132_Text_KiyoIntro
	.global Route132_Text_KiyoDefeat
	.global Route132_Text_KiyoPostBattle
	.global Route132_Text_MakaylaIntro
	.global Route132_Text_MakaylaDefeat
	.global Route132_Text_MakaylaPostBattle
	.global Route132_Text_JonathanIntro
	.global Route132_Text_JonathanDefeat
	.global Route132_Text_JonathanPostBattle
	.global Route132_Text_PaxtonIntro
	.global Route132_Text_PaxtonDefeat
	.global Route132_Text_PaxtonPostBattle
	.global Route132_Text_DarcyIntro
	.global Route132_Text_DarcyDefeat
	.global Route132_Text_DarcyPostBattle
	.global Route133_Text_FranklinIntro
	.global Route133_Text_FranklinDefeat
	.global Route133_Text_FranklinPostBattle
	.global Route133_Text_DebraIntro
	.global Route133_Text_DebraDefeat
	.global Route133_Text_DebraPostBattle
	.global Route133_Text_LindaIntro
	.global Route133_Text_LindaDefeat
	.global Route133_Text_LindaPostBattle
	.global Route133_Text_WarrenIntro
	.global Route133_Text_WarrenDefeat
	.global Route133_Text_WarrenPostBattle
	.global Route133_Text_BeckIntro
	.global Route133_Text_BeckDefeat
	.global Route133_Text_BeckPostBattle
	.global Route133_Text_MollieIntro
	.global Route133_Text_MollieDefeat
	.global Route133_Text_MolliePostBattle
	.global Route133_Text_ConorIntro
	.global Route133_Text_ConorDefeat
	.global Route133_Text_ConorPostBattle
	.global Route134_Text_JackIntro
	.global Route134_Text_JackDefeat
	.global Route134_Text_JackPostBattle
	.global Route134_Text_LaurelIntro
	.global Route134_Text_LaurelDefeat
	.global Route134_Text_LaurelPostBattle
	.global Route134_Text_AlexIntro
	.global Route134_Text_AlexDefeat
	.global Route134_Text_AlexPostBattle
	.global Route134_Text_HitoshiIntro
	.global Route134_Text_HitoshiDefeat
	.global Route134_Text_HitoshiPostBattle
	.global Route134_Text_AaronIntro
	.global Route134_Text_AaronDefeat
	.global Route134_Text_AaronPostBattle
	.global Route134_Text_KelvinIntro
	.global Route134_Text_KelvinDefeat
	.global Route134_Text_KelvinPostBattle
	.global Route134_Text_MarleyIntro
	.global Route134_Text_MarleyDefeat
	.global Route134_Text_MarleyPostBattle
	.global Route134_Text_ReynaIntro
	.global Route134_Text_ReynaDefeat
	.global Route134_Text_ReynaPostBattle
	.global Route134_Text_HudsonIntro
	.global Route134_Text_HudsonDefeat
	.global Route134_Text_HudsonPostBattle
@ END GENERATED LOCALIZATION EXPORTS
