LilycoveCity_ContestLobby_Text_InterviewRequest:
	.string "Ồ, xin chào! Bạn vừa tham gia một\n"
	.string "POKéMON CONTEST, đúng không? Nhìn\l"
	.string "POKéMON của bạn là biết ngay.\p"
	.string "Tôi là phóng viên. Tôi đang làm một\n"
	.string "phóng sự về POKéMON CONTESTS.\p"
	.string "Nếu được, bạn có thể trả lời vài câu hỏi\n"
	.string "không?$"

LilycoveCity_ContestLobby_Text_DescribeContest:
	.string "Ồ, bạn đồng ý sao? Cảm ơn nhé.\p"
	.string "Nói ngắn gọn, bạn sẽ miêu tả cuộc thi\n"
	.string "vừa tham gia như thế nào?$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX:
	.string "À, tôi hiểu rồi. Một nhận xét rất bổ ích.\p"
	.string "Qua đó có thể cảm nhận khá rõ cuộc thi\n"
	.string "đã diễn ra thế nào.\p"
	.string "Tôi còn một câu hỏi cuối cùng.\p"
	.string "Khi nghe từ “{STR_VAR_2}”, bạn\n"
	.string "hình dung ra điều gì?$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview:
	.string "Tôi hiểu rồi!\p"
	.string "Vậy đó là cách bạn hình dung khái niệm\n"
	.string "“{STR_VAR_2}”.\p"
	.string "Cảm ơn bạn! Bạn đã cho tôi vài ý tưởng\n"
	.string "rất hay.\p"
	.string "Giờ tôi nghĩ mình có thể viết một phóng\n"
	.string "sự hay về POKéMON CONTESTS.\p"
	.string "Biết đâu phóng sự này còn được phát\n"
	.string "trên truyền hình. Hãy đón xem nhé!$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe:
	.string "Ồ, tiếc quá...\p"
	.string "Nếu bắt gặp câu chuyện nào hay, hãy kể\n"
	.string "cho tôi nghe nhé.$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest:
	.string "Tôi rất mong chờ POKéMON CONTEST tiếp\n"
	.string "theo của bạn.$"

gTVBravoTrainerText00::
	.string "Đúng rồi! Đến giờ BRAVO TRAINER rồi!\p"
	.string "Hôm nay, chúng ta sẽ giới thiệu một\n"
	.string "POKéMON của {STR_VAR_1}.\p"
	.string "POKéMON này đạt hạng\n"
	.string "{STR_VAR_3} trong hạng mục\l"
	.string "{STR_VAR_2}.$"

gTVBravoTrainerText01::
	.string "Xin giới thiệu {STR_VAR_2}, một\n"
	.string "{STR_VAR_1}!\p"
	.string "Biệt danh {STR_VAR_2}...\p"
	.string "Ngay cả biệt danh ấy cũng toát lên khí\n"
	.string "chất như đang tuyên bố\l"
	.string "“{STR_VAR_3}”!$"

gTVBravoTrainerText02::
	.string "Dù sao, khi HLV {STR_VAR_1}\n"
	.string "đưa POKéMON này dự cuộc thi, chúng tôi\l"
	.string "đã ghi lại được vài lời đầy nhiệt huyết\l"
	.string "về người bạn đồng hành đáng tin cậy\l"
	.string "ấy.$"

gTVBravoTrainerText03::
	.string "Khi được hỏi về cuộc thi sau đó,\n"
	.string "{STR_VAR_1} nở nụ cười thật\l"
	.string "tươi và vui vẻ đáp:\l"
	.string "“{STR_VAR_2}!”\p"
	.string "Quả thật, POKéMON của\n"
	.string "{STR_VAR_1} đã xếp thứ\l"
	.string "{STR_VAR_3} trong cuộc thi.\p"
	.string "Tôi thấy câu nói ấy lúc này hợp với\n"
	.string "{STR_VAR_1} vô cùng!$"

gTVBravoTrainerText04::
	.string "Khi được hỏi về cuộc thi sau đó,\n"
	.string "{STR_VAR_1} hơi cay đắng đáp:\l"
	.string "“{STR_VAR_2}.”\p"
	.string "Quả thật, POKéMON của\n"
	.string "{STR_VAR_1} đã xếp thứ\l"
	.string "{STR_VAR_3} trong cuộc thi.\p"
	.string "Có thể cảm nhận rõ sự thất vọng của\n"
	.string "{STR_VAR_1}!$"

gTVBravoTrainerText05::
	.string "Hẳn bạn cũng muốn biết\n"
	.string "{STR_VAR_1} hình dung\l"
	.string "{STR_VAR_2} là gì, đúng không?\p"
	.string "Chắc chắn rồi! Vì thế, tất nhiên chúng\n"
	.string "tôi đã hỏi!\p"
	.string "Câu trả lời được gói gọn hoàn hảo\n"
	.string "trong: “{STR_VAR_3}!”\p"
	.string "Đối với {STR_VAR_1}, khái niệm\n"
	.string "{STR_VAR_2} chính là như vậy!$"

gTVBravoTrainerText06::
	.string "Chiêu cuối cùng, {STR_VAR_2}, mà\n"
	.string "{STR_VAR_1} sử dụng hoàn toàn\l"
	.string "thể hiện “{STR_VAR_3}”!$"

gTVBravoTrainerText07::
	.string "Hoan hô, {STR_VAR_1}! Hoan hô,\n"
	.string "{STR_VAR_2}!\p"
	.string "Hy vọng chúng ta sẽ được thấy\n"
	.string "{STR_VAR_1} vươn tới những tầm\l"
	.string "cao hơn nữa!\p"
	.string "Chương trình đến đây là hết! Hẹn gặp\n"
	.string "lại lần sau!$"

gTVBravoTrainerText08::
	.string "Xin giới thiệu {STR_VAR_1} của\n"
	.string "HLV!$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "Xin chào! Bạn là HLV vừa đấu trận\n"
	.string "xong, đúng không?\p"
	.string "Tôi đang phỏng vấn HLV ở khắp mọi\n"
	.string "nơi.\p"
	.string "Tôi có thể xin bạn vài lời về cảm nhận\n"
	.string "sau trận đấu không?$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "Bạn đồng ý sao? Thật chứ? Cảm ơn bạn!\n"
	.string "Vậy thì, ừm...\p"
	.string "Hôm nay ở BATTLE TOWER, kết quả thế\n"
	.string "nào?\p"
	.string "Bạn hài lòng với trận đấu chứ? Hay bạn\n"
	.string "thấy không vui?$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "Ồ... Xin lỗi vì đã làm phiền bạn.\p"
	.string "Lần tới khi đến BATTLE TOWER, hãy cho\n"
	.string "chúng tôi phỏng vấn nhé.$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "Quả nhiên!\p"
	.string "Vẻ mãn nguyện hiện rõ trên khuôn mặt\n"
	.string "bạn...\p"
	.string "Rõ ràng bạn vừa có một trận đấu tuyệt\n"
	.string "vời.$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "Ồ, tôi hiểu...\p"
	.string "Quả thật, rất khó để trận đấu diễn ra\n"
	.string "đúng như kế hoạch.$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "Ồ, tôi có thể hỏi thêm một câu nữa\n"
	.string "không?\p"
	.string "Nếu gói gọn cảm nhận về trận đấu này\n"
	.string "trong một câu, bạn sẽ nói gì?$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "Ôi, ngầu không tưởng!\p"
	.string "Đúng là một câu tuyệt vời! Hy vọng lần\n"
	.string "tới bạn cũng sẽ thi đấu thật tốt.\p"
	.string "Mong sớm gặp lại bạn!$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "Ồ, tôi hiểu...\p"
	.string "Nhưng kiểu người ít nói cũng rất ngầu,\n"
	.string "đúng không?\p"
	.string "Hy vọng bạn sẽ lại cho tôi cơ hội được\n"
	.string "nghe những suy nghĩ của bạn!$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "Tôi rất mong chờ trận đấu tiếp theo của\n"
	.string "bạn!$"

BravoTrainerBattleTower_Text_Intro::
	.string "Vâng! Đã đến giờ BRAVO TRAINER!\p"
	.string "Hôm nay, chúng ta sẽ giới thiệu\n"
	.string "{STR_VAR_1}, người đã tham gia\l"
	.string "thử thách BATTLE TOWER!\p"
	.string "Trong thử thách này, {STR_VAR_1}\n"
	.string "đã đưa một {STR_VAR_2} cực kỳ\l"
	.string "lợi hại vào thi đấu.$"

BravoTrainerBattleTower_Text_NewRecord::
	.string "Cặp đôi đã lập kỷ lục mới với\n"
	.string "{STR_VAR_2} trận thắng liên tiếp\l"
	.string "trong hạng đấu {STR_VAR_1}! Hoan\l"
	.string "hô, HLV!$"

BravoTrainerBattleTower_Text_Lost::
	.string "Cặp đôi cuối cùng đã để thua\n"
	.string "{STR_VAR_1} ở trận thứ\l"
	.string "{STR_VAR_2}. Nỗ lực đáng khen,\l"
	.string "HLV!\p"
	.string "Nhưng mà, gặp phải {STR_VAR_1}\n"
	.string "quá sớm trong thử thách chỉ là do\l"
	.string "không may thôi.\p"
	.string "Chúng tôi đã hỏi HLV về cảm nghĩ\n"
	.string "sau trận đấu với {STR_VAR_1}.$"

BravoTrainerBattleTower_Text_Won::
	.string "Cặp đôi đã giành chiến thắng chung\n"
	.string "cuộc sau khi đánh bại hoàn toàn\l"
	.string "{STR_VAR_2} của\l"
	.string "{STR_VAR_1}. Hoan hô, HLV!\p"
	.string "Hạ được cả {STR_VAR_1}... Thật\n"
	.string "khó tin! Quá sức ngoạn mục!\p"
	.string "Chúng tôi đã hỏi HLV về cảm nghĩ\n"
	.string "trong khoảnh khắc vinh quang ấy.$"

BravoTrainerBattleTower_Text_LostFinal::
	.string "Sau một chuỗi chiến thắng, cặp đôi cuối\n"
	.string "cùng đã để thua {STR_VAR_2} của\l"
	.string "{STR_VAR_1}, chướng ngại cuối\l"
	.string "cùng của họ.\p"
	.string "Nỗ lực đáng khen, HLV!\p"
	.string "Dù vậy, cũng phải công nhận đối thủ.\n"
	.string "Không mấy khi ta được thấy một bộ đôi\l"
	.string "nổi tiếng như {STR_VAR_1} và\l"
	.string "{STR_VAR_2}.\p"
	.string "Chúng tôi đã hỏi HLV về cảm nghĩ\n"
	.string "khi giao đấu với bộ đôi danh tiếng này.$"

BravoTrainerBattleTower_Text_Satisfied::
	.string "HLV đã nói thế này: “Tôi hài lòng!”\p"
	.string "Quả là một câu trả lời đầy sảng khoái,\n"
	.string "phải không? Hoan hô, HLV!\p"
	.string "Được chiến đấu thỏa thích đến mức\n"
	.string "hoàn toàn mãn nguyện chẳng phải tuyệt\l"
	.string "vời sao?\p"
	.string "Tôi đã biết HLV hài lòng đến mức\n"
	.string "nào khi nghe câu này:$"

BravoTrainerBattleTower_Text_Unsatisfied::
	.string "HLV đã nói thế này: “Tôi chưa hài\n"
	.string "lòng...”\p"
	.string "Rõ ràng HLV của chúng ta hơi buồn\n"
	.string "khi thốt ra câu ấy.\p"
	.string "Nhưng để có thể hoàn toàn mãn nguyện\n"
	.string "sau một trận đấu đâu phải chuyện dễ\l"
	.string "dàng, đúng không?\p"
	.string "Dù sao, tôi đã biết HLV của chúng\n"
	.string "ta thất vọng đến mức nào khi nghe câu\l"
	.string "này:$"

BravoTrainerBattleTower_Text_None1::
	.string "Không có$"

BravoTrainerBattleTower_Text_None2::
	.string "Không có$"

BravoTrainerBattleTower_Text_None3::
	.string "Không có$"

BravoTrainerBattleTower_Text_None4::
	.string "Không có$"

BravoTrainerBattleTower_Text_Response::
	.string "“{STR_VAR_1}.”$"

BravoTrainerBattleTower_Text_ResponseSatisfied::
	.string "“{STR_VAR_1}.” Chẳng phải tuyệt\n"
	.string "lắm sao?\p"
	.string "Tôi thấy câu ấy thực sự thể hiện niềm\n"
	.string "vui của {STR_VAR_2}.\p"
	.string "Trận đấu cuối cùng với\n"
	.string "{STR_VAR_3}... Quả đúng là điều mà\l"
	.string "người ta gọi là “{STR_VAR_1}”!$"

BravoTrainerBattleTower_Text_ResponseUnsatisfied::
	.string "“{STR_VAR_1}.” Chẳng phải quá\n"
	.string "phù hợp sao?\p"
	.string "Trận đấu cuối cùng với\n"
	.string "{STR_VAR_3}... Không thể dùng từ\l"
	.string "nào khác ngoài “{STR_VAR_1}” để\l"
	.string "miêu tả!\p"
	.string "Tôi thấy nỗi thất vọng của\n"
	.string "{STR_VAR_2} đã được thể hiện rõ\l"
	.string "ràng!$"

BravoTrainerBattleTower_Text_Outro::
	.string "Hoan hô, {STR_VAR_1}! Hoan hô,\n"
	.string "{STR_VAR_2}!\p"
	.string "Hy vọng chúng ta sẽ được chứng kiến\n"
	.string "{STR_VAR_1} vươn tới những tầm\l"
	.string "cao hơn nữa!\p"
	.string "Chương trình hôm nay đến đây là hết!\n"
	.string "Hẹn gặp lại lần sau!$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName:
	.string "Chà!\p"
	.string "Nhìn là biết bạn dành rất nhiều tình\n"
	.string "yêu cho {STR_VAR_1}.\p"
	.string "Ra là nó có tên {STR_VAR_2}.\p"
	.string "Tôi có thể nhờ bạn một việc không?\p"
	.string "Tôi là phóng viên truyền hình và đang\n"
	.string "thực hiện một cuộc khảo sát về\l"
	.string "POKéMON.\p"
	.string "Bạn có sẵn lòng trả lời vài câu hỏi đơn\n"
	.string "giản không?$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers:
	.string "Tuyệt quá! Cảm ơn bạn!\p"
	.string "Được rồi, bắt đầu nhé. Tôi chỉ cần\n"
	.string "những câu trả lời ngắn gọn thôi, được\l"
	.string "chứ?$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon:
	.string "Khi lần đầu gặp {STR_VAR_1}, bạn\n"
	.string "đã cảm thấy thế nào?\p"
	.string "Bạn sẽ miêu tả cảm xúc lúc ấy ra sao?$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike:
	.string "Bạn chăm sóc {STR_VAR_1} bằng\n"
	.string "tất cả tình yêu thương.\p"
	.string "Nếu ví nó với một thứ mà bạn thích, đó\n"
	.string "sẽ là gì?$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon:
	.string "Câu hỏi này cũng liên quan đến\n"
	.string "{STR_VAR_1} yêu quý của bạn.\p"
	.string "Điều gì ở {STR_VAR_1} đã thu hút\n"
	.string "bạn?$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou:
	.string "Được rồi, nghe hợp lý đấy.\p"
	.string "Câu tiếp theo có lẽ sẽ hơi khó một chút.\p"
	.string "Câu hỏi là...\p"
	.string "POKéMON có ý nghĩa thế nào đối với\n"
	.string "bạn?$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview:
	.string "Tôi hiểu rồi!\p"
	.string "Hừm hừm...\p"
	.string "Được rồi! Cảm ơn bạn đã giúp tôi.\p"
	.string "Cuộc trò chuyện với bạn vừa thú vị vừa\n"
	.string "giúp tôi hiểu thêm nhiều điều.\p"
	.string "Có thể cuộc phỏng vấn của chúng ta sẽ\n"
	.string "được phát trên TV đấy. Nhớ đón xem\l"
	.string "nhé!\p"
	.string "Được rồi, đến đây là hết. Tạm biệt!$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe:
	.string "Ồ, được thôi...\p"
	.string "Nếu lúc nào bạn muốn kể cho tôi nghe về\n"
	.string "POKéMON, tôi sẽ ở đây!$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews:
	.string "Tôi thích công việc này, vì qua những\n"
	.string "cuộc phỏng vấn, tôi có thể hiểu thêm về\l"
	.string "POKéMON.$"

SlateportCity_PokemonFanClub_Text_InterviewRequest:
	.string "Chào bạn, có vẻ bạn và\n"
	.string "{STR_VAR_1} rất thân thiết.\p"
	.string "Bạn biết không? Tôi là phóng viên\n"
	.string "truyền hình.\p"
	.string "Tôi đi khắp nơi để phỏng vấn mọi người\n"
	.string "về POKéMON.\p"
	.string "Bạn có sẵn lòng kể cho tôi đôi điều về\n"
	.string "{STR_VAR_1} không?$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon:
	.string "Chà, cảm ơn bạn!\p"
	.string "Vậy hãy kể cho tôi bất cứ điều gì bạn\n"
	.string "muốn về {STR_VAR_1} nhé.$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2:
	.string "Chà... Câu chuyện thật thú vị.\p"
	.string "Bạn và {STR_VAR_1} thực sự rất\n"
	.string "gắn bó, phải không?\p"
	.string "Tôi có cảm giác câu chuyện của bạn sẽ\n"
	.string "trở thành một phóng sự truyền hình\l"
	.string "tuyệt vời.\p"
	.string "Tôi hứa sẽ biến nó thành một chương\n"
	.string "trình thật hấp dẫn. Nhớ đón xem nhé.\p"
	.string "Được rồi, đến đây là hết. Tạm biệt!$"

gTVFanClubOpinionsText00::
	.string "CHÚNG TA LÀ POKéMON FAN CLUB!\p"
	.string "Chúng tôi đang lên sóng!\p"
	.string "Trong chương trình này, chúng tôi sẽ\n"
	.string "lắng nghe ý kiến của bạn, rồi thay bạn\l"
	.string "hét thật to những điều ấy! Ý tưởng\l"
	.string "chương trình tuyệt vời quá, phải\l"
	.string "không?\p"
	.string "Hôm nay, chúng tôi xin gửi đến quý vị\n"
	.string "bản tin từ phóng viên được cử tới\l"
	.string "POKéMON FAN CLUB.\p"
	.string "Vậy ai là người hâm mộ POKéMON được\n"
	.string "giới thiệu hôm nay?\p"
	.string "... ... ... ... ... ... ... ...\p"
	.string "{STR_VAR_1}!\p"
	.string "Hãy cùng nghe {STR_VAR_1} nói gì\n"
	.string "về {STR_VAR_3}, một\l"
	.string "{STR_VAR_2}.\p"
	.string "Và tôi sẽ hét thật to những lời yêu\n"
	.string "thương ấy trên TV!\p"
	.string "Hú-hà!\p"
	.string "Cùng hô nào!$"

gTVFanClubOpinionsText01::
	.string "Chúng tôi đã hỏi {STR_VAR_1}:\n"
	.string "“Khi lần đầu nhìn thấy\l"
	.string "{STR_VAR_2} của mình, bạn đã\l"
	.string "nghĩ gì?”\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Tuyệt! Quả là một tiếng hô đầy khí thế!\p"
	.string "Nó có khiến bạn nhớ lại những ngày\n"
	.string "tháng xa xưa ấy không?$"

gTVFanClubOpinionsText02::
	.string "Chúng tôi đã hỏi {STR_VAR_1}:\n"
	.string "“Nếu ví {STR_VAR_2} của bạn với\l"
	.string "một thứ gì đó, thì đó sẽ là...”\p"
	.string "... ... ... ... ... ... ... ...\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Chà, quả là một ý tưởng độc đáo!\p"
	.string "Ta có thể cảm nhận rõ tình cảm mãnh liệt\n"
	.string "mà HLV dành cho {STR_VAR_2}.$"

gTVFanClubOpinionsText03::
	.string "Và xem nào... Điều gì ở\n"
	.string "{STR_VAR_2} ấy đã thu hút\l"
	.string "{STR_VAR_1} đến vậy?\p"
	.string "... ... ... ... ... ... ... ...\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Chà! Quả là một lời tuyên bố ngoạn mục!\p"
	.string "Tình yêu mà HLV dành cho\n"
	.string "{STR_VAR_2} đã được thể hiện rõ\l"
	.string "ràng!$"

gTVFanClubOpinionsText04::
	.string "Hửm? Ồ, vẫn còn nữa. Hãy cùng xem nào!\p"
	.string "Để tôi xem...\p"
	.string "Chúng tôi đã hỏi {STR_VAR_1}:\n"
	.string "“POKéMON có ý nghĩa thế nào đối với\l"
	.string "bạn?”\p"
	.string "... ... ... ... ... ...\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Hoan hô!\p"
	.string "Đó là tiếng hô tuyệt nhất tôi được\n"
	.string "nghe cả ngày hôm nay!\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Nghe mà chỉ muốn hét thật to hết lần\n"
	.string "này đến lần khác!\p"
	.string "Sau một tiếng hô tuyệt vời như vậy, đã\n"
	.string "đến lúc nói lời tạm biệt và hẹn gặp lại!\p"
	.string "Vậy tất cả chúng ta hãy cùng hô lần\n"
	.string "cuối nào! Cùng nhau nhé...\p"
	.string "“{STR_VAR_3}!”$"

gTVFanClubText00::
	.string "CHÚNG TA LÀ POKéMON FAN CLUB!\p"
	.string "Chúng tôi đang lên sóng!\p"
	.string "Hôm nay, chúng ta sẽ mở màn với\n"
	.string "POKéMON SURVEY CORNER.\p"
	.string "Trong vô số câu chuyện được dệt nên\n"
	.string "bởi POKéMON và HLV, vở kịch mới\l"
	.string "đầy bất ngờ nào sẽ thu hút sự chú ý\l"
	.string "của chúng ta hôm nay?\p"
	.string "Để tôi xem...\p"
	.string "Cái này!\p"
	.string "Chúng ta sẽ bắt đầu với lá thư này!\p"
	.string "Đây là thư của {STR_VAR_1} viết\n"
	.string "về một {STR_VAR_2} yêu quý.\p"
	.string "Hãy xem người viết có thể bày tỏ tình\n"
	.string "yêu dành cho {STR_VAR_2} nồng\l"
	.string "nhiệt đến mức nào! Hừm hừm...$"

gTVFanClubText01::
	.string "Chà! Quả là một lá thư tuyệt vời!$"

gTVFanClubText02::
	.string "Tôi thích quá, nên xin đọc lại lần nữa!$"

gTVFanClubText03::
	.string "Một lá thư hay đáng để đọc đi đọc lại!$"

gTVFanClubText04::
	.string "Đoạn “{STR_VAR_3}” thực sự làm\n"
	.string "cảm xúc thêm phần mạnh mẽ!\p"
	.string "Đây là một lá thư tuyệt vời với tình\n"
	.string "cảm sâu sắc xuất phát từ trái tim!$"

gTVFanClubText05::
	.string "Đặc biệt là đoạn “{STR_VAR_3}”!\p"
	.string "Tôi rất thích cách dùng\n"
	.string "“{STR_VAR_3}”!$"

gTVFanClubText06::
	.string "Nhân tiện, dù không quan trọng lắm,\n"
	.string "nhưng “{STR_VAR_3}” là một câu\l"
	.string "nói rất hay.\p"
	.string "Gần đây tôi thường xuyên dùng\n"
	.string "“{STR_VAR_3}” khi trò chuyện.$"

gTVFanClubText07::
	.string "Nếu phải chấm điểm lá thư này, tôi sẽ\n"
	.string "cho {STR_VAR_3} điểm.\p"
	.string "Lần sau, tôi mong chờ một lá thư còn\n"
	.string "hay hơn nữa đấy, {STR_VAR_1}!\p"
	.string "Ôi chao, nhìn giờ kìa! Đã đến lúc nói lời\n"
	.string "tạm biệt và hẹn gặp lại!$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest:
	.string "Ồ? Có phải bạn thích POKéMON không?\p"
	.string "Tôi đang làm nhiệm vụ cho đài truyền\n"
	.string "hình.\p"
	.string "Tôi đang thu thập những câu chuyện gần\n"
	.string "đây về POKéMON và HLV.\p"
	.string "Nếu không phiền, bạn có thể kể cho tôi\n"
	.string "đôi điều về mình không?$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort:
	.string "Tôi đang thu thập những câu chuyện gần\n"
	.string "đây về POKéMON và HLV.\p"
	.string "Nếu không phiền, bạn có thể kể cho tôi\n"
	.string "đôi điều về mình không?$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon:
	.string "Ồ, bạn đồng ý sao? Cảm ơn bạn!\p"
	.string "Vậy hãy kể cho tôi bất cứ trải nghiệm\n"
	.string "thú vị nào gần đây có liên quan đến\l"
	.string "POKéMON.$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory:
	.string "Ồ, tôi hiểu rồi...\p"
	.string "Nếu có câu chuyện thú vị nào muốn kể,\n"
	.string "xin hãy cho tôi biết nhé.$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview:
	.string "Ồ, thật là một câu chuyện truyền cảm\n"
	.string "hứng!\p"
	.string "Tôi nhất định sẽ đưa câu chuyện của\n"
	.string "bạn lên truyền hình.\p"
	.string "Tôi nghĩ nó sẽ được phát sóng vào một\n"
	.string "lúc nào đó, nên hãy chờ đón nhé.$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory:
	.string "Hừm... Mình đã có một câu chuyện hay\n"
	.string "cho chương trình TV.\p"
	.string "Phải mau chóng viết lại mới được!$"

gTVRecentHappeningsText00::
	.string "Xin chào, đã đến giờ RECENT\n"
	.string "HAPPENINGS.\p"
	.string "Đối với HLV POKéMON, mỗi ngày đều\n"
	.string "là một câu chuyện như trong sách.\p"
	.string "Điều chúng tôi muốn làm là giới thiệu\n"
	.string "đến quý vị một vài câu chuyện POKéMON\l"
	.string "như thế.\p"
	.string "Hôm nay, chúng tôi mang đến câu chuyện\n"
	.string "của HLV {STR_VAR_1}.\p"
	.string "Gần đây {STR_VAR_1} đã trải qua\n"
	.string "chuyện gì? Hãy cùng tìm hiểu.\p"
	.string "Xem nào...$"

gTVRecentHappeningsText01::
	.string "Thật đáng để suy ngẫm, phải không?\p"
	.string "Câu chuyện giúp ta hình dung rõ những\n"
	.string "gì {STR_VAR_1} đã trải qua gần\l"
	.string "đây. Cứ như chính chúng ta cũng có mặt\l"
	.string "để chứng kiến vậy!$"

gTVRecentHappeningsText02::
	.string "“{STR_VAR_3}.” Câu ấy tạo điểm\n"
	.string "nhấn và chiều sâu cho câu chuyện.$"

gTVRecentHappeningsText03::
	.string "“{STR_VAR_3}.” Câu ấy mang đến\n"
	.string "cảm giác rõ nét về địa điểm, giúp chúng\l"
	.string "ta hình dung ra bối cảnh của câu\l"
	.string "chuyện.$"

gTVRecentHappeningsText04::
	.string "Đoạn “{STR_VAR_3}” trong câu\n"
	.string "chuyện được diễn đạt rất sinh động.$"

gTVRecentHappeningsText05::
	.string "{STR_VAR_1} đã kể lại một câu\n"
	.string "chuyện tuyệt vời có liên quan đến\l"
	.string "POKéMON.\p"
	.string "Và giờ đây, câu chuyện của\n"
	.string "{STR_VAR_1} cũng đã khắc sâu vào\l"
	.string "tâm trí quý vị.\p"
	.string "Chương trình hôm nay đến đây là hết.\n"
	.string "Xin mời đón xem lần sau.$"

gTVMassOutbreakText00::
	.string "Xin chào! Đã đến giờ POKéMON NEWS.\p"
	.string "Chúng tôi vừa nhận được tin về một\n"
	.string "hiện tượng vô cùng hiếm gặp.\p"
	.string "Có báo cáo về một đợt xuất hiện hàng\n"
	.string "loạt của {STR_VAR_2} ở khu vực\l"
	.string "gần {STR_VAR_1}.\p"
	.string "Như quý vị có lẽ đã biết,\n"
	.string "{STR_VAR_2} là một POKéMON hiếm\l"
	.string "và rất khó tìm.\p"
	.string "Đây có vẻ là cơ hội hiếm có để chứng\n"
	.string "kiến đợt xuất hiện bí ẩn của\l"
	.string "{STR_VAR_2} ngoài tự nhiên.\p"
	.string "Đó là toàn bộ tin tức từ POKéMON NEWS.$"

gTV3CheersForPokeblocksText00::
	.string "MC: Chúc quý vị luôn vui vẻ, “BA LỜI\n"
	.string "KHEN CHO {POKEBLOCK}” đã lên sóng!\p"
	.string "Hôm nay, chúng ta sẽ đánh giá\n"
	.string "{POKEBLOCK} do {STR_VAR_1} và\l"
	.string "các cộng sự pha chế.\p"
	.string "Không chần chừ thêm nữa, hãy để tôi\n"
	.string "cho POKéMON sành ăn GULPIN của mình\l"
	.string "nếm thử.\p"
	.string "... ... ... ... ... ... ... ... ... ... ... ...$"

gTV3CheersForPokeblocksText01::
	.string "GULPIN: Gubi! Gubii!\p"
	.string "MC: Và kết luận là nó rất\n"
	.string "{STR_VAR_1}! GULPIN nói rằng\l"
	.string "hương vị của nó là\l"
	.string "“{STR_VAR_2}!”\p"
	.string "Cảm ơn rất nhiều, {STR_VAR_3}!$"

gTV3CheersForPokeblocksText02::
	.string "Màn pha chế của {STR_VAR_1} vẫn\n"
	.string "còn nhiều điều chưa đạt yêu cầu.\p"
	.string "Nếu HLV này pha chế tốt hơn,\n"
	.string "{POKEBLOCK} sẽ ngon hơn nhiều.$"

gTV3CheersForPokeblocksText03::
	.string "GULPIN: Gubi! Gubii!\p"
	.string "MC: Hừm... Nó quá {STR_VAR_1}.\n"
	.string "GULPIN nói rằng hương vị của nó là\l"
	.string "“{STR_VAR_2}!”\p"
	.string "Có vẻ những sai sót của\n"
	.string "{STR_VAR_3} đã làm giảm chất\l"
	.string "lượng pha chế...$"

gTV3CheersForPokeblocksText04::
	.string "Thật đáng tiếc khi nỗ lực dẫn đầu của\n"
	.string "{STR_VAR_1} đã trở nên vô ích.\p"
	.string "Hy vọng lần sau {STR_VAR_2} sẽ\n"
	.string "thể hiện tốt hơn!$"

gTV3CheersForPokeblocksText05::
	.string "Hẹn gặp lại lần sau! Khẩu hiệu của chúng\n"
	.string "tôi là “BA LỜI KHEN CHO {POKEBLOCK}!”$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
	.string "Xin chào!\p"
	.string "Tôi là người hâm mộ cuồng nhiệt của\n"
	.string "{STR_VAR_1}. Bạn nghĩ gì về\l"
	.string "{STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
	.string "Tôi hiểu rồi. Vậy đó là suy nghĩ của bạn\n"
	.string "về HLV ấy.$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
	.string "Bạn đã hoàn toàn quên mất\n"
	.string "{STR_VAR_1} rồi sao?$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
	.string "Tôi là người hâm mộ cuồng nhiệt của\n"
	.string "{STR_VAR_1}. Bạn nghĩ gì về\l"
	.string "{STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
	.string "Nếu chấm trên thang điểm một trăm, bạn\n"
	.string "đánh giá {STR_VAR_1} mạnh đến\l"
	.string "mức nào?$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
	.string "Bạn đã hoàn toàn quên mất\n"
	.string "{STR_VAR_1} rồi sao?$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
	.string "Ồ, tôi hiểu rồi! Khi nào có dịp, bạn nên\n"
	.string "gặp {STR_VAR_1}. Tôi chắc bạn\l"
	.string "cũng sẽ trở thành người hâm mộ!$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
	.string "Tôi hiểu rồi.\p"
	.string "Cảm ơn bạn! Thông tin này rất hữu ích.\p"
	.string "Tôi sẽ chia sẻ với những người hâm mộ\n"
	.string "khác của {STR_VAR_1} để cùng bàn\l"
	.string "luận.$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
	.string "Sắp tới sẽ có một chương trình TV đặc\n"
	.string "biệt về {STR_VAR_1}.\p"
	.string "Hy vọng bạn sẽ đón xem!$"

gTVTrainerFanClubSpecialText00::
	.string "TRAINER FAN CLUB {STR_VAR_1}\n"
	.string "SPECIAL!\p"
	.string "Đây là chương trình đặc biệt dành cho\n"
	.string "người hâm mộ {STR_VAR_1} trên\l"
	.string "khắp HOENN!\p"
	.string "Hôm nay, chúng ta sẽ đặt câu hỏi: “Mọi\n"
	.string "người nghĩ gì về {STR_VAR_1}?”\p"
	.string "Chúng tôi đã hỏi {STR_VAR_2} với\n"
	.string "tư cách đại diện cho các HLV.\p"
	.string "Chúng tôi hỏi: “Nếu dùng một từ để miêu\n"
	.string "tả {STR_VAR_1}, bạn sẽ chọn từ\l"
	.string "nào?”\p"
	.string "Câu trả lời là: “{STR_VAR_3}.”\p"
	.string "Xin khen ngợi {STR_VAR_2}! Quả là\n"
	.string "một nhận xét sâu sắc!\p"
	.string "“{STR_VAR_3}\n"
	.string "{STR_VAR_1}.” Nghe thật thuận\l"
	.string "tai!\p"
	.string "{STR_VAR_2} cũng đã chấm sức\n"
	.string "mạnh của {STR_VAR_1} theo thang\l"
	.string "điểm từ 0 đến 100.$"

gTVTrainerFanClubSpecialText01::
	.string "Số điểm là {STR_VAR_3}! Quả thực\n"
	.string "là một điểm số rất cao!\p"
	.string "Rõ ràng {STR_VAR_2} vô cùng kính\n"
	.string "trọng {STR_VAR_1}.$"

gTVTrainerFanClubSpecialText02::
	.string "Số điểm là {STR_VAR_3}! Đây là\n"
	.string "một điểm số khá tốt.\p"
	.string "Hẳn {STR_VAR_2} coi\n"
	.string "{STR_VAR_1} là đối thủ.$"

gTVTrainerFanClubSpecialText03::
	.string "Số điểm là {STR_VAR_3}! Đây là\n"
	.string "một điểm số khá thấp.\p"
	.string "Hẳn {STR_VAR_2} chỉ coi\n"
	.string "{STR_VAR_1} là bạn đồng hành phụ\l"
	.string "trợ.$"

gTVTrainerFanClubSpecialText04::
	.string "Số điểm là {STR_VAR_3}! Điểm số\n"
	.string "thật tệ.\p"
	.string "Hẳn {STR_VAR_2} coi\n"
	.string "{STR_VAR_1} là cấp dưới.$"

gTVTrainerFanClubSpecialText05::
	.string "Quý vị đã nghe rõ rồi đấy!\p"
	.string "Tôi nghĩ tất cả chúng ta đều vừa biết\n"
	.string "thêm một điều mới về\l"
	.string "{STR_VAR_1}.\p"
	.string "Để khép lại chương trình, xin gửi đến\n"
	.string "quý vị lời của {STR_VAR_2}.\p"
	.string "{STR_VAR_3} {STR_VAR_1}!$"

gTVNameRaterText00::
	.string "Và giờ, đã đến lúc dành cho...\n"
	.string "CHƯƠNG TRÌNH NAME RATER.\p"
	.string "Tôi sẽ đoán vận mệnh POKéMON của bạn\n"
	.string "từ biệt danh mà bạn đã đặt cho nó.\p"
	.string "Việc của tôi là đưa ra lời khuyên, và đó\n"
	.string "luôn là những lời khuyên hữu ích.\p"
	.string "Hôm nay, tôi sẽ luận giải biệt danh\n"
	.string "{STR_VAR_3} của POKéMON\l"
	.string "{STR_VAR_2} thuộc về\l"
	.string "{STR_VAR_1}.\p"
	.string "Hừm hừm...\p"
	.string "Hừm... Biệt danh này...$"

gTVNameRaterText01::
	.string "Một biệt danh gợi lên tài năng trên\n"
	.string "nhiều phương diện.\p"
	.string "Tôi khuyên HLV này hãy can đảm\n"
	.string "đương đầu với nhiều thử thách.$"

gTVNameRaterText02::
	.string "Một biệt danh bổ trợ hoàn hảo cho tên\n"
	.string "của HLV là {STR_VAR_1}.\p"
	.string "Nó báo hiệu rằng hai bạn sẽ tạo nên một\n"
	.string "mối quan hệ hợp tác ăn ý và đúng thời\l"
	.string "điểm.$"

gTVNameRaterText03::
	.string "Một biệt danh xứng đáng với một\n"
	.string "POKéMON độc nhất vô nhị!\p"
	.string "Nếu được nuôi dạy đúng cách, nét độc\n"
	.string "đáo của POKéMON này sẽ nở rộ rực rỡ!$"

gTVNameRaterText04::
	.string "Một biệt danh sẽ vun đắp khía cạnh ân\n"
	.string "cần và giàu lòng trắc ẩn của POKéMON.\p"
	.string "Nếu được nuôi dạy đúng cách, POKéMON\n"
	.string "này sẽ thể hiện sự ấm áp chân thành!$"

gTVNameRaterText05::
	.string "Một biệt danh rất hay, báo hiệu những\n"
	.string "điều vĩ đại trong tương lai.\p"
	.string "Tôi rất tò mò muốn biết tương lai đang\n"
	.string "dành điều gì cho POKéMON này.$"

gTVNameRaterText06::
	.string "Một biệt danh hay, sẽ giúp POKéMON luôn\n"
	.string "khỏe mạnh và tràn đầy sức sống!\p"
	.string "POKéMON ấy hẳn sẽ sung sức và cường\n"
	.string "tráng trong một thời gian rất dài.$"

gTVNameRaterText07::
	.string "Một biệt danh hay, sẽ khiến POKéMON vô\n"
	.string "cùng năng động!\p"
	.string "Tôi nghĩ POKéMON này sẽ thể hiện rất\n"
	.string "xuất sắc trong các trận đấu.$"

gTVNameRaterText08::
	.string "Một biệt danh cuốn hút, sẽ khiến\n"
	.string "POKéMON trở nên vô cùng duyên dáng!\p"
	.string "Tôi tin POKéMON này sẽ rất biết cách\n"
	.string "chinh phục khán giả trong POKéMON\l"
	.string "CONTESTS.$"

gTVNameRaterText09::
	.string "Biệt danh {STR_VAR_1} lấy chữ\n"
	.string "“{STR_VAR_3}” làm nền tảng.\p"
	.string "Chữ ấy được nâng đỡ bởi chữ cái đầu\n"
	.string "tiên “{STR_VAR_2}”, tạo cho biệt\l"
	.string "danh một cảm giác hiện diện vững chắc.$"

gTVNameRaterText10::
	.string "Biệt danh {STR_VAR_1} có hình\n"
	.string "thức rất cân đối và dễ chịu.\p"
	.string "Sự hiện diện của hai chữ\n"
	.string "“{STR_VAR_2}” và\l"
	.string "“{STR_VAR_3}” quả thực vô cùng\l"
	.string "tuyệt vời!$"

gTVNameRaterText11::
	.string "Biệt danh {STR_VAR_1} mang một\n"
	.string "cảm giác uyển chuyển và thanh cao.\p"
	.string "Đặc biệt tuyệt vời là sự chuyển tiếp\n"
	.string "từ chữ đầu “{STR_VAR_2}” sang\l"
	.string "“{STR_VAR_3}”.$"

gTVNameRaterText12::
	.string "Chúng ta hãy cùng xem xét những ví dụ\n"
	.string "khác về các biệt danh hay nhé?$"

gTVNameRaterText13::
	.string "Hãy thử ví dụ này. Lấy một phần từ tên\n"
	.string "HLV là {STR_VAR_1}, ta sẽ có\l"
	.string "biệt danh tuyệt vời\l"
	.string "{STR_VAR_2}{STR_VAR_3}.$"

gTVNameRaterText14::
	.string "Biệt danh\n"
	.string "{STR_VAR_2}{STR_VAR_3}\l"
	.string "cũng sẽ rất phù hợp.$"

gTVNameRaterText15::
	.string "Tên loài POKéMON là {STR_VAR_2}\n"
	.string "có thể được dùng làm cơ sở để tạo ra\l"
	.string "biệt danh\l"
	.string "{STR_VAR_1}{STR_VAR_3}.$"

gTVNameRaterText16::
	.string "{STR_VAR_1}{STR_VAR_3}\n"
	.string "cũng sẽ là một biệt danh hiệu quả.$"

gTVNameRaterText17::
	.string "Điều luôn phải tránh là sử dụng tên của\n"
	.string "một loài POKéMON khác.\p"
	.string "Chẳng hạn, đừng lấy tên\n"
	.string "{STR_VAR_2} để tạo thành biệt\l"
	.string "danh\l"
	.string "{STR_VAR_1}{STR_VAR_3}.\l"
	.string "Như thế là không thể chấp nhận được.$"

gTVNameRaterText18::
	.string "Tôi phải nói rằng {STR_VAR_1} là\n"
	.string "một biệt danh khá hay.\p"
	.string "Tôi hy vọng HLV sẽ tiếp tục dành\n"
	.string "tình yêu thương cho\l"
	.string "{STR_VAR_1}.\p"
	.string "Chương trình hôm nay đến đây là hết.\n"
	.string "Mong chúng ta sẽ lại gặp nhau.$"

gTVPokemonAnglerText00::
	.string "{STR_VAR_2} ANGLER\p"
	.string "NGƯỜI DẪN: Xin chào! Hôm nay, chúng ta\n"
	.string "sẽ tìm hiểu bí quyết câu\l"
	.string "{STR_VAR_2}.\p"
	.string "GURU, ông có lời khuyên gì để bắt được\n"
	.string "{STR_VAR_2}?\p"
	.string "GURU: Hửm? Bắt {STR_VAR_2} à?\n"
	.string "Tôi nói cho mà biết, hãy kiên nhẫn chờ\l"
	.string "đợi. Đó là điều quan trọng nhất.\p"
	.string "Có thấy {STR_VAR_1} ở đằng kia\n"
	.string "không? HLV đó là một tấm gương\l"
	.string "tốt.\p"
	.string "HLV ấy đã để sổng tới\n"
	.string "{STR_VAR_3} POKéMON rồi.\p"
	.string "Nhưng {STR_VAR_1} vẫn đứng đó\n"
	.string "chờ. Không chịu bỏ cuộc. Đó là nguyên\l"
	.string "tắc để bắt được {STR_VAR_2}.\p"
	.string "NGƯỜI DẪN: Tôi hiểu rồi...\p"
	.string "Ồ! Cuối cùng {STR_VAR_1} đã câu\n"
	.string "được một {STR_VAR_2} khó bắt!\p"
	.string "HLV ấy dường như sắp rơi nước\n"
	.string "mắt vì quá vui!\p"
	.string "Nhìn vẻ mặt hân hoan đó khiến tôi cũng\n"
	.string "muốn đi câu cá!\p"
	.string "Quý vị khán giả, sao không nhân dịp này\n"
	.string "thử đi câu {STR_VAR_2}?\p"
	.string "Hẹn gặp lại trong buổi phát sóng tiếp\n"
	.string "theo. Chúc tất cả quý vị câu cá vui vẻ!$"

gTVPokemonAnglerText01::
	.string "{STR_VAR_2} ANGLER\p"
	.string "NGƯỜI DẪN: Xin chào! Hôm nay, chúng ta\n"
	.string "sẽ tìm hiểu bí quyết câu\l"
	.string "{STR_VAR_2}.\p"
	.string "GURU, ông có lời khuyên gì để bắt được\n"
	.string "{STR_VAR_2}?\p"
	.string "GURU: Hửm? Bắt {STR_VAR_2} à?\n"
	.string "Tôi nói cho mà biết, hãy vung ROD thật\l"
	.string "mạnh mẽ!\p"
	.string "Có thấy {STR_VAR_1} ở đằng kia\n"
	.string "không? Nhìn cách sử dụng ROD kìa!\p"
	.string "HLV ấy đã bắt được liên tiếp\n"
	.string "{STR_VAR_3} con rồi.\p"
	.string "NGƯỜI DẪN: Thật không thể tin nổi!\n"
	.string "Trông cứ như một cơn bão...\p"
	.string "Chứng kiến kỹ thuật điêu luyện đến thế\n"
	.string "khiến tôi cũng muốn đi câu cá.\p"
	.string "Quý vị khán giả, sao không nhân dịp này\n"
	.string "thử đi câu {STR_VAR_2}?\p"
	.string "Hẹn gặp lại trong buổi phát sóng tiếp\n"
	.string "theo. Chúc tất cả quý vị câu cá vui vẻ!$"

gTVPokemonTodayFailedText00::
	.string "Xin chào!\p"
	.string "Đã đến giờ POKéMON TODAY!\p"
	.string "BIG SIS: Chào mọi người! Hôm nay tất cả\n"
	.string "có vui vẻ và tràn đầy năng lượng\l"
	.string "không?\p"
	.string "Hôm nay, chúng ta sẽ tìm hiểu POKéMON\n"
	.string "{STR_VAR_2} của\l"
	.string "{STR_VAR_1}!\p"
	.string "BIG BRO: Đúng vậy! Chúng ta sẽ làm thế!$"

gTVPokemonTodayFailedText01::
	.string "Ồ! Nhắc đến {STR_VAR_1} mới\n"
	.string "nhớ...\p"
	.string "BIG SIS, chính mắt em đã nhìn thấy\n"
	.string "HLV ấy!\p"
	.string "BIG SIS: Ồ, em đã thấy gì?\p"
	.string "BIG BRO: Chuyện là em phải đi đến\n"
	.string "{STR_VAR_2}.\p"
	.string "Khi ấy, em tình cờ gặp\n"
	.string "{STR_VAR_1} đang cố bắt POKéMON\l"
	.string "{STR_VAR_3}, nhưng...$"

gTVPokemonTodayFailedText02::
	.string "POKéMON ấy đã chạy thoát!\p"
	.string "Kết quả là số POKé BALLS bị lãng phí lên\n"
	.string "đến: {STR_VAR_2}!\p"
	.string "Mọi người phải thấy vẻ mặt thất vọng\n"
	.string "của {STR_VAR_1} khi POKéMON ấy\l"
	.string "bỏ chạy mới được!$"

gTVPokemonTodayFailedText03::
	.string "Nhưng {STR_VAR_1} đã sơ suất và\n"
	.string "khiến POKéMON ấy ngất xỉu!\p"
	.string "Kết quả là số POKé BALLS bị lãng phí lên\n"
	.string "đến: {STR_VAR_2}!\p"
	.string "Mọi người phải thấy vẻ mặt bàng hoàng\n"
	.string "của {STR_VAR_1} khi POKéMON ấy\l"
	.string "ngất xỉu mới được!$"

gTVPokemonTodayFailedText04::
	.string "BIG SIS: Này! Như thế không hay đâu!\p"
	.string "Không nên cười trên nỗi bất hạnh của\n"
	.string "người khác chứ!\p"
	.string "Ôi, {STR_VAR_1} đáng thương.\n"
	.string "Thật tội nghiệp!\p"
	.string "BIG BRO: Đúng vậy! Xin lỗi vì đã cười.$"

gTVPokemonTodayFailedText05::
	.string "BIG SIS: Phư phư phư...\p"
	.string "BIG BRO: Này! Chị cũng vừa cười đấy\n"
	.string "thôi!\p"
	.string "BIG SIS: Hả?!\p"
	.string "Tôi đâu có cười! Thật đấy, tôi không\n"
	.string "cười mà!\p"
	.string "Ôi, {STR_VAR_1} đáng thương.\n"
	.string "Thật tội nghiệp!\p"
	.string "BIG BRO: ...$"

gTVPokemonTodayFailedText06::
	.string "BIG SIS: Đùa thế đủ rồi! Hãy cùng xem\n"
	.string "POKéMON hôm nay...\p"
	.string "Hả? Đã hết giờ rồi sao?\p"
	.string "Ôi! Hôm nay chúng ta chưa kịp giới thiệu\n"
	.string "một POKéMON nào cả!\p"
	.string "BIG BRO: Hẹn gặp lại lần sau!\p"
	.string "BIG SIS: Này, đừng kết thúc chương\n"
	.string "trình khi chưa có tôi chứ!$"

gTVPokemonTodaySuccessfulText00::
	.string "Xin chào!\p"
	.string "Đã đến giờ của POKéMON TODAY!\p"
	.string "BIG SIS: Chào mọi người! Hôm nay ai\n"
	.string "cũng khỏe khoắn và tràn đầy sức sống\l"
	.string "chứ?\p"
	.string "Hôm nay, chúng ta sẽ tìm hiểu về\n"
	.string "POKéMON {STR_VAR_2} của\l"
	.string "{STR_VAR_1}!\p"
	.string "BIG BRO: Phải! Chính xác là vậy!$"

gTVPokemonTodaySuccessfulText01::
	.string "BIG SIS: {STR_VAR_1} đã đặt biệt\n"
	.string "danh {STR_VAR_3} cho\l"
	.string "{STR_VAR_2}!\p"
	.string "Có vẻ {STR_VAR_3} đang được yêu\n"
	.string "thương và chăm sóc rất chu đáo!$"

gTVPokemonTodaySuccessfulText02::
	.string "BIG BRO: HLV đã phải ném tổng cộng\n"
	.string "ngần này POKé BALLS để bắt nó:\l"
	.string "{STR_VAR_3}!\p"
	.string "Cuối cùng, chỉ một {STR_VAR_2}\n"
	.string "đã bắt được nó!$"

gTVPokemonTodaySuccessfulText03::
	.string "BIG SIS: Nếu bắt dễ dàng đến thế, hẳn\n"
	.string "định mệnh đã đưa {STR_VAR_1} và\l"
	.string "{STR_VAR_2} đến với nhau!$"

gTVPokemonTodaySuccessfulText04::
	.string "BIG SIS: Chà! Tuyệt quá!\p"
	.string "Nhưng người ta vẫn nói rằng, POKéMON\n"
	.string "càng khó bắt thì càng nhận được nhiều\l"
	.string "tình yêu từ HLV của mình!$"

gTVPokemonTodaySuccessfulText05::
	.string "BIG SIS: {STR_VAR_2} của\n"
	.string "{STR_VAR_1} là một POKéMON khó\l"
	.string "quên, vì đã được bắt bằng MASTER BALL\l"
	.string "vô giá!\p"
	.string "BIG BRO: Chà! Siêu tuyệt vời!\p"
	.string "BIG SIS: Chắc chắn {STR_VAR_1}\n"
	.string "đã rất muốn có {STR_VAR_2}!$"

gTVPokemonTodaySuccessfulText06::
	.string "BIG BRO: Rồi còn đặt biệt danh\n"
	.string "{STR_VAR_3} cho\l"
	.string "{STR_VAR_2} ấy nữa...\p"
	.string "Chỉ vậy cũng đủ thấy gu của HLV\n"
	.string "{STR_VAR_1} rồi.\p"
	.string "BIG SIS: Tôi hoàn toàn đồng ý!$"

gTVPokemonTodaySuccessfulText07::
	.string "Nếu là tôi, tôi sẽ đặt biệt danh ấy cho\n"
	.string "một {STR_VAR_3} như thế này!\p"
	.string "BIG BRO: Chà! Biết đâu đó lại là khởi\n"
	.string "đầu của một trào lưu mới!$"

gTVPokemonTodaySuccessfulText08::
	.string "{STR_VAR_2}, chú\n"
	.string "{STR_VAR_1} ư? Nghe hoàn hảo\l"
	.string "quá còn gì?\p"
	.string "Cả cách ghép chữ lẫn âm điệu đều cực\n"
	.string "kỳ hợp với POKéMON {STR_VAR_1}!\p"
	.string "BIG BRO: Ừ, đúng thật!$"

gTVPokemonTodaySuccessfulText09::
	.string "Theo tôi biết, chưa có HLV nào\n"
	.string "từng đặt biệt danh {STR_VAR_2}\l"
	.string "cho {STR_VAR_1} của mình!\p"
	.string "BIG BRO: Thế mới thấy HLV này có gu\n"
	.string "đặt biệt danh tuyệt vời đến mức nào!$"

gTVPokemonTodaySuccessfulText10::
	.string "Lần tới bắt được một POKéMON, tôi sẽ\n"
	.string "đặt tên nó là {STR_VAR_2}.\p"
	.string "BIG BRO: Hả? Tôi cũng vậy! Tôi cũng sẽ\n"
	.string "dùng biệt danh {STR_VAR_2}!$"

gTVPokemonTodaySuccessfulText11::
	.string "BIG SIS: Ôi không! Nhìn giờ kìa!\p"
	.string "Thôi, chương trình hôm nay xin kết\n"
	.string "thúc tại đây. Hẹn gặp lại lần sau!\p"
	.string "BIG BRO: Hãy nhớ rằng, lần tới chính\n"
	.string "POKéMON của bạn có thể sẽ trở thành\l"
	.string "tâm điểm đấy!$"

SmartShopper_Text_Intro::
	.string "Xin chào!\p"
	.string "Đã đến giờ của TODAY'S SMART SHOPPER.\p"
	.string "PHỎNG VẤN: Quý khán giả có khỏe\n"
	.string "không?\p"
	.string "Hôm nay, chúng tôi sẽ ghé thăm một cửa\n"
	.string "hàng ở {STR_VAR_2}.\p"
	.string "Hãy xem gần đây mặt hàng nào đang bán\n"
	.string "chạy nhất.$"

SmartShopper_Text_ClerkNormal::
	.string "Hãy phỏng vấn nhân viên để tìm hiểu\n"
	.string "tình hình.\p"
	.string "Xin chào, việc kinh doanh thế nào rồi?\p"
	.string "NHÂN VIÊN: Ồ, rất thuận lợi.\p"
	.string "Gần đây, {STR_VAR_2} bán đặc\n"
	.string "biệt chạy.\p"
	.string "Mới hôm nọ, một HLV tên\n"
	.string "{STR_VAR_1} đã mua tới\l"
	.string "{STR_VAR_3} cái.$"

SmartShopper_Text_RandomComment1::
	.string "PHỎNG VẤN: HLV ấy đã mua tới\n"
	.string "{STR_VAR_3} {STR_VAR_2}\l"
	.string "sao? Quả là một mẻ lớn!\p"
	.string "Theo tôi đoán, hẳn {STR_VAR_1}\n"
	.string "đang tích trữ để chuẩn bị cho một\l"
	.string "chuyến đi dài đến những miền xa xôi.\p"
	.string "Khi đi xa, {STR_VAR_2} rất quan\n"
	.string "trọng!$"

SmartShopper_Text_RandomComment2::
	.string "PHỎNG VẤN: Nhắc đến\n"
	.string "{STR_VAR_2}, gần đây tôi cũng\l"
	.string "vừa mua {STR_VAR_3} cái.\p"
	.string "Dù sao thì {STR_VAR_2} cũng là\n"
	.string "một vật phẩm tuyệt vời!$"

SmartShopper_Text_RandomComment3::
	.string "PHỎNG VẤN: {STR_VAR_2} ư?! Lại\n"
	.string "còn tới {STR_VAR_3} cái?!\p"
	.string "Tôi không ngờ có người lại mua nhiều\n"
	.string "đến thế.\p"
	.string "Trời ạ, mỗi lần tôi chỉ đủ tiền mua một\n"
	.string "hoặc hai cái...$"

SmartShopper_Text_RandomComment4::
	.string "PHỎNG VẤN: Có lần tôi đã mua cả đống\n"
	.string "{STR_VAR_2}.\p"
	.string "Nhưng hóa ra lại nhiều quá. Cuối cùng\n"
	.string "tôi phải hối hận...\p"
	.string "Từ đó, tôi chỉ mua đúng những gì thật\n"
	.string "sự cần thiết...\p"
	.string "Ôi!\p"
	.string "Nói về tôi thì có ích gì chứ!$"

SmartShopper_Text_SecondItem::
	.string "NHÂN VIÊN: {STR_VAR_1} cũng mua số\n"
	.string "lượng lớn {STR_VAR_2}, tổng\l"
	.string "cộng {STR_VAR_3} cái.\p"
	.string "PHỎNG VẤN: Ồ, lựa chọn thông minh\n"
	.string "đấy. {STR_VAR_2} cũng là một vật\l"
	.string "phẩm rất hữu ích.$"

SmartShopper_Text_ThirdItem::
	.string "NHÂN VIÊN: Ngoài ra, HLV ấy còn mua\n"
	.string "{STR_VAR_3} vật phẩm\l"
	.string "{STR_VAR_2}.$"

SmartShopper_Text_DuringSale::
	.string "NHÂN VIÊN: Hơn nữa, lúc đó có đợt\n"
	.string "đại hạ giá. Quả là mua sắm thông minh.$"

SmartShopper_Text_OutroNormal::
	.string "PHỎNG VẤN: Hừm... Có vẻ\n"
	.string "{STR_VAR_1} là một tay săn giá\l"
	.string "hời rất khôn ngoan!\p"
	.string "Tổng số tiền mua sắm của\n"
	.string "{STR_VAR_1} là...\p"
	.string "¥{STR_VAR_2}?! Thật là một khoản\n"
	.string "đáng kinh ngạc!\p"
	.string "Ôi! Chúng ta hết giờ rồi! Hẹn gặp lại\n"
	.string "trong chương trình lần sau!$"

SmartShopper_Text_IsVIP::
	.string "NHÂN VIÊN: Không nghi ngờ gì nữa,\n"
	.string "{STR_VAR_1} là khách hàng VIP.$"

SmartShopper_Text_ClerkMax::
	.string "Hãy phỏng vấn nhân viên để tìm hiểu\n"
	.string "tình hình.\p"
	.string "Xin chào, việc kinh doanh thế nào rồi?\p"
	.string "NHÂN VIÊN: Ồ, việc kinh doanh tốt\n"
	.string "cực tốt. Chúng tôi gần như không xuể.\p"
	.string "Gần đây, một HLV tên\n"
	.string "{STR_VAR_1} đã mua số lượng lớn\l"
	.string "vật phẩm {STR_VAR_2}.\p"
	.string "HLV ấy gần như vét sạch toàn bộ\n"
	.string "{STR_VAR_2} trong kho.\p"
	.string "Tôi chưa từng tưởng tượng có khách\n"
	.string "hàng lại cần nhiều {STR_VAR_2}\l"
	.string "đến thế. Thật chưa từng thấy!\p"
	.string "PHỎNG VẤN: Vậy chắc đã bán khoảng\n"
	.string "100 hoặc 200 cái?\p"
	.string "NHÂN VIÊN: Ồ không, còn nhiều hơn\n"
	.string "rất nhiều!\p"
	.string "PHỎNG VẤN: Trời ơi!\n"
	.string "{STR_VAR_1} hẳn là một vị khách\l"
	.string "đặc biệt!\p"
	.string "NHÂN VIÊN: Không nghi ngờ gì nữa,\n"
	.string "{STR_VAR_1} là khách hàng VIP.$"

SmartShopper_Text_OutroMax::
	.string "PHỎNG VẤN: Hừm... Thật đáng kinh\n"
	.string "ngạc.\p"
	.string "Nhưng tại sao HLV ấy lại cần mua\n"
	.string "nhiều đến vậy?\p"
	.string "... ...\p"
	.string "Bí ẩn càng thêm sâu, nhưng thời lượng\n"
	.string "hôm nay đã hết. Hẹn gặp lại trong\l"
	.string "chương trình lần sau!\p"
	.string "Dù vậy, {STR_VAR_1} quả thật là\n"
	.string "một nhân vật bí ẩn...$"

gTVWorldOfMastersText00::
	.string "THẾ GIỚI CỦA CÁC BẬC THẦY\p"
	.string "Xin chào quý khán giả.\p"
	.string "Có lẽ các bạn đã biết một HLV tên\n"
	.string "{STR_VAR_1}.\p"
	.string "{STR_VAR_1} nổi tiếng là bậc thầy\n"
	.string "bắt POKéMON.\p"
	.string "Hành trình tìm kiếm POKéMON của\n"
	.string "{STR_VAR_1} hoàn toàn dựa vào\l"
	.string "việc kiên trì đi bộ dò tìm.\p"
	.string "Trong một ngày đáng nhớ, HLV ấy đã\n"
	.string "đi khoảng {STR_VAR_2} bước.\p"
	.string "Tổng số POKéMON bắt được trong ngày\n"
	.string "hôm đó đạt con số ấn tượng là\l"
	.string "{STR_VAR_3}!$"

gTVWorldOfMastersText01::
	.string "Thành tích đáng nể ấy hẳn có được nhờ\n"
	.string "sự tin tưởng giữa HLV và\l"
	.string "{STR_VAR_1}.$"

gTVWorldOfMastersText02::
	.string "Bậc thầy đã bắt được\n"
	.string "{STR_VAR_3} cuối cùng trong ngày\l"
	.string "ở gần {STR_VAR_2}.\p"
	.string "POKéMON ấy dường như giữ một vị trí\n"
	.string "đặc biệt với tư cách kỷ lục gia.\p"
	.string "Các HLV tài năng hãy thử sức với\n"
	.string "kỷ lục tuyệt vời này.\p"
	.string "Chương trình hôm nay xin kết thúc tại\n"
	.string "đây. Hẹn gặp lại lần sau.$"

gTVTodaysRivalTrainerText00::
	.string "TODAY'S RIVAL HLV!\p"
	.string "Xin chào toàn thể HLV POKéMON!\n"
	.string "Hôm nay mọi người thế nào?\p"
	.string "Như mọi ngày, hôm nay chúng ta sẽ tìm\n"
	.string "hiểu về một đối thủ!$"

gTVTodaysRivalTrainerText07::
	.string "HLV đối thủ hôm nay là\n"
	.string "{STR_VAR_1}, hiện đang ở quanh\l"
	.string "{STR_VAR_3}.\p"
	.string "Cho đến nay, {STR_VAR_1} đã đăng\n"
	.string "ký {STR_VAR_2} POKéMON trong\l"
	.string "POKéDEX.$"

gTVTodaysRivalTrainerText08::
	.string "HLV đối thủ hôm nay là\n"
	.string "{STR_VAR_1}, hiện đang ở trong\l"
	.string "một SECRET BASE.\p"
	.string "Cho đến nay, {STR_VAR_1} đã đăng\n"
	.string "ký {STR_VAR_2} POKéMON trong\l"
	.string "POKéDEX.$"

gTVTodaysRivalTrainerText09::
	.string "HLV đối thủ hôm nay là\n"
	.string "{STR_VAR_1}.\p"
	.string "Cho đến nay, {STR_VAR_1} đã đăng\n"
	.string "ký {STR_VAR_2} POKéMON trong\l"
	.string "POKéDEX.$"

gTVTodaysRivalTrainerText10::
	.string "HLV đối thủ hôm nay là\n"
	.string "{STR_VAR_1}, hiện đang ở trên\l"
	.string "một chuyến phà.\p"
	.string "Cho đến nay, {STR_VAR_1} đã đăng\n"
	.string "ký {STR_VAR_2} POKéMON trong\l"
	.string "POKéDEX.$"

	.string "$"

gTVTodaysRivalTrainerText01::
	.string "Vậy đối thủ của chúng ta có bao nhiêu\n"
	.string "BADGES? Câu trả lời là\l"
	.string "{STR_VAR_1}!$"

gTVTodaysRivalTrainerText02::
	.string "Nhưng đối thủ của chúng ta vẫn chưa\n"
	.string "giành được một BADGE nào!$"

gTVTodaysRivalTrainerText03::
	.string "Đối thủ của chúng ta vẫn chưa giành\n"
	.string "được một BATTLE FRONTIER Symbol nào.$"

gTVTodaysRivalTrainerText04::
	.string "Hãy xem đối thủ của chúng ta có bao\n"
	.string "nhiêu BATTLE FRONTIER Symbols.\p"
	.string "Gold Symbols: {STR_VAR_1}! Silver\n"
	.string "Symbols: {STR_VAR_2}!$"

gTVTodaysRivalTrainerText05::
	.string "Đối thủ của chúng ta đã tích lũy được\n"
	.string "{STR_VAR_1} Battle Point(s) tại\l"
	.string "BATTLE FRONTIER.$"

gTVTodaysRivalTrainerText06::
	.string "Vậy khi so với {STR_VAR_1}, bạn\n"
	.string "thể hiện ra sao?\p"
	.string "Cuộc phiêu lưu vẫn tiếp diễn!\p"
	.string "Hỡi các HLV!\p"
	.string "Hãy cùng tiến bước và luôn vượt lên\n"
	.string "trước các đối thủ!$"

TrendWatcher_Text_Intro::
	.string "DEWFORD TREND-WATCHER NETWORK!\p"
	.string "MC: Khỏe chứ? Chúng tôi sẽ mang đến\n"
	.string "những tin mới nhất về mọi trào lưu đang\l"
	.string "nổi ở DEWFORD.\p"
	.string "Khách mời hôm nay là một bậc lão làng,\n"
	.string "nổi danh là chuyên gia về mọi chuyện ở\l"
	.string "DEWFORD.\p"
	.string "Ông lão: Rất vui được tới đây.\p"
	.string "MC: Vào thẳng vấn đề nhé.\p"
	.string "Theo bác, điều gì đang khiến người dân\n"
	.string "DEWFORD phát cuồng?\p"
	.string "Ông lão: {STR_VAR_1}\n"
	.string "{STR_VAR_2}.\p"
	.string "MC: Bác nói {STR_VAR_1}\n"
	.string "{STR_VAR_2} sao?\p"
	.string "Ông lão: Không.\p"
	.string "{STR_VAR_1} {STR_VAR_2}\n"
	.string "chưa bao giờ nổi tiếng cả.\p"
	.string "Cậu có muốn nghe chuyện đó không?\p"
	.string "MC: Ờ, không. Chúng tôi muốn biết thứ gì\n"
	.string "đang thịnh hành lúc này...$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTaughtMePhrase::
	.string "Ông lão: {STR_VAR_1}\n"
	.string "{STR_VAR_2} là cụm từ mà\l"
	.string "{STR_VAR_3} ở LITTLEROOT đã dạy\l"
	.string "tôi, bảo rằng nó rất thời thượng...$"

TrendWatcher_Text_FemaleTaughtMePhrase::
	.string "Ông lão: {STR_VAR_1}\n"
	.string "{STR_VAR_2} là cụm từ mà\l"
	.string "{STR_VAR_3} ở LITTLEROOT đã dạy\l"
	.string "tôi, bảo rằng nó rất thời thượng...$"

TrendWatcher_Text_PhraseWasHopeless::
	.string "Nhưng hoàn toàn vô vọng.\p"
	.string "Lễ hội {STR_VAR_1}\n"
	.string "{STR_VAR_2}!\p"
	.string "Cuộc thi {STR_VAR_1}\n"
	.string "{STR_VAR_2}!\p"
	.string "Tôi đã cố hết sức truyền bá cho mọi\n"
	.string "người, nhưng...\p"
	.string "Có lẽ phần {STR_VAR_1} không ổn...\p"
	.string "MC: Ờ, xin lỗi bác, nhưng tôi cần nghe về\n"
	.string "thứ đang thịnh hành...$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTellMeBigger::
	.string "Ông lão: {STR_VAR_3}! Làm ơn hãy\n"
	.string "cho tôi biết một thứ lớn hơn cả\l"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_FemaleTellMeBigger::
	.string "Ông lão: {STR_VAR_3}! Làm ơn hãy\n"
	.string "cho tôi biết một thứ lớn hơn cả\l"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_Outro::
	.string "MC: ...Ờ... Vậy là mọi người đã rõ rồi nhé,\n"
	.string "hỡi những tín đồ thời thượng!\p"
	.string "{STR_VAR_1} {STR_VAR_2}...\n"
	.string "ờ... chưa từng trở nên thịnh hành ở\l"
	.string "DEWFORD!\p"
	.string "Tôi hết giờ rồi. Hẹn gặp lại trên sóng!\p"
	.string "Ông lão: {STR_VAR_1}\n"
	.string "{STR_VAR_2}!$"

gTVHoennTreasureInvestigatorsText00::
	.string "HOENN TREASURE INVESTIGATORS!\p"
	.string "Chào mọi người! Gần đây có tìm được\n"
	.string "vật phẩm bí mật nào không?\p"
	.string "Như thường lệ, chúng ta sẽ xem xét\n"
	.string "những lời kể tận mắt về các bí mật khắp\l"
	.string "nơi!\p"
	.string "Hãy bắt đầu bằng một lá thư. Thư viết:\n"
	.string "Phát hiện {STR_VAR_1}!$"

gTVHoennTreasureInvestigatorsText01::
	.string "Chà, chúng ta phải xem lá thư này mới\n"
	.string "được! Tôi sẽ đọc cho mọi người nghe.\p"
	.string "...Kính gửi INVESTIGATORS, chúc mọi\n"
	.string "người luôn mạnh khỏe.\p"
	.string "Gần đây, tôi đã thấy {STR_VAR_2}\n"
	.string "ở đâu đó quanh {STR_VAR_3}.\p"
	.string "HLV ấy đã tìm được vật phẩm\n"
	.string "{STR_VAR_1}. Tôi ghen tị quá.\p"
	.string "...Giỏi lắm, {STR_VAR_2}!\p"
	.string "Quý khán giả, hãy lấy đó làm động lực,\n"
	.string "bật ITEMFINDERS lên và tìm kiếm!\p"
	.string "Tôi sẽ chờ những tin tức thú vị từ tất\n"
	.string "cả các bạn!$"

gTVHoennTreasureInvestigatorsText02::
	.string "Chà, chúng ta phải xem lá thư này mới\n"
	.string "được! Tôi sẽ đọc cho mọi người nghe.\p"
	.string "...Kính gửi INVESTIGATORS, chúc mọi\n"
	.string "người luôn mạnh khỏe.\p"
	.string "Gần đây, tôi đã thấy {STR_VAR_2}\n"
	.string "trên một chuyến phà.\p"
	.string "HLV ấy đã tìm được vật phẩm\n"
	.string "{STR_VAR_1}. Tôi ghen tị quá.\p"
	.string "...Giỏi lắm, {STR_VAR_2}!\p"
	.string "Quý khán giả, hãy lấy đó làm động lực,\n"
	.string "bật ITEMFINDERS lên và tìm kiếm!\p"
	.string "Tôi sẽ chờ những tin tức thú vị từ tất\n"
	.string "cả các bạn!$"

gTVFindThatGamerText00::
	.string "TÌM TAY CHƠI!\p"
	.string "Chào tất cả các tay chơi! Vòng quay\n"
	.string "{STR_VAR_2} của các bạn thế nào\l"
	.string "rồi?\p"
	.string "Như thường lệ, chúng ta sẽ hướng ánh\n"
	.string "đèn vào một HLV hiếm có từng ghé\l"
	.string "thăm GAME CORNER!\p"
	.string "Tay chơi số một hôm nay là...\n"
	.string "{STR_VAR_1}!$"

gTVFindThatGamerText01::
	.string "{STR_VAR_1} đã chơi trò\n"
	.string "{STR_VAR_2} và thắng được con\l"
	.string "số đáng nể là {STR_VAR_3} COINS.\p"
	.string "Khi {STR_VAR_1} tới, chúng ta\n"
	.string "phải bảo đảm có đủ COINS.\p"
	.string "Đó là lời các nhân viên GAME CORNER\n"
	.string "thường lẩm bẩm mỗi khi tay chơi của\l"
	.string "chúng ta nhập cuộc!\p"
	.string "Quý khán giả, nếu đến GAME CORNER chơi\n"
	.string "trò {STR_VAR_2}, tốt nhất hãy\l"
	.string "trông chừng COINS của mình cẩn thận\l"
	.string "như {STR_VAR_1}.\p"
	.string "Chúng tôi đang truyền hình trực tiếp\n"
	.string "từ GAME CORNER, nơi bạn có thể cảm\l"
	.string "nhận sự phấn khích!\p"
	.string "Chương trình hôm nay xin kết thúc tại\n"
	.string "đây!$"

gTVFindThatGamerText02::
	.string "{STR_VAR_1} đã chơi trò\n"
	.string "{STR_VAR_2} và thua mất\l"
	.string "{STR_VAR_3} COINS.\p"
	.string "Mỗi khi {STR_VAR_1} tới, doanh số\n"
	.string "COIN của chúng ta dường như lại tăng.\p"
	.string "Đó là lời các nhân viên GAME CORNER nói\n"
	.string "mỗi khi tay chơi của chúng ta nhập\l"
	.string "cuộc!$"

gTVFindThatGamerText03::
	.string "Quý khán giả, nếu đến GAME CORNER chơi\n"
	.string "trò {STR_VAR_2}, tốt nhất hãy\l"
	.string "trông chừng COINS của mình cẩn thận\l"
	.string "như {STR_VAR_1}.\p"
	.string "Chúng tôi đang truyền hình trực tiếp\n"
	.string "từ GAME CORNER, nơi bạn có thể cảm\l"
	.string "nhận sự phấn khích!\p"
	.string "Chương trình hôm nay xin kết thúc tại\n"
	.string "đây!$"

gTVBreakingNewsText00::
	.string "TIN NÓNG TRÊN TV!$"

gTVBreakingNewsText01::
	.string "{STR_VAR_2} quý hiếm đã bị\n"
	.string "{STR_VAR_1} bắt!\p"
	.string "Chúng tôi đang truyền hình trực tiếp\n"
	.string "từ khu vực gần {STR_VAR_3}!\p"
	.string "Trước đó, chính tại đây,\n"
	.string "{STR_VAR_1} đã bắt thành công\l"
	.string "một {STR_VAR_2} quý hiếm!$"

gTVBreakingNewsText02::
	.string "Khi {STR_VAR_1} chạm trán\n"
	.string "{STR_VAR_2} quý hiếm, HLV ấy\l"
	.string "đã tung POKéMON {STR_VAR_3} ra\l"
	.string "trận.$"

gTVBreakingNewsText03::
	.string "Trong trận đấu, HLV đã ném tổng\n"
	.string "cộng {STR_VAR_1} POKé BALLS.\p"
	.string "Cuối cùng, POKéMON quý hiếm đã bị bắt\n"
	.string "bằng {STR_VAR_2} được dùng sau\l"
	.string "cùng.$"

gTVBreakingNewsText04::
	.string "Ngay khoảnh khắc đó, tiếng reo gào\n"
	.string "chiến thắng của {STR_VAR_1} vang\l"
	.string "vọng khắp {STR_VAR_2}.\p"
	.string "Phải nói rằng tôi hơi ghen tị với\n"
	.string "{STR_VAR_1}. Tôi cũng muốn reo\l"
	.string "thật lớn.\p"
	.string "...Buổi truyền hình trực tiếp từ khung\n"
	.string "cảnh hân hoan xin kết thúc tại đây!$"

gTVBreakingNewsText05::
	.string "{STR_VAR_1} không thể bắt được\n"
	.string "{STR_VAR_2} quý hiếm!\p"
	.string "Chúng tôi đang truyền hình trực tiếp\n"
	.string "từ khu vực gần {STR_VAR_3}!\p"
	.string "Chính tại đây, {STR_VAR_1} đã\n"
	.string "không thể bắt được một\l"
	.string "{STR_VAR_2} quý hiếm!$"

gTVBreakingNewsText06::
	.string "Khi {STR_VAR_1} chạm trán\n"
	.string "{STR_VAR_2} quý hiếm, HLV ấy\l"
	.string "đã tung POKéMON {STR_VAR_3} ra\l"
	.string "trận.$"

gTVBreakingNewsText07::
	.string "HLV đã cho {STR_VAR_2} sử\n"
	.string "dụng chiêu {STR_VAR_1}.\p"
	.string "Ngoài ý muốn, HLV ấy đã khiến\n"
	.string "POKéMON quý hiếm ngất đi...$"

gTVBreakingNewsText12::
	.string "Tuy nhiên, {STR_VAR_1} đã hoảng\n"
	.string "hốt khi trông thấy {STR_VAR_2}\l"
	.string "quý hiếm.\p"
	.string "Trong lúc rối trí, HLV ấy đã ra lệnh\n"
	.string "cho {STR_VAR_3} tấn công.\p"
	.string "Ngoài ý muốn, HLV ấy đã khiến\n"
	.string "POKéMON quý hiếm ngất đi.$"

gTVBreakingNewsText08::
	.string "Ngay khoảnh khắc đó, tiếng hét thất\n"
	.string "vọng của {STR_VAR_1} vang vọng\l"
	.string "khắp {STR_VAR_2}...$"

gTVBreakingNewsText09::
	.string "Tuy nhiên, có vẻ {STR_VAR_1} đã\n"
	.string "hết POKé BALLS.\p"
	.string "HLV ấy buộc phải dừng trận đấu với\n"
	.string "{STR_VAR_2} quý hiếm.\p"
	.string "Ngay khoảnh khắc đó, tiếng hét thất\n"
	.string "vọng của {STR_VAR_1} vang vọng\l"
	.string "khắp {STR_VAR_3}...$"

gTVBreakingNewsText10::
	.string "Tuy nhiên, {STR_VAR_2} đã bất\n"
	.string "ngờ bỏ chạy.\p"
	.string "Ngay khoảnh khắc đó, tiếng hét thất\n"
	.string "vọng của {STR_VAR_1} vang vọng\l"
	.string "khắp {STR_VAR_3}...$"

gTVBreakingNewsText11::
	.string "Phải nói rằng tôi rất thông cảm với\n"
	.string "{STR_VAR_1}. Chuyện này khiến\l"
	.string "tôi cũng muốn hét lên.\p"
	.string "...Buổi truyền hình trực tiếp từ khung\n"
	.string "cảnh u sầu xin kết thúc tại đây!$"

gTVSecretBaseVisitText00::
	.string "Xin chào mọi người! Lại đến giờ của\n"
	.string "SECRET BASE VISIT.\p"
	.string "Hôm nay, chúng ta sẽ ghé thăm SECRET\n"
	.string "BASE của {STR_VAR_1}.\p"
	.string "{STR_VAR_1} đã trang trí SECRET\n"
	.string "BASE theo phong cách riêng như thế\l"
	.string "nào?\p"
	.string "Hãy cùng tìm hiểu! ... ... ... ... ... ...$"

gTVSecretBaseVisitText01::
	.string "Ồ! Tuyệt diệu làm sao!\p"
	.string "{STR_VAR_2} này... Thật không\n"
	.string "ngờ lại có thể thấy nó ở đây!$"

gTVSecretBaseVisitText02::
	.string "Ồ! Thật phi thường!\p"
	.string "Không có lấy một món đồ nội thất hay\n"
	.string "vật trang trí nào!\p"
	.string "Người thường đừng mong bắt chước\n"
	.string "được tuyên ngôn táo bạo này!\p"
	.string "Đơn giản, nhưng tràn ngập, phải, tràn\n"
	.string "ngập nét hoang dã!\p"
	.string "Xin ngả mũ trước {STR_VAR_1}.\n"
	.string "Chỉ có thể là bạn!$"

gTVSecretBaseVisitText03::
	.string "Ồ! Tôi hiểu rồi! Tôi đã nhìn thấu tất cả!\p"
	.string "Việc đặt {STR_VAR_2} ở đây... Nó\n"
	.string "truyền tải một thông điệp đầy hiệu quả!$"

gTVSecretBaseVisitText04::
	.string "Ồ! Tôi hiểu rồi! Tôi đã nhìn thấu tất cả!\p"
	.string "Không gian này được cố ý để trống,\n"
	.string "không bày bất kỳ vật trang trí nào!\p"
	.string "Nó truyền tải một thông điệp đầy hiệu\n"
	.string "quả!$"

gTVSecretBaseVisitText05::
	.string "Chà!\p"
	.string "Sự kết hợp giữa {STR_VAR_2} và\n"
	.string "{STR_VAR_3}!\p"
	.string "Nếu có một sự kết hợp trong mơ thì\n"
	.string "chính là đây!$"

gTVSecretBaseVisitText06::
	.string "Chà!\p"
	.string "Cách đặt {STR_VAR_2} ngay tại vị\n"
	.string "trí này...\p"
	.string "Sự hiện diện của nó bao trùm toàn bộ\n"
	.string "SECRET BASE!$"

gTVSecretBaseVisitText07::
	.string "Chà!\p"
	.string "Ở đây chẳng bày thứ gì cả.\p"
	.string "Chính khoảng trống này tạo nên ấn tượng\n"
	.string "cho toàn bộ SECRET BASE.$"

gTVSecretBaseVisitText08::
	.string "Ồ! {STR_VAR_1} tới rồi! Hãy thách\n"
	.string "đấu HLV ấy!\p"
	.string "... ... ... ... ... ... ... ... ... ... ... ...$"

gTVSecretBaseVisitText09::
	.string "Haizz... Phải công nhận\n"
	.string "{STR_VAR_1} rất xuất sắc.\p"
	.string "Các POKéMON của HLV ấy thật sự\n"
	.string "xứng đáng với danh hiệu CHAMPION.\p"
	.string "Chúng đã chứng minh đầy thuyết phục\n"
	.string "bản lĩnh của HLV\l"
	.string "{STR_VAR_1}.\p"
	.string "Việc {STR_VAR_2} biết chiêu\n"
	.string "{STR_VAR_3}...\p"
	.string "Điều đó cho thấy {STR_VAR_1} là\n"
	.string "một HLV như thế nào.\p"
	.string "Quả là một bài học đáng giá!$"

gTVSecretBaseVisitText10::
	.string "Ái chà! Phải công nhận\n"
	.string "{STR_VAR_1} rất xuất sắc.\p"
	.string "Các POKéMON của HLV ấy mạnh khủng\n"
	.string "khiếp!\p"
	.string "Chúng đã chứng minh đầy thuyết phục\n"
	.string "sự bền bỉ của HLV\l"
	.string "{STR_VAR_1}.\p"
	.string "Việc {STR_VAR_2} biết chiêu\n"
	.string "{STR_VAR_3}...\p"
	.string "Điều đó cho thấy {STR_VAR_1} là\n"
	.string "một HLV như thế nào.\p"
	.string "Quả là một bài học đáng giá!$"

gTVSecretBaseVisitText11::
	.string "Chà! Phải công nhận {STR_VAR_1}\n"
	.string "rất xuất sắc.\p"
	.string "Các POKéMON của HLV ấy rõ ràng đã\n"
	.string "được nuôi dưỡng rất cân bằng.\p"
	.string "Chúng đã chứng minh đầy thuyết phục\n"
	.string "sự chu đáo của HLV\l"
	.string "{STR_VAR_1}.\p"
	.string "Việc {STR_VAR_2} biết chiêu\n"
	.string "{STR_VAR_3}...\p"
	.string "Điều đó cho thấy {STR_VAR_1} là\n"
	.string "một HLV như thế nào.\p"
	.string "Quả là một bài học đáng giá!$"

gTVSecretBaseVisitText12::
	.string "Chà chà! Phải công nhận\n"
	.string "{STR_VAR_1} rất xuất sắc.\p"
	.string "Các POKéMON của HLV ấy cho thấy\n"
	.string "tiềm năng phát triển to lớn trong\l"
	.string "tương lai.\p"
	.string "Chúng đại diện cho những hy vọng và\n"
	.string "ước mơ của {STR_VAR_1}.\p"
	.string "Việc {STR_VAR_2} biết chiêu\n"
	.string "{STR_VAR_3}...\p"
	.string "Điều đó cho thấy {STR_VAR_1} là\n"
	.string "một HLV như thế nào.\p"
	.string "Quả là một bài học đáng giá!$"

gTVSecretBaseVisitText13::
	.string "Phải nói rằng đây quả là một SECRET\n"
	.string "BASE tuyệt vời!\p"
	.string "Quý khán giả, nếu có cơ hội, hãy ghé\n"
	.string "thăm SECRET BASE của\l"
	.string "{STR_VAR_1}.\p"
	.string "Hẹn gặp lại lần sau, xin kính chào!$"

gTVPokemonLotteryWinnerFlashReportText00::
	.string "Thật hào hứng! Thật kịch tính!\p"
	.string "Đây là POKéMON LOTTERY WINNER FLASH\n"
	.string "REPORT!\p"
	.string "Xin chào! Chúng tôi đang truyền hình\n"
	.string "trực tiếp từ POKéMON LOTTERY CORNER ở\l"
	.string "tầng trệt của LILYCOVE DEPARTMENT\l"
	.string "STORE!\p"
	.string "Như thường lệ, hôm nay lại xuất hiện\n"
	.string "thêm một HLV may mắn!\p"
	.string "Tên của HLV ấy là...\n"
	.string "{STR_VAR_1}!\p"
	.string "{STR_VAR_1} đã trúng giải\n"
	.string "{STR_VAR_2} và mang về\l"
	.string "{STR_VAR_3}!\p"
	.string "{STR_VAR_1}! Xin chúc mừng!\p"
	.string "Quý khán giả, đừng chỉ đứng xem, hãy\n"
	.string "tham gia ngay!\p"
	.string "Tất cả chúng tôi tại LILYCOVE\n"
	.string "DEPARTMENT STORE mong chờ lần ghé\l"
	.string "thăm tiếp theo của bạn!\p"
	.string "Chương trình truyền hình trực tiếp từ\n"
	.string "LILYCOVE DEPARTMENT STORE, nơi có bộ\l"
	.string "sưu tập hàng hóa phong phú nhất toàn\l"
	.string "HOENN, xin kết thúc tại đây!$"

gTVThePokemonBattleSeminarText00::
	.string "HỘI THẢO POKéMON trận đấu!\p"
	.string "Chúng ta phân tích các trận đấu để xem\n"
	.string "có thể học hỏi được điều gì từ người\l"
	.string "khác.\p"
	.string "Tình huống nghiên cứu hôm nay là trận\n"
	.string "đấu của {STR_VAR_1}.\p"
	.string "{STR_VAR_2} của\n"
	.string "{STR_VAR_1} đang chiến đấu với\l"
	.string "một {STR_VAR_3}...$"

gTVThePokemonBattleSeminarText01::
	.string "Và nó đã dùng chiêu {STR_VAR_3}\n"
	.string "lên {STR_VAR_2}...\p"
	.string "Hừm... {STR_VAR_1}! Làm như vậy\n"
	.string "là sai rồi!$"

gTVThePokemonBattleSeminarText02::
	.string "Ngoài chiêu thức tai hại đó,\n"
	.string "{STR_VAR_1} của HLV còn biết$"

gTVThePokemonBattleSeminarText03::
	.string "các chiêu {STR_VAR_1},\n"
	.string "{STR_VAR_2} và\l"
	.string "{STR_VAR_3}.$"

gTVThePokemonBattleSeminarText04::
	.string "các chiêu {STR_VAR_1} và\n"
	.string "{STR_VAR_2}.$"

gTVThePokemonBattleSeminarText05::
	.string "chiêu {STR_VAR_2}.$"

gTVThePokemonBattleSeminarText06::
	.string "Vậy trong tình huống này, HLV đáng\n"
	.string "lẽ nên dùng gì?\p"
	.string "... ... ... ... ... ... Chiêu {STR_VAR_1}!\p"
	.string "Chiêu {STR_VAR_1} chắc chắn sẽ\n"
	.string "hiệu quả hơn {STR_VAR_2}.\p"
	.string "Quý khán giả, hãy rút kinh nghiệm từ\n"
	.string "tình huống này và chiến đấu thật khôn\l"
	.string "ngoan!\p"
	.string "Hẹn gặp lại lần sau, xin kính chào!$"

gTVTrainerFanClubText00::
	.string "Tất cả cùng hô nào! TRAINER FAN CLUB!\p"
	.string "MC: Mọi người đang sung chứ? Hôm nay,\n"
	.string "chúng tôi đã tập hợp những người hâm\l"
	.string "mộ HLV siêu nổi tiếng\l"
	.string "{STR_VAR_1}!\p"
	.string "KHÁN GIẢ: Wrooooooaaaaah!\p"
	.string "KHÁN GIẢ: {STR_VAR_1}!\p"
	.string "MC: Mọi người! Các bạn thấy\n"
	.string "{STR_VAR_1} thế nào?!\p"
	.string "KHÁN GIẢ: Chúng tôi yêu {STR_VAR_1}!\p"
	.string "MC: Các bạn yêu điều gì ở\n"
	.string "{STR_VAR_1}?!$"

gTVTrainerFanClubText01::
	.string "KHÁN GIẢ: Ném POKé BALLS cực ngầu!$"

gTVTrainerFanClubText02::
	.string "KHÁN GIẢ: Dáng chạy đáng yêu!$"

gTVTrainerFanClubText03::
	.string "KHÁN GIẢ: Cách HLV ấy trở nên mạnh mẽ\n"
	.string "khi gặp khó khăn!$"

gTVTrainerFanClubText04::
	.string "KHÁN GIẢ: Kiến thức của HLV ấy về\n"
	.string "POKéMON!$"

gTVTrainerFanClubText05::
	.string "KHÁN GIẢ: Sự dịu dàng của HLV ấy dành\n"
	.string "cho mọi POKéMON!$"

gTVTrainerFanClubText06::
	.string "KHÁN GIẢ: Kỹ thuật điều khiển BIKE\n"
	.string "vời của HLV ấy!$"

gTVTrainerFanClubText07::
	.string "KHÁN GIẢ: Cách mua vật phẩm đầy ấn\n"
	.string "tượng của HLV ấy!$"

gTVTrainerFanClubText08::
	.string "KHÁN GIẢ: Cách HLV ấy đặt biệt danh\n"
	.string "thật duyên cho POKéMON!$"

gTVTrainerFanClubText09::
	.string "KHÁN GIẢ: Cách trang trí SECRET BASE\n"
	.string "cực chất của HLV!$"

gTVTrainerFanClubText10::
	.string "KHÁN GIẢ: Cách dùng TMs táo bạo của\n"
	.string "HLV!$"

gTVTrainerFanClubText11::
	.string "MC: Như các bạn vừa thấy,\n"
	.string "{STR_VAR_1} đang cực kỳ nổi!\l"
	.string "Nóng đến mức chạm vào là bỏng tay, ui\l"
	.string "da!\p"
	.string "Người hâm mộ {STR_VAR_1} có một\n"
	.string "khẩu hiệu đặc biệt!\p"
	.string "MC: Khi tôi hô {STR_VAR_1}, các\n"
	.string "bạn đáp...\p"
	.string "KHÁN GIẢ: {STR_VAR_2}!\p"
	.string "KHÁN GIẢ: {STR_VAR_3}!\p"
	.string "KHÁN GIẢ: {STR_VAR_2}!\p"
	.string "KHÁN GIẢ: {STR_VAR_3}!\p"
	.string "MC: Đúng vậy, khi ai đó nói\n"
	.string "“{STR_VAR_1}”...\p"
	.string "Hãy đáp lại “{STR_VAR_2}\n"
	.string "{STR_VAR_3}!”\p"
	.string "Nghe thật độc đáo! Tôi hiểu vì sao mọi\n"
	.string "người lại hâm mộ\l"
	.string "{STR_VAR_1} rồi!\p"
	.string "Nào, bạn đang ngồi trước TV cũng tham\n"
	.string "gia đi! Tất cả cùng hô nào!\p"
	.string "MC: Khi tôi hô {STR_VAR_1}, các\n"
	.string "bạn đáp...\p"
	.string "KHÁN GIẢ: {STR_VAR_2}!\p"
	.string "KHÁN GIẢ: {STR_VAR_3}!\p"
	.string "KHÁN GIẢ: {STR_VAR_2}!\p"
	.string "KHÁN GIẢ: {STR_VAR_3}!\p"
	.string "MC: Cảm ơn những người hâm mộ\n"
	.string "{STR_VAR_1} đã tham gia! Chương\l"
	.string "trình đến đây là hết! Hẹn gặp lại!\p"
	.string "MC: Khi tôi hô {STR_VAR_1}, các\n"
	.string "bạn đáp...\p"
	.string "KHÁN GIẢ: {STR_VAR_2}!\p"
	.string "KHÁN GIẢ: {STR_VAR_3}!$"

TVSpotTheCuties_Text_Intro::
	.string "TÌM POKéMON ĐÁNG YÊU!\n"
	.string "POKéMON ĐEO RIBBONS!\p"
	.string "Xin chào, các khán giả thân yêu!\p"
	.string "Tôi biết các bạn cũng sẽ đồng ý rằng\n"
	.string "một POKéMON đeo RIBBONS trông thật\l"
	.string "tuyệt mỹ!\p"
	.string "Hôm nay, tôi muốn giới thiệu một\n"
	.string "POKéMON đáng yêu mà tôi bắt gặp khi\l"
	.string "đang dạo phố.\p"
	.string "POKéMON xinh đẹp được giới thiệu hôm\n"
	.string "nay là {STR_VAR_2} của\l"
	.string "{STR_VAR_1}.$"

TVSpotTheCuties_Text_RibbonsLow::
	.string "Số RIBBONS mà {STR_VAR_2} đeo là\n"
	.string "{STR_VAR_3}.\p"
	.string "Chỉ vậy cũng đủ thấy {STR_VAR_1}\n"
	.string "yêu quý POKéMON này đến nhường nào.$"

TVSpotTheCuties_Text_RibbonsMid::
	.string "{STR_VAR_2} đeo tới\n"
	.string "{STR_VAR_3} RIBBONS tuyệt đẹp!\p"
	.string "Điều đó cho thấy {STR_VAR_1} tận\n"
	.string "tâm với POKéMON này đến mức nào!$"

TVSpotTheCuties_Text_RibbonsHigh::
	.string "{STR_VAR_2} đeo tới\n"
	.string "{STR_VAR_3} RIBBONS đáng kinh\l"
	.string "ngạc!\p"
	.string "Điều đó cho thấy {STR_VAR_1} tận\n"
	.string "tụy với việc sưu tầm đến mức nào!$"

TVSpotTheCuties_Text_RibbonIntro::
	.string "Hãy cùng ngắm kỹ vô số RIBBONS mà\n"
	.string "{STR_VAR_2} đang đeo.$"

TVSpotTheCuties_Text_RibbonChampion::
	.string "CHAMPION RIBBON trông đặc biệt hợp.\p"
	.string "{STR_VAR_2} đã nhận được nó khi\n"
	.string "bước vào HALL OF FAME.\p"
	.string "Quả thực nó làm nổi bật lòng dũng cảm\n"
	.string "của {STR_VAR_2}.\p"
	.string "{STR_VAR_2} cùng CHAMP RIBBON!\n"
	.string "Một sự kết hợp siêu hiệu quả!$"

TVSpotTheCuties_Text_RibbonCool::
	.string "COOL RIBBON trông đặc biệt hợp.\p"
	.string "{STR_VAR_2} đã nhận được nó\n"
	.string "nhờ chiến thắng một COOL CONTEST.\p"
	.string "Quả thực nó làm nổi bật vẻ sành điệu\n"
	.string "của {STR_VAR_2}.\p"
	.string "{STR_VAR_2} cùng COOL RIBBON!\n"
	.string "Một sự kết hợp siêu hiệu quả!$"

TVSpotTheCuties_Text_RibbonBeauty::
	.string "BEAUTY RIBBON trông đặc biệt hợp.\p"
	.string "{STR_VAR_2} đã nhận được nó\n"
	.string "nhờ chiến thắng một BEAUTY CONTEST.\p"
	.string "Quả thực nó làm nổi bật vẻ đẹp của\n"
	.string "{STR_VAR_2}.\p"
	.string "{STR_VAR_2} cùng BEAUTY RIBBON!\n"
	.string "Một sự kết hợp siêu hiệu quả!$"

TVSpotTheCuties_Text_RibbonCute::
	.string "CUTE RIBBON trông đặc biệt hợp.\p"
	.string "{STR_VAR_2} đã nhận được nó\n"
	.string "nhờ chiến thắng một CUTE CONTEST.\p"
	.string "Quả thực nó làm nổi bật vẻ đáng yêu của\n"
	.string "{STR_VAR_2}.\p"
	.string "{STR_VAR_2} cùng CUTE RIBBON!\n"
	.string "Một sự kết hợp siêu hiệu quả!$"

TVSpotTheCuties_Text_RibbonSmart::
	.string "SMART RIBBON trông đặc biệt hợp.\p"
	.string "{STR_VAR_2} đã nhận được nó\n"
	.string "nhờ chiến thắng một SMART CONTEST.\p"
	.string "Quả thực nó làm nổi bật sự thông minh\n"
	.string "của {STR_VAR_2}.\p"
	.string "{STR_VAR_2} cùng SMART RIBBON!\n"
	.string "Một sự kết hợp siêu hiệu quả!$"

TVSpotTheCuties_Text_RibbonTough::
	.string "TOUGH RIBBON trông đặc biệt hợp.\p"
	.string "{STR_VAR_2} đã nhận được nó\n"
	.string "nhờ chiến thắng một TOUGH CONTEST.\p"
	.string "Quả thực nó làm nổi bật vẻ cứng cỏi của\n"
	.string "{STR_VAR_2}.\p"
	.string "{STR_VAR_2} cùng TOUGH RIBBON!\n"
	.string "Một sự kết hợp siêu hiệu quả!$"

TVSpotTheCuties_Text_RibbonWinning::
	.string "WINNING RIBBON trông đặc biệt hợp.\p"
	.string "{STR_VAR_2} đã nhận được nó\n"
	.string "nhờ những thành tích tại BATTLE\l"
	.string "TOWER.\p"
	.string "Quả thực nó làm nổi bật sức mạnh của\n"
	.string "{STR_VAR_2}.\p"
	.string "{STR_VAR_2} cùng WINNING\n"
	.string "RIBBON! Một sự kết hợp siêu hiệu quả!$"

TVSpotTheCuties_Text_RibbonVictory::
	.string "VICTORY RIBBON trông đặc biệt hợp.\p"
	.string "{STR_VAR_2} đã nhận được nó\n"
	.string "nhờ những thành tích tại BATTLE\l"
	.string "TOWER.\p"
	.string "Quả thực nó làm nổi bật sức mạnh phi\n"
	.string "thường của {STR_VAR_2}.\p"
	.string "{STR_VAR_2} cùng VICTORY\n"
	.string "RIBBON! Một sự kết hợp siêu hiệu quả!$"

TVSpotTheCuties_Text_RibbonArtist::
	.string "ARTIST RIBBON trông đặc biệt hợp.\p"
	.string "{STR_VAR_2} đã nhận được nó\n"
	.string "nhờ làm mẫu cho một họa sĩ.\p"
	.string "Quả thực nó làm nổi bật sức hút của một\n"
	.string "ngôi sao nhạc pop ở {STR_VAR_2}.\p"
	.string "{STR_VAR_2} cùng ARTIST RIBBON!\n"
	.string "Một sự kết hợp siêu hiệu quả!$"

TVSpotTheCuties_Text_RibbonEffort::
	.string "Hard Worker RIBBON trông đặc biệt hợp.\p"
	.string "{STR_VAR_2} đã nhận được nó\n"
	.string "nhờ tinh thần làm việc đặc biệt chăm\l"
	.string "chỉ.\p"
	.string "Quả thực nó làm nổi bật quyết tâm của\n"
	.string "{STR_VAR_2}.\p"
	.string "{STR_VAR_2} cùng Hard Worker\n"
	.string "RIBBON! Một sự kết hợp siêu hiệu quả!$"

TVSpotTheCuties_Text_Outro::
	.string "Haiz...\p"
	.string "RIBBONS và POKéMON... Chúng thật là một\n"
	.string "cặp hoàn hảo!\p"
	.string "Trước khi ngất ngây, tôi xin chào tạm\n"
	.string "biệt tất cả các bạn!$"

gTVPokemonNewsBattleFrontierText00::
	.string "Xin chào! Đã đến giờ phát POKéMON NEWS.\p"
	.string "Chúng tôi có một tin đáng mừng từ\n"
	.string "BATTLE FRONTIER.$"

gTVPokemonNewsBattleFrontierText01::
	.string "HLV {STR_VAR_1} đã lập kỷ\n"
	.string "lục mới với chuỗi {STR_VAR_2}\l"
	.string "trận thắng liên tiếp trong thử thách\l"
	.string "SINGLE BATTLE ROOM của BATTLE TOWER.\p"
	.string "Xin chúc mừng {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText02::
	.string "HLV {STR_VAR_1} đã lập kỷ\n"
	.string "lục mới với chuỗi {STR_VAR_2}\l"
	.string "trận thắng liên tiếp trong thử thách\l"
	.string "DOUBLE BATTLE ROOM của BATTLE TOWER.\p"
	.string "Xin chúc mừng {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText03::
	.string "HLV {STR_VAR_1} đã lập kỷ\n"
	.string "lục mới với chuỗi {STR_VAR_2}\l"
	.string "trận thắng liên tiếp trong thử thách\l"
	.string "MULTI BATTLE ROOM của BATTLE TOWER.\p"
	.string "Xin chúc mừng {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText04::
	.string "HLV {STR_VAR_1} đã lập kỷ\n"
	.string "lục mới với chuỗi {STR_VAR_2}\l"
	.string "trận thắng liên tiếp trong thử thách\l"
	.string "LINK MULTI BATTLE ROOM của BATTLE\l"
	.string "TOWER.\p"
	.string "Xin chúc mừng {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText05::
	.string "HLV {STR_VAR_1} đã lập kỷ\n"
	.string "lục mới với chuỗi {STR_VAR_2}\l"
	.string "chức vô địch liên tiếp khi tranh tài tại\l"
	.string "các giải SINGLE BATTLE của BATTLE\l"
	.string "DOME.\p"
	.string "Xin chúc mừng {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText06::
	.string "HLV {STR_VAR_1} đã lập kỷ\n"
	.string "lục mới với chuỗi {STR_VAR_2}\l"
	.string "chức vô địch liên tiếp khi tranh tài tại\l"
	.string "các giải DOUBLE BATTLE của BATTLE\l"
	.string "DOME.\p"
	.string "Xin chúc mừng {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText07::
	.string "HLV {STR_VAR_1} đã lập kỷ\n"
	.string "lục mới với chuỗi {STR_VAR_2}\l"
	.string "trận thắng liên tiếp trong thử thách\l"
	.string "Battle Swap Single của BATTLE FACTORY.\p"
	.string "Xin chúc mừng {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText08::
	.string "HLV {STR_VAR_1} đã lập kỷ\n"
	.string "lục mới với chuỗi {STR_VAR_2}\l"
	.string "trận thắng liên tiếp trong thử thách\l"
	.string "Battle Swap Double của BATTLE FACTORY.\p"
	.string "Xin chúc mừng {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText09::
	.string "HLV {STR_VAR_1} đã lập kỷ\n"
	.string "lục mới khi vượt qua {STR_VAR_2}\l"
	.string "phòng trong thử thách Battle Choice\l"
	.string "của BATTLE PIKE.\p"
	.string "Xin chúc mừng {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText10::
	.string "HLV {STR_VAR_1} đã lập kỷ\n"
	.string "lục mới với chuỗi {STR_VAR_2}\l"
	.string "trận thắng liên tiếp khi tranh tài tại\l"
	.string "Set KO Tournaments của BATTLE ARENA.\p"
	.string "Xin chúc mừng {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText11::
	.string "HLV {STR_VAR_1} đã lập kỷ\n"
	.string "lục mới với chuỗi {STR_VAR_2}\l"
	.string "trận thắng liên tiếp trong thử thách\l"
	.string "SINGLE BATTLE HALL của BATTLE PALACE.\p"
	.string "Xin chúc mừng {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText12::
	.string "HLV {STR_VAR_1} đã lập kỷ\n"
	.string "lục mới với chuỗi {STR_VAR_2}\l"
	.string "trận thắng liên tiếp trong thử thách\l"
	.string "DOUBLE BATTLE HALL của BATTLE PALACE.\p"
	.string "Xin chúc mừng {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText13::
	.string "HLV {STR_VAR_1} đã lập kỷ\n"
	.string "lục mới khi vượt qua {STR_VAR_2}\l"
	.string "tầng trong thử thách Battle Quest của\l"
	.string "BATTLE PYRAMID.\p"
	.string "Xin chúc mừng {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText14::
	.string "Và cả ba POKéMON, {STR_VAR_1},\n"
	.string "{STR_VAR_2} và\l"
	.string "{STR_VAR_3}!\p"
	.string "Xin chúc mừng màn trình diễn phá kỷ lục\n"
	.string "của các bạn!$"

gTVPokemonNewsBattleFrontierText15::
	.string "Và cả hai POKéMON, {STR_VAR_1} và\n"
	.string "{STR_VAR_2}!\p"
	.string "Xin chúc mừng màn trình diễn phá kỷ lục\n"
	.string "của các bạn!$"

gTVPokemonNewsBattleFrontierText16::
	.string "Và bốn POKéMON: {STR_VAR_1}!\p"
	.string "{STR_VAR_2}!\p"
	.string "{STR_VAR_3}!$"

gTVPokemonNewsBattleFrontierText17::
	.string "Và {STR_VAR_1}!\p"
	.string "Xin chúc mừng màn trình diễn phá kỷ lục\n"
	.string "của các bạn!$"

gTVPokemonNewsBattleFrontierText18::
	.string "Hãy cùng mong chờ thêm nhiều thành\n"
	.string "tích lập kỷ lục từ {STR_VAR_1} và\l"
	.string "những POKéMON trung thành!\p"
	.string "POKéMON NEWS xin kết thúc tại đây!$"

gTVWhatsNo1InHoennTodayText00::
	.string "AI LÀ SỐ 1 HOENN HÔM NAY?\p"
	.string "Vâng, lại đến giờ rồi!\p"
	.string "Xin chào quý khán giả! Các bạn có đang\n"
	.string "cố gắng hết sức trong mọi việc không?\p"
	.string "Hãy cùng xem HLV nào đã thể hiện\n"
	.string "xuất sắc nhất hôm nay!\p"
	.string "HLV số 1 hôm nay không ai khác\n"
	.string "chính là {STR_VAR_1}!$"

gTVWhatsNo1InHoennTodayText01::
	.string "Chỉ trong một ngày, {STR_VAR_1}\n"
	.string "đã quay SLOTS tại GAME CORNER\l"
	.string "{STR_VAR_2} lần.\p"
	.string "Trong lúc chơi, người ta nghe thấy\n"
	.string "{STR_VAR_1} lẩm bẩm: “Với mình,\l"
	.string "mấy vòng quay còn chẳng nhúc nhích...”\l"
	.string "Thật thú vị, phải không?$"

gTVWhatsNo1InHoennTodayText02::
	.string "Chỉ trong một ngày, {STR_VAR_1}\n"
	.string "đã chơi ROULETTE tại GAME CORNER\l"
	.string "{STR_VAR_2} lần.\p"
	.string "Trong lúc chơi, {STR_VAR_1} đã\n"
	.string "hét lên: “Cứ để những quả bóng quyết\l"
	.string "định!”\p"
	.string "Ánh mắt của HLV tập trung cao độ,\n"
	.string "gương mặt đầy vẻ chăm chú.$"

gTVWhatsNo1InHoennTodayText03::
	.string "Chỉ trong một ngày, {STR_VAR_1}\n"
	.string "đã chiến đấu với POKéMON hoang dã\l"
	.string "{STR_VAR_2} lần!\p"
	.string "Có vẻ các POKéMON của\n"
	.string "{STR_VAR_1} đã mạnh lên vượt\l"
	.string "bậc.\p"
	.string "Chúng dường như luôn háo hức chiến\n"
	.string "đấu ở bất kỳ đâu, bất kỳ lúc nào và\l"
	.string "bằng mọi cách!$"

gTVWhatsNo1InHoennTodayText04::
	.string "Chỉ trong một ngày, {STR_VAR_1}\n"
	.string "đã xoay BERRY BLENDER\l"
	.string "{STR_VAR_2} lần!\p"
	.string "Đến cuối, ngay cả {STR_VAR_1}\n"
	.string "cũng có vẻ chóng mặt.\p"
	.string "HLV lảo đảo chẳng khác nào một\n"
	.string "SPINDA!$"

gTVWhatsNo1InHoennTodayText05::
	.string "Chỉ trong một ngày, {STR_VAR_1}\n"
	.string "đã trồng {STR_VAR_2} BERRIES!\p"
	.string "Kết quả là quần áo của\n"
	.string "{STR_VAR_1} lấm lem đất cát.\p"
	.string "Vô số hoa đã nở rộ tại những nơi\n"
	.string "HLV gieo trồng.\p"
	.string "Người ta nói những bông hoa ấy có thể\n"
	.string "xoa dịu lòng người.$"

gTVWhatsNo1InHoennTodayText06::
	.string "Chỉ trong một ngày, {STR_VAR_1}\n"
	.string "đã hái {STR_VAR_2} BERRIES!\p"
	.string "TÚI ĐỒ của {STR_VAR_1} đầy ắp\n"
	.string "BERRIES đến mức sau đó HLV đi lại\l"
	.string "cũng khó khăn!$"

gTVWhatsNo1InHoennTodayText07::
	.string "Chỉ trong một ngày, {STR_VAR_1}\n"
	.string "đã giành được {STR_VAR_2}\l"
	.string "Battle Points!\p"
	.string "Sau đó, người ta thấy\n"
	.string "{STR_VAR_1} phân vân không biết\l"
	.string "nên đổi Battle Points lấy một món đồ\l"
	.string "cực chất hay một vật trang trí nội thất\l"
	.string "độc đáo.\p"
	.string "Theo ghi nhận, HLV vừa cân nhắc\n"
	.string "các lựa chọn vừa cười tủm tỉm.$"

gTVWhatsNo1InHoennTodayText08::
	.string "Quả là đáng nể!\p"
	.string "{STR_VAR_1}! Bạn chính là\n"
	.string "HLV số 1 hôm nay!\p"
	.string "Quý khán giả, hãy lấy {STR_VAR_1}\n"
	.string "làm động lực! Các bạn cũng có thể trở\l"
	.string "thành số 1 mỗi ngày!$"

TVSecretBaseSecrets_Text_Intro::
	.string "SECRET BASE SECRETS!\p"
	.string "Các HLV làm gì trong chốn riêng\n"
	.string "tư của SECRET BASES?\p"
	.string "Hôm nay, chúng ta sẽ điều tra SECRET\n"
	.string "BASE của {STR_VAR_1}.\p"
	.string "Ồ? Có vẻ {STR_VAR_2} đã ghé thăm.\p"
	.string "Hãy cùng nhìn trộm một chút!\p"
	.string "{STR_VAR_2} sẽ làm gì đây?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1::
	.string "Tiếp theo, {STR_VAR_2} sẽ làm gì?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2::
	.string "Giờ thì {STR_VAR_2} sẽ làm gì\n"
	.string "đây?$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving::
	.string "Cuối cùng, {STR_VAR_2} đã đi\n"
	.string "{STR_VAR_3} bước trong SECRET\l"
	.string "BASE của {STR_VAR_1} rồi mới rời\l"
	.string "đi.$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer::
	.string "Hmm...\p"
	.string "Có vẻ SECRET BASE của\n"
	.string "{STR_VAR_1} không khiến\l"
	.string "{STR_VAR_2} hứng thú...$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase::
	.string "Có vẻ {STR_VAR_2} đã tận hưởng\n"
	.string "trọn vẹn SECRET BASE của\l"
	.string "{STR_VAR_1}.$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase::
	.string "Có vẻ {STR_VAR_2} đã trở thành\n"
	.string "một người cực kỳ yêu thích SECRET\l"
	.string "BASE của {STR_VAR_1}.$"

TVSecretBaseSecrets_Text_Outro::
	.string "Quý khán giả cũng có thể ghé thăm\n"
	.string "SECRET BASE của {STR_VAR_1}.\p"
	.string "Hãy đón xem lần tới khi chúng tôi ghé\n"
	.string "thăm một SECRET BASE khác! Cảm ơn các\l"
	.string "bạn đã theo dõi!$"

TVSecretBaseSecrets_Text_StoppedMoving1::
	.string "Vị khách đã đứng lại!\p"
	.string "Vị khách hoàn toàn không nhúc nhích!\p"
	.string "SECRET BASE của {STR_VAR_1} kém\n"
	.string "ấn tượng đến vậy sao?$"

TVSecretBaseSecrets_Text_StoppedMoving2::
	.string "Vị khách đã đứng lại!\p"
	.string "Vị khách hoàn toàn không nhúc nhích!\p"
	.string "Có phải vì mệt không? Vị khách đã kiệt\n"
	.string "sức rồi sao?$"

TVSecretBaseSecrets_Text_UsedChair::
	.string "Vị khách đã ngồi xuống một chiếc ghế! Vị\n"
	.string "khách đã yên vị!\p"
	.string "Nhìn vẻ mặt thích thú ấy kìa!\p"
	.string "Chiếc ghế hẳn phải rất thoải mái mới\n"
	.string "khiến vị khách phản ứng như vậy!$"

TVSecretBaseSecrets_Text_UsedBalloon::
	.string "Vị khách lao thẳng vào một quả bóng\n"
	.string "bay!\p"
	.string "Nó nổ rồi! Trời ơi, nó nổ tung rồi!\p"
	.string "Có vẻ vị khách giật mình vì tiếng động\n"
	.string "bất ngờ!$"

TVSecretBaseSecrets_Text_UsedTent::
	.string "Vị khách đã chui vào một TENT!\p"
	.string "Vị khách đang chạy khắp nơi!\p"
	.string "Ôi chao, vị khách đang nô đùa!\p"
	.string "Có vẻ vị khách bất ngờ trước kích\n"
	.string "thước của TENT!$"

TVSecretBaseSecrets_Text_UsedPlant::
	.string "Vị khách đang ngắm nghía một chậu cây!\p"
	.string "Thật bất ngờ, vị khách có gu rất chín\n"
	.string "chắn!$"

TVSecretBaseSecrets_Text_UsedGoldShield::
	.string "Vị khách đang ngắm nghía một GOLD\n"
	.string "SHIELD!\p"
	.string "Đôi mắt của vị khách dường như sáng\n"
	.string "lên vì kinh ngạc!$"

TVSecretBaseSecrets_Text_UsedSilverShield::
	.string "Vị khách đang ngắm nghía một SILVER\n"
	.string "SHIELD!\p"
	.string "Có vẻ vị khách đang tròn mắt kinh ngạc!$"

TVSecretBaseSecrets_Text_UsedGlassOrnament::
	.string "Vị khách đang ngắm nghía một GLASS\n"
	.string "ORNAMENT!\p"
	.string "Ôi không!\p"
	.string "Vị khách đang chạm vào nó!\p"
	.string "Nó sắp phủ đầy dấu vân tay rồi...$"

TVSecretBaseSecrets_Text_UsedTV::
	.string "Vị khách đang xem truyền hình!\p"
	.string "Có vẻ chúng ta đã gặp một người cực mê\n"
	.string "TV!$"

TVSecretBaseSecrets_Text_UsedMudBall::
	.string "Vị khách đã giẫm mạnh lên một MUD BALL!\p"
	.string "Vị khách trông vô cùng thích thú!$"

TVSecretBaseSecrets_Text_UsedBag::
	.string "...Ồ?\p"
	.string "Vị khách đang lục TÚI ĐỒ của mình!\p"
	.string "Vị khách lấy ra một {STR_VAR_2}!\p"
	.string "Nhìn vị khách mỉm cười khi giơ\n"
	.string "{STR_VAR_2} lên kìa!\p"
	.string "Cứ như quảng cáo trên TV vậy!$"

TVSecretBaseSecrets_Text_UsedCushion::
	.string "Vị khách chộp lấy một chiếc đệm rồi...$"

TVSecretBaseSecrets_Text_HitCushion::
	.string "...bắt đầu đập nó!\p"
	.string "Vị khách đang chịu nhiều căng thẳng lắm\n"
	.string "sao?$"

TVSecretBaseSecrets_Text_HuggedCushion::
	.string "...ôm chặt lấy nó!\p"
	.string "Có phải vị khách đang vui vì chuyện gì\n"
	.string "đó không?$"

TVSecretBaseSecrets_Text_BattledWon::
	.string "Vị khách đang trò chuyện với\n"
	.string "{STR_VAR_1}!\p"
	.string "Có vẻ họ sắp chiến đấu!\p"
	.string "Và...\p"
	.string "Vị khách thắng rồi! Vị khách đã giành\n"
	.string "chiến thắng trên sân khách!\p"
	.string "Vị khách đang nhảy múa ăn mừng!$"

TVSecretBaseSecrets_Text_BattledLost::
	.string "Vị khách đang trò chuyện với\n"
	.string "{STR_VAR_1}!\p"
	.string "Có vẻ họ sắp chiến đấu!\p"
	.string "Và...\p"
	.string "{STR_VAR_1} thắng rồi! Vị khách\n"
	.string "đã thua!\p"
	.string "Vị khách trông thật chán nản!$"

TVSecretBaseSecrets_Text_DeclinedBattle::
	.string "Vị khách đang trò chuyện với\n"
	.string "{STR_VAR_1}!\p"
	.string "Có vẻ họ sắp chiến đấu!\p"
	.string "Và...\p"
	.string "Không, vị khách đã từ chối!\p"
	.string "Rốt cuộc sẽ không có trận đấu nào cả!\p"
	.string "Vị khách không thấy {STR_VAR_1}\n"
	.string "đủ hấp dẫn sao?$"

TVSecretBaseSecrets_Text_UsedPoster::
	.string "Vị khách đang chăm chú nhìn một tấm áp\n"
	.string "phích!\p"
	.string "Tấm áp phích hợp ý vị khách chăng?\p"
	.string "...Nhưng... Ánh mắt của vị khách có gì đó\n"
	.string "thật đáng ngại.$"

TVSecretBaseSecrets_Text_UsedNoteMat::
	.string "Vị khách đã giẫm lên một NOTE MAT!\p"
	.string "...Hmm... Vị khách vừa sáng tác một giai\n"
	.string "điệu thật vui nhộn!$"

TVSecretBaseSecrets_Text_BattledDraw::
	.string "Vị khách đang trò chuyện với\n"
	.string "{STR_VAR_1}!\p"
	.string "Có vẻ họ sắp chiến đấu!\p"
	.string "Và...\p"
	.string "Hòa rồi! Vẫn chưa phân thắng bại!\p"
	.string "Cả hai HLV đều có vẻ vô cùng thất\n"
	.string "vọng!$"

TVSecretBaseSecrets_Text_UsedSpinMat::
	.string "Vị khách đã giẫm lên một SPIN MAT!\p"
	.string "Có vẻ vị khách đang chóng mặt!\p"
	.string "Vị khách đang lảo đảo! Cẩn thận!$"

TVSecretBaseSecrets_Text_UsedSandOrnament::
	.string "Vị khách đang với tay về phía một SAND\n"
	.string "ORNAMENT!\p"
	.string "Ôi!\p"
	.string "Nó vỡ vụn rồi! Nó tan tành rồi!\p"
	.string "Vị khách trông vừa ngượng ngùng vừa\n"
	.string "áy náy!$"

TVSecretBaseSecrets_Text_UsedDesk::
	.string "Vị khách đang dùng ngón tay quệt trên\n"
	.string "mặt bàn!\p"
	.string "Có vẻ vị khách không chấp nhận được\n"
	.string "bụi bẩn!\p"
	.string "Thật bất ngờ, vị khách rất quan tâm đến\n"
	.string "sự ngăn nắp!$"

TVSecretBaseSecrets_Text_UsedBrick::
	.string "Vị khách đang nhìn chằm chằm vào một\n"
	.string "BRICK!\p"
	.string "Có lẽ vị khách đang nghĩ về món đồ đặt\n"
	.string "trên BRICK.$"

TVSecretBaseSecrets_Text_UsedSolidBoard::
	.string "Vị khách đang đi qua SOLID BOARD.\p"
	.string "Vị khách cứ nhìn xuống mãi.\p"
	.string "Có vẻ vị khách nhút nhát và thận trọng\n"
	.string "đến bất ngờ!$"

TVSecretBaseSecrets_Text_UsedFence::
	.string "Vị khách đang chăm chú nhìn một FENCE!\p"
	.string "Phải chăng một ý tưởng mới về bẫy vừa\n"
	.string "lóe lên trong đầu vị khách?$"

TVSecretBaseSecrets_Text_UsedGlitterMat::
	.string "Vị khách đã giẫm lên một GLITTER MAT!\p"
	.string "Vị khách đang tạo đủ kiểu dáng!\p"
	.string "Có vẻ vị khách đang mơ tưởng mình là\n"
	.string "một thần tượng!$"

TVSecretBaseSecrets_Text_UsedTire::
	.string "Vị khách đang chăm chú nhìn một TIRE!\p"
	.string "Có phải vị khách đang nghĩ xem loại xe\n"
	.string "nào sẽ dùng nó không?$"

TVSecretBaseSecrets_Text_UsedStand::
	.string "Vị khách đã trèo lên một STAND!\p"
	.string "Từ trên cao, vị khách đang nhìn bao\n"
	.string "quát BASE của {STR_VAR_1}!\p"
	.string "Và...\p"
	.string "Gầm vang một tiếng! Vị khách đang gầm\n"
	.string "lên!$"

TVSecretBaseSecrets_Text_BrokeDoor::
	.string "Vị khách đã lao thẳng vào một\n"
	.string "BREAKABLE DOOR!\p"
	.string "Vị khách đang cười vang khoái chí!$"

TVSecretBaseSecrets_Text_UsedDoll::
	.string "Vị khách đang nói chuyện với một DOLL!\p"
	.string "...Hơi rợn người...$"

TVSecretBaseSecrets_Text_UsedSlide::
	.string "Vị khách đang trèo lên thang của một\n"
	.string "SLIDE!\p"
	.string "Và...\p"
	.string "Vị khách trượt xuống rồi!\p"
	.string "Có vẻ vị khách đang vui chơi thỏa\n"
	.string "thích!$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown::
	.string "Vị khách đang trèo lên thang của một\n"
	.string "SLIDE!\p"
	.string "Và...\p"
	.string "Vị khách lại trèo xuống bằng thang!\p"
	.string "Vị khách đột nhiên sợ quá nên đổi ý\n"
	.string "sao?$"

TVSecretBaseSecrets_Text_UsedJumpMat::
	.string "Vị khách đã giẫm lên một JUMP MAT!\p"
	.string "Vị khách nhảy một lần!\p"
	.string "Nhảy lần thứ hai!\p"
	.string "Và tiếp đất thành công!\p"
	.string "Vị khách đang vỗ tay! Quả là một màn\n"
	.string "độc diễn!$"

gTVSafariFanClubText00::
	.string "CLB HÂM MỘ SAFARI!\p"
	.string "PHÓNG VIÊN: Nào, các chiến hữu! Đang\n"
	.string "ném SAFARI BALLS đấy chứ?\p"
	.string "Còn tôi thì chắc chắn rồi, vì tôi đang\n"
	.string "có mặt tại SAFARI ZONE đầy ắp những\l"
	.string "POKéMON tuyệt vời!\p"
	.string "Bắt đầu thôi, hãy trò chuyện với người\n"
	.string "bạn HƯỚNG DẪN VIÊN tốt bụng này!\p"
	.string "Nào, anh bạn, tình hình các HLV\n"
	.string "đến đây thế nào?$"

gTVSafariFanClubText01::
	.string "HƯỚNG DẪN: Có vẻ mọi người đều đang\n"
	.string "rất hăng.\p"
	.string "{STR_VAR_1} đặc biệt làm rất tốt.\p"
	.string "Lần trước, {STR_VAR_1} đã bắt\n"
	.string "được tới {STR_VAR_2} POKéMON.$"

gTVSafariFanClubText02::
	.string "HLV này dùng {POKEBLOCK}S rất\n"
	.string "khéo. Tôi nghĩ lần đó đã dùng\l"
	.string "{STR_VAR_2}.$"

gTVSafariFanClubText03::
	.string "HLV này không dùng dù chỉ một\n"
	.string "{POKEBLOCK}! Không một cái nào!\p"
	.string "Đúng là chuyên gia.$"

gTVSafariFanClubText04::
	.string "PHÓNG VIÊN: Vậy sao?\p"
	.string "Nghe như người bạn {STR_VAR_1}\n"
	.string "của chúng ta là một bậc thầy SAFARI cừ\l"
	.string "khôi!\p"
	.string "HƯỚNG DẪN: Tôi hy vọng HLV sẽ quay lại\n"
	.string "và cho chúng tôi xem kỹ thuật tuyệt vời\l"
	.string "đó.$"

gTVSafariFanClubText05::
	.string "HƯỚNG DẪN: Có vẻ chẳng ai làm tốt.\p"
	.string "{STR_VAR_1} đặc biệt kém may\n"
	.string "mắn.\p"
	.string "Lần trước, HLV chỉ bắt được\n"
	.string "{STR_VAR_2} POKéMON.$"

gTVSafariFanClubText06::
	.string "HƯỚNG DẪN: Có vẻ chẳng ai làm tốt.\p"
	.string "{STR_VAR_1} đặc biệt kém may\n"
	.string "mắn.\p"
	.string "Lần trước, HLV không bắt được\n"
	.string "một POKéMON nào. Không một con nào!$"

gTVSafariFanClubText07::
	.string "HLV này có dùng {POKEBLOCK}S. Tôi\n"
	.string "nghĩ lần đó đã dùng {STR_VAR_2}.\p"
	.string "Nhưng trời ạ, tôi mong HLV sẽ khá\n"
	.string "hơn một chút.$"

gTVSafariFanClubText08::
	.string "Tôi nghĩ HLV sẽ may mắn hơn nếu\n"
	.string "dùng {POKEBLOCK}S, vì lần đó hoàn toàn\l"
	.string "không dùng cái nào.$"

gTVSafariFanClubText09::
	.string "PHÓNG VIÊN: Vậy sao?\p"
	.string "Nghe như người bạn {STR_VAR_1}\n"
	.string "của chúng ta cần dạn dày kinh nghiệm\l"
	.string "SAFARI hơn.\p"
	.string "HƯỚNG DẪN: Tôi hy vọng HLV sẽ ghé lại\n"
	.string "thật nhiều lần để quen dần.$"

gTVSafariFanClubText10::
	.string "PHÓNG VIÊN: Đúng vậy! Đương đầu với\n"
	.string "thử thách là điều rất quan trọng!\p"
	.string "Quý khán giả, hãy đến SAFARI và tự mình\n"
	.string "thử sức!\p"
	.string "Hẹn gặp lại lần sau, tạm biệt nhé!$"

ContestLiveUpdates_Text_Intro::
	.string "“CẬP NHẬT TRỰC TIẾP CONTEST!”\p"
	.string "MC: Cảm ơn quý vị đã theo dõi!\p"
	.string "Chúng tôi đang truyền hình trực tiếp\n"
	.string "từ nơi {STR_VAR_1} vừa kết thúc.\p"
	.string "Khán phòng vẫn chật kín những khán giả\n"
	.string "chưa muốn ra về.\p"
	.string "Khán giả: {STR_VAR_2}!\p"
	.string "Khán giả: {STR_VAR_3}!\p"
	.string "MC: Như quý vị vừa nghe, POKéMON\n"
	.string "{STR_VAR_2} của\l"
	.string "{STR_VAR_3} đã giành chiến thắng\l"
	.string "tại cuộc thi.\p"
	.string "Khán giả: {STR_VAR_2}! Bạn là\n"
	.string "tuyệt nhất!\p"
	.string "Khán giả: {STR_VAR_3}! Giỏi lắm!\p"
	.string "MC: Hãy cùng nghe người hâm mộ nói gì\n"
	.string "về cuộc thi này.$"

ContestLiveUpdates_Text_WonBothRounds::
	.string "Khán giả: {STR_VAR_2} đã dẫn đầu\n"
	.string "ở cả phần chấm điểm sơ bộ lẫn phần chấm\l"
	.string "điểm thứ hai!\p"
	.string "{STR_VAR_2} đó chắc chắn sẽ còn\n"
	.string "chiến thắng!$"

ContestLiveUpdates_Text_BetterRound2::
	.string "Khán giả: {STR_VAR_2} không thể\n"
	.string "hiện tốt ở phần chấm điểm sơ bộ, nhưng\l"
	.string "lại thắng lớn ở phần chấm điểm thứ hai!\p"
	.string "Đó là màn lội ngược dòng kỳ diệu của\n"
	.string "{STR_VAR_2}. Hoan hô!$"

ContestLiveUpdates_Text_EqualRounds::
	.string "Khán giả: {STR_VAR_2} đã giữ\n"
	.string "phong độ ổn định suốt cả phần chấm\l"
	.string "điểm sơ bộ lẫn phần chấm điểm thứ hai.\p"
	.string "{STR_VAR_3} và\n"
	.string "{STR_VAR_2} đúng là một bộ đôi\l"
	.string "không tầm thường!$"

ContestLiveUpdates_Text_BetterRound1::
	.string "Khán giả: Xét về tiêu chí\n"
	.string "{STR_VAR_1}, {STR_VAR_2}\l"
	.string "đó thật sự nổi bật.\p"
	.string "Tuy nhiên, tôi mong lần sau nó sẽ có\n"
	.string "những màn trình diễn hay hơn.$"

ContestLiveUpdates_Text_GotNervous::
	.string "Khán giả: Khi {STR_VAR_2} trở nên\n"
	.string "căng thẳng, tôi không thể ngăn mình hét\l"
	.string "lên cổ vũ.\p"
	.string "Tôi muốn nhắn với {STR_VAR_2}\n"
	.string "rằng: “Chúc mừng nhé!”$"

ContestLiveUpdates_Text_StartledFoes::
	.string "Khán giả: Màn trình diễn của\n"
	.string "{STR_VAR_2} đó làm cả tôi cũng\l"
	.string "phải giật mình!\p"
	.string "{STR_VAR_2}, bạn tuyệt lắm!$"

ContestLiveUpdates_Text_UsedCombo::
	.string "Khán giả: Màn trình diễn liên hoàn của\n"
	.string "{STR_VAR_2} thật ngoạn mục!\p"
	.string "Tôi xúc động đến tận tâm can!$"

ContestLiveUpdates_Text_ExcitingAppeal::
	.string "Khán giả: Màn trình diễn của nhà vô địch\n"
	.string "{STR_VAR_2} khiến tim tôi đập\l"
	.string "thình thịch!$"

ContestLiveUpdates_Text_WasCool::
	.string "{STR_VAR_2}! Bạn ngầu lắm!$"

ContestLiveUpdates_Text_WasBeautiful::
	.string "{STR_VAR_2}! Bạn đẹp lắm!$"

ContestLiveUpdates_Text_WasCute::
	.string "{STR_VAR_2}! Bạn đáng yêu lắm!$"

ContestLiveUpdates_Text_WasSmart::
	.string "{STR_VAR_2}! Bạn thông minh lắm!$"

ContestLiveUpdates_Text_WasTough::
	.string "{STR_VAR_2}! Bạn mạnh mẽ lắm!$"

ContestLiveUpdates_Text_VeryExcitingAppeal::
	.string "Khán giả: Màn trình diễn của nhà vô địch\n"
	.string "{STR_VAR_2} vẫn khiến tim tôi đập\l"
	.string "thình thịch!$"

ContestLiveUpdates_Text_VeryCool::
	.string "{STR_VAR_2}! Không ai có thể\n"
	.string "ngầu hơn bạn!$"

ContestLiveUpdates_Text_VeryBeautiful::
	.string "{STR_VAR_2}! Bạn là người đẹp\n"
	.string "nhất!$"

ContestLiveUpdates_Text_VeryCute::
	.string "{STR_VAR_2}! Bạn đúng là đáng\n"
	.string "yêu nhất!$"

ContestLiveUpdates_Text_VerySmart::
	.string "{STR_VAR_2}! Bạn là người thông\n"
	.string "minh nhất trong những người thông\l"
	.string "minh!$"

ContestLiveUpdates_Text_VeryTough::
	.string "{STR_VAR_2}! Bạn là người mạnh\n"
	.string "mẽ nhất trong những người mạnh mẽ!$"

ContestLiveUpdates_Text_TookBreak::
	.string "Khán giả: Ngay cả khi {STR_VAR_2}\n"
	.string "tạm ngừng trình diễn, tôi vẫn không thể\l"
	.string "rời mắt khỏi nó.\p"
	.string "Tôi hoàn toàn bị {STR_VAR_2} đó\n"
	.string "mê hoặc.$"

ContestLiveUpdates_Text_GotStartled::
	.string "Khán giả: Khi {STR_VAR_2} bị màn\n"
	.string "trình diễn của một POKéMON khác làm\l"
	.string "giật mình, tôi suýt bật khóc.\p"
	.string "{STR_VAR_2}, bạn đã rất kiên\n"
	.string "cường! Giỏi lắm!$"

ContestLiveUpdates_Text_MoveWonderful::
	.string "Khán giả: Ôi... Chiêu {STR_VAR_3}\n"
	.string "của {STR_VAR_2}! Chiêu\l"
	.string "{STR_VAR_3} của\l"
	.string "{STR_VAR_2}! Chiêu\l"
	.string "{STR_VAR_3} của\l"
	.string "{STR_VAR_2}! Sao có thể tuyệt\l"
	.string "vời đến thế?$"

ContestLiveUpdates_Text_TalkAboutAnotherMon::
	.string "MC: Vậy là quý vị đã nghe rồi đấy. Nơi\n"
	.string "này tràn ngập người hâm mộ\l"
	.string "{STR_VAR_1}!\p"
	.string "Tôi cũng phải nhắc đến một POKéMON\n"
	.string "khác đã thu hút sự chú ý của mình, đó\l"
	.string "là {STR_VAR_3} của\l"
	.string "{STR_VAR_2}.\p"
	.string "{STR_VAR_3} của\n"
	.string "{STR_VAR_2}...$"

ContestLiveUpdates_Text_FailedToAppeal::
	.string "Trong phần chấm điểm thứ hai, vì quá\n"
	.string "căng thẳng nên nó không thể thực hiện\l"
	.string "dù chỉ một màn trình diễn.\p"
	.string "Lần sau, tôi mong được thấy\n"
	.string "{STR_VAR_1} này thực hiện ít\l"
	.string "nhất một màn trình diễn.$"

ContestLiveUpdates_Text_LastInBothRounds::
	.string "Nó đã đứng chót ở cả phần chấm điểm sơ\n"
	.string "bộ lẫn phần chấm điểm thứ hai.\p"
	.string "Tôi hy vọng {STR_VAR_1} sẽ huấn\n"
	.string "luyện lại {STR_VAR_2} này và xóa\l"
	.string "đi nỗi hổ thẹn của vị trí chót không thể\l"
	.string "chối cãi ấy.$"

ContestLiveUpdates_Text_NotExcitingEnough::
	.string "Nó đã không tận dụng được sự phấn\n"
	.string "khích của khán giả để thực hiện một\l"
	.string "màn trình diễn thích hợp.\p"
	.string "Chúng tôi hy vọng lần sau\n"
	.string "{STR_VAR_1} sẽ biết cách nắm bắt\l"
	.string "cảm xúc của khán giả và đẩy sự phấn\l"
	.string "khích của họ lên đến đỉnh điểm.$"

ContestLiveUpdates_Text_LostAfterWinningRound1::
	.string "Dù đứng đầu phần chấm điểm sơ bộ,\n"
	.string "những màn trình diễn của nó trong phần\l"
	.string "chấm điểm thứ hai lại không tạo được\l"
	.string "ấn tượng.\p"
	.string "Nó đã phải nhận một trận thua ngược\n"
	.string "đầy ê chề.\p"
	.string "Tôi tin rằng giờ đây {STR_VAR_1}\n"
	.string "đang nghiên cứu cách thực hiện những\l"
	.string "màn trình diễn hiệu quả hơn.$"

ContestLiveUpdates_Text_NeverExciting::
	.string "Những màn trình diễn của nó trong phần\n"
	.string "chấm điểm thứ hai chưa từng khiến khán\l"
	.string "giả phấn khích.\p"
	.string "Chúng tôi hy vọng nó sẽ thôi bận tâm\n"
	.string "đến các POKéMON khác và học cách\l"
	.string "hướng màn trình diễn đến khán giả\l"
	.string "nhiều hơn.$"

ContestLiveUpdates_Text_LostBySmallMargin::
	.string "Nó chỉ thua {STR_VAR_2} của\n"
	.string "{STR_VAR_1} với cách biệt rất\l"
	.string "nhỏ.\p"
	.string "Tiến sát chiến thắng đến vậy rồi vẫn\n"
	.string "thất bại hẳn là đau lòng lắm.\p"
	.string "Tôi sẽ không ngạc nhiên nếu\n"
	.string "{STR_VAR_3} đang khóc vì kết quả\l"
	.string "này.$"

ContestLiveUpdates_Text_RepeatedAppeals::
	.string "Nó khiến GIÁM KHẢO thất vọng vì\n"
	.string "lặp lại cùng một màn trình diễn.\p"
	.string "Đó là lỗi không thể tha thứ trong bất\n"
	.string "kỳ cuộc thi nào, và POKéMON ấy đã phải\l"
	.string "trả giá.\p"
	.string "{STR_VAR_1} nên cảm thấy có lỗi\n"
	.string "vì màn thể hiện đáng buồn này.$"

ContestLiveUpdates_Text_ValiantEffortButLost::
	.string "{STR_VAR_1} đã nỗ lực đầy quả\n"
	.string "cảm, nhưng...\p"
	.string "Tất cả đều vô ích khi cuối cùng vẫn\n"
	.string "đứng chót.\p"
	.string "{STR_VAR_1} nên rút kinh nghiệm\n"
	.string "từ thất bại này và vận dụng thật tốt\l"
	.string "những gì đã học được.$"

ContestLiveUpdates_Text_Outro::
	.string "Tôi xin khép lại chương trình bằng lời\n"
	.string "chào quen thuộc dành cho những người\l"
	.string "chiến thắng.\p"
	.string "Lần này là {STR_VAR_1} và\n"
	.string "{STR_VAR_2}!\p"
	.string "MC: Mọi người sẵn sàng chưa? Cùng hô\n"
	.string "nào!\p"
	.string "Khán giả: {STR_VAR_1}!\n"
	.string "{STR_VAR_2}! Xin chúc mừng! Hai\l"
	.string "bạn là nhà vô địch cuộc thi!$"

gTVPokemonBattleUpdateText00::
	.string "“POKéMON BATTLE UPDATE!”\p"
	.string "Liên tục cập nhật những kết quả mới\n"
	.string "nhất từ các trận đấu POKéMON!$"

gTVPokemonBattleUpdateText01::
	.string "Hai HLV {STR_VAR_1} và\n"
	.string "{STR_VAR_2} đã đối đầu trong một\l"
	.string "trận {STR_VAR_3} trận đấu.\p"
	.string "Trận đấu kết thúc với chiến thắng\n"
	.string "thuộc về {STR_VAR_1}!$"

gTVPokemonBattleUpdateText02::
	.string "Trong trận đấu, {STR_VAR_2} của\n"
	.string "{STR_VAR_1} đã trở thành một\l"
	.string "thế lực đáng gờm khi sử dụng\l"
	.string "{STR_VAR_3}!$"

gTVPokemonBattleUpdateText03::
	.string "Màn thể hiện yếu kém của\n"
	.string "{STR_VAR_2} thuộc về\l"
	.string "{STR_VAR_1} đã gây tổn thất rất\l"
	.string "lớn.$"

gTVPokemonBattleUpdateText04::
	.string "Xin chúc mừng chiến thắng của bạn,\n"
	.string "{STR_VAR_1}!\p"
	.string "Với người thất bại {STR_VAR_2},\n"
	.string "chúng tôi mong bạn sẽ có kết quả tốt\l"
	.string "hơn vào lần sau!\p"
	.string "Chương trình “POKéMON BATTLE\n"
	.string "UPDATE!” kỳ này xin được khép lại tại\l"
	.string "đây.$"

gTVPokemonBattleUpdateText05::
	.string "Hai đội của HLV {STR_VAR_1}\n"
	.string "và {STR_VAR_2} đã chạm trán\l"
	.string "trong một trận MULTI BATTLE.\p"
	.string "Trận đấu kết thúc với chiến thắng\n"
	.string "thuộc về đội của {STR_VAR_1}.$"

gTVPokemonBattleUpdateText06::
	.string "Trong trận đấu, {STR_VAR_2}\n"
	.string "thuộc đội của {STR_VAR_1} đã trở\l"
	.string "thành một thế lực đáng gờm khi sử dụng\l"
	.string "{STR_VAR_3}.$"

gTVPokemonBattleUpdateText07::
	.string "Màn thể hiện yếu kém của\n"
	.string "{STR_VAR_3} thuộc đội\l"
	.string "{STR_VAR_2} đã gây tổn thất rất\l"
	.string "lớn.\p"
	.string "Xin chúc mừng chiến thắng của đội bạn,\n"
	.string "{STR_VAR_1}!\p"
	.string "Với đội thất bại của {STR_VAR_2},\n"
	.string "chúng tôi mong các bạn sẽ có kết quả\l"
	.string "tốt hơn vào lần sau!\p"
	.string "Chương trình “POKéMON BATTLE\n"
	.string "UPDATE!” kỳ này xin được khép lại tại\l"
	.string "đây.$"

GabbyAndTy_Text_GabbyPreFirstBattle:
	.string "GABBY: Ô! Ngay tại nơi này mà chúng tôi\n"
	.string "lại phát hiện một HLV trông rất\l"
	.string "mạnh!\p"
	.string "Được rồi, quay máy! Bắt đầu cuộc phỏng\n"
	.string "vấn nào.$"

GabbyAndTy_Text_GabbyIntro:
	.string "GABBY: Ô! Bạn là {PLAYER}! Chào bạn!\n"
	.string "Bạn còn nhớ chúng tôi lần trước không?\p"
	.string "Bạn có thể cho chúng tôi thấy mình đã\n"
	.string "mạnh lên đến mức nào không? Được rồi,\l"
	.string "bắt đầu phỏng vấn!$"

GabbyAndTy_Text_GabbyDefeatFirstTime:
	.string "GABBY: Mắt tôi quả nhiên không nhìn lầm!\n"
	.string "Tôi đã phát hiện ra một HLV phi\l"
	.string "thường!$"

GabbyAndTy_Text_WhoAreYouInterview:
	.string "GABBY: Tuyệt vời! Tuyệt vời! Bạn là ai\n"
	.string "vậy?!\p"
	.string "Tôi đã biết chúng tôi sắp gặp chuyện\n"
	.string "lớn ngay khi phát hiện ra bạn!\p"
	.string "Ôi, xin để tôi giải thích. Chúng tôi đi\n"
	.string "khắp nơi để phỏng vấn đủ loại HLV.\p"
	.string "Vậy bạn có thể dành chút thời gian cho\n"
	.string "chúng tôi phỏng vấn không?$"

GabbyAndTy_Text_QuoteFromLastInterview:
	.string "GABBY: “{STR_VAR_1}!”\p"
	.string "Bạn nhớ chứ? Đó là câu chốt bạn đã nói\n"
	.string "sau trận đấu lần trước.\p"
	.string "Những chuyện như thế này tôi không\n"
	.string "bao giờ quên!$"

GabbyAndTy_Text_YouStompedUsInterviewAgain:
	.string "Lần trước giao đấu, bạn đã đánh bại\n"
	.string "chúng tôi trước khi chúng tôi kịp trở\l"
	.string "tay...\p"
	.string "Vậy bạn thấy sao? Bạn có muốn được\n"
	.string "phỏng vấn lần nữa không?$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain:
	.string "Lần trước giao đấu, bạn đã ném POKé\n"
	.string "BALL vào chúng tôi, đúng không?\p"
	.string "Chúng tôi sốc đến mức kể chuyện đó cho\n"
	.string "tất cả mọi người!\p"
	.string "Vậy bạn thấy sao? Bạn có muốn được\n"
	.string "phỏng vấn lần nữa không?$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain:
	.string "Lần trước giao đấu, cách sử dụng vật\n"
	.string "phẩm khéo léo của bạn đã hạ gục chúng\l"
	.string "tôi.\p"
	.string "Vậy bạn thấy sao? Bạn có muốn được\n"
	.string "phỏng vấn lần nữa không?$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain:
	.string "Lần trước giao đấu, ít ra chúng tôi\n"
	.string "cũng thể hiện khá ra trò.\p"
	.string "Vậy bạn thấy sao? Bạn có muốn được\n"
	.string "phỏng vấn lần nữa không?$"

GabbyAndTy_Text_InterviewAgain:
	.string "Vậy bạn thấy sao? Bạn có muốn được\n"
	.string "phỏng vấn lần nữa không?$"

GabbyAndTy_Text_DescribeYourFeelings:
	.string "Bạn đồng ý sao? Cảm ơn nhé!\p"
	.string "Được rồi, hãy diễn tả cảm xúc của bạn\n"
	.string "về trận đấu với chúng tôi, nhưng phải\l"
	.string "thật ngắn gọn và ấn tượng. Bắt đầu!$"

GabbyAndTy_Text_PerfectWellBeSeeingYou:
	.string "GABBY: Ừm, đúng rồi! Đó là câu chốt hoàn\n"
	.string "hảo!\p"
	.string "Tôi có cảm giác chuyện này sẽ tạo nên\n"
	.string "một chương trình TV tuyệt vời.\p"
	.string "Có thể chương trình sẽ được phát trên\n"
	.string "TV, nên nhớ đón xem chúng tôi nhé!\p"
	.string "Được rồi! Hẹn gặp lại bạn!$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut:
	.string "GABBY: Ôi...\p"
	.string "Được rồi, nhưng đừng bỏ cuộc nhé!\n"
	.string "Chúng tôi sẽ tiếp tục để mắt đến bạn!$"

GabbyAndTy_Text_KeepingAnEyeOutForYou:
	.string "GABBY: Chúng tôi sẽ tiếp tục để mắt đến\n"
	.string "bạn!$"

GabbyAndTy_Text_GabbyNotEnoughMons:
	.string "GABBY: Có HLV mạnh nào sở hữu\n"
	.string "nhiều POKéMON ở quanh đây không nhỉ?$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime:
	.string "GABBY: Chà, bạn thật đáng nể!\p"
	.string "So với lần giao đấu trước, bạn đã mạnh\n"
	.string "lên rất, rất nhiều.\p"
	.string "Quả nhiên chúng tôi đã đúng khi nhận ra\n"
	.string "bạn là một HLV đầy triển vọng.\p"
	.string "Vậy bạn thấy sao? Lần này bạn có sẵn\n"
	.string "lòng trả lời phỏng vấn không?$"

GabbyAndTy_Text_GabbyDefeat:
	.string "GABBY: Trận đấu thật căng thẳng! Anh\n"
	.string "đã quay lại hết chưa?$"

GabbyAndTy_Text_TyPreFirstBattle:
	.string "TY: Này, nhìn xem! Ngay tại nơi này lại\n"
	.string "có một HLV trông rất mạnh! Máy\l"
	.string "quay đang chạy rồi!$"

GabbyAndTy_Text_TyIntro:
	.string "TY: Này, nhìn xem! Tôi nhớ bạn rồi!\p"
	.string "Tôi sẽ dùng chiếc máy quay này ghi lại\n"
	.string "toàn bộ trận đấu!$"

GabbyAndTy_Text_TyPostBattle:
	.string "TY: Bạn đúng là có tố chất! Tôi quay\n"
	.string "được những cảnh tuyệt vời rồi!$"

GabbyAndTy_Text_TyNotEnoughMons:
	.string "TY: Bạn chỉ có đúng một POKéMON thôi\n"
	.string "sao?\p"
	.string "Nếu có thêm POKéMON thì cảnh quay sẽ\n"
	.string "hay hơn, nhưng...$"

GabbyAndTy_Text_TyDefeatFirstTime:
	.string "TY: Đúng là chúng ta đã phát hiện một\n"
	.string "HLV đầy triển vọng. Đây là tin sốt\l"
	.string "dẻo lớn đấy!$"

GabbyAndTy_Text_TyDefeat:
	.string "TY: Ừ, tôi quay được hết rồi. Toàn bộ\n"
	.string "trận đấu đều đã vào máy.$"

gTVInSearchOfTrainersText00::
	.string "IN SEARCH OF HLV...\p"
	.string "GABBY: Xin chào! Hôm nay tôi đang có mặt\n"
	.string "ở khu vực gần {STR_VAR_1}.\p"
	.string "Chúng tôi đang tìm kiếm những tài năng\n"
	.string "mới đầy triển vọng.\p"
	.string "Hôm nay, ống kính của chúng tôi hướng\n"
	.string "về HLV {PLAYER}.\p"
	.string "HLV này có điều gì đó khiến chúng\n"
	.string "tôi đặc biệt chú ý.$"

gTVInSearchOfTrainersText01::
	.string "Chúng tôi từng giao đấu với {PLAYER},\n"
	.string "và có thể khẳng định HLV này chắc\l"
	.string "chắn đã tiến bộ hơn trước rất nhiều.\p"
	.string "Tôi đã biết mình phát hiện ra một người\n"
	.string "đặc biệt ngay khi nhìn thấy HLV\l"
	.string "này!$"

gTVInSearchOfTrainersText02::
	.string "Cách tốt nhất để xác định sức mạnh của\n"
	.string "một HLV...\p"
	.string "À, cách nhanh nhất chính là giao đấu. Và\n"
	.string "thế là cuộc điều tra của chúng tôi bắt\l"
	.string "đầu!\p"
	.string "... ...\p"
	.string "Đó là lý do chúng tôi bước vào trận đấu\n"
	.string "với {PLAYER}.\p"
	.string "Với màn thể hiện áp đảo, chúng tôi đã bị\n"
	.string "đánh bẹp, cuốn tròn rồi quăng sang một\l"
	.string "bên!\p"
	.string "{PLAYER} mạnh đến mức không chút\n"
	.string "khoan nhượng...\p"
	.string "Sau đây là cảm nhận của chúng tôi sau\n"
	.string "khi giao đấu với HLV nổi bật hôm\l"
	.string "nay.$"

gTVInSearchOfTrainersText03::
	.string "Sự kết hợp giữa {STR_VAR_1} và\n"
	.string "{STR_VAR_3} thật tuyệt diệu!\p"
	.string "Hình ảnh {STR_VAR_1} và\n"
	.string "{STR_VAR_3} hết lòng hỗ trợ lẫn\l"
	.string "nhau giữa trận chiến ác liệt...\p"
	.string "Đó là một cảnh tượng tuyệt vời!\p"
	.string "{STR_VAR_2} là chiêu HLV đã\n"
	.string "sử dụng cuối cùng trong trận đấu với\l"
	.string "chúng tôi.\p"
	.string "Chiêu {STR_VAR_2} chính là biểu\n"
	.string "tượng cho tình bạn giữa\l"
	.string "{STR_VAR_1} và\l"
	.string "{STR_VAR_3}!$"

gTVInSearchOfTrainersText04::
	.string "...Sau cuộc chạm trán ấy, tôi đã mất hết\n"
	.string "tự tin vào bản thân.\p"
	.string "Chúng tôi bị đánh bại trước khi kịp\n"
	.string "tung ra dù chỉ một đòn. Hu hu... Sụt sịt...\p"
	.string "Dù vậy, những trận đấu của {PLAYER}\n"
	.string "vẫn rất đáng xem.\p"
	.string "Tôi khuyên những HLV tự tin hãy\n"
	.string "đến thách đấu {PLAYER}.$"

gTVInSearchOfTrainersText05::
	.string "Tôi chỉ có một điều muốn nói. Đừng hòng\n"
	.string "ném POKé BALL trong trận đấu với\l"
	.string "HLV!\p"
	.string "{PLAYER} quả thật rất mạnh, nhưng\n"
	.string "chẳng hiểu gì về những luật cơ bản.\p"
	.string "Tôi có một yêu cầu dành cho khán giả\n"
	.string "truyền hình.\p"
	.string "Nếu gặp {PLAYER}, xin hãy nhắc nhở\n"
	.string "HLV này!$"

gTVInSearchOfTrainersText06::
	.string "{PLAYER} rất giỏi phán đoán hành\n"
	.string "động của đối thủ.\p"
	.string "Thời điểm sử dụng vật phẩm cũng hiệu\n"
	.string "quả đáng kinh ngạc!$"

gTVInSearchOfTrainersText07::
	.string "Nói thật, tôi từng nghĩ mình cũng khá\n"
	.string "giỏi.\p"
	.string "Dù cuối cùng vẫn thua, chúng tôi đã có\n"
	.string "một trận đấu vô cùng quyết liệt.\p"
	.string "Nhưng nếu đối đầu với tôi mà còn chật\n"
	.string "vật thì bạn vẫn phải cố gắng nhiều đấy,\l"
	.string "{PLAYER}!$"

gTVInSearchOfTrainersText08::
	.string "Sau trận đấu, chúng tôi đề nghị\n"
	.string "{PLAYER} đưa ra một lời tổng kết\l"
	.string "ngắn gọn.\p"
	.string "HLV ấy trả lời:\n"
	.string "“{STR_VAR_1}.”\p"
	.string "Hai POKéMON {STR_VAR_2} và\n"
	.string "{STR_VAR_3} của {PLAYER}...\l"
	.string "Cùng câu nói “{STR_VAR_1}”...\p"
	.string "Ừm! Thâm thúy thật! Câu nói ấy hẳn chứa\n"
	.string "đựng ý nghĩa rất sâu xa!\p"
	.string "Quả không bất ngờ, một HLV giỏi\n"
	.string "luôn có những điều hay để nói.\p"
	.string "Chương trình hôm nay xin kết thúc tại\n"
	.string "đây! Hẹn gặp lại trong lần phát sóng\l"
	.string "tới!$"

ContestLadyShow_Text_Intro::
	.string "“POKéMON CONTEST LIVE UPDATES!”\p"
	.string "MC: Xin lỗi vì đã tạm ngắt chương trình\n"
	.string "thường lệ, và cảm ơn quý vị đã theo\l"
	.string "dõi!\p"
	.string "Chúng tôi đang truyền hình trực tiếp\n"
	.string "từ nơi {STR_VAR_1} vừa kết\l"
	.string "thúc!\p"
	.string "Khán giả: ?!!!!\p"
	.string "MC: Ô! Có vẻ những người tham gia\n"
	.string "cuộc thi đang tiến về phía này!\p"
	.string "Tôi sẽ thử thực hiện một cuộc phỏng\n"
	.string "vấn bất ngờ dành cho quý vị đang theo\l"
	.string "dõi tại nhà!\p"
	.string "Khán giả: ?!!!! ?!!!!$"

ContestLadyShow_Text_Won::
	.string "MC: Xin lỗi! Cảm ơn cô đã tham gia\n"
	.string "chương trình truyền hình trực tiếp!\p"
	.string "Cho phép tôi chúc mừng chiến thắng của\n"
	.string "cô nhé?\p"
	.string "Yếu tố then chốt nào đã tạo nên chiến\n"
	.string "thắng ngoạn mục hôm nay?\p"
	.string "BEAUTY: Hôm nay tôi và\n"
	.string "{STR_VAR_2} đã cố gắng hết sức!\p"
	.string "Nhưng chắc chắn chúng tôi không thể\n"
	.string "thành công nếu thiếu mọi sự giúp đỡ đã\l"
	.string "nhận được trước thềm cuộc thi!\p"
	.string "MC: Cô có muốn chia sẻ niềm vui với một\n"
	.string "người đặc biệt nào không? Hãy nhắn gửi\l"
	.string "trực tiếp nào!\p"
	.string "BEAUTY: Người đang ở ngoài kia!\p"
	.string "{STR_VAR_3}! Bạn có đang xem\n"
	.string "không? Chúng tôi làm được rồi! Cảm ơn\l"
	.string "bạn!$"

ContestLadyShow_Text_Lost::
	.string "MC: Xin lỗi! Cảm ơn cô đã tham gia\n"
	.string "chương trình truyền hình trực tiếp!\p"
	.string "Cô hẳn rất thất vọng trước diễn biến\n"
	.string "vừa rồi. Cô có muốn nói gì không?\p"
	.string "BEAUTY: Đau lòng quá... Tôi và\n"
	.string "{STR_VAR_2} đã cố gắng hết sức...\p"
	.string "Nhưng tôi cảm thấy mình đã phụ lòng\n"
	.string "tất cả những người luôn ủng hộ chúng\l"
	.string "tôi.\p"
	.string "MC: Tôi không muốn nói điều này, nhưng\n"
	.string "màu sắc của POKéMON này hơi kém.\p"
	.string "BEAUTY: {STR_VAR_3}, tôi xin lỗi...\n"
	.string "Lần sau tôi sẽ làm tốt hơn, tôi thề\l"
	.string "đấy... Sụt sịt... Oaaaa!\p"
	.string "Khán giả: Thấy chưa? Cô gái tội nghiệp\n"
	.string "quá!\p"
	.string "MC: Ơ... Nguy rồi...\p"
	.string "À... Chương trình hôm nay chỉ còn thời\n"
	.string "lượng đến đây! Cảm ơn quý vị đã theo\l"
	.string "dõi!$"

ContestLadyShow_Text_LostBadly::
	.string "MC: Xin lỗi! Cảm ơn cô đã tham gia\n"
	.string "chương trình truyền hình trực tiếp!\p"
	.string "Phần thi cuộc thi của cô diễn ra thế\n"
	.string "nào?\p"
	.string "BEAUTY: Chẳng có gì suôn sẻ cả... Không\n"
	.string "hiểu sao {STR_VAR_2} của tôi lại\l"
	.string "không giành được chút yêu thích nào.\p"
	.string "MC: Tôi không muốn nói điều này, nhưng\n"
	.string "màu sắc của POKéMON này hơi kém.\p"
	.string "BEAUTY: ... ... ... ... ... ... ...Sụt sịt... Oaaaa!\p"
	.string "Khán giả: Thấy chưa? Cô gái tội nghiệp\n"
	.string "quá!\p"
	.string "MC: Ơ... Nguy rồi...\p"
	.string "À... Chương trình hôm nay chỉ còn thời\n"
	.string "lượng đến đây! Cảm ơn quý vị đã theo\l"
	.string "dõi!$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global LilycoveCity_ContestLobby_Text_InterviewRequest
	.global LilycoveCity_ContestLobby_Text_DescribeContest
	.global LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX
	.global LilycoveCity_ContestLobby_Text_ThatsAllForInterview
	.global LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe
	.global LilycoveCity_ContestLobby_Text_LookingForwardToNextContest
	.global gTVBravoTrainerText00
	.global gTVBravoTrainerText01
	.global gTVBravoTrainerText02
	.global gTVBravoTrainerText03
	.global gTVBravoTrainerText04
	.global gTVBravoTrainerText05
	.global gTVBravoTrainerText06
	.global gTVBravoTrainerText07
	.global gTVBravoTrainerText08
	.global BattleFrontier_BattleTowerLobby_Text_InterviewRequest
	.global BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut
	.global BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou
	.global BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle
	.global BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned
	.global BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle
	.global BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine
	.global BattleFrontier_BattleTowerLobby_Text_SilentType
	.global BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle
	.global BravoTrainerBattleTower_Text_Intro
	.global BravoTrainerBattleTower_Text_NewRecord
	.global BravoTrainerBattleTower_Text_Lost
	.global BravoTrainerBattleTower_Text_Won
	.global BravoTrainerBattleTower_Text_LostFinal
	.global BravoTrainerBattleTower_Text_Satisfied
	.global BravoTrainerBattleTower_Text_Unsatisfied
	.global BravoTrainerBattleTower_Text_None1
	.global BravoTrainerBattleTower_Text_None2
	.global BravoTrainerBattleTower_Text_None3
	.global BravoTrainerBattleTower_Text_None4
	.global BravoTrainerBattleTower_Text_ResponseSatisfied
	.global BravoTrainerBattleTower_Text_ResponseUnsatisfied
	.global BravoTrainerBattleTower_Text_Outro
	.global SlateportCity_PokemonFanClub_Text_InterviewRequestHasName
	.global SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers
	.global SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon
	.global SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike
	.global SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon
	.global SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou
	.global SlateportCity_PokemonFanClub_Text_ThatsAllForInterview
	.global SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe
	.global SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews
	.global SlateportCity_PokemonFanClub_Text_InterviewRequest
	.global SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon
	.global SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2
	.global gTVFanClubOpinionsText00
	.global gTVFanClubOpinionsText01
	.global gTVFanClubOpinionsText02
	.global gTVFanClubOpinionsText03
	.global gTVFanClubOpinionsText04
	.global gTVFanClubText00
	.global gTVFanClubText01
	.global gTVFanClubText02
	.global gTVFanClubText03
	.global gTVFanClubText04
	.global gTVFanClubText05
	.global gTVFanClubText06
	.global gTVFanClubText07
	.global SlateportCity_OceanicMuseum_1F_Text_InterviewRequest
	.global SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort
	.global SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon
	.global SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory
	.global SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview
	.global SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory
	.global gTVRecentHappeningsText00
	.global gTVRecentHappeningsText01
	.global gTVRecentHappeningsText02
	.global gTVRecentHappeningsText03
	.global gTVRecentHappeningsText04
	.global gTVRecentHappeningsText05
	.global gTVMassOutbreakText00
	.global gTV3CheersForPokeblocksText00
	.global gTV3CheersForPokeblocksText01
	.global gTV3CheersForPokeblocksText02
	.global gTV3CheersForPokeblocksText03
	.global gTV3CheersForPokeblocksText04
	.global gTV3CheersForPokeblocksText05
	.global LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer
	.global LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink
	.global LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer
	.global LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2
	.global LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer
	.global LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2
	.global LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer
	.global LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo
	.global LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial
	.global gTVTrainerFanClubSpecialText00
	.global gTVTrainerFanClubSpecialText01
	.global gTVTrainerFanClubSpecialText02
	.global gTVTrainerFanClubSpecialText03
	.global gTVTrainerFanClubSpecialText04
	.global gTVTrainerFanClubSpecialText05
	.global gTVNameRaterText00
	.global gTVNameRaterText01
	.global gTVNameRaterText02
	.global gTVNameRaterText03
	.global gTVNameRaterText04
	.global gTVNameRaterText05
	.global gTVNameRaterText06
	.global gTVNameRaterText07
	.global gTVNameRaterText08
	.global gTVNameRaterText09
	.global gTVNameRaterText10
	.global gTVNameRaterText11
	.global gTVNameRaterText12
	.global gTVNameRaterText13
	.global gTVNameRaterText14
	.global gTVNameRaterText15
	.global gTVNameRaterText16
	.global gTVNameRaterText17
	.global gTVNameRaterText18
	.global gTVPokemonAnglerText00
	.global gTVPokemonAnglerText01
	.global gTVPokemonTodayFailedText00
	.global gTVPokemonTodayFailedText01
	.global gTVPokemonTodayFailedText02
	.global gTVPokemonTodayFailedText03
	.global gTVPokemonTodayFailedText04
	.global gTVPokemonTodayFailedText05
	.global gTVPokemonTodayFailedText06
	.global gTVPokemonTodaySuccessfulText00
	.global gTVPokemonTodaySuccessfulText01
	.global gTVPokemonTodaySuccessfulText02
	.global gTVPokemonTodaySuccessfulText03
	.global gTVPokemonTodaySuccessfulText04
	.global gTVPokemonTodaySuccessfulText05
	.global gTVPokemonTodaySuccessfulText06
	.global gTVPokemonTodaySuccessfulText07
	.global gTVPokemonTodaySuccessfulText08
	.global gTVPokemonTodaySuccessfulText09
	.global gTVPokemonTodaySuccessfulText10
	.global gTVPokemonTodaySuccessfulText11
	.global SmartShopper_Text_Intro
	.global SmartShopper_Text_ClerkNormal
	.global SmartShopper_Text_RandomComment1
	.global SmartShopper_Text_RandomComment2
	.global SmartShopper_Text_RandomComment3
	.global SmartShopper_Text_RandomComment4
	.global SmartShopper_Text_SecondItem
	.global SmartShopper_Text_ThirdItem
	.global SmartShopper_Text_DuringSale
	.global SmartShopper_Text_OutroNormal
	.global SmartShopper_Text_IsVIP
	.global SmartShopper_Text_ClerkMax
	.global SmartShopper_Text_OutroMax
	.global gTVWorldOfMastersText00
	.global gTVWorldOfMastersText01
	.global gTVWorldOfMastersText02
	.global gTVTodaysRivalTrainerText00
	.global gTVTodaysRivalTrainerText07
	.global gTVTodaysRivalTrainerText08
	.global gTVTodaysRivalTrainerText09
	.global gTVTodaysRivalTrainerText10
	.global gTVTodaysRivalTrainerText01
	.global gTVTodaysRivalTrainerText02
	.global gTVTodaysRivalTrainerText03
	.global gTVTodaysRivalTrainerText04
	.global gTVTodaysRivalTrainerText05
	.global gTVTodaysRivalTrainerText06
	.global TrendWatcher_Text_Intro
	.global TrendWatcher_Text_MaleTaughtMePhrase
	.global TrendWatcher_Text_FemaleTaughtMePhrase
	.global TrendWatcher_Text_PhraseWasHopeless
	.global TrendWatcher_Text_MaleTellMeBigger
	.global TrendWatcher_Text_FemaleTellMeBigger
	.global TrendWatcher_Text_Outro
	.global gTVHoennTreasureInvestigatorsText00
	.global gTVHoennTreasureInvestigatorsText01
	.global gTVHoennTreasureInvestigatorsText02
	.global gTVFindThatGamerText00
	.global gTVFindThatGamerText01
	.global gTVFindThatGamerText02
	.global gTVFindThatGamerText03
	.global gTVBreakingNewsText00
	.global gTVBreakingNewsText01
	.global gTVBreakingNewsText02
	.global gTVBreakingNewsText03
	.global gTVBreakingNewsText04
	.global gTVBreakingNewsText05
	.global gTVBreakingNewsText06
	.global gTVBreakingNewsText07
	.global gTVBreakingNewsText12
	.global gTVBreakingNewsText08
	.global gTVBreakingNewsText09
	.global gTVBreakingNewsText10
	.global gTVBreakingNewsText11
	.global gTVSecretBaseVisitText00
	.global gTVSecretBaseVisitText01
	.global gTVSecretBaseVisitText02
	.global gTVSecretBaseVisitText03
	.global gTVSecretBaseVisitText04
	.global gTVSecretBaseVisitText05
	.global gTVSecretBaseVisitText06
	.global gTVSecretBaseVisitText07
	.global gTVSecretBaseVisitText08
	.global gTVSecretBaseVisitText09
	.global gTVSecretBaseVisitText10
	.global gTVSecretBaseVisitText11
	.global gTVSecretBaseVisitText12
	.global gTVSecretBaseVisitText13
	.global gTVPokemonLotteryWinnerFlashReportText00
	.global gTVThePokemonBattleSeminarText00
	.global gTVThePokemonBattleSeminarText01
	.global gTVThePokemonBattleSeminarText02
	.global gTVThePokemonBattleSeminarText03
	.global gTVThePokemonBattleSeminarText04
	.global gTVThePokemonBattleSeminarText05
	.global gTVThePokemonBattleSeminarText06
	.global gTVTrainerFanClubText00
	.global gTVTrainerFanClubText01
	.global gTVTrainerFanClubText02
	.global gTVTrainerFanClubText03
	.global gTVTrainerFanClubText04
	.global gTVTrainerFanClubText05
	.global gTVTrainerFanClubText06
	.global gTVTrainerFanClubText07
	.global gTVTrainerFanClubText08
	.global gTVTrainerFanClubText09
	.global gTVTrainerFanClubText10
	.global gTVTrainerFanClubText11
	.global TVSpotTheCuties_Text_Intro
	.global TVSpotTheCuties_Text_RibbonsLow
	.global TVSpotTheCuties_Text_RibbonsMid
	.global TVSpotTheCuties_Text_RibbonsHigh
	.global TVSpotTheCuties_Text_RibbonIntro
	.global TVSpotTheCuties_Text_RibbonChampion
	.global TVSpotTheCuties_Text_RibbonCool
	.global TVSpotTheCuties_Text_RibbonBeauty
	.global TVSpotTheCuties_Text_RibbonCute
	.global TVSpotTheCuties_Text_RibbonSmart
	.global TVSpotTheCuties_Text_RibbonTough
	.global TVSpotTheCuties_Text_RibbonWinning
	.global TVSpotTheCuties_Text_RibbonVictory
	.global TVSpotTheCuties_Text_RibbonArtist
	.global TVSpotTheCuties_Text_RibbonEffort
	.global TVSpotTheCuties_Text_Outro
	.global gTVPokemonNewsBattleFrontierText00
	.global gTVPokemonNewsBattleFrontierText01
	.global gTVPokemonNewsBattleFrontierText02
	.global gTVPokemonNewsBattleFrontierText03
	.global gTVPokemonNewsBattleFrontierText04
	.global gTVPokemonNewsBattleFrontierText05
	.global gTVPokemonNewsBattleFrontierText06
	.global gTVPokemonNewsBattleFrontierText07
	.global gTVPokemonNewsBattleFrontierText08
	.global gTVPokemonNewsBattleFrontierText09
	.global gTVPokemonNewsBattleFrontierText10
	.global gTVPokemonNewsBattleFrontierText11
	.global gTVPokemonNewsBattleFrontierText12
	.global gTVPokemonNewsBattleFrontierText13
	.global gTVPokemonNewsBattleFrontierText14
	.global gTVPokemonNewsBattleFrontierText15
	.global gTVPokemonNewsBattleFrontierText16
	.global gTVPokemonNewsBattleFrontierText17
	.global gTVPokemonNewsBattleFrontierText18
	.global gTVWhatsNo1InHoennTodayText00
	.global gTVWhatsNo1InHoennTodayText01
	.global gTVWhatsNo1InHoennTodayText02
	.global gTVWhatsNo1InHoennTodayText03
	.global gTVWhatsNo1InHoennTodayText04
	.global gTVWhatsNo1InHoennTodayText05
	.global gTVWhatsNo1InHoennTodayText06
	.global gTVWhatsNo1InHoennTodayText07
	.global gTVWhatsNo1InHoennTodayText08
	.global TVSecretBaseSecrets_Text_Intro
	.global TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1
	.global TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2
	.global TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving
	.global TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer
	.global TVSecretBaseSecrets_Text_PlayerEnjoyedBase
	.global TVSecretBaseSecrets_Text_PlayerHugeFanOfBase
	.global TVSecretBaseSecrets_Text_Outro
	.global TVSecretBaseSecrets_Text_StoppedMoving1
	.global TVSecretBaseSecrets_Text_StoppedMoving2
	.global TVSecretBaseSecrets_Text_UsedChair
	.global TVSecretBaseSecrets_Text_UsedBalloon
	.global TVSecretBaseSecrets_Text_UsedTent
	.global TVSecretBaseSecrets_Text_UsedPlant
	.global TVSecretBaseSecrets_Text_UsedGoldShield
	.global TVSecretBaseSecrets_Text_UsedSilverShield
	.global TVSecretBaseSecrets_Text_UsedGlassOrnament
	.global TVSecretBaseSecrets_Text_UsedTV
	.global TVSecretBaseSecrets_Text_UsedMudBall
	.global TVSecretBaseSecrets_Text_UsedBag
	.global TVSecretBaseSecrets_Text_UsedCushion
	.global TVSecretBaseSecrets_Text_HitCushion
	.global TVSecretBaseSecrets_Text_HuggedCushion
	.global TVSecretBaseSecrets_Text_BattledWon
	.global TVSecretBaseSecrets_Text_BattledLost
	.global TVSecretBaseSecrets_Text_DeclinedBattle
	.global TVSecretBaseSecrets_Text_UsedPoster
	.global TVSecretBaseSecrets_Text_UsedNoteMat
	.global TVSecretBaseSecrets_Text_BattledDraw
	.global TVSecretBaseSecrets_Text_UsedSpinMat
	.global TVSecretBaseSecrets_Text_UsedSandOrnament
	.global TVSecretBaseSecrets_Text_UsedDesk
	.global TVSecretBaseSecrets_Text_UsedBrick
	.global TVSecretBaseSecrets_Text_UsedSolidBoard
	.global TVSecretBaseSecrets_Text_UsedFence
	.global TVSecretBaseSecrets_Text_UsedGlitterMat
	.global TVSecretBaseSecrets_Text_UsedTire
	.global TVSecretBaseSecrets_Text_UsedStand
	.global TVSecretBaseSecrets_Text_BrokeDoor
	.global TVSecretBaseSecrets_Text_UsedDoll
	.global TVSecretBaseSecrets_Text_UsedSlide
	.global TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown
	.global TVSecretBaseSecrets_Text_UsedJumpMat
	.global gTVSafariFanClubText00
	.global gTVSafariFanClubText01
	.global gTVSafariFanClubText02
	.global gTVSafariFanClubText03
	.global gTVSafariFanClubText04
	.global gTVSafariFanClubText05
	.global gTVSafariFanClubText06
	.global gTVSafariFanClubText07
	.global gTVSafariFanClubText08
	.global gTVSafariFanClubText09
	.global gTVSafariFanClubText10
	.global ContestLiveUpdates_Text_Intro
	.global ContestLiveUpdates_Text_WonBothRounds
	.global ContestLiveUpdates_Text_BetterRound2
	.global ContestLiveUpdates_Text_EqualRounds
	.global ContestLiveUpdates_Text_BetterRound1
	.global ContestLiveUpdates_Text_GotNervous
	.global ContestLiveUpdates_Text_StartledFoes
	.global ContestLiveUpdates_Text_UsedCombo
	.global ContestLiveUpdates_Text_ExcitingAppeal
	.global ContestLiveUpdates_Text_WasCool
	.global ContestLiveUpdates_Text_WasBeautiful
	.global ContestLiveUpdates_Text_WasCute
	.global ContestLiveUpdates_Text_WasSmart
	.global ContestLiveUpdates_Text_WasTough
	.global ContestLiveUpdates_Text_VeryExcitingAppeal
	.global ContestLiveUpdates_Text_VeryCool
	.global ContestLiveUpdates_Text_VeryBeautiful
	.global ContestLiveUpdates_Text_VeryCute
	.global ContestLiveUpdates_Text_VerySmart
	.global ContestLiveUpdates_Text_VeryTough
	.global ContestLiveUpdates_Text_TookBreak
	.global ContestLiveUpdates_Text_GotStartled
	.global ContestLiveUpdates_Text_MoveWonderful
	.global ContestLiveUpdates_Text_TalkAboutAnotherMon
	.global ContestLiveUpdates_Text_FailedToAppeal
	.global ContestLiveUpdates_Text_LastInBothRounds
	.global ContestLiveUpdates_Text_NotExcitingEnough
	.global ContestLiveUpdates_Text_LostAfterWinningRound1
	.global ContestLiveUpdates_Text_NeverExciting
	.global ContestLiveUpdates_Text_LostBySmallMargin
	.global ContestLiveUpdates_Text_RepeatedAppeals
	.global ContestLiveUpdates_Text_ValiantEffortButLost
	.global ContestLiveUpdates_Text_Outro
	.global gTVPokemonBattleUpdateText00
	.global gTVPokemonBattleUpdateText01
	.global gTVPokemonBattleUpdateText02
	.global gTVPokemonBattleUpdateText03
	.global gTVPokemonBattleUpdateText04
	.global gTVPokemonBattleUpdateText05
	.global gTVPokemonBattleUpdateText06
	.global gTVPokemonBattleUpdateText07
	.global GabbyAndTy_Text_GabbyPreFirstBattle
	.global GabbyAndTy_Text_GabbyIntro
	.global GabbyAndTy_Text_GabbyDefeatFirstTime
	.global GabbyAndTy_Text_WhoAreYouInterview
	.global GabbyAndTy_Text_QuoteFromLastInterview
	.global GabbyAndTy_Text_YouStompedUsInterviewAgain
	.global GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain
	.global GabbyAndTy_Text_CleverItemSkillsInterviewAgain
	.global GabbyAndTy_Text_WeLookedRespectableInterviewAgain
	.global GabbyAndTy_Text_InterviewAgain
	.global GabbyAndTy_Text_DescribeYourFeelings
	.global GabbyAndTy_Text_PerfectWellBeSeeingYou
	.global GabbyAndTy_Text_DontGiveUpKeepingEyeOut
	.global GabbyAndTy_Text_KeepingAnEyeOutForYou
	.global GabbyAndTy_Text_GabbyNotEnoughMons
	.global GabbyAndTy_Text_GiveUsAnInterviewThisTime
	.global GabbyAndTy_Text_GabbyDefeat
	.global GabbyAndTy_Text_TyPreFirstBattle
	.global GabbyAndTy_Text_TyIntro
	.global GabbyAndTy_Text_TyPostBattle
	.global GabbyAndTy_Text_TyNotEnoughMons
	.global GabbyAndTy_Text_TyDefeatFirstTime
	.global GabbyAndTy_Text_TyDefeat
	.global gTVInSearchOfTrainersText00
	.global gTVInSearchOfTrainersText01
	.global gTVInSearchOfTrainersText02
	.global gTVInSearchOfTrainersText03
	.global gTVInSearchOfTrainersText04
	.global gTVInSearchOfTrainersText05
	.global gTVInSearchOfTrainersText06
	.global gTVInSearchOfTrainersText07
	.global gTVInSearchOfTrainersText08
	.global ContestLadyShow_Text_Intro
	.global ContestLadyShow_Text_Won
	.global ContestLadyShow_Text_Lost
	.global ContestLadyShow_Text_LostBadly
@ END GENERATED LOCALIZATION EXPORTS
