VerdanturfTown_House_MapScripts::
	.byte 0

VerdanturfTown_House_EventScript_Woman1::
	msgbox VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague, MSGBOX_NPC
	end

VerdanturfTown_House_EventScript_Woman2::
	msgbox VerdanturfTown_House_Text_DefeatEliteFourInARow, MSGBOX_NPC
	end

VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague:
	.string "Ở nơi xa xôi, sâu trong EVER GRANDE\n"
	.string "CITY, có POKéMON LEAGUE.\p"
	.string "Những HLV tụ hội ở đó đều tài giỏi\n"
	.string "đến đáng sợ.$"

VerdanturfTown_House_Text_DefeatEliteFourInARow:
	.string "Tôi nghĩ luật của POKéMON LEAGUE yêu\n"
	.string "cầu bạn phải liên tiếp đấu với toàn bộ\l"
	.string "ELITE FOUR.\p"
	.string "Nếu thua bất kỳ ai trong số họ, bạn phải\n"
	.string "bắt đầu thử thách lại từ người đầu\l"
	.string "tiên.$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague
	.global VerdanturfTown_House_Text_DefeatEliteFourInARow
@ END GENERATED LOCALIZATION EXPORTS
