SeafloorCavern_Entrance_MapScripts::
	map_script MAP_SCRIPT_ON_RESUME, SeafloorCavern_Entrance_OnResume
	.byte 0

SeafloorCavern_Entrance_OnResume:
	setdivewarp MAP_UNDERWATER_SEAFLOOR_CAVERN, 6, 5
	setescapewarp MAP_UNDERWATER_SEAFLOOR_CAVERN, 6, 5
	end

SeafloorCavern_Entrance_EventScript_Grunt::
	lockall
	goto_if_eq VAR_HAS_TALKED_TO_SEAFLOOR_CAVERN_ENTRANCE_GRUNT, 1, SeafloorCavern_Entrance_EventScript_GruntSpeechShort
	waitse
	playse SE_PIN
	applymovement LOCALID_SEAFLOOR_CAVERN_ENTRANCE_GRUNT, Common_Movement_ExclamationMark
	waitmovement 0
	applymovement LOCALID_SEAFLOOR_CAVERN_ENTRANCE_GRUNT, Common_Movement_Delay48
	waitmovement 0
	delay 20
	call_if_eq VAR_FACING, DIR_WEST, SeafloorCavern_Entrance_EventScript_GruntFacePlayerWest
	call_if_eq VAR_FACING, DIR_EAST, SeafloorCavern_Entrance_EventScript_GruntFacePlayerEast
	call_if_eq VAR_FACING, DIR_NORTH, SeafloorCavern_Entrance_EventScript_GruntFacePlayerNorth
	delay 30
	setvar VAR_HAS_TALKED_TO_SEAFLOOR_CAVERN_ENTRANCE_GRUNT, 1
	copyobjectxytoperm LOCALID_SEAFLOOR_CAVERN_ENTRANCE_GRUNT
	msgbox SeafloorCavern_Entrance_Text_HearMagmaNearMossdeep, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_SEAFLOOR_CAVERN_ENTRANCE_GRUNT, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	releaseall
	end

SeafloorCavern_Entrance_EventScript_GruntSpeechShort::
	call_if_eq VAR_FACING, DIR_WEST, SeafloorCavern_Entrance_EventScript_GruntFacePlayerWest
	call_if_eq VAR_FACING, DIR_EAST, SeafloorCavern_Entrance_EventScript_GruntFacePlayerEast
	call_if_eq VAR_FACING, DIR_NORTH, SeafloorCavern_Entrance_EventScript_GruntFacePlayerNorth
	msgbox SeafloorCavern_Entrance_Text_HearMagmaNearMossdeepShort, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_SEAFLOOR_CAVERN_ENTRANCE_GRUNT, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	releaseall
	end

SeafloorCavern_Entrance_EventScript_GruntFacePlayerEast::
	applymovement LOCALID_SEAFLOOR_CAVERN_ENTRANCE_GRUNT, Common_Movement_WalkInPlaceFasterLeft
	waitmovement 0
	return

SeafloorCavern_Entrance_EventScript_GruntFacePlayerWest::
	applymovement LOCALID_SEAFLOOR_CAVERN_ENTRANCE_GRUNT, Common_Movement_WalkInPlaceFasterRight
	waitmovement 0
	return

SeafloorCavern_Entrance_EventScript_GruntFacePlayerNorth::
	applymovement LOCALID_SEAFLOOR_CAVERN_ENTRANCE_GRUNT, Common_Movement_WalkInPlaceFasterDown
	waitmovement 0
	return

SeafloorCavern_Entrance_Text_HearMagmaNearMossdeep:
	.string "Này! Ta nhớ mặt ngươi!\p"
	.string "Ngươi đã đến đây thì chắc lại định phá\n"
	.string "bọn ta chứ gì!\p"
	.string "Một nhóc ranh như ngươi mà cũng nghĩ\n"
	.string "mình có thể đối đầu với TEAM AQUA sao?\p"
	.string "Ta nói ngươi còn non cả nghìn tỷ năm!\p"
	.string "Ngươi chỉ xứng nhập bọn với TEAM\n"
	.string "MAGMA thôi!\p"
	.string "Nhắc đến TEAM MAGMA, nghe nói chúng đã\n"
	.string "xuất hiện gần MOSSDEEP.\p"
	.string "Lũ côn đồ đó chẳng hợp với biển chút\n"
	.string "nào!$"

SeafloorCavern_Entrance_Text_HearMagmaNearMossdeepShort:
	.string "Một nhóc ranh như ngươi mà cũng nghĩ\n"
	.string "mình có thể đối đầu với TEAM AQUA sao?\p"
	.string "Ta nói ngươi còn non cả nghìn tỷ năm!\p"
	.string "Ngươi chỉ xứng nhập bọn với TEAM\n"
	.string "MAGMA thôi!\p"
	.string "Nhắc đến TEAM MAGMA, nghe nói chúng đã\n"
	.string "xuất hiện gần MOSSDEEP.\p"
	.string "Lũ côn đồ đó chẳng hợp với biển chút\n"
	.string "nào!$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global SeafloorCavern_Entrance_Text_HearMagmaNearMossdeep
	.global SeafloorCavern_Entrance_Text_HearMagmaNearMossdeepShort
@ END GENERATED LOCALIZATION EXPORTS
