OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "Khi trận đấu POKéMON bắt đầu, con đứng\n"
	.string "bên trái danh sách sẽ ra sân trước.\p"
	.string "Vì vậy, khi có thêm POKéMON trong đội,\n"
	.string "hãy thử thay đổi thứ tự các POKéMON.\p"
	.string "Việc đó có thể mang lại lợi thế cho cậu.$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global OldaleTown_House1_Text_LeftPokemonGoesOutFirst
@ END GENERATED LOCALIZATION EXPORTS
