.set NUM_OPPONENTS, VAR_0x8009

BerryBlender_Text_WantToMakePokeblocks:
	.string "Ồ? Cháu muốn làm vài {POKEBLOCK}S cùng\n"
	.string "ông già này sao?$"

BerryBlender_Text_Excellent:
	.string "Tuyệt lắm!$"

BerryBlender_Text_MadeOldTimerSad:
	.string "Ôi... Cháu làm ông già này buồn rồi...$"

BerryBlender_Text_KnowHowToMakePokeblocks:
	.string "Cháu có biết cách làm một {POKEBLOCK}\n"
	.string "không?$"

BerryBlender_Text_LetsBerryBlender:
	.string "Vậy bắt đầu thôi!\p"
	.string "Cùng BERRY BLENDER nào!$"

BerryBlender_Text_ExplainBerryBlending:
	.string "Được rồi, để ta giải thích một chút.\p"
	.string "Đừng lo, đơn giản lắm.\p"
	.string "Khi mũi tên của BLENDER đến ký hiệu của\n"
	.string "cháu, chỉ cần nhấn A Button.\p"
	.string "Cháu chỉ cần làm vậy thôi. Thử rồi sẽ\n"
	.string "thấy dễ đến mức nào.$"

BerryBlender_Text_DontHaveAnyBerries:
	.string "Ồ? Cháu không có BERRIES sao?\p"
	.string "Không có BERRIES thì cháu không thể\n"
	.string "làm {POKEBLOCK}S.$"

BerryBlender_Text_CanHaveOneOfMyBerries:
	.string "Như vậy thì không được rồi, phải\n"
	.string "không?\p"
	.string "Nếu cháu không chê đồ còn dư, ta có thể\n"
	.string "cho cháu một trong số BERRIES của\l"
	.string "mình.\p"
	.string "Như vậy, chúng ta có thể cùng dùng\n"
	.string "BERRY BLENDER để làm vài {POKEBLOCK}S.$"

BerryBlender_Text_DontHaveAnyBerriesToSpare:
	.string "Nếu còn dư BERRIES, ta rất sẵn lòng cho\n"
	.string "cháu một quả...\p"
	.string "Nhưng hôm nay ta không còn quả nào để\n"
	.string "cho cả. Đành để lần khác vậy.$"

BerryBlender_Text_PokeblockCaseIsFull:
	.string "Nhưng {POKEBLOCK} CASE của cháu đã\n"
	.string "đầy.\p"
	.string "Cháu nên dùng bớt vài {POKEBLOCK}S\n"
	.string "trước khi quay lại gặp ta.$"

BerryBlender_Text_DontHavePokeblockCase:
	.string "Nhưng cháu không có {POKEBLOCK} CASE.\p"
	.string "Cháu nên kiếm một {POKEBLOCK} CASE rồi\n"
	.string "quay lại gặp ta.$"

BerryBlender_Text_LetsGetBlendingAlready:
	.string "Bắt tay trộn ngay thôi nào!$"

BerryBlender_Text_WhatKindOfPokeblockWillIGet:
	.string "Không biết mình sẽ nhận được loại\n"
	.string "{POKEBLOCK} nào nhỉ? Hồi hộp quá!$"

BerryBlender_Text_WantToBlendPokeblocksWithUs:
	.string "Chào bạn! Bạn muốn trộn vài\n"
	.string "{POKEBLOCK}S cùng bọn mình không?$"

BerryBlender_Text_Okay:
	.string "Được thôi!$"

BerryBlender_Text_ThatsTooBad:
	.string "Tiếc quá...\p"
	.string "Nhưng bất cứ khi nào bạn muốn trộn, bọn\n"
	.string "mình vẫn luôn ở đây!$"

BerryBlender_Text_KnowHowToMakePokeblocks2:
	.string "Tất nhiên là bạn biết cách trộn\n"
	.string "{POKEBLOCK}S rồi, đúng không?$"

BerryBlender_Text_LetsBerryBlender2:
	.string "Vậy bắt đầu thôi!\p"
	.string "Cùng BERRY BLENDER nào!$"

BerryBlender_Text_ExplainBerryBlending2:
	.string "Được rồi! Để mình giải thích nhé!\p"
	.string "Khi mũi tên của BLENDER đang quay đến\n"
	.string "ký hiệu của bạn, chỉ cần nhấn A Button.\p"
	.string "Chỉ cần vậy thôi. Khá dễ, đúng không?$"

BerryBlender_Text_DontHaveAnyBerries2:
	.string "Ô, nhưng khoan đã... Bạn không có\n"
	.string "BERRIES.\p"
	.string "Không có BERRIES thì bạn không thể làm\n"
	.string "{POKEBLOCK}S...\p"
	.string "Khi nào kiếm được BERRIES để trộn thì\n"
	.string "cứ đến nhé, bọn mình sẽ luôn ở đây.$"

BerryBlender_Text_PokeblockCaseIsFull2:
	.string "Ô, nhưng khoan đã... {POKEBLOCK} CASE\n"
	.string "của bạn đã đầy.\p"
	.string "Bạn nên dùng bớt vài {POKEBLOCK}S rồi\n"
	.string "quay lại.$"

BerryBlender_Text_DontHavePokeblockCase2:
	.string "Ô, nhưng khoan đã... Bạn không có\n"
	.string "{POKEBLOCK} CASE.\p"
	.string "Bạn nên kiếm một {POKEBLOCK} CASE rồi\n"
	.string "quay lại.$"

@ Unused
BerryBlender_Text_MakePokeblocksWithOurGroup:
	.string "Ồ, chào cháu! Cháu có muốn làm vài\n"
	.string "{POKEBLOCK}S cùng nhóm nhỏ của chúng\l"
	.string "ta không?$"

BerryBlender_Text_OhDear:
	.string "Ôi chao!$"

BerryBlender_Text_LeftUsInShock:
	.string "Ôi trời ơi...\p"
	.string "Cháu làm chúng ta sốc quá!$"

BerryBlender_Text_KnowHowToMakePokeblocks3:
	.string "Tất nhiên cháu biết cách làm\n"
	.string "{POKEBLOCK}S rồi, đúng không?$"

BerryBlender_Text_LetsBerryBlender3:
	.string "Được rồi, cháu nhé! Bắt đầu thôi!\p"
	.string "Cùng BERRY BLENDER thôi!$"

BerryBlender_Text_ExplainBerryBlending3:
	.string "Ôi chao!\p"
	.string "Vậy thì ta sẽ giải thích thật dễ hiểu\n"
	.string "cho cháu.\p"
	.string "Khi mũi tên của BLENDER quay đến ký\n"
	.string "hiệu của cháu, hãy nhấn Nút A.\p"
	.string "Chỉ cần vậy thôi. Đơn giản lắm, phải\n"
	.string "không?$"

BerryBlender_Text_DontHaveAnyBerries3:
	.string "Cháu không có BERRIES nào, phải không?\p"
	.string "Không có BERRIES thì cháu không thể\n"
	.string "làm {POKEBLOCK}S.\p"
	.string "Chúng ta luôn làm {POKEBLOCK}S ở đây,\n"
	.string "nên khi có một hai quả BERRY thì hãy\l"
	.string "đến làm cùng nhau nhé.$"

BerryBlender_Text_PokeblockCaseIsFull3:
	.string "Có vẻ {POKEBLOCK} CASE của cháu đã\n"
	.string "đầy.\p"
	.string "Hãy dùng bớt vài {POKEBLOCK}S rồi quay\n"
	.string "lại nhé.$"

BerryBlender_Text_DontHavePokeblockCase3:
	.string "Có vẻ cháu vẫn chưa có {POKEBLOCK}\n"
	.string "CASE.\p"
	.string "Cháu cần lấy một {POKEBLOCK} CASE rồi\n"
	.string "hãy quay lại.$"

BerryBlender_Text_SetNewBlenderRecord:
	.string "Được rồi! Hôm nay mình nhất định sẽ lập\n"
	.string "kỷ lục tốc độ BLENDER mới!$"

BerryBlender_Text_LookGoodAtBlendingJoinUs:
	.string "Ôi chao! Trông cháu có vẻ rất giỏi pha\n"
	.string "trộn. Cháu có muốn tham gia cùng chúng\l"
	.string "ta không?$"

BerryBlender_Text_MakeDeliciousPokeblocks:
	.string "Mình sẽ làm những {POKEBLOCK}S thật\n"
	.string "ngon để POKéMON của mình đáng yêu hơn.$"

BerryBlender_Text_SaveGameBeforeBerryBlenderLink:
	.string "{POKEBLOCK}S sẽ được làm từ BERRIES\n"
	.string "cùng bạn bè bằng BERRY BLENDER.\p"
	.string "Bạn có đồng ý lưu trò chơi trước khi\n"
	.string "kết nối với bạn bè không?$"

BerryBlender_Text_SearchingForFriends:
	.string "Đang tìm bạn bè... ... ... Nút B: Hủy$"

BerryBlender_Text_Player1Arrived:
	.string "{STR_VAR_1} đã đến.$"

BerryBlender_Text_Player1And2Arrived:
	.string "{STR_VAR_1} và\n"
	.string "{STR_VAR_2} đã đến.$"

BerryBlender_Text_AllPlayersArrived:
	.string "{STR_VAR_1}, {STR_VAR_2}\n"
	.string "và {STR_VAR_3} đã đến.$"

BerryBlender_Text_NoBerriesLink:
	.string "Bạn không có BERRIES. Không thể dùng\n"
	.string "BERRY BLENDER.$"

BerryBlender_Text_PokeblockCaseIsFullLink:
	.string "{POKEBLOCK} CASE của bạn đã đầy. Không\n"
	.string "thể dùng BERRY BLENDER.$"

BerryBlender_Text_DontHavePokeblockCaseLink:
	.string "Bạn không có {POKEBLOCK} CASE. Không\n"
	.string "thể dùng BERRY BLENDER.$"

BerryBlender_Text_LoveMakingPokeblocks:
	.string "Mình rất thích làm {POKEBLOCK}S.\p"
	.string "Mình luôn mang theo vài quả BERRIES.$"

BerryBlender_Text_MakePokeblocksUsingBerryBlender:
	.string "Nếu bạn muốn, chúng ta có thể cùng làm\n"
	.string "vài {POKEBLOCK}S bằng BERRY BLENDER.$"

BerryBlender_Text_DontHaveAnyBerriesHaveOne:
	.string "Ồ? Bạn không có BERRIES nào sao?\p"
	.string "Thế thì không ổn chút nào, phải không?\p"
	.string "Nếu bạn không ngại quả còn dư, tôi có\n"
	.string "thể cho bạn một quả trong số BERRIES\l"
	.string "của mình.$"

BerryBlender_Text_UseItToMakePokeblocksTogether:
	.string "Chúng ta sẽ dùng nó để cùng làm\n"
	.string "{POKEBLOCK}S bằng BERRY BLENDER.$"

BerryBlender_Text_DontHaveAnyBerriesNoneToSpare:
	.string "Ồ? Bạn không có BERRIES nào sao?\p"
	.string "Nếu còn dư, tôi sẵn lòng cho bạn một\n"
	.string "quả...\p"
	.string "Nhưng hôm nay tôi không có quả nào để\n"
	.string "cho. Xin lỗi nhé.$"

BerryBlender_EventScript_BerryBlender1::
	lockall
	goto_if_unset FLAG_HIDE_LILYCOVE_CONTEST_HALL_BLEND_MASTER, BerryBlender_EventScript_BlendMasterPresent
	setvar NUM_OPPONENTS, 1
	applymovement LOCALID_BLEND_MASTER, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_WantToMakePokeblocks, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryUseBerryBlender1
	goto BerryBlender_EventScript_DeclineBlender1
	end

BerryBlender_EventScript_DeclineBlender1:
	msgbox BerryBlender_Text_MadeOldTimerSad, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1NoBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerries, MSGBOX_DEFAULT
	dotimebasedevents
	goto_if_set FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY, BerryBlender_EventScript_Blender1NoSpareBerries
	goto BerryBlender_EventScript_Blender1GiveSpareBerry
	end

BerryBlender_EventScript_Blender1NoSpareBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerriesToSpare, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1GiveSpareBerry:
	msgbox BerryBlender_Text_CanHaveOneOfMyBerries, MSGBOX_DEFAULT
	giveitem ITEM_PECHA_BERRY
	setflag FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY
	goto BerryBlender_EventScript_UseBerryBlender1
	end

BerryBlender_EventScript_UseBerryBlender1:
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_StartBlender1
	goto BerryBlender_EventScript_ExplainBlending1
	end

BerryBlender_EventScript_StartBlender1:
	msgbox BerryBlender_Text_LetsBerryBlender, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending1:
	msgbox BerryBlender_Text_ExplainBerryBlending, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender1
	end

BerryBlender_EventScript_TryUseBerryBlender1:
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender1NoCase
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_Blender1CaseFull
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender1NoBerries
	msgbox BerryBlender_Text_Excellent, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_UseBerryBlender1
	end

BerryBlender_EventScript_DoBerryBlending:
	copyvar VAR_0x8004, NUM_OPPONENTS
	fadescreen FADE_TO_BLACK
	special DoBerryBlending
	releaseall
	end

BerryBlender_EventScript_Blender1CaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFull, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1NoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCase, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BerryBlender2::
	lockall
	setvar NUM_OPPONENTS, 2
	applymovement LOCALID_CONTEST_LOBBY_BLENDER_2_PARTICIPANT, Common_Movement_FaceOriginalDirection
	applymovement LOCALID_CONTEST_LOBBY_BLENDER_2_LEADER, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_WantToBlendPokeblocksWithUs, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryUseBerryBlender2
	goto BerryBlender_EventScript_DeclineBlender2
	end

BerryBlender_EventScript_DeclineBlender2:
	msgbox BerryBlender_Text_ThatsTooBad, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2NoBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerries2, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_UseBerryBlender2:
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks2, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_StartBlender2
	goto BerryBlender_EventScript_ExplainBlending2
	end

BerryBlender_EventScript_StartBlender2:
	msgbox BerryBlender_Text_LetsBerryBlender2, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending2:
	msgbox BerryBlender_Text_ExplainBerryBlending2, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender2
	end

BerryBlender_EventScript_TryUseBerryBlender2:
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender2NoBerries
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender2NoCase
	msgbox BerryBlender_Text_Okay, MSGBOX_DEFAULT
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_UseBerryBlender2
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_Blender2CaseFull
	end

BerryBlender_EventScript_Blender2CaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFull2, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2NoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCase2, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BerryBlender3::
	lockall
	setvar VAR_0x8008, LOCALID_CONTEST_LOBBY_BLENDER_3_LEADER
	setvar NUM_OPPONENTS, 3
	applymovement LOCALID_CONTEST_LOBBY_BLENDER_3_PARTICIPANT_1, Common_Movement_FaceOriginalDirection
	applymovement LOCALID_CONTEST_LOBBY_BLENDER_3_PARTICIPANT_2, Common_Movement_FaceOriginalDirection
	applymovement VAR_0x8008, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_LookGoodAtBlendingJoinUs, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryUseBlender3
	goto BerryBlender_EventScript_DeclineBlender3
	end

BerryBlender_EventScript_DeclineBlender3:
	msgbox BerryBlender_Text_LeftUsInShock, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender3NoBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerries3, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_UseBerryBlender3:
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks3, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_StartBlender3
	goto BerryBlender_EventScript_ExplainBlending3
	end

BerryBlender_EventScript_StartBlender3:
	msgbox BerryBlender_Text_LetsBerryBlender3, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending3:
	msgbox BerryBlender_Text_ExplainBerryBlending3, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender3
	end

BerryBlender_EventScript_TryUseBlender3:
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender3NoBerries
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender3NoCase
	msgbox BerryBlender_Text_OhDear, MSGBOX_DEFAULT
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_UseBerryBlender3
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_Blender3CaseFull
	end

BerryBlender_EventScript_Blender3CaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFull3, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender3NoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCase3, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterPresent:
	lockall
	setvar NUM_OPPONENTS, 1
	msgbox BerryBlender_Text_SeeMyMasteryInAction, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryBlendWithBlendMaster
	msgbox BerryBlender_Text_TooBusyNowIsee, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterNoBerries:
	msgbox BerryBlender_Text_BlendMasterNoBerries, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_TryBlendWithBlendMaster:
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_BlendMasterNoCase
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_BlendMasterNoBerries
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_BlendWithBlendMaster
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_BlendMasterCaseFull
	end

BerryBlender_EventScript_BlendWithBlendMaster:
	msgbox BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks, MSGBOX_YESNO
	call_if_eq VAR_RESULT, NO, BerryBlender_EventScript_BlendMasterExplainBlending
	msgbox BerryBlender_Text_BlendMasterLetsBerryBlender, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_BlendMasterExplainBlending:
	msgbox BerryBlender_Text_BlendMasterExplainBerryBlending, MSGBOX_DEFAULT
	return

BerryBlender_EventScript_BlendMasterNoCase:
	msgbox BerryBlender_Text_BlendMasterNoPokeblockCase, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterCaseFull:
	msgbox BerryBlender_Text_BlendMasterPokeblockCaseFull, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2Man::
	msgbox BerryBlender_Text_SetNewBlenderRecord, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender3PokefanF::
	msgbox BerryBlender_Text_LookGoodAtBlendingJoinUs, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender2Twin::
	msgbox BerryBlender_Text_MakeDeliciousPokeblocks, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender1ExpertM::
	setvar VAR_0x8008, 15
	goto BerryBlender_EventScript_ExpertMCheckGiveBerry
	end

BerryBlender_EventScript_ExpertMCheckGiveBerry:
	lock
	faceplayer
	msgbox BerryBlender_Text_LoveMakingPokeblocks, MSGBOX_DEFAULT
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, TRUE, BerryBlender_EventScript_ExpertMPlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_ExpertMNoBerries
	end

BerryBlender_EventScript_ExpertMPlayerHasBerries:
	msgbox BerryBlender_Text_MakePokeblocksUsingBerryBlender, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_ExpertMNoBerries:
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_ExpertMNoSpareBerries
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_ExpertMNoSpareBerries
	dotimebasedevents
	goto_if_set FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY, BerryBlender_EventScript_ExpertMNoSpareBerries
	goto BerryBlender_EventScript_ExpertMGiveBerry
	end

BerryBlender_EventScript_ExpertMNoSpareBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerriesNoneToSpare, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_ExpertMGiveBerry:
	msgbox BerryBlender_Text_DontHaveAnyBerriesHaveOne, MSGBOX_DEFAULT
	giveitem ITEM_PECHA_BERRY
	setflag FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY
	msgbox BerryBlender_Text_UseItToMakePokeblocksTogether, MSGBOX_DEFAULT
	release
	end

BerryBlender_Movement_BlendLeaderWalkInPlace:
	walk_in_place_faster_right
	step_end

BerryBlender_EventScript_BerryBlenderLink::
	lockall
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_LinkBlenderNoBerries
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_LinkBlenderNoCase
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_LinkBlenderSaveGame
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_LinkBlenderCaseFull
	end

BerryBlender_EventScript_LinkBlenderSaveGame:
	msgbox BerryBlender_Text_SaveGameBeforeBerryBlenderLink, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryDoLinkBlender
	goto_if_eq VAR_RESULT, NO, BerryBlender_EventScript_CancelLinkBlender
	end

BerryBlender_EventScript_LinkBlenderNoBerries:
	msgbox BerryBlender_Text_NoBerriesLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_TryDoLinkBlender:
	call Common_EventScript_SaveGame
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_CancelLinkBlender
	specialvar VAR_RESULT, IsWirelessAdapterConnected
	goto_if_eq VAR_RESULT, TRUE, BerryBlender_EventScript_StartDecideLinkLeader
	message BerryBlender_Text_SearchingForFriends
	waitmessage
	special TryBerryBlenderLinkup
	goto_if_eq VAR_RESULT, LINKUP_SUCCESS, BerryBlender_EventScript_SpawnLinkPartners
	goto_if_eq VAR_RESULT, LINKUP_SOMEONE_NOT_READY, BerryBlender_EventScript_CloseLinkNotReady
	goto_if_eq VAR_RESULT, LINKUP_DIFF_SELECTIONS, BerryBlender_EventScript_CloseLinkDifferentSelections
	goto_if_eq VAR_RESULT, LINKUP_FAILED, BerryBlender_EventScript_CloseLink
	goto_if_eq VAR_RESULT, LINKUP_CONNECTION_ERROR, BerryBlender_EventScript_LinkError
	end

BerryBlender_EventScript_TwoPlayerLink:
	msgbox BerryBlender_Text_Player1Arrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_ThreePlayerLink:
	msgbox BerryBlender_Text_Player1And2Arrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_FourPlayerLink:
	msgbox BerryBlender_Text_AllPlayersArrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_DoLinkBerryBlending:
	setvar VAR_0x8004, 0  @ number of opponents, 0 indicates Link
	fadescreen FADE_TO_BLACK
	removeobject 240 @ Unclear where these local IDs come from,
	removeobject 239 @ but presumably they'd be the 4 link players
	removeobject 238
	removeobject 237
	special DoBerryBlending
	releaseall
	end

BerryBlender_EventScript_CancelLinkBlender:
	releaseall
	end

BerryBlender_EventScript_LinkBlenderCaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFullLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_LinkBlenderNoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCaseLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLinkNotReady:
	special CloseLink
	msgbox Text_SomeoneIsNotReadyToLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLinkDifferentSelections:
	special CloseLink
	msgbox Text_PlayersMadeDifferentSelections, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLink:
	special CloseLink
	msgbox gText_PokeblockLinkCanceled, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_LinkError:
	special CloseLink
	msgbox Text_LinkErrorPleaseReset, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_SpawnLinkPartners:
	fadescreen FADE_TO_BLACK
	specialvar VAR_RESULT, GetLinkPartnerNames
	copyvar VAR_0x8008, VAR_RESULT
	copyvar VAR_0x8004, VAR_0x8008
	special SpawnLinkPartnerObjectEvent
	goto BerryBlender_EventScript_LinkPlayersArrived
	end

BerryBlender_EventScript_LinkPlayersArrived:
	fadescreen FADE_FROM_BLACK
	switch VAR_0x8008
	case 2, BerryBlender_EventScript_TwoPlayerLink
	case 3, BerryBlender_EventScript_ThreePlayerLink
	case 4, BerryBlender_EventScript_FourPlayerLink
	end

BerryBlender_EventScript_StartDecideLinkLeader:
	setvar VAR_0x8004, LINK_GROUP_BERRY_BLENDER
	goto BerryBlender_EventScript_DecideLinkLeader
	end

BerryBlender_EventScript_DecideLinkLeader:
	message LilycoveCity_ContestLobby_Text_PleaseDecideLinkLeader
	waitmessage
	multichoice 16, 6, MULTI_LINK_LEADER, FALSE
	switch VAR_RESULT
	case 0, BerryBlender_EventScript_TryJoinGroup
	case 1, BerryBlender_EventScript_TryLeadGroup
	case 2, BerryBlender_EventScript_CloseLink
	case MULTI_B_PRESSED, BerryBlender_EventScript_CloseLink
	end

BerryBlender_EventScript_TryLeadGroup:
	call BerryBlender_EventScript_TryBecomeLinkLeader
	goto_if_eq VAR_RESULT, LINKUP_SUCCESS, BerryBlender_EventScript_LinkLeaderDecided
	goto_if_eq VAR_RESULT, LINKUP_FAILED, BerryBlender_EventScript_DecideLinkLeader
	goto_if_eq VAR_RESULT, LINKUP_RETRY_ROLE_ASSIGN, BerryBlender_EventScript_TryLeadGroup
	release
	end

BerryBlender_EventScript_TryJoinGroup:
	call BerryBlender_EventScript_TryJoinLinkGroup
	goto_if_eq VAR_RESULT, LINKUP_SUCCESS, BerryBlender_EventScript_LinkLeaderDecided
	goto_if_eq VAR_RESULT, LINKUP_FAILED, BerryBlender_EventScript_DecideLinkLeader
	goto_if_eq VAR_RESULT, LINKUP_RETRY_ROLE_ASSIGN, BerryBlender_EventScript_TryJoinGroup
	release
	end

BerryBlender_EventScript_TryBecomeLinkLeader:
	special TryBecomeLinkLeader
	return

BerryBlender_EventScript_TryJoinLinkGroup:
	special TryJoinLinkGroup
	return

BerryBlender_EventScript_LinkLeaderDecided:
	goto BerryBlender_EventScript_SpawnLinkPartners
	end

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global BerryBlender_Text_WantToMakePokeblocks
	.global BerryBlender_Text_Excellent
	.global BerryBlender_Text_MadeOldTimerSad
	.global BerryBlender_Text_KnowHowToMakePokeblocks
	.global BerryBlender_Text_LetsBerryBlender
	.global BerryBlender_Text_ExplainBerryBlending
	.global BerryBlender_Text_DontHaveAnyBerries
	.global BerryBlender_Text_CanHaveOneOfMyBerries
	.global BerryBlender_Text_DontHaveAnyBerriesToSpare
	.global BerryBlender_Text_PokeblockCaseIsFull
	.global BerryBlender_Text_DontHavePokeblockCase
	.global BerryBlender_Text_LetsGetBlendingAlready
	.global BerryBlender_Text_WhatKindOfPokeblockWillIGet
	.global BerryBlender_Text_WantToBlendPokeblocksWithUs
	.global BerryBlender_Text_Okay
	.global BerryBlender_Text_ThatsTooBad
	.global BerryBlender_Text_KnowHowToMakePokeblocks2
	.global BerryBlender_Text_LetsBerryBlender2
	.global BerryBlender_Text_ExplainBerryBlending2
	.global BerryBlender_Text_DontHaveAnyBerries2
	.global BerryBlender_Text_PokeblockCaseIsFull2
	.global BerryBlender_Text_DontHavePokeblockCase2
	.global BerryBlender_Text_MakePokeblocksWithOurGroup
	.global BerryBlender_Text_OhDear
	.global BerryBlender_Text_LeftUsInShock
	.global BerryBlender_Text_KnowHowToMakePokeblocks3
	.global BerryBlender_Text_LetsBerryBlender3
	.global BerryBlender_Text_ExplainBerryBlending3
	.global BerryBlender_Text_DontHaveAnyBerries3
	.global BerryBlender_Text_PokeblockCaseIsFull3
	.global BerryBlender_Text_DontHavePokeblockCase3
	.global BerryBlender_Text_SetNewBlenderRecord
	.global BerryBlender_Text_LookGoodAtBlendingJoinUs
	.global BerryBlender_Text_MakeDeliciousPokeblocks
	.global BerryBlender_Text_SaveGameBeforeBerryBlenderLink
	.global BerryBlender_Text_SearchingForFriends
	.global BerryBlender_Text_Player1Arrived
	.global BerryBlender_Text_Player1And2Arrived
	.global BerryBlender_Text_AllPlayersArrived
	.global BerryBlender_Text_NoBerriesLink
	.global BerryBlender_Text_PokeblockCaseIsFullLink
	.global BerryBlender_Text_DontHavePokeblockCaseLink
	.global BerryBlender_Text_LoveMakingPokeblocks
	.global BerryBlender_Text_MakePokeblocksUsingBerryBlender
	.global BerryBlender_Text_DontHaveAnyBerriesHaveOne
	.global BerryBlender_Text_UseItToMakePokeblocksTogether
	.global BerryBlender_Text_DontHaveAnyBerriesNoneToSpare
@ END GENERATED LOCALIZATION EXPORTS
