PetalburgCity_House1_MapScripts::
	.byte 0

PetalburgCity_House1_EventScript_Man::
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

PetalburgCity_House1_EventScript_Woman::
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

PetalburgCity_House1_Text_TravelingIsWonderful:
	.string "Du hành thật tuyệt!\p"
	.string "Khi còn trẻ, tôi từng ngao du khắp biển\n"
	.string "cả và núi non!$"

PetalburgCity_House1_Text_GoOnAdventure:
	.string "Thở dài...\p"
	.string "Giá mà tôi có thể phiêu lưu cùng vài\n"
	.string "POKéMON...\p"
	.string "Bò qua những bãi cỏ ẩm ướt... Leo lên\n"
	.string "những ngọn núi đá gập ghềnh...\p"
	.string "Vượt qua biển động dữ dội... Lang thang\n"
	.string "trong những hang động tối tăm...\p"
	.string "Và đôi khi còn hơi nhớ nhà...\p"
	.string "Du hành hẳn phải tuyệt vời lắm!$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global PetalburgCity_House1_Text_TravelingIsWonderful
	.global PetalburgCity_House1_Text_GoOnAdventure
@ END GENERATED LOCALIZATION EXPORTS
