AbandonedShip_Rooms2_B1F_MapScripts::
	.byte 0

AbandonedShip_Rooms2_B1F_EventScript_Camper::
	msgbox AbandonedShip_Rooms2_B1F_Text_PerfectPlaceToGoExploring, MSGBOX_NPC
	end

AbandonedShip_Rooms2_B1F_Text_PerfectPlaceToGoExploring:
	.string "Đây là nơi hoàn hảo để thám hiểm! Ở đây\n"
	.string "thú vị thật!\p"
	.string "Tôi cá là trên tàu có những kho báu\n"
	.string "tuyệt vời.$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global AbandonedShip_Rooms2_B1F_Text_PerfectPlaceToGoExploring
@ END GENERATED LOCALIZATION EXPORTS
