SootopolisCity_Gym_B1F_MapScripts::
	.byte 0

SootopolisCity_Gym_B1F_EventScript_Andrea::
	trainerbattle_single TRAINER_ANDREA, SootopolisCity_Gym_B1F_Text_AndreaIntro, SootopolisCity_Gym_B1F_Text_AndreaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_AndreaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Crissy::
	trainerbattle_single TRAINER_CRISSY, SootopolisCity_Gym_B1F_Text_CrissyIntro, SootopolisCity_Gym_B1F_Text_CrissyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_CrissyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Brianna::
	trainerbattle_single TRAINER_BRIANNA, SootopolisCity_Gym_B1F_Text_BriannaIntro, SootopolisCity_Gym_B1F_Text_BriannaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BriannaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Connie::
	trainerbattle_single TRAINER_CONNIE, SootopolisCity_Gym_B1F_Text_ConnieIntro, SootopolisCity_Gym_B1F_Text_ConnieDefeat
	msgbox SootopolisCity_Gym_B1F_Text_ConniePostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Bridget::
	trainerbattle_single TRAINER_BRIDGET, SootopolisCity_Gym_B1F_Text_BridgetIntro, SootopolisCity_Gym_B1F_Text_BridgetDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BridgetPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Olivia::
	trainerbattle_single TRAINER_OLIVIA, SootopolisCity_Gym_B1F_Text_OliviaIntro, SootopolisCity_Gym_B1F_Text_OliviaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_OliviaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Tiffany::
	trainerbattle_single TRAINER_TIFFANY, SootopolisCity_Gym_B1F_Text_TiffanyIntro, SootopolisCity_Gym_B1F_Text_TiffanyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_TiffanyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Bethany::
	trainerbattle_single TRAINER_BETHANY, SootopolisCity_Gym_B1F_Text_BethanyIntro, SootopolisCity_Gym_B1F_Text_BethanyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BethanyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Annika::
	trainerbattle_single TRAINER_ANNIKA, SootopolisCity_Gym_B1F_Text_AnnikaIntro, SootopolisCity_Gym_B1F_Text_AnnikaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_AnnikaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Daphne::
	trainerbattle_single TRAINER_DAPHNE, SootopolisCity_Gym_B1F_Text_DaphneIntro, SootopolisCity_Gym_B1F_Text_DaphneDefeat
	msgbox SootopolisCity_Gym_B1F_Text_DaphnePostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_Text_AndreaIntro:
	.string "Tôi sẽ cho bạn thấy những kỹ thuật\n"
	.string "tuyệt đỉnh mà tôi học được từ LEADER\l"
	.string "JUAN!$"

SootopolisCity_Gym_B1F_Text_AndreaDefeat:
	.string "Xin hãy tha thứ cho tôi, JUAN...$"

SootopolisCity_Gym_B1F_Text_AndreaPostBattle:
	.string "Hãy xem chuyện gì xảy ra nếu bạn làm\n"
	.string "nứt tất cả các ô sàn.$"

SootopolisCity_Gym_B1F_Text_CrissyIntro:
	.string "Bạn đã vất vả tới tận đây, nhưng sẽ\n"
	.string "không được gặp JUAN đâu.\p"
	.string "Ít nhất là nếu thua tôi!$"

SootopolisCity_Gym_B1F_Text_CrissyDefeat:
	.string "Bạn mạnh thật! Vẻ ngoài dễ thương của\n"
	.string "bạn đã đánh lừa tôi!$"

SootopolisCity_Gym_B1F_Text_CrissyPostBattle:
	.string "Có lẽ bạn đủ giỏi để không bị JUAN hạ\n"
	.string "gục chỉ bằng một đòn.$"

SootopolisCity_Gym_B1F_Text_DaphneIntro:
	.string "Cảnh tượng JUAN điều khiển một trận\n"
	.string "đấu...\p"
	.string "Vẻ đẹp ấy đã thôi thúc tôi trở thành\n"
	.string "HLV.$"

SootopolisCity_Gym_B1F_Text_DaphneDefeat:
	.string "Bạn đã chiến đấu đẹp mắt hơn tất cả\n"
	.string "những gì tôi có thể thể hiện...$"

SootopolisCity_Gym_B1F_Text_DaphnePostBattle:
	.string "Vẻ duyên dáng bạn đem vào trận đấu\n"
	.string "thật tuyệt vời.\p"
	.string "Ôi... Tôi thật may mắn khi tìm thấy\n"
	.string "POKéMON.$"

SootopolisCity_Gym_B1F_Text_ConnieIntro:
	.string "Để tôi dạy bạn biết các trận đấu có thể\n"
	.string "khắc nghiệt đến mức nào.$"

SootopolisCity_Gym_B1F_Text_ConnieDefeat:
	.string "Ồ. Bạn mạnh thật.$"

SootopolisCity_Gym_B1F_Text_ConniePostBattle:
	.string "Tôi sẽ mách bạn một điều hữu ích.\p"
	.string "Nếu muốn tới chỗ JUAN, bạn cần bước\n"
	.string "lên mỗi ô sàn đúng một lần.$"

SootopolisCity_Gym_B1F_Text_BridgetIntro:
	.string "POKéMON GYM cấp cao nhất vùng HOENN...\p"
	.string "Chính là SOOTOPOLIS GYM.$"

SootopolisCity_Gym_B1F_Text_BridgetDefeat:
	.string "Trình độ của bạn cao thật đấy!$"

SootopolisCity_Gym_B1F_Text_BridgetPostBattle:
	.string "Thay vì mãn nguyện vì được ở trong\n"
	.string "một GYM mạnh, tôi nghĩ tập luyện ở\l"
	.string "những nơi khác sẽ giúp mình mạnh hơn.\l"
	.string "Mà trên hết, có vẻ còn vui hơn nhiều.$"

SootopolisCity_Gym_B1F_Text_OliviaIntro:
	.string "Tôi rèn luyện POKéMON cùng JUAN.\p"
	.string "Đừng nghĩ tôi dễ bị bắt nạt.$"

SootopolisCity_Gym_B1F_Text_OliviaDefeat:
	.string "Tôi đã thua...$"

SootopolisCity_Gym_B1F_Text_OliviaPostBattle:
	.string "Tôi nghĩ bạn có tiềm năng. Sao không ở\n"
	.string "lại tập luyện cùng chúng tôi?$"

SootopolisCity_Gym_B1F_Text_TiffanyIntro:
	.string "Lướt duyên dáng trên băng mà không\n"
	.string "cắt ngang bất kỳ đường nào...\p"
	.string "Một HLV thực hiện được màn trình\n"
	.string "diễn ấy hẳn sẽ đẹp đẽ và thanh lịch vô\l"
	.string "cùng!$"

SootopolisCity_Gym_B1F_Text_TiffanyDefeat:
	.string "Gì cơ, xin lỗi nhé?!$"

SootopolisCity_Gym_B1F_Text_TiffanyPostBattle:
	.string "Điều này quá hiển nhiên, nhưng sức\n"
	.string "mạnh của một HLV chẳng liên quan\l"
	.string "gì đến tuổi tác cả.$"

SootopolisCity_Gym_B1F_Text_BethanyIntro:
	.string "Khi ở bên POKéMON của mình, thời gian\n"
	.string "trôi nhanh đến mức chưa kịp thốt lên\l"
	.string "'Ối!' đã hết rồi.$"

SootopolisCity_Gym_B1F_Text_BethanyDefeat:
	.string "Ối!$"

SootopolisCity_Gym_B1F_Text_BethanyPostBattle:
	.string "Ước gì tôi có thể quên những chuyện vô\n"
	.string "vọng trước cả khi kịp thốt lên 'Ối!'.$"

SootopolisCity_Gym_B1F_Text_AnnikaIntro:
	.string "Nếu bạn muốn, tôi có thể đấu bằng những\n"
	.string "POKéMON cực kỳ quý hiếm.$"

SootopolisCity_Gym_B1F_Text_AnnikaDefeat:
	.string "Ồ, thế nào? Bạn đã ngắm kỹ POKéMON của\n"
	.string "tôi chưa?$"

SootopolisCity_Gym_B1F_Text_AnnikaPostBattle:
	.string "Tôi tới GYM này vì JUAN đã khen những\n"
	.string "POKéMON đáng yêu của tôi.\p"
	.string "Ôi, giá mà tôi gặp JUAN từ nhiều năm\n"
	.string "trước, khi mình còn trẻ...$"

SootopolisCity_Gym_B1F_Text_BriannaIntro:
	.string "Khúc khích... Vẻ mặt nghiêm nghị của bạn\n"
	.string "thật quyến rũ.$"

SootopolisCity_Gym_B1F_Text_BriannaDefeat:
	.string "Ôi trời. Tôi đã quá nương tay với bạn\n"
	.string "rồi.$"

SootopolisCity_Gym_B1F_Text_BriannaPostBattle:
	.string "Tôi chắc bạn chẳng thể chạm nổi một\n"
	.string "ngón tay vào JUAN đâu. Khúc khích...$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global SootopolisCity_Gym_B1F_Text_AndreaIntro
	.global SootopolisCity_Gym_B1F_Text_AndreaDefeat
	.global SootopolisCity_Gym_B1F_Text_AndreaPostBattle
	.global SootopolisCity_Gym_B1F_Text_CrissyIntro
	.global SootopolisCity_Gym_B1F_Text_CrissyDefeat
	.global SootopolisCity_Gym_B1F_Text_CrissyPostBattle
	.global SootopolisCity_Gym_B1F_Text_DaphneIntro
	.global SootopolisCity_Gym_B1F_Text_DaphneDefeat
	.global SootopolisCity_Gym_B1F_Text_DaphnePostBattle
	.global SootopolisCity_Gym_B1F_Text_ConnieIntro
	.global SootopolisCity_Gym_B1F_Text_ConnieDefeat
	.global SootopolisCity_Gym_B1F_Text_ConniePostBattle
	.global SootopolisCity_Gym_B1F_Text_BridgetIntro
	.global SootopolisCity_Gym_B1F_Text_BridgetDefeat
	.global SootopolisCity_Gym_B1F_Text_BridgetPostBattle
	.global SootopolisCity_Gym_B1F_Text_OliviaIntro
	.global SootopolisCity_Gym_B1F_Text_OliviaDefeat
	.global SootopolisCity_Gym_B1F_Text_OliviaPostBattle
	.global SootopolisCity_Gym_B1F_Text_TiffanyIntro
	.global SootopolisCity_Gym_B1F_Text_TiffanyDefeat
	.global SootopolisCity_Gym_B1F_Text_TiffanyPostBattle
	.global SootopolisCity_Gym_B1F_Text_BethanyIntro
	.global SootopolisCity_Gym_B1F_Text_BethanyDefeat
	.global SootopolisCity_Gym_B1F_Text_BethanyPostBattle
	.global SootopolisCity_Gym_B1F_Text_AnnikaIntro
	.global SootopolisCity_Gym_B1F_Text_AnnikaDefeat
	.global SootopolisCity_Gym_B1F_Text_AnnikaPostBattle
	.global SootopolisCity_Gym_B1F_Text_BriannaIntro
	.global SootopolisCity_Gym_B1F_Text_BriannaDefeat
	.global SootopolisCity_Gym_B1F_Text_BriannaPostBattle
@ END GENERATED LOCALIZATION EXPORTS
