LilycoveCity_House4_MapScripts::
	.byte 0

LilycoveCity_House4_EventScript_Man1::
	msgbox LilycoveCity_House4_Text_MysteriesAtBottomOfSea, MSGBOX_NPC
	end

LilycoveCity_House4_EventScript_Man2::
	msgbox LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis, MSGBOX_NPC
	end

LilycoveCity_House4_Text_MysteriesAtBottomOfSea:
	.string "Những bí ẩn lớn nhất của hành tinh này\n"
	.string "nằm dưới đáy biển.\p"
	.string "Có người nói thế, nhưng tôi cũng không\n"
	.string "biết...$"

LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis:
	.string "Có một rãnh biển sâu dưới nước nằm\n"
	.string "giữa MOSSDEEP và SOOTOPOLIS.\p"
	.string "Dù sao thì có người đã kể tôi như vậy.$"

@ BEGIN GENERATED LOCALIZATION EXPORTS
	.global LilycoveCity_House4_Text_MysteriesAtBottomOfSea
	.global LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis
@ END GENERATED LOCALIZATION EXPORTS
